### ISSUE TITLE
Build Win32 wrappers against prebuilt core

### ISSUE THREAD

**Issue by fealebenpae** [realm/realm-dotnet#1008]
Now that we have a prebuilt package of core for Win32 we should change the wrappers Visual Studio project to download and build against that instead of a local checkout of realm-core.

**Comment by AndyDentFree** [comment]
When you make this change remember to update `wrappers/readme.md` to say how it works now ;-)

**Comment by fealebenpae** [comment]
The vcxproj should automatically pull down the core tarball from our CDN. There would be no manual steps other than building in Visual Studio.
