### ISSUE TITLE
Query of one-to-many IList<T>

### ISSUE THREAD

**Issue by DrifterApps** [realm/realm-dotnet#1030]
I have 2 classes:

public class Invoice : RealmObject
{
   public int Id;
   public string Name { get; set; }
   public IList<Product> Products { get; }
}

public class Product : RealmObject
{
   public int Id { get; set; }
   public string Name { get; set; }
   public double Price { get; set; }
}

I want the ability to do a query where I can list all invoices containing a specific product.

I would code my LINQ query as such but I get an unsupported exception:

realm.All<Invoice>().Where(i => i.Products.Any(p => p.Name == "product 1"));

I can do it this way but then getting the invoice count for each product takes way too long.

realm.All<Invoice>().ToList().Where(i => i.Products.Any(p => p.Name == "product 1"));

I've tried anything I could think of but it just doesn't work.

Realm version(s): 0.80

Xamarin/Visual Studio version: Latest

Which operating system version and device: Mac OS X

**Comment by nirinchev** [comment]
With the latest version (0.81.0), we added support for [inverse relationships](https://realm.io/docs/xamarin/latest/#inverse-relationships). So you can modify your model slightly like:
```csharp
public class Product : RealmObject
{
    /* other properties */
    [Backlink(nameof(Invoice.Products))]
    public IQueryable<Invoice> RelatedInvoices { get; }
}
```

and then you can query the invoices like:

```csharp
var product = realm.All<Product>().FirstOrDefault(p => p.Name == "product 1");
var invoices = product.RelatedInvoices;
```

**Comment by DrifterApps** [comment]
Great news, can't wait to try it out!!!

**Comment by nirinchev** [comment]
It's already live, so you don't have to wait 😋

**Comment by DrifterApps** [comment]
Hi,

I did get it to work on a simple class and it works quite well, but the same doesn't seem to work on a class more complex with a few properties with custom setter and getter crashes.

As soon as I access the Backlink to a persisted property, the application crashes with this Exception:

`System.BadImageFormatException: Method is a pinvoke or open generic`

The log gives me no other information. The whole thing is strange. 

Unless you heard other wise and have some info for me, it would be appreciated. But for now with no info in the logs, I will treat this as my bug.

Thanks!!

**Comment by nirinchev** [comment]
Can you share your models with us so we can try to see if it's something you're doing wrong or some edge case we haven't covered? If you prefer to share them privately, email us at help@realm.io and we'll take a look. Thanks!

**Comment by DrifterApps** [comment]
Hi,

I was trying to reproduce the problem, with test project, before sending you my classes and I couldn't. But I finally managed to reproduce the crash.

 My models Invoice and Product, defined exactly as above, are defined in a PCL Library. If they are defined in my Android App project, then I have no issue. As soon as I moved the models to my PCL Library, I got the BadImageFormatException.

If you need, I can send you my test project.

**Comment by AndyDentFree** [comment]
@DrifterApps yes, **please** send your test project. I you are not willing to attach a zip of it here, email it to help@realm.io

>As soon as I moved the models to my PCL Library, I got the BadImageFormatException.
I'm wondering if something is going wrong in the Fody weaving in that circumstance, or if we have a minor discrepancy in our PCL interfaces, although I would have thought that would cause linker errors. With your test project, we can break into the weaver during compilation and confirm if that's where it is going wrong.

**Comment by DrifterApps** [comment]
[TestRealm.zip](https://github.com/realm/realm-dotnet/files/662809/TestRealm.zip)
Here you go!

**Comment by sushihangover** [comment]
I just came across the same issue, it crashes the soft debugger/Mono runtime if you try to debug it.

```
[mono-rt] Stacktrace:
[mono-rt] 
[mono-rt]   at <unknown> <0xffffffff>
[mono-rt]   at TestRealm.MainActivity.OnCreate (Android.OS.Bundle) [0x0010f] in /Users/sushi/RealmObjectViaLibrary/TestRealm/MainActivity.cs:57
[mono-rt]   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (intptr,intptr,intptr) [0x00011] in /Users/builder/data/lanes/4009/72366f70/source/monodroid/src/Mono.Android/platforms/android-25/src/generated/Android.App.Activity.cs:2550
[mono-rt]   at (wrapper dynamic-method) object.30ef17fc-a561-4129-b8cb-215210df2379 (intptr,intptr,intptr) <IL 0x00017, 0x00027>
[mono-rt]   at (wrapper native-to-managed) object.30ef17fc-a561-4129-b8cb-215210df2379 (intptr,intptr,intptr) <IL 0x00022, 0x0009f>
```

```
2016-12-19 22:31:44.868 RealmWLib[71561:26312217] critical: Stacktrace:

2016-12-19 22:31:44.869 RealmWLib[71561:26312217] critical:   at <unknown> <0xffffffff>
2016-12-19 22:31:44.869 RealmWLib[71561:26312217] critical:   at RealmWLib.ViewController.ViewDidLoad () [0x000d4] in /Users/sushi/RealmObjectViaLibrary/TestRealm/RealmWLib/ViewController.cs:48
2016-12-19 22:31:44.870 RealmWLib[71561:26312217] critical:   at (wrapper runtime-invoke) object.runtime_invoke_void__this__ (object,intptr,intptr,intptr) <IL 0x0004f, 0x00304>
2016-12-19 22:31:44.870 RealmWLib[71561:26312217] critical:   at <unknown> <0xffffffff>
2016-12-19 22:31:44.870 RealmWLib[71561:26312217] critical:   at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain (int,string[],intptr,intptr) <IL 0x0005c, 0x0037b>
2016-12-19 22:31:44.870 RealmWLib[71561:26312217] critical:   at UIKit.UIApplication.Main (string[],intptr,intptr) [0x00005] in /Users/builder/data/lanes/3985/b4a43820/source/xamarin-macios/src/UIKit/UIApplication.cs:79
2016-12-19 22:31:44.870 RealmWLib[71561:26312217] critical:   at UIKit.UIApplication.Main (string[],string,string) [0x00038] in /Users/builder/data/lanes/3985/b4a43820/source/xamarin-macios/src/UIKit/UIApplication.cs:63
2016-12-19 22:31:44.871 RealmWLib[71561:26312217] critical:   at RealmWLib.Application.Main (string[]) [0x00008] in /Users/sushi/RealmObjectViaLibrary/TestRealm/RealmWLib/Main.cs:12
2016-12-19 22:31:44.871 RealmWLib[71561:26312217] critical:   at (wrapper runtime-invoke) <Module>.runtime_invoke_void_object (object,intptr,intptr,intptr) <IL 0x00051, 0x0030a>
2016-12-19 22:31:44.871 RealmWLib[71561:26312217] critical: 
Native stacktrace:

2016-12-19 22:31:44.872 RealmWLib[71561:26312217] critical: 
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
```

**Comment by nirinchev** [comment]
I was able to reproduce it, thank you both very much for your help!

**Comment by nirinchev** [comment]
I've created a separate issue to track the PCL crash bug. I'm closing this one as it seems backlinks are what you needed (probably not crashing backlinks, but still, backlinks 😸). If you have further questions or something else is not working (apart from the PCL case), feel free to reopen!
