### ISSUE TITLE
0.81 crash, NotifyPropertyChanged?

### ISSUE THREAD

**Issue by eyadon** [realm/realm-dotnet#1036]
Updating from 0.80 to 0.81

12-16 11:23:52.791 I/MonoDroid(18324): UNHANDLED EXCEPTION:
12-16 11:23:52.801 I/MonoDroid(18324): System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Realm accessed from incorrect thread.
12-16 11:23:52.801 I/MonoDroid(18324):   at Realms.NativeException.ThrowIfNecessary (System.Func`2[T,TResult] overrider) [0x00014] in <03f96af2858c46cfb7cbbc741b866d11>:0 
12-16 11:23:52.801 I/MonoDroid(18324):   at Realms.MarshalHelpers.GetString (Realms.MarshalHelpers+NativeStringGetter getter) [0x0002c] in <03f96af2858c46cfb7cbbc741b866d11>:0 
12-16 11:23:52.801 I/MonoDroid(18324):   at Realms.ObjectHandle.GetString (System.IntPtr propertyIndex) [0x00014] in <03f96af2858c46cfb7cbbc741b866d11>:0 
12-16 11:23:52.801 I/MonoDroid(18324):   at Realms.RealmObject.GetStringValue (System.String propertyName) [0x00017] in <03f96af2858c46cfb7cbbc741b866d11>:0 
12-16 11:23:52.801 I/MonoDroid(18324):   at RealmDAL.Models.RealmDeviceInfo.get_Address () [0x00006] in <9fab3fde3fce488c8001b7af9cf38adb>:0 
12-16 11:23:52.801 I/MonoDroid(18324):   at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
12-16 11:23:52.801 I/MonoDroid(18324):   at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00038] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:305 
12-16 11:23:52.801 I/MonoDroid(18324):    --- End of inner exception stack trace ---
12-16 11:23:52.801 I/MonoDroid(18324):   at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00050] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:313 
12-16 11:23:52.801 I/MonoDroid(18324):   at Realms.WovenGetterMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00018] in <03f96af2858c46cfb7cbbc741b866d11>:0 
12-16 11:23:52.801 I/MonoDroid(18324):   at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/reflection/methodbase.cs:229 
12-16 11:23:52.801 I/MonoDroid(18324):   at Xamarin.Forms.BindingExpression+BindingExpressionPart.TryGetValue (System.Object source, System.Object& value) [0x00052] in <b0fc14d4e5b04749b7241d1235a68329>:0 
12-16 11:23:52.801 I/MonoDroid(18324):   at Xamarin.Forms.BindingExpression.ApplyCore (System.Object sourceObject, Xamarin.Forms.BindableObject target, Xamarin.Forms.BindableProperty property, System.Boolean fromTarget) [0x001a1] in <b0fc14d4e5b04749b7241d1235a68329>:0 
12-16 11:23:52.801 I/MonoDroid(18324):   at Xamarin.Forms.BindingExpression.Apply (System.Boolean fromTarget) [0x0003e] in <b0fc14d4e5b04749b7241d1235a68329>:0 
12-16 11:23:52.801 I/MonoDroid(18324):   at Xamarin.Forms.BindingExpression+BindingExpressionPart.<PropertyChanged>b__44_0 () [0x00000] in <b0fc14d4e5b04749b7241d1235a68329>:0 
12-16 11:23:52.801 I/MonoDroid(18324):   at Java.Lang.Thread+RunnableImplementor.Run () [0x0000b] in /Users/builder/data/lanes/3511/ce955cc0/source/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:36 
12-16 11:23:52.801 I/MonoDroid(18324):   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in /Users/builder/data/lanes/3511/ce955cc0/source/monodroid/src/Mono.Android/platforms/android-24/src/generated/Java.Lang.IRunnable.cs:81 
12-16 11:23:52.801 I/MonoDroid(18324):   at (wrapper dynamic-method) System.Object:16954a77-089e-4f56-b92c-9cd1fbac6460 (intptr,intptr)

#### Steps & Code to Reproduce

Display bound list of unmanaged objects, user selects object, loading screen appears, various processing occurs, event causes object to become managed -- stepping through the code, it crashes upon committing the transaction.  

#### Version of Realm and tooling
Realm version(s): 0.81.0

Xamarin/Visual Studio version: VS Enterprise 2015 Update 3, Xamarin 4.2.1.64

Which operating system version and device: Windows 7, Android 6.0 Samsung S7

**Comment by nirinchev** [comment]
Sounds like you're managing the object on a non-UI thread, which binds it to that thread, then it raises `PropertyChanged`, which causes the Forms binding to trigger, which invokes a property getter on the UI thread, causing the exception you're seeing. As a temporary workaround, you could invoke `Realm.Add` in a `Device.BeginInvokeOnMainThread. A more robust solution would be to prefer binding to managed objects and modifying a different instance of the same object on the background thread, e.g.:

```csharp
public MyObject BoundObject { get; }
        
public void UpdatingCallback(int objectId)
{
    using (var realm = Realm.GetInstance())
    {
        var objectToUpdate = realm.Find<MyObject>(objectId);
        /* perform update */
    }
}
```

If you *absolutely* must manage an unmanaged object that has an active data binding on the UI thread, you could do something like:

```csharp
public MyObject CurrentObject { get; } // Initially unmanaged

public async Task ManageCurrentObject()
{
    var objectId = CurrentObject.Id;
    var tcs = new TaskCompletionSource<object>();
    Device.InvokeOnMainThread(() =>
    {
        using (var mainRealm = Realm.GetInstance())
        {
            mainRealm(CurrentObject); // Managed on UI thread
        }
        tcs.SetResult(null);
    }
    await tcs.Task;
    using (var backgroundRealm = Realm.GetInstance())
    {
        var backgroundObject = backgroundRealm.Find<MyObject>(objectId);
        /* update any properties */
    }
}
```

**Comment by eyadon** [comment]
Thanks for the suggestions.
