### ISSUE TITLE
Consider making Realm methods open and commit a transaction automatically

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-dotnet#1043]
To me it seems unnecessarily cumbersome to have to write code like:
```csharp
MyObject myObject = null;
_realm.Write(() =>
{
    myObject = _realm.Add(new MyObject
    {
        Id = 1;
    };
});
```

I suggest that we make all state mutating instance methods create and commit a transaction if one is not already opened (similarly to our data binding object setters).

Then, people will only need to use `Write` or `BeginWrite` when they want to rollback multiple changes in case of an exception or when they want to update `RealmObject`s properties. Does that make sense or am I missing something?

**Comment by kristiandupont** [comment]
That does indeed seem tempting but it also seems like something we might want to discuss with the other SDK's so we not converging too much.

**Comment by bmunkholm** [comment]
There are a number of issues with that which we have previously discussed and that I have likely forgotten most about. But a few are:
- People will Add() in a loop not realizing the overheads of multiple transaction, so it leads to poor performance
- Having multiple ways to make write transactions - some are implicit, others are not?
- what am I forgetting?

**Comment by nirinchev** [comment]
After a brief discussion, we all agree that the negatives of this approach outweigh the positives. While it will be a more convenient in some cases, the potential for misuse is too high.
