### ISSUE TITLE
AllLoggedIn should return dictionary

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#1054]
The current Cocoa `RLMSyncUsers.allUsers` returns a `Dictionary<identity_String, User>` and Java are going to be implementing that instead of a straight collection. We should match.

**Comment by nirinchev** [comment]
I disagree - there's nothing beneficial about returning a dictionary for .NET users judging by @cmelchior's comments on Slack. It will be a marshalling pain for us and
```csharp
var user = User.All["some-id"];
```
isn't that much better than
```csharp
var user = User.All.Single(u => u.Id == "some-id");
```

**Comment by AndyDentFree** [comment]
Unless we get the others to change, going our own way here violates #966 validating our API aligns with others.

**Comment by nirinchev** [comment]
I believe the API should be what feels most natural for the language. Cocoa and Java don't have LINQ, so a dictionary might make sense for them, but I don't see how it's beneficial for the .NET binding. After all, we should align our API while keeping it consistent with the platform we're developing for. @kristiandupont @fealebenpae what's your opinion on that?

**Comment by fealebenpae** [comment]
I prefer the array over the dictionary. I don't see how a dictionary keyed on an opaque string like the user identity would be useful :/

But as @nirinchev said, with LINQ it's really easy to look up a user by its identity if you need it.

**Comment by nirinchev** [comment]
I don't think we should blindly align the return types. They have the same name, return a collection, so the fact one is a dictionary and the other array doesn't seem like a big deal, considering .NET has linq. @bmunkholm opinion?

**Comment by bmunkholm** [comment]
The main requirements for alignment are in this order:
1. Align functionality across SDKs
2. Align API types and naming across bindings, unless there is a clear standard/norm that dictates 3.
3. Design API's to be native/natural to the individual language and platform.

At the end of the day the API must behave and look native, but only do that when the alignment is clearly against the natural norm.
