### ISSUE TITLE
Backlink crash Sequence contains no elements

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#1058]
Private [bug report](https://secure.helpscout.net/conversation/295343625/8182/?folderId=907322) below. I have asked if they are defining the model in a PCL.

So I suppose when I create a "PortfolioModel" object and add "ProfitModel"
to Profits list of "PortfolioModel" object, "ProfitModel.Portfolio" should
autopopulate to current "PortfolioModel" object.
But when starting application with this schema, I get an error "Sequence
contains no elements" when first call Realm.GetInstance(). Removing
[BackLink] fixes the issue but in this case, there is no reversed
connection.

using the latest stable xamarin.forms and running iOS 10.2 on iPhone 6 simulator

**Comment by nirinchev** [comment]
Looking at their model, it seems they got the model declaration wrong. The backlink property should be `IQueryable`.
