### ISSUE TITLE
Sanity check for Authentication

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-dotnet#1073]
Write a few tests to ensure that logging in with each provider works.

**Comment by AndyDentFree** [comment]
Waiting for ROS to stabilise and especially the OS permissions issues.

**Comment by AndyDentFree** [comment]
I'm pushing this back to inactive until I have seen that this works with the native Java and Cocoa apps - it seems a low priority and I am not convinced the auth chain is working with current servers.

**Comment by nirinchev** [comment]
It's been manually sanity checked. ROS has their own set of auth tests to validate they don't regress.
