### ISSUE TITLE
Weave .NET Standard assemblies

### ISSUE THREAD

**Issue by hrach** [realm/realm-dotnet#1076]
#### Expected Results

Successful build.

#### Actual Results

Build fails in .netstandard 1.6 project. In 0.80 it was ok. Bug appears after upgrade. Clean & rebuild doesn't help.

```
1>    Fody: Fody (version 1.29.4.0) Executing
1>MSBUILD : error : Fody: An unhandled exception occurred:
1>MSBUILD : error : Exception:
1>MSBUILD : error : Object reference not set to an instance of an object.
1>MSBUILD : error : StackTrace:
1>MSBUILD : error :    at AssemblyResolverExtensions.LookupTypeDefinition(IAssemblyResolver resolver, String typeName, String[] assemblyNames)
1>MSBUILD : error :    at ModuleWeaver.Execute()
1>MSBUILD : error :    at lambda_method(Closure , Object )
1>MSBUILD : error :    at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 161
1>MSBUILD : error :    at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 82
1>MSBUILD : error : Source:
1>MSBUILD : error : RealmWeaver.Fody
1>MSBUILD : error : TargetSite:
1>MSBUILD : error : Mono.Cecil.TypeDefinition LookupTypeDefinition(Mono.Cecil.IAssemblyResolver, System.String, System.String[])
```
#### Steps & Code to Reproduce

0. Create .netstandard project.
1. Create entities
2. Try to build

#### Code Sample
Generally irelevant.
```csharp
	public class EventEntity : RealmObject
	{
		[PrimaryKey]
		public int Id { get; set; }
		public string Name { get; set; }
	}
```

#### Version of Realm and tooling
Realm version(s): 0.81
Xamarin/Visual Studio version: VS 2017 latest RC:
Which operating system version and device: WIN 10

**Comment by hrach** [comment]
I've just tried to reproduce from scratch - successfully.

1) Create .netstandard 1.6.
2) Add

to csproj
``` 
  <PropertyGroup>
    <NuGetTargetMoniker>.NETStandard,Version=v1.6</NuGetTargetMoniker>
  </PropertyGroup>
```

edit in project.json
```
  "frameworks": {
    "netstandard1.6": {
      "imports": "portable-net45+win8+wpa81+wp8"
    }
  }
```

3) Install realm. (Explicitly install latest version DotNetCross.Memory.Unsafe from nuget)
4) Create simple entity
5) Try to build.

**Comment by fealebenpae** [comment]
Hey @hrach,

We don't support `RealmObject` models in .NET Standard assemblies so something in the last update must have broken them (I'm assuming they worked previously).

We'll look into adding support for using Realm in a .NET Standard project, but in the mean time I can suggest using a PCL to hold your `RealmObject` classes as a workaround and reference it in your .NET Standard project.

**Comment by hrach** [comment]
I'm not sure if I described it correctly, the .netstandard project is "just" included in my Xamarin Android/iOS project. If I remember it correctly, somewhere I've read that including realm in such project is just "bait", the real implementation is done by a the main project.

**Comment by guiwaltricke** [comment]
i tried the 0.80 and didn't work with Xamarin.Forms with .NET STANDARD 1.6 or 1.1... anyone has a workaround?

**Comment by fealebenpae** [comment]
@hrach it's a two-pronged approach - the Realm runtime is included in the actual Xamarin.iOS or Xamarin.Android project (so the assembly reference is bait-and-switched), but the assembly that contains `RealmObject` classes is processed (or "woven") during compile-time to make the getters and setters of the properties on those classes call Realm APIs. This happens both for regular Xamarin projects and for PCLs. It's this assembly processing component that is broken with regards to .NET Standard projects.

@guiwaltricke could you please open a new issue and describe the problem you're having in a bit more detail?

**Comment by fealebenpae** [comment]
Hey @hrach,

I cannot add unit tests for this because Xamarin Studio in the Stable channel still doesn't support building .NET Standard libraries, but I believe #1117 should fix the regression in the assembly weaver when working with .NET Standard assemblies.
