### ISSUE TITLE
Remove Session.SyncConfiguration

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-dotnet#1078]
Looking at the code, it has a private setter, but that is never invoked. Am I missing something or is it an actual bug?

**Comment by fealebenpae** [comment]
That's actually something we should remove.

In .net we can't recreate the `SyncConfiguration` instance from the native `Session` object (because we're missing information about `SyncConfigurationBase` members).

**Comment by nirinchev** [comment]
I updated the title to reflect that.
