### ISSUE TITLE
Saving relations

### ISSUE THREAD

**Issue by roman-morev** [realm/realm-dotnet#1079]
Hi. 
I have models:
```
public class Personal : RealmObject
{
    [JsonProperty("id")]
    [PrimaryKey]
    public int Id { get; set; }
    [JsonProperty("name")]
    public string Name { get; set; }
    [JsonProperty("company")]
    public Company Company { get; set; }
}
public class Company : RealmObject
{
    [JsonProperty("name")]
    [PrimaryKey]
    public string Name { get; set; }
}
```

In my ViewModel I received JSON with Personals like this:
`[
  {
	"id":1,
	"name":"Personal 1",
	"company": {
		"name":"Company"
	}
  },
  {
	"id":2,
	"name":"Personal 2",
	"company": {
		"name":"Company"
	}
  }
]`

Then I saving my List of Personals
```
    var realm = Realm.GetInstance();
    foreach (var personal in list)
    {
        realm.Write(() => realm.Add(personal));   
    }
```

And i've got exception
```Realms.RealmDuplicatePrimaryKeyValueException: A class_Company object already exists with primary key property Name == 'Company'```

How can I save my List<Personal> and how can i update company in second personal correctrly?

**Comment by AndyDentFree** [comment]
If you pass in a flag to Add, it will update existing objects rather than clashing with their primary key.

` realm.Write(() => realm.Add(personal, update:true));`   

See also [the doc](https://realm.io/docs/xamarin/latest/#updating-objects)

**Comment by roman-morev** [comment]
in this case i've got System.NullReferenceException: Object reference not set to an instance of an object.
