### ISSUE TITLE
.NET Standard package

### ISSUE THREAD

**Issue by kristiandupont** [realm/realm-dotnet#1080]
In order to support UWP we need to turn our packages into .NET Standard packages. This will require us to update the uses of a number of apis that have been removed, mostly reflection. Parts of this work has been done already in #865.

**Comment by AndyDentFree** [comment]
I think it is not so much _turn our packages into_ as _make duplicate packages_

We need to keep supporting PCL for a significant duration. I suggest we take the cue from Xamarin - we shouldn't drop PCL support before they do.

**Comment by fealebenpae** [comment]
We will not be getting rid of the PCL assembly.

What we'll do is get rid of the Xamarin.iOS, MonoDroid, and .NET 4.5.2 assemblies and replace them with a single assembly targeting the .NET Standard 1.4 profile, which covers all our current platforms and adds UWP and .NET Core as well.

The PCL assembly will be moved into the new `ref` convention folder in the NuGet package which will make sure it is only ever compiled against and never copied to the build output of a project referencing our package. Check out https://docs.nuget.org/ndocs/create-packages/project.json-and-uwp#directory-structure for a detailed description of the new package format.
