### ISSUE TITLE
Split packages into native and library

### ISSUE THREAD

**Issue by kristiandupont** [realm/realm-dotnet#1082]
In order to support UWP, we will need to split our packages into two parts: native and library.

**Comment by fealebenpae** [comment]
Right now we use the `lib` folder in the NuGet package to house both the managed assembly and the native library the assembly P/Invokes into.

With #1080 we'll transition to a single `lib/netstandard1.4` folder that will contain our managed assemblies. The native libraries we'll break out into the following folders:
 - `runtimes/win81-x86/native`
 - `runtimes/win81-x64/native`
 - `runtimes/win81-arm/native`
 - `runtimes/win10-arm64/native`
 - `runtimes/osx-x64/native` to come in the future
 - `runtimes/linux-x64/native` to also come in the future

For iOS and Android we'll use the new `contentFiles` convention to add `librealm-wrappers.a` and `librealm-wrappers.so` to the referencing project with the proper build action (`NativeReference` and `AndroidNativeLibrary`, respectively) which we currently do manually with a `.targets` file.

**Comment by AndyDentFree** [comment]
The bulk of the above comment needs to end up in a readme - it's a great description of how the process (will) works.

**Comment by kristiandupont** [comment]
We don't need this anymore because when using the runtimes folder, Nuget is now smart enough to include the .net standard assemblies and the platform specific native wrappers without having to separate them into a separate package.
