### ISSUE TITLE
Nullable DateTimeOffset and quering by LINQ

### ISSUE THREAD

**Issue by hrach** [realm/realm-dotnet#1084]
I would like to filter entities by nullable DateTimeOffset property. I have exactly the same problem as desribed here: http://stackoverflow.com/questions/38763893/how-to-check-for-null-on-nullable-types-using-linq-expression-in-realm

The answers refers to nullable support for primitives, not for DateTimeOffset. Also, the referenced unit  tests doesn't test this behavior.

Documentation also doesn't describe any usage.

```csharp
public class EventEntity : RealmObject
{
	[PrimaryKey]
	public int Id { get; set; }
	public DateTimeOffset? StartAt { get; set; }
}

var realm = Realm.GetInstance();
DateTimeOffset maxStartAt = DateTimeOffset.Now.AddDays(-2);
return realm.All<EventEntity>()
	.Where(e => e.StartAt == null || e.StartAt > maxStartAt);
```
> `System.NotSupportedException: The rhs of the binary operator 'GreaterThan' should be a constant or closure variable expression. 
Unable to process `Convert(value(TickinCzHost.ViewModel.EventsViewModel+<>c__DisplayClass7_0).maxStartAt)` occurred`

#### Version of Realm and tooling
Realm version(s): 0.81
Xamarin/Visual Studio version: VS 2017 RC
Which operating system version and device: A6.0 & OnePlus 3

**Comment by hrach** [comment]
Hm, the same happens for long?

```csharp
public class EventEntity : RealmObject
{
	[PrimaryKey]
	public int Id { get; set; }
	public long? StartAt { get; set; }
}

var realm = Realm.GetInstance();
long maxStartAt = DateTimeOffset.Now.AddDays(-2).ToEpochTime();
return realm.All<EventEntity>()
	.Where(e => e.StartAt == null || e.StartAt > maxStartAt);
```

**Comment by fealebenpae** [comment]
Hey @hrach,

This seems like a bug. Could you try making the `maxStartAt` nullable as well? That should simplify the expression tree a bit and work around the problem area in our expression visitor.

**Comment by hrach** [comment]
Thank you! The workaround nullable works! So this works:

```csharp
DateTimeOffset? maxStartAt = DateTimeOffset.Now.AddDays(-2);
return realm.All<EventEntity>()
	.Where(e => e.StartAt == null || e.StartAt > maxStartAt)
	.OrderByDescending(e => e.StartAt);
```
