### ISSUE TITLE
Support Windows Phone 8.1 as legacy platform

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#1086]
I'm floating this for discussion based on a few factors:

- casual queries with local corporate and especially mining users - Windows Phone 8.1 is the OS on the majority
- As late as [2016-09-11, WP10 was reported](http://www.digitaltrends.com/computing/windows-10-mobile-market-share/) as only 14% of the WP market
- support for 8.1 in .Net Standard is only up to .Net Standard 1.2 therefore it will require special attention as we target .Net Standard higher versions.

**Comment by nirinchev** [comment]
I'm more concerned with having Core support for WP than the .NET binding.

**Comment by fealebenpae** [comment]
@nirinchev it's the opposite for me :P

**Comment by nirinchev** [comment]
Could be because I'm overly confident in my mad .NET skills 😎
