### ISSUE TITLE
Preserve initialisation expressions when weaving

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#109]
If the user specifies a default value for a property, weaving as a side-effect means it no longer works.
class Dog : RealmObject
       {
           public string Name { get; set; }
           public string Color { get; set; } = "Brown";
}

If not explicitly set, all Dogs should be Brown but instead they have no Color.

**Comment by nirinchev** [comment]
This works as expected for `Realm.Add` and we're deprecating `Realm.CreateObject`, so seems like it's no longer an issue.
