### ISSUE TITLE
Smoke test for Win32

### ISSUE THREAD

**Issue by kristiandupont** [realm/realm-dotnet#1092]
Nuget smoke test to verify that basics work with a simple Win32 app

**Comment by nirinchev** [comment]
I helped my brother integrate it in a very simple WPF app and everything seems to be working just fine (except for automatic transactions, but that's a [known issue](https://github.com/realm/realm-dotnet/issues/1154)).

**Comment by AndyDentFree** [comment]
Smoke indicating fire - testing latest nuget inc win32

```
-		$exception	{"Sequence contains no elements"}	System.InvalidOperationException

		StackTrace	"   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)\r\n   at Realms.Schema.ObjectSchema.FromType(Type type) in C:\\jenkins\\workspace\\realm_realm-dotnet_PR-1156-MBX7MABTU7AGARA56SRARS4LL7OI2XJECRRBJLGHWS3UNAVVWGNQ\\Shared\\Realm.Shared\\Schema\\ObjectSchema.cs:line 132\r\n   at Realms.Schema.RealmSchema.CreateSchemaForClasses(IEnumerable`1 classes) in C:\\jenkins\\workspace\\realm_realm-dotnet_PR-1156-MBX7MABTU7AGARA56SRARS4LL7OI2XJECRRBJLGHWS3UNAVVWGNQ\\Shared\\Realm.Shared\\Schema\\RealmSchema.cs:line 95\r\n   at Realms.Schema.RealmSchema.BuildDefaultSchema() in C:\\jenkins\\workspace\\realm_realm-dotnet_PR-1156-MBX7MABTU7AGARA56SRARS4LL7OI2XJECRRBJLGHWS3UNAVVWGNQ\\Shared\\Realm.Shared\\Schema\\RealmSchema.cs:line 143\r\n   at System.Lazy`1.CreateValue()"	string

```

**Comment by nirinchev** [comment]
is this only on win32? Can you post a repro?

**Comment by AndyDentFree** [comment]
Blocked on Microsoft - I'm sick of wasting time trying to get VS2015 going again because they have temporarily, and apologetically, killed VS2017 RC

**Comment by fealebenpae** [comment]
If you have 2017 installed you should be able to build from 2015 - it should pick up the v141 toolchain.

The best option, though, is to build from the VS 2017 command prompt using `msbuild` like we do for CI: https://github.com/realm/realm-dotnet/blob/master/Jenkinsfile#L113-L115. Then you won't have to care about wrappers at all and will be able to use 2015.
