### ISSUE TITLE
Custom authentication doc and sample

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#1113]
Show how our custom auth can be used especially with Azure. I've seen some great single-signon articles and meetup presentations over the years.

**Comment by AndyDentFree** [comment]
Wait until we have working samples of this in Cocoa.

**Comment by nirinchev** [comment]
We have a post on Azure AD auth: https://realm.io/news/azure-auth/

The ROS team is working on custom auth tutorials, so I feel there's nothing else to be done on our side.
