### ISSUE TITLE
Failed To Resolve Reference When Adding Backlink

### ISSUE THREAD

**Issue by Prin53** [realm/realm-dotnet#1116]
#### Goal

I am trying to add inverted relationship to `ItemModel : RealmObject`

#### Expected Results

Successful compilation.

#### Actual Results

> /iOS/MTOUCH: Error MT2002: Failed to resolve "System.Linq.IQueryable System.Linq.Queryable::AsQueryable(System.Collections.IEnumerable)" reference from "System.Linq.Queryable, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" (MT2002) (*.iOS)

#### Steps & Code to Reproduce

I tried:
- removing/adding Realm
- updating packages
- cleaning/building

Also tried to change `IQueryable` to `IList`, but get when accessing object:

> ../realm/table.hpp:1634: [realm-core-2.2.0] Assertion failed: typeid(Col) == typeid(col)
> 0   *.iOS                          0x000000010bc5f4f8 _ZN5realm4utilL18terminate_internalERNSt3__118basic_stringstreamIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 40
> 1   *.iOS                          0x000000010bc5f7fa _ZN5realm4util9terminateEPKcS2_lOSt16initializer_listINS0_9PrintableEE + 506
> 2   *.iOS                          0x000000010bdfd25d _ZN5realm5Table12get_linklistEmm + 173
> 3   *.iOS                          0x000000010bc1ddb1 object_get_list + 156
> 4   ???                                 0x000000011e43fbe1 0x0 + 4802739169
> IMPORTANT: if you see this error, please send this log to help@realm.io.

#### Code Sample

```csharp
public class ItemModel : RealmObject
{
	[Backlink(nameof(UserModel.Items))]
	public IQueryable<UserModel> Owners 
	{
		get;
	}
}
```

#### Version of Realm and tooling
Realm version(s): 0.81.0

Xamarin/Visual Studio version: Xamarin Studio 6.1.3

Which operating system version and device: iOS 10.2

**Comment by fealebenpae** [comment]
Hey @Prin53,

Sounds like you're defining your model in a Portable Class Library and your iOS Application project has the managed linker enabled. Backlinks are broken when used in PCLs - #1053 tracks this.
