### ISSUE TITLE
Document WriteAsync

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#1137]
I have now had two separate users ask me to confirm we have this feature, because it doesn't appear in the main doc.

**Comment by AndyDentFree** [comment]
Update [this SO question](http://stackoverflow.com/questions/39369085/realm-async-usage-in-tasks) and [HelpScout issue](https://secure.helpscout.net/conversation/248103312/6334/?folderId=907322) when complete.

**Comment by AndyDentFree** [comment]
Am reviewing how this works in detail thanks to user support tasks so figured would do writeup now.

**Comment by nirinchev** [comment]
After the latest set of changes, it will do a `Task.Run` if there's synchronization context (~99% chance it's on the main thread). If there isn't one, it will execute synchronously, as that seemed like a reasonable way to prevent people from shooting themselves in the foot.

**Comment by AndyDentFree** [comment]
Docs updated as per [PR comments](https://github.com/realm/realm.io/pull/2906) so please have and OK
