### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by luyzfernando** [realm/realm-dotnet#1149]
#### Goal

> What do you want to achieve?

#### Expected Results

> Remove all e Save 

#### Actual Results

>System.NullReferenceException: Object reference not set to an instance of an object.
>
>01-12 13:07:06.094 D/Mono    ( 8902): DllImport attempting to load: '/system/lib/liblog.so'.
>01-12 13:07:06.094 D/Mono    ( 8902): DllImport loaded library '/system/lib/liblog.so'.
>01-12 13:07:06.094 D/Mono    ( 8902): DllImport searching in: '/system/lib/liblog.so' ('/system/lib/liblog.so').
>01-12 13:07:06.094 D/Mono    ( 8902): Searching for '__android_log_print'.
>01-12 13:07:06.095 D/Mono    ( 8902): Probing '__android_log_print'.
>01-12 13:07:06.095 D/Mono    ( 8902): Found as '__android_log_print'.
>01-12 13:07:06.111 I/MonoDroid( 8902): UNHANDLED EXCEPTION:
>01-12 13:07:06.119 I/MonoDroid( 8902): System.NullReferenceException: Object reference not set to an instance of an object.
>01-12 13:07:06.119 I/MonoDroid( 8902):   at (wrapper managed-to-native) Realms.SharedRealmHandle+NativeMethods:begin_transaction (Realms.SharedRealmHandle,Realms.NativeException&)
>01-12 13:07:06.119 I/MonoDroid( 8902):   at Realms.SharedRealmHandle.BeginTransaction () [0x00000] in <03f96af2858c46cfb7cbbc741b866d11>:0 
>01-12 13:07:06.119 I/MonoDroid( 8902):   at Realms.Transaction..ctor (Realms.Realm realm) [0x0000d] in <03f96af2858c46cfb7cbbc741b866d11>:0 
>01-12 13:07:06.119 I/MonoDroid( 8902):   at Realms.Realm.BeginWrite () [0x00000] in <03f96af2858c46cfb7cbbc741b866d11>:0 
>01-12 13:07:06.119 I/MonoDroid( 8902):   at CRH.Mobile.Database.Realm.DeleteAll[TModel] () [0x00008] in D:\Project\CRH\CRH.Mobile\CRH.Mobile.Database\Realm.cs:112 
>01-12 13:07:06.119 I/MonoDroid( 8902):   at CRH.Mobile.Implementation.FakeUserService+<SyncDocuments>d__2.MoveNext () [0x002ee] in D:\Project\CRH\CRH.Mobile\CRH.Mobile.Implementation\UserService.cs:100 
>01-12 13:07:06.119 I/MonoDroid( 8902): --- End of stack trace from previous location where exception was thrown ---
>01-12 13:07:06.119 I/MonoDroid( 8902):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
>01-12 13:07:06.120 I/MonoDroid( 8902):   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>m__0 (System.Object state) [0x00000] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1018 
>01-12 13:07:06.120 I/MonoDroid( 8902):   at Android.App.SyncContext+<Post>c__AnonStorey0.<>m__0 () [0x00000] in /Users/builder/data/lanes/3511/501e63ce/source/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:18 
>01-12 13:07:06.120 I/MonoDroid( 8902):   at Java.Lang.Thread+RunnableImplementor.Run () [0x0000b] in /Users/builder/data/lanes/3511/501e63ce/source/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:36 
>01-12 13:07:06.120 I/MonoDroid( 8902):   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in /Users/builder/data/lanes/3511/501e63ce/source/monodroid/src/Mono.Android/platforms/android-24/src/generated/Java.Lang.IRunnable.cs:81 
>01-12 13:07:06.120 I/MonoDroid( 8902):   at (wrapper dynamic-method) System.Object:82f011de-baaa-4222-adc7-284393602063 (intptr,intptr)
>01-12 13:07:06.150 W/art     ( 8902): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
>01-12 13:07:06.156 D/Mono    ( 8902): DllImport searching in: '__Internal' ('(null)').
>01-12 13:07:06.156 D/Mono    ( 8902): Searching for 'java_interop_jnienv_throw'.
>01-12 13:07:06.156 D/Mono    ( 8902): Found as 'java_interop_jnienv_throw'.
>An unhandled exception occured.

#### Steps & Code to Reproduce

I open the screen, make an Async connection with the server and wait for the return.

After the result, I remove all records from the table and reinsert everything.

This works perfectly, however, by closing the screen and opening it again and the process repeats, and the error happens.

#### Code Sample

```csharp
IoC.Container.Get<IUserService>().SyncDocuments();

public async void SyncDocuments()
{
	var result = await _rest.GetAsync<IEnumerable<UserDocumentResponse>>(GetRelativeUrl("api/user/documents"));

	if (result.Status == RestResultCode.Success)
	{
		_database.DeleteAll<UserDocumentDatabase>();

		var insertModel = new List<UserDocumentDatabase>();
		foreach (var item in result.Data)
		{
			var document = new UserDocumentDatabase
			{
				Type = item.Type
			};

			foreach (var itemDocument in item.Documents)
				document.Documents.Add(new UserDocumentItemDatabase(itemDocument.Name, itemDocument.Value));

			insertModel.Add(document);
		}

		database.Insert<UserDocumentDatabase>(insertModel);
	}
}

public void DeleteAll<TModel>() where TModel : RealmObject
        {
            var realm = Realms.Realm.GetInstance();

            using (var trans = realm.BeginWrite())
            {
                realm.RemoveAll<TModel>();
                trans.Commit();
            }
        }

public void Insert<TModel>(IEnumerable<TModel> models) where TModel : RealmObject
        {
            var realm =  Realms.Realm.GetInstance();
            realm.Write(() =>
            {
                foreach (var model in models)
                    realm.Add(model, false);
            });
        }
```

#### Version of Realm and tooling
Realm version(s): ?
 **0.81.0**
Xamarin/Visual Studio version: ?
**Xamarin 4.2.2.11
VS 2015 U3**
Which operating system version and device: ?
**Motorola XT1058 with Android 5.1 and iOS Simulator 6 with iOS 10.2**

**Comment by AndyDentFree** [comment]
What is `foreach (var item in new result.Data)` supposed to do?

**Comment by luyzfernando** [comment]
Map the data from the server to my "table"

**Comment by AndyDentFree** [comment]
I kind of got that, although I don't know why you have separated out a loop of copying data to local objects and then again to the Realm with your Insert.

But, sorry if I'm being dense here, I don't understand your idiom - why `in` **new**?

I expected `foreach (var item in result.Data)` but maybe I am missing something.

**Comment by luyzfernando** [comment]
Excuse me. "new" was in the wrong place. I already edited the post.

Data is downloaded from the API and saved locally.

**Comment by fealebenpae** [comment]
Hey @luyzfernando,

Thank you for the bug report, but I'm afraid I don't understand the scenario well enough to be able to reproduce it. Would it be possible to send us a small project that demonstrates the exception? You can either put it on GitHub, or send it to help@realm.io if the code needed to reproduce the exception is sensitive.

**Comment by eyadon** [comment]
I think I'm seeing the same or very similar issue. Realm is used all over the place in my app, but there's a spot where I will frequently get a null ref for no apparent reason, usually works the first time through but 2nd+ gets more and more crash-prone. Sending repro to help@realm.io.

**Comment by fealebenpae** [comment]
Thanks to @eyadon's repro I believe I managed to track down the issue, which is already (collaterally) fixed in https://github.com/realm/realm-dotnet/pull/1061/commits/bf58baa1f5470e9739a87a339c4e4ce3ff356470.

Our next release will be in a few days and it'll include said fix. @luyzfernando @eyadon, please give it a spin once it's out and let us know if it resolves the crash.

**Comment by chiranjeebghosh** [comment]
For me the issue was I had changed the case of my namespace which created all the issues.
