### ISSUE TITLE
Enable "microtransactions" for WPF data-bindings

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-dotnet#1154]
With https://github.com/realm/realm-dotnet/issues/887 we added support for automatic transactions in Forms, however, the WPF binding engine doesn't care about `IReflecatableType`. It respects [`ICustomTypeProvider`](https://msdn.microsoft.com/en-us/library/system.reflection.icustomtypeprovider(v=vs.110).aspx) though, so we could implement that as well. Let's hope we don't end up with a 3rd one for UWP  

Here's a [blog post](http://www.jonathanantoine.com/2011/11/24/wpf-4-5-–-part-13-binding-to-types-that-implement-icustomtypeprovider-2/) about using those.

**Comment by fealebenpae** [comment]
> Let's hope we don't end up with a 3rd one for UWP 😹

Don't worry, we will.

**Comment by redtetrahedron** [comment]
Any progress on this?

**Comment by papafe** [comment]
You can read more about it [here](https://www.mongodb.com/docs/atlas/device-sdks/deprecation/), but Realm/Atlas Device Sync SDKS have been deprecated.
