### ISSUE TITLE
How to refresh an object with value ?

### ISSUE THREAD

**Issue by tematim** [realm/realm-dotnet#1155]
Hello,

I'm working with Xamarin and Realm.

I have a parent class like this  :
`public sealed class Context : RealmObject
    {
        public UserToken token { get; set; }
}`
The child is : 
`public class UserToken : RealmObject
    {
        public string Token { get; set; }

        public bool IsExpired { get; set; }
    }`

At the launch, I check the database and if null, I create one entry : 
`var _realm = Realm.GetInstance();
            var entries = _realm.All<Context>();
            Context = entries.FirstOrDefault();
            if(Context == null)
            {
                var transaction = _realm.BeginWrite();
                var entry = _realm.CreateObject<Context>();
                var token = _realm.CreateObject<UserToken>();
                entry.token = token;
                transaction.Commit();
            }`

The userToken is linked with JWT Auth, so when I receive it, I want to update it.

My code is : 
`var token = JsonConvert.DeserializeObject<UserToken>(JObject.Parse(content).ToString());
                        _realm = Realm.GetInstance();
                        var context = _realm.All<Context>().FirstOrDefault().tokenDetails;
                        var transaction1 = _realm.BeginWrite();
                        context.Realm.Add(token);
                        transaction1.Commit();`

I know it's wrong, because I add one userToken entry and not updating the existing one.

How can I do it correctly ?

Regards

**Comment by kristiandupont** [comment]
Hi Tematim,

it's not completely clear to me what you are trying to do. Is there only one `Context` instance in the realm at all times, which has a token that needs updating? If so, you might be able to simplify like this (note that `Realm.CreateObject` is deprecated and you should use `Realm.Add` instead):

```csharp
var _realm = Realm.GetInstance(); 
var entries = _realm.All<Context>();
Context = entries.FirstOrDefault(); 
if(Context == null) 
{
    _realm.Write(() =>
    {
        Context = _realm.Add(new Context { token = new UserToken { Token = token } }); 
     }
}
```
and
```csharp
var token = JsonConvert.DeserializeObject<UserToken>(JObject.Parse(content).ToString());
var context = _realm.All<Context>().FirstOrDefault(); // (Not sure what ".tokenDetails" was here) 
_realm.Write(() =>
{
    context.token.Token = token.Token;
});
```

Let me know if this helps.

**Comment by tematim** [comment]
Hello,

Thanks for your samples. I can update my values correctly.
I have a question about the first one.

I have this code :  
`                var _realm = Realm.GetInstance();
                var entries = _realm.All<GrandNancy>();
                Context = entries.FirstOrDefault();
                if(Context == null)
                {
                    var newContext = new Context();
                    newContext.payload = new Payload();
                    newContext.token = new UserToken();
#if DEBUG
                    newContext.ExecutionMode = "Debug";
#endif
#pragma warning disable 162
                    newContext.ExecutionMode = "Release";
#pragma warning restore 162
                    _realm.Write(() =>
                    {
                        Context = _realm.Add(newContext);
                    });
                }`

And I can't add the new value to the current context.

Could you help me ?

**Comment by kristiandupont** [comment]
Do you mean you can't replace the `Context.token.Token` value? That should be possible, I don't know why it wouldn't be. Do you get an error?

**Comment by tematim** [comment]
I'm talking about the new context value.

I have this error : Cannot convert source type 'void' to target type 'Context'

**Comment by kristiandupont** [comment]
It seems like you might be reaching the non-generic version of `Add`.  Try specifying the type:
```csharp
Context = _realm.Add<Context>(newContext);
```

**Comment by AndyDentFree** [comment]
@tematim there is a bug in version 0.81.0 in the PCL reference assembly, which fails to declare the 2nd parameter to `Add` as optional. This means the compiler is giving you the dynamic version of the Add.

Try changing your code 

`Context = _realm.Add(newContext, update=false);`

**Comment by tematim** [comment]
Sorry for the delay, the update:false fixed it.

Thanks for your help
