### ISSUE TITLE
Backlinks to the current class fail

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#1163]
Trying to declare circular relationships with a Backlink result in an `InvalidOperationException` _Sequence contains no elements_ being thrown during `RealmSchema.BuildDefaultSchema`.

eg: with a class such as:

```
    public class Employee : RealmObject
    {
        public string Name { get; set; }

        public IList<Employee> Reports { get; }

        [Backlink(nameof(Employee.Reports))]
        public Employee Boss { get; set; }
    }

```

**Comment by fealebenpae** [comment]
The type of a backlinks property should always be `IQueryable<T>` - the real bug is that the weaver has bot emitted a build error because of this.
