### ISSUE TITLE
Write LoginKit

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#1167]
Note that [current repo](https://github.com/realm-demos/realm-loginkit/)  needs a reorg to push Swift down a level

**Comment by nirinchev** [comment]
Can't we just create Xamarin bindings?

**Comment by AndyDentFree** [comment]
>Can't we just create Xamarin bindings?

was a suggestion to use bindings to call the native components written in Java and Swift.

I think it's much cleaner to copy their layout specifications and rewrite the minimal code in C#.

**In addition** we need a Xamarin Forms version.

 As Xamarin themselves are happy in at least one [ major recent sample](https://github.com/Microsoft/BikeSharing360_MobileApps) to use [AcrUserDialogs](https://github.com/aritchie/userdialogs) I think we can continue to do so. They were used in RealmTasks. That will simplify the UI side.

**Comment by nirinchev** [comment]
Xamarin Forms projects can use native controls, we just need to provide a renderer. Why do you think it's cleaner to rewrite a bunch of UI code instead of exposing the configuration API and proxying the calls to native?

**Comment by AndyDentFree** [comment]
People want to control look and feel in their apps and login screens may be presented very early in the flow. I think the effort is similar and our native screens are not sufficiently complex to justify them being done native. 

Get product management to decide the debate.
