### ISSUE TITLE
Visual Studio reference to librealm-wrappers.a reference could not be found

### ISSUE THREAD

**Issue by m-mccool** [realm/realm-dotnet#1169]
#### Goal

> What do you want to achieve?

For the Visual Studio project to correctly reference the librealm-wrappers.a

> ?

In my PCL, Android and iOS projects int my Xamarin mobile App, the nuget package has added a reference to the librealm-wrappers.a file. The path it is looking in is <MySolutionPath>\packages\Realm.0.81.0\build\../lib/Xamarin.iOS10/librealm-wrappers.a

Note the change from backward slashes to forward slashes. If you look on the file system with a path only containing backslashes then the file is in the correct location.

The application still builds correctly, but I have warnings in my build output

#### Steps & Code to Reproduce

Install the V0.88.1 nuget package into VIsual Studio 2015 on a windows machine

#### Version of Realm and tooling
Realm 0.88.1
Windows 7 SP1
Visual Studio 2015 Enterprise Version 14.0.25420.1 with Nuget Package Manager 3.4.4
Xamarin 4.1.2.18
Xamarin.Android 6.1.2.21
Xamarin.iOS 9.8.2.22

Which operating system version and device: ?

**Comment by fealebenpae** [comment]
Hey @m-mccool,

Is this a build warning, or a warning in the Solution Explorer?

**Comment by m-mccool** [comment]
This is the warning I get

Severity	Code	Description	Project	File	Line	Suppression State
Warning		The referenced component '<MySolutionPath>\packages\Realm.0.81.0\build\../lib/Xamarin.iOS10/librealm-wrappers.a' could not be found.	<ProjectName>

**Comment by TheFenux** [comment]
I'm still seeing this, repeatedly, even after removing it manually, in Visual Studio 2015, on Windows 10, with Realm 1.1.1.
