### ISSUE TITLE
RealmDraw for UWP Windows Phone

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#1174]
Update RealmDraw to work at least on Windows 10 Phone.

Blocked on sync but can get GUI going with local Realm so ready for drop-in solution. (More concerned about there being a moderate amount of work here than there is for RealmTasks)

**Comment by AndyDentFree** [comment]
As minor task, doing the testing necessary to confirm can use UWP with Skia drawing - that's a required step.

**Comment by AndyDentFree** [comment]
You can't use UWP with SkiaSharp. However, a UWP App built with Xamarin Forms works fine.

The implication for Draw is that it would have to be simply rewritten as a Forms app and that requires getting touch handling going for Forms. SkiaSharp has no inbuilt touch tracking which is why Draw was first written with simple native iOS and Android views. 

Adding touch tracking to SkiaSharp for Forms is not onerous so will tackle that as the next exploratory step.

**Comment by nirinchev** [comment]
What's the problem with using SkiaSharp on UWP directly?

**Comment by AndyDentFree** [comment]
I realised that conclusion is just silly - if it works in Forms it must be possible to get it working without. Am looking back at my earlier sample that wasn't working and may be a SkiaSharp update that's fixed issues I had with the plain UWP app.

**Comment by AndyDentFree** [comment]
OK, it works building UWP for my Surface Pro as an x84 machine!

Despite the Forms project working, my solo UWP project runs into a deployment problem on the device. I was stupidly interpreting that as a Skia issue because working code still gets Intellisense errors (classic gotcha to have Build+Intellisense selected in the Output panel) so I had an error regarding the SKXamlCanvas.

Weirdly, after a rebuild, reboot and another rebuild with VS2017 the device now works quite happily. So I'm putting it down to combination of possibly VS2015 issues, Windows 10 weirdness and not realising that the error that _looked_ like a SkiaSharp error was just Intellisense stupidity.

**Comment by AndyDentFree** [comment]
Can take this to be working on device and then remaining blocked on Sync for UWP.

**Comment by SKLn-Rad** [comment]
Is this not "do-able" now :)

**Comment by nirinchev** [comment]
It definitely is, it's just that we haven't gotten around to doing it.

**Comment by cbush** [comment]
We are revamping the Realm docs. We're not ignoring this issue -- we've read through every one of them, and we'll be sure to address this as part of our updates. We're closing the GitHub issues and creating new JIRA tickets to track the work at a high level.
