### ISSUE TITLE
Queries on backlinks fail

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#1177]
Given a declaration:

```
    public class Employee : RealmObject
    {
        public string Name { get; set; }

        public IList<Employee> Reports { get; }

        [Backlink(nameof(Employee.Reports))]
        public IQueryable<Employee> Bosses { get; }

        public Employee Boss
        {
            get
            {
                return Bosses.FirstOrDefault();
            }
        }
    }
```

The following unit test fails because the value of `bossesBoss` is the Sally object, instead of null.

```
        [Test]
        public void RecursiveBacklinks()
        {
            realm.Write(() =>
            {
                realm.Add(new Employee
                {
                    Name = "Sally",
                    Reports =
                    {
                        new Employee { Name = "Sree" },
                        new Employee { Name = "Jake" }
                    }
                });
            });
            var jake = realm.All<Employee>().Single(p => p.Name == "Jake");
            Assert.That(jake.Boss?.Name, Is.EqualTo("Sally"));
            var bossesBoss = jake.Boss?.Boss;
            Assert.That(bossesBoss, Is.Null);
        }
```

**Comment by AndyDentFree** [comment]
I think the problem is that perfectly logical LINQ syntax is failing because we are invoking it on the `IQueryable<Employee>` which is meant to be a subset from the backlink, but ends up behaving as if it is `All<Employee>()`.

So we can't query the results of Backlinks and because by definition they are returning a collection, the only way to use them is to force them to a non-Realm collection with ToList().

**Comment by nirinchev** [comment]
Briefly investigating it, looks like `RealmResultsVisitor.CreateQuery` uses the incorrect overload for creating `Query`. `object_get_backlinks` creates `Results` with a `TableView` which should then be passed to the `Query` ctor, but is not. @fealebenpae feel free to fix ;)
