### ISSUE TITLE
Migration handler not being invoked

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#1186]
Copied here from comments on #768:

**Comment by AndyDentFree** [comment]
Please supply some sample code. I would have expected the migration handler to be called because it should be about the _current_ version supporting the handler.  There may be a misunderstanding in how you're setting up the handler, or how it is written. Email to help@realm.io if you don't want to attach it publicly.

**Comment by sushihangover** [comment]
@AndyDentFree See the comments on this SO answer. The users started with `0.77.1`, did not manually assign a schema version, thus the db was not initiated with a schema version of 0, but now he needs to perform a migration. 

>Sorry that should have read 0.81.0. This is what I am doing my initial development investigation on. My in production version is 0.77.1. Will this be able to be migrated?

>My real question now is if I have an app in production written using v0.77.1 and now want to upgrade the app to one which uses v0.81.0, will it detect the migration. If not can I force a migration to happen to bridge a version of realm that does not support migrations to one that does?

Ref: http://stackoverflow.com/a/41838630/4984832

**Comment by m-mccool** [comment]
Yes @sushihangover @AndyDentFree the code in the SO post is what I am attempting

**Comment by AndyDentFree** [comment]
Answered on SO but is complicated by them started with 0.77.1. Looking at the changelog, 0.77.2 was the version introducing a fix _Schema version numbers now start at 0 rather than UInt64.MaxValue_

**Comment by AndyDentFree** [comment]
Testing proves starting with 0.77.1 is not a problem - migration happens as expected.

**Comment by m-mccool** [comment]
So if I set my new version of the app to schema version 1, the migration callback will be called? That's not what I am experiencing, I'll do more investigation.

**Comment by AndyDentFree** [comment]
As requested on SO, please clarify the platforms. I only tested on IOS hardware so maybe there's a subtle bug somewhere else.

**Comment by m-mccool** [comment]
I am currently using Xamarin Android on KitKat and Lollipop.

**Comment by AndyDentFree** [comment]
I cannot replicate this on Android either - tried a couple of different versions and devices. My suggestion is to try bumping your  number higher in case you somehow set it at 1 earlier.

**Comment by nirinchev** [comment]
@m-mccool did you manage to resolve your issue?

**Comment by m-mccool** [comment]
I haven't had time unfortunately to get back to it. But I will be trying it in the next few days. Will try on android to set the number higher to see if it works.

**Comment by m-mccool** [comment]
@AndyDentFree Just to clarify how are you performing your migrations, by installing .apk files or just by deploying from visual studio. Does it matter?

**Comment by nirinchev** [comment]
It shouldn't matter - in both cases, a migration callback should be invoked.

**Comment by AndyDentFree** [comment]
@m-mccool I was just deploying from Xamarin Studio on Mac which means I was also running a debug version. That's a good point that I hadn't checked a fully-linked Release version.

**Comment by m-mccool** [comment]
@AndyDentFree @nirinchev We tried this this morning. The steps are outlined below.

Installed the app that uses Realm 0.77.1. 

We then installed a version of the app that uses 0.81.0. It had a schema change which added a new string field to an existing realm object.

In both cases the installation was a debug build from within visual studio (e.g F5)

The migration callback does not get called.

**Comment by AndyDentFree** [comment]
I spent some time going through and revising my demo app to be clearer when migration is being invoked and made sure that I built and ran a version with 0.77.1 then the version with 0.81.0 on Android.

In this process, I ran into an amazing bug with Xamarin Studio and the Android tooling - it will replace resources but **leave old code behind**. It took significant testing to convince myself of this and after posting my own question on the forums, was directed to a long-running thread. You can see my comments [here](https://forums.xamarin.com/discussion/comment/261078/#Comment_261078)

**Comment by m-mccool** [comment]
Hi @AndyDentFree Thanks for looking into this again. Have you tried using Visual Studio, I don't think it has this bug.

**Comment by AndyDentFree** [comment]
VS2017 does indeed avoid the earlier problems with Xamarin Studio and successfully compiles code however it seems to run into other problems replacing the app on Android with the change in Realm version - a `DLLNotFound` problem causing an exception with the debug version.

**Comment by m-mccool** [comment]
@AndyDentFree we are still using Visual Studio 2015

**Comment by AndyDentFree** [comment]
The good news is that VS2015 and 2017 can co-reside for Xamarin development (that was only recently true) and I'm able to test with both.

The (bad?) news for people doing Windows Phone development is that VS2017 doesn't support it so you **have** to keep a VS2015 environment around.

**Comment by m-mccool** [comment]
Hi @AndyDentFree Did you manage to find out whether this migration scenario should work on Android.

**Comment by AndyDentFree** [comment]
@m-mccool sorry I couldn't get around my dev tool issues but will try again with VS2017. I don't work at Realm as of April and was trying to wrap up another couple of issues in the last few days.

I couldn't find anything to suggest migration would fail in theory. I was also starting to wonder if the problems in debug mode are a red herring - stupid stuff like not replacing code when debugging may not necessarily occur when deploying a new version of a compiled app.
