### ISSUE TITLE
Backlink show all data, not only the related

### ISSUE THREAD

**Issue by hrach** [realm/realm-dotnet#1191]
Backlink property in my EventEntity:

```cs
[Backlink(nameof(TicketEntity.Event))]
public IQueryable<TicketEntity> Tickets { get; }
```

TicketEntity property:
```cs
public EventEntity Event { get; set; }
```

`Event.Tickets` contains all tickets in the db, not only the associated with the entity. 

Xamarin   4.3.0.598 (95cf4d3)
Xamarin.Android   7.1.0.19 (3d959b6)
Model in PCL.

**Comment by nirinchev** [comment]
There's a known issue with backlinks where executing a query will actually query all objects:https://github.com/realm/realm-dotnet/issues/1177 . However, getting all related should work as expected. Can you try to call ToArray on your backlink property and let me know if the problem still exists?

**Comment by hrach** [comment]
Ah, you are right, I aws using tickinEvent.Tickets.Count(); method and in other call also a query. With ToArray() it works.
