### ISSUE TITLE
RealmWeaver incorrect warning RealmObject non-automatic

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#1195]
We avoid weaving when there is a non-automatic get or set on a property.

However, when the return type is RealmObject, a warning is still published. eg:

`Fody.RealmWeaver: Employee.Boss is not an automatic property but its type is a RealmObject which normally indicates a relationship`

As shown in our `TestObjects.cs` class `Employee`

**Comment by nirinchev** [comment]
Why is it incorrect? I think that's the point of it being a warning - the property is not woven, but we still warn you so that if it were a mistake, you can fix it.

**Comment by cbush** [comment]
We are revamping the Realm docs. We're not ignoring this issue -- we've read through every one of them, and we'll be sure to address this as part of our updates. We're closing the GitHub issues and creating new JIRA tickets to track the work at a high level.
