### ISSUE TITLE
Improve Windows cross-process reliability

### ISSUE THREAD

**Issue by kristiandupont** [realm/realm-dotnet#1202]

**Comment by nirinchev** [comment]
I believe this is the Core PR that tracks it: https://github.com/realm/realm-core/pull/2497

AFAICT, there's no work to be done on the .NET side. Should we keep the issue open as a reminder or should we just close it?

**Comment by kristiandupont** [comment]
I don't think there is any reason to track it here.

**Comment by fealebenpae** [comment]
We need to incorporate the work done in Core at the Object Store level - the ExternalCommitHelper is the one that's the most flakey right now.

**Comment by nirinchev** [comment]
This should be done now, right?
