### ISSUE TITLE
Obsolete IRealmCollection.ObjectSchema

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-dotnet#1214]
It is not relevant for IRealmCollection. I suggest we obsolete it and introduce a new interface that will expose the same property (which we can then apply on RealmObject as well).

**Comment by AndyDentFree** [comment]
I'm OK with a new interface but think it vital to retain _something_ with this functionality because I'm sure there's at least one user out there with it in production.

**Comment by nirinchev** [comment]
Yes, it appears that there is some value to it (despite my assumptions 😅), so I think extracting an interface just for that will align nicely with the `I` in SOLID 🤓
