### ISSUE TITLE
DateTimeOffset property with MinDate value is set to Unix Epoch start after insert

### ISSUE THREAD

**Issue by tomasszabo** [realm/realm-dotnet#1225]
#### Goal

I have a Task object with DateTimeOffset properties.

````csharp
public class Task : RealmObject 
{
  public DateTimeOffset Reminder { get; set; }
  ...
}
````

Task instance has Remidner property set to MinValue (I'm using DateTimeOffset.MinValue as "date not set" identifier). I want to save Task instance to Realm with

````csharp
using (var transaction = realm.BeginWrite()) {
  ...
  realm.Add (task);
  transaction.Commit();
}
````

#### Expected Results

Task instance is stored and  `task.Reminder` property should be `DateTimeOffset.MinValue` (i.e. "1/1/0001 12:00:00 AM +00:00").

#### Actual Results

Task instance is stored but `task.Reminder`property  is Unix epoch start (i.e. "1/1/1970 12:00:00 AM +00:00") and  `task.Reminder == DateTimeOffset.MinValue` returns false.

#### Version of Realm and tooling
Realm version(s): 0.82.1
Xamarin/Visual Studio version: Xamarin Studio Community 6.1.5
Which operating system version and device: iOS simulator 10.2

**Comment by nirinchev** [comment]
This is indeed an incorrect behavior. I would suggest you work around it by modifying your property type to `DateTimeOffset?` - then use `null` as indication that the date has not been set.

**Comment by sushihangover** [comment]
During a Realm schema migration where you have **added** a `DateTimeOffset` property, the `NewRealm` will contain the unix epoch date in those new properties.
