### ISSUE TITLE
SubscribeForNotifications handler is never called, if subscription is created not from the Main thread

### ISSUE THREAD

**Issue by Shaddix** [realm/realm-dotnet#1232]
Subj

Realm 1.0.3 Windows/Android

If I call SubscribeForNotifications not from the Main thread, handler is not called when I add the data.
In the following example the `Changed` handler is called when `Task.Factory.StartNew(` is commented out, but is not called, when I uncomment it

            //Task.Factory.StartNew(() =>
            //{
                var realm = Realm.GetInstance();

                realm.All<Tst1>().SubscribeForNotifications(Changed);
            //}).Wait();

            var r = Realm.GetInstance();
            r.Write(() =>
            {
                r.Add(new Tst1()
                {
                    Comment = DateTime.Now.ToString()
                });
            });

**Comment by nirinchev** [comment]
Hi Shaddix,

This is a known limitation when using threads without looper/runloop. Please refer to the [docs](https://realm.io/docs/xamarin/latest/#seeing-changes-from-other-threads) for more info.
