### ISSUE TITLE
Realm.RemoveAll(string) doesn't work

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-dotnet#1245]
Reported by user here: http://stackoverflow.com/questions/42301477/remove-data-from-old-realm-during-realm-database-migration#comment71759098_42301910

**Comment by AndyDentFree** [comment]
As noted in the SO it didn't work in his context because he was calling it on the dynamic interface of the "old" Realm in a migration block. The `oldRealm` is read-only.

**Comment by nirinchev** [comment]
His comment states
> It throws a RealmException complaining that Realm.RemoveRange() expects an IQueryable from .All or something like

so I thought it might be some issue with casting from `IQueryable<dynamic>` to `IQueryable<RealmObject>`. Haven't tried it yet, but if you can confirm it works as expected for read-write realms, we can close that.

**Comment by UKDeveloper99** [comment]
It doesn't work on newRealm, not oldRealm. To clarify.

**Comment by nirinchev** [comment]
So it looks like this is indeed a bug - I'll investigate later this week.
