### ISSUE TITLE
Tight loop, multiple reads, Garbage Collection - Crash without stacktrace

### ISSUE THREAD

**Issue by adamcogx** [realm/realm-dotnet#1250]
I have a loop (its a bit contrived as it was part of a test) that causes an Android app to crash without a stack trace:

```
for (int i = 0; i < 1000; i++) {
    list.AddRange(realm.All<T>().ToList());
}

```
If a garbage collection happens during this loop:

```
02-22 13:07:17.181 D/Mono    (18448): GC_TAR_BRIDGE bridges 0 objects 0 colors 0 ignored 0 sccs 0 xref 0 cache 0/0 setup 0.09ms tarjan 0.03ms scc-setup 0.05ms gather-xref 0.00ms xref-setup 0.00ms cleanup 0.00ms
02-22 13:07:17.181 D/Mono    (18448): GC_BRIDGE: Complete, was running for 0.11ms
02-22 13:07:17.181 D/Mono    (18448): GC_MINOR: (Nursery full) time 22.41ms, stw 22.75ms promoted 972K major size: 4688K in use: 3962K los size: 2048K in use: 1391K
02-22 13:07:17.208 D/Mono    (18448): Assembly Ref addref HockeySDK.AndroidBindings[0xb9b3b2f8] -> System[0xb9c157b0]: 19
02-22 13:07:17.212 W/Ditech  (18448): Interation 26
02-22 13:07:17.267 W/Ditech  (18448): Interation 27
02-22 13:07:17.294 W/art     (18448): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
02-22 13:07:17.310 W/Ditech  (18448): Interation 28
```

It will crash without warning and without a stack trace.

If I debug the loop and step through it, it works fine.  Without debugging it crashes after 28 loops, when debugging it goes much further (I didn't go beyond 75 loops).

**EDIT:** The realm call only returns 2 rows (just so you don't think its a huge result set)

**Comment by nirinchev** [comment]
Thanks for the report! We'll have someone look into it and get back at you.

**Comment by nirinchev** [comment]
Hi @adamcogx I tried to reproduce your issue, but was unable to do so. This is my test code:

```csharp
[Test]
public void RealmAll_InALoop_ShouldNotThrow()
{
    _realm.Write(() =>
    {
        _realm.Add(new Person
        {
            FirstName = "1"
        });

        _realm.Add(new Person
        {
            LastName = "2"
        });
    });

    var list = new List<Person>();
    Assert.That(() =>
    {
        for (var i = 0; i < 1000; i++)
        {
            list.AddRange(_realm.All<Person>().ToList());
            Console.WriteLine("Iteration: " + i);
        }
    }, Throws.Nothing);

    Assert.That(list.Count, Is.EqualTo(2000));
}
```

I see a garbage collection during the loop but it doesn't cause a crash:
```
Iteration: 950
Iteration: 951
Iteration: 952
Iteration: 953
Iteration: 954
Iteration: 955
Iteration: 956
[art] Starting a blocking GC Explicit
[art] Explicit concurrent mark sweep GC freed 10264(553KB) AllocSpace objects, 0(0B) LOS objects, 47% free, 4MB/8MB, paused 349us total 21.876ms
[Mono] GC_TAR_BRIDGE bridges 189 objects 5521 opaque 4114 colors 192 colors-bridged 189 colors-visible 189 xref 35 cache-hit 0 cache-semihit 0 cache-miss 3 setup 0.08ms tarjan 4.82ms scc-setup 0.10ms gather-xref 0.02ms xref-setup 0.01ms cleanup 0.23ms
[Mono] GC_BRIDGE: Complete, was running for 25.65ms
[Mono] GC_MINOR: (Nursery full) time 39.70ms, stw 39.98ms promoted 1506K major size: 2400K in use: 1663K los size: 1024K in use: 120K
Iteration: 957
Iteration: 958
Iteration: 959
Iteration: 960
```

Can you share a minimal repro project?

**Comment by adamcogx** [comment]
Not sure I can.  I don’t remember what I was doing and changed the code to avoid it.  I still get a random crash every so often but because it has no stack trace I cannot tell you where it happened, just that it did (HockeyApp tells me there was a crash but has no strack trace)

 

Adam Greene, CTO

 

 <http://cognitivex.com/> 
506.802.8648 <tel://5068028648/>  (o) | 1.800.670.COGX(2649) <tel://18006702649/>  ext 2 | http://cognitivex.com <http://cognitivex.com/> 

 

We build web and mobile applications that solve real business problems.

**Comment by nirinchev** [comment]
Without a reproduction case, we won't be able to investigate that further. If you manage to isolate a source of the crash, feel free to reopen the issue.
