### ISSUE TITLE
Add support for Fody.Costura out of the box

### ISSUE THREAD

**Issue by jonstodle** [realm/realm-dotnet#1252]
#### Goal

If you're using Realm with [Fody.Costura](https://github.com/Fody/Costura) you'll have to do some tinkering to get it working. This is a suggestion/request to support for Costura "out of the box", eg: being able to use Realm without extra config in Costura.

#### Expected Results

Right now NativeCommon.cs assumes Realm.dll is available in folder at runtime (see #1249 for details on this). This prevents it from being easily used with solutions like Costura. It works nicely if you do an installer-type deploy, but not so well if you want to distribute a single exe file.

I honestly don't know how much work this will require to implement, but it's hinted in #1249 that it might be possible to do if there's an interest for it.

**Comment by jonstodle** [comment]
The current setup also makes it very difficult (impossible?) to run Realm in [LINQPad](http://www.linqpad.net/) or [RoslynPad](https://roslynpad.net/), which are great for testing, prototyping or just playing around.

Having it possible to use Realm in those tools may lower the bar for some to test Realm out.

**Comment by ahmedalejo** [comment]
I have be trying to use Realm with [LINQPad](http://www.linqpad.net/) without success  as well.
Any news on this.

**Comment by nirinchev** [comment]
Fody.Costura is in maintenance mode so we'll not allocate resources to support it.
