### ISSUE TITLE
Migrate to realm-per SynchronizationContext rather than per-thread

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-dotnet#1257]
It seems possible to lift the same-thread requirement for Realm instances and instead impose same-synchronization context one. This will improve our interoperability with RX and custom synchronization contexts.

**Comment by AndyDentFree** [comment]
Could you explain why this is safe in more detail at some point because I thought the single-thread restrictions were about OS threads down at core level.

**Comment by nirinchev** [comment]
That's in response to a conversation I had with @fealebenpae about it (he was the one to suggest it).

The way I understand it, Core doesn't care about threads - it's more of a Object Store concept that's introduced to prevent race conditions and other potentially dangerous async situations. Since the synchronization context guarantees the order of operations, we could use that which would allow us to work as expected in situations where it dispatches actions on different threads. 

I can't say I've researched it heavily, but it looked like it's doable.

**Comment by nirinchev** [comment]
This will be done with the Core 6 upgrade.
