### ISSUE TITLE
Issue resolving files in VS2015 for iOS project

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#1264]
SO question from regular, experienced Realm user, who is normally one solving **other** people's problems (thanks).

[Xamarin.Forms with Realm - issue resolving files when bulding iOs](http://stackoverflow.com/questions/42647188/xamarin-forms-with-realm-issue-resolving-files-when-bulding-ios)

**Comment by Yelnik** [comment]
Also cannot build iOS project from VS2015 connect to Mac

**Comment by nirinchev** [comment]
That's related to https://github.com/realm/realm-dotnet/issues/1265

It appears 1.1.0 has a bug when building from Visual Studio. There is no workaround, so either use Xamarin Studio or revert to 1.0.4.
