### ISSUE TITLE
Strange MvxCollectionView bug (databinding)

### ISSUE THREAD

**Issue by UKDeveloper99** [realm/realm-dotnet#1267]
Feel free to chime in:
https://github.com/MvvmCross/MvvmCross/issues/1545

**Comment by UKDeveloper99** [comment]
I shall reproduce this in a test project in the morning so you can take a look. If the issue turns out to be something with MvvmCross and not Realm I'm sure you can advise them accordingly.
Cheers.

**Comment by batrand** [comment]
FYI, I linked a test project that reproduces this bug, but GitHub somehow misinterpreted the link and instead led to a nonexistent page. I've edited the post. Here's the [project repo](https://bitbucket.org/batrand/mvxbug_realmbinding).

**Comment by UKDeveloper99** [comment]
This is resolved as far as I'm concerned, the fix in the referenced issue seems to be adequate.

**Comment by nirinchev** [comment]
Just for self-sufficiency's sake, the Mvx team has suggested to use the old `MvxBindingContext`: https://github.com/MvvmCross/MvvmCross/issues/1545#issuecomment-285803447
