### ISSUE TITLE
librealm-wrappers.a for Xamarin.iOS isn't found

### ISSUE THREAD

**Issue by mrxten** [realm/realm-dotnet#1271]
I tried to add Realm to XF project and got this error:
![image](https://cloud.githubusercontent.com/assets/13070572/23811994/836a8c44-05e9-11e7-9e80-27b74e30702e.png)

... but file is there:

![image](https://cloud.githubusercontent.com/assets/13070572/23812115/252d1100-05ea-11e7-9e1d-e0d92be0256f.png)

I tried to ignore that. Android version starts fine, but iOS app throws an exception:

![image](https://cloud.githubusercontent.com/assets/13070572/23812046/dc4ab62c-05e9-11e7-8ec2-dec05fcf59b1.png)

How can I resolve this issue?

#### Version of Realm and tooling
Realm version(s): 1.1.0

Xamarin/Visual Studio version: 2017

Which operating system version and device: win 10

**Comment by nirinchev** [comment]
Is this a screenshot from the PCL? If that's the case, it shouldn't have that native reference - it should be in the iOS project. Also, make sure you've added Realm to the iOS project.

**Comment by mrxten** [comment]
Yes, this is PCL. But if I delete the reference from PCL how I will use Realm in XF?
I doing like this: https://github.com/realm/realm-dotnet/tree/master/examples/QuickJournal
In your example reference there in each project: PCL, Xamarin.Droid, Xamarin.iOS

**Comment by mrxten** [comment]
It used Bait and Switch Trick. So, what a problem?
In PCL:
![image](https://cloud.githubusercontent.com/assets/13070572/23821272/fcc9c4ac-063d-11e7-97d2-1c40c7d39f24.png)
In Xamarin.Android:
![image](https://cloud.githubusercontent.com/assets/13070572/23821276/2d96d7a0-063e-11e7-9102-935592148291.png)
In Xamarin.iOS:
![image](https://cloud.githubusercontent.com/assets/13070572/23821275/234e1236-063e-11e7-93a4-d55ae2e67f46.png)

**Comment by nirinchev** [comment]
Yes, you should have a reference to the PCL, but the native reference `librealm-wrappers.a` should not be in the PCL - it's an iOS thing. Can you try to remove Realm from all projects and add it again?

**Comment by mrxten** [comment]
Yes, I tried repeatedly

**Comment by nirinchev** [comment]
In that case, can you share a project that reproduces this behavior? If you prefer to send it privately, feel free to do so at help@realm.io.

**Comment by nirinchev** [comment]
1.1.1 was released that fixes an issue when building from VS for iOS. Can you check if it fixes your problem?

**Comment by mrxten** [comment]
Okay, i will try.

**Comment by nirinchev** [comment]
@mrxten were you able to test if the new version fixes the problem?

**Comment by mrxten** [comment]
No, but I will definitely test when I come back from rest. I'll let you know in few days.

**Comment by nirinchev** [comment]
Glad to hear that!

**Comment by tonholis** [comment]
Hi! 
I have a similar issue with Realm 2.1.0 added in a PCL library for a Xamarin.Forms app.
It works fine on iOS and Android but I'm still getting those warnings.

```
The referenced component 'D:\Projects\MyApp\packages\Realm.2.1.0\build\..\native\..\runtimes\osx.10.10-x64\native\librealm-wrappers.dylib' could not be found.	MyApp
The referenced component 'D:\Projects\MyApp\packages\Realm.2.1.0\build\..\native\..\runtimes\osx.10.10-x64\native\librealm-wrappers.dylib' could not be found.	MyApp.Droid	
The referenced component 'D:\Projects\MyApp\packages\Realm.2.1.0\build\..\native\..\runtimes\osx.10.10-x64\native\librealm-wrappers.dylib' could not be found.	MyApp.iOS
The referenced component 'D:\Projects\MyApp\packages\Realm.2.1.0\build\..\native\ios\universal\librealm-wrappers.a' could not be found.	MyApp
The referenced component 'D:\Projects\MyApp\packages\Realm.2.1.0\build\..\native\ios\universal\librealm-wrappers.a' could not be found.	MyApp.Droid
The referenced component 'D:\Projects\MyApp\packages\Realm.2.1.0\build\..\native\ios\universal\librealm-wrappers.a' could not be found.	MyApp.iOS
```

Is there any way to solve these warnings?
