### ISSUE TITLE
Unable to create offline fallback

### ISSUE THREAD

**Issue by torbenboeck** [realm/realm-dotnet#1285]
#### Goal

We're having probems creating an offline fallback for when the internet connection is not available.

We have another issue, that is currently being looked into by Yavor (https://github.com/realm/realm-dotnet/issues/1272#issuecomment-286064516), so it might be related to that, but it would be great, if you were able to tell if we're doing something wrong here.

#### Expected Results

We except to get an offline version of the realm, that has all the data, we've added

#### Actual Results

The offline version does not have any data in it. We can start adding data to it, but it does not get synchronized.

#### Code Sample

```csharp

internal static Realm CreateRealm()
        {
            Realm instance = null;
            var credentials = Credentials.UsernamePassword("xxx", "xxxx", false);
            var authURL = new Uri("url");

            User user = null;
            try
            {
                Task.Run(async () =>
                {
                    user = await User.LoginAsync(credentials, authURL);
                }).Wait();

                var serverURL = new Uri("realm://url/~/default");
                var config = new SyncConfiguration(user, serverURL);

                instance = Realm.GetInstance(config);
            }
            catch (Exception e)
            {
                instance = Realm.GetInstance();
            }

            return instance;
        }

```

#### Version of Realm and tooling
Realm version(s): ?
1.1.1
Xamarin/Visual Studio version: ?
2015
Which operating system version and device: ?
Windows 10
Android

**Comment by fealebenpae** [comment]
Similarly to #1272, the issue is a missing port in the `URI` passed to `SyncConfiguration`.

But a cleverer workaround is to use the persisted `User.AllLogedIn` property to get a `User` object that's been logged in already in a previous launch and open a synchronized realm without having to manually create an offline local-only realm.

**Comment by nirinchev** [comment]
I'd like to also point out that an "offline" realm cannot be converted to a synced realm unless you manually copy the data. We have a task in our backlog to support logging in with anonymous users, but @fealebenpae's suggestion will help you handle all cases except for the initial Login.

**Comment by torbenboeck** [comment]
Thank you so much for the help. I was confused by the fact that the port
was not mentioned for the server url in the Xamarin documentation on your
site. I should have spotted it myself of course, but I must have stared too
long at the problem :)

Best,
Torben
