### ISSUE TITLE
SubscribeNotifications inserts too many objects after update

### ISSUE THREAD

**Issue by tomasszabo** [realm/realm-dotnet#1299]
#### Goal

I have following query:

````csharp
DateTimeOffset dateStart = date.Date;
DateTimeOffset dateEnd = dateStart.AddDays (1);

var realm = GetRealm ();
var result = realm.All<Task> ()
			.Where (t => t.Deleted == false &&
				  t.Completed == false &&
				  t._Reminder >= dateStart &&
				  t._Reminder < dateEnd)
			.OrderBy (t => t._Reminder)
			.AsRealmCollection ();
````

which returns tasks for specific date. `_Reminder` property is of `DateTimeOffset` data type. Then later in my code I'm subscribing to query changes:

````csharp
result.SubscribeNotifications ((sender, changes, error) => {
    ...
});
````

according to the changes in query, I'm updating UI.

#### Expected Results

E.g. I'm querying all tasks for tomorrow and it returns for example only 1 Task object. Then I change the reminder on task to today (i.e. was tomorrow now it's today), save the task to Realm and then the query fires my notification method and the result should be empty query (i.e. I should receive delete change in order to remove the task from UI).

#### Actual Results

I'm receiving 2x insert changes and 1x delete change and the query then contains 1 task (but should not, because the `_Reminder` property on Task object is set to today, not tomorrow as the query condition). 

If the query is not for tomorrow but more in future (e.g. 5 days ahead) and I change the reminder back to today, then I receive 5x insert changes and 1x delete change. The query should be empty but it contains 4 Task objects (all are same).

Unfortunately, the count of insert and delete changes is not deterministic (i.e. I don't know why but sometimes it's different) but there are more insert changes then delete changes. It seems to only happen when changing the date from future to present time, when I'm changing reminder to the future, it seems to be working as expected. 

#### Version of Realm and tooling

Realm version(s): 1.1.1 (NuGet package)
Xamarin/Visual Studio version: Xamarin Studio Community 6.2
Which operating system version and device: iOS simulator 10.2

**Comment by AndyDentFree** [comment]
Can you please show us the code which is doing the update you mention:

> Then I change the reminder on task to today

**Comment by tomasszabo** [comment]
Update: I've removed the mention of modify changes as it was related to other query. Relevant are only insert and delete changes.

@AndyDentFree 
It's a lot of code but if I reduce it, then basically I'm updating the task object with following code:

````csharp
var realm = GetRealm ();

using (var transaction = realm.BeginWrite ()) {
  try { 
    task.Reminder = newDate;

    realm.Add (task, true);

    transaction.Commit ();
  } catch (Exception) {
    transaction.Rollback ();
  }
}
````

where property `Reminder` is a decorator for `_Reminder`:

````csharp
public class Task : RealmObject 
{
  ...

  [Indexed]
  public DateTimeOffset _Reminder {
    get;
    set;
  }

  public DateTimeOffset Reminder {
    get {
      return _Reminder.IsMinValue () ? _Reminder : _Reminder.ToLocalTime ();
    }
    set {
      _Reminder = value.IsMinValue () ? value : value.ToUniversalTime ();
    }
  }
}
````

**Comment by AndyDentFree** [comment]
@tomasszabo 

I thought I might see a `realm.Add (task, true);` or similar.

Does your `Task` have  a PrimaryKey?

As you can see from the [docs on Updating Objects](https://realm.io/docs/xamarin/latest/#updating-objects) we only provide _updates_ using `Add` when there's a PrimaryKey on the class.

**Comment by tomasszabo** [comment]
@AndyDentFree 
Yes, there is a `realm.Add (task, true)`, it's in the middle of try-catch block in my code sample above.

And yes, `Task` does have a primary key. Without a primary key, I will have Realm full of tasks in a while. It looks following:

````csharp
public class Task : RealmObject 
{
  [PrimaryKey]
  public string Id {
    get;
    set;
  }

 ...
}
````

Anyway, other queries behave like expected, the only problem I have is with this one, which has date range in where condition. Maybe some problem with LINQ?

**Comment by nirinchev** [comment]
I've tried to replicate the issue you describe, but it works as expected for me. This is the test I wrote:

```csharp
[Test]
public void Test_1299()
{
    AsyncContext.Run(async () =>
    {
        var inserted = new List<int[]>();
        var deleted = new List<int[]>();

        DateTimeOffset dateStart = DateTimeOffset.UtcNow.Date;
        DateTimeOffset dateEnd = dateStart.AddDays(1);

        var task = new Task1299
        {
            _Reminder = DateTimeOffset.UtcNow
        };

        _realm.Write(() =>
        {
            _realm.Add(task);
        });

        var result = _realm.All<Task1299>()
                           .Where(t => t.Deleted == false &&
                                  t.Completed == false &&
                                  t._Reminder >= dateStart &&
                                  t._Reminder < dateEnd)
                           .OrderBy(t => t._Reminder)
                           .AsRealmCollection();

        Assert.That(result.Count, Is.EqualTo(1));

        var token = result.SubscribeForNotifications((sender, changes, error) =>
        {
            if (changes != null)
            {
                if (changes.InsertedIndices.Any())
                {
                    inserted.Add(changes.InsertedIndices);
                }

                if (changes.DeletedIndices.Any())
                {
                    deleted.Add(changes.DeletedIndices);
                }
            }
        });

        _realm.Write(() => task._Reminder = DateTimeOffset.UtcNow.AddDays(2));
        Assert.That(result.Count, Is.EqualTo(0));
        await Task.Yield();

        Assert.That(inserted.Count, Is.EqualTo(0));
        Assert.That(deleted.Count, Is.EqualTo(1));
        Assert.That(deleted[0].Count, Is.EqualTo(1));
        Assert.That(deleted[0][0], Is.EqualTo(0));

        token.Dispose();
    });
}
```

where `Task1299` looks like this:

```csharp
private class Task1299 : RealmObject
{
    public bool Deleted { get; set; }

    public bool Completed { get; set; }

    [Indexed]
    public DateTimeOffset _Reminder { get; set; }
}
```

Can you take a look and let us know what is different with your setup?

**Comment by tomasszabo** [comment]
@nirinchev 
By seeing your test I realised that this time it's my fault. I forgot to dispose the subscription event (i.e. `token.Dispose()`) and changes on old queries were affecting my newest results. I'm sorry, you can close this issue.

**Comment by nirinchev** [comment]
I'm glad things are working fine for you now!
