### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kronic** [realm/realm-dotnet#1303]
```
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Realms;

namespace RealmTest
{
	public class Test : RealmObject
	{
		[PrimaryKey]
		public int Id { get; set; }

		[Indexed]
		public string A { get; set; }
	}

	internal class Program
	{
		private static void Main(string[] args)
		{
			var dbFileFullName = Path.Combine(Directory.GetCurrentDirectory(), "rr.rr");
			Realm.DeleteRealm(realmConfigurationBase);
			var realmConfigurationBase = new RealmConfiguration(dbFileFullName);

			var t1 = Task.Run(() =>
			{
				using (var instance = Realm.GetInstance(realmConfigurationBase))
				using (var beginWrite = instance.BeginWrite())
				{
					Console.WriteLine("t1 start");
					for (var i = 0; i < 1000000; i++)
					{
						if(i % 2 == 0)
						{
							instance.Add(new Test {Id = i, A = (i * i).ToString()});
						}
					}
					beginWrite.Commit();
					Console.WriteLine("t1 end");
				}
			});
			var t2 = Task.Run(() =>
			{
				using (var instance = Realm.GetInstance(realmConfigurationBase))
				using (var beginWrite = instance.BeginWrite())
				{
					Console.WriteLine("t2 start");
					for (var i = 0; i < 1000000; i++)
					{
						if(i % 2 != 0)
						{
							instance.Add(new Test {Id = i, A = (i * i).ToString()});
						}
					}
					beginWrite.Commit();
					Console.WriteLine("t2 end");
				}
			});

			var t3 = Task.Run(async () =>
			{
				await Task.WhenAny(t1, t2);
				using (var instance = Realm.GetInstance(realmConfigurationBase))
				{
					Console.WriteLine("t3 start");
					for (var i = 0; i < 1000000; i++)
					{
						try
						{
							await Task.Delay(200);
							var count = instance.All<Test>().Count();
							Console.WriteLine($"count = {count}");

						}
						catch(Exception ex)
						{
							var fc = Console.ForegroundColor;
							Console.ForegroundColor = ConsoleColor.Red;
							Console.WriteLine(ex);
							Console.ForegroundColor = fc;
						}
					}
					Console.WriteLine("t3 end");
				}
			});
			Task.WaitAll(t1, t2, t3);
			Console.ReadKey();
		}
	}
}
```

**Comment by AndyDentFree** [comment]
I'm not sure what error you are getting but do **not** try to delete just a Realm with `File.Delete(dbFileFullName);`

Instead do `Realm.DeleteRealm(realmConfigurationBase);`

See [Deleting Realm Files](https://realm.io/docs/xamarin/latest/#deleting-realm-files) - there are more than just one file.

**Comment by kronic** [comment]
I am change code File.Delete(dbFileFullName); -> Realm.DeleteRealm(realmConfigurationBase);
I Have exeption:
System.Exception: Realm accessed from incorrect thread.
   в Realms.RealmResults`1.CreateHandle() в C:\jenkins\workspace\_realm-dotnet_release_1.1.1-S7NL3AZZ3PXAXXTBAUXPTN4JUF4H2MQM3SW4U2P73STDAAHWRYIA\Shared\Realm.Shared\Linq\RealmResults.cs:строка 77
   в System.Lazy`1.CreateValue()
   в System.Lazy`1.LazyInitValue()
   в System.Lazy`1.get_Value()
   в Realms.RealmResults`1.get_ResultsHandle() в C:\jenkins\workspace\_realm-dotnet_release_1.1.1-S7NL3AZZ3PXAXXTBAUXPTN4JUF4H2MQM3SW4U2P73STDAAHWRYIA\Shared\Realm.Shared\Linq\RealmResults.cs:строка 37
   в Realms.RealmResults`1.CreateQuery() в C:\jenkins\workspace\_realm-dotnet_release_1.1.1-S7NL3AZZ3PXAXXTBAUXPTN4JUF4H2MQM3SW4U2P73STDAAHWRYIA\Shared\Realm.Shared\Linq\RealmResults.cs:строка 65
   в Realms.RealmResultsVisitor.VisitConstant(ConstantExpression c) в C:\jenkins\workspace\_realm-dotnet_release_1.1.1-S7NL3AZZ3PXAXXTBAUXPTN4JUF4H2MQM3SW4U2P73STDAAHWRYIA\Shared\Realm.Shared\Linq\RealmResultsVisitor.cs:строка 891
   в Realms.ExpressionVisitor.Visit(Expression exp) в C:\jenkins\workspace\_realm-dotnet_release_1.1.1-S7NL3AZZ3PXAXXTBAUXPTN4JUF4H2MQM3SW4U2P73STDAAHWRYIA\Shared\Realm.Shared\Linq\ExpressionVisitor.cs:строка 77
   в Realms.RealmResultsVisitor.RecurseToWhereOrRunLambda(MethodCallExpression m) в C:\jenkins\workspace\_realm-dotnet_release_1.1.1-S7NL3AZZ3PXAXXTBAUXPTN4JUF4H2MQM3SW4U2P73STDAAHWRYIA\Shared\Realm.Shared\Linq\RealmResultsVisitor.cs:строка 102
   в Realms.RealmResultsVisitor.VisitMethodCall(MethodCallExpression m) в C:\jenkins\workspace\_realm-dotnet_release_1.1.1-S7NL3AZZ3PXAXXTBAUXPTN4JUF4H2MQM3SW4U2P73STDAAHWRYIA\Shared\Realm.Shared\Linq\RealmResultsVisitor.cs:строка 206
   в Realms.ExpressionVisitor.Visit(Expression exp) в C:\jenkins\workspace\_realm-dotnet_release_1.1.1-S7NL3AZZ3PXAXXTBAUXPTN4JUF4H2MQM3SW4U2P73STDAAHWRYIA\Shared\Realm.Shared\Linq\ExpressionVisitor.cs:строка 73
   в Realms.RealmResultsProvider.Execute[T](Expression expression) в C:\jenkins\workspace\_realm-dotnet_release_1.1.1-S7NL3AZZ3PXAXXTBAUXPTN4JUF4H2MQM3SW4U2P73STDAAHWRYIA\Shared\Realm.Shared\Linq\RealmResultsProvider.cs:строка 65
   в System.Linq.Queryable.Count[TSource](IQueryable`1 source)
   в RealmTest.Program.<>c__DisplayClass0_0.<<Main>b__2>d.MoveNext() в C:\Users\kroni\documents\visual studio 2015\Projects\RealmTest\RealmTest\Program.cs:строка 71

**Comment by nirinchev** [comment]
Because you are using Task.Delay in t3, the continuation is dispatched on a different thread, so accessing the Realm is no longer valid (as realms are bound to the thread they were created on). Since you're on a background thread, there's no reason to use Task.Delay and instead you could use Thread.Sleep.
