### ISSUE TITLE
DOC: Confused about Delete and SubscribeForNotifications

### ISSUE THREAD

**Issue by DrifterApps** [realm/realm-dotnet#1307]
Hi,

I'm using Realm 1.1.1 and when I remove an object from my Realm, my query to which I registered to SubscribeForNotifications, I receive a notification but the changes parameter is always NULL.

The documentation states that:

> The changes parameter will be null the first time the callback is invoked with the initial results. 

What does that mean? And why would I not receive the notification with the object that was deleted?

Thanks!

**Comment by Shaddix** [comment]
Regarding Deleted objects: https://github.com/realm/realm-dotnet/issues/1286

**Comment by nirinchev** [comment]
You should definitely receive a notification with deleted indices populated. Can you share your code where you're subscribing and deleting the object? Keep in mind that you need to keep a reference to the subscription token for as long as you want to receive notifications. Letting it get garbage collected is the most common reason for unexpected behavior, but I'd be happy to look into your specific scenario.

**Comment by DrifterApps** [comment]
Actually I was unit testing my classes using the Android Runner. I guess I did not understand the differences between the Looper Thread and the background thread. When I call realm.Refresh() it refreshes my query and I do receive the changes parameter.

The one thing you can maybe clarify is the following statement:

> Realms are also refreshed when write transactions are committed with Transaction.Commit().

On a background thread, do I still have to call Realm.Refresh() or is the Transaction.Commit() suppose to do it for me?? It doesn't seem to do that when I tried different tests.

Unless you know what I'm understanding wrong, I will post my code when I get home tonight.

Thanks!!

**Comment by nirinchev** [comment]
When beginning a transaction, the Realm is definitely refreshed. Since write transactions are blocking (i.e. you can't have more than one at a time), when committing that transaction, you are definitely on the latest version, so no refreshing is needed. Perhaps the documentation can be more explicit about it, I'll look into that later today.

**Comment by nirinchev** [comment]
I hope this has answered your question. Feel free to reopen if that's not the case.
