### ISSUE TITLE
Unmanaged memory leak

### ISSUE THREAD

**Issue by regetk** [realm/realm-dotnet#1312]
![realmmemory2](https://cloud.githubusercontent.com/assets/1598510/24390539/468b3560-1392-11e7-8d57-8d59884ddf9c.PNG)

When load object to memory (row 27 in pic), it will remain there.
As seen, heap size and object count is almost same, but process memory will increase until all memory is consumed.

This testapp is .NET 4.6.1 console project.
Object count in Realm is ~6000, Realm size is ~ 164 MB (compact is not done). This process memory consumption depends of Realm size. With big Realm size, it is better visible. 
SmaUiRecord is POCO containing only int, string, bool and DatetimeOffset values (17 fields) 

Maybe simpler example
![realmmemory3](https://cloud.githubusercontent.com/assets/1598510/24390555/5e382600-1392-11e7-8e85-baa7fc2f5508.PNG)

RealmUtils.GetRealm() is same as Realm.GetInstance.

## Version of Realm and Tooling
- Visual Studio 2015 (tested with Proffessional and Community versions)
- Realm.Database 1.1.1  
- .NET 4.6.1
- OS Win 10 64 bit and Win 7 64 bit

**Comment by nirinchev** [comment]
Thanks for the report, I was able to reproduce it. Here's the code I used:

```csharp
using System;
using System.IO;
using System.Reflection;
using System.Threading;
using Realms;

namespace Issue1312
{
    class Program
    {
        private static string RealmPath
        {
            get
            {
                var currentFolder = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
                return Path.Combine(currentFolder, "temp.realm");
            }
        }

        static void Main(string[] args)
        {
            Populate();
            while(true)
            {
                using (var realm = Realm.GetInstance(RealmPath))
                {
                    var foos = realm.All<Foo>();
                    foreach (var item in foos)
                    {
                        var key = item.SomeString;
                    }
                }

                Thread.Sleep(10);
            }
        }

        private static void Populate()
        {
            var config = new RealmConfiguration(RealmPath);
            Realm.DeleteRealm(config);

            using (var realm = Realm.GetInstance(config))
            {
                realm.Write(() =>
                {
                    for (var i = 0; i < 10000; i++)
                    {
                        realm.Add(new Foo
                        {
                            SomeString = "Some String" + i,
                        });
                    }
                });
            }
        }

        public class Foo : RealmObject
        {
            public string SomeString { get; set; }
        }
    }
}
```
