### ISSUE TITLE
Deleted object is not revived after a transaction rollback

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-dotnet#1332]
The following snippet fails:
```csharp
var person = new Person();
_realm.Write(() => _realm.Add(person));

using (var transaction = _realm.BeginWrite())
{
    _realm.Remove(person);
    transaction.Rollback();
}

var test = person.FirstName;
```

It looks like the row reference is removed upon deletion and not restored after transaction rollback.

**Comment by papafe** [comment]
This works with the current master, but I have made a PR to add a test exactly for this.
