### ISSUE TITLE
System.EntryPointNotFoundException: mono_get_runtime_build_info Realm 1.2.0 on Android

### ISSUE THREAD

**Issue by BergQuester** [realm/realm-dotnet#1335]
I recently updated Realm from 1.1.1 to 1.2.0. Before the update both iOS and Android loaded fine. After the update I get the a crash only on Android:

I have tried cleaning the project, deleting the app from my devices and rebooting devices.

## Goals

A successful update of the Realm nuget that does not crash so that I can use an updated compacted Realm file produced by the Realm Browser app.

## Expected Results

That Realm 1.2.0 does not crash on Android

## Actual Results

> System.EntryPointNotFoundException: mono_get_runtime_build_info
>   at at (wrapper managed-to-native) System.Runtime.InteropServices.RuntimeInformation:mono_get_runtime_build_info ()
>   at System.Runtime.InteropServices.RuntimeInformation.get_FrameworkDescription () [0x00000] in /Users/builder/data/lanes/4009/3a62f1ea/source/mono/mcs/class/System.Runtime.InteropServices.RuntimeInformation/System.Runtime.InteropServices/RuntimeInformation.cs:45
>   at Realms.NativeCommon.Initialize () [0x00000] in <550621f4184f47c0bdfce087c391c293>:0
## Steps to Reproduce

I started with a clean git status and simply updated the nuget for the Android, iOS and PCL projects in Xamarin Studio.

## Code Sample

The code that is crashing is the return statement here:

	var config = new RealmConfiguration() { SchemaVersion = 2 };

	return Realm.GetInstance(config);

## Version of Realm and Tooling

- Flavor:
  - [x] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: N/A
- Client SDK Version: Xamarin Community 6.2.1, Realm Mobile Database 1.2.0
- Client OS & Version: Android 4.2.2, 6.0, 7.1.2

**Comment by nirinchev** [comment]
That's very surprising, considering we have a try-catch block around that piece of code, precisely for that reason: https://github.com/realm/realm-dotnet/blob/master/Realm/Realm/Native/NativeCommon.cs#L80

Can you share what devices you're using that exhibit this behavior?

**Comment by BergQuester** [comment]
Samsung Galaxy Tab 3 Lite w/ 4.2.2
BLU R1 HD w/ 6.0
LG Nexus 5x w/ 7.1.2

**Comment by nirinchev** [comment]
I believe I have fixed the problem, however, without being able to reproduce it, I can't verify that the fix actually works on your devices. Can you try to update to our prerelease package and let us know if you experience the same problem: https://drive.google.com/file/d/0B45yfBWnWXwALVRLMl9RM29Za28/view?usp=sharing

**Comment by BergQuester** [comment]
Tested on all of my Android devices and the pre-release appears to fix the issue.

**Comment by BergQuester** [comment]
Thank you for your quick response!

**Comment by ChrisWay** [comment]
I've had the same issue with my Xamarin Forms app, but I've only run it in the Android 7.1 x86 emulator, so you might be able to reproduce it there @nirinchev. I've not had a chance to test the pre-release version yet but it hopefully works as @BergQuester says.
