### ISSUE TITLE
Crash with MvxRecyclerView using MvvmCross and Realm 1.2.0

### ISSUE THREAD

**Issue by voluntas88** [realm/realm-dotnet#1343]
After updating from 1.1.1 to 1.2.0 version, there is crash during scrolling back with MvxRecyclerView (MvvmCross https://github.com/MvvmCross/MvvmCross) and RealmObjects as source.

Sample project, to reproduce the crash: https://github.com/voluntas88/RealmMvvmCrossRecyclerView
MvxRecyclerView has collection of RealmObjects as Source. The MvxRecyclerView item is binded to RealmObject properties.
After app launch, MvxRecyclerView is correctly loaded and populated with data.
Scroll list forward and then start to scrolling it back. At that moment the crash is occurred with error:

>  Got a SIGSEGV while executing native code. This usually indicates
>  a fatal error in the mono runtime or one of the native libraries 
>  used by your application.
> 
>  F/libc    ( 5719): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x8 in tid 5747 (Thread-47753) 

 Version 1.1.1 works well with sample code.

**Comment by EmmanVazz** [comment]
I have the same issue however haven't been able to make a repo to reproduce. Hopefully the repo provided is enough to track down the issue.

**Comment by justinimel** [comment]
Same.

**Comment by nirinchev** [comment]
Thanks for the report and the repro case! I'll try to look into it tomorrow.

**Comment by EmmanVazz** [comment]
Is there any news on this issue?

**Comment by EmmanVazz** [comment]
Seems like this is affecting a hand full of us. Any update? Anything helpful in the latest 1.2.1 release? Thanks!

**Comment by nirinchev** [comment]
Unfortunately 1.2.1 was more of a maintenance release to update the Fody dependency, so no progress there. On the bright side, we've recently fixed a few bugs related to notifications (which is the underlying cause of the crash here). If you're willing to test a pre-release nuget, [here it is](https://drive.google.com/file/d/0B45yfBWnWXwAMXVoUWw2N0JKczQ/view?usp=sharing). With this version, I am no longer able to reproduce the crash on a simulator.

Be aware though, that it's a prerelease version, so it hasn't been thoroughly tested and may introduce regressions or other issues.

**Comment by UKDeveloper99** [comment]
I'm getting this crash as well, will give the pre-release nuget a go and see if that helps. Cheers.

**Comment by UKDeveloper99** [comment]
That seems to be working although I'm now getting a `System.ObjectDisposedException`. Will investigate the cause of that and report back.

**Comment by nirinchev** [comment]
Are you getting it with the repro project from the first post or with your own app? I think the only realm object that may throw it is the `Realm` class if you attempt to call methods that should reach the database (i.e. most public methods). I'll leave the issue open a few more days so more people can check if the crashes disappear.

**Comment by EmmanVazz** [comment]
Gave it a test on iOS and droid. The issue seems to be solved. Also I don't get the System.ObjectDisposedException exception that was mentioned.

**Comment by UKDeveloper99** [comment]
One of my own projects, the `MvxRecyclerView` is bound to an `IRealmCollection`. About every 40 seconds the database updates all the objects in the bounded list with new (unmanaged versions) using `Add(update:true, obj)`. The exception seems to firing on the line `_realm.Write(() => ...)`. I'm getting cannot access a disposed object `System.ObjectDisposedException` and the object name is `MvvmCross.Binding.Droid.Views.MvxAdapter`. If I just leave it updating it seems to occur randomly, so it could update the realm objects 5 or 6 times before the exception occurs. Any ideas? I'll attempt to debug it further.

**Comment by UKDeveloper99** [comment]
```
mvx:Warning:130.37 Exception masked during Adapter RealNotifyDataSetChanged ObjectDisposedException: Cannot access a disposed object.
Object name: 'MvvmCross.Binding.Droid.Views.MvxAdapter'.
	  at Java.Interop.JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self) [0x00030] in /Users/builder/data/lanes/4468/b16fb820/source/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.cs:153 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00002] in /Users/builder/data/lanes/4468/b16fb820/source/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:21 
  at Android.Widget.BaseAdapter.NotifyDataSetChanged () [0x00000] in /Users/builder/data/lanes/4468/b16fb820/source/monodroid/src/Mono.Android/platforms/android-25/src/generated/Android.Widget.BaseAdapter.cs:297 
  at MvvmCross.Binding.Droid.Views.MvxAdapter.RealNotifyDataSetChanged () [0x00000] in <6a0c851a22864d0993089d65320a630c>:0 . Are you trying to update your collection from a background task? See http://goo.gl/0nW0L6
```

**Comment by UKDeveloper99** [comment]
I believe the exception is unrelated, feels like a by product of starting background tasks every 10 seconds to do these web requests that fetch the data to update the realm list. (No I'm not updating the realm on the background thread, just to clarify). At some point something is getting garbage collected. I think you can consider this issue fixed, the original issue has disappeared.

**Comment by UKDeveloper99** [comment]
So I fixed the issue that was giving me `System.ObjectDisposedException`, on the off-chance that it might help anyone reading this topic I'll explain the cause and solution. A lot of the time with MvvmCross there is a need to subclass the adapter to add some custom logic. In my particular case I had my own custom adapter subclass inherited from `Mvx.Adapter`. Setting a custom adapter with mvvmcross requires you to set it programmatically in code, on the widget. E.g. For an `Mvx.GridView` you would do `gridview.Adapter = new MyCustomAdapter()` then create the binding programmatically because the binding can't be done via XML. 

In my case I had forgotten to remove the `mvx:bind` call from the XML file, so when the view was inflated the widget was databinded to the original mvx adapter **and then** immediately after to the new custom adapter.  Because the original adapter was most likely garbage collected after a while, somehow Realm was still trying to reference it for the first binding. I guess Realm was then propagating this `System.ObjectDisposedException` when it tried to fire collection changed notifications on the original adapter, which no longer existed. 

So there you go, make sure you remove you're xml bindings if you bind in code =)
