### ISSUE TITLE
Realm 1.2 does not work in win 7/ win server 2008 R2/win server 2012 R2

### ISSUE THREAD

**Issue by regetk** [realm/realm-dotnet#1345]
## Goals, Expected Results

Realm 1.2 is working in win 7/ win server 2008 R2/win server 2012 R2

## Actual Results
Realm 1.2 app working only in Windows 10

**Other windowses end up with error:**
Unable to load DLL 'realm-wrappers': The specified procedure could not be found. (Exception from HRESULT: 0x8007007F)

**StackTrace:**    at Realms.NativeCommon.register_notify_realm_changed(NotifyRealmCallback callback)
   at Realms.Realm..cctor()
**TargetSite:** Void register_notify_realm_changed(NotifyRealmCallback)}

**Realm 1.2 project Packages list:**
 Packages:
"DotNetCross.Memory.Unsafe" version="0.2.3.4" targetFramework="net461" />
  "Fody" version="1.29.4" targetFramework="net461" developmentDependency="true" />
 "Realm.Database" version="1.2.0" targetFramework="net461" />
  "Realm.DataBinding" version="1.0.0" targetFramework="net461" />
 "Remotion.Linq" version="2.1.1" targetFramework="net461" />
  "System.Collections" version="4.3.0" targetFramework="net461" />
 "System.Console" version="4.3.0" targetFramework="net461" />
  "System.Diagnostics.Debug" version="4.3.0" targetFramework="net461" />
  "System.Diagnostics.Tools" version="4.3.0" targetFramework="net461" />
  "System.Dynamic.Runtime" version="4.3.0" targetFramework="net461" />
  "System.Globalization" version="4.3.0" targetFramework="net461" />
  "System.IO.FileSystem" version="4.3.0" targetFramework="net461" />
 "System.IO.FileSystem.Primitives" version="4.3.0" targetFramework="net461" />
  "System.Linq" version="4.3.0" targetFramework="net461" />
 "System.Linq.Expressions" version="4.3.0" targetFramework="net461" />
  "System.Linq.Queryable" version="4.3.0" targetFramework="net461" />
  "System.ObjectModel" version="4.3.0" targetFramework="net461" />
  "System.Reflection" version="4.3.0" targetFramework="net461" />
  "System.Reflection.Extensions" version="4.3.0" targetFramework="net461" />
  "System.Reflection.Primitives" version="4.3.0" targetFramework="net461" />
  "System.Reflection.TypeExtensions" version="4.3.0" targetFramework="net461" />
  "System.Runtime" version="4.3.0" targetFramework="net461" />
  "System.Runtime.Extensions" version="4.3.0" targetFramework="net461" />
  "System.Runtime.InteropServices" version="4.3.0" targetFramework="net461" />
  "System.Runtime.InteropServices.RuntimeInformation" version="4.3.0" targetFramework="net461" />
  "System.Threading" version="4.3.0" targetFramework="net461" />

## Steps to Reproduce
Create simple console app.
Build and run it.
When using Realm Database ver 1.1.1, then app is working.
When using Realm Database ver 1.2.0 then "missing dll" error happens. 

## Code Sample

 

>  class Program
>     {
>         static void Main(string[] args)
>         {
>             Realm realm = Realm.GetInstance();
>             var collection = realm.All<TestObject>();
>             Console.ReadLine();
>         }
>     }
> 
>     class TestObject : RealmObject
>     {
>         public string TestString { get; set; }
>     }

**OS tested:** win 10 , win server 2008 R2, win server 2012 R2, Win 7 - all 64 bit
Realm 1.2 runs only in Win 10

**Dev. environments:**
Visual Studio 2015 Pro and Community

**Build settings:**
Debug | Any CPU

**Comment by fealebenpae** [comment]
We only support Windows 8.1 and upwards as a minimum target. Server 2012 R2 should be compatible with 8.1, but I don't have access to a machine running that to test and debug. We definitely don't support Windows 7 and Server 2008, though.

**Comment by fealebenpae** [comment]
Update: in 1.2.0 we shipped a new version of the Realm Core (the database engine) which seems to be now using newer Windows APIs.

**Comment by regetk** [comment]
Thank you for answering,

I hope you update "Prerequisites" section too, with this very important info.
Right now is there  "Windows Desktop (win32-x86 and win64-x64)."

**Comment by nirinchev** [comment]
The website update is being deployed and you'll be able to see the updated prerequisites shortly. Thanks for reporting this!
