### ISSUE TITLE
PlatformNotSupportedException occurs

### ISSUE THREAD

**Issue by wyvern610** [realm/realm-dotnet#1346]
Why realm so buggy..

## Expected Results
No excetpion

## Actual Results
PlatformNotSupportedException occured.

The PCL build of Realm is being linked which probably means you need to use NuGet or otherwise link a platform-specific Realm.dll to your main application.

>	Realm.dll!Realms.Schema.RealmSchema.AddDefaultTypes(System.Collections.Generic.IEnumerable<System.Type> types)	不明
 	WpfRealmTestApp.exe!WpfRealmTestApp.App.Main()	不明
 	[ネイティブからマネージへの移行]	
 	[マネージからネイティブへの移行]	
 	mscorlib.dll!System.AppDomain.ExecuteAssembly(string assemblyFile, System.Security.Policy.Evidence assemblySecurity, string[] args)	不明
 	Microsoft.VisualStudio.HostingProcess.Utilities.dll!Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()	不明
 	mscorlib.dll!System.Threading.ThreadHelper.ThreadStart_Context(object state)	不明
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	不明
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	不明
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	不明
 	mscorlib.dll!System.Threading.ThreadHelper.ThreadStart()	不明

## Steps to Reproduce

1.Create new WPF project.
2.Then Copy and Paste the followings

`

    public partial class MainWindow : Window
    {
        private Realm realm;

        public MainWindow()
        {
            InitializeComponent();
            var baseDir = System.IO.Path.GetDirectoryName(Environment.GetCommandLineArgs()[0]);
            var realmConfig = new RealmConfiguration(System.IO.Path.Combine(baseDir, "test.realm"));
            realmConfig.ShouldDeleteIfMigrationNeeded = true;
            realm = Realm.GetInstance(realmConfig);
        }
    }

    class Family : RealmObject
    {
        [Required]
        [Indexed]
        public string Name { get; set; }

        public IList<FamilyMember> Members { get; }
    }

    class FamilyMember : RealmObject
    {
        public Family Family { get; set; }
        [Required]
        [Indexed]
        public string Name { get; set; }
    }

`

3.Run and PlatformNotSupportedException occurs

## Version of Realm and Tooling

Microsoft Visual Studio Community 2015
Version 14.0.25425.01 Update 3
Microsoft .NET Framework
Version 4.6.01586

Realm v1.2.0
Realm.Database v1.2.0
Realm.DataBinding v1.2.0

**Comment by nirinchev** [comment]
Hi @wyvern610, Realm 1.2.0 will work with .NET Framework 4.6.1 and newer. I assume that you're targeting an older version of the .NET Framework, which is why NuGet incorrectly picks up the PCL assembly instead of the .NET Standard one.

You can either downgrade to Realm 1.1.1 which supports 4.5.1, or upgrade your target framework to a newer one (we recommend 4.6.2). In the near future, we plan to re-enable older .NET Framework versions, but the Visual Studio tooling is not mature enough to allow us to do it yet.

**Comment by wyvern610** [comment]
Hi.
After upgrading target framework to newer one.
It works fine.

Thx a lot.
