### ISSUE TITLE
Realm Weaver fails on VSTS (Realm 1.2.0)

### ISSUE THREAD

**Issue by Qwin** [realm/realm-dotnet#1352]
Having issues with Realm Weaver, I am using realm 1.2.0 and it works locally with my Xamarin.Android using Xamarin Studio. (Mac OS) However running my build on VSTS (VisualStudio.com), it is failling with the below error. (it was working fine with 0.76.1) The only thing I could find on google was the this thread : (https://github.com/Fody/MethodTimer/issues/25)

> 2017-04-12T23:36:37.9359480Z /Users/vso113222/vsts-agent/_work/1/s/packages/Fody.1.29.4/build/portable-net+sl+win+wpa+wp/Fody.targets (FodyTarget target) ->
> 2017-04-12T23:36:37.9368770Z 
> 2017-04-12T23:36:37.9383260Z 	: error : Fody: An unhandled exception occurred:
> 2017-04-12T23:36:37.9400580Z Exception:
> 2017-04-12T23:36:37.9424230Z Format of the executable (.exe) or library (.dll) is invalid.
> 2017-04-12T23:36:37.9448950Z StackTrace:
> 2017-04-12T23:36:37.9461340Z 
> 2017-04-12T23:36:37.9473650Z 
> 2017-04-12T23:36:37.9498040Z Server stack trace: 
> 2017-04-12T23:36:37.9521520Z   at Mono.Cecil.PE.ImageReader.ReadImage () [0x00013] in <b5a52cab1f0046ce9f68342127787868>:0 
> 2017-04-12T23:36:37.9536580Z   at Mono.Cecil.PE.ImageReader.ReadImageFrom (System.IO.Stream stream) [0x00007] in <b5a52cab1f0046ce9f68342127787868>:0 
> 2017-04-12T23:36:37.9553710Z   at Mono.Cecil.ModuleDefinition.ReadModule (System.IO.Stream stream, Mono.Cecil.ReaderParameters parameters) [0x00022] in <b5a52cab1f0046ce9f68342127787868>:0 
> 2017-04-12T23:36:37.9571360Z   at Mono.Cecil.ModuleDefinition.ReadModule (System.String fileName, Mono.Cecil.ReaderParameters parameters) [0x0000a] in <b5a52cab1f0046ce9f68342127787868>:0 
> 2017-04-12T23:36:37.9586840Z   at Mono.Cecil.ModuleDefinition.ReadModule (System.String fileName) [0x00007] in <b5a52cab1f0046ce9f68342127787868>:0 
> 2017-04-12T23:36:37.9602190Z   at IsolatedContainsTypeChecker.Check (System.String assemblyPath, System.String typeName) [0x0000d] in <f6f9069078364b4db60945017a527c4a>:0 
> 2017-04-12T23:36:37.9618520Z   at (wrapper xdomain-dispatch) IContainsTypeChecker:Check (object,byte[]&,byte[]&,string,string)
> 2017-04-12T23:36:37.9627160Z 
> 2017-04-12T23:36:37.9641620Z Exception rethrown at [0]: 
> 2017-04-12T23:36:37.9660810Z   at (wrapper xdomain-invoke) IContainsTypeChecker:Check (string,string)
> 2017-04-12T23:36:37.9676860Z   at ContainsTypeChecker.Check (System.String assemblyPath, System.String typeName) [0x00000] in <43b4cdd4452d4d25962bc83cad41de84>:0 
> 2017-04-12T23:36:37.9692350Z   at Processor.ShouldStartSinceFileChanged () [0x00000] in <43b4cdd4452d4d25962bc83cad41de84>:0 
> 2017-04-12T23:36:37.9707100Z   at Processor.Inner () [0x00029] in <43b4cdd4452d4d25962bc83cad41de84>:0 
> 2017-04-12T23:36:37.9721790Z   at Processor.Execute () [0x00034] in <43b4cdd4452d4d25962bc83cad41de84>:0 
> 2017-04-12T23:36:37.9736200Z Source:
> 2017-04-12T23:36:37.9753040Z Mono.Cecil

**UPDATE:**
I got some more information after lots of tries. The last version that works on VSTS is 1.0.4. It led me to believe that this update : https://github.com/realm/realm-dotnet/commit/e2234306f9fc1030dd0413584ae93a40a3c055ed#diff-de304777ca445e8ac7cd4bfe580980da
Might have broken it when shifting from  :
Fody.1.29.4\Mono.Cecil.dll to Mono.Cecil.0.9.6.4 direct reference. (I wonder which version of Mono.Cecil Fody had, that one seems to work. I think that's why Fody added the binaries themselves instead of adding Mono.Cecil directly. )

**Comment by nirinchev** [comment]
That's interesting. The linked patch should not be affecting Fody - it's only related to the WeaveRealmAssembly task. It's a public holiday here in Denmark, but we'll look into it next week.

**Comment by Qwin** [comment]
@nirinchev Any news on this ?

**Comment by nirinchev** [comment]
Unfortunately no, we haven't had the time to investigate this further. On a related note, in Realm 1.2.1 we updated to Fody 2.0.6 which uses a newer Cecil version, so it might be worth giving it a shot.

**Comment by SirDev** [comment]
@Qwin I have this working on VSTS with CI/CD, and it works properly. I had to switch to the hosted build agent (not hosted 2017) - and this worked properly. Also with 1.2.0.

**Comment by Qwin** [comment]
@SirDev it works now for me too by using my own private build agent. I think they recently updated the VSTS hosted agent so now it might work.

**Comment by nirinchev** [comment]
Thanks for the update! I'll close the issue, but if you encounter it again, feel free to reopen it.
