### ISSUE TITLE
Native linking failed MTOUCH ERROR -framework Security

### ISSUE THREAD

**Issue by UKDeveloper99** [realm/realm-dotnet#1359]
## Goals

Build for iPhone **device** in Debug mode.

## Expected Results

Build successful

## Actual Results

<img width="871" alt="screen shot 2017-04-18 at 17 26 55" src="https://cloud.githubusercontent.com/assets/11443031/25141707/4341637c-245c-11e7-94ca-6dc2859118fd.png">

```
    Undefined symbols for architecture arm64:
      "_RtlGetVersion", referenced from:
          wrapper_managed_to_native_Interop_NtDll_RtlGetVersion_Interop_NtDll_RTL_OSVERSIONINFOEX_ in System.Runtime.InteropServices.RuntimeInformation.dll.arm64.o
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

## Steps to Reproduce

Build in debug mode for a device, not simulator.

## Code Sample

Repro project here: https://github.com/UKDeveloper99/RealmNativeLinkingIssue

## Version of Realm and Tooling

- Realm version 1.0.2
- Xamarin Studio: latest **beta** channel (may occur in stable, not sure).
- Xcode version 8.2.1

**Comment by UKDeveloper99** [comment]
Note that the error didn't occur until I put some Realm code directly in to the iOS project. See `appdelegate.cs`

**Comment by istx25** [comment]
Hey @UKDeveloper99! Thanks for reaching out. Someone will review what you've shared and follow-up soon. Cheers!

**Comment by istx25** [comment]
Actually, in the meantime, would you be able to test if this problem occurs in the stable version of Xamarin Studio? Thanks.

**Comment by nirinchev** [comment]
I tested it with the stable version and it's reproducible.

**Comment by nirinchev** [comment]
This is caused by our usage of `System.RuntimeInformation`, which was clearly a mistake. Please use the pre-release package linked in https://github.com/realm/realm-dotnet/issues/1335#issuecomment-291873628 as it works around it.

**Comment by UKDeveloper99** [comment]
Got it, thanks.
