### ISSUE TITLE
DateTimeOffset property of RealmObject is always saved as Default Value

### ISSUE THREAD

**Issue by superphil0** [realm/realm-dotnet#1362]
## Goals
Trying to set DateTimeOffset on RealmObject

## Expected Results
After writing to realm, the object should have the set time

## Actual Results
Defaults to 1/1/0001

## Steps to Reproduce
Assign a DateTimeOffset and write it to realm DB from within Xamarin android application
read said object from DB and compare DateTimeOffset

## Code Sample
```c#
 public  class MyObj: RealmObject
    {
        public DateTimeOffset Time { get; set; }

    }


var db = Realm.GetInstance("mydb");
using (var transaction = db.BeginWrite())
            {
                db.Add(new MyObj
                {
                    Time = DateTimeOffset.Now // is {4/21/2017 3:16:06 PM +00:00}
                });
                transaction.Commit();
            }
var x = db.All<MyObj>().ElementAt(0).Time
// x  is 0001/1/1 but should be NOW
```
## Version of Realm and Tooling

- Realm Object Server Version: not used 
- Flavor:
  - Realm Developer

- Client SDK Version: Realm.Database 1.2.0
- Client OS & Version: Tried on android 7.1 (emulator) and android 6.0 (Galaxy s6)

**Comment by nirinchev** [comment]
I've tried replicating the issue and was unable to do so. Judging from the way you're accessing the object - `db.All<MyObj>().ElementAt(0)`, it makes me think it's possible you've persisted an object with default datetime the first time you ran the application and you're inspecting that object every time. To verify if that's the case, you can call `db.RemoveAll()` before adding the object. Keep in mind that this will remove all your objects from the database.

If the behavior persists even after you've cleared the database, could you please isolate it in a repro project so we can take a look.

**Comment by superphil0** [comment]
Hey,

db.RemoveAll() was part of my code
I wrote a minimal test project here https://github.com/superphil0/realmxamarin/tree/master

Weirdly enough I can't run it since the application in Debug mode is stuck at Realm.GetInstance() (described here https://github.com/realm/realm-java/issues/610)

I tried changing the namespace in the android manifest files in the hope of creating new files, it didn't help.
If I run it in Release mode the app simply crashes.

Tested both on real device and emulator

**Comment by superphil0** [comment]
I found the problem, I updated some 15 packages which lead to breaking Realm in multiple ways.

You can see the changes in https://github.com/superphil0/realmxamarin/tree/master
the first commit is broken, the second works with downgraded packages

when will this be addressed?

**Comment by nirinchev** [comment]
The only unsupported package I can see is Fody 2.x, but I'd expect the build to fail when upgrading to that one. We're working on a few issues with the latest Fody and hope to release a compatible version in the near future.

Are you able to reproduce your original issue after downgrading packages?

**Comment by superphil0** [comment]
No I was not, me guess it that realm silently failed with the unsupported
package, which is not quite a bug, but a bit annoying to find out. Maybe
you can add a runtime check of supported dependency versions to at least
make this visible?

**Comment by nirinchev** [comment]
Unfortunately, unless we have a repro project, we can't know what to check for. The only known dependency incompatibility is Fody 2.x and that package is used only during compilation - at runtime we have no knowledge of it.

**Comment by nirinchev** [comment]
We've recently released a version that works with Fody 2.x, so the dependency issue should be solved. If you're able to reproduce the original problem, feel free to reopen this issue.
