### ISSUE TITLE
RemoveAll(..) issues.

### ISSUE THREAD

**Issue by UKDeveloper99** [realm/realm-dotnet#1369]
I'm sorry for the rather vague nature of this ticket. But that's because all the issues I've experienced with `_realm.RemoveAll(..)` have been in wildly different circumstances and all hard to isolate the specific issue.

I've had 3 separate issues with this function. Two have occurred from usage in a migration scenario. Directly on the new realm object. The other has been causing some strange issues with MvvmCross which I have described [here](https://github.com/realm/realm-dotnet/issues/1204). The migrations issue has indicated that my app in the wild have rogue data leftover from the old database when migrations occur. It's causing me a lot of issues and unhappy clients. I don't have an easy way to reproduce it, nor do I want to make a test project.

I just want a solid bug-free way to empty the database no questions asked. Whether that is on a migration or within the app lifecycle.

Someone needs to investigate and test `_realm.RemoveAll` with large amounts of data and look for inconsistencies.

**Comment by istx25** [comment]
Hi @UKDeveloper99. Thanks for reaching out. 

Would you be able to edit your issue to follow the template from https://github.com/realm/realm-dotnet/issues/new and even if you can not provide all of the details, if there is anything that you can think of (that wasn't included above), please do. Please also include the versions of Realm and your tooling so we know what we're dealing with.

Thanks!

**Comment by bmunkholm** [comment]
It appears the user is not able to provide more details or has come past this in some way.
@nirinchev Do we have anything to go on for this?

**Comment by UKDeveloper99** [comment]
I'm waiting for some free time to create a repo project.

**Comment by nirinchev** [comment]
I believe this has to do MVVMCross trying to access objects after they've been deleted. Unfortunately, we haven't been able to reproduce it, so I'll put it on hold. When you're able to create a repro project that we can debug locally, do share it and we'll take it from there.
