### ISSUE TITLE
Sorting by an interface property fails with KeyNotFoundException

### ISSUE THREAD

**Issue by PedroLV** [realm/realm-dotnet#1373]
Hello:

This code was working on previous xamarin version , but now on Realm Xamarin 1.2 fails.

## Goals
Execute a simple query like this:

`T obj = realm.All<T>().OrderByDescending(x => x.Id).FirstOrDefault();`

## Expected Results
Get an object from database. This code was working on realm 1.1.1

The query produces an exception

Error --> **System.Collections.Generic.KeyNotFoundException**: The given key was not present in the dictionary.
  at System.ThrowHelper.ThrowKeyNotFoundException () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/10.8.0.175/src/mono/mcs/class/referencesource/mscorlib/system/throwhelper.cs:68 
  at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x00021] in ....

## Steps to Reproduce
Create a simple class, and run the code.

## Code Sample
```
public class Dog : RealmObject, IDocument
    {
        [PrimaryKey]
        public Int32 Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        
    }

public interface IDocument
    {
         Int32 Id { get; set; }
    }
//code
var realm = Realm.GetInstance();

            realm.Write(() =>
            {
                try
                {
                    Int32 newId = NewId<Dog>(realm); 
                  
                    realm.Add(new Dog { Id = newId, Name = "Rex", Age = 1 });
                }
                catch(System.Exception ex)
                {
                    Debug.WriteLine("Error --> " + ex.ToString()); 
                }
            });

private  Int32 NewId<T>( Realm realm) where T : Realms.RealmObject, IDocument
        {
            try
            {
                 //this query gets an exception
                T obj = realm.All<T>().OrderByDescending(x => x.Id).FirstOrDefault();
                if (obj == null)
                {
                    return 1;
                }
                return obj.Id + 1;
            }
            catch (InvalidOperationException)
            {
                return 1;
            }
        }


```

## Version of Realm and Tooling
Realm 1.2 Xamarin
Visual Studio 2017
Xamarin IOS

* Realm Object Server Version: none
* Flavor: Developer
* Server OS & Version: Windows 10
* Client SDK Version: Xamarin IOS SDK 10.8.0.174
* Client OS & Version: IOS 10.3

**Comment by istx25** [comment]
Hi @PedroLV. Thank you for reaching out. I wanted to let you know that we've seen your issue and that someone will follow-up with you soon. However, in the meantime, would you be able to edit your issue to provide us with **all** of the versions that you're using. You've only provided a few that we ask for. Thanks!

**Comment by nirinchev** [comment]
This is a bug with our sorting logic in `RealmResultsVisitor.TraverseSort` - we're using `expression.Member.DeclaringType` which in this case is reported as the interface (`IDocument`) instead of the runtime type (`Dog`).

**Comment by daawaan** [comment]
Hello, I came across this bug recently with using `OrderBy` in a generic method. As a workaround, I manually created the expression for the query instead. Are there any reasons why the `ReflectedType` isn't used instead of the `DeclaringType`?

**Comment by papafe** [comment]
As an additional note, we are planning a rework of the LINQ provider implementation, so the internals will probably look different in the future
