### ISSUE TITLE
Custom initialization of RealmObject

### ISSUE THREAD

**Issue by Dids** [realm/realm-dotnet#1382]
## Goals
I work with a lot of hierarchical RealmObjects, and there are times when one or more parent objects need to be notified when a child changes (including child properties).
As I work in Xamarin.Forms, I also need it to be compatible with data binding, so changes are automatically reflected on the UI without any/much manual intervention.

## Expected Results
So far I've been trying to do this in the parent object's constructor, subscribing for notifications in the children IList, then manually raising property change notifications from that, but this doesn't work with Realm, since the object is (most of the time) not managed when the constructor is called. It does seem to work sometimes, and when it does, it works very well, but it's far from reliable and really shouldn't even be working.

@nirinchev mentioned in the Xamarin Slack that a virtual initializer for RealmObjects would apply to this situation, if it would be called (internally) after the object is managed.

From what I can tell, this should solve my issue 100%.

**Comment by nirinchev** [comment]
Here's a link to the [prerelease nuget](https://drive.google.com/file/d/0B45yfBWnWXwAV19kWXhvZmVrQ0E/view?usp=sharing).
