### ISSUE TITLE
Windows 7 Support

### ISSUE THREAD

**Issue by kjeremy** [realm/realm-dotnet#1385]
## Goals

Support Windows 7.  Many people cannot upgrade to Windows 10 and are still stuck on Windows 7.  It would be nice if they could use Realm.

## Expected Results

Support Windows 7

**Comment by dubstylee** [comment]
Couldn't they use Realm for WPF on Windows 7? Or is there some other dependency that is not met?

**Comment by kjeremy** [comment]
Everything I've seen in the docs say they only support Windows Desktop
which is 8+.

**Comment by dubstylee** [comment]
> Everything I've seen in the docs say they only support Windows Desktop
which is 8+.

In the Windows Desktop news release, it says that it will run on any of the millions of machines that support the Win32 API. I'm pretty sure Windows 7 should work, but I don't have any Windows 7 devices to verify. I have certainly been able to create WPF applications though, which should work fine on Windows 7.

**Comment by nirinchev** [comment]
We support WPF apps, but only on Windows 8.1 or later. 

We realize there are some people stuck on older Windows versions and are constantly monitoring GitHub issues and other support channels for community trends and if there's enough interest, we'll prioritize legacy platforms support. For the time being though, we feel 8.1 is sufficiently low target for the majority of our users.

**Comment by mehulsutariya** [comment]
Hi @nirinchev 

Thanks for your response. I understand your rationale regarding not supporting very old systems.

However, I would like to add that Windows 7 is still one of the widely used versions out there in the market worldwide.
http://gs.statcounter.com/os-version-market-share/windows/desktop/worldwide

As a result, even other platforms like Electron also provide support for Windows 7. For developers, it becomes very important to support Windows 7 to reach out to all possible end users. 

So, even though you might not get many direct requests from developers regarding support for windows 7, it is possible about 40-45% of all Windows users who won't be able to benefit from the awesomeness of Realm.

Hope this can add considered in your prioritisation.

**Comment by FutureTD** [comment]
Windows 7 supports .NET Core and all the .NET Framework versions. 

I Started using this library on Windows 10, assuming it would support windows 7 atleast. What would happen exactly if I ran my project on windows 7, would it just not work at all? Are there specific things that works on Windows 8.1+ only?

 I am just a little confused as to why this would not work on Windows 7.

**Comment by dustink** [comment]
+1 for windows 7

**Comment by mehulsutariya** [comment]
Hello guys,

Is there any chance of supporting Realm for Windows 7 anytime soon?

**Comment by fooevr** [comment]
My company's iOS and android application already using realm.
but almost all of our enterprise customer's clients still run Windows 7, so we have to use sqlite as client cache db.
I'm extremely eager PC client db move to realm. Thanks!

**Comment by sushihangover** [comment]
@fooevr  With about 18 months left before the MS extended support expires for Win7SP1 and the fat that all new CPUs/chipset do not support Win7, I personally would doubt that Realm would find an **RIO** for adding support at this point in time...

**Comment by Svarr** [comment]
I am not stuck with Windows 7, I just want to use an OS that is stable and user-friendly. Win 7 is the latest that more or less lives up to these expectations.
I need to find a different DB, it seems...

**Comment by fealebenpae** [comment]
@Svarr the core of Realm is written in C++ and uses a number of Win32 APIs that were introduced in Windows 8. By the time we began implementing support for Windows Microsoft had already dropped support for Windows 7 and we didn’t have the resources to set up tests on 10, 8.1, 8, and 7.

**Comment by Svarr** [comment]
@fealebenpae Thanks for clearing that up. I can understand your argumentation, but I wish there was a solution other than searching for an alternate DB that will inevitably differ from what I am used to (I use Realm for Android Apps). It's just frustrating.

**Comment by nirinchev** [comment]
Windows 7 is now EOL-ed so we don't plan to add support for it.

**Comment by dongfo** [comment]
+1 for windows 7

**Comment by peppy** [comment]
Can understand the reasoning for not wanting to support Windows 7, but just a heads up that this is likely going to be a pain point for deployment for us. A quick check on the latest [steam survey](https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam) shows around 5% of gamers are still using Windows 7.

**Comment by mexmer** [comment]
@nirinchev Windows 7 is EOL only for consumers
enterprise still use it, enterprise pays for ESU, and ESU for windows 7 SP1 ends on January 10, 2023

**Comment by nirinchev** [comment]
@mexmer appreciate the feedback. While I totally agree that there are valid use cases, it would be a major effort on our end to support Windows 7 and we can't reasonably commit all those resources unless there's a likelihood of getting a return on the investment. So far the majority of users commenting here are looking for support in the open source database, which is free. If there's a commercial use case and a customer willing to sponsor this development, I'd be happy to discuss that further.

**Comment by mexmer** [comment]
@nirinchev i will make fork, and send you commit link, for win7 compilation, but only for realm.lib not other stuff. i also understand your stance, because i know well, how much work is to do all testing ... having project compile for older platform, doesn't mean everything will work when run.

**Comment by nirinchev** [comment]
@mexmer to be able to run on Win7, we need support for it in the Core database (http://github.com/realm/realm-core) - I'm not sure if that's what you're referring to when you say realm.lib. The .NET SDK itself doesn't depend on Win 8 API.

**Comment by mexmer** [comment]
yeah you right, i'm in wrong project ... i have modified realm.lib compiled from realm-core project. it uses api calls like createfile2, mapfileviewfromapp and others, that are needed for UWP aps, but not available when you set WINVER 0x0601 ... so i have some changes around those calls .... sorry, for confusion.

**Comment by darkralts** [comment]
if only this was a think osu lazer would work on windows 7
