### ISSUE TITLE
Support XAML Previewer for Xamarin.Forms

### ISSUE THREAD

**Issue by mogwai** [realm/realm-dotnet#1394]
# System

OSX: 10.12.4
VS MAC: 7.0 (build 3146)
Realm: 1.1.1
Xamarin.Forms: 2.3.4.231

The preview of the screen isn't working with any combination of the settings:
android, ios, tablet or phone. I am using a PCL Project with Xamarin.Forms targeting Android and iOS. 

![screen shot 2017-05-15 at 13 07 11](https://cloud.githubusercontent.com/assets/5440566/26057003/89b7ff14-396f-11e7-8bfe-e93540a4eefb.png)

## Code Sample

```csharp
public static Realm GetInstance() {
	var config = new RealmConfiguration(Constants.REALM_FILE);
	try {
		return Realm.GetInstance(config);
	} catch (System.Reflection.ReflectionTypeLoadException err) {
		Debug.WriteLine(err);
	} catch (Exception e) {
		Debug.WriteLine(e.Message);
		Realm.DeleteRealm(config);
		return Realm.GetInstance(config);
	}
	return null;
}
```

**Comment by fealebenpae** [comment]
Hey @lengk,

We don't support running inside the Xamarin.Forms previewer at this time. I'll leave this issue open so as to track this.

**Comment by lengk** [comment]
A quick fix for using the previewer: 

Remove any classes that belong to the Realm namespace.

**Comment by robertmiles3** [comment]
This would be extremely helpful.

**Comment by thearaks** [comment]
Please, solve this issue since it makes impossible to work with XAML layouts!

**Comment by lengk** [comment]
@thearaks Not impossible. What I do is have a separate Xamarin project open and create a new view with XAML in there. If you need Models you can create your own ones that don't extend object. this way actually means the project builds faster and deploys faster also. 

If your using visual studio on a mac, you can use a [launcher](https://github.com/Redth/MSSolutionLauncher/releases) to open another project!

**Comment by robertmiles3** [comment]
@lengk Correct, not impossible, but a horrible developer experience.

**Comment by lengk** [comment]
@robertmiles3 Agreed not great. I wonder if anyone has got realm working with: http://livexaml.com/

**Comment by vlkam** [comment]
@lengk  Yes, Realm 1.6 working with LiveXAML

**Comment by EmmanVazz** [comment]
Really this is still not working? All the other open source projects I am using support this. It has been a while on this issue and no progress.

**Comment by nirinchev** [comment]
This hasn't been prioritized because there's very little demand for it - as you can see from the issue, there are a handful of people asking for it and there's a viable alternative (livexaml). While we'd like to deliver a superb experience in all areas, we also have to focus our resources on the bugs and features that will have the largest impact.

**Comment by vlkam** [comment]
I suppose Form previewer is dead because Xamarin have announced Live Reload for XAML
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/live-reload

**Comment by EmmanVazz** [comment]
Ugh why did they make something else that does the same thing? Preview isn't that stable even when it is working. Hopefully this is better but I doubt it.
