### ISSUE TITLE
Add support for keypath filtering for notifications

### ISSUE THREAD

**Issue by tom-pratt** [realm/realm-dotnet#1398]
## Goals

To be able to subscribe to a RealmCollection for updates but not trigger a notification if only some linked object is changed.

Say I have a RealmCollection of `Things`. I don't always want a notification if only one of the `SubThings` properties gets updated.

```
public class Thing : RealmObject
{
        public string Name { get; set; }
        public IList<SubThing> SubThings { get; }
}
```

## Expected Results

The reason is that I might have recyclerview of `Things`. If a `SubThing` changes then a partial cell update should happen using normal data binding within the cell to the `SubThing`. If a `Thing` actually changes then I want to call `adapter.NotifyDataSetChanged()` or some variation on that. What I would consider an actual change would be either a `Thing` property changing, or the RealmList `SubThings` being modified (add, remove).

it would be nice to have the subscribe method something like.

`RealmCollection.SubscribeForNotifications(Callback, notifyLinkedObjectUpdated: false)`

**Comment by Tom-Pratt** [comment]
Related question from realm-cocoa

[https://github.com/realm/realm-cocoa/issues/3704](url)

**Comment by Tom-Pratt** [comment]
That cocoa issue highlights the issue a lot better than I did. Ignoring certain properties is the key. 

My issue is that I would like it if you call also ignore properties on Linked objects.

**Comment by nirinchev** [comment]
The idiosyncratic .NET approach would be to use `INotifyCollectionChanged` with combination of `INotifyPropertyChanged` - your adapter is concerned only with added/removed objects, and the cells themselves subscribe for object notifications and update their content.

While there's value in extending the `SubscribeForNotifications` API and allow skipping certain properties, to me it seems that adopting the XAML data binding approach would be a better long term solution. 

I'll leave this issue open as a way to measure community interest and if we get enough requests/upvotes, we'll prioritize it.

**Comment by Tom-Pratt** [comment]
Hi thanks for the reply. Yes being able to bind to changing properties within a cell using INotifyPropertyChanged is very useful. 

However a full cell update is more frequently the desired visual effect, both iOS and Android allow you to notify specific cells to be refreshed resulting in a short fade out and then fade back in with the new data.

Just updating view properties via normal data binding generally occurs with no animation and doesn't really look right for cells in most cases. 

SubscribeForNotifications and ChangeSet seem to be better suited to dispatching cell updates in iOS and Android than INotifyCollectionChanged if you're not using Xamarin Forms.

**Comment by UKDeveloper99** [comment]
I like this idea.

**Comment by SureshSc** [comment]
+1

**Comment by kevin-ponce** [comment]
+1

**Comment by anysome** [comment]
+11111111111111

**Comment by DominicFrei** [comment]
> The idiosyncratic .NET approach would be to use `INotifyCollectionChanged` with combination of `INotifyPropertyChanged` - your adapter is concerned only with added/removed objects, and the cells themselves subscribe for object notifications and update their content.
> 
> While there's value in extending the `SubscribeForNotifications` API and allow skipping certain properties, to me it seems that adopting the XAML data binding approach would be a better long term solution.
> 
> I'll leave this issue open as a way to measure community interest and if we get enough requests/upvotes, we'll prioritize it.

@nirinchev The [Key Path Filtering for Change Notifications PR in Core](https://github.com/realm/realm-core/pull/4646) could probably offer an alternative for this as soon as it is accepted and merged.

**Comment by tele-bird** [comment]
+1 !!

I have found that changes to child (RealmObject) collections within a parent (RealmObject) cause our query subscription delegate to be invoked with ChangeSet.ModifiedIndices.  This was unexpected by us, and it causes our layouts to re-initialize needlessly.  We'd like to be able to selectively filter out these change notifications on a per-property basis, and it was confirmed to us that this feature would allow us to do that.
