### ISSUE TITLE
Realm changes do not propage instantly (Xamarin.Android)

### ISSUE THREAD

**Issue by SirDev** [realm/realm-dotnet#1419]
## Goals
I'm trying to save an object in one activity in android, and using the object in the 'next' activity, by passing around its unique Id (Guid). I'm doing this because it's not possible to pass over complete objects between activities (due to threading limitations in Realm).

## Expected Results
Saving an object makes it available everywhere in the app because Realm is uptodate everywhere.

## Actual Results
The object is not available when querying it in another thread in another part of the application, immediately after saving it. This happens on quick phones mostly.

## Steps to Reproduce
 In a service method in a PCL i'm calling the following code (shortened for readability)

```
using(var realm = Realm.GetInstance()) { 
    // customer is created here with all its props etc.
    var primaryKey = customer.Id;
    realm.Write(() => { realm.Add(customer, true); });
    return newPrimaryKey;
}
```

 In the new activity I call 
```
using(var realm = Realm.GetInstance()) { 
    var myobj = realm.All<obj>.Where(x => Id == newPrimaryKey).SingleOrDefault();
    // object sometimes is null here
}
```
The object is sometimes null. sometimes it's not. If I add a delay of 200ms, it does (usually) work. This is only on very fast phones. The problem is that I'm not able to add delays everywhere, because the application will crash due to return to a new thread, making realm crash on "Realm was accessed from an incorrect thread

## Workaround
By calling 
`realm.Refresh();`
before any large crucial action this can be circumvented. I've added it in more than 30 places of my code and the sync issues are gone now.

## Version of Realm and Tooling

- Realm Object Server Version: N/A
- Client SDK Version: 1.2.0
- Client OS & Version: Every android version from v4.0 (I haven't tested lower)

Seems to happen on reasonably new phones (samsung galaxy S7+S8, Xiaomi Mi5)

**Comment by SirDev** [comment]
Please not that (apart from the above sample) this happens in multiple places. I have a questionaire-app that show/hides questions based on answers given (e.g. do you own a house -> NO -> "what did your house cost" is hidden.

This all happens on different threads as Realm doesn't allow multithreading, and by the time the " what did your house cost" question is loaded, the "isHidden= true" hasn't been set / synced yet to the other Realm threads.

This makes for very hard debugging, as it only happens sometimes, and it is very hard to reproduce.

**Comment by fealebenpae** [comment]
What happens if you manually call `Refresh()` on the realm instance immediately after you acquire it in the second activity?

I suspect this has something to do with the Android Looper where the event loop in the second activity has not yet had the chance to tell Realm that there is newer data in the realm file so it opens a slightly older transaction.

**Comment by SirDev** [comment]
It works, as I later added as a workaround to the initial ticket. It works properly then. I added the refresh in multiple places now, and I don't have 'concurrency issues'  any more. So with this workaround it's manageable, but not optimal.

**Comment by fealebenpae** [comment]
> As an added note: I came across some code that wasn't properly ' closing ' the realm (e.g. not using `using(var r = Realm.GetInstance()) { ... }` - so perhaps it has something to do with that as well?

I don't think so, unless the subsequent code runs on the same thread. `GetInstance()` uses a per-thread cache to make sure opening realms is fast.

Could you isolate this behavior in a small app and share it with us so that we can try and debug it? Alternatively you can send your project to help@realm.io if the code is confidential.

**Comment by nirinchev** [comment]
I'm marking this as a bug - we should make sure that `GetInstance` will advance to the latest state so people don't have to manually refresh the Realm immediately after opening it.
