### ISSUE TITLE
SubscribeForNotifications callback won't get invoked when subscribed on worker thread

### ISSUE THREAD

**Issue by TobiasBuchholz** [realm/realm-dotnet#1427]
## Goals
I'm trying to use the SubscribeForNotifications() method on a worker thread, so its callback will also get invoked on a worker thread.

## Expected Results
The callback gets invoked on the worker thread so I can do stuff with the objects on the worker thread as well.

## Actual Results
The callback won't get invoked at all. Actually some times it does get invoked, but most times it does not. There is no consistency.

## Code Sample
I'm using Reactive Extensions + ReactiveUI for handling the threads.

```
Debug.WriteLine($"subscribe for notifications on UI thread");
Realm
    .GetInstance()
    .All<HelloWorldModel>()
    .SubscribeForNotifications((collection, _, __) => Debug.WriteLine($"SubscribeForNotifications called on UI thread: count = {collection.Count}"));

Observable
    .Defer(() =>
    {
         Debug.WriteLine($"subscribe for notifications on worker thread");
         Realm
             .GetInstance()
	     .All<HelloWorldModel>()
	     .SubscribeForNotifications((collection, _, __) => Debug.WriteLine($"SubscribeForNotifications called on worker thread: count = {collection.Count}"));

         return Observable.Return(Unit.Default);
    })
    .SubscribeOn(RxApp.TaskpoolScheduler)
    .SubscribeSafe();

Observable
    .Defer(async () =>
    {
        Debug.WriteLine($"processing stuff for a few seconds");
        await Task.Delay(TimeSpan.FromSeconds(5));

        var realm = Realm.GetInstance();
        realm.Write(() =>
        {
             realm.Add(new HelloWorldModel { Id = realm.All<HelloWorldModel>().ToList().Count() }, true);
             realm.Refresh();
             Debug.WriteLine($"HelloWorldModel added: count = {realm.All<HelloWorldModel>().ToList().Count()}");
        });

        return Observable.Return(Unit.Default);
    })
    .SubscribeOn(RxApp.TaskpoolScheduler)
    .SubscribeSafe();       
```

When the code is executed it prints the following to the console:
-> subscribe for notifications on UI thread
-> subscribe for notifications on worker thread
-> processing stuff for a few seconds
-> SubscribeForNotifications called on UI thread: count = 2
-> HelloWorldModel added: count = 3
-> SubscribeForNotifications called on UI thread: count = 3

So unfortunately there are no calls to the subscriber on the worker thread.

I've also created a working sample project where you can find this code in the PlayGround.ViewModels.MainViewModel class:
[repo link](https://github.com/TobiasBuchholz/PlayGround/blob/subscribe_for_notifications_on_worker/PlayGround.ViewModels/MainViewModel.cs)

## Version of Realm and Tooling
Version 1.4.0

**Comment by nirinchev** [comment]
It appears that you're letting the notification token (the result of [`SubscribeForNotifications`](https://realm.io/docs/xamarin/latest/api/reference/Realms.CollectionNotificationsExtensions.html#Realms_CollectionNotificationsExtensions_SubscribeForNotifications__1_System_Linq_IQueryable___0__Realms_NotificationCallbackDelegate___0__)) get garbage collected which severs the connection to the Realm. What's more, the Realm instance itself is garbage collected. [Here's the relevant section](https://realm.io/docs/xamarin/latest/#collection-notifications) in the docs - while the example is simplified, it shows that you should keep a reference to the token for as long as you wish to receive notifications.

**Comment by TobiasBuchholz** [comment]
I don't know why the MainViewModel + tokens should get garbage collected when it's still on the screen. I've added some dispose logic though (see [db4ed9598f408b34ff234835890459fbd150a21f](https://github.com/TobiasBuchholz/PlayGround/commit/db4ed9598f408b34ff234835890459fbd150a21f)), but I'm still getting the same result.

Also, if what you are saying would be the case, then why isn't the subscription on the main thread garbage collected as well?

**Comment by nirinchev** [comment]
I'm sorry, I didn't see the example project, I was commenting based on the code snippet you posted. I'll look into the project and get back at you.

**Comment by nirinchev** [comment]
I went over the code and, while I'm not very familiar with Rx, my brief research suggests that TaskpoolScheduler uses TPL threads (i.e. ones that don't have a runloop/looper). This means that the background thread will not automatically refresh the Realm like the main thread would. Refer to the [Seeing Changes From Other Threads](https://realm.io/docs/xamarin/latest/#seeing-changes-from-other-threads) section from the docs for more info.

**Comment by TobiasBuchholz** [comment]
I assumed the same, that's why I'm calling `realm.Refresh();` right after adding the model to the realm. See:
```
var realm = Realm.GetInstance();
realm.Write(() =>
{
    realm.Add(new HelloWorldModel { Id = realm.All<HelloWorldModel>().ToList().Count() }, true);
    realm.Refresh();
    Debug.WriteLine($"HelloWorldModel added: count = {realm.All<HelloWorldModel>().ToList().Count()}");
});
```
PS: I've also tried it without that call and it behaves exactly the same, the subscription on the main thread is still getting the events.

**Comment by nirinchev** [comment]
Refresh will update the realm on the thread it's called, it will not update realms that are on background threads.

**Comment by nirinchev** [comment]
I'll close this as it is a known limitation of the automatic notification mechanism. If you have any further questions, don't hesitate to reopen it.

**Comment by qwertylolman** [comment]
> I'll close this as it is a known limitation of the automatic notification mechanism. If you have any further questions, don't hesitate to reopen it.

Is there any way to workaround this limitation on Xamarin, except subscription on UI thread?

**Comment by nirinchev** [comment]
Can you clarify your use case? It's hard to suggest a workaround if we don't know what you're trying to achieve.
