### ISSUE TITLE
Incorrect property name given on property changed event when Backlinks are listed before the property in the class definition

### ISSUE THREAD

**Issue by ChrisWay** [realm/realm-dotnet#1432]
## Goals
When subscribed to property changed events on a Realm object, the property name that is given is incorrect if the property is listed after any properties marked with the Backlink attribute in the class definition.

## Expected Results
The correct property name to be passed in to the OnPropertyChanged method.

## Actual Results /  Steps to Reproduce
For the following class definition:
```
public class Captain : RealmObject
{
    public string Name { get; set; }
    [Backlink(nameof(Ship.Captain))]
    public IQueryable<Ship> Ships { get; }
    public string Age { get; set; }
}
```
When the "Age" property is changed, "Ships" is being passed into OnPropertyChanged."Name" works as expected. 

## Code Sample
I have [uploaded a Xamarin Forms project](https://github.com/ChrisWay/RealmTest) which shows the issue. The first Entry is bound to Name which works as expected but Age outputs the wrong property name.

## Version of Realm and Tooling
- Realm: 1.4.0

**Comment by nirinchev** [comment]
Thanks for the report - it is indeed a bug on our part. Until the fix is released you can work around it by moving all your Backlink properties to the bottom.
