### ISSUE TITLE
Parallel builds fail on CI

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-dotnet#1438]
Very often, when several PRs are being built at the same time, the builds fail with sporadic errors, e.g. https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-dotnet/detail/PR-1423/13/pipeline

Seems like something fishy is going on with NuGet, so we should probably run restore immediately before the build to ensure that we have all the packages necessary.

**Comment by fealebenpae** [comment]
This is because we stash the `project.lock.json` files from one node and occasionally use them on another where they don't apply. We can fix this by restoring on every node.
