### ISSUE TITLE
Include category in `GetInstanceAsync` exception message

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-dotnet#1448]
Right now we throw an obscure message with a magic number in it, making it hard to figure out what went wrong. At the very least we should include the category and ideally we should provide more friendly actionable messages for common errors.

For example, I got an error 89, which apparently indicates operation canceled, likely due to the session being destroyed, but I needed to ask the team to figure it out.

**Comment by fealebenpae** [comment]
The problem with this is that the values differ by platform - those are actually POSIX error codes from my experience. We'll need to handle them at the C++ level instead of C# and translate them to platform-agnostic values our C# code knows about.
