### ISSUE TITLE
GetInstanceAsync fails when realm doesn't exist

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-dotnet#1449]
Exception is obscure posix error (89). If the realm has been created, it works perfectly fine.

**Comment by fealebenpae** [comment]
Hasn't https://github.com/realm/realm-dotnet/pull/1503 resolved this?

**Comment by nirinchev** [comment]
It has resolved passing the correct error message, but I wasn't able to reproduce it - I think we no longer throw an exception when the realm doesn't exist (and create it instead). I decided to keep the issue open just as a reminder to write a unit test with `GetInstanceAsync` as a guard against regressions.
