### ISSUE TITLE
Is it possible to open a Realm in dynamic mode outside of a migration?

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-dotnet#1450]
I checked the docs but I only see Dynamic API in regards to migrations.

Is it possible to access Realm with dynamic API outside of migration?

**Comment by nirinchev** [comment]
Unfortunately, it's not possible to do that yet. We have an issue tracking this: https://github.com/realm/realm-dotnet/issues/778. Do you have a particular use case in mind that would require dynamic realm opening?

**Comment by nirinchev** [comment]
Yes, that's a solid use case :) I'll close this issue to avoid duplication of comments/feedback, but we're noting your interest and will keep that in mind as we plan our work.
