### ISSUE TITLE
Is it possible to use this library as a dependency for other binding depending on Realm.iOS/Realm.Android?

### ISSUE THREAD

**Issue by kanvuduc** [realm/realm-dotnet#1453]
Hi,

I am creating a binding for a SDK (Android/iOS) depending on Realm.iOS and Realm.Android.

I am wondering it is possible to use this as dependency for my binding?

Regards.

**Comment by nirinchev** [comment]
Unfortunately no - the API of Realm Java and Realm Xamarin are quite different and even if they weren't, there would be no way to instruct the native library to call into the c# one.
