### ISSUE TITLE
Expose a property to show if a Transaction is open on a Realm

### ISSUE THREAD

**Issue by ChrisWay** [realm/realm-dotnet#1454]
Would it be possible to add a property to Realm to show whether a Transaction is currently open or not? It looks like this is already available as an internal field.

Cheers

**Comment by nirinchev** [comment]
Can you explain your use case in a bit more detail? Obviously, there's no problem for us to change the access modifier of the property, I'm just cautious as to whether it will be helpful, as even if we expose it, there would be no way for you to commit or rollback the transaction.

**Comment by ChrisWay** [comment]
Basically I need to set a property within OnManaged if it has not already been set. If I'm creating a new instance of this object then this is already wrapped inside of a transaction so it can be rolled back if the user cancels, but edits use the automatic transactions provided by Realm for data binding. So I need to know if I'm inside a Transaction or not to know whether to wrap setting the property in a Realm.Write.

**Comment by nirinchev** [comment]
Alright, makes sense :) I'll try to squeeze it into our next release

**Comment by ChrisWay** [comment]
Thanks very much 😄

**Comment by nirinchev** [comment]
This has shipped in 1.5

**Comment by oleg-varlamov** [comment]
Hello! 
Is it planned to add the IsOpen property for the transaction?
