### ISSUE TITLE
IRealmCollection does not update UWP ListView

### ISSUE THREAD

**Issue by themacguffinman** [realm/realm-dotnet#1461]
I'm trying to use RealmDB for a native UWP app and I can't seem to get the UWP `ListView` to live update using `IRealmCollection`.

I get an `IRealmCollection` normally:

```
DeviceItems = this.appDb.All<Models.Device>()
                .OrderBy(d => d.Nickname)
                .AsRealmCollection();
```

I bind the `ListView.ItemsSource` normally:

```
<ListView
            Name="DeviceList"
            ItemsSource="{x:Bind ViewModel.DeviceItems, Mode=OneWay}"
            ItemTemplate="{StaticResource DeviceItemTemplate}"
            ItemContainerTransitions="{x:Null}"
            IsItemClickEnabled="True"
            Grid.Row="1"
            Grid.Column="0">
            <ListView.ItemContainerStyle>
                <Style TargetType="ListViewItem">
                    <Setter Property="HorizontalContentAlignment" Value="Stretch" />
                </Style>
            </ListView.ItemContainerStyle>
        </ListView>
```

Yet when I add a new record to RealmDB like so:

```
appDb.Write(() =>
            {
                var device = new Models.Device()
                {
                    Host = Guid.NewGuid().ToString(),
                };
                appDb.Add(device, true);
            });
```
The `ListView` doesn't update. This is strange because:

* I verified that the `CollectionChanged` event is definitely being fired.
* The `ListView` updates properly if I bind to a non-Realm `ObservableCollection`

Maybe RealmDB isn't firing the `CollectionChanged` event in the main thread which stops the ListView from being updated? I'm not sure. Either way, it's clear that RealmDB's `IRealmCollection` isn't working as intended.

- OS & Version: Windows 10 Pro N (version 1703) (build 15063.413)
- Platform: UWP target version Windows 10 Creators Update (10.0 Build 15063)
- Realm.Database NuGet version: 1.5.0
- Fody NuGet version: 2.1.0
- Fielder.Fody NuGet version: 1.1.1
- PropertyChanged.Fody NuGet version: 2.1.2
- Microsoft.NETCore.UniversalWindowsPlatform NuGet version: 5.3.3

**Comment by nirinchev** [comment]
Thanks for the report, we'll try and investigate it.

`CollectionChanged` is fired on the original thread the object was created on (this will usually be the main thread), so this should not be causing issues.

**Comment by ChrisWay** [comment]
I've had the same issue, it seems to be caused by using OrderBy, without that, updates work fine. In my case this was on an Android app, so isn't limited to UWP.

**Comment by nirinchev** [comment]
This is peculiar - if `CollectionChanged` is being fired in both cases, the fact that ordering is applied shouldn't affect the binding.

**Comment by ChrisWay** [comment]
Yep on Android with Xamarin Forms. I don't remember if `CollectionChanged` is being fired though, if I get time today I'll create a little test project.

**Comment by themacguffinman** [comment]
@ChrisWay @nirinchev I left out `OrderBy` like so:

```
DeviceItems = this.appDb.All<Models.Device>()
                .AsRealmCollection();
```

It still doesn't work. The `OrderBy` doesn't seem to be the problem.

**Comment by nirinchev** [comment]
I have managed to reproduce the issue with the UWP ListView - unlike the Xamarin Forms implementation, it doesn't play nicely with `IReadOnlyList` which our collections implement and instead expects `IList` implementation. I'll investigate further, but until then, feel free to give this [prerelease nuget](https://drive.google.com/file/d/0B45yfBWnWXwAajhyLVkxeWNmOFE/view?usp=sharing) a try.

**Comment by themacguffinman** [comment]
@nirinchev The prerelease nuget you provided works, thanks! Do you know when 1.6.0 will officially arrive?

**Comment by nirinchev** [comment]
No - we haven't planned a release yet. Historically, we've shipped new minor versions 2-4 weeks apart, so unless something unexpected happens, you can expect the public release of 1.6 in the next two weeks.

**Comment by dubstylee** [comment]
I can confirm that the 1.6.0 update fixes this issue.
