### ISSUE TITLE
DateTimeOffset type property default value is wrong after upgrading schema

### ISSUE THREAD

**Issue by MrClockOff** [realm/realm-dotnet#1462]
## Goals
Upgrading Realm schema while adding new object property of type `DateTimeOffset` should populate property default value as `01.01.0001 00:00:00`

## Expected Results
After schema upgrade new `DateTimeOffset` property default value is `01.01.0001 00:00:00`

## Actual Results
After schema upgrade new `DateTimeOffset` property default value is `0.1.01.1970 00:00:00`

## Steps to Reproduce
Use Android or iOS environment.
Create an object with any properties, populate objects and store in Realm. Add new `DateTimeOffset` property in Realm object and upgrade Realm schema. Check new property populated default value in Realm objects. 

## Version of Realm and Tooling
Realm Nuget package v1.5.0

**Comment by nirinchev** [comment]
I'm sorry for the inconvenience, this looks like a bug on our part. We'll investigate and fix, but in the meantime, you can probably work around it by manually assigning the default `DateTimeOffset` value to your new property in the migration callback.

**Comment by MrClockOff** [comment]
Thank you for useful advice
