### ISSUE TITLE
Expose mechanism to prevent adding classes to the default schema

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-dotnet#1467]
Library authors may wish to opt out of the module initializer weaving to avoid their objects leaking into users' default schema. Additionally, if a library is loaded lazily, it will try to add its classes after the default schema has materialized, throwing an exception.

**Comment by kristiandupont** [comment]
I.e. make this one public? https://github.com/realm/realm-dotnet/blob/9e0e15a95615b9507edf2974bb5777d339cd9f9b/Realm/Realm/Attributes/Attributes.cs#L57

**Comment by nirinchev** [comment]
If we make it assembly level and update  the weaver to respect it when weaving the module initializer, this could work.
