### ISSUE TITLE
Realm for desktop is not functioning for Realm V 1.4 and above

### ISSUE THREAD

**Issue by amasasi** [realm/realm-dotnet#1468]
I have run realm for desktop, it requires the System.Linq and even after adding it still the error persists. I have decided to use realm V 1.0.3 now

## Version of Realm and Tooling

- Realm Object Server Version: ?
- Flavor:
  - [ ] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: ? (e.g. CentOS 6)
- Client SDK Version: ?
- Client OS & Version: ?

**Comment by nirinchev** [comment]
Can you share more details - which operating system are you running on, what is the exact error you're receiving? If you could isolate a small reproduction sample, that would be ideal.

**Comment by amasasi** [comment]
I am using windows 10 on a 64  bit laptop. Can you please give an email so i can send you the project?

**Comment by nirinchev** [comment]
You can send it to help@realm.io.

**Comment by amasasi** [comment]
done

**Comment by nirinchev** [comment]
This has been resolved via email.
