### ISSUE TITLE
RealmObject to notify when removed from realm

### ISSUE THREAD

**Issue by tom-pratt** [realm/realm-dotnet#1474]
## Goals

Be able to observe when an individual RealmObject is removed from the realm.

e.g. the RealmObject's `IsValid` property is included in `INotifyPropertyChanged` events. Or another similar mechanism.

Currently in situations where updates occur  in the background that could delete a RealmObject it feels like you have to check IsValid before every use of the object.

**Comment by nirinchev** [comment]
That's a good idea - I'll add it to our backlog and we'll look into it in the near future.
