### ISSUE TITLE
Support Move action in IRealmCollection

### ISSUE THREAD

**Issue by egimbernat** [realm/realm-dotnet#1480]
## Goals

In order to support ListView element reorder IRealmCollection need to have Move function like ObservableCollection.

## Expected Results

Reorder "On-Memory" and expose it to CollectionChanged event with Action "Move"

**Comment by nirinchev** [comment]
There’s a Move extension method on IList<T>. IRealmCollection implements IReadOnlyList which is why you’re not seeing it. Since the binding engine will use reflection anyway, there’s no need to call AsRealmCollection on regular IList properties.

**Comment by nirinchev** [comment]
@egimbernat does the proposed solution help? Should I close the issue or do you have other related questions?

**Comment by egimbernat** [comment]
@nirinchev  I can't find the Move extension to IList, that I'm trying to do is using an observable collection and syncing it with realm, by now I'm getting many unespected results and is not fully working

**Comment by nirinchev** [comment]
Here it is: https://github.com/realm/realm-dotnet/blob/master/Realm/Realm/Extensions/CollectionNotificationsExtensions.cs#L115

You can use it like:
```csharp
public class Foo : RealmObject
{
    public IList<Bar> Bars { get; }
}

var foo = realm.Find<Foo>(0);
var bar = foo.Bars[0];
foo.Bars.Move(bar, 5);
```

**Comment by nirinchev** [comment]
@egimbernat I hope this helps. If you have further questions, don't hesitate to reach out.
