### ISSUE TITLE
SubscribeForNotifications Not Calling All Callbacks

### ISSUE THREAD

**Issue by benfrye** [realm/realm-dotnet#1481]
## Goals
We are trying to have multiple RealmResults lists that we can subscribe to for change notifications in various places that will get updates to stay in sync with each other.

## Expected Results
We expect all of the change notification callbacks for various RealmResults that have the same data to fire when changes/removals occur.

## Actual Results
Once more than one subscription has been added, intermittently the callbacks added later will not get fired. This happens more regularly the more subscriptions there are. For instance, if Object A subscribes for notifications, then Object B, then Object C, then Object D, it is likely that only Object A and B will get callbacks when a realm item as been modified/removed.

It would appear at some point in the NotifyCallbacks loop something is failing and breaking the for-loop. We are maintaining a reference to the token, and it happens for all notifications added after a certain point, consecutively, leading to this thought.

We have seen this on as few as 2 objects subscribing for notifications, and as high as 7. However, I have never seen more than 3 objects being subscribed successfully _all_ receive the appropriate callbacks. After 3 objects, the objects subscribed 4th, 5th, etc. never receive their callbacks.

## Steps to Reproduce
1. Have multiple instances (3 and up seems like the most consistent) of an object that do the below code, i.e. Create their own unique RealmResults and then subscribe for notifications to those realm results. The point being, the collections should have the same data and be in sync, but they are in fact separate RealmResults instances.
_(This is being done on the main thread)_
2. Remove (Removal more consistently fails than simply changing, though that will sometimes cause this as well) a Realm instance that was in the RealmResults from Realm.

## Code Sample
```
private RealmResults<MetaData> _metadata;
private IDisposable _metadataChangeNotification;
(...)
_metadata = (RealmResults<MetaData>)realm.All<MetaData>().Where(metaData => metaData.IsInLibrary);
_metadataChangeNotification = _metadata.SubscribeForNotifications(HandleMetaDataStateChangedNotification);
```

## Version of Realm and Tooling

- Realm Object Server Version: N/A
- Server OS & Version: N/A
- Client SDK Version: 0.80.0 (Stuck on 0.80.0 due to the testing limitations discussed in Issue #1059)
- Client OS & Version: iOS 10

**Comment by nirinchev** [comment]
We have moved to another approach to deliver notifications in 1.2.0 which is more reliable and simpler. Unfortunately, we don't have the resources to backport that to 0.80.0. Is the json deserialization issue the only one you're facing with the testing overrides? If so, if you can isolate it into a small project, I can take a look and see if we can sort it out.

**Comment by nirinchev** [comment]
Hey @benfrye following up to see if you managed to find a workaround or if there's a way for us to help you.

**Comment by nirinchev** [comment]
I’ll close due to inactivity. Feel free to reopen if you’d like us to look into it.

**Comment by benfrye** [comment]
@nirinchev Sorry for the delayed response. I was out for a couple of weeks. After getting back I sat down to draw up a sample project for you and realized that at some point since 0.81 you all have resolved the bait and switch testing problem we were experiencing! Just finished updating our Realm implementation to 1.6 and this notification problem is indeed resolved as well! This is all great news.

**Comment by nirinchev** [comment]
That’s great to hear! I hope you’ll like using the latest and greatest, but if you come across any issues, we’re here to help :)
