### ISSUE TITLE
Realm 1.5.0 nuget package for ios/android => cannot install Systm.IO.Compression

### ISSUE THREAD

**Issue by FrancoisM** [realm/realm-dotnet#1482]
There is a dependency on System.IO.Compression but it can't be installed on either iOS or Android target 7.1. Ok on .NetStandard library and UWP project though.

"Failed to add reference. The package 'System.IO.Compression' tried to add a framework reference to 'System.IO.Compression' which was not found in the GAC."

**Comment by FrancoisM** [comment]
My workaround: adding the reference to the framework directly in VS.
Then I had the same error with System.Net.Http. Did the same thing and then I could install Realm Nuget package.

**Comment by nirinchev** [comment]
This looks more like a NuGet/VS issue than something we have control over. We bring System.IO.Compression and System.Net.Http as dependencies via NETStandard.Library, but I can't see a way our packaging could affect ability to install either of those. Glad to hear you found a workaround though!
