### ISSUE TITLE
Deserialising JSON Objects with Arrays of primitives

### ISSUE THREAD

**Issue by lengk** [realm/realm-dotnet#1492]
# Problem

I'm having an issue deserialising a json into a realm object using NewtonSoft. I can't seem to get an array of primitives parsed into the object.

## Model 

```csharp

public class Event : RealmObject {
    [PrimaryKey]
    public int ID { get; set; }
    public List<string> images { get; }
    public string name { get; set; }
}
```

## Parsing the JSON

```csharp
var json = "[{"+
    "'name': 'Place'"+
    "'images': ["+
        "'img_url',"+
        "'img_url2'"+
    "]"+
"}]";

var events = JsonConvert.DeserializeObject<Event[]>(json);
var realm = Realm.GetInstance();
realm.Write(()=>{
    foreach(var eve in events){
        realm.Add(eve, true);
    }
})
var RealmEvents = realm.All<Event>(); // Empty Images lsit
```

However interestingly the img urls are not being parsed into the realm object as the object is null on initialisation.

I tried various types including `string[]` `String[]` `IEnumerable<string>` but the string are still not being parsed. 

**I'm sure that this could be resolved by making images an array of objects and create a new realm object for the images**

```javascript
{
    name:"PLAce",
    images: [
        {url:"imageurl"},
        {url:"imageurl"}
    ]
}
```

It just seems strange that you can't parse in an array of primtives from a json straight into Realm.

I tried an array of integers and had the same problem. I've tried to initalise the `List<string>` in the constructor but I think that is meaning when realm reads the object it is reset to zero but the parsing is done correctly

```csharp

public class Event : RealmObject {

    public Event(){
        images = new List<string>();
    }

    [PrimaryKey]
    public int ID { get; set; }
    public List<string> images { get; }
    public string name { get; set; }
}
```

I've also tried to create the object and then populate it but the images are still null.

```csharp
var json = "[{"+
    "'name': 'Place'"+
    "'images': ["+
        "'img_url',"+
        "'img_url2'"+
    "]"+
"}]";

var eventsArray = JArray.Parse(json);
using (var trans = realm.BeginWrite()) {
    foreach (var eve in eventsArray) {
        var newEvent = realm.CreateObject("Event");
        JsonConvert.PopulateObject(eve.ToString(), newEvent);
    }
    trans.Commit();
}
```

## Version of Realm and Tooling

- Flavor:
  - [x] Developer
- Client SDK Version: 1.5.0

**Comment by nirinchev** [comment]
Realm doesn’t support collections of primitives yet. Because your property only has a getter, it’s ignored by Realm which is why you don’t get a compile time error.

To resolve it, you’ll need to create a RealmObject with a single property of type string and use that as the generic argument of your list (which should be IList to be picked up by Realm).

**Comment by lengk** [comment]
Ah ok. Yes I realised this would be a hack around the problem. Is there a plan to add this feature or is it too complicated?

**Comment by nirinchev** [comment]
Yes, we have an [issue tracking](https://github.com/realm/realm-dotnet/issues/1194) that. The good news is that support for list of primitives was [added recently](https://github.com/realm/realm-core/issues/1881) in Realm's C++ core, so we hope to expose it in the .NET SDK in the near future.

I hope this clears things out. I'll close the issue, but if you have more questions, feel free to reopen it.

**Comment by lengk** [comment]
Thanks @nirinchev thats great news! Just to help anyone else looking for the same problem:

## Before
```javascript

{
    "name":"Place",
    "images": [
        "some-Url"
        "some-Url2"
    ]
}

```

```csharp

public class Event : RealmObject {
    [PrimaryKey]
    public int ID { get; set; }
    public List<string> images { get; }
    public string name { get; set; }
}

```

## After

```javascript

{
    "name":"Place",
    "images": [
        {"url":"some-Url"}
        {"url":"some-Url2"}
    ]
}

```

```csharp

public class Event : RealmObject {
    [PrimaryKey]
    public int ID { get; set; }
    public IList<ImageURL> images { get; }
    public string name { get; set; }
}

public class ImageURL : RealmObject {
    public string url { get; set; }
}

```
