### ISSUE TITLE
.Cast<>() on RealmResults<> and RealmList<>

### ISSUE THREAD

**Issue by tom-pratt** [realm/realm-dotnet#1495]
## Goals

Be able to cast RealmList and have a live RealmList returned. Same for RealmResults.

Will help to restrict access to property setters outside of certain contexts.

## Expected Results

```
var myObjects = realm.All<MyObject>();
IEnumerable<IMyObject> myObjectInterfaces = myObjects.Cast<IMyObject>();
```
 
Where `myObjectInterfaces` is still live and observable.

**Comment by fealebenpae** [comment]
You can perform a cast like `var myObjectInterfaces = realm.All<MyObject>() as IEnumerable<IMyObject>;`.

`Cast` on `RealmList` is implemented by LINQ To Objects (the `System.Linq.Enumerable` class) and we have no control over it. We implement the LINQ Provider for `RealmResults` ourselves, but I don't think we're planning to implement `Cast` in it, especially when the regular `as` cast works perfectly well in this case.

**Comment by tom-pratt** [comment]
Thanks! I actually didn't realise this about c#.

I wonder if its possible to cast IList<T> to IReadOnlyList<IT>.

Thanks for setting me in the right direction. I can research this further now
