### ISSUE TITLE
RealmList<T> does not support set by index

### ISSUE THREAD

**Issue by nielsenko** [realm/realm-dotnet#1538]
I get a `NotSupportedException`when trying to set an item on a RealmList<T> by index

```
System.NotSupportedException: Setting items directly is not supported.
  at Realms.RealmList`1[T].set_Item (System.Int32 index, T value)
```

From this java issue [2044](https://github.com/realm/realm-java/issues/2044), I gather that it should be possible to support this.

**Comment by nirinchev** [comment]
Correct - that is currently not supported. One possible workaround is to use `RemoveAt` + `Insert` to achieve the same result.

**Comment by nielsenko** [comment]
Yes. That is what I do for the moment, but it doesn't play nice with change notification.

I looked at realm-java, and found that the LinkView class has a:
```
private native void nativeSet(long nativeLinkViewPtr, long pos, long rowIndex);
```
but that same native method is not exposed in the `ListView.NativeMethods` class on .net. Anyway it seems trivial to add this, since core supports it, and once that is done to implement set item on `RealmList<T>`. Can we expect it in the near future?

**Comment by nirinchev** [comment]
Yes, it's fairly easy to implement and I can look into it after #1517 has been merged. While we can't give exact timelines, it's realistic to expect it sometime next month.
