### ISSUE TITLE
Incorrect API docs for OfferPermissionsAsync 

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-dotnet#1540]
The [api docs](https://github.com/realm/realm-dotnet/blob/master/Realm/Realm.Sync/User.cs#L405) state:

> The access level to grant matching users. Note that the access level setting is absolute, i.e. it may revoke permissions for users that previously had a higher access level. To revoke all permissions, use <see cref="AccessLevel.None" />

This is incorrect - PermissionOffers access level is additive and not absolute.

**Comment by cbush** [comment]
We are revamping the Realm docs. We're not ignoring this issue -- we've read through every one of them, and we'll be sure to address this as part of our updates. We're closing the GitHub issues and creating new JIRA tickets to track the work at a high level.
