### ISSUE TITLE
Complex object properties

### ISSUE THREAD

**Issue by nielsenko** [realm/realm-dotnet#1546]
I often find myself making simple value objects inherit from RealmObject just to be able to store them in Realm. Problem is I need to manage life-time of these manually now.

Example:
	
    public class Dimensions : RealmObject
    { 
        public int? Height { get; set; }
        public int? Width { get; set; }
        public int? Depth { get; set; }

        public bool HasValue => Depth != null || Height != null || Width != null;
    }

In order to store this as a property of another `RealmObject` I need to inherit from `RealmObject`. But I don't need to query this and I would prefer the object to die with the referencing parent.

**Comment by bmunkholm** [comment]
@nielsenko Hi Kasper, can you be a bit more explicit ;-)

**Comment by nielsenko** [comment]
Yes. Didn't mean to hit save just yet 😊

**Comment by nielsenko** [comment]
I hope it is a bit more clear now. Sorry for hitting save early. 

Anyway, perhaps if I could mark such an object using an attribute (`RealmValueObjectAttribute`) or by implementing a marker interface `IRealmValueObject` and have Realm realize, that it just needs to serialize/deserialize this as a binary blob.

**Comment by nirinchev** [comment]
I'm sorry, I'm still not sure I understand. Is your main concern that we don't offer cascading deletes? As for serializing/deserializing, is there a reason not to do it yourself (other than the need to write some boilerplate)? E.g. you could do:
```csharp
public class Parent : RealmObject
{
    public Dimensions Dimensions
    {
        get { return Deserialize(DimensionsBlob); }
        set { DimensionsBlob = Serialize(value); }
    }

    private byte[] DimensionsBlob { get; set; }
}
```

**Comment by nirinchev** [comment]
@nielsenko did that help or are you still having issues?

**Comment by nielsenko** [comment]
@nirinchev Well, think of it as a feature request.

Your suggested solution, apart from the fact that I'm lazy and I have to implement `Deserialize` and `Serialize` .. and `INotifyPropertyChanged`, and make sure to re-serialize whenever `Height`, `Width` or `Depth` changes, is fine.

Cascading deletes would work for me as well, and be much cleaner I guess.

**Comment by nirinchev** [comment]
Gotcha. In that case, I believe cascading deletes is the "true" solution as that would offer notifications and all other niceties. To avoid confusion, I'll close this issue, but you can track https://github.com/realm/realm-dotnet/issues/310. In the meantime, you'll have to either use serialization or write a custom delete logic, e.g.:
```csharp
public static void RemoveCustom<T>(this Realm realm, T value)
{
    if (value is Parent parent)
    {
        // Remove the "value" object to clean it up
        realm.Remove(parent.Dimensions);
    }

    realm.Remove(value);
}
```
