### ISSUE TITLE
Sync for Windows

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-dotnet#1559]

**Comment by aweFalafelApps** [comment]
Any estimated timeframe on this by chance?

**Comment by nirinchev** [comment]
We don't have concrete time frame to report, but it's a very high priority, so I would expect it in the near future. If anyone's interested, we could send over prerelease versions for testing.

**Comment by aweFalafelApps** [comment]
I'd be interested and happy to help anyway I can!

**Comment by Bo-Yee-Woods** [comment]
Can you send me the pre-release version? I can help you to test it.

**Comment by nirinchev** [comment]
Just enable "Show pre-release packages" in your NuGet package manager and install 2.0.0-rc1 - it supports syncing on Windows.
