### ISSUE TITLE
Enable encryption on Windows

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-dotnet#1562]
Should be just flipping the switch as Core has support now.

**Comment by atultiwari** [comment]
Any estimated timeframe on this, please?
I wanted to move from SQLite to Realm only because of its Cross-Platform & Encryption features.
Thanks.

**Comment by nirinchev** [comment]
We don't have timeframes yet, but we're close to enabling that. You can keep track of progress on this PR: https://github.com/realm/realm-dotnet/pull/1570
