### ISSUE TITLE
Add support for partial sync

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-dotnet#1565]
Product: https://github.com/realm/product/issues/245
OS: https://github.com/realm/realm-object-store/pull/547

**Comment by nielsenko** [comment]
If an object `x` is in the result set of the query defining a partial sync, will any object pointed to by `x`, say `y` where `typeof(x) != typeof(y)`, and `type(y)` not sync'ed, also be include, or will they appear as null?

In other words, will you traverse the graph and include all objects transitively, similar to how changes are raised when any object in the transitive closure of the result set is changed?

**Comment by nirinchev** [comment]
Yes, the initial implementation will traverse the graph and sync all objects that are reachable from matching objects. Eventually, we'll provide mechanisms to control that behavior, for example by explicitly specifying which paths to eagerly include in the synced dataset.

**Comment by nielsenko** [comment]
Sweet music in my ear - v1.7 is shaping up to be epic! 🥇 
How about _orphaned_ objects, ie. objects that fall outside the transitive closure of the query that define the sync _scope_? Will they be removed from the local realm, or left lingering?

**Comment by nirinchev** [comment]
Not sure. @kspangsege can you pitch in?

**Comment by kspangsege** [comment]
In the current version of partial sync, the local Realm will contain those objects, that are matched directly by one of your subscription queries, as well as those that are reachable via one, or multiple "pointers" from a directly matched object. I.e., the local Realm consists of the transitive "pointer" closure of the union of the subscription result sets.

In a future version, we intend to add a way by which the user can "prune" the closure operation, and thereby prevent that too much of the reference Realm gets replicated into the local Realm.

**Comment by kspangsege** [comment]
Ah, I realize now that I am just repeating what Nikola already said.

> Will they be removed from the local realm, or left lingering?

They will be removed. How fast depends on whether the client is connected to the server, and how "stressed out" the server is.

**Comment by nielsenko** [comment]
@kspangsege Thanks for clarification. But, it made me think of another corner case. What happens if a realm object is created locally, that falls outside _the transitive "pointer" closure of the union of the subscription result sets_ (lets us call this the _sync scope_ going forward). Will it be uploaded to the remote realm regardless, ie. are _sync scope_ only relevant for downloads, or will it eventually die silently in the local realm?

**Comment by kspangsege** [comment]
> Will it be uploaded to the remote realm regardless

Yes, it will by uploaded. Shortly thereafter, though, the server will make the client delete (unsubscribe from) that object, because it is not in the "sync scope", as you call it. But the new object will continue to live in the reference Realm, and can be later subscribed to by the client, or by other clients.

**Comment by nielsenko** [comment]
@kspangsege Again thanks for the clarification - it works just as I would like it to. In general, is it always so that uploads are processed before downloads?

**Comment by kspangsege** [comment]
> In general, is it always so that uploads are processed before downloads?

No, not if I understand you correctly. Are you worried about the object getting deleted before it is uploaded? That would not be possible due to the protocol. As far as I know, there are no race conditions that the applications needs to worry about.

**Comment by nielsenko** [comment]
@kspangsege Good to hear. This is getting a bit off topic, but does that mean that it is not only the ROS that does merges, but also the local clients? Since they may download data that needs to be merged with data, that they have yet to upload?

**Comment by kspangsege** [comment]
> does that mean that it is not only the ROS that does merges, but also the local clients? Since they may download data that needs to be merged with data, that they have yet to upload?

Yes. That is exactly what is going on.
