### ISSUE TITLE
Facing issues in using realm-nightly build

### ISSUE THREAD

**Issue by atultiwari** [realm/realm-dotnet#1576]
Hi,

I am trying to use Realm-nightly build. I have gone through the links mentioned in the readme file. But somehow, I am not able to access the realm-nightly build.
These are the steps I did -
1. First I added realm-nightly build url into NuGet Package Manager Sources.
![1](https://user-images.githubusercontent.com/586934/30780075-11293180-a120-11e7-8df8-a6eaaee14363.png)

2. Then I opened NuGet Package Manager for solution. I can see Realm when package source is nuget.org
![2](https://user-images.githubusercontent.com/586934/30780086-427a42c4-a120-11e7-8ec5-0e36719b75b3.png)

3. But I can't find Realm when I change my package source for nightly build
![3](https://user-images.githubusercontent.com/586934/30780094-5e836b4e-a120-11e7-8cbb-b8d6b8bff572.png)
![4](https://user-images.githubusercontent.com/586934/30780093-5e8333ae-a120-11e7-938b-40459fb39e04.png)

I don't know what am I missing here. Can anyone please guide me?
Thanks.

Atul

**Comment by fealebenpae** [comment]
You need to select the `Include prerelease` checkbox next to the search bar.

**Comment by atultiwari** [comment]
@fealebenpae thank you very much, it's showing now.
