### ISSUE TITLE
realm-wrappers dll not found in test environment on win10

### ISSUE THREAD

**Issue by lamest** [realm/realm-dotnet#1584]
## Goals
I'm trying to test some code that uses realm. 

## Expected Results
Test executes

## Actual Results
When i press F5 to execute console application - it runs without issues(also without breakpoint hit *sic!), but if i try to run test with ctrl-t+ctrl-r, I got System.TypeInitializationException->System.DllNotFoundException with claims on realm-wrappers dll

## Steps to Reproduce
add simple test with Realm.GetInstance() call and try to execute it.

## Code Sample
[repro project](https://github.com/lamest/repro_realm_wrappers)

## Version of Realm and Tooling
Using NUnit 3.8.1 and VS test adapter on Visual Studio 15.3.5 windows 10 1703.

Repro project include Realm.Database 1.6 and Realm.DataBindings 1.2.

**Comment by nirinchev** [comment]
Thanks for the report. I'm not sure if the VS test runner picks up the platform-specific (i.e. Windows) library or uses the PCL, but if it's the latter, that could be the cause of the issue. We'll investigate and report back when we have more information.

**Comment by lamest** [comment]
So how do I can test now with Resharper or VS test explorers?

**Comment by cfxway** [comment]
Cant write unit tests with realm, same error.

**Comment by mauruskuehne** [comment]
We have the same problem. We use the following realm packages:
<package id="Realm.Database" version="3.0.0" targetFramework="net47" />
<package id="Realm.DataBinding" version="1.2.0" targetFramework="net47" />
