### ISSUE TITLE
Use 'osx || macos' nodes for tests and native builds

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-dotnet#1588]
The CPH macs have been upgraded so we can use those for native bits/tests as well and reduce contention with Cocoa's PRs.

**Comment by fealebenpae** [comment]
It’s only the macOS wrappers that are built exclusively on `osx` nodes because the `macos` ones have libuv installed and that causes wrappers to automatically link it. We can disable the automatic linking in CMake and then allow Jenkins to build the macOS wrappers on `macos` nodes as well.

**Comment by nirinchev** [comment]
Our .NET Core tests are also run on 'osx' nodes - I guess those can be switched to use all nodes for free?

**Comment by fealebenpae** [comment]
Yes, we should be able to do that today.
