### ISSUE TITLE
Realms.Exceptions.RealmFileAccessErrorException: Unable to open a realm at path

### ISSUE THREAD

**Issue by porkyhead** [realm/realm-dotnet#1592]
## Goals

Launch app without crashing

## Expected Results

No crash

## Actual Results

10-06 09:55:20.396 E/mono    ( 6608): System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Realms.Exceptions.RealmFileAccessErrorException: Unable to open a realm at path '/data/user/0/dk.idealdev.amgen/files/realm-object-server/io.realm.object-server-utility/metadata/sync_metadata.realm': Not a Realm file.
10-06 09:55:20.396 E/mono    ( 6608):   at Realms.NativeException.ThrowIfNecessary (System.Func`2[T,TResult] overrider) [0x0000a] in /Users/tightdb/jenkins/workspace/realm_realm-dotnet_PR-1516-XXBWU7QHQ7BDRGFQ3SWG4LYYREWB3SW2HPOQJGKXIIGUKJLT7ULA@3/Realm/Realm/Native/NativeException.cs:52 
10-06 09:55:20.396 E/mono    ( 6608):   at Realms.Sync.SharedRealmHandleExtensions.ConfigureFileSystem (System.Nullable`1[T] userPersistenceMode, System.Byte[] encryptionKey, System.Boolean resetMetadataOnError) [0x0003e] in /Users/tightdb/jenkins/workspace/realm_realm-dotnet_PR-1516-XXBWU7QHQ7BDRGFQ3SWG4LYYREWB3SW2HPOQJGKXIIGUKJLT7ULA@2/Realm/Realm.Sync/Handles/SharedRealmHandleExtensions.cs:151 
10-06 09:55:20.396 E/mono    ( 6608):   at Realms.Sync.SharedRealmHandleExtensions.DoInitialFileSystemConfiguration () [0x0000d] in /Users/tightdb/jenkins/workspace/realm_realm-dotnet_PR-1516-XXBWU7QHQ7BDRGFQ3SWG4LYYREWB3SW2HPOQJGKXIIGUKJLT7ULA@2/Realm/Realm.Sync/Handles/SharedRealmHandleExtensions.cs:130 
10-06 09:55:20.396 E/mono    ( 6608):   at Realms.Sync.User.get_Current () [0x00000] in /Users/tightdb/jenkins/workspace/realm_realm-dotnet_PR-1516-XXBWU7QHQ7BDRGFQ3SWG4LYYREWB3SW2HPOQJGKXIIGUKJLT7ULA@2/Realm/Realm.Sync/User.cs:46

## Steps to Reproduce

When launching my Xamarin.Android app it crashes when trying to get a realm instance with a sync config.

## Code Sample

```
var realm = Realm.GetInstance(dataController.SyncConfig);


 public SyncConfiguration SyncConfig
        {
            get
            {
                var user = Realms.Sync.User.Current;
                if (user == null)
                    return null;

                var config = new SyncConfiguration(user, new Uri(Amgen.Config.REALM_URL))
                {
                    EncryptionKey = RealmEncryptionKey()
                };
                return config;
            }
        }

```

## Version of Realm and Tooling

- Realm Object Server Version: ?
- Flavor:
  - [ ] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: ? (e.g. CentOS 6)
- Client SDK Version: 1.6.0
- Client OS & Version: Tried only Android 7.0 + 8.0

**Comment by nirinchev** [comment]
Can you delete `/data/user/0/dk.idealdev.amgen/files/realm-object-server/io.realm.object-server-utility/metadata/sync_metadata.realm`? Looks like it got corrupted or written by an incompatible newer/older version of the SDK.

**Comment by porkyhead** [comment]
The issue still persist after a Clear Data or uninstall of the app. The strange thing is, that I do not get the crash if I add a small delay (like 200 ms) before trying to acquire the realm instance. Do you have an explanation for that?

**Comment by nirinchev** [comment]
That's very surprising indeed. Do you think you can isolate a small repro project - that will help us immensely with identifying the cause?

**Comment by nirinchev** [comment]
Closing this due to lack of response. When you find the time to create a repro project, feel free to reopen.
