### ISSUE TITLE
Realm.Database 2.0.0-rc1 / "No RealmObjects. Has linker stripped them?...." 

### ISSUE THREAD

**Issue by sushihangover** [realm/realm-dotnet#1593]
## Goals

Upgrade app from Realm `1.6.0` to `2.0.0-rc1` and test a iOS/Android application that is using Xamarin.Forms that has the RealmObjects in a PCL library

## Expected Results

No runtime errors

## Actual Results

iOS and Android report:

`No RealmObjects. Has linker stripped them? See https://realm.io/docs/xamarin/latest/#linker-stripped-schema
`
## Steps to Reproduce

* Update Nuget package to from `1.6.0` to  `2.0.0-rc1` in all projects
  * Delete app from device(s)
  * Clean / Rebuild / Deploy / Debug results in `No RealmObjects. Has linker st....`
  * Only change is the 1.6 to 2.0.0-tc1 package change
* RealmObjects are in a PCL library

**Note:** If the solution/project is not placing the RealmObjects in a PCL/NetStd library, but are included into the core application project, Realm is fine and all the RealmObjects are available.

`<package id="Realm.Database" version="2.0.0-rc1" targetFramework="portable45-net45+win8+wpa81" />
`

* Xamarin.iOS Version: 11.2.0.8 
* Xamarin.Android Version: 8.0.0.33

**Comment by adolgov** [comment]
I'm seeing a similar issue, but I'm running 1.6.0 and using PCL + Xamarin.Android. My solution worked correctly prior to the upgrade, even with RealmObjects declared in a PCL project.

I've just upgraded
```
Fody: 2.1.2 -> 2.1.3
Realm: 1.5.0 -> 1.6.0
Realm.Database: 1.5.0 -> 1.6.0
Realm.DataBinding: 1.1.0 -> 1.2.0
```

I checked the recommendations in the [Failed to Weave](https://realm.io/docs/xamarin/latest/#failed-to-weave) of the documentation, and also tried the [solution linked at stackoverflow](https://stackoverflow.com/questions/25794350/xamarin-studio-build-targets-trying-to-get-fody-working/26110785#26110785), all with no luck.

**Comment by nirinchev** [comment]
Can you make sure the module initializer of your PCL project is run prior to using Realm? For example, create a dummy class with an empty method in your PCL and invoke it. If the error persists, we'll need a repro project/more info as things are working as expected with the setup I tried.

**Comment by sushihangover** [comment]
Thanks, I'm aware of the assembly initialization order, I wrote an SO answer that addresses that:

* https://stackoverflow.com/questions/46049316/xamarin-realm-no-realmobject-has-linker-stripped-them/46052017#46052017

This is a failure to resolve the RealmObjects after the assembly containing the class definitions is loaded. Something changed from 1.6 to 2.0rc1 that is causes the failure as no other code changes were made. I perform all Realm-based code in the same Viper-based data module (which translates to the same assembly). Disassembly of that shows the classes are there and weaved. Also force loading the assembly and its dependancies (in reverse order) via a Assembly.Load works in 1.6 and fails in 2.0c1 with the same error.

**Comment by nirinchev** [comment]
That's very odd, as I don't remember touching anything that could result in such behavior.

@sushihangover does any of your projects in the json extensions repo exhibit this behavior? If so, I'll try to clone it and debug.

@adolgov do you think you can share a repro project? If you'd like to share it privately, you can email it to help@realm.io and reference this issue.

**Comment by adolgov** [comment]
As mentioned in the thread @sushihangover posted, the problem resolved when I completely removed all Realm and Fody NuGet packages from my solution, cleaned the solution, and then re-added everything back in.

After initially removing the NuGet packages, I also went and manually removed the .dll file and FodyWeavers.xml files that removing the packages seemed to leave behind.

**Comment by nirinchev** [comment]
I tried the same approach with the Nuget tests project in @sushihangover's repo and things worked. So seems to me like some Nuget weirdness 🤔

**Comment by ddomengeaux** [comment]
This appears to be more of an issue with Fody. I'm running into the same issue with 1.6.0 and trying to upgrade to Fody 2.1.3 from 2.1.2. It appears that moving to .3 causes the weaving tasks not to run. The upgrade also seemed to break the propertychanged weaver I use in the rest of my projects.

**Comment by sushihangover** [comment]
Ok,  I have some RealmObject being weaved and some not in this crazy solution at a client site that has way to many projects in it and RealmObjects in _multiple_ projects.

I created a matrix of Xamarin.iOS, Xamarin.Android apps and libraries projects and NetStandard and PCL library projects and hybrid NetStandard projects (ones that were PCL-based but converted to NetStandard, thus the csproj is the old style but it uses a project.json. All those projects using Fody `2.1.2` and Realm 1.6 initially.

Delete obj/bin and package dirs between every test, perform a nuget restore, and run msbuild with `/verbosity:diag` from cmd-line (using NuGet Version: `4.3.0.4406`)

* Realm `1.6`/  Fody `2.1.2` / `<RealmWeaver/>` builds correctly in every project.

Update the Realm package to `2.0.0-rc1`:

Realm `2.0.0-rc1`/  Fody `2.1.2` / `<RealmWeaver/>`   **Fails** to weave anything in **PCL projects**, the `FodyTarget` never shows up MSBuild for this project type. All other project types weave correctly.

Update to Fody `2.1.3`:

Realm `2.0.0-rc1`/  Fody `2.1.3` / `<RealmWeaver/>`  **Fails** to weave anything in **PCL** and **NetStandard** projects, the `FodyTarget` never shows up MSBuild for this project type.

Delete and re-add Realm 2.0.0-rc1,  keeping Fody `2.1.3`:

Realm `2.0.0-rc1`/  Fody `2.1.3` / builds correctly in every project.

Check out test solution (Realm `1.6`/  Fody `2.1.2`) on another box with the same nuget version, builds correctly in every project.

Check out test solution (Realm `1.6`/  Fody `2.1.3`) on another box with the same nuget version, builds correctly in every project.

Check out test solution (Realm `2.0.0-rc1`/  Fody `2.1.2`) on another box with the same nuget version, **fails** to weave PCL projects.

Check out test solution (Realm `2.0.0-rc1`/  Fody `2.1.3`) on another box with the same nuget version, **fails** to weave PCL projects but NetStandard weaves fine.

I am SOOOO confused.... there is some strange wackiness going on.

Re: https://github.com/Fody/Fody/issues/409

**Comment by jpeterson312** [comment]
I can not get it to work with Fody 2.1.3 (same error every time) -> No RealmObjects. Has linker stripped them?

I just down graded Fody to 2.1.2 (seems to be my only option)... I'm running Realm 2.0.0

**Comment by ddomengeaux** [comment]
Fody has dropped support for .NET 4.5. Converting my project to .netstandard solved the issue, but I ended up downgrading since now all the libraries in use are compatible with .netstandard as of yet.

**Comment by nirinchev** [comment]
I'm closing this as it seems to be an issue with Fody/NuGet and not directly related to Realm.
