### ISSUE TITLE
Debugging in Visual Studio Mac / Xamarin Studio

### ISSUE THREAD

**Issue by lengk** [realm/realm-dotnet#1597]
## Description
I've noticed that debugging realm objects in realm has strange behaviour for v1.6.0, but also version below it too.

For example, say I have a object SubFilter:

```csharp
public class SubFilter : RealmObject {
    public string name {get;set;}
}
```

Some other realm objects use this object:

```csharp
public class FilterConfig : RealmObject {
     ...
     public IList<SubFilter> Filters {get;}
}
```

Whilst running the App in Debug mode, using the `Immediate Console` produces strange behaviour:

<img width="495" alt="screen shot 2017-10-16 at 12 17 34" src="https://user-images.githubusercontent.com/5440566/31609431-0cd84546-b26c-11e7-978f-b4b096be6f30.png">

As you can see in the picture above, the variable name is clearly set however when trying to access it, the debugger says its null? This leads to confusion while debugging. 

Is this an issue in Visual Studio on Windows too?

## Version of Realm and Tooling

- Client SDK Version: Realm 1.6.0
- Client OS & Version: macOS Sierra 10.12.6

**Comment by nirinchev** [comment]
That looks like a bug in Visual Studio for Mac. Are you running a Xamarin app or .NET Core one?

**Comment by lengk** [comment]
I'm running a Xamarin App

**Comment by fealebenpae** [comment]
Could you please experiment with the same code in other project types, such as .NET Core, or different Xamarin flavors like iOS or Mac?

How does the same object look in the `Watch` window?

**Comment by nirinchev** [comment]
Closing this due to lack of response. If you encounter it again or have more details to share, feel free to reopen.

**Comment by mogwai** [comment]
I'm still having this issue. I've just converted my PCL project to .NET Standard. 

This is in VS Mac and has caused me many problem. I've recently re-installed everything just because of this problem.

**Comment by mogwai** [comment]
https://github.com/mogwai/vsmac-realm-debugger-issue
