### ISSUE TITLE
I got an error when I installing Realm use Carthage 

### ISSUE THREAD

**Issue by jiangshang0514** [realm/realm-dotnet#1606]
I got an error when I installing Realm use Carthage 

Xcode version is 9.0.1 , Carthage version is 0.26.2 ,carthage file: github "realm/realm-cocoa" , run "carthage update --platform ios" ,then I got an error : "
*** Skipped installing realm-cocoa.framework binary due to the error: "Incompatible Swift version - framework was built with 4.0 (swiftlang-900.0.65 clang-900.0.37) and the local version is 4.0 (swiftlang-900.0.65.2 clang-900.0.37)."
"

## Version of Realm and Tooling

- Realm Object Server Version: v3.0.1
- Flavor:
  - [x] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: ? (e.g. CentOS 6)
- Client SDK Version: ?
- Client OS & Version: ?
- Xcode Version:9.0.1
- Carthage Version:0.26.2

**Comment by jiangshang0514** [comment]
This is the success？

**Comment by nirinchev** [comment]
This repo contains the code and issues for the .NET SDK. It seems you're interested in the Swift/Obj C SDK, so I'll move your issue to https://github.com/realm/realm-cocoa.

**Comment by nirinchev** [comment]
Issue moved to [realm/realm-cocoa #5429](https://github.com/realm/realm-cocoa/issues/5429) via [**ZenHub**](https://www.zenhub.com/)
