### ISSUE TITLE
Decide what to do in terms of Multiplexing

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-dotnet#1620]
Based on my fading memories, I think we decided we could enable it by default and add an option to disable it for the notifier.

**Comment by fealebenpae** [comment]
I believe we should look into adding session multiplexing support to the sync proxy service in ROS and then enable multiplexing wholesale for all the bindings - I don't imagine anyone would ever want to disable multiplexing.

I've already researched this in ROS and it's possible to implement - we just need to take any possible performance impact into account.
