### ISSUE TITLE
Cannot login user in UWP project

### ISSUE THREAD

**Issue by Bo-Yee-Woods** [realm/realm-dotnet#1635]
In my uwp project, .net standard is 1.5. Realm object server is v1.8.3, provided by Azure. When I tried login in using following code, my program is forever waiting 'User.LoginAsync' to return user.  What is wrong?  
     
    var realmUrl = new Uri("realm://52.230.25.125:9080/~/default");
    var authURL = new Uri("http://52.230.25.125:9080");
    var credentials = Credentials.UsernamePassword(username, password, createUser: false);
    var user = await User.LoginAsync(credentials, authURL);
    var config = new SyncConfiguration(user, realmUrl);

**Comment by nirinchev** [comment]
As mentioned on StackOverflow, you need to upgrade your [ROS installation to 2.0](https://realm.io/docs/realm-object-server/latest/#upgrading). In the future, please refrain from opening issues in multiple channels as that makes it harder for us to monitor and respond.

**Comment by nirinchev** [comment]
On SO, you mentioned seeing the same problem even after the update. Are you seeing this in Debug or Release? What are you testing on - phone or PC? Can you try to wrap the login call in try-catch to check if an exception is thrown? Ideally, if you have a small sample that reproduces the issue, that would be great.

**Comment by nirinchev** [comment]
Closing this due to lack of response.
