### ISSUE TITLE
Expose modified timestamp and modified transaction id

### ISSUE THREAD

**Issue by nielsenko** [realm/realm-dotnet#1648]
## Goals

Feature request.

Be able to see on a RealmObject what timestamp it was last modified, and some token identifying the transaction it was modified in.

If the timestamp is the same for all objects modified in the same transaction, and the timestamp is different between all transactions (ie. fx it is a Lamport timestamp), then a token for the modifying transaction is not needed.

Today, I need to maintain such meta-data myself, even though I know that Realm must have the information available.

**Comment by nirinchev** [comment]
Thanks for the suggestion. I'll add it to our backlog and talk to the core team to figure out how feasible it is.

**Comment by nielsenko** [comment]
With realm core 6.0 looming in the near future, I would like to hear if this feature request is more or less likely to happen?
