### ISSUE TITLE
Bug: Local realm not syncronised with Realm Object Server

### ISSUE THREAD

**Issue by bvschie** [realm/realm-dotnet#1654]
I have the simple realm dog-demo and use the SyncConfiguration

I see local/cached realm have all the objects; the realm on server is created - but doesn't contain any visible objects, access with Realm Studio 1.10 (but tried earlier versions);

![image](https://user-images.githubusercontent.com/25656835/33773000-cbddccf6-dc36-11e7-8a0a-a5ddcc343f79.png)

The ros is on a http (without ssl) server; so i tried with .EnableSSLValidation = false; there is no difference;

Also tried with an Errorhandler; but do not get any error;

```
static void Main(string[] args)
        {
            var credentials = Credentials.UsernamePassword("???@???.???", "?????", createUser: false);
            var x  = User.LoginAsync(credentials, new Uri("http://???.???:9080"));
            User user =  x.Result ;
            
            var loginConf = new SyncConfiguration(user, new Uri($"realm://???.???:8090/~/bbb1"));
            loginConf.EnableSSLValidation = false;

            var realm = Realm.GetInstance(loginConf);

            // Update and persist objects with a thread-safe transaction
            realm.Write(() =>
            {
                realm.Add(new Dog { Name = "Rex", Age = 1 });
            });

            // Query and update from any thread
            new Thread(() =>
            {
                var realm2 = Realm.GetInstance(loginConf);

                var theDog = realm2.All<Dog>().Where(d => d.Age == 1).First();
                realm2.Write(() => theDog.Age = 3);
            }).Start();

            Console.ReadLine();
        }

```

## Version of Realm and Tooling

- Realm Object Server Version: 2.0.23
- Flavor: 
  - [ X] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: ? Ubuntu 16.04 
- Client SDK Version: Realm 2.1.0
- Client OS & Version: Windows 8.1 / VS2017 / .Net Framework 4.6.1 / .NetCore 2.0.1 / System.net.http 4.4.3

**Comment by nirinchev** [comment]
Seems like the port number in your configuration is wrong - you're using 8090 instead of 9080.

**Comment by nirinchev** [comment]
I'm not sure how the realm was created in ROS - definitely nothing is using the server url from the user. If you're able to reproduce it, we'd be happy to investigate further.

As for the port issue - for Realm there's no difference between wrong port (i.e. server that is permanently unavailable) and temporary connection issues.

**Comment by bvschie** [comment]
When i LoginAsync on port 9080, and do a GetInstance with a SyncConfiguration on a different port; it created the realm on the server straight away!

![image](https://user-images.githubusercontent.com/25656835/33804373-a4e99058-dda3-11e7-93b1-65b58c94ddb8.png)

The with the code, it doesn't matter what port i use, it will create the realm! on the server; it will only Sync when the SyncConfiguration is on port 9080!

```
            var x  = User.LoginAsync(credentials, new Uri("http://xxx.xxx:9080"));
            User user =  x.Result ;
            
            var loginConf = new SyncConfiguration(user, new Uri($"realm://xxx.xxx:1111/~/Test1"));
            //loginConf.EnableSSLValidation = false;

            // loginConf.ObjectClasses = new[] { typeof(Dog), typeof(Person) };

            var realm = Realm.GetInstance(loginConf);

```
![image](https://user-images.githubusercontent.com/25656835/33804393-fa823024-dda3-11e7-9c14-330b7be55606.png)

**Comment by nirinchev** [comment]
It seems this is caused by the Realm Object Server - when asking for an access token for the Realm at a certain path, we're using the server url from the user (because it's possible to have the auth service at one endpoint and the realm service at another). When the access token is issued, an empty Realm is created.

I've opened an issue against the ROS repo where you can follow the progress https://github.com/realm/realm-object-server/issues/316.
