### ISSUE TITLE
Unable to create in-memory database

### ISSUE THREAD

**Issue by sbosell** [realm/realm-dotnet#1657]
The .net library seems to lack the ability to create an in-memory database much like many of the mobile libraries.  The RealmConfiguration does not have an `inMemoryRealmwithIdentifier`.
## Goals

The goal is to be able to create an in-memory database with the .net library.

**Comment by nirinchev** [comment]
This has been added a while ago, but hasn't been released yet - https://github.com/realm/realm-dotnet/pull/1638.

If you need it now and are not afraid to work with prerelease builds, check out the [Nightly Builds](https://github.com/realm/realm-dotnet#nightly-builds) section in the Readme for details on how to get a version that has it.

**Comment by Zhuinden** [comment]
Also I've just realized there was an issue for in-memory realms previously (which I didn't find for some reason) https://github.com/realm/realm-dotnet/issues/191
