### ISSUE TITLE
Backlink not working

### ISSUE THREAD

**Issue by Bo-Yee-Woods** [realm/realm-dotnet#1659]
I have two class Course and class Student

    Class Student
    {
        public int Id { get; set; }
        public Course Course { get; set; }
    }

    Class Course 
    {
        public int Id { get; set; }
        [Backlink(nameof(Student.Course ))]
        public IQueryable<Student> Students { get; }
    }

     realm.Write(() =>
     {
          newStudent.Course = courseA;
          realm.Add(newStudent);
     });

After the above code is executed, courseA.Students is still empty list. Why Backlink does not work?
(Realm 2.1.0)

**Comment by fealebenpae** [comment]
What kind of project are you trying to run this on - Xamarin, .NET Core? What operating system?

**Comment by Bo-Yee-Woods** [comment]
Microsoft.NETCore.UniversalWindowsPlatform v6.0.2 on windows 10 with latest upgrade

**Comment by nirinchev** [comment]
Hi @Bo-Yee-Woods, I tried to reproduce the problem with a new UWP project and was unable to. Here's the project I used:
[Issue1659.zip](https://github.com/realm/realm-dotnet/files/1588000/Issue1659.zip). Can you check if it works with your setup? If it does, can you try to modify it so that it exhibits the issue that you've reported?

**Comment by Bo-Yee-Woods** [comment]
I know why my code cannot work, because I have following code. Because I don't know how IQueryable works, then I initialize it.

    Class Course 
    {
        public Course()
        {
            Students = Enumerable.Empty<Student>().AsQueryable();
        }
        public int Id { get; set; }
        [Backlink(nameof(Student.Course ))]
        public IQueryable<Student> Students { get; }
    }

**Comment by nirinchev** [comment]
It seems this has been resolved.
