### ISSUE TITLE
Realm-database #1 is bigger than Realm-database #2 while less records

### ISSUE THREAD

**Issue by StefaanAvonds** [realm/realm-dotnet#1666]
## Description

I have a Xamarin.Forms-application and in there I'm using 2 different Realm-databases: 1 for Accelerometer-readings and the other for Gyro-readings. Suddenly I was getting exceptions indicating the size of my 2nd database (Gyro) was too big.

Following statistics were found when opening both files in Realm Studio for Windows:
The Accelerometer-database contained 115.138 records and was in total about 82MB, while the Gyro-database only had 86.075 records but was about 262MB. The structure of both tables are identical (string? (for guid), string? (for guid), date, date, date, bool, float, float, float).

Why is the database with less records 3 times bigger than the other database?

## Expected Results

Equal size for equal databases.

## Actual Results

Database with less records is 3 times bigger.

## Version of Realm and Tooling

NuGet-packages:
- Realm version 2.1.0
- Realm.Database version 2.1.0
- Realm.DataBinding version 1.2.0

**Comment by fealebenpae** [comment]
Hey @StefaanAvonds,

Could you please share a bit more details about your setup? Do you use Sync or do you perform read and writes on multiple threads?

**Comment by StefaanAvonds** [comment]
@fealebenpae 
Indeed I'm reading and writing on multiple threads. Although writing is buffered to only happen once every 10 seconds and performs a bulk insert of all new values.

The insert happens like this:
```
        private void InitializeSync()
        {
            var source = Observable.Interval(TimeSpan.FromSeconds(10));
            source.Subscribe((tick) => Sync());
        }

        private async void Sync()
        {
            await Observable.Start(() =>
            {
                var temp = new List<StatisticAccelerometer>(_newObjects);
                _newObjects = new ConcurrentBag<StatisticAccelerometer>();

                using (var realm = Realm.GetInstance(_databaseName))
                {
                    realm.Write(() =>
                    {
                        foreach (var item in temp)
                        {
                            realm.Add(item);
                        }
                    });
                }
            });
        }
```

**Comment by fealebenpae** [comment]
A possible cause of the increased size is long-living instances of the database on worker threads (especially threads without a working `SynchronizationContext`, such as ones that make up the .NET thread pool). Essentially an instance like that holds on to a view of the realm file and without a `SynchronizationContext` to update the instance to the latest view the old data on disk is never garbage collected by the database.

You can verify if old versions inside the realm file are a problem by attempting to compact it using the `Realm.Compact` method.

**Comment by StefaanAvonds** [comment]
It's probably not wise to call the Compact-method while it is being used, I assume? Is compacting on launch app a good idea?

**Comment by fealebenpae** [comment]
I suggest modifying your app to call `Compact` purely as a diagnostic measure - provided there are no long-lived instances on background threads compacting should not be necessary.

Still, if there are instances of the realm other than the one you’re attempting to compact you’ll get an exception, so it’s safe to compact if there are multiple instances.

**Comment by nirinchev** [comment]
Additionally, you could set the `ShouldCompactOnLaunch` property on the configuration so that compaction is only executed when it makes sense (e.g. when it's going to free a meaningful amount of memory). Check out the docs for more info: https://realm.io/docs/dotnet/latest/#compacting-realms

**Comment by StefaanAvonds** [comment]
I tried compacting the databases and it is working very nice! With a second run I created a database with 18.587 records and a total size of 1.664 KB. So you are right @fealebenpae .

The `ShouldCompactOnLaunch` property does seem nice, thanks for the hint! 

Thanks for the assistance.

**Comment by nirinchev** [comment]
No worries. If you have further questions, don't hesitate to ask :)
