### ISSUE TITLE
Fody/RealmWeaver messes up referenced assembly versions

### ISSUE THREAD

**Issue by cbruegg** [realm/realm-dotnet#1667]
While migrating a Xamarin project with Realm DB to .NET Standard 2.0, @mb236 and I stumbled upon an issue that causes Fody or RealmWeaver to mess up the referenced assembly versions in the weaved assembly:

`The type 'IReflectableType' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Reflection, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'`

A sample project reproducing the error can be found [here](https://github.com/HiP-App/HiP-Forms/tree/iss-hipm-821).
1. Checkout the branch `iss-hipm-821`
2. Add the file [Constants.cs](https://gist.github.com/cbruegg/2524f57781b6ac23bcb337ca8d3fdc10) in `Hip-Mobile-Internal` (top-level folder)
3. Build the project `HipMobileUI`

You can simply ignore any potential errors caused by the project `HipMobile.Tests`, feel free to just delete it from the solution. The only remaining errors will look like the message cited above.

We're using Realm 2.1.0.

Originally we thought this was an issue with the C# compiler, but @joperezr thinks it's an issue with Fody/RealmWeaver. See also [our filed issue in their bugtracker](https://github.com/dotnet/standard/issues/591) for more details. We then filed an issue with Fody, but the [maintainer told us to file an issue here](https://github.com/Fody/Fody/issues/438#issuecomment-353199462).

**Comment by nirinchev** [comment]
Yes, we're aware of the issue and are tracking it in https://github.com/realm/realm-dotnet/issues/1663. There's a community-provided hotfix in this [forum thread](https://forums.realm.io/t/ireflectabletype-is-defined-in-an-assembly-that-is-not-referenced/792/6?u=nirinchev) that you can try out. We'll try to address it with an official fix once the team is back from holiday.

**Comment by ChetanLimitless** [comment]
#nirinchev Are you done with this issue coz I am also facing this issue.

**Comment by nirinchev** [comment]
No, that hasn't been resolved yet.
