### ISSUE TITLE
proposed spell corrections to some of the markdown

### ISSUE THREAD

**Issue by jeis2497052** [realm/realm-dotnet#1669]
## Goals

propose some spelling corrections

## Code Sample

diff --git a/examples/Benchmarkr/README.md b/examples/Benchmarkr/README.md
index 7ba5cdcf..2d1fc94d 100644
--- a/examples/Benchmarkr/README.md
+++ b/examples/Benchmarkr/README.md
@@ -1,10 +1,10 @@
-Benchmarkr
+Benchmarks
 ==========
 There are Lies, Damn Lies and Benchmarks - this an attempt of the latter.
 
 Benchmarks are inherently flawed and can basically express anything you want. Add to that that it's tecic
ally difficult. So this is no attempt at giving a comprehensive comparison of the performance of Realm or 
other solutions. It's just a quick reality check on a very limited number of operations to give us some in
dicators that we are not messing up the great raw performance of Realm underlying database engine and that
 it seems likely that we are not radically slower than other solutions.                                  
 
-Specifially it compares a few simple operations for Realm, SQLite and Couchbase:
+Specifically it compares a few simple operations for Realm, SQLite and Couchbase:
 * Insert 150k objects in one transaction
 * Query 450k objects and count the 100k matches
 * Query 450k objects and enumerate all 100k matching objects
@@ -13,9 +13,9 @@ How to run
 ----------
 Run it and press the Start button to see benchmarks appear after a possibly long number of seconds.
 It's been observed that Couchbase might not be able to complete this test on some devices.
-In that case it's adviced to reduce the number of objects used.
+In that case it's advised to reduce the number of objects used.
 
-Interprete the results
+Interpret the results
 ----------------------
 The UI is world class awful and just lists the number of milliseconds each operation took. So smaller ibe
tter.                                                                                                    
 
diff --git a/wrappers/README.md b/wrappers/README.md
index 180713c8..b90f7770 100644
--- a/wrappers/README.md
+++ b/wrappers/README.md
@@ -15,7 +15,7 @@ Downloading ObjectStore
 
 ### Cloning
 
-If you cloned your `realm-dotnet` repository, you can use a git commmand to get the submodule:
+If you cloned your `realm-dotnet` repository, you can use a git command to get the submodule:
 
 1. Open a terminal window in the `realm-dotnet` source directory
 1. Enter the command `git submodule update --recursive`

## Version of Realm and Tooling

- Realm Object Server Version: ?
- Flavor:
  - [ ] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: ? (e.g. CentOS 6)
- Client SDK Version: ?
- Client OS & Version: ?

**Comment by nirinchev** [comment]
Thanks for pointing these out!

**Comment by jeis2497052** [comment]
Happy to contribute Nikola
