### ISSUE TITLE
Realms.Sync User doesn't work in Xamarin.Forms PCL or .NETStandard

### ISSUE THREAD

**Issue by AlonikiX** [realm/realm-dotnet#1674]
Does Realms.Sync supports PCL or .NET Standard in Xamarin.Forms now? When I try to get CurrentUser, it always throws an exception. But when I use it in shared project, it works fine.
![6265ff52-5105-4689-b74f-b7ceabe315e2](https://user-images.githubusercontent.com/11833091/35097649-2c15b5aa-fca5-11e7-8129-40686ca81018.png)

Also, `User.LoginAsync()` throws the same exception.
I am using VS for Mac, is their any solutions? It has been annoying me for a day, please help.

**Comment by fealebenpae** [comment]
Have you added the Realm NuGet to the application project as well?

**Comment by AlonikiX** [comment]
Yes, I have. When using PCL, `RealmWeaver.xml` will be added to the project automatically, and I can use default Realm without login. While using .NET 2.0, the `RealmWeaver.xml` will mess up the project. However, none of them can work with `Realms.Sync.User`.

**Comment by fealebenpae** [comment]
Could you create a new project that crashes this way and upload it somewhere?

**Comment by AlonikiX** [comment]
That's weird.. After I rebuild the iOS project (the new project I just created), the exception changes to this one. 
![ceb6bae1-0dea-43af-8008-34e073736ad4](https://user-images.githubusercontent.com/11833091/35100770-1c764478-fcb1-11e7-89e7-381ed2c68a42.png)
If I didn't rebuild, it will throw the previous exception.

I have added iOS Allow Arbitrary Load to Info.plist, but still get the HTTP exception.

Here is the PCL project: https://github.com/AlonikiX/Realm-PCL.git
Here is the .NET 2.0 project: https://github.com/AlonikiX/NETRealm.git (Manually adding the `FodyWeaver.xml`)

Thanks.

**Comment by fealebenpae** [comment]
I could successfully run both projects (at least to the point where `Realm.GetInstance` complained there are no `RealmObject` classes in the app).

What do you test on - device or simulator, and which model and iOS version?

**Comment by AlonikiX** [comment]
Sorry, it is my mistake, I deleted the iOS 8 simulator and restarted all the things, and it works now. 😅
So that is how I solve this issue (using VS for MAC & .NET 2.0 Xamarin.Forms):
1.Add `FodyWeavers.xml ` manually to both projects (I don't know why they cannot be added automatically)
2. Rebuild all the projects (otherwise it will still throw the previous exception)
3. Restart VS (as least for my mac, it is a step must have)
4. Sometimes have to delete the simulator (maybe just need to delete the app, not sure)

Anyway, thanks for spending such long time to help me : )
