### ISSUE TITLE
Logging out user without dispose realm will mess up the whole user realm

### ISSUE THREAD

**Issue by AlonikiX** [realm/realm-dotnet#1675]
## Questions
Hi, when I use `User.Current.LogOutASync()` to log out the current user, it shows no error or exception. When I try to login in again, it still works. The tricky thing is, this user realm can be instantiated again but cannot query data anymore. When I used `All<T>()`, it simply return no data, though I can see all the data via Realm.Studio.

## Features
Is there any API for clear deleting a user in a realm object server?

### Steps to reproduce
1. Use `Credentials.UsernamePassword(Username, Password, true)` and `User.LoginAsync(credentials, authURL)` to sign up a user.
2. Use `User.Current.LogOutASync()` to logout this user.
3. Login again.
4. Try to query data,  e.g. `var userList = realm.All<PTUser>()`.
5. Get no data.

### Steps to work out
1. `await User.Current.LogOutAsync();`
2. `realm.Dispose();`
3. ` realm = null;`
4. Now can logout/login without faults
                        

- Realm Object Server Version: 2.6.0
- Client SDK: .NET Standard 2.0 & Realm 2.1.0
- Flavor:
  - [ ] Developer
  - [ ] Professional
  - [ ] Enterprise

What is the right way to login-logout a user? I will appreciate any helps, thanks.

**Comment by AlonikiX** [comment]
Sorry, that still not works for all scenario as well. If I log out the user, and then close the app, next time I restart the app again, try login and query data, same fault again. However, if I didn't log out before I close the app, then next time it will work fine.

**Comment by AlonikiX** [comment]
Once my user encountered this bug, it cannot query data anymore, even if I reinstall my app. But what's weird, I use the demo app https://github.com/realm/realm-tasks to login my user, it works fine again, login / logout has no problem... I copied the key code from the demo app to .NET 2.0 project,  and the same bug again. So I am thinking maybe it is a problem of .NET 2.0 Xamarin.Forms project? Not sure.

**Comment by nirinchev** [comment]
Are you querying for data immediately after logging in? If that's the case, it's possible that the realm hasn't downloaded yet. Can you try to add 'await realm.GetSession().WaitForDownloadAsync()' before running the query?

**Comment by AlonikiX** [comment]
Thank for your help, it works!!! This issue has been annoying me for two days. 
However, I am still curious about why the demo app doesn't need to await for download finished. I intentionally login and logout rapidly and frequently, but it still works fine. And for my own project, if I don't add this statement, it will definitely crash every time.

**Comment by AlonikiX** [comment]
I think the reason why the demo app doesn't not crash is it doesn't operate to a null object, whereas I was trying to use the null object.

**Comment by nirinchev** [comment]
Glad you got it working :) If you have further questions, don't hesitate to reach out.
