### ISSUE TITLE
RealmInvalidTransactionException - In a transaction

### ISSUE THREAD

**Issue by lengk** [realm/realm-dotnet#1676]
Would it be possible to record the line of code that started the transaction that is currently being executed when this error is thrown?

**Comment by nirinchev** [comment]
Doesn't it appear in the stack trace of the exception?

**Comment by lengk** [comment]
Sorry I'll confirm this soon

**Comment by nirinchev** [comment]
Closing due to lack of response. If you have more information, feel free to reopen it.
