### ISSUE TITLE
Error while loading assemblies: Realm.dll

### ISSUE THREAD

**Issue by vaddanki** [realm/realm-dotnet#1680]
I am following the steps at this blog.
https://realm.io/blog/introducing-realm-xamarin/

Getting the following build error (Visual Studio 2017 Preview, Xamarin. IOS 10.3)
Error while loading assemblies:xxxxDebug/Realm.dll

I have verified that the file is present at the location. Turned on the verbosity for compile log to Diagnostic level but did not see any messages.

Can someone advise?
Thanks
Venki

## Version of Realm and Tooling

- Realm Object Server Version: ?
- Flavor:
  - [ ] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: ? (e.g. CentOS 6)
- Client SDK Version: ?
- Client OS & Version: ?

**Comment by nirinchev** [comment]
Do you have a reproduction project that we can try and build ourselves?

**Comment by vaddanki** [comment]
Thanks for the response. I will send it tonight when I go home.
________________________________

**Comment by nirinchev** [comment]
Closing due to lack of response. Feel free to reopen if you're still getting this error and can share a repro project.
