### ISSUE TITLE
PropertyChanged of RealmObject does not fire

### ISSUE THREAD

**Issue by AlonikiX** [realm/realm-dotnet#1681]
## Questions: 
Hi, the `PropertyChanged` event of `RealmObject` does not fire in my project. I think that is because something wrong in my code. In order to find out the reason, I created a repro, https://github.com/AlonikiX/RPCNE.git, and I already set up the ROS on AWS, so just simply run the project, it should work. There are 4 `RealmObject` in this repro, they are all in `Models` folder. And the main page is `HomePage`, which is located in `Views` folder and its view model is in `ViewModels`.  When running the app, there will be a list view, and its cell properties are binding with different objects. And the bottom buttons can modify different properties.

## StackOverflow:
https://stackoverflow.com/questions/48533217/realm-dotnet-nested-realmobject-propertychanged-does-not-fire

## Goals
When clicking `Age`, the `RPDeviceList.RPDevices[x].RPObject.PropertyChanged` should fire, and the UI should update automatically as well. Also, if any changes via ROS, the app should also have the same behaviour. The goal is how to implement auto update of the UI, when any RealmObject changed by local operations or remote operations. And if it is possible, I look forward to knowing what causes the issue.

## Expected Results
All `PropertyChanged` events I added to different objects should fire, and UI should update automatically.

## Actual Results
The `PropertyChanged` of the nested object `RPObject` does not fire, the UI does not update neither, however, its data does change. The non-nested property `RPDevice.Battery` can update the UI correctly, but `PropertyChanged` does not fire as well. When I move add property changed event to the button click command, it sometimes can fire but the UI still does not update.

Maybe I am just being tricked by some stupid mistakes, but I hope anyone can help me. Thank you.

**Comment by nirinchev** [comment]
Looking at the code (I imagine the relevant portion is https://github.com/AlonikiX/RPCNE/blob/master/RPCNE/ViewModels/HomePageViewModel.cs#L138) it looks like your Realm objects get garbage collected which is why the property changed event never fires. To quickly verify if that's the case, create a class-level list and them to it in the loop. Something like:

```cs
foreach (var device in DeviceList.Devices) {
    //Nested RealmObject PropertyChanged does not fire
    device.Object.PropertyChanged += (sender, e) => {
        Console.WriteLine(e.PropertyName);
        OnPropertyChanged("DeviceList");
    };
    this.cacheList.Add(device);

    // Rest of your logic
}
```

**Comment by AlonikiX** [comment]
`this.cacheList.Add(device);` this works for `device` level, the `PropertyChanged` does fire now, and without this statement, it won't fire; so I think you guess is correct. However, it still not works for `device.Object`. Even I emulate your solution, create a cache list for `device.Object`, the `PropertyChanged` still does not fire. Another strange thing is, in `device.PropertyChanged` event, the `OnPropertyChanged("DeviceList");` will not update the changed `device.Object` to the UI.

**Comment by nirinchev** [comment]
How are you emulating my solution? You must do something like:

```cs
var obj = device.Object;
obj.PropertyChanged += (s,e) => {};
objectCache.Add(obj);
```

Note that I create a local variable and don't use the property accessor twice as the way Realm works, it will give you a new object every time you access the property. Also, note that this solution is in no way recommended - it was meant to confirm the source of your issues. It's not a good idea to use that as it can cause serious memory leaks if you're not careful. In general, I don't see why you need to manually raise property changes instead of relying on the data binding engine itself.

**Comment by AlonikiX** [comment]
Thanks for your correction, now the `PropertyChanged` works for `obj` too. As for why I want to use property changes, that is because I tried to use data binding, but it did not update the nested object changes to the UI. I know there is something wrong in my code. 

Sorry, my English is not very good, please pardon me for restating what I want to achieve. 

I have a `Listview` which should present the real-time data of  `Device.Battery` and `Device.Object.Age` in cells. Now data binding works well for `Device.Battery`, but not for `Device.Object.Age`, so I wonder how I should implement it. What is the right way to bind a nested realm object with the UI, so that when I change the data vis ROS or locally and update the UI automatically? 

Here is my current implementation (not working):
![f16cacb1-61da-4329-a757-f09454dee198](https://user-images.githubusercontent.com/11833091/35773578-94aada34-09aa-11e8-83c4-871a612e6295.png)
![2f486606-ec8f-4f10-98a0-d19300b85827](https://user-images.githubusercontent.com/11833091/35773601-4f255b96-09ab-11e8-97ea-21f5e2fc4d59.png)

If I should not use nested realm object (use the property accessor twice), then how should I design my model?

Sincerely thanks for your kindly helps and time : )

**Comment by nirinchev** [comment]
Closing this as very old. Feel free to open a new issue if that's still a problem.
