### ISSUE TITLE
System.EntryPointNotFoundException: shared_realm_install_callbacks

### ISSUE THREAD

**Issue by Orma07** [realm/realm-dotnet#1684]
## Goals

Hi, i'm tring to use realm in my Xamarin .net standard library and when i use : 
```
 var realm = Realm.GetInstance(GetRealmConfiguration());
 public RealmConfiguration GetRealmConfiguration()
        {
            var config = new RealmConfiguration("byme-mobile.db");
            //LogBroker.Instance.TraceDebug("Realm path: " + config.DatabasePath);
            config.SchemaVersion = DataModelSchema.MODEL_SCHEMA_VERSION;
            config.ShouldDeleteIfMigrationNeeded = true; // TODO: we should set up a proper migration mechanism based on the current/new schema version :)
            return config;
        }
```

 

## Expected Results
get istance of realm

## Actual Results

UNHANDLED EXCEPTION:
02-07 16:12:45.715 I/MonoDroid( 3027): System.TypeInitializationException: The type initializer for 'Realms.SharedRealmHandle' threw an exception. ---> System.EntryPointNotFoundException: shared_realm_install_callbacks
02-07 16:12:45.715 I/MonoDroid( 3027):   at (wrapper managed-to-native) Realms.SharedRealmHandle+NativeMethods:install_callbacks (Realms.SharedRealmHandle/NativeMethods/NotifyRealmCallback,Realms.SharedRealmHandle/NativeMethods/GetNativeSchemaCallback)
02-07 16:12:45.715 I/MonoDroid( 3027):   at Realms.SharedRealmHandle..cctor () [0x0002c] in /Users/realm/workspace/realm_realm-dotnet_PR-1633/Realm/Realm/Handles/SharedRealmHandle.cs:132 
02-07 16:12:45.715 I/MonoDroid( 3027):    --- End of inner exception stack trace ---
02-07 16:12:45.715 I/MonoDroid( 3027):   at Realms.RealmConfiguration.CreateRealm (Realms.Schema.RealmSchema schema) [0x000b4] in /Users/realm/workspace/realm_realm-dotnet_PR-1633/Realm/Realm/RealmConfiguration.cs:153 
02-07 16:12:45.715 I/MonoDroid( 3027):   at Realms.Realm.GetInstance (Realms.RealmConfigurationBase config, Realms.Schema.RealmSchema schema) [0x0003e] in /Users/realm/workspace/realm_realm-dotnet_PR-1633/Realm/Realm/Realm.cs:131 
02-07 16:12:45.715 I/MonoDroid( 3027):   at Realms.Realm.GetInstance (Realms.RealmConfigurationBase config) [0x00000] in /Users/realm/workspace/realm_realm-dotnet_PR-1633/Realm/Realm/Realm.cs:86 
02-07 16:12:45.715 I/MonoDroid( 3027):   at ByMeLib.Database.ByMeRealmProvider.GetRealm () [0x00001] in C:\Users\User-Kalpa\Documents\workspace\byme_app_mobile\ByMe_Lib\ByMe_Lib\Database\RealmProvider.cs:18 
02-07 16:12:45.715 I/MonoDroid( 3027):   at MTSByMe.App..ctor () [0x0007c] in C:\Users\User-Kalpa\Documents\workspace\byme_app_mobile\MTSByMe\MTSByMe\App.xaml.cs:49 
02-07 16:12:45.715 I/MonoDroid( 3027):   at MTSByMe.Android.MainActivity.OnCreate (Android.OS.Bundle bundle) [0x0009d] in C:\Users\User-Kalpa\Documents\workspace\byme_app_mobile\MTSByMe\MTSByMe.Android\MainActivity.cs:95 
02-07 16:12:45.715 I/MonoDroid( 3027):   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <848bbd7c681a4975918c72f17d2f5144>:0 
02-07 16:12:45.715 I/MonoDroid( 3027):   at (wrapper dynamic-method) System.Object:6689618a-2c60-43cd-88b1-51864f45a3f0 (intptr,intptr,intptr)
02-07 16:12:45.744 W/art     ( 3027): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
02-07 16:12:45.751 D/Mono    ( 3027): DllImport searching in: '__Internal' ('(null)').
02-07 16:12:45.751 D/Mono    ( 3027): Searching for 'java_interop_jnienv_throw'.
02-07 16:12:45.751 D/Mono    ( 3027): Probing 'java_interop_jnienv_throw'.
02-07 16:12:45.752 D/Mono    ( 3027): Found as 'java_interop_jnienv_throw'.

## Version of Realm and Tooling

- Realm 2.1.0
- Flavor:
  - [x] Developer
  - [x] Professional
  - [x] Enterprise
- Client SDK Version: Android api 26
- Client OS & Version: Android 6.0

**Comment by nirinchev** [comment]
Did you install Realm in your Android project as well?

**Comment by Orma07** [comment]
Yes I did

**Comment by nirinchev** [comment]
Do you think you can share your project so we can try to investigate? From the description, I can't spot anything obviously wrong, yet we do have tests that pass with very similar setup :)

**Comment by Orma07** [comment]
I'm trying Realm on  custom android, unfortunately, I couldn't post code

**Comment by nirinchev** [comment]
Does that happen on a completely new project?

**Comment by Orma07** [comment]
Yes

**Comment by nirinchev** [comment]
Can you share that completely new project then? I don't suppose it contains any secret code.
