### ISSUE TITLE
Realm 2.0 and 2.1 Fails to Install on .NET Standard 1.4

### ISSUE THREAD

**Issue by zlstringham** [realm/realm-dotnet#1685]
## Goals

Install `Realm.Database` into a .NET Standard 1.4 Library.

## Expected Results

<img width="194" alt="realm nuget" src="https://user-images.githubusercontent.com/4406098/35944740-69f6a6b4-0c12-11e8-982d-4a6ed715fc79.PNG">
<img width="461" alt="realm doc" src="https://user-images.githubusercontent.com/4406098/35944757-7c9af0b8-0c12-11e8-9522-2c300ea8162f.png">

[(ref)](https://realm.io/docs/dotnet/latest/)

## Actual Results

NuGet fails with a non-descriptive error about changes being rolled back. I suspect this is due to Realm.Database 2.0's dependency bump from `NETStandard.Library (>= 1.6.1)` to `NETStandard.Library (>= 2.0.0)` despite the package still saying `NETStandard,Version=1.4`

## Steps to Reproduce

1. Open Visual Studio
2. Create a .NET Standard Library project
3. Change the project version from .NET Standard 2.0 to .NET Standard 1.4
4. Try to install `Realm.Database` version 2.1.0 from NuGet.

## Version of Realm and Tooling

- Realm Object Server Version: ?
- Flavor:
  - [ ] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: ? (e.g. CentOS 6)
- Client SDK Version: ?
- Client OS & Version: ?

**Comment by lunelake** [comment]
I have same issue.

**Comment by nirinchev** [comment]
Sorry for the delay - are you seeing that on VS for Mac or Windows? If it's on Mac, then it's likely a bug in Visual Studio and you'll be able to install the package by manually editing the project file to reference Realm and then issuing the `Restore Packages` command.

**Comment by zlstringham** [comment]
Sorry. This would have been VS 2017 for Windows.

**Comment by nirinchev** [comment]
Closing this as it concerns a very old version of the library.
