### ISSUE TITLE
Do we have cascading delete function?

### ISSUE THREAD

**Issue by AlonikiX** [realm/realm-dotnet#1686]
Hi, I wonder if there is a handy function which can be used to remove any realm objects recursively. Currently I just use c# reflection to completely delete or clone a realm object and its nested objects, but I am not sure whether it is a good workaround.

**Comment by nirinchev** [comment]
At the moment we don't have anything built in. We're tracking it in https://github.com/realm/realm-dotnet/issues/310.

We have exposed a property called [`BacklinksCount`](https://realm.io/docs/dotnet/2.1.0/api/reference/Realms.RealmObject.html#Realms_RealmObject_BacklinksCount) on the `RealmObject` class to check the # of objects that link to this one. You can probably use that in your custom logic to avoid deleting objects that are still being referenced.
