### ISSUE TITLE
How do you query the linked object's fields just like in the java version?

### ISSUE THREAD

**Issue by sidgo28** [realm/realm-dotnet#1687]
## Goals
I tried this but it doesn't work: 
`realm.Where(x => x.Group.Name == "Tax");`

## Version of Realm and Tooling

- Realm Object Server Version: ?
- Flavor:
  - [ ] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: ? (e.g. CentOS 6)
- Client SDK Version: ?
- Client OS & Version: ?

**Comment by nirinchev** [comment]
Unfortunately, this is not currently supported by the .NET SDK and is tracked by https://github.com/realm/realm-dotnet/issues/806.
