### ISSUE TITLE
Crash when using Realm in published WinForms application

### ISSUE THREAD

**Issue by tjosten** [realm/realm-dotnet#1690]
## Goals

I am working on a **WinForms** application with C# and .NET 4.6.1. I have installed the Realm.Database and Realm.DataBinding package with NuGet, and can see both the references under Project -> References in Visual Studio. 

When running my app from Visual Studio, everything works fine and as expected. When publishing my app with Visual Studio though, copying the resulting installer as well as the "Application Files" folder to another PC and installing my app, **it crashes with a DllNotFoundException saying that "realm-wrappers.dll" was not found.**

## Expected Results

The applications works when run from Visual Studio as well as when published.

## Actual Results

The application crashes when published and installed on another PC.

`Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException
   at Realms.SynchronizationContextEventLoopSignal.install_eventloop_callbacks(get_eventloop, post_on_event_loop, release_eventloop)
   at Realms.SynchronizationContextEventLoopSignal.Install()
   at Realms.NativeCommon.Initialize()
   at Realms.SharedRealmHandle..cctor()`

## Steps to Reproduce

Create new WinForms application. Install Realm.Database. Initialize a new Realm. Compile and publish to another PC.

## Version of Realm and Tooling

- Realm Object Server Version: not applicable
- Client SDK Version: v2.1.0
- Client OS & Version: Windows 10 Pro, 1709, Build 16299.15

**Comment by nirinchev** [comment]
I'm not familiar with how winforms does publishing but from the error it seems it hasn't included one of Realm's dlls. Can you verify that all the dlls in your debug build are also present in the published version?

**Comment by tjosten** [comment]
I have meanwhile switched from the Visual Studio-included publishing mechanism to creating a MSI file with WiX Toolset; it does work fine with this. I am closing the issue because it was most probably a configuration issue on my side.
