### ISSUE TITLE
Support for F# properties

### ISSUE THREAD

**Issue by AdhemarVandamme** [realm/realm-dotnet#1691]
I submit this as an issue/enhancement/feature request, because that’s what I think is necessary to achieve my goal.
However, any other idea on how to proceed is appreciated.

## Goals

I recently started to learn and appreciate Microsoft’s functional-flavoured language for .NET, F#.
I’m currently porting a number of my toy projects to F#.
It’s mostly a satisfying exercice: my F# code is generally shorter and cleaner than the C# equivalent.

But **I haven’t managed to get Realm working under F#**.

## Analysis

I believe the reason is that F# has no true **auto-implemented properties**, unline C# v3.0+.

The closest equivalent to

```C#
public class Dog : RealmObject {
    public string Name { get; set; }
    public int Age { get; set; }
    public Person Owner { get; set; }
}

public class Person : RealmObject {
    public string Name { get; set; }
    public IList<Dog> Dogs { get; }
}
```

that I managed, is

```F#
type Dog () =
    inherit RealmObject ()
    member val Name = Unchecked.defaultof<string> with get, set
    member val Age = Unchecked.defaultof<int> with get, set
    member val Owner = Unchecked.defaultof<Person> with get, set

and Person () =
    inherit RealmObject ()
    member val Name = Unchecked.defaultof<string> with get, set
    member this.Dogs with get () = Unchecked.defaultof<IList<Dog>>
```

**Update**: the last line should be
```
    member val Dogs = Unchecked.defaultof<IList<Dog>>
```

whose properties are not quite auto-implemented, since the code specifies the initial value (and won’t compile if it doesn’t).
(I haven’t examined the CIL bytecode of the C# and F# classes, but I’m pretty sure they differ.)

Since those properties aren’t really auto-implemented, they don’t get persisted in Realms.

## Actual Results

Result of the compilation of the F# classes above:

```
warning : Fody/RealmWeaver: Dog.Owner is not an automatic property but its type is a RealmObject which normally indicates a relationship.
error : Fody/RealmWeaver: Class Dog is a RealmObject but has no persisted properties.
error : Fody/RealmWeaver: Class Person is a RealmObject but has no persisted properties.
```

## Feature request

I don’t hold my breath for F#-the-language going to include auto-implemented properties in the near future, so this is a feature request for a `[<Persist>]` attribute that allows properties to be persisted in Realms (ignoring if necessary their implementations) despite not being auto-implemented.
One can think of it as the opposite of the `[<Ignore>]` attribute, which allows properties to **not** be persisted in Realms, when they are auto-implemented.

**Comment by nirinchev** [comment]
Sorry for getting back to you so late. Unfortunately, we're quite busy at the moment and it's unlikely we'll be able to look into this in the next few weeks. Briefly looking at your proposal though, it seems reasonable and not a huge change, so if you're up for it, we'd be more than happy to review a PR :)

**Comment by AdhemarVandamme** [comment]
Apparently, properties that are defined with `member val` **are** called _automatically implemented properties_. And they **do** have _backing stores_ (_backing fields_).

There was an error in the way I defined `Dogs` in F#. The way to define a read-only automatically implemented property is
```
and Person () =
    inherit RealmObject ()
    member val Name = Unchecked.defaultof<string> with get, set
    member val Dogs = Unchecked.defaultof<IList<Dog>>
```

I had a look at the CIL bytecode. The difference is smaller than I reckoned.

The CIL bytecode from C#:
```
.field private string '<Name>k__BackingField'

.method public hidebysig specialname instance string 
        get_Name() cil managed
{
  .custom instance void [mscorlib]System.Runtime.CompilerServices.CompilerGeneratedAttribute::.ctor() = ( 01 00 00 00 ) 
  // Code size       7 (0x7)
  .maxstack  8
  IL_0000:  ldarg.0
  IL_0001:  ldfld      string Dog::'<Name>k__BackingField'
  IL_0006:  ret
} // end of method Dog::get_Name

.method public hidebysig specialname instance void 
        set_Name(string 'value') cil managed
{
  .custom instance void [mscorlib]System.Runtime.CompilerServices.CompilerGeneratedAttribute::.ctor() = ( 01 00 00 00 ) 
  // Code size       8 (0x8)
  .maxstack  8
  IL_0000:  ldarg.0
  IL_0001:  ldarg.1
  IL_0002:  stfld      string Dog::'<Name>k__BackingField'
  IL_0007:  ret
} // end of method Dog::set_Name
```

The CIL bytecode from C#:
```
.field assembly string Name@

.method public hidebysig specialname instance string 
        get_Name() cil managed
{
  // Code size       8 (0x8)
  .maxstack  8
  IL_0000:  nop
  IL_0001:  ldarg.0
  IL_0002:  ldfld      string Dog::Name@
  IL_0007:  ret
} // end of method Dog::get_Name

.method public hidebysig specialname instance void 
        set_Name(string v) cil managed
{
  // Code size       9 (0x9)
  .maxstack  8
  IL_0000:  nop
  IL_0001:  ldarg.0
  IL_0002:  ldarg.1
  IL_0003:  stfld      string Dog::Name@
  IL_0008:  ret
} // end of method Dog::set_Name
```

The initial values, which is not optional in F# automatically implemented properties, are only used in the constructors.

The reason the C# code works, and the F# code doesn’t, is that the CIL of the `get`-method in the C# version (as well as the `set`-method, but only the `get`-method is checked) is decorated with a `CompilerGeneratedAttribute`. Without this attribute on the `get`-method, `IsAutomatic(this PropertyDefinition property)` in `PropertyDefinitionExtensions.cs` won’t return `true`.

**Comment by nirinchev** [comment]
Nice work! So does that mean that if you just add `[<CompilerGenerated>]` on your properties, it would work out of the box?

**Comment by AdhemarVandamme** [comment]
Unfortunately no, I tried that. That doesn’t decorate the `get`-method.

**Comment by nirinchev** [comment]
Ah... that will be applied on the property itself, right? So in the weaver we should check the custom attributes of the property in addition to the ones on the get method. Do you feel like trying it out? You should be able to clone the repo, unload everything from the solution except the weaver and monkey patch it by replacing the .dll in the nuget package folder.

**Comment by AdhemarVandamme** [comment]
Yes, now that I have figured this out this far, I feel like trying this out myself.
But I won’t in the next 10 days.

**Comment by nirinchev** [comment]
Okay, I'll ping you in this issue in case I start working on it to avoid duplicating work :)

**Comment by ChXIII** [comment]
First of all, it's possible to use Realm with F# but requires implementing property with explicit backing field like so:
```fsharp
type Guitar() =
    inherit RealmObject()
    let mutable _id = ObjectId.GenerateNewId()
    member this.Id
        with [<CompilerGenerated>] get () = _id
        and set id = _id <- id
````
Secondly, I can create a PR that fixes but but I'm not sure what would be a better solution:
- weaver can check custom attribute of the property itself. However, programmer would have to mark each property with `CompilerGenerated` attribute:
```fsharp
type Guitar() =
    inherit RealmObject()
    [<PrimaryKey; CompilerGenerated>]
    member val Id = ObjectId.GenerateNewId() with get, set
    [<Required; CompilerGenerated>]
    member val Model: string = null with get, set
    [<CompilerGenerated>]
    member val Price = 0.0 with get, set
```
But at least it's not really F#-specific solution and can be used in any language.
- weaver can check name of backing field. F#-compiler names backing fields for auto-implemented properties as `PropertyName@` (C# does similar thing - `'<propertyName>k__BackingField'`). C# and VB don't allow names with `@` at the end, F# reserves such names for use in compiler. So the possibility of false positive seems low.
- Opt-in way with separate nuget-package with weaver that runs before Realm.Fody and adds `CompilerGenerated` attributes.
