### ISSUE TITLE
WPF App Build Error

### ISSUE THREAD

**Issue by justinrogowski** [realm/realm-dotnet#1693]
Apologies if I have missed a solution somewhere. I have searched through the current issue library and help docs. 

I am experiencing a problem when building a WPF App project in VS2017. I have tried this on Windows 7 and Windows 10. I install VS2017 community edition, create a new 4.6.2 WPF App project and then add Realm from NuGet.

After this the project will not build. I get the following error:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Unknown build error, 'Binary format of the specified custom attribute was invalid.'

I am new to realm and I appreciate that this might be specific to my configuration so any pointers or things to check for would be beneficial.

I have also tried updating all packages that can be updated via NuGet and still experience the error.

Does anyone have any ideas?

## Goals

Build a simple WPF App in VS2017 using Realm from NuGet

## Expected Results

Build Succeeded
## Actual Results

Severity	Code	Description	Project	File	Line	Suppression State
Error		Unknown build error, 'Binary format of the specified custom attribute was invalid.'

C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.WinFx.targets(268,9): error MC1000: Unknown build error, 'Binary format of the specified custom attribute was invalid.' 

## Steps to Reproduce

1. Open VS2017
2. Create 'WPF App' Project (Target 4.6.2 - Does the same for 4.7 & 4.7.1 etc.)
3. Add Realm from NuGet - wait for install to complete
4. Build project - This is where I get the error

## Version of Realm and Tooling

- Realm Object Server Version: N/A
- Flavor:
  - [x] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: N/A
- Client SDK Version: Realm 2.1
- Client OS & Version: Windows 10 Pro (1709 - 16299.248)

**Comment by justinrogowski** [comment]
Could anyone confirm at all if they are experiencing a similar issue?

If I don't get any feedback to this issue due to time constraints (which I understand), could someone at least let me know when a new release of the dotnet version might be released so I could try with that?

My current workaround:

I am able to test Realm by adding it to a Class Library. I then put all Realm code in that library and reference it in my WPF App. I make sure I do NOT reference Realm.Sync in the WPF App. This allows me to compile and run (I need to make sure I swap out the realm-wrappers.dll with the one from the Class Library or else I can't use the Sync features of course). 

This isn't ideal of course and need a solution that solves the main build error for WPF Apps.

Writing and reading from a synced realm seems to work fine for simple objects in this test environment. I have encountered other issues when setting related objects but I will open a new issue for those specifically if they keep happening.

**Comment by nirinchev** [comment]
Sorry for getting back to you so late. It looks like this error would be caused by the weaver generating incorrect IL. It's surprising though as we have tests that make sure Realm works as expected on .NET Framework projects. We have our hands full at the moment, but if you can create a repro, I'd love to take a look once I get some free time.

**Comment by justinrogowski** [comment]
[BlankRealmTest.zip](https://github.com/realm/realm-dotnet/files/1804069/BlankRealmTest.zip)

This is simply an empty 'WPF App' project with Realm added from NuGet (Newest Version). Just building this shows the error. 

Let me know how you get on. 

Also, I don't suppose you know when you might get a chance to take a look at this? Is it going to be a case of days or weeks do you think?

Thanks

**Comment by Martynnw** [comment]
Just to add my team has run into the same issue which manifested when we tried to build a nuget package for a project using Realms 3.0.

When packaging nuget makes a call to CustomAttributeData.GetCustomAttributes which fails silently due to the 'Binary format of the specified custom attribute was invalid.' exception. Nuget.exe returns

```
Authors is required.
Description is required.
```

For now we will have to downgrade to Realms 2.0, being able to package our libraries is essential.

**Comment by nirinchev** [comment]
Links to the prerelease nugets:

https://drive.google.com/file/d/1XIoOBQAZh6axhbhJ3B8qjaJmR9FFbdil/view?usp=sharing
https://drive.google.com/file/d/1AzkWPgVWVP-fPyeE_86RVjJj2gNc__24/view?usp=sharing

**Comment by tuyen-vuduc** [comment]
@nirinchev I still faced this issue on Realm v3.1.0.

I have latest PropertyChanged.Foday v2.5.8 and latest Realm v3.1.0 installed.

My weavers.xml
```
<?xml version="1.0" encoding="utf-8"?>
<Weavers>
  <PropertyChanged />
  <RealmWeaver/>
</Weavers>
```
Plz help.

**Comment by nirinchev** [comment]
How is that related to this issue? Nothing in the logs you posted seems to suggest that it's the same problem.

**Comment by tuyen-vuduc** [comment]
I created another issue for this (#1758)
