### ISSUE TITLE
[Feature] Tizen support

### ISSUE THREAD

**Issue by listepo** [realm/realm-dotnet#1697]
## Goals
It would be nice to have support for [Tizen](https://developer.tizen.org/development/visual-studio-tools-tizen/installing-visual-studio-tools-tizen)

## Expected Results
Support for Tizen platform

**Comment by nirinchev** [comment]
Thanks for the feature request. We're constantly evaluating additional platforms to support and, while Tizen is definitely promising, it doesn't seem enough people are interested in developing for it to justify the cost of supporting yet another platform. I'm going to leave the issue open, however, so people can add reactions to the first post and if it looks like many people are thumbs-upping the idea, we'll reevaluate.
