### ISSUE TITLE
Uncompatible with PropertyChanged.Fody

### ISSUE THREAD

**Issue by HobDev** [realm/realm-dotnet#1702]
## Goals

I want to use realm in my solution as well as Fody.PropertyChanged

## Expected Results

Both packages could be included in a solution

## Actual Results

The <PropertyChanged/> markup in FodyWeaver.xml above <RealmWeaver/> through an exception. But if the markup is put below <RealmWeaver/> the realm database doesn't work correctly. The realm object creates but properties remain null in the database

## Steps to Reproduce
install both packages and do a add operation

## Versions of realm and tooling
realm version 2.1

- Realm Object Server Version: ?
- Flavor:
  - [ ] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: ? (e.g. CentOS 6)
- Client SDK Version: ?
- visual sudio for mac

**Comment by nirinchev** [comment]
We have tests that verify Realm is compatible with `PropertyChanged.Fody` 1.53.0. We don't officially claim compatibility, but we do our best efforts not to break things when used alongside that package. Can you share which version of `PropertyChanged.Fody` you're using as well as what your classes look like?

**Comment by HobDev** [comment]
I was using the latest version 2.2.9. Now I uninstalled it and the realm database is working fine. I am developing xamarin forms app using realm database. The app is developed using MVVM architecture of xamarin forms. The user just input a string in the Entry which is data bound to a property in View Model. I assign that property a property defined in Model. The Model is inherited from RealmObject.

**Comment by nirinchev** [comment]
`RealmObject` implement `INotifyPropertyChanged`, so there should be no reason to need Fody.PropertyChanged when using its inheritors.

**Comment by HobDev** [comment]
There are lots of other Properties in the View Model.  They are required for the app logic. The package is not necessary but to keep the code compact I want to use the PropertyChanged.Fody.  The View Model does not inherit from RealmObject. Does you suggest to do so.

**Comment by nirinchev** [comment]
Ah, okay, I misunderstood you, sorry. Can you paste the exception you get?

**Comment by HobDev** [comment]
When I write the value to realm it does not complain as if the value is persisted. But when I try to access it the "the null reference exception" is thrown. Note that the realm object is created and persisted but the the property remains null.

**Comment by nirinchev** [comment]
Can you try applying `[DoNotNotify]` on your RealmObject inheritors? That should in theory tell the PropertyChanged weaver to leave the class alone.

**Comment by HobDev** [comment]
I will try that and report back to you. Thanks

**Comment by HobDev** [comment]
Seems like the problem was related to old package of Fody. I re-installed PropertyChanged.Fody and updated Fody on all projects. Since the problem doesn't arise.

**Comment by EmmanVazz** [comment]
Hello what version did you get to work together. When I try to build on the latest of everything I get 

`1>    Fody: Fody (version 3.0.3.0) Executing
1>MSBUILD : error : Fody: The weaver assembly 'RealmWeaver.Fody, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null' references an out of date version of Mono.Cecil.dll. Expected strong name token of '1C-A0-91-87-7D-12-CA-03' but got '50-CE-BF-1C-CE-B9-D0-5E'. The weaver needs to update to at least version 3.0 of FodyHelpers.
1>    Fody:   Finished Fody 222ms.`

**Comment by HobDev** [comment]
As of today the latest realm package ver 3.0.0 is compatible with Fody ver 2.5.0. The Fody ver 2.5.0 is compatible with PropertyChanged.Fody ver 2.2.10. This combination is working in my project.

**Comment by EmmanVazz** [comment]
What order do you have them in your FodyWeaver?

**Comment by Dids** [comment]
@EmmanVazz The order is definitely important:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Weavers>
    <PropertyChanged/>
    <RealmWeaver/>
</Weavers>
```

**Comment by Dids** [comment]
Also note that Fody 3.x is not compatible with Realm, not yet at least.

**Comment by HobDev** [comment]
The order in the FodyWeaver.xml 
```
<?xml version="1.0" encoding="utf-8" ?>
<Weavers>
    <RealmWeaver/>
     <PropertyChanged/>   
</Weavers>
```
Earlier I put Propertychanged on top and was getting compile time error.

**Comment by Dids** [comment]
I've definitely had issues with the `PropertyChanged` weaver running _after_ `RealmWeaver`, since it can potentially overwrite any changes done by the Realm weaver.

**Comment by HobDev** [comment]
Yes, you are right. Keeping `PropertyChanged' before `Realmweaver` is adviced in other thread also.

**Comment by EmmanVazz** [comment]
hmm I get the same error. Putting it in that order does make that error go away. However all the realm object save property values as null.

**Comment by EmmanVazz** [comment]
For those that get that error, I removed [assembly: XamlCompilation(XamlCompilationOptions.Compile)] from the top of my App.xaml.cs and that made the error go away. I have propertychanged before realm in the weaver and everything is working properly. I guess XamlC messes something up for some odd reason.
