### ISSUE TITLE
Race conditions in partial sync subscriptions

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-dotnet#1716]
It looks like there is some race condition in the partial sync subscription logic that manifests itself in peculiar ways.

This subscription doesn't appear to work:

```csharp
var subscription = realm.All<Foo>().Subscribe();
await subscription.WaitForSynchronizationAsync(); // Never resolves
```

Similarly, subscribing twice results in similar behavior:

```csharp
var subscription = realm.All<Foo>().Where(f => f.Bar > 0).Subscribe();
await subscription.WaitForSynchronizationAsync(); // <-- works

var subscription2 = realm.All<Foo>().Where(f => f.Bar > 0).Subscribe();
await subscription2.WaitForSynchronizationAsync(); // <-- never resolves

```

**Comment by Dids** [comment]
This still seems to be an issue, but only sometimes. Sometimes the subscriptions resolve, sometimes they don't. More often than not they don't.

**Comment by nirinchev** [comment]
This is likely a different issue, as the one reported here was fixed (and we have a unit test to verify it). Can you please open a new issue, ideally with some repro instructions so we can take a look?
