### ISSUE TITLE
# chack list empty

### ISSUE THREAD

**Issue by gantich** [realm/realm-dotnet#1724]
## Version of Realm and Tooling

- Realm Object Server Version: ?
- Flavor:
  - [ ] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: ? (e.g. CentOS 6)
- Client SDK Version: ?
- Client OS & Version: ?

**Comment by nirinchev** [comment]
Can you please fill in the template? The title of this issue doesn't make a lot of sense.
