### ISSUE TITLE
Android Keystore SSL certificate validation

### ISSUE THREAD

**Issue by fealebenpae** [realm/realm-dotnet#1727]
See https://github.com/realm/realm-js/pull/1761

**Comment by guatedude2** [comment]
I'm too interested in getting SSL working on RN android. 
Currently we have to use non SSL as we keep getting `Unknown OpenSSL error: 336707910`

**Comment by nirinchev** [comment]
This is worked around by upgrading to a sync client that bundles the certificates. Ideally, we should still integrate with the android keystore but it's lower priority now.

**Comment by nirinchev** [comment]
This is no longer needed with v10.
