### ISSUE TITLE
On Xamarin Android gets stuck on Realm.GetInstanceAsync call when using Realm Cloud Platform 

### ISSUE THREAD

**Issue by rdelrosario** [realm/realm-dotnet#1732]
When using Realm Platform Cloud cannot get the realm instance on Xamarin Android, task never returns a result when calling **Realm.GetInstanceAsync**.

Code snippet.

```cs
    var credentials = Credentials.UsernamePassword("user", "password", false);
    var user = await User.LoginAsync(credentials, new Uri($"https://{SyncHost}");
    var realm =  await Realm.GetInstanceAsync(new SyncConfiguration(user,new Uri($"realms://{SyncHost}/studenthub"));
```

Code gets stuck on Realm.GetInstanceAsync call.

## Goals

Get the realm database instance on Xamarin Android.

## Expected Results

Should behave as on iOS and return the Realm instance.

## Actual Results

When running on Xamarin Android never gets a response from **Realm.GetInstanceAsync** method. On iOS works perfectly.

## Steps to Reproduce

On Xamarin Android:

1. Create a realm platform cloud instance
2. Create a realm path with some classes inside.
3. Create a Realm User 
4. Try to login with username/password
5. Try to get realm by using **Realm.GetInstanceAsync**

## Code Sample

```cs
    var credentials = Credentials.UsernamePassword("user", "password", false);
    var user = await User.LoginAsync(credentials, new Uri($"https://{SyncHost}");
    var realm =  await Realm.GetInstanceAsync(new SyncConfiguration(User.Current,new Uri($"realms://{SyncHost}/studenthub"));
```

## Version of Realm and Tooling

- Realm Cloud

- Flavor:
  - [X] Developer
  - [ ] Professional
  - [ ] Enterprise

- Client SDK Version:  3.0.0
- Client OS & Version: Android 6.0

**Comment by nirinchev** [comment]
This is likely due to the fact Android doesn't allow access to the certificate store using the native API. We'll provide a workaround with a new version that we'll release soon but in the meantime you can set EnableSSLValidation to false on the SyncConfiguration.
