### ISSUE TITLE
If you load the application without internet when opening a Realm with SyncConfiguration it doesn't load data until you are online even when the local Realm is already synced with data.

### ISSUE THREAD

**Issue by Char0394** [realm/realm-dotnet#1742]
After realm is synced, if you close the application and then open the application without an internet connection the realm it should load the data from the local file instead of waiting until has internet connection to load the data since this blocks the application to be usable for offline scenarios when is opened without internet connection.

## Goals

Be able to load the local version of the data when there's no internet connection.

## Expected Results

Should load the data from the offline file when application is started without internet.

## Actual Results

Realm not loading data when there's not internet connection and a SyncConfiguration is specified.

## Steps to Reproduce

1.  Open the application with internet connection
2. Open a Realm with data using a SyncConfiguration
3. After data is shown close the application
4. Re-open application without internet connection (it won't load data, will stay waiting until you get connected to internet)

**Note: If you reconnect to internet then data will load but that doesn't work for my scenario because application is unusable until you reconnect to the internet, after that it will work even if you lose connection but will not if you close and reload the application.**

## Code Sample

```cs
 await Realm.GetInstanceAsync(new SyncConfiguration(user,serverUri){
					EnableSSLValidation = false
});
```

## Version of Realm and Tooling

Realm Cloud

- Flavor:
  - [ ] Developer
  - [ ] Professional
  - [X] Enterprise

- Client SDK Version: 3.0.0
- Client OS & Version: Android 6.0, iOS 11.0

**Comment by nirinchev** [comment]
`GetInstanceAsync` tries to download the data from the server before it returns, which cannot happen when you don't have connection. We currently don't handle connectivity changes as that would be too cumbersome across platforms, especially Android.

You could use `GetInstance` to open the local Realm and use it regardless of connectivity. If you want to notify the user when the local Realm has been synchronized with the server, you can use [`Session.WaitForDownloadAsync`](https://www.realm.io/docs/dotnet/3.0.0/api/reference/realms.sync.session#Realms_Sync_Session_WaitForDownloadAsync).
