### ISSUE TITLE
Unable to use Fody v3 with Realm

### ISSUE THREAD

**Issue by Hawxy** [realm/realm-dotnet#1743]
## Goals

Use the latest version of Fody alongside Realm

## Expected Results

Build successfully with Fody v3.

## Actual Results

- Inability to use Fody v3.0.3 due to:
`Fody: The weaver assembly 'RealmWeaver.Fody, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null' references an out of date version of Mono.Cecil.dll. Expected strong name token of '1C-A0-91-87-7D-12-CA-03' but got '50-CE-BF-1C-CE-B9-D0-5E'. The weaver needs to update to at least version 3.0 of FodyHelpers.	
`

From a quick search, this seems to be a repeat of the last time Fody had a major update, and thus it needs to be updated within Realm.

As a side note, there's a _lot_ of warnings produced when you add realm to XF, between version conflicts and osx libraries being referenced that don't exist. Maybe something to investigate.

## Steps to Reproduce
(I'm currently working on a XF v3.0 project)
1. Open Visual Studio 2017 15.7.1
2. Create a new Xamarin.Forms project using .NET Standard with Droid/iOS/UWP targets
3. Add Realm via nuget 
4. Build solution, get various warnings, but build successfully.
5. Add Fody v3.0.3 via nuget
6. Build, get above error.

## Version of Realm and Tooling

- Client SDK Version: 3.0.0
- Client OS & Version: Windows 10 1803

**Comment by anhhtz** [comment]
Downgrade Foddy to 2.5.0 and it works fine.

**Comment by andrekiba** [comment]
There is a way to fix this? Every time there is an update in Fody something breaks. In my project I also have PrepertyChanged.Fody and AsyncErrorHandler.Fody and it is almost impossible to find the correct formula to make them together! What is the correct way? Thank you!

**Comment by Hawxy** [comment]
Looks like this'll be fixed whenever #1744 gets merged

**Comment by Jyosua** [comment]
@andrekiba The latest Realm, 2.2.10 for PropertyChanged.Fody, and 2.5.0 for Fody. Just go to the desired nuget's page on nuget.org and click on each release until you see the dependency list 2.5.0 for Fody instead of 3+.
