### ISSUE TITLE
Why realm installs Net Standard libraries in my iOS and Android projects?

### ISSUE THREAD

**Issue by alexrainman** [realm/realm-dotnet#1745]
I will write my code on a Net Standard library and share it between platforms. It's kind of odd that when i install realm on my platform projects it's like the net standard version is being installed.

**Comment by nirinchev** [comment]
Realm is distributed as a .NET standard library, so there's nothing else that could be installed in your platform specific projects. The native libraries we use, however, are platform-specific and they end up in your executable.

Fody is needed to rewrite the compiled models and wire up the Realm infrastructure under the hood, otherwise, you would have to write a bunch of boilerplate code. It's needed because we can't know before compilation in which projects you define your models (you can define them in any project).

Do you have concerns about this architecture or you were just curious about it?

**Comment by alexrainman** [comment]
Not curious, I am testing it to see if it is a feasible solution for us. If i don't install Realm on my platform projects then i get an exception:

```
Could not load type of field 'RealmTest.DbService:Database' (0) due to: Could not load file or assembly 'Realm, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. assembly:Realm, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null type:<unknown type> member:(null) signature:<none>
```

**Comment by nirinchev** [comment]
You should install Realm in your platform projects because otherwise there's no way to get the native libraries that contain the core database logic. I'm confused - what is the reason not to install it in your platform projects?

**Comment by alexrainman** [comment]
I don't develop anything on platform specific. I do it all in my shared library so, i am expecting installing Realm in my Net Standard project, that i will share with iOS and Android, and then install the native library on each platform with no Net Standard dependency.

Bait and Switch trick, no?

**Comment by alexrainman** [comment]
All these packages shouldn't be there in my iOS project:

<img width="318" alt="screen shot 2018-05-24 at 6 35 08 pm" src="https://user-images.githubusercontent.com/3793554/40518659-5707d01a-5f81-11e8-8ff3-da6405b33a80.png">

I am expecting something like Realm.Database.iOS or something like that. And as Fody is also installed, then i have a FodyWeavers.xml everywhere.

Not clean.

**Comment by alexrainman** [comment]
Another issue, Realm.Database depends on Realm.DataBindings, and that's an specific package for Xamarin.Forms, and i am not using Forms.

Can you guys fix this?

Can you guys release a separated package just with the native libraries for Android and iOS? With not Net Standard or Xamarin.Forms dependencies?

**Comment by alexrainman** [comment]
Realm.DataBindings gets installed also in my Net Standard project where i don't use any Xamarin Forms stuff.

**Comment by alexrainman** [comment]
This is what is added as reference in my iOS project:

```
**/RealmTest/packages/Realm.Database.3.0.0/lib/netstandard1.4/Realm.dll
```

**Comment by alexrainman** [comment]
You dont need to split it. You can ship multiple assemblies in the same package targeting each platform and each of them with its own dependencies. Take a look at what i did with modernhttpclient-updated using a multi-target project.

It will stay intuitive for people to find your package but not needed packages won’t be installed on Android and iOS and you will end up with smaller assemblies being ship in your mobile app.

**Comment by alexrainman** [comment]
Sorry to hear that because thats not how Xamarin plugins work. You don’t ship platform specific code into the Net Standard assembly which will be referenced in your platform specific projects and end up with bunch of not needed packages being installed.

**Comment by nirinchev** [comment]
I'm sorry but I don't see any benefit to what you're proposing. We don't have platform specific code in our NETStandard assembly - all the platform specific code is in the native assemblies.

**Comment by alexrainman** [comment]
Thats exactly my point. If i use your native libraries in a native iOS or Android project, do i have to install all those packages? No.

**Comment by nirinchev** [comment]
I believe there's some fundamental misunderstanding here. Even though the .NET assembly is NETStandard and platform agnostic, you still need it if you want to declare your models in your iOS project. You can't subclass RealmObject if you don't reference an assembly that declares it. Similarly, we can't weave your models declared in the iOS project if we don't have Fody. So even though the Core logic is native, you still need the C# assembly that exposes it.

**Comment by alexrainman** [comment]
It cannot be done with a binding library? Isn’t RealmObject in the native library?

Going to take a look if i have some free time.

**Comment by nirinchev** [comment]
No, Realm isn't a binding library if I understand you correctly - it has native core, but that is written in C++ and the .NET SDK isn't just a wrapper around the Cocoa/Android SDKs, but a standalone project.

**Comment by alexrainman** [comment]
So, the native C++ core is not shared with Cocoa/Android SDKs?

**Comment by alexrainman** [comment]
Do you think something can be done where your current package is installed only on the shared library and then something smaller in Android and iOS to load the native core only? More like others Xamarin plugins?

Thanks.

**Comment by nirinchev** [comment]
Why does it matter - at the end of the day, you only get a single copy of the assembly. And no, I don't think that's possible because there may not be a shared project - people may have just an iOS project or a Windows project, or even a cross platform .NET Core project.
