### ISSUE TITLE
Migrate to a multi-target project (feature request)

### ISSUE THREAD

**Issue by alexrainman** [realm/realm-dotnet#1746]
## Goals

Installing Realm in Android and iOS means installing a native library on each platform.

## Expected Results

A minimum set of packages to be installed in Android and iOS without installing .Net Standard SDK and other related dependencies.

https://montemagno.com/converting-xamarin-libraries-to-sdk-style-multi-targeted-projects/

https://montemagno.com/new-plugin-for-xamarin-multi-target-templates-for-visual-studio-2017/

## Actual Results

<img width="326" alt="screen shot 2018-05-26 at 10 51 13 am" src="https://user-images.githubusercontent.com/3793554/40578037-bb5eea42-60d2-11e8-83ab-64bb830216aa.png">

**Comment by alexrainman** [comment]
How much time it can take to migrate the project? Ummm not much i guess.

Anyway, i hope you guys think about it.

👍🏻

**Comment by alexrainman** [comment]
So, with the current architecture, there's not way i can instal Realm only on my shared project.

**Comment by nirinchev** [comment]
No - Realm has platform-specific native libraries, which we can't realistically install in a shared project. Even with a multi-targeting approach, you will still need to install in the platform-specific projects.

**Comment by alexrainman** [comment]
Can this native libraries be distributed in a way that you install only them in Android and iOS?

**Comment by nirinchev** [comment]
They could, but we don't want to do that currently, because we'd like to allow people who don't have shared projects to be able to use Realm in an iOS-only or Windows-only application. Ultimately, we want to provide simple install instructions where people don't have to think about which nuget to install on which platform, do they want just the native libraries or the whole package, things like that. I'm not saying our distribution strategy is perfect, but it's super easy for people to get started.

We will consider making improvements on it when we have some spare time, but the way I see it, there are no real-world drawbacks (e.g. app size increase/performance degradation) with the current package structure. The only negative aspect is that it's installing some packages you may not need for compilation in your platform-specific project, but most of those are just reference assemblies, and the rest will get pulled in anyway from the shared project, so at the end of the day, it's just a few extra lines in your editor 🙃

**Comment by alexrainman** [comment]
I wish i have time to pull your code and create a Xamarin plugin from it.

I am in the middle of the same discussion with Couchbase.Lite team. They already have some platform specific packages called Couchbase.Lite.Support.[platform]. I think they will fix them so you don't need to install the whole thing when you are writing your BL in a shared project.

I believe that option needs to be offered. Won't take more from your time.

Thanks!

**Comment by alexrainman** [comment]
I found that adding this to the PropertyGroup of the shared .csproj solved the problem with Couchbase.Lite:

```
<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
```

Now i can install the library only on my shared project. They offer small platform specific packages that install the native libraries and provide a init method.

If i try this approach with Realm i get an exception:

```
System.TypeInitializationException
The type initializer for 'Realms.SharedRealmHandle' threw an exception.

base: {System.TypeLoadException}

{System.DllNotFoundException: realm-wrappers
  at (wrapper managed-to-native) Realms.SynchronizationContextEventLoopSignal.install_eventloop_callbacks(Realms.SynchronizationContextEventLoopSignal/get_eventloop,Realms.SynchronizationContextEventLoopSignal/post_on_event_loop,Realms.SynchronizationContextEventLoopSignal/release_eventloop)
  at Realms.SynchronizationContextEventLoopSignal.Install () [0x0003b] in /Users/realm/workspace/realm_realm-dotnet_PR-1723/Realm/Realm/Native/SynchronizationContextEventLoopSignal.cs:122 
  at Realms.NativeCommon.Initialize () [0x00119] in /Users/realm/workspace/realm_realm-dotnet_PR-1723/Realm/Realm/Native/NativeCommon.cs:91 
  at Realms.SharedRealmHandle..cctor () [0x00000] in /Users/realm/workspace/realm_realm-dotnet_PR-1723/Realm/Realm/Handles/SharedRealmHandle.cs:124 }
```

My advice is you guys can do the same for users that don't write platform specific code but BL is in a shared project.

Let's say you distribute packages named Realm.Xamarin.[platform] which i will install in iOS and Android. They can contain the native libraries and provide a method to initially load them (something you may be already doing in your current architecture, no?).

Thanks.

**Comment by nirinchev** [comment]
As already said multiple times, I can see no real benefit of doing that. We'll focus on features that actually improve people's apps for now, but you're welcome to fork the project and build the kind of package that fits your preferences 🙃

**Comment by alexrainman** [comment]
I can do that and maintain the new packages if you point me out how it can be done.

Thanks

**Comment by nirinchev** [comment]
Please create a new issue as what you're experiencing seems completely unrelated to this one.
