### ISSUE TITLE
(3rd party) ListView items does not refresh after deleting the last items from IRealmcollection

### ISSUE THREAD

**Issue by toumir** [realm/realm-dotnet#1747]
Hi, 

I wonder if the binding work correctly if I bind 3rd party ListView ItemSource to IRealmCollection and why it working for the Out-Of-The-Box ListView and not for 3rd party ListView 

## Goals
ListView Refreshed after deleting Item

## Expected Results
I tested this behavior with telerik & syncfusion ListView
- Item removed from Database ===> OK 
- ListView Updated ===> OK 

## Actual Results
- Item removed from databade, OK
- ListView **NOT Updated** although the item has been deleted from Database!

## Steps to Reproduce

1- using Add Item button : add multiple items to the ListView(Telerik or Syncfusion) add more than 2 Items
2- remove the **last** or the **before the last Item** from the ListView: swipe to the right to remove an item

**FYI : No problem with Out-of-the-Box ListView,** to test this : 
in the MainPage2.xaml, **comment** the 3rd party listview and **uncomment** the out-of-the-box Listview, 

## Code Sample
Full project attached 

## Version of Realm and Tooling
Realm 3.0.0, XF : 2.4.X and above, third party ListView Telerik
[DemoProj.zip](https://github.com/realm/realm-dotnet/files/2042643/DemoProj.zip)
[vid.zip](https://github.com/realm/realm-dotnet/files/2042644/vid.zip)

**Comment by toumir** [comment]
**"I think that the RealmResults collection does something that is incorrect, namely to raise a collection changed with action Remove and provide a null instead of the removed item. I am not sure what causes this behavior in the RealmResults collection. Perhaps this is a bug and you can contact the team developing the Realm library."**
answer from third party Listview support!

Can anyone Help, I think @nirinchev is busy for this days :) 
regards.

**Comment by nirinchev** [comment]
Unfortunately, this is by design - since Realm objects read their values directly from disk, when an object is removed, we can't provide meaningful values for its properties - we no longer know what they were before the deletion. We do provide the index of the removed item though, which should be enough for the listview to update its internal state (this is what the Xamarin/WPF implementations do).

**Comment by toumir** [comment]
Thanks @nirinchev for the quick reply, thus **I'm forced** to work with regular ListView

**Comment by nirinchev** [comment]
You can probably reach out to their support and verify how they are handling deletions - e.g. are they doing referential equality checks to remove the item. If that's the case, then, their design is a really bad fit for Realm as we don't ever keep instances of the objects around - every time you access an object from the list, you get a new instance, e.g.:

```csharp
var bars = foo.Bars; // foo is RealmObject and Bars is IList<Bar>
var bar1 = bars[0];
var bar2 = bars[0];

// bar1 and bar2 are different instances pointing to the same native data.
// we override .Equals to call into the native code and verify if they are indeed
// the same instances, but reference equality check will return false.
bar1.Equals(bar2); // true
bar1 == bar2; // false
object.ReferenceEquals(bar1, bar2); // false
```

If, however, they actually use indices, and are just surprised to get a `null` (throwing a NRE somewhere), you can create an adapter collection that proxies the events from the RealmCollection and when it encounters a deletion, replaces the `null` objects with empty objects (`new Bar()`).

In the worst case - if they check referential equality (and you really want to use their listview), you can still create an adapter collection that caches the elements of the RealmCollection and upon deletion delivers the correct instance (albeit now invalid, as the native object is gone).

**Comment by toumir** [comment]
not a bad Idea, thanks for your time Sir @nirinchev 👍

**Comment by toumir** [comment]
Let say we have Product Entity, **you have to override the Equals Method and GetHashCode if you wish**
```
public class Product : RealmObject
{
        [PrimaryKey]
        public string Id { get; set; }
        public string Name { get; set; }

        public override bool Equals(object obj)
        {
            if (object.ReferenceEquals(this, obj))
            {
                return true;
            }

            if (!(obj is Product other))
            {
                return false;
            }

            var areEqual = base.Equals(obj);

            if (this.IsValid && other.IsValid)
            {
                return base.Equals(obj);
            }

            if (!this.IsValid && !other.IsValid)
            {
                if (!areEqual)
                {
                }

                return true;
            }
            if (areEqual)
            {
            }
            return false;
        }
    }
```
**Define a proxy collection, in my case I have more than one collection, thus I make it generic**
```
public class Coll<TEntity> : IEnumerable, INotifyCollectionChanged where TEntity  : RealmObject
    {
        public object OldItem;

        private readonly IRealmCollection<TEntity> _realmCollection;

        public Coll(IRealmCollection<TEntity> realmCollection)
        {
            this._realmCollection = realmCollection;

            if (this._realmCollection != null)
            {
                this._realmCollection.CollectionChanged += RealmCollection_CollectionChanged;
            }
        }

        public event NotifyCollectionChangedEventHandler CollectionChanged;

        public IEnumerator GetEnumerator()
        {
            return this._realmCollection.GetEnumerator();
        }

        private void RealmCollection_CollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            NotifyCollectionChangedEventArgs args;
            if (e.Action == NotifyCollectionChangedAction.Remove)
            {
                args = new NotifyCollectionChangedEventArgs(NotifyCollectionChangedAction.Remove, this.GetOldItems(), e.OldStartingIndex);
            }
            else
            {
                args = e;
            }

            this.RaiseCollectionChanged(args);
        }

        private IList GetOldItems()
        {
            var oldItems = new List<object> { this.OldItem };
            return oldItems;
        }

        private void RaiseCollectionChanged(NotifyCollectionChangedEventArgs e)
        {
            this.CollectionChanged?.Invoke(this, e);
        }
    }
```

**Usage**
In the ViewModel side, define a realmcollection

```
private IRealmCollection<Product> _products;
public IRealmCollection<Product> Products
{
 get => _products;
 set
  {
    SetProperty(ref _products,value);
    this.UpdateProductsCollection(value);
   }
}
```
define UpdateProductsCollection to keep the realmcollection and proxy collection in synch

```
private void UpdateProductsCollection(IRealmCollection<Product> value)
{
   this.ProdColl = new Coll<Product>(value);
}
```
and the bound collection to your 3rd party ListView
```
private Coll<Product> _productColl;
public Coll<Product> ProductColl
 {
      get => _productColl;
      set => SetProperty(ref _productColl, value);
}
```

in the XAML side, in my case I use Telerik listView, you can use what you want (Synchfuion,...)

```
...
<tdc:RadListView ItemsSource="{Binding ProductColl}"  ...>
	<tdc:RadListView.ItemTemplate>
		<DataTemplate>
			<tlv:ListViewTemplateCell>
				<tlv:ListViewTemplateCell.View>
					<Grid Padding="10">
						<Label Text="{Binding Name}"/>
					</Grid>
				</tlv:ListViewTemplateCell.View>
			</tlv:ListViewTemplateCell>
		</DataTemplate>
	</tdc:RadListView.ItemTemplate>
</tdc:RadListView>
...
```
**following this steps you can delete an item from a list without throwing NRE and with correct refresh**
this can help someone to overcome the NRE issue, 
best regards
