### ISSUE TITLE
Realm Linking Framework Error

### ISSUE THREAD

**Issue by joaowd** [realm/realm-dotnet#1766]
## Goals

Trying to Link "Framework SDK Only"

## Expected Results

Link the frameworks

## Actual Results

<img width="717" alt="screen shot 2018-08-29 at 18 12 07" src="https://user-images.githubusercontent.com/10066011/44803689-15542100-abb7-11e8-9659-20cebb364c7f.png">

[Full Console Log](https://gist.github.com/joaowd/9eeb868c110696f2e06958daa44c432f)

## Steps to Reproduce

1 - Project Options > Linker behaviour > Link Framework SDKs Only
2 - Build the project

## Version of Realm and Tooling

- Flavor:
  - [x] Developer
  - [x] Professional
  - [ ] Enterprise

- Client SDK Version: 3.1.0.0
- Project: Xamarin.iOS
- Client OS & Version: Visual Studio for Mac 7.6.1

**Comment by nirinchev** [comment]
Why do you think this is caused by Realm? It looks like the linker is complaining about GLKView which I've never heard of, so it's unlikely to be referenced by Realm.

**Comment by joaowd** [comment]
Hello Nikola, thanks for the fast reply.

Well in the 3rd error message has a reference of Realm.3.1.0, and since this started happening when I updated realm I thought it was a realm problem.

**Comment by nirinchev** [comment]
It's somewhat misleading, but the 3rd message simply lists the flags with which the linker was run - it's not indicative of an error.

**Comment by nirinchev** [comment]
Does the error go away if you simply downgrade Realm without changing anything else?

**Comment by joaowd** [comment]
Didn't try to downgrade, will check that. Thanks.

**Comment by joaowd** [comment]
Alright, actually it was another framework giving me problems, thanks Nikola!
