### ISSUE TITLE
System.PlatformNotSupportedException

### ISSUE THREAD

**Issue by ghost1372** [realm/realm-dotnet#1770]
hi i cant use realm, i create wpf new project then install 

> Install-Package Realm -Version 3.2.0

after initialize
` var rel = Realm.GetInstance();`
i get this error:

> System.PlatformNotSupportedException: 'The PCL build of Realm is being linked which probably means you need to use NuGet or otherwise link a platform-specific Realm.dll to your main application

i tested it on netframwork 4.5 , 4.6, 4.6.2 but get error

## Version of Realm and Tooling

Visual Studio 2017 Enterprise
Windows 10 Pro RedStone 4
Realm 3.2.0

**Comment by nirinchev** [comment]
As the exception message says, you must add the Realm package to your executable application.

**Comment by ghost1372** [comment]
how? i install Realm from Nuget with 

> Install-Package Realm -Version 3.2.0

 command
where is wrong?

**Comment by nirinchev** [comment]
You can't - Realm is a .NET Standard 1.4 library, so the minimum supported .NET Framework version is 4.6.1.

**Comment by ghost1372** [comment]
if i compile raelm is it possible? (removing .Net Standard)

**Comment by nirinchev** [comment]
Yes, you should be able to compile the .NET project from source targeting .NET 4.5.0 and include the already precompiled native binaries that are part of the public nuget. These aren't tied to the .NET version. Keep in mind that regardless of the .NET version, we still have a hard requirement for Windows 8.1 or higher.
