### ISSUE TITLE
While un install app realm Db not going  to clear

### ISSUE THREAD

**Issue by jitendrajadav** [realm/realm-dotnet#1771]
I am having application with Xamarin forms once I am login app I am storing some data for e.g. SessionId and so on.

once I am un installing my application and trying to launch fresh app it will get old session id from realm Db I don't know why it is taking those data?

1.My question is it removing all the realm Db once app is uninstall? 

2.If not is there any way where I can remove all the realm Db while Un install app?

**Comment by fealebenpae** [comment]
Please fill out the issue template and tell us how to reproduce this, and most importantly - on what platform.

**Comment by jitendrajadav** [comment]
it is on both platform android and iOS

**Comment by Mohsens22** [comment]
It's really wired. 
As I know Realm saves Db in a appdata storage; so after uninstall everything must be removed.

I develop UWP with realm and no user reported that issue so far. 
Could you please tell us more about your issue? So we can help you out.

**Comment by bmunkholm** [comment]
Closing - No response.
