### ISSUE TITLE
Better subscription management

### ISSUE THREAD

**Issue by bmunkholm** [realm/realm-dotnet#1812]
See Cocoa (https://realm.io/docs/swift/3.13.1/api/Classes/Realm.html#/s:10RealmSwift0A0C13subscriptionsAA7ResultsCyAA16SyncSubscriptionCyAA6ObjectCGGyF) and JS (https://realm.io/docs/javascript/latest/api/Realm.html#subscriptions) for reference.

**Comment by roberhofer** [comment]
@fealebenpae : Can you confirm whether .NET has the ability to easily retrieve, list, and search existing subscriptions? Alexander and myself were not really sure whether this already has been done in .NET.

**Comment by fealebenpae** [comment]
That hasn't been implemented yet AFAIK.

**Comment by roberhofer** [comment]
ok, thanks. Then will leave this in an upcoming Sprint to complete and catch up w. Cocoa and JS.
