### ISSUE TITLE
Xamarin.Android ListViewAdapter GetItemId(int position) causes Realms.Exceptions.RealmInvalidObjectException: Attempted to access detached row was thrown.

### ISSUE THREAD

**Issue by DakotaHoch** [realm/realm-dotnet#1816]
## Goals

GetItemId(int position) should return an object's ID from the ListViewAdapter's collection of RealmObjects (IList<EquipmentList>).

## Expected Results

The IList should be indexed with the position, and the indexed object's primary key should be returned.

## Actual Results

Realms.Exceptions.RealmInvalidObjectException: Attempted to access detached row was thrown.

## Steps to Reproduce

-Create Xamarin.Android project, create a custom ListViewAdapter, inheriting from BaseAdapter. ----Create custom RealmObject.
-Create item collection of IList<CustomRealmObject>
-Override GetItemId(int position) method in ListViewAdapter.
-Implement ListView in Activity.
-Tap on ListViewItem.

## Code Sample

```
internal sealed class EquipmentListViewAdapter : BaseAdapter<EquipmentList>
{
        private readonly LayoutInflater _inflater;
        private List<EquipmentList> _items;

        public EquipmentListViewAdapter(Context context)
        {
            _inflater = LayoutInflater.From(context);
            _items = null;
        }

        public override long GetItemId(int position)
        {
            return _count > 0 ? _items[position].PK : -1;
        }

        public override EquipmentList this[int position] => _count > 0 ? _items[position] : null;
}
```
```
public sealed class ActivityIssuance : AppCompatActivity
{
       private RealmDatabase _db = new RealmDatabase();
       private EquipmentListViewAdapter _equipmentAdapter;

       protected override void OnCreate(Bundle savedInstanceState)
       {
              _equipmentAdapter = new EquipmentListViewAdapter(this);
       }

       private void GetItems
       {
             _equipmentAdapter.Items = _db.Connection.All<EquipmentList>().Where(e => e.Visible == 
                  1).ToList();
       } 
}
```

## Version of Realm and Tooling
Realm.Database 3.3.0

**Comment by fealebenpae** [comment]
Have you tried calling `AsRealmCollection()` instead of `ToList()` on the query? `IRealmCollection<T>` is an interface that implements `IReadOnlyList<T>` and is random-access enabled. The issue with calling `ToList()` is that it copies the query in a new collection that is not updated when objects that match the query are added or removed from the database.

**Comment by nirinchev** [comment]
Closing due to lack of response.
