### ISSUE TITLE
Feature request: multiple ID search

### ISSUE THREAD

**Issue by ukushu** [realm/realm-dotnet#1823]
## Goals
Search RealmObjects by multiple ID's

As I see realm is not support search by ID list.
Doing search for each separate ID is not a good enough workaround.

Java have the following workaround: 
`realm.where(Foo.class).in("id", ids).findAll();`

but C# does not have similar.
I have tried few things but still have no any good idea for this.

So my questions is the following:

1. Will it be supported in future? Near or far
2. Do c# realm have good enough workaround for the task?

## Version of Realm and Tooling
c# .Net realm 3.3.0

**Comment by ukushu** [comment]
I have found workaround. I wrote it here:
https://stackoverflow.com/questions/54009005/query-realm-for-objects-by-ids-collection/54038857#54038857

but question 1 is still actual:
1. Will it be supported in future? Near or far

**Comment by nirinchev** [comment]
Sorry for the late response - the workaround you posted is a bit complicated. You could achieve the same result by generating a string query and using the `.Filter` extension method. Something like (not tested):

```
var query = string.join(" OR ", idsToMatch.Select(i => $"UserKey == {i}"));
realm.All<MyObject>().Filter(query);
```

We intend to support it in the future, but not in the near term.

**Comment by ukushu** [comment]
Example of working code that will work more optimal than code in your answer (just for someone who will be interested in the question) :

    public static class MyQueryableExtensions
    {
        public static IQueryable<T> In<T, TProp>(this IQueryable<T> source,
            Expression<Func<T, TProp>> propSelector, IEnumerable<TProp> values)
        {
            var @params = propSelector.Parameters;
            var propAcc = propSelector.Body;
            Expression body = Expression.Constant(false, typeof(bool));
            foreach (var v in values)
                body = Expression.OrElse(body,
                    Expression.Equal(propAcc,
                        Expression.Constant(v, typeof(TProp))));
            var lambda = Expression.Lambda<Func<T, bool>>(body, @params);
            return source.Where(lambda);
        }
    }

Example of usage:

    _db.Realm.All<Quest>().In( (a)=>a.Id, idsList );

**Comment by nirinchev** [comment]
Your code is optimized for type safety, the example I gave is going to be slightly faster, although I expect it'll only be noticeable if the `idsList` is quite large.

**Comment by ukushu** [comment]
Your solution must be slower, because of: 
1. no need any resources for string parsing to expression tree. 
2. and as you said: type safety. And also this mean that there will be no extra packing/unpacking processes and will be no useless comparation of strings with ints [and similar]

but ofc speed difference on your and my solutions will be close to zero with small `idsList` :)

In any case, thanks for your time. 
It's always useful to read your opinion

**Comment by nirinchev** [comment]
The string query is parsed by the native module so no .NET query trees are constructed for it. On the other hand, the LINQ query needs to be translated into a native query which will happen by splitting it at logical operators (the ORs) and calling into native to build the query. Since the managed-to-native transition is the most costly operation when building the query and we have to repeat it for every element of the collection, this will most likely trump the time it takes our native module to parse the string query.

Not posting this to argue or anything, just thought it'd be interesting for you (and others who might stumble into this issue) how the query engine works in the .NET SDK 🤓
