### ISSUE TITLE
Dynamical change of IList properties by property name is not possible

### ISSUE THREAD

**Issue by ukushu** [realm/realm-dotnet#1825]
## Goals

I'm trying to get any `<IList>` property via it's name for change it due to runtime:

	public class Quest : RealmObject
	{
	    public IList<bool> Days { get; }
	}

I have a methods:

    private object GetPropertyValue(object obj, string propName)
    {
        return obj.GetType().GetProperty(propName)?.GetValue(obj, null);
    }

    private void FillIList(IList iLst, IEnumerable source)
    {
        iLst.Clear();
        foreach (var a in source)
        {
            iLst.Add(a);
        }
    }

I'm trying to call:

    var origObjListRef = GetPropertyValue(_questInstance, "Days");

## Expected Results

Expected behavior that method returns object that represents `IList` or object that can be converted into `IList` 

## Actual Results

This method returns `RealmList<SomeType>`; No ability to convert it to `IList` 

Also RealmList is not generic class. So I cannot write universal method `FillIList()`

## Question:
How can I get original `IList` Days of class `Quest` dynamically by it's name?  

Or how can I cast `RealmList` to `IList`?

Why it's return `RealmList`? And why RealmList is not represent `IList`.

Casting or `Convert.ChangeType()` doesn't work at all.

## Version of Realm and Tooling
Realm 3.3.0

**Comment by nirinchev** [comment]
`RealmList<T>` implements `IList<T>`, it doesn't implement the non-generic `IList` interface. In your model class, you define your property as `IList<bool>` - you can always cast `origObjListRef` to `IList<bool>` but you can not cast it to `IList`.

**Comment by nirinchev** [comment]
It is possible, but it's likely to be prone to runtime errors. You can change your argument type to `object` and then use reflection to look up the `Add` method and invoke it with your object. This will obviously result in a runtime exception if you pass in an incorrect type, which is why ideally you would use generics. Something like:

```csharp
private void FillIList<T>(IList<T> iLst, IEnumerable<T> source)
{
    iLst.Clear();
    foreach (var a in source)
    {
        iLst.Add(a);
    }
}
```

If that's not possible, then you'll need to rely on reflection.

**Comment by ukushu** [comment]
nirinchev , you're rock!

	public void FillIList<T1>(IList<T1> iLst, IEnumerable<T1> source)
	{
		iLst.Clear();

		foreach (var a in source)
		{
			iLst.Add(a);
		}
	}


and:

	Type origType = ///;

	var origObjListRef = GetPropertyValue(_origItem, propertyName); //Realm obj item with propertyName
	var currObjListRef = (IEnumerable) GetPropertyValue(this, propertyName); // SomeClass obj item with propertyName

	MethodInfo method = this.GetType().GetMethod("FillIList").MakeGenericMethod(origType);
	method.Invoke(this, new[] { origObjListRef, currObjListRef }); // call method to copy all items from propertyName of SomeObj to propertyName of RealmObj
