### ISSUE TITLE
Realm migration rename field crash for .Net

### ISSUE THREAD

**Issue by rravimr** [realm/realm-dotnet#1830]
## Goals

 I have changed the field name Like (Id to DoctorId) and How can I perform migrate for this rename

## Expected Results

To change the field name and assign the old values from exsiting data

## Actual Results

Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: ''Realms.Dynamic.DynamicRealmObject' does not contain a definition for 'Id''

## Steps to Reproduce

1. Create relam class and insert some values ( SaleDoctor ==> Id, Name)
2. Changed the Id as DoctorId
3. Perform migration using call back

## Code Sample

this.SyncEngine.RealmConfigurationBase.SchemaVersion = currentVersion;
                this.SyncEngine.RealmConfigurationBase.MigrationCallback = (migration, oldSchemaVersion) =>
                {                 
                    if (oldSchemaVersion == 2)
                    {
                        var newPeople = migration.NewRealm.All<SaleDoctor>();
                        var oldPeople = migration.OldRealm.All("SaleDoctor");

                        for (var i = 0; i < newPeople.Count(); i++)
                        {
                            var oldPerson = oldPeople.ElementAt(i);
                            var newPerson = newPeople.ElementAt(i);

                            newPerson.DoctorId = oldPerson.Id;
                        }
                    }
                };

## Version of Realm and Tooling

Relam Database - .Net Latest

**Comment by Guiorgy** [comment]
try
`var newPeople = migration.NewRealm.All<SaleDoctor>();`
or whatever your Class is called

**Comment by fealebenpae** [comment]
Do you use any `MapTo` attributes in your schema?

**Comment by Guiorgy** [comment]
No, but I also haven't renamed things yet. Only added more.
heres what they did in the documentation:
```cs
var newPeople = migration.NewRealm.All<Person>();
var oldPeople = migration.OldRealm.All("Person");
```
so... yeah.

**Comment by fealebenpae** [comment]
I'm sorry @Guiorgy, I meant to ask @rravimr.

**Comment by Guiorgy** [comment]
@fealebenpae, ¯\_(ツ)_/¯ oops. Didn't look.
@rravimr, `var newPeople = migration.NewRealm.All();` just as I mentioned, here you either need to pass a generic type (`<SaleDoctor>`), or pass the string you mapped to. Have you tried that?

**Comment by rravimr** [comment]
@Guiorgy @fealebenpae  . Thanks for your response
The issue was resolved after the use of MapTo variables.
