### ISSUE TITLE
Fody 4.0.0

### ISSUE THREAD

**Issue by Guiorgy** [realm/realm-dotnet#1831]
## Goals

Build using Fody 4.0.0

## Expected Results

Normal build.

## Actual Results

Fody had a breaking update. Realm should be updated to follow it's new rules:
`Fody: No weavers found for the configuration entries RealmWeaver. Add the desired weavers via their nuget package; see https://github.com/Fody/Fody/wiki on how to migrate InSolution, custom or legacy weavers.`
In other words, RealmWeavers has to be added to the solution via NuGet.

## Steps to Reproduce

Use Fody 4.0.0 or above

**Comment by Guiorgy** [comment]
#1820 was already reported

**Comment by mark4asp** [comment]
Closed, but not resolved?

1. My ViewModel (class library) project has packages: Fody 4.0.2, ReactiveUI, ReactiveUI.Fody, ReactiveUI.Winforms (all 9.10.1) added. I get this error:

"No weavers found for the configuration entries ReactiveUI. Add the desired weavers via their nuget package; see https://github.com/Fody/Fody/wiki on how to migrate InSolution, custom or legacy weavers."

My FodyWeavers.xml file is:

<?xml version="1.0" encoding="utf-8"?>
<Weavers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FodyWeavers.xsd">
  <ReactiveUI />
</Weavers>

2. Why is the error message giving a hyperlink to https://github.com/Fody/Fody/wiki, when it is no longer there?

What is the resolution of issue 1? (No weavers ... blah)

**Comment by nirinchev** [comment]
Not sure how the error you're getting is related to Realm? You don't appear to be using it.

**Comment by mark4asp** [comment]
The solution to this issue (to get the project to build) was to remove the "FodyWeavers.xml" from offending project, then build it.

**Comment by Guiorgy** [comment]
@nirinchev, as stated, scince a while ago, Fody deprecated FodyWeavers.xml configuration. But from 4.0.x, it was completely removed. Now, Realm needs to provide the Weaver as a nuget package, if I am not mistaken.

**Comment by nirinchev** [comment]
@Guiorgy I was replying to @mark4asp's last comment. The issue that you opened is correctly marked as duplicate and progress is tracked in #1820. We're working on it and expect to provide an update in the near future.
