### ISSUE TITLE
Compile errors while building realm sample in visual studio

### ISSUE THREAD

**Issue by vamsivaliveru** [realm/realm-dotnet#1832]
## Version of Realm and Tooling

- Realm Object Server Version: ? (you can see this as well in Studio once connected to a Realm instance) 
- Flavor:
  - [ ] Realm Cloud
  - [ ] Self-Hosted
- Server OS & Version: ? (e.g. CentOS 6)
- Client SDK Version: ?
- Client OS & Version: ?

**Comment by vamsivaliveru** [comment]
Error list

clang : error : linker command failed with exit code 1 (use -v to see invocation)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '__ZN5realm5_impl21PrimitiveListNotifier12do_attach_toERNS_11SharedGroupE'.
MTOUCH : error MT5213: Duplicate symbol in: /Samples/SignPad/packages/Realm.3.3.0/native/ios/universal/librealm-wrappers.a(primitive_list_notifier.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '__ZN5realm5_impl21PrimitiveListNotifier12release_dataEv'.
MTOUCH : error MT5213: Duplicate symbol in: /Samples/SignPad/packages/Realm.3.3.0/native/ios/universal/librealm-wrappers.a(primitive_list_notifier.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '__ZN5realm5_impl21PrimitiveListNotifier14do_detach_fromERNS_11SharedGroupE'.
MTOUCH : error MT5213: Duplicate symbol in: /Samples/SignPad/packages/Realm.3.3.0/native/ios/universal/librealm-wrappers.a(primitive_list_notifier.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '__ZN5realm5_impl21PrimitiveListNotifier19do_prepare_handoverERNS_11SharedGroupE'.
MTOUCH : error MT5213: Duplicate symbol in: /Samples/SignPad/packages/Realm.3.3.0/native/ios/universal/librealm-wrappers.a(primitive_list_notifier.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '__ZN5realm5_impl21PrimitiveListNotifier27do_add_required_change_infoERNS0_21TransactionChangeInfoE'.
MTOUCH : error MT5213: Duplicate symbol in: /Samples/SignPad/packages/Realm.3.3.0/native/ios/universal/librealm-wrappers.a(primitive_list_notifier.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '__ZN5realm5_impl21PrimitiveListNotifier3runEv'.
MTOUCH : error MT5213: Duplicate symbol in: /Samples/SignPad/packages/Realm.3.3.0/native/ios/universal/librealm-wrappers.a(primitive_list_notifier.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '__ZN5realm5_impl21PrimitiveListNotifierC1ENS_13BasicTableRefINS_5TableEEENSt3__110shared_ptrINS_5RealmEEE'.
MTOUCH : error MT5213: Duplicate symbol in: /Samples/SignPad/packages/Realm.3.3.0/native/ios/universal/librealm-wrappers.a(primitive_list_notifier.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '__ZN5realm5_impl21PrimitiveListNotifierC2ENS_13BasicTableRefINS_5TableEEENSt3__110shared_ptrINS_5RealmEEE'.
MTOUCH : error MT5213: Duplicate symbol in: /Samples/SignPad/packages/Realm.3.3.0/native/ios/universal/librealm-wrappers.a(primitive_list_notifier.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '__ZTIN5realm5_impl21PrimitiveListNotifierE'.
MTOUCH : error MT5213: Duplicate symbol in: /Samples/SignPad/packages/Realm.3.3.0/native/ios/universal/librealm-wrappers.a(primitive_list_notifier.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '__ZTSN5realm5_impl21PrimitiveListNotifierE'.
MTOUCH : error MT5213: Duplicate symbol in: /Samples/SignPad/packages/Realm.3.3.0/native/ios/universal/librealm-wrappers.a(primitive_list_notifier.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '__ZTVN5realm5_impl21PrimitiveListNotifierE'.
MTOUCH : error MT5213: Duplicate symbol in: /Samples/SignPad/packages/Realm.3.3.0/native/ios/universal/librealm-wrappers.a(primitive_list_notifier.o) (Location related to previous error)
error MT5209 : Native linking error : 11 duplicate symbols for architecture arm64
MTOUCH : error MT5201: Native linking failed. Please review the build log and the user flags provided to gcc: -L/Samples/SignPad/packages/Realm.3.3.0/build/../native/ios/universal -lrealm-wrappers -lz -framework Security
MTOUCH : error MT5202: Native linking failed. Please review the build log.

**Comment by Guiorgy** [comment]
What Fody version are you using?
