### ISSUE TITLE
Native linking failed MTOUCH ERROR 

### ISSUE THREAD

**Issue by vamsivaliveru** [realm/realm-dotnet#1833]
## Goals

Build for iPhone **device** in Debug mode.

## Expected Results

Build successful

## Actual Results

clang : error : linker command failed with exit code 1 (use -v to see invocation)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '__ZN5realm5_impl21PrimitiveListNotifier12do_attach_toERNS_11SharedGroupE'.
MTOUCH : error MT5213: Duplicate symbol in: /Samples/SignPad/packages/Realm.3.3.0/native/ios/universal/librealm-wrappers.a(primitive_list_notifier.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '__ZN5realm5_impl21PrimitiveListNotifier12release_dataEv'.
MTOUCH : error MT5213: Duplicate symbol in: /Samples/SignPad/packages/Realm.3.3.0/native/ios/universal/librealm-wrappers.a(primitive_list_notifier.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '__ZN5realm5_impl21PrimitiveListNotifier14do_detach_fromERNS_11SharedGroupE'.
MTOUCH : error MT5213: Duplicate symbol in: /Samples/SignPad/packages/Realm.3.3.0/native/ios/universal/librealm-wrappers.a(primitive_list_notifier.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '__ZN5realm5_impl21PrimitiveListNotifier19do_prepare_handoverERNS_11SharedGroupE'.
MTOUCH : error MT5213: Duplicate symbol in: /Samples/SignPad/packages/Realm.3.3.0/native/ios/universal/librealm-wrappers.a(primitive_list_notifier.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '__ZN5realm5_impl21PrimitiveListNotifier27do_add_required_change_infoERNS0_21TransactionChangeInfoE'.
MTOUCH : error MT5213: Duplicate symbol in: /Samples/SignPad/packages/Realm.3.3.0/native/ios/universal/librealm-wrappers.a(primitive_list_notifier.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '__ZN5realm5_impl21PrimitiveListNotifier3runEv'.
MTOUCH : error MT5213: Duplicate symbol in: /Samples/SignPad/packages/Realm.3.3.0/native/ios/universal/librealm-wrappers.a(primitive_list_notifier.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '__ZN5realm5_impl21PrimitiveListNotifierC1ENS_13BasicTableRefINS_5TableEEENSt3__110shared_ptrINS_5RealmEEE'.
MTOUCH : error MT5213: Duplicate symbol in: /Samples/SignPad/packages/Realm.3.3.0/native/ios/universal/librealm-wrappers.a(primitive_list_notifier.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '__ZN5realm5_impl21PrimitiveListNotifierC2ENS_13BasicTableRefINS_5TableEEENSt3__110shared_ptrINS_5RealmEEE'.
MTOUCH : error MT5213: Duplicate symbol in: /Samples/SignPad/packages/Realm.3.3.0/native/ios/universal/librealm-wrappers.a(primitive_list_notifier.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '__ZTIN5realm5_impl21PrimitiveListNotifierE'.
MTOUCH : error MT5213: Duplicate symbol in: /Samples/SignPad/packages/Realm.3.3.0/native/ios/universal/librealm-wrappers.a(primitive_list_notifier.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '__ZTSN5realm5_impl21PrimitiveListNotifierE'.
MTOUCH : error MT5213: Duplicate symbol in: /Samples/SignPad/packages/Realm.3.3.0/native/ios/universal/librealm-wrappers.a(primitive_list_notifier.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '__ZTVN5realm5_impl21PrimitiveListNotifierE'.
MTOUCH : error MT5213: Duplicate symbol in: /Samples/SignPad/packages/Realm.3.3.0/native/ios/universal/librealm-wrappers.a(primitive_list_notifier.o) (Location related to previous error)
error MT5209 : Native linking error : 11 duplicate symbols for architecture arm64
MTOUCH : error MT5201: Native linking failed. Please review the build log and the user flags provided to gcc: -L/Samples/SignPad/packages/Realm.3.3.0/build/../native/ios/universal -lrealm-wrappers -lz -framework Security
MTOUCH : error MT5202: Native linking failed. Please review the build log.

## Steps to Reproduce

Build in debug mode for a device, not simulator. I have added a native dll created from objective sharpie. The file is attached here for reference
[FCBindingLibrary.dll.zip](https://github.com/realm/realm-dotnet/files/2855692/FCBindingLibrary.dll.zip)

## Code Sample

using System;
using System.Linq;
using System.Threading.Tasks;
using CoreGraphics;
using CoreImage;
using Foundation;
using FreshchatSDK;
using Photos;
using Realms;
using Realms.Sync;
using SignPad.Model;
using UIKit;
using Xamarin.Controls;

namespace SignPad
{
    public partial class ViewController : UIViewController
    {      

        private Realm realm;

        protected ViewController(IntPtr handle) : base(handle)
        {
            // Note: this .ctor should not contain any initialization logic.
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            // Perform any additional setup after loading the view, typically from a nib.
           
            btnaddcar.TouchUpInside += (object sender, EventArgs e) =>
            {
                addNewCar();
            };

            btnShowFAQ.TouchUpInside += (object sender, EventArgs e) =>
            {
                Freshchat.SharedInstance().ShowFAQs(this);
            };           

        }

        private void addNewCar()
        {
            try
            {
                //var config = new RealmConfiguration("mydatabase.realm");
                //var realm = Realm.GetInstance(config);

                realm = Realm.GetInstance(DAL_DBAccessVariable.config);

                //realm = Realm.GetInstance();

                string carBrand = txtcarbrand.Text;
                string carModel = txtcarmodel.Text;

                // Update and persist objects with a thread-safe transaction
                realm.Write(() =>
                {
                    realm.Add(new Car { Brand = carBrand, Model = carModel });
                });

                var cars = realm.All<Car>();

                // Use LINQ to query
                //var puppies = realm.All<Dog>().Where(d => d.Age < 2);

                lblResult.Text = "Count cars: " + cars.Count();
                txtcarmodel.ResignFirstResponder();

                //var cars= realm.All<Car>().Where(dBrand.Equals("BMW"));

                //var cars = from cars in realm.All<Car where cars.Brand.Equals("BMWlect cars;

            }
            catch (Realms.Exceptions.RealmException e)
            { }
        }

        public override void DidReceiveMemoryWarning()
        {
            base.DidReceiveMemoryWarning();
            // Release any cached data, images, etc that aren't in use.
        }      
       
    }
}

Class file for configuration:

using System;
using Realms;
using System.IO;

namespace SignPad
{
    public class DAL_DBAccessVariable
    {
        private const string databaseName = "name.realm";
        public static readonly string dbPath =
            Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Personal), databaseName);
        public static readonly RealmConfiguration config = new RealmConfiguration(dbPath);
    }
}

## Version of Realm and Tooling

* Realm version - latest from Nuget package
* Visual Studio: 7.7.4 (build 1)
* Xcode version : 10.1
[FCBindingLibrary.dll.zip](https://github.com/realm/realm-dotnet/files/2855689/FCBindingLibrary.dll.zip)

**Comment by vamsivaliveru** [comment]
This is my linkwith.cs file for the binding library

using ObjCRuntime;

[assembly: LinkWith("libFDFreshchatSDK.a",
                     LinkTarget.ArmV7 | LinkTarget.ArmV7s | LinkTarget.i386 | LinkTarget.x86_64 | LinkTarget.Arm64
                    ,SmartLink = true, ForceLoad = false                   
                     ,Frameworks ="Foundation AVFoundation AudioToolbox CoreMedia CoreData ImageIO Photos SystemConfiguration Security CoreGraphics"
                     ,LinkerFlags = "-all_load -ObjC"
                    )]

**Comment by fealebenpae** [comment]
Does it work without the Freshchat binding library? If so, I recommend changing your linkswith to set `ForceLoad = true` and remove the `-all_load` linker flag.

**Comment by vamsivaliveru** [comment]
The sample works without the binding library. 

Now, I have commented the linker flags in the link with file and in the actual iOS project the build is successful now. But I see an error in the app delegate.cs finishedlaunching method. The error is "Exception of type 'Foundation.You_Should_Not_Call_base_In_This_Method' was thrown"

**Comment by fealebenpae** [comment]
I think this might be related to your binding library. My suggestion is to make sure it works in an empty project without other libraries first so you can isolate any issues.

**Comment by vamsivaliveru** [comment]
I have made it to work now. But the app crash if we do some operation using our binding library. Initially, we had similar issue and we eliminated by adding '-gcc_flags "-all_load -ObjC"' in the mtouch arguments in the visual studio. If I add it now, I am seeing the same errors shared above

**Comment by fealebenpae** [comment]
`-all_load` affects all static libraries in the linking, which is why you're seeing problems with the realm-wrappers static library. `-force_load path/to/library` should have the same effect, but only for that specific library. The `ForceLoad` parameter of the `LinkWith` attribute is supposed to enable just that.

**Comment by vamsivaliveru** [comment]
I have used the binding library to create a dll which I have used in the iOS project. Can you tell me the code / command to be used for mtouch arguments to eliminate this one ? I have used .a file to create the dll.

**Comment by fealebenpae** [comment]
Like I said above, I think it should work by setting `ForceLoad = true`. I'm afraid I don't have other ideas and you might be better off asking on StackOverflow. I can only provide help for Realm-specific issues.

**Comment by vamsivaliveru** [comment]
Yes. The solution compiles successfully after commenting the line "LinkerFlags = "-all_load -ObjC"" and making force load = true in the linkwith.cs file. After this, the iOS project compiles successfully but the app crashes after doing some operations. 

Earlier, this happened, and we put the line '-gcc_flags "-all_load -ObjC"' in the mtouch which caused the app to work smoothly.

**Comment by vamsivaliveru** [comment]
By adding the line '-gcc_flags "-L${ProjectDir} -lFDFreshchatSDK -force_load ${ProjectDir}/libFDFreshchatSDK.a", I am able to compile the code successfully'

**Comment by fealebenpae** [comment]
Try setting `SmartLink = false` - [according to the docs](
https://docs.microsoft.com/en-us/dotnet/api/objcruntime.linkwithattribute.smartlink#ObjCRuntime_LinkWithAttribute_SmartLink) this might cause `ForceLoad = true` to be ignored.

**Comment by vamsivaliveru** [comment]
We were able to fix this from adding the touch arguments mentioned by me. Thanks for the help
