### ISSUE TITLE
Selected backlink closures for subscriptions

### ISSUE THREAD

**Issue by kneth** [realm/realm-dotnet#1834]
See Epic: [realm/engineering#13](https://github.com/realm/engineering/issues/13)
Helps unblock a adapter performance issue.

**Comment by Guiorgy** [comment]
@kneth, link is dead BTW

**Comment by nirinchev** [comment]
It's a link to a private repo, but essentially, the proposal is to enable specifying which backlinks should be included when subscribing to results in query based Realms (currently, backlinks are ignored and only forward links are processed).
