### ISSUE TITLE
AspnetCore Add Permissions

### ISSUE THREAD

**Issue by keodime** [realm/realm-dotnet#1836]
## Goals
Trying to add permissions and to add that permission on object level.
## Expected Results
Object is created with the permission
The permission is created and link to a role
The role has the list of user
The user exist.

## Actual Results
Throw Object Reference null exception
## Step to Reproduce
Permission.Get(role, realm)
Permission.Get(role.Name, realm)
...
always throw error : object reference ... null reference.

Config : Fullsync
Credential: Custom Jwt as an admin of the ROS.
I drilled down a bit and of course it can't work in fullSync.

Behind the scene it calls RealmPermission.Get(realm).Permissions.
The problem is RealmPermission.Get(realm) always return null with FullSyncConfiguration.

## Code Sample

```
PermissionUser user = PermissionUser.Get(realm, userId); // Get Or Create User 
PermissionRole role = PermissionRole.Get(realm, siteId);    // Get Or Create Role

if (!role.Users.Contains(user))
{
    role.Users.Add(user);
}

//From here Everything work and if you commit those change, it creates a role with the user link to it.

Permission permission = Permission.Get(role, realm); //That is crashing

```
## Half work around
The reason why we set the optionalPath Parameter on instance is web app in azure doesnt have access in read/write everywhere, so we have to tell the instance where to write.
GetInstance in QueryBasedSync

Since there's already a user connected to the same realm in fullSync, for my querybaseConfig OptionalPath is compose of a predefined string and a randomGuid, so it does not interfere with an other open instance of fullSync for the same User. 
```
await Realm.GetInstanceAsync(new QueryBasedSyncConfiguration(_realmUri, _user, $"{_optionalPath}{Guid.NewGuid()}"){
     ObjectClasses = new[]
     {
         typeof(RealmSite)
     }
 });
```
```
Permission permission = null;

await queryBasedClient.WriteAsync(realm =>
{
       PermissionUser user = PermissionUser.Get(realm, userId);
       PermissionRole role = PermissionRole.Get(realm, siteId);

        if (!role.Users.Contains(user))
        {
              role.Users.Add(user);
        }

        permission = Permission.Get(role, realm);
        permission.SetReadonlyPermission();
});
```
Then GetInstance in fullSync, because I cant seems to find my object in QueryBasedSync.
```
await Realm.GetInstanceAsync(new FullSyncConfiguration(_realmUri, _user, $"{_optionalPath}{_user.Identity}")
{
    ObjectClasses = new[]
    {
        typeof(RealmPermission),
        typeof(PermissionUser),
        typeof(PermissionRole),
        typeof(ClassPermission),
        typeof(Permission),
        typeof(RealmSite)
    }
});

```

```
await fullSyncClient.WriteAsync(realm =>
{
    RealmSite site = realm.Find<RealmSite>(siteId);

    site.Permissions.Add(permission);

    realm.Add(site, true);
});
```
RealmSite Object

```
internal class RealmSite : RealmObject
{
    [MapTo("permissions")]
    public IList<Permission> Permissions { get; }

    [PrimaryKey]
    [Required]
    [MapTo("id")]
    public string PrimaryKey { get; set; }
}
```
Then the RealmSite object doesnt have the permission.

## Version of Realm and Tooling

- Realm Object Server Version: ? (you can see this as well in Studio once connected to a Realm instance) 
- Flavor:
  - [ ] Realm Cloud
  - [x] Self-Hosted
- Client SDK Version: nugget 3.4.0
- Framework: Aspnet Core 2

**Comment by fealebenpae** [comment]
Hi @keodime,

Object-level permissions aren't supported in full sync mode, only the legacy path-level permissions are. We should improve the exception you get to be more meaningful instead of just a NRE.

In this case you should always use query-based sync. When you open a query-based sync realm you also need to [create a subscription with a query that matches a subset of the data you wish to load in the partial realm](https://docs.realm.io/sync/using-synced-realms/syncing-data#query-based-synchronization) in order for the realm to contain any data at all.

**Comment by keodime** [comment]
Thank you, it did work.

For further people trying to add permissions in dotnet here's a code sample working.

Subscription<RealmSite> subscription = queryBasedClient.All<RealmSite>().Where(x => x.PrimaryKey == siteId).Subscribe()

```
await queryBasedClient.WriteAsync(realm =>
{
    PermissionUser user = PermissionUser.Get(realm, userId);
    PermissionRole role = PermissionRole.Get(realm, siteId);

    if (!role.Users.Contains(user))
    {
        role.Users.Add(user);
    }

    Permission permission = Permission.Get(role, realm);
    permission.SetReadonlyPermission();

    RealmSite site = subscription.Results.Single();

    site.Permissions.Add(permission);

    realm.Add(site, true);
});
```
