### ISSUE TITLE
Can't authenticate using cached anonymous user

### ISSUE THREAD

**Issue by pfedotovsky** [realm/realm-dotnet#1843]
## Goals
Login using cached anonymous user.
I create an anonymous user when the app starts the first time and then use the cached user for subsequent requests. 

## Expected Results
Login succeded.

## Actual Results
Exception

> {Realms.Sync.Exceptions.SessionException: An error has occurred while refreshing the access token. ---> Realms.Sync.Exceptions.AuthenticationException: The path is invalid or current user has no access.\n  at Realms.Sync.AuthenticationHelper.MakeAuthRequestAsync (System.Net.Http.HttpMethod method, System.Uri uri, System.Collections.Generic.IDictionary`2[TKey,TValue] body, System.String authHeader) [0x002e9] in /Users/realm/workspace/realm_realm-dotnet_PR-1826/Realm/Realm.Sync/Helpers/AuthenticationHelper.cs:301 \n  at Realms.Sync.AuthenticationHelper.RefreshAccessTokenAsync (Realms.Sync.Session session, System.Boolean reportErrors) [0x000b7] in /Users/realm/workspace/realm_realm-dotnet_PR-1826/Realm/Realm.Sync/Helpers/AuthenticationHelper.cs:73 \n   --- End of inner exception stack trace ---}

I see the user in Realm Cloud, state is _Active_.

## Steps to Reproduce

1. Create a new instance in Realm cloud
2. Create a new Realm
3. Login using Credentials.Anonymous();
4. Login using User.Current after some time

## Code Sample
```
var user = User.Current;
var syncConfiguration = new FullSyncConfiguration(RealmUrl, user, GetOnlineRealmPath());
var realm = Realm.GetInstance(syncConfiguration);
```

## Version of Realm and Tooling

- Realm Cloud
- Client SDK Version: Realm 3.4.0
- Client OS & Version: Windows 10 October update

**Comment by nirinchev** [comment]
What is `GetOnlineRealmPath`?

**Comment by pfedotovsky** [comment]
@nirinchev that's the path to the Realm
```
        private static string GetOnlineRealmPath()
        {
            var documentsPath = Environment.GetFolderPath(Environment.SpecialFolder.Personal);
            return Path.Combine(documentsPath, "RealmDB.realm");
        }
```

**Comment by nirinchev** [comment]
Ugh, my bad, I meant to ask about the `RealmUrl` 🤦‍♂️ Essentially, I want to see what URL you're trying to create the Realm at as the stacktrace implies that the user doesn't have access to that path.

**Comment by pfedotovsky** [comment]
@nirinchev the URL is realms://dotnet.de1a.cloud.realm.io/<RealmName>.
It works fine with other users (newly created)

**Comment by nirinchev** [comment]
Okay, just to be clear, non-admin users have access only to their home folder `~/`. It's not clear what `RealmName` is here, but a non-admin user by default can't just create a Realm `/foo` - it needs to be `/~/foo`. If that's not what's happening, I'll need a simple repro app that I can use to try and simulate the issue.

**Comment by pfedotovsky** [comment]
@nirinchev the scenario I use is the following
1. Create Realm in the root directory, i.e. _/dotnet_
2. Connect to this Realm using Credentials.Anonymous()
3. Cache the user, use User.Current for subsequent logins
4. After some time error ocurrs (I guess token is expired)

Can you clarify what's the duration of access token for _Credentials.Anonymous()?_ 
I'll try create repro app, but I need to know how to get to the point where access token has to be refreshed.

**Comment by nirinchev** [comment]
Did you grant permissions to the `/dotnet` Realm? Because by default anonymous users can't connect to these realms.

**Comment by pfedotovsky** [comment]
@nirinchev No, I didn't do anything with permissions. But my anonymous users can connect to the created realm (in the root directory).

If this is not supposed to work, how can I share the Realm? All clients are anonymous and need read-only access.

**Comment by nirinchev** [comment]
You can share it precisely by granting read-only global permissions. But if you never did that, then it's not surprising you get an `AuthenticationException` and any changes that you may make locally would not be synchronized.

**Comment by pfedotovsky** [comment]
@nirinchev I've just created new Realm at the root level, (_/dotnet_) using Realm Studio, haven't set up any permissions. The code below works fine with _Credentials.Anonymous()_

```
var realmUrl = new Uri("realms://dotnet.de1a.cloud.realm.io/dotnet");
User user = await User.LoginAsync(Credentials.Anonymous(), new Uri("https://dotnet.de1a.cloud.realm.io"));

var syncConfiguration = new FullSyncConfiguration(realmUrl, user);

var realm = Realm.GetInstance(syncConfiguration);
```

**Comment by nirinchev** [comment]
What do you mean by "works fine"? Can you write an object to the realm and then see the change in Studio or vice versa?

**Comment by pfedotovsky** [comment]
@nirinchev ok, it seems that it's not working fine :)

Is there a way to see which user trying to access Realm? I see logs in Realm Studio but I don't see any user related information.

**Comment by pfedotovsky** [comment]
@nirinchev it turned out that I used cached admin user and it was working fine. The error occurred when I try to use anonymous users and get access to the root realm. I've added read-only permissions for the root realm for all users and now anonymous users can access the realm.

BTW, I haven't found any documentation about modifying permissions using Realm Studio - I did it via modifying __admin_ realm and adding a new object to the _Permissions_ class.

**Comment by nirinchev** [comment]
Realm Studio doesn't yet offer that functionality, but it's on our roadmap. While writing to the `__admin` Realm does achieve that, we strongly discourage using it directly. Instead, you could have used the [.NET permission API](https://docs.realm.io/sync/using-synced-realms/access-control/path-level-permissions#granting-permissions) to do that. Note that in your case you would have needed to use the admin user (as they own the Realm) to grant permissions to everyone.
