### ISSUE TITLE
Realm.GetInstanceAsync does not return if no permission

### ISSUE THREAD

**Issue by liarsing** [realm/realm-dotnet#1852]
## Goals

get a realm instance by Realm.GetInstanceAsync

## Expected Results

Realm instance returned

## Actual Results

the method does not return or throw any exception

## Steps to Reproduce

1. Create a global realm, say /global by admin
1. modify permission by using User.ApplyPermissionsAsync
1. Attempt to get realm using non-admin user
3a. Realm.GetInstanceAsync returns normally if AccessLevel.Read/Write is applied
3b. Realm.GetInstanceAsync does not return if AccessLevel.None is applied

## Code Sample

//with admin user
var condition = PermissionCondition.UserId("*");
var realmUrl = "https://...us1.cloud.realm.io/global";
await user.ApplyPermissionsAsync(condition, realmUrl, AccessLevel.None);

//with non-admin user
var configuration = new FullSyncConfiguration(new Uri("/global", UriKind.Relative), user);
var globalRealm = await Realm.GetInstanceAsync(configuration);

## Version of Realm and Tooling
Realm Cloud
Win 10
.NET 4.7.2

**Comment by papafe** [comment]
I have tried to reproduce the error with the new API and with RealmSync. Disabling a certain user returns an exception as expected, so I am closing the ticket
