### ISSUE TITLE
API to delete cached users

### ISSUE THREAD

**Issue by pfedotovsky** [realm/realm-dotnet#1856]
## Goals
API method to delete user information cached via `User.Current` & `User.AllLoggenIn` properties.

There's a method `User.Current.LogOutAsync()`, but it throws an exception if a user is invalid (i.e. doesn't exist anymore).

The purpose is to clean up any user information during Xamarin.Forms app upgrade to a newer version.

StackOverflow question: https://stackoverflow.com/questions/55722955/how-to-delete-realm-user-information

**Comment by nirinchev** [comment]
You can iterate over all users obtained by calling `User.AllLoggedIn` and call logout for each of them.

**Comment by pfedotovsky** [comment]
@nirinchev _LogOutAsync_ throws an exception if a user is deleted on the server, but does delete user locally. So I have to use the following code, which doesn't seem good - i.e. how to distinguish exceptions?

```
try
{
  foreach (var user in users)
  {
    await user.LogOutAsync();
  }
}
catch (Exception e)
{
  Crashes.TrackError(e);
}
```

**Comment by nirinchev** [comment]
This will get reworked after we migrate to MongoDB Realm. Until then, we don't plan to change the existing behavior.
