### ISSUE TITLE
Realm 2-way binding in Xamarin Forms UWP throws exception

### ISSUE THREAD

**Issue by kyurkchyan** [realm/realm-dotnet#1869]
## Goals

I am working on Xamarin forms project targeting iOS/Droid/UWP. We are building the app in a reactive manner and use direct model bindings. So, when we bind to the model RealmObject property in an Entry for instance the value is persisted automatically. 

## Expected Results

Changing the Text of the entry should persist the value of the RealmObject.

## Actual Results

On iOS/Android everything works as expected. On UWP as soon as page is loaded I receive the following exception
`Cannot modify managed objects outside of a write transaction.`

## Steps to Reproduce

1. Open the RealmBindingSample project
2. Set UWP as the startup project
3. Run it

## Code Sample

 For instance, let's imagine we have the following code
```
public class Product : RealmObject
    {
        public string Name { get; set; }
    }
    // Learn more about making custom code visible in the Xamarin.Forms previewer
    // by visiting https://aka.ms/xamarinforms-previewer
    [DesignTimeVisible(false)]
    public partial class MainPage : ContentPage
    {
        public static string LocalPath = "";
        public MainPage()
        {
            InitializeComponent();
            var realm = Realm.GetInstance(Path.Combine(LocalPath, "RealmSample.realm"));
            realm.Write(() =>
            {
                realm.Add(new Product()
                {
                    Name = "Test"
                });
            });
            BindingContext = realm.All<Product>().FirstOrDefault();
        }
    }

```

And the following xaml file

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d"
             x:Class="RealmBindingSample.MainPage">

    <StackLayout>
        <Entry 
            Text="{Binding Name}"/>
    </StackLayout>

</ContentPage>
```

## Version of Realm and Tooling
Realm.Database 3.4.0

### Sample project
[RealmBindingSample.zip](https://github.com/realm/realm-dotnet/files/3294249/RealmBindingSample.zip)

**Comment by nirinchev** [comment]
Two way data binding doesn't work with UWP with Realm 3.4.0 because it's a netstandard 1.4 library and the classes needed to implement automatic transactions were only added in netstandard 2.0. You can upgrade Realm to 4.0.0, but be advised that that will require upgrading your UWP project to target netstandard 2.0.

**Comment by kyurkchyan** [comment]
@nirinchev  thanks for the reply. It indeed solve the issue. I used to reference Realm.Database nuget when I don't need the real time cloud syncing. I am closing the issue, but to clarify we are not ought to use Realm.Database package anymore?

**Comment by nirinchev** [comment]
Correct - we unified the various Realm packages into a single package. Here is a brief guide when upgrading from 3.x: https://realm.io/docs/dotnet/latest#upgrading-from-realm-3x
