### ISSUE TITLE
This bundle Payload/.../realm-wrappers.framework is invalid

### ISSUE THREAD

**Issue by kyurkchyan** [realm/realm-dotnet#1870]
## Goals

I have Xamarin.iOS application using Realm nuget 4.0.0. I am trying to upload the ipa file to apple iTunes store

## Expected Results

I am expecting for the ipa to be successfully uploaded.
## Actual Results

I am getting iTunes error while the upload process

> ERROR ITMS-90056: "This bundle Payload/.../Frameworks/realm-wrappers.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion. Please find more information about CFBundleVersion at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion"

## Steps to Reproduce

1. Install Realm 4.0.0 nuget into Xamarin.iOS solution
2. Create archive
3. Export the signed archive into ipa
4. try to distribute the archive through Application loader

## Version of Realm and Tooling
Realm.Net nuget 4.0.0

**Comment by kyurkchyan** [comment]
This is pretty serious issue. It blocks us from being able to publish the app to TestFlight.

**Comment by Dids** [comment]
Same issue here, and this is definitely critical at this point.

```
ERROR ITMS-90057: "The bundle 'Payload/MyApp.app/Frameworks/realm-wrappers.framework' is missing plist key. The Info.plist file is missing the required key: CFBundleShortVersionString. Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring"
ERROR ITMS-90056: "This bundle Payload/MyApp.app/Frameworks/realm-wrappers.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion. Please find more information about CFBundleVersion at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion"
Return status of iTunes Transporter was 1: ERROR ITMS-90057: "The bundle 'Payload/MyApp.app/Frameworks/realm-wrappers.framework' is missing plist key. The Info.plist file is missing the required key: CFBundleShortVersionString. Please find more information about CFBundleShortV\nERROR ITMS-90056: "This bundle Payload/MyApp.app/Frameworks/realm-wrappers.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion. Please find more information about CFBundleVersion at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion"
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
```

**Comment by Dids** [comment]
@nirinchev Any ideas? Even a hacky workaround would do at this point, need to get a new build to the App Store soon.

**Comment by Dids** [comment]
So to recap, `CFBundleVersion` is there but empty, and `CFBundleShortVersionString` is missing entirely.

![Screenshot 2019-06-20 12 18 50](https://user-images.githubusercontent.com/3455449/59837240-97375580-9355-11e9-85fd-b234ab0e5af5.png)

**Comment by Dids** [comment]
@kyurkchyan Here's a temporary workaround for now:

```sh
/usr/libexec/PlistBuddy -c "Set :CFBundleVersion 4.0.0" "packages/Realm.4.0.0/native/ios/universal/realm-wrappers.framework/Info.plist"
/usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string 4.0.0" "packages/Realm.4.0.0/native/ios/universal/realm-wrappers.framework/Info.plist"
```

It'll basically just set/add the missing version information, so it should go through the upload process (even if the version information isn't technically correct).

**Comment by kyurkchyan** [comment]
@Dids thanks for the suggestion. It did solve the problem for now.

**Comment by Dids** [comment]
Note that while did does solve the problem, I'm still seeing instant crashes at launch on iOS devices. Likely related to #1871.

Starting to look like maybe 4.0.0 wasn't properly tested?

**Comment by kyurkchyan** [comment]
@Dids  Yeah :( Unfortunately that's the case for me. It crashes immediately on a device. Though it works perfectly fine on a simulator. I banged my head over the wall quite a while trying to find the cause.
