### ISSUE TITLE
Realm fails in deployed WPF/Windows10 app with realm-wrapper.dll not found error

### ISSUE THREAD

**Issue by duncangroenewald** [realm/realm-dotnet#1877]
## Goals

Trying to run a WPF/Windows10 App - which works fine when run in debug mode under VS but fails when deployed with ClickOnce.

## Expected Results

Expect it to run like it does when running in debug mode under VS.

## Actual Results

App throws an exception "Unable to load DLL 'realm-wrappers'".

## Steps to Reproduce

Create a simple WPF/Windows 10 app and include the NUGET Realm 4.0.1 package.

As a workaround it seems that if you do a build for release the Release build folder does include all the required files, including the realm-wrappers.dll.  Perhaps something about the DLL placement that does not work with ClickOnce.

## Code Sample

I will have to create a sample application for you to test but it seems there are others who have reported the same issue.  It seems the realm-wrappers.dll files are in the .nuget folder and the debug app works fine.  Some problem that the dll is not being included in the deployed app.

## Version of Realm and Tooling

- Realm Object Server Version: None
- Client SDK Version: Realm NUGET Package 4.0.1
- Client OS & Version: Windows 10

**Comment by tbarela** [comment]
I'm not too familiar with Realm, I'm looking at it as part of a larger pre-existing project right now. But I think this is the same issue...

But while trying to build a csproj that uses Realm.Server.1.1.0, I get errors about not being able to copy ''realm-wrappers.dll'. At that location, a "real-server-wrappers.dll' does exist however, and when I renamed it to match the first filename, it built sucessfully.

Looking at the nuget package itself, the filenames seem to be inconsistent...
![realm-nupkg-issue](https://user-images.githubusercontent.com/8857282/60932733-26100180-a274-11e9-8876-d43676216aed.png)

**Comment by nirinchev** [comment]
@tbarela this seems like a different issue. The Realm.Server package has been merged into the Realm package starting with Realm 4.0, so it's probably best to just upgrade to that version.

**Comment by fealebenpae** [comment]
I think this is because the `realm-wrappers.dll` files are included as `None` and not `Content`. I'll investigate, but it seems likely going with `Content` will fix this.
