### ISSUE TITLE
Can't build for Xamarin.iOS after upgrading to Realm 4.0.1 

### ISSUE THREAD

**Issue by MadSam08** [realm/realm-dotnet#1878]
I have an Xamarin.iOS application and after upgrading to the realm 4.0.1 the project won't build it throws just an exception, don't know how to resolved it.

## Expected Results
Expected the application to build with no errors.

## Actual Results

Failed to resolve "System.Void Realms.WovenAssemblyAttribute::.ctor()" reference from "Realm, Version=4.0.1.0, Culture=neutral, PublicKeyToken=null"

## Using:
Visual Studio Enterprise 2019 v16.1.5
Using Windows 10
Xamarin.iOS 12.10.0.157
Realm 4.0
Build machine
Xcode 10.2.1
MacOS Mojave 10.14.5

**Comment by nirinchev** [comment]
That's a very surprising exception - can you try to delete your packages, obj, and bin folders to make sure there's no leftover state? Also, do you linking enabled? It's possible that the linker strips that attribute before the weaver has a chance to reference it?

**Comment by MadSam08** [comment]
@nirinchev I did delete all the obj and bin folder, the linking behavior is set to Don't Link, 
Now after cleaning all the left overs I get a different error message 
library not found for -lrealm-wrappers

Native linking failed. Please review the build log and the user flags provided to gcc: -L
native/ios/universal -lrealm-wrappers -lz -framework

**Comment by fealebenpae** [comment]
I think because you're using Visual Studio's feature to remotely build Xamarin.iOS projects on a linked macOS machine there are some files on the macOS machine that need to be wiped as well to make sure the project is being built from scratch.

Alternatively, create a new Xamarin.iOS project and add Realm to it and see if the same behavior repeats. A new project will have no cache/stale build artifacts.

**Comment by MadSam08** [comment]
I fixed the issue, the problem was related to VS not installing correctly the nuget pack

**Comment by MadSam08** [comment]
T:* Fixed

**Comment by xDelivered-Patrick** [comment]
I'm also running into this issue. I have all the correct libraries installed. 

In terms of flags - is '-L native/ios/universal -lrealm-wrappers -lz -framework'  correct?
-lrealm-wrappers looks like it needs a whitespace between -l and 'realm-wrappers'. 

Just guessing here, perhaps that's a legitimate command.

**Comment by xDelivered-Patrick** [comment]
This is the error building on VS AppCenter

`
"/Users/vsts/agent/2.154.1/work/1/s/Sift.iOS/Sift.iOS.csproj" (Rebuild target) (1) ->
(_CompileToNative target) -> 
  clang : error : linker command failed with exit code 1 (use -v to see invocation) [/Users/vsts/agent/2.154.1/work/1/s/Sift.iOS/Sift.iOS.csproj]
  error MT5209 : Native linking error : library not found for -lrealm-wrappers [/Users/vsts/agent/2.154.1/work/1/s/Sift.iOS/Sift.iOS.csproj]
  MTOUCH : error MT5201: Native linking failed. Please review the build log and the user flags provided to gcc: -ObjC -lsqlite3 -ObjC -ObjC -lc++ -lsqlite3 -lz -ObjC -lc++ -lsqlite3 -lz -L/Users/vsts/.nuget/packages/realm/4.0.1/build/../native/ios/universal -lrealm-wrappers -lz -framework Security [/Users/vsts/agent/2.154.1/work/1/s/Sift.iOS/Sift.iOS.csproj]
  MTOUCH : error MT5202: Native linking failed. Please review the build log. [/Users/vsts/agent/2.154.1/work/1/s/Sift.iOS/Sift.iOS.csproj]

    49 Warning(s)
    4 Error(s)

Time Elapsed 00:02:26.88
##[error]Xamarin.iOS task failed with error Error: /Library/Frameworks/Mono.framework/Versions/5_18_2/bin/msbuild failed with return code: 1. For guidance on setting up the build definition, see https://go.microsoft.com/fwlink/?LinkId=760847.
[command]/usr/bin/security delete-keychain /Users/vsts/agent/2.154.1/work/1/s/_xamariniostasktmp.keychain
##[section]Finishing: Build Xamarin.iOS solution
##[section]Starting: Checkout`
