### ISSUE TITLE
Updated Example with more functionality

### ISSUE THREAD

**Issue by HobDev** [realm/realm-dotnet#1882]
## Goals

The Example in realm-dotnet repo is very small and outdated. It is not updated for years. An updated example which shows lots of important features of realm-dotnet using Xamarin.Forms will be very helpful for getting started. 

## Version of Realm and Tooling

- Realm Object Server Version: ? (you can see this as well in Studio once connected to a Realm instance) 
- Flavor:
  - [ ] Realm Cloud
  - [ ] Self-Hosted
- Server OS & Version: ? (e.g. CentOS 6)
- Client SDK Version: ?
- Client OS & Version: ?

**Comment by nirinchev** [comment]
Check out https://github.com/realm/my-first-realm-app and https://github.com/realm/realm-tasks/tree/master/RealmTasks%20Xamarin - they are slightly more complex than the examples in this repo.

**Comment by HobDev** [comment]
https://github.com/HobDev/ToDoRealm  is a Xamarin.Forms sample inspired from Xamarin.Forms ToDo sample app. The official sample used SQLite. I  replaced SQLite with Realm in my sample.
Thank you
