### ISSUE TITLE
Add ThreadSafeReference for IRealmCollection

### ISSUE THREAD

**Issue by WhitePhoera** [realm/realm-dotnet#1886]
## Goals

Hello, i want to offload as much work as possible to background threads.(i prefer to show loading indicator, instead of small stuterring)
As well as preparing IRealmCollection<T> as well.
ThreadSafeReference have IList support, but IRealmCollection don't implement it, so i can't use that way.

## Expected Results

Be able to resolve IRealmCollection when passing between realm instances.

## Actual Results

No such method/class

## Code Sample

```
var dat = Task.Run(() =>
{
    using (var r = Realm.GetInstance(realm.Config))
        return r.All<Test>().AsRealmCollection();
}).Result;
Console.WriteLine(dat.IsValid);//false
```

## Version of Realm and Tooling

3.4.0

**Comment by nirinchev** [comment]
Is there a reason for casting to IRealmCollection? You can create a ThreadSafeReference from the query results instead.

**Comment by WhitePhoera** [comment]
Which results you mean?

After ToList it will not be live results already.
IQueriable as well not results yet.

**Comment by WhitePhoera** [comment]
actually i looked inside method AsRealmCollection, that really just cast.
then i must just use Query passing. 

sorry for bothering.
