### ISSUE TITLE
CollectionChanged / Notification callback not triggered

### ISSUE THREAD

**Issue by PieEatingNinjas** [realm/realm-dotnet#1895]
Got some strange behaviour regarding CollectionChanged / notification callbacks. Am I missing something or is this a bug in the framework? If you need any additional information, don't hesitate to reach out.

## Goals
I'm registering a notification callback and CollectionChanged event handler on a Realm collection. I'd assume that if I'd add an object to this collection, the notification callback and the CollectionChanged event would get triggered.

## Expected Results
The notification callback and the CollectionChanged event to be triggered.

## Actual Results
The notification callback is triggered once, without a ChangeSet. The CollectionChanged event is never fired. Despite the object to be successfully added to Realm.
However, if I add an additional ~~empty~~ realm.Write transaction, everything works as expected: callback is called and CollectionChanged event is triggered after this additional transaction is called. (see code below)

## Steps to Reproduce
In Visual Studio for Mac Enterprise 8.2.3 (Build 16) I created a new .NET Core Console Application. Added Realm (4.1.0) NuGet package. Added the code below:

## Code Sample
```csharp
 class Program
 {
     static void Main(string[] args)
     {
         var realm = Realm.GetInstance();

         realm.Write(() =>
         {
             realm.RemoveAll<Dog>();
         });            

         var listOfDogs = realm.All<Dog>();
         var realmCollectionOfDogs = listOfDogs.AsRealmCollection();

         listOfDogs.SubscribeForNotifications(callabck);
         realmCollectionOfDogs.CollectionChanged += Program_CollectionChanged;

         realm.Write(() =>
         {
             realm.Add(new Dog { Name = "Bruce", Age = 11 });
         });

         //Without this, the notificationCallback will only be triggered without a changeset and the CollectionChanged will not get triggered at all
         //With this, everything seems to work as I would expect...
         //realm.Write(() =>
         //{
         //});

         Console.ReadKey();
     }


     private static void callabck(IRealmCollection<Dog> sender, ChangeSet changes, Exception error)
     {
         Console.WriteLine("callback");
         if (changes != null)
         {
             foreach (var item in sender)
             {
                 Console.WriteLine((item as Dog)?.Name);
             }
         }
     }

     private static void Program_CollectionChanged(object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
     {
         Console.WriteLine("Collection changed");
     }
 }

 public class Dog : RealmObject
 {
     public string Name { get; set; }
     public int Age { get; set; }
 }

```

## Version of Realm and Tooling
* Realm Object Server Version: N/A
* Flavor: N/A
* Server OS & Version: N/A
* Client SDK Version: 4.1.0
* Client OS & Version: macOS Mojave 10.14.6 (18G87), .NET Core 2.1

**Comment by nirinchev** [comment]
Sounds like Console.ReadKey blocks the thread you're on so a notification can't be delivered.

**Comment by PieEatingNinjas** [comment]
Mmm... that might indeed be the case. I’ll check it out asap and will let you know.

**Comment by fealebenpae** [comment]
I think notifications aren’t delivered because console apps lack a synchronization context suitable for Realm notifications. I suggest using [`Nito.AsyncEx.Context`](https://www.nuget.org/packages/Nito.AsyncEx.Context) and wrapping your Main method in an `AsyncContext.Run()` call after you resolve the `Console.ReadKey()` situation.
