### ISSUE TITLE
Pause and Start Subscriptions

### ISSUE THREAD

**Issue by luccasclezar** [realm/realm-dotnet#1898]
## Goals

I don't know if this is supported right now in a way I couldn't think of, but having a snapshot of the data of a subscription after unsubscribing is a pretty common scenario.

A solution that wouldn't disrupt Realm's sense of 'liveness' would be to have a way of pausing and starting a Subscription (much like `Session.Stop()` and `Session.Start()`) so that we could show the paused Subscription's results while it fetches the updates from the server.

## Expected Results

For instance, in a social network:

1. UserA access UserB's profile.
2. A Subscription to UserB's profile is created.
3. When UserA closes UserB's profile, unsubscribe.
4. Then UserA accesses UserB's profile again.
5. UserA would see a local copy of UserB's profile instantly while the renewed Subscription fetches any new data from the server.

## Actual Results

5. UserA would need to re-download UserB's entire profile with a new Subscription before getting to see anything.

**Comment by luccasclezar** [comment]
Bump.

Isn't there a workaround? Anything I could do to keep the Subscription paused or keep the Subscription data locally after unsubscribing?

**Comment by nirinchev** [comment]
There's nothing similar to that functionality at the moment. One alternative approach you could try is to create subscriptions with an expiration (say 1 day/1 week or whatever works for your app). Then, update the expiration date every time userA accesses userB's profile and rely on automatic subscription cleaning rather than unsubscribe manually. It's not what you're looking for, but it should provide a similar experience.

**Comment by luccasclezar** [comment]
Okay, thank you. I already implemented like this while waiting for an answer, so I'll keep it this way.

Feel free to close this issue if this feature will not be considered for a while.

**Comment by bmunkholm** [comment]
We will put it back on the "Idea Backlog". If others feel the use for this, please upvote with 👍 in the issue description.

**Comment by nirinchev** [comment]
QBS and subscriptions are not supported with MongoDB Realm, so we won't work on that. We will revisit, once MongoDB Realm adds support for something similar to what the old QBS was doing.
