### ISSUE TITLE
Cannot delete objects without Realm accessed from incorrect thread

### ISSUE THREAD

**Issue by ndastur** [realm/realm-dotnet#1900]
## Goals
Iterate through a list of realm objects and delete each one as it is processed

## Expected Results
Object gets deleted.

## Actual Results
A Realm accessed from incorrect thread exception is thrown

## Steps to Reproduce

The code below demos the error.
I have also tried wrapping the foreach in the realm.BeginWrite()... and so getting my list inside of that block. I.e.

```
var realm = Realm.GetInstance();
                using (var trans = realm.BeginWrite())
                {
                    var queueItems = realm.All<DataQueue>().OrderBy(u => u.Created);

                    foreach (DataQueue item in queueItems)
                    {
                        if (await SendItemAsync(item.Type, item.Obj))
                        {
                                realm.Remove(item);
                        }
                    }
                    trans.Commit();
                }
```
## Code Sample
```
public class DataQueue : RealmObject
    {
        public DateTimeOffset Created { get; set; }
	public string Type { get; set; }
	public string Obj { get; set; }

        public DataQueue()
        {
            Created = DateTime.Now;
        }
    }

public async Task<(bool, int)> SendAllQueue(CancellationToken token = default)
{
  var realm = await Realm.GetInstanceAsync();
  var queueItems = realm.All<DataQueue>().OrderBy(u => u.Created);
  foreach (DataQueue item in queueItems)
  {
  if (await SendItemAsync(item.Type, item.Obj))
    {
       using (var trans = realm.BeginWrite()) {
          realm.Remove(item);
          trans.Commit();
        }
    }
   }
}
```

Start the data send with 

```
            Task.Run(async () => {
                    var (result, count) = await DataSyncQueue.Instance.SendAllQueue();
            });
```
## Version of Realm and Tooling
Realm Database inside of a Xamarin Forms app running on Android.

**Comment by nirinchev** [comment]
Is this happening on a background thread? If it is, then awaiting something will dispatch the continuation to a random thread from the thread pool, which will violate Realm's thread confinement. You either need to execute the code on the main thread or use something like Nito.AsyncContext to inject synchronization context to your thread.

**Comment by ndastur** [comment]
Hi @nirinchev . Thanks for your help. I have to say I don't quite understand.
```
Task.Run(async () => {
   var (result, count) = await DataSyncQueue.Instance.SendAllQueue();
});
```
Is called on app start-up. But as it should, does dispatch the "job" into a thread. I thought by requesting a new realm instance in the function I should avoid the threading issues? I'm not passsing objects between threads. Everything should be happening in the same thread. Should it not? If I have got this all wrong do you happen to have an example using Nito.AsyncContext?

**Comment by ndastur** [comment]
Just as a follow-up and help to others. Wrapping in  ```Nito.AsyncEx.AsyncContext.Run(async () => { ... }``` does seem to solve the problem. But this does "feel" wrong. I'd have thought the pattern I was describing above is common enough and something is not right in the underlying library. Also seems a shame to have to use an additional 3rd party library.

**Comment by nirinchev** [comment]
Realm objects need to be accessed from the thread they are instantiated on. This is covered by the docs. When using `await` on a background thread, the continuation is dispatched on a random thread, thus violating that restriction. This is not the case for the main thread or Nito.AsyncEx threads as those have synchronization context which ensures that continuations can be posted on the same thread.

**Comment by ndastur** [comment]
@nirinchev Still doesn't quite make sense and I'd suggest not very friendly user experience. There are now 100s of posts on SO about Realm and thread problems. Having a quick peek in the code .ConfigureAwait(false) does not seem to be used in this library on calls that are awaited. Is there a reason. Is this the reason for the problems users experience?

**Comment by nirinchev** [comment]
No, the ConfigureAwait doesn't have any effect on the behavior you're observing - it's an inherent property of c#/.NET and ConfigureAwait doesn't change the way continuations are dispatched on background threads. There are benefits and drawbacks of the threading model Realm has chosen and those are discussed at length on SO/blog posts, so I won't go into them here,
