### ISSUE TITLE
InvalidOperationException when removing databound object

### ISSUE THREAD

**Issue by carlst99** [realm/realm-dotnet#1903]
## Goals
I have a WPF application in which I am binding a ListView to a collection of RealmObjects. My goal is to remove one of these objects from the database

## Expected Results
I expected the object to be successfully removed and the bound ListView to update.

## Actual Results
System.InvalidOperationException: 'Added item does not appear at given index '1'.'. No stack trace is given. On enabling native code debugging the exception seems to be occuring in realm-wrappers.dll. Slightly misleading as the debug output shows the exception occurs in PresentationFramework.dll

## Steps to Reproduce
Bind a ListView to a collection of RealmObjects. Remove an object from the realm instance and you will cause an InvalidOperationException

## Code Sample
I've created a repository with a couple of [test projects](https://github.com/carlst99/RealmTester) highlighting the issue. Add a few blogs and then select and try to delete one; it should crash with the error. 

Note that the first test project mimics my use-case scenario, hence the libraries Stylet and MaterialDesignThemes

## Version of Realm and Tooling
* realm-dotnet 4.1.0, local DB
* Have tested on .NET Framework 4.6.1, 4.8
* Windows 10

**Comment by carlst99** [comment]
I've figured out how to workaround this. The full example is in the workaround branch of the sample repo (RealmTesterBasic project), but here's a summary.

Instead of binding directly to an IQueryable<T>, bind to a list, e.g.

```c#
List<T> MyCollection = _realm.All<T>().ToList()
```

Then everytime you update the DB, simply reset the list using the above. You can capture updates either through your own logic or with the Realm.RealmChanged event.

The same goes for any IList<T> properties in your RealmObjects; convert them to a list in your ViewModel before binding, and update them as appropriate. It's painful, but it works.

**Comment by redbeaner** [comment]
Hi ! I'm facing the same issue and just wonder why can't we use IEnumerable<T> return from _realm.All<T> instead have to call ToList(). The Example from Realm.Net on Github for Xamarin Form also suggest to bind directly to IEnumerable<T>.

**Comment by papafe** [comment]
> I've figured out how to workaround this. The full example is in the workaround branch of the sample repo (RealmTesterBasic project), but here's a summary.
> 
> Instead of binding directly to an IQueryable, bind to a list, e.g.
> 
> ```cs
> List<T> MyCollection = _realm.All<T>().ToList()
> ```
> 
> Then everytime you update the DB, simply reset the list using the above. You can capture updates either through your own logic or with the Realm.RealmChanged event.
> 
> The same goes for any IList properties in your RealmObjects; convert them to a list in your ViewModel before binding, and update them as appropriate. It's painful, but it works.

Yes, it definitely works, but as you said this is a problem as it will create issues with the bindings. I manage to reproduce the issue and I'll try to investigate

**Comment by polymath74** [comment]
I have recently started converting a project from SqlServer to Realm, and have just encountered this bug. I can reproduce it consistently. I added my own CollectionChanged event handler, and my guess is WPF is misusing the event args. (I have had problems with WPF and CollectionChanged events before!)

So the notification comes in like this:
![image](https://user-images.githubusercontent.com/89322485/130336344-d2b1fb83-4271-4dc4-bfb7-f0e36360d579.png)

It has 1 old item, with the index in OldStartingIndex, but the item itself is null.

I wonder whether WPF is trying to look for a null object at that index? Or is it just completely wrong—the exception complains about an "added item" but this is a delete…?

**Comment by nirinchev** [comment]
Yeah, we were looking into that Friday and [came across the culprit](https://github.com/dotnet/wpf/blob/3a7e2a77d41d2e3ec68dc7ad32c60d7df88ab49f/src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Data/EnumerableCollectionView.cs#L430-L431), which, ironically, has a comment about replacing the message with a better one 🥲 In any case, we have several avenues we're exploring that will mitigate this and hope to have a fix with our next release.
