### ISSUE TITLE
Google Pixel XL No Sd Card Folder xamrian forms 4 custom realm location

### ISSUE THREAD

**Issue by davidbuckleyni** [realm/realm-dotnet#1904]
In Production, I am using a google pixel xl for the device but it has no sdcard folder I want to create a folder so I can easily get the file of the database from ADB without rooting my device at present I cant as its a Y6 2019 device.

How do i tell it to create the database in specific folder on the phone. I am using xamrian forms 4

**Comment by fealebenpae** [comment]
You can do this by supplying the `optionalPath` argument when invoking a `RealmConfiguration` constructor:
```csharp
var config = new RealmConfiguration(optionalPath: "/path/to/my/db.realm");
```
