### ISSUE TITLE
Cannot use RealmObject after update to 4.0

### ISSUE THREAD

**Issue by suhomlineugene** [realm/realm-dotnet#1905]
I updated the Realm in Xamarin iOS project to 4.0.

After this RealmObject is couldn't be finded.

Here is code

`public class Filter: RealmObject
{
    public string CategoryId { get; set; }
}`

Realm package is installed. Any advice, how to fix this?

**Comment by nirinchev** [comment]
Try clearing the bin/obj folders as well as the nuget package cache.

**Comment by suhomlineugene** [comment]
> Try clearing the bin/obj folders as well as the nuget package cache.

Tried already, didn't helps.

**Comment by nirinchev** [comment]
What is the .NET version your project is targeting? Realm 4.0 bumped the realm target from .NET standard 1.4 to 2.0. Perhaps it is now incompatible with your project?

**Comment by Doxoh** [comment]
Same problem.
At my Xamarin.IOS Project Realms.RealmObject is availble but the Xamarin Forms PCL project the namespace Realms does not available. 

I'm using Mono 5.20.0.

Does someone have an idea to fix it?

**Comment by nirinchev** [comment]
PCL projects are not supported in Realm 4.x. You can migrate your PCL to a netstandard project.

**Comment by Doxoh** [comment]
@nirinchev thanks, I will test it today

**Comment by fealebenpae** [comment]
As the 4.0 release noted, Realm no longer provides a Portable Class Library version. PCL projects will not be able to access the Realm API once they upgrade to 4.0. We suggest migrating to .NET Standard 2.0.
