### ISSUE TITLE
Support in-memory Realms

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#191]
As per the [Cocoa docs](https://realm.io/docs/objc/latest/api/Classes/RLMRealm.html#//api/name/inMemoryRealmWithIdentifier:) need a way to specify an in-memory Realm and simple test it works.

Class documentation in Realm.cs will need updating as will the `index.md`

**Comment by AndyDentFree** [comment]
Note that most of this is now implemented as of the acceptance of PR #812 so we just need a C# trivial configuration interface and a unit test.

**Comment by seburgi** [comment]
Sounds like this would be very useful for integration tests, where data should only live in memory. Any plans to support this soon? Thanks!
