### ISSUE TITLE
Realm Cloud doesn't work in Azure Function due to missing 'realm-wrappers' dll

### ISSUE THREAD

**Issue by pfedotovsky** [realm/realm-dotnet#1914]
## Goals
Deploy Azure Function with Realm package to access shared realm.

## Expected Results
Azure function works, no exceptions.

## Actual Results
_The type initializer for 'Realms.Sync.SharedRealmHandleExtensions' threw an exception._
Inner exception states that 'realm-wrappers.dll' is not found.

## Steps to Reproduce
1. Create empty Azure Function project with .NET Core
1. Add Realm package, add _await User.LoginAsync_ call
1. Deploy to Azure (Windows based App Service)
1. Run function in Azure

## Code Sample
See https://github.com/pfedotovsky/RealmAzureFunction

## Version of Realm and Tooling
* Realm Object Server Version: Realm Cloud
* Realm 4.2.0

**Comment by pfedotovsky** [comment]
I've found the workaround. In Azure, the folder structure after deployment is

- wwwroot
-- bin
-- runtimes
-- <other files/folders>

The fix is to move the _/runtimes_ folder under _/bin_ in Azure (using Kudu) so the structure is

- wwwroot
-- bin
--- runtimes
-- <other files/folders>

There's another issue with running Azure Function on MacOS Catalina locally, it fails with the same reason.
The folder structure is
- wwwroot
-- bin
--- runtimes
-- <other files/folders>

If I copy _librealm-wrappers.dylib_ from _/runtimes_ to _/bin_ the issue is resolved.


Overall, it seems that something is broken with copying native libraries to the right place. Not sure if it's Visual Studio or Realm or Nuget issue.

**Comment by nirinchev** [comment]
This seems to have been resolved by Microsoft for Functions targeting .NET 3.1 and newer. Closing this as things work as expected for new enough platforms and there's a feasible workaround for old ones.
