### ISSUE TITLE
Ream.GetInstance(config) throws "The process has no package identity. (Exception from HRESULT: 0x80073D54)"

### ISSUE THREAD

**Issue by Yeah69** [realm/realm-dotnet#1917]
## Goals

I would like to open the realm file with my WPF application again.

## Expected Results

Ream.GetInstance(config) returns a realm instance without throwing an exception.

## Actual Results

Ream.GetInstance(config) throws "The process has no package identity. (Exception from HRESULT: 0x80073D54)"

![image](https://user-images.githubusercontent.com/11756150/67240637-26fb2680-f452-11e9-8694-96c7ea587205.png)

StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)

## Steps to Reproduce

Call Ream.GetInstance(config).
I am not sure what caused it. I had build the WPF application a few times and run on debug everything worked fine. Then I made a hard reset with git to the most recent commit so I would loose my uncommited changes. I think since then it throws this exception.
Then I updated to the last stable version of Realm (4.2.0). Unfortunately it didn't help.

I can however open the file in the Realm Studio successfully.

## Version of Realm and Tooling

Realm nuget package version: 4.2.0
.Net Framework 4.7.2
![image](https://user-images.githubusercontent.com/11756150/67241278-6d9d5080-f453-11e9-8e8c-f68a4b30b4a2.png)

**Comment by Yeah69** [comment]
Okay, it turns out that I disabled "Just my code" in VS.
Hence, it is some exception which I can ignore because it probably is catched somewhere in the Realm code base.
I am sorry if this issue caused someone trouble or effort.

**Comment by nirinchev** [comment]
I think this error may be thrown as we attempt to guess where to store the realm file - we use reflection to determine if it's a UWP app or a WPF one and since it's not on a hot path, we just try to call a method and catch the exception rather than do extensive error checking.
