### ISSUE TITLE
realm v.4.2.0 visual studio doesn,t hit the breakpoint ( xamarin cross platform windows )

### ISSUE THREAD

**Issue by fkbeys** [realm/realm-dotnet#1919]
Hello friends.
today i updated the realm with nuget packet to version 4.2.0.

after update, the visual studio couldnt hit the breakpoints.
i managed to fix it after long hours searching on internet. finally, i downgraded the version to 4.0.0 and now it s working great. thank u.

**Comment by nirinchev** [comment]
Duplicate of https://github.com/realm/realm-dotnet/issues/1910
