### ISSUE TITLE
Realm aux named pipe '.realm.note' cause VS for Mac to freeze

### ISSUE THREAD

**Issue by pfedotovsky** [realm/realm-dotnet#1921]
If solution contains 'realm.note' file, it causes lots of issues for VS for Mac

- 90% vs for Mac stuck at opening solution
- rest 10%, solution is opened, but Intellisence not working

It's a known VS for Mac issue (https://developercommunity.visualstudio.com/content/problem/390791/gathering-class-information-does-not-disappear-cau.html), as VS for Mac doesn't support named pipes.

The _'realm.note'_ is added when _.realm_ file is opened so it's a common scenario when _'realm.note'_ is present. Adding it to _.gitignore_ doesn't help.

I'm creating this issue to see if there's anything that can be done on Realm side till the issue is resolved in Visual Studio for Mac. I suggest at least mentioning the issue in the Realm documentation.

**Comment by pfedotovsky** [comment]
@fealebenpae I'd be happy to help with the testing. Could you please clarify the steps to define mime types?

**Comment by nirinchev** [comment]
I've hit this once or twice too. My workaround is to force Realm to create files under `bin`, where VS for Mac ignores them. Not ideal, but not terrible either.

**Comment by fealebenpae** [comment]
@pfedotovsky as far as I understand on macOS the Realm Studio app bundle needs to declare it understands the `*.realm.note` extension, just as it does `*.realm` and that its MIME type is `application/octet-stream` or something else binary so that VSMac knows it's binary and not text.
