### ISSUE TITLE
Cannot open a synced realm in 4.2.0

### ISSUE THREAD

**Issue by raudabaugh** [realm/realm-dotnet#1922]
## Goals

We have a ASP.NET Core GraphQL server that is built on top of Realm .NET SDK. Recently, our server started hanging when trying to open a synchronized Realm.

## Expected Results

Execute `Realm.GetInstance(config)` consistently without error.

## Actual Results
Somehow the sync client got into a state where it always attempts a client reset, even after completely clearing out all local realm data.
```
Oct 26 19:55:29  ThreadAPI:  DEBUG - Realm sync client ([realm-core-5.23.3], [realm-sync-4.7.5])
Oct 26 19:55:29  ThreadAPI:  DEBUG - Supported protocol versions: 26-29
Oct 26 19:55:29  ThreadAPI:  DEBUG - Platform: Windows Server Win32 unknown 10.0.14393.2969 x86_64
Oct 26 19:55:29  ThreadAPI:  DEBUG - Build mode: Release
Oct 26 19:55:29  ThreadAPI:  DEBUG - Config param: max_open_files = 256
Oct 26 19:55:29  ThreadAPI:  DEBUG - Config param: one_connection_per_session = 1
Oct 26 19:55:29  ThreadAPI:  DEBUG - Config param: connect_timeout = 120000 ms
Oct 26 19:55:29  ThreadAPI:  DEBUG - Config param: connection_linger_time = 30000 ms
Oct 26 19:55:29  ThreadAPI:  DEBUG - Config param: ping_keepalive_period = 60000 ms
Oct 26 19:55:29  ThreadAPI:  DEBUG - Config param: pong_keepalive_timeout = 120000 ms
Oct 26 19:55:29  ThreadAPI:  DEBUG - Config param: fast_reconnect_limit = 60000 ms
Oct 26 19:55:29  ThreadAPI:  DEBUG - Config param: disable_upload_compaction = 0
Oct 26 19:55:29  ThreadAPI:  DEBUG - Config param: tcp_no_delay = 0
Oct 26 19:55:29  ThreadAPI:  DEBUG - Config param: disable_sync_to_disk = 0
Oct 26 19:55:29  ThreadAPI:  DEBUG - User agent string: 'RealmSync/4.7.5 (Windows Server Win32 unknown 10.0.14393.2969 x86_64) RealmDotNet/4.2.0.0 (.NET Core 4.6.28008.02) '
Oct 26 19:55:29  ThreadAPI:  DEBUG - Connection[1]: WebSocket::Websocket()
Oct 26 19:55:29  ThreadAPI:  INFO - Connection[1]: Session[1]: Binding 'd:\home\site\realmobjectserver\4b3dd0342e9dc9ec4184b7d60a6fc11dc192895bdc4e08cd9c84ba3c41cf7519\sync.threadlearning.dev\01c63205-6d4d-4073-aa2a-fa57db25a257' to '/01c63205-6d4d-4073-aa2a-fa57db25a257/organization'
Oct 26 19:55:29  ThreadAPI:  DEBUG - Connection[1]: Session[1]: Activating
Oct 26 19:55:29  ThreadAPI:  INFO - Connection[1]: Session[1]: client_reset_config = true, Realm exists = false, async open = true, client reset = false
Oct 26 19:55:29  ThreadAPI:  ERROR - Connection[1]: Session[1]: Client reset config requires an existing metadata directory
```
We downgraded to 4.1.0-alpha-430 which fixed the issue. The client stopped attempting a client reset and opened the realm successfully.

## Version of Realm and Tooling

- Realm Object Server Version: 3.23.1
- Flavor:
  - [ ] Realm Cloud
  - [x] Self-Hosted
- Server OS & Version: Ubuntu 18.04.1
- Client SDK Version: 4.2.0
- Client OS & Version: Azure App Service on Windows (Microsoft Windows NT 10.0.14393.0)

**Comment by fealebenpae** [comment]
This sounds like a bug on our end. I'll investigate, but in the mean time it should be possible to work around by setting the `ClientResyncMode` on your sync configuration to `ClientResyncMode.Manual`.

Do you get this if you run the project locally, or only when it's deployed on Azure App Service?

**Comment by bmunkholm** [comment]
Just following up on this issue. Was this ever resolved for you @raudabaugh or is this still relevant? I'll close this for now, but do feel free to reopen in case this is still an issue.
