### ISSUE TITLE
Deadlock on calling realm.Refresh()

### ISSUE THREAD

**Issue by peppy** [realm/realm-dotnet#1933]
## Goals
Implementing realm (migrating from EF) in a game, with manual `Refresh` logic.

## Expected Results
Being able to call `Refresh` from any/all threads and having it eventually complete.

## Actual Results
Under certain workloads, a deadlock will occur where a single thread is stuck on `SharedRealmHandle.Refresh()`. I can confirm there are not open transactions at this point, and if I allow it, multiple threads will all block on this same call.

![image](https://user-images.githubusercontent.com/191335/70345947-81383580-18a0-11ea-8333-973482ed7835.png)

![image](https://user-images.githubusercontent.com/191335/70345992-99a85000-18a0-11ea-9514-1ce168a14243.png)

I am working to isolate a reproduction case, but felt I should post this before I do in case I am missing something obvious.

## Steps to Reproduce
* Perform writes on thread 1.
* Perform writes on thread 2.
* Call refresh from thread 1.
* Occasionally deadlocks (~80% of the time).

## Code Sample
coming soon

## Version of Realm and Tooling
latest

**Comment by nirinchev** [comment]
Is this happening on Windows?

**Comment by peppy** [comment]
Yes, I'm currently testing on windows. I'll give the same scenario a try on macOS later today.

**Comment by nirinchev** [comment]
What kind of information are you looking for? On Windows we've seen some occasional reports of notification related issues but haven't been able to isolate a consistent repro for those.

**Comment by peppy** [comment]
Raw operation output or something similar (to help with repro, because right now i'm just trial-and-error removing and adding code to see what breaks it).

**Comment by peppy** [comment]
Thank you for the hint about it being notification related. I have isolated to a 100% reproducible case:

```csharp
using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Realms;

namespace RealmDeadlockTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var config = new RealmConfiguration();

            Realm.DeleteRealm(config);
            Realm instanceFactory() => Realm.GetInstance();

            new WriterThread(instanceFactory);

            using (var localRealm = instanceFactory())
            {
                var subscription = localRealm.All<TestObject>().SubscribeForNotifications((sender, changes, error) => { Console.WriteLine("got notification"); });

                while (true)
                {
                    localRealm.Refresh();
                    Console.Write(".");
                    Thread.Sleep(10);
                }
            }
        }

        private class TestObject : RealmObject
        {
            [PrimaryKey] public string ID { get; set; }

            public TestObject()
            {
                ID = Guid.NewGuid().ToString();
            }
        }

        private class WriterThread
        {
            public WriterThread(Func<Realm> instanceFactory)
            {
                Task.Factory.StartNew(() =>
                {
                    using (var localRealm = instanceFactory())
                    {
                        while (true)
                        {
                            var obj = new TestObject();

                            using (var transaction = localRealm.BeginWrite())
                            {
                                localRealm.Add(obj);
                                Console.WriteLine("Storing item from other thread");
                                transaction.Commit();
                            }

                            Thread.Sleep(50);
                        }
                    }
                }, TaskCreationOptions.LongRunning);
            }
        }
    }
}
```

![image](https://user-images.githubusercontent.com/191335/70368689-3561ac80-18f1-11ea-938e-6acfd9b83c03.png)

**Comment by peppy** [comment]
Should I be posting this against realm core to get some attention on it? Looks like it's probably not .NET related.

**Comment by bmunkholm** [comment]
@fealebenpae just needs to recover from the holidays backlog to have a chance to look at it.

**Comment by fealebenpae** [comment]
The underlying issue is caused by https://github.com/realm/realm-object-store/issues/872. We'll track any possible resolution there.
