### ISSUE TITLE
System.Collections assembly binding redirection problem in UWP application

### ISSUE THREAD

**Issue by denizcan** [realm/realm-dotnet#1934]
When I use IList<> to create one-to-many relation, Realm requires 4.2.1 version of the System.Collections assembly… The UWP application uses 4.6.x. Visual Studio 2019 does not solve the binding by itself… I got the following error when I try accessing the IList<> property:

![ceedd7527b8aed8a9fc9c2b475507dec9827130e](https://user-images.githubusercontent.com/1451003/71243561-ac4f6a00-2321-11ea-96f0-5ebdcbf05c89.jpg)

**Comment by fealebenpae** [comment]
Hey @denizcan, can you share a small project that reproduces this?

**Comment by denizcan** [comment]
Hi @fealebenpae 

I created a small UWP project, that tries to add a Dog to a Person's Dogs property.. When run, the following exception is thrown:

<img width="739" alt="Screen Shot 2019-12-20 at 20 40 39" src="https://user-images.githubusercontent.com/1451003/71278578-06bfe900-2369-11ea-925b-683c2121a5a3.png">

[RealmBindingError.zip](https://github.com/realm/realm-dotnet/files/3989480/RealmBindingError.zip)
 a simple project

**Comment by fealebenpae** [comment]
I can confirm this is a bug. Our module weaver does not correctly add references to `List<T>` in UWP assemblies. We should fix this, but in the mean time you should be able to work around this if you create a .NET Standard 2.0 class library to hold your `RealmObject` model classes and reference it in your UWP application.

**Comment by denizcan** [comment]
Thanks, with .NET Standard 2.0 class library as a class holder it works as intended..

**Comment by LaPeste** [comment]
The
