### ISSUE TITLE
Windows 10 Realm at path X already opened with different schema version

### ISSUE THREAD

**Issue by chalcosoma** [realm/realm-dotnet#1940]
Hello! I want to make the code ready if I need to migrate the database, using a version variable to check if it needs to be migrated but I cannot set the Realm instance with the new schemaVersion. 
I'm getting a "realm at path already opened with different schema version" exception.
I don't know if it is related to #1668 
More details below. Thanks in advance.

## Goals
I'm trying to check if the realm schemaVersion is older than current and migrate database if so.

## Expected Results
Migrate the old database and get a new realm instance with the new schemaVersion.

## Actual Results
Exception: realm at path already opened with different schema version

## Steps to Reproduce
Run the sample code.

## Code Sample
`
public const ulong FIRST_VERSION = 1;
public static Realm CreateRealmInstance()
{
    Realm oldRealm;
    ulong oldVersion = FIRST_VERSION;

// The value of this variable is 2
    ulong newVersion = (ulong)Properties.Settings.Default["DatabaseVersion"];

    try
    {
        oldRealm = Realm.GetInstance();
        oldVersion = oldRealm.Config.SchemaVersion;
    }
    catch (Exception e)
    {
        throw new Exception(e.Message);
    }

    var configNew = new RealmConfiguration
    {
        SchemaVersion = newVersion,
        MigrationCallback = (migration, oldSchemaVersion) =>
        {
            if (oldSchemaVersion < newVersion)
            {
                MigrateDatabase();
                
            }
            oldRealm.Dispose();
        },
        ShouldCompactOnLaunch = (totalBytes, usedBytes) =>
        {
            ulong oneHundredMB = 100 * 1024 * 1024;
            return totalBytes > oneHundredMB && (double)usedBytes / totalBytes < 0.5;
        }
    };

    try
    {
// The exception happens on this line
        Realm realmInstance = Realm.GetInstance(configNew);

        return realmInstance;
    }
    catch (Exception e)
    {
        throw new Exception(e.Message);
    }
}
`

## Version of Realm and Tooling
- Flavor:
  - [X] Self-Hosted
- OS & Version: Windows 10 Pro 1909
- SDK Version: 4.2.0

**Comment by fealebenpae** [comment]
If you run `Realm.GetInstance()` for the same realm on the same thread multiple times you will get the same instance, which is what this error means. You can either open the new realm in a second thread (the realm instance cache is thread-local), or you can set the [`RealmConfigurationBase.EnableCache`](https://github.com/realm/realm-dotnet/blob/1d474a891e1449f7c07be5745d676ec9c8c1605d/Realm/Realm/Configurations/RealmConfigurationBase.cs#L54) property on the second configuration with reflection (it's not a publicly-visible property).

That said, `RealmConfigurationBase.SchemaVersion` isn't updated with the actual schema version on disk once it opens a realm. Perhaps it'll be a good idea to expose a `Realm.SchemaVersion` property for that - feel free to open a separate issue if you'd like this done.

In any case, you don't need to check the old schema version to implement conditional migration - you should always set the schema version and migration callback on the realm configuration and Realm will only execute the migration if the schema version in the configuration differs from the schema version on disk.

I hope this helps.

**Comment by chalcosoma** [comment]
Hi again! Thank you!

I didn't understand correctly what do I need to manage database migration. How do I migrate the database using schemaVersion? I read the Realm documentation but I still don't know how do I do. Could you show me an example, please? Is it okay to ask here or do I should ask in the forum or stackoverflow?

**Comment by peppy** [comment]
@chalcosoma your code is over-complicating the situation. as mentioned above, `MigrationCallback` is only fired *if* a migration is required. so your code above, should be replaced (in full) by:

```csharp
var configNew = new RealmConfiguration
{
    SchemaVersion = newVersion,
    MigrationCallback = (migration, oldSchemaVersion) =>
    {
        MigrateDatabase();
    },
    ShouldCompactOnLaunch = (totalBytes, usedBytes) =>
    {
        ulong oneHundredMB = 100 * 1024 * 1024;
        return totalBytes > oneHundredMB && (double)usedBytes / totalBytes < 0.5;
    }
};

try
{
```

your `MigrateDatabase` method will be called once if the schema is not matching the correct latest version. You can use the `oldSchemaVersion` and `newVersion` potentially as arguments to that method and then decide how to proceed with the migration.
