### ISSUE TITLE
Nullable reference types

### ISSUE THREAD

**Issue by charlesroddie** [realm/realm-dotnet#1943]
.Net can distinguish nullable and non-nullable objects, with libraries expected to add support by Nov when .Net 5 ships. https://devblogs.microsoft.com/dotnet/embracing-nullable-reference-types/

It is a huge benefit to users to have nullable and non-nullable types separated. What work will realm-dotnet need to do to support this and are there any plans?

```csharp
public class Dog : RealmObject
{
    public string Name { get; set; }
    public int Age { get; set; }
    public Person? Owner { get; set; }
}
```

**Comment by fealebenpae** [comment]
We definitely plan to add support for nullable reference types, but we don't have a set timeline just yet.

**Comment by charlesroddie** [comment]
Currently you can use nullable types in RealmObject definitions:
```csharp
public class Dog : RealmObject
{
    // Need to preserve a parameteressless contstructor so needs a default value.
    // Syntax matching https://github.com/Fody/Fody/pull/801
    public string Name { get; set; } = null!
    public int Age { get; set; }
    public Person? Owner { get; set; }
}
```
They get ignored by Realm but don't cause any problems and are still useful.

**Comment by J-Swift** [comment]
How about now? : D

(you guys do a great job btw)

**Comment by nirinchev** [comment]
Hey Jimmy, thanks for the kind words! We're actively working on a project to take advantage of the new roslyn source generators for our model declarations. While the first iteration of the feature will not add support for nullable reference types, we have it as a follow-up task. So again, while we don't have any timelines we can report, we're getting closer!

**Comment by papafe** [comment]
We're going to support nullability annotations within the new source generated models in #2982, so I'm going to close this as a duplicate
