### ISSUE TITLE
[Docs] Link to realm-dotnet is unconvenient

### ISSUE THREAD

**Issue by FoggyFinder** [realm/realm-dotnet#1948]
To reproduce:

0. Open https://realm.io/docs
1. Select `.Net` that leads `https://realm.io/docs/dotnet/latest`

![_link](https://user-images.githubusercontent.com/16510738/73646617-80decf80-4682-11ea-9f14-f23cb540c86e.jpg)

So api links look like:

https://realm.io/docs/dotnet/api/reference/Realms.RealmObject.html

that is invalid and kind of annoying.

Suggestion: change link from `https://realm.io/docs/dotnet/latest` to `https://realm.io/docs/dotnet/latest/`. Then version will be applied.

**Comment by bmunkholm** [comment]
Thanks for reporting this. In reproducing I'm not sure where you find the "So api links look like: ...". 
Where exactly do you find a link that doesn't work?

**Comment by FoggyFinder** [comment]
All over the page since references are relative:
`<a href="api/reference/Realms.RealmObject.html">`

![_sampleLink](https://user-images.githubusercontent.com/16510738/73649783-40cf1b00-4689-11ea-825d-7e9d52efb746.jpg)

**Comment by bmunkholm** [comment]
Ahh, yeah that does not look good! Thanks - it's fixed now and will likely be deployed soon.
Until then if you click the left menu-bar on the ".NET" you will get the correct links.
