### ISSUE TITLE
Fix clash between IOS Wrappers build and (unofficial) Windows wrappers build

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#195]
The IOS wrappers build downloads headers put into `wrappers/core/include/realm`

The Windows wrappers build directly accesses headers from the adjacent core. We need to ensure that we only ever have a core that aligns with the version being used in the main `Makefile` for iOS and Android, or we have a separate directory for headers used by the Windows wrappers.

This causes the build to fail with `transact_log.hpp`.

We need to discuss how to fix this - may be possible just with project tweaks but this seems a bit indeterminate. If we're using copied headers, it seems safer to _firewall_ off the Windows Wrappers build as well by **not** referring to realm-core.

**Comment by fealebenpae** [comment]
Closed in #1061
