### ISSUE TITLE
Why RealmObject

### ISSUE THREAD

**Issue by mgwalm** [realm/realm-dotnet#1957]
Ive just looked at this and i see an immediate breaking issue. 

All my objects need to derive from RealmObject. Seeing i use the same data objects (the exact same assembly) at all layers of my application it means i need to cary a reference to Realm at all layers of my application.

I hope you understand what i mean?

**Comment by fealebenpae** [comment]
Unlike traditional ORMs, Realm doesn't serialize data back and forth between some data store and POCO models. Realm objects are handles around entries in the underlying database, which has both pros and cons - changes are reflected immediately and automatically, all objects are observable, but there are restrictions such as thread affinity and the need to always subclass from `RealmObject`.

A workaround would be to use [AutoMapper](https://automapper.org) to convert between the `RealmObject` models and POCO models without other dependencies. However, Realm doesn't work well in an overly-abstracted application that depends on something like the Repository pattern - you could make it work, but it would be clunky, and you would lose nearly all the benefits Realm gives you.

**Comment by VagueGit** [comment]
We use a layered architecture and map Realm objects onto POCOs. It actually works well but you must be selective in the classes and properties you map, so object mappers may not be a good fit.

The value to us in Realm is syncing relational objects and the Realm team shouldn't underestimate the value of this feature. For those of us who use a layered architecture, 'liveness' is a -ive, not a +ive.

**Comment by fealebenpae** [comment]
Have you tried defining interfaces for your models instead? That way other layers in your app work only with the interfaces and don't need to add a dependency on the Realm package.

It's exceedingly unlikely we'll ever add support for using POCOs like Entity Framework, however.
