### ISSUE TITLE
Upgrade from 4.2.0 to 4.3.0 throws Metadata Realm encryption was specified, but no encryption key was provided

### ISSUE THREAD

**Issue by VagueGit** [realm/realm-dotnet#1960]
We don't use encryption. This works with Realm 4.2.0
```
Credentials credentials = Credentials.UsernamePassword(userName.Trim(), password.Trim(), createUser);
Uri authURI = new Uri($"https://{server}");
try
{
    realmUser = await User.LoginAsync(credentials, authURI);
}
```
With Realm 4.3.0 the line `realmUser = await User.LoginAsync(credentials, authURI);` throws the exception

> Metadata Realm encryption was specified, but no encryption key was provided.
The stacktrace

>  at Realms.NativeException.ThrowIfNecessary(Func`2 overrider)
>    at Realms.Sync.SharedRealmHandleExtensions.Configure(Nullable`1 userPersistenceMode, Byte[] encryptionKey, Boolean resetMetadataOnError, String basePath)
>    at Realms.Sync.SharedRealmHandleExtensions.DoInitialFileSystemConfiguration()
>    at Realms.Sync.User.<LoginAsync>d__4.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at Wibble.Services.DataService.<LoginAsync>d__12.MoveNext() in C:\Repos\FSL\Wibble\Services\DataService.cs:line 89
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at UUWP.ViewModels.SetupWizard1PageViewModel.<LogInAsync>d__49.MoveNext() in C:\Repos\FSL\UUWP\ViewModels\SetupWizard1PageViewModel.cs:line 80
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at UUWP.Views.SetupWizard1Page.<LoginAsync>d__5.MoveNext() in C:\Repos\FSL\UUWP\Views\SetupWizard1Page.xaml.cs:line 56

We don't use encryption. I didn't see anything in the release notes about this being a breaking change.

**Comment by fealebenpae** [comment]
The user metadata for logged-in users (usernames, server addresses, UUIDs) is encrypted by default - this is unrelated from whether the realms you use are encrypted or not. It seems this is related to the same underlying problem as https://github.com/realm/realm-dotnet/issues/1956.
