### ISSUE TITLE
global_notifier_cs.cpp:88: [realm-core-5.23.3] Unhandled exception in GlobalNotifier

### ISSUE THREAD

**Issue by hariomenkel** [realm/realm-dotnet#1961]
## Goals

I'm trying to set up a Global Notifier to handle Push Notifications for my App. My App aims to send push notifications to the devices of the user at a time the user defined. It works fine but from time to time (maximum after an hour) the application handling the notifications crashes with the following error:

ERROR: Connection[1]: Reading failed: Premature end of input
Connection[1]: Connection closed due to error
C:\jenkins\workspace\realm_realm-dotnet_PR\wrappers\src\global_notifier_cs.cpp:88: [realm-core-5.23.3] Unhandled GlobalNotifier runtime error
<backtrace not supported on this platform>!!! IMPORTANT: Please sind this log and info about Realm SDK version and other relevant reproduction info to help@realm.io

## Expected Results

GlobalNotifier shouldn't crash occasionally

## Actual Results

Crashes

## Steps to Reproduce

Set up a GlobalNotifier, wait for maximum an hour, crashes with the mentioned error

## Code Sample

Code has been shared in ticket 5414

## Version of Realm and Tooling

- Realm Object Server Version: ? 3.28.4
- Flavor:
  - [X] Realm Cloud
  - [ ] Self-Hosted
- Server OS & Version: ? Cloud
- Client SDK Version: 4.3.0
- Client OS & Version: Windows 10

**Comment by nirinchev** [comment]
That code will be removed as part of the MongoDB Realm effort.
