### ISSUE TITLE
Xamarin.Forms iOS app crashes on startup on device when nuget package (v4.3.0) added

### ISSUE THREAD

**Issue by jackv24** [realm/realm-dotnet#1964]
## Goals

Trying to launch my iOS app that uses Realm. It launches fine using the iOS simulator and on Android devices, but on an iOS device it crashes immediately.

## Expected Results

App launches without error.

## Actual Results

App crashes immediately. The following is output in Visual Studio:

```
Launched application 'com.jackvine.ComicWrap' on 'Jack???s iPad' with pid 901
Xamarin.Hosting: Process '901' exited.
Application 'com.jackvine.ComicWrap' terminated.
dyld: Library not loaded: @rpath/realm-wrappers.framework/realm-wrappers
  Referenced from: /private/var/containers/Bundle/Application/0D9BDF2D-966D-49D5-9540-7885916AEE27/ComicWrap.iOS.app/ComicWrap.iOS
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/0D9BDF2D-966D-49D5-9540-7885916AEE27/ComicWrap.iOS.app/Frameworks/realm-wrappers.framework/realm-wrappers: code signature invalid for '/private/var/containers/Bundle/Application/0D9BDF2D-966D-49D5-9540-7885916AEE27/ComicWrap.iOS.app/Frameworks/realm-wrappers.framework/realm-wrappers'
	/private/var/containers/Bundle/Application/0D9BDF2D-966D-49D5-9540-7885916AEE27/ComicWrap.iOS.app/Frameworks/realm-wrappers.framework/realm-wrappers: stat() failed with errno=1
```

## Steps to Reproduce

1. Create new Xamarin.Forms app with Xamarin.Essentials v1.5.0 & Xamarin.Forms v4.5.0.356
2. Install latest realm packages for all projects (v4.3.0)
3. Build and run on iOS device (must be on a real device, crash does not happen on simulator)
4. Observe app crashing immediately

## Code Sample

This happens with a blank project, but for reference my project repo is [here](https://github.com/jackv24/ComicWrap).

## Version of Realm and Tooling

- Client SDK Version: v4.3.0
- Client OS & Version: iOS 13.3.1

- Xamarin.Forms Version: v4.5.0.356
- Xamarin.Essentials Version: v1.5.0

**Comment by fealebenpae** [comment]
It looks like Visual Studio isn't signing the framework properly. What's your Visual Studio version?

I found a similar issue reported here: https://github.com/xamarin/xamarin-macios/issues/5624. Perhaps the workaround there is applicable in your case as well?

**Comment by jackv24** [comment]
Thanks, I'll try that workaround later!

I get this issue both when using Visual Studio on Windows connected to a Mac over LAN, and also when using Visual Studio for Mac.

Visual Studio Windows:

    Microsoft Visual Studio Community 2019
    Version 16.4.5
    VisualStudio.16.Release/16.4.5+29806.167
    Microsoft .NET Framework
    Version 4.8.03752

Visual Studio for Mac:

    Community Ver.
    Version 8.4.7 (build 17)

**Comment by fealebenpae** [comment]
Can you try to add `/realm-wrappers` to the path? `realm-wrappers.framework` is a folder and inside it the actual binary is `realm-wrappers`: `$(ProjectDir)/$(AppBundleDir)/Frameworks/realm-wrappers.framework/realm-wrappers`. I think `codesign` should work with just the folder path, but I'm not sure.

If you're still getting this, can you run `codesign -d -vvvv` against `realm-wrappers.framework/realm-wrappers` in your app bundle? Visual Studio should be signing this with your Developer identity, same as the app itself.

**Comment by jackv24** [comment]
Still not working unfortunately. I ran that codesign command and got the following output:

```
jackv@Jacks-Mac-mini realm-wrappers.framework % codesign -d -vvvv realm-wrappers
Executable=/Users/jackv/Documents/Development/ComicWrap/ComicWrap/ComicWrap.iOS/bin/iPhone/Debug/device-builds/ipad7.3-13.3.1/ComicWrap.iOS.app/Frameworks/realm-wrappers.framework/realm-wrappers
Identifier=io.realm.wrappers
Format=bundle with Mach-O thin (arm64)
CodeDirectory v=20400 size=48853 flags=0x0(none) hashes=1520+3 location=embedded
VersionPlatform=2
VersionMin=524288
VersionSDK=852480
Hash type=sha256 size=32
CandidateCDHash sha1=d6a1e966361f6863884f72299c30664004997d74
CandidateCDHashFull sha1=d6a1e966361f6863884f72299c30664004997d74
CandidateCDHash sha256=1a3622c22d7dbe3d6e789cade6dd6db0b0687c83
CandidateCDHashFull sha256=1a3622c22d7dbe3d6e789cade6dd6db0b0687c838c7bcde813405917e94daee8
Hash choices=sha1,sha256
CMSDigest=513dcf7a819322b1ce8787c1aa1c757c057d4f7ce6731f8d53bd12793ee7698b
CMSDigestType=2
Executable Segment base=0
Executable Segment limit=5554176
Executable Segment flags=0x0
Page size=4096
CDHash=1a3622c22d7dbe3d6e789cade6dd6db0b0687c83
Signature size=4823
Authority=Apple Development: jackv_24@yahoo.com.au (69L3G34W56)
Authority=Apple Worldwide Developer Relations Certification Authority
Authority=Apple Root CA
Signed Time=7 Mar 2020 at 9:35:18 am
Info.plist entries=21
TeamIdentifier=S2385ZU257
Sealed Resources version=2 rules=10 files=0
Internal requirements count=1 size=192
```

The Apple Development account seems correct.

One thing to note: I am using free provisioning (but this works fine without Realm installed)

**Comment by jackv24** [comment]
Seems like it's an issue with using a free developer account with iOS 13.3.1, according the the answer [here](https://stackoverflow.com/questions/60015309/running-ios-apps-causes-runtime-error-for-frameworks-code-signature-invalid) from Adriano Bucella

**Comment by fealebenpae** [comment]
Ah, that's very unfortunate - do you think you might try this with a paid developer account, or maybe a device running another iOS version? We haven't changed anything when it comes to how the framework is built since the 4.0 release so I can't think of what else might be happening.

**Comment by jackv24** [comment]
I'll probably have to wait for iOS 13.4 and see if it's fixed. Don't have another iOS device unfortunately, nor a paid account.

**Comment by jackv24** [comment]
Now that iOS 13.4 has been released I can confirm it is fixed!
