### ISSUE TITLE
[Feature Request] Support running Realm in the Xamarin.Forms Previewer

### ISSUE THREAD

**Issue by spellizzari** [realm/realm-dotnet#1966]
## Goals

I want to be able to run Realm in design mode for the Xamarin.Forms Previewer (I create an in-memory database with fake data to populate my view model). The problem is that Xamarin.Forms isolates each DLL built and referenced in a cache folder and Realm fails to load the native wrapper DLL (it needs to load the win-x64 version inside the Previewer). If I P/Invoke LoadLibrary and call it before initializing Realm in my ViewModel then it works fine.

## Expected Results

Running Realm inside Xamarin.Forms Previewer should work out of the box without having to load the native wrapper manually.

## Actual Results

The first call to Realm.GetInstance throws an exception (TypeInitializerException) saying that realm-wrapper.dll could not be found.

**Comment by dgerding** [comment]
This would be appreciated 👍
