### ISSUE TITLE
Realm DB Size increasing very large, can't online compact in API Services.

### ISSUE THREAD

**Issue by tricuongle** [realm/realm-dotnet#1968]
I have API web services use Realm DB. (I'm new user with Realm database.)
I only update data on Realm database (don't writing more records)
It increased to 1 GB data but if I compact it, it only take 64 KB data is used. 
I know it is transaction logs problem, but API services can't Re-Launch many times to solve it. 
I can't know when I develop program base on Realm DB. 

After read on many forum but no solution for me. 
I don't want to re-writing all program because issue. 

## Goals
I want to save with real data on Realm.

I use ShouldCompactOnLaunch, Realm.Compact but can't use if program run 24/7. 
## Expected Results

1. Small DB size. 
2. Compact write data to DB.
3. Any way to disable database transaction logs.

## Version of Realm and Tooling

- Realm Object Server Version: 4.2.0
- Flavor:
  - [ ] Realm Cloud
  - [X] Self-Hosted
- Server OS & Version: CentOS 6

**Comment by nirinchev** [comment]
Do you dispose of Realms you open on background threads?

**Comment by tricuongle** [comment]
Dear @nirinchev  

Yes, when I use "dispose" the Database Size is not increase high, but another problem:
1. Performan slow down. 
2. Error Message = "Cannot access a closed Realm.\r\nObject name: 'Realms.Realm'."
When 2 requests go to Server in the same time. 
Could you suggest any Idead?
Thanks

**Comment by nirinchev** [comment]
You need to open a Realm and dispose of it on every request - these happen on random threads, so you can't reuse the same Realm instance. Your code should look something like:

```csharp
public async Task<MyResponse>()
{
    await DoStuff();

    using (var realm = Realm.GetInstance())
    {
        // use the Realm - don't use await while the Realm is open
    }

    await DoSomeMoreStuff();
    return response;
}
```

**Comment by tricuongle** [comment]
Thank you @nirinchev, it work!
:) Nice Day.
