### ISSUE TITLE
RealmException "Access to invalidated List object"

### ISSUE THREAD

**Issue by robertmiles3** [realm/realm-dotnet#1971]
Maybe I'm using bindings wrong, in which case I'd love some tips given I can't find but maybe 1 or 2 examples out in the wild. I have a `Folder` model with an `IList<Item> Items` inside it. I want to be able to view the list of folders in a `ListView`, tap into a folder to see its details and items attached, then pop back to the main list and delete the folder if I wish. However, I'm getting the `Access to invalidated List object` exception every time.

## Expected Results

Be able to delete the folder after coming back to the main `ListView`

## Actual Results

RealmException "Access to invalidated List object"

## Steps to Reproduce

1. Start repro project in simulator (I was using iPhone 11 iOS 13.3)
2. Tap into a folder ("Folder 1" for example)
3. Navigate back to the main view
4. Swipe on "Folder 1" and tap the "Delete" context command

## Code Sample

See repro at [https://github.com/robertmiles3/realmcrash](https://github.com/robertmiles3/realmcrash)

## Version of Realm and Tooling

Realm NuGet: 4.3.0

**Comment by robertmiles3** [comment]
May I humbly request an update on this? It's been 19 days.

**Comment by fealebenpae** [comment]
Hey @robertmiles3, sorry, I haven't had access to an iOS device where I can debug your repro.

I don't have a good answer for this right now - what's happening is that as you navigate away from the view that's bound to Realm objects it isn't immediately torn down by Xamarin.Forms, so it still has databinding references to the realm object you're about to delete.

I don't have a way to test whether this will work, but my suggestion is to set the `Folder` property in `FolderDetailViewModel` to null just after you navigate away from the view, but before you delete the realm object. You will also need to raise the `PropertyChanged` event for the `Folder` property. This should cause Forms to disengage data binding from the realm object and not try to access it after it's been deleted.

**Comment by robertmiles3** [comment]
Thanks for the tip. Just tried it, but that doesn't work either. 

FYI, this problem is reproducible in the iOS Simulator so you don't need a physical device.

**Comment by fealebenpae** [comment]
I could try to run this on Android, if your Forms app also reproduces the same issue there?

**Comment by robertmiles3** [comment]
Can I humbly request a status update on this?

**Comment by bmunkholm** [comment]
@fealebenpae

**Comment by bmunkholm** [comment]
@robertmiles3 I know @fealebenpae has had other priorities, and is off this week. Not really too useful to you I know, but thought I would at least update you with that.

**Comment by robertmiles3** [comment]
Two months since I last asked about this. Any update? Still crashing, and I'm not aware of any workaround.

**Comment by robertmiles3** [comment]
Thanks so much for tackling this! Is there an ETA for a version with this fix?

**Comment by nirinchev** [comment]
We don't have an ETA yet, but we're actively working on a major version upgrade and we're fairly close to resolving all outstanding issues. I hope it won't be long before we can release it.

**Comment by robertmiles3** [comment]
Thanks! I'm eager to get that next version and start also testing the sync with MongoDB Realm.

**Comment by nirinchev** [comment]
Syncing with MongoDB Realm will take a bit longer, unfortunately. The next major version will be an upgrade of the core Realm database and won't work with MongoDB Realm yet. The MongoDB Realm capable version of the .NET SDK will be released as a beta later this fall, but you can keep track of our progress here on GitHub and I can share some early prerelease packages once we have _something_ syncing.
