### ISSUE TITLE
System.InvalidCastException: Unable to cast object of type 'EventLoop' to type 'ShouldCompactDelegate'.

### ISSUE THREAD

**Issue by scarabdesign** [realm/realm-dotnet#1987]
Our project is Xamarin Universal Windows Platform (UWP)
Running Realm 4.3.0 (from NuGet package)
If a migration is required, it seems realm config will either run the migration callback or a compact on launch, but we are getting an error when we try both in the same config.

We are only running Realm instances in the clients, not syncing to a server (yet). Our Xamarin project is running UWP, Android and iOS versions. UWP is the only one showing this issue.

## Goals
We need to be able to run both a migration and a compact if a migration is required.

## Expected Results
We expect to run both without exception, both compacting the db if needed and running the migration callback when migration is needed.

## Actual Results
Getting the following error:
```
System.InvalidCastException: Unable to cast object of type 'EventLoop' to type 'ShouldCompactDelegate'.
	at Realms.RealmConfiguration.ShouldCompactOnLaunchCallback(IntPtr delegatePtr, UInt64 totalSize, UInt64 dataSize)
	at Realms.SharedRealmHandle.NativeMethods.open(Configuration configuration, SchemaObject[] objects, Int32 objects_length, SchemaProperty[] properties, Byte[] encryptionKey, NativeException& ex)
	at Realms.SharedRealmHandle.Open(Configuration configuration, RealmSchema schema, Byte[] encryptionKey)
	at Realms.RealmConfiguration.CreateRealm(RealmSchema schema)at ERPXamarin.Models.AppModel.CompactRealm()
```

## Steps to Reproduce
The code sample below will catch an error if a migration is required. 

I'm testing the migration by removing our application from the client, reverting back to an earlier version of our project which had Realm 4.2.0, running and installing, then upgrading to the latest version of our project which has Realm 4.3.0. The SchemaVersion is increased by 12.

If I remove `ShouldCompactOnLaunch` then `MigrationCallback` is called and the migration is successful. If I remove `MigrationCallback`, then `ShouldCompactOnLaunch` is called and does not result in an error. If both are included (if a migration is required) then `ShouldCompactOnLaunch` callback is run and then the error pops after that and `MigrationCallback` is never called.

## Code Sample
```
var config = new RealmConfiguration(RealmConfiguration.DefaultRealmName)
{
	SchemaVersion = 20,
	MigrationCallback = (Migration migration, ulong oldVersion) =>
	{
		//Do stuff here
	},
	ShouldCompactOnLaunch = (ulong totalBytes, ulong bytesUsed) =>
	{
		return bytesUsed/totalBytes < 0.9;
	}
};

try
{
	var realm = Realm.GetInstance(config);
	realm.Dispose();
}
catch (Exception e)
{
	//Error here: System.InvalidCastException
}
```

## Version of Realm and Tooling

- Realm Object Server Version: (?)
- Flavor:
  - [ ] Realm Cloud
  - [x] Self-Hosted
- Server OS & Version: Only using Realm locally
- Client SDK Version: 4.3.0 (?)
- Client OS & Version: Windows 10, version 1903

**Comment by toXel** [comment]
@scarabdesign Have you found a solution for the problem? I'm also fighting with it...

**Comment by scarabdesign** [comment]
> @scarabdesign Have you found a solution for the problem? I'm also fighting with it...

Nope. Had to choose one or the other. If the migration is needed at launch, we migrate, otherwise we compact. So, if a migration happened on the last app launch, a compact will happen on the next launch.

**Comment by toXel** [comment]
@scarabdesign Ah nice idea. How do you check if a migration is needed in the compact delegate?

**Comment by nirinchev** [comment]
I was unable to repro this - I pushed a unit test that attempts to open a Realm while setting both the compact delegate and the migration callback and it passes on iOS and Windows: https://github.com/realm/realm-dotnet/blob/ni/migration-callback-repro/Tests/Realm.Tests/Database/MigrationTests.cs#L161-L176

If that's still a problem for you, can you try to isolate a small repro case or give me pointers on how the unit test code differs from what you're doing?
