### ISSUE TITLE
Integration test GetInstanceShouldThrowIfFileIsLocked fails to detect locked files.

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#199]
integration test GetInstanceShouldThrowIfFileIsLocked is not working - never gets a locked file exception despite whatever we do to try to generate a locked file. It is unclear if this is a failure of being able to lock files on IOS vs other platforms.

In practice, this may never be a mobile issue. if that is the case, it should be downgraded as an issue.

**Comment by papafe** [comment]
This test does not exist anymore
