### ISSUE TITLE
Compiling .NET Core wrappers on Linux

### ISSUE THREAD

**Issue by Fixer040** [realm/realm-dotnet#1992]
## Goals
To successfully build the .NET Core wrappers on a Linux machine as described by the documentation. Is there some way to build without Realm Sync? I'm not interested in that feature.

## Expected Results
Successful build.

## Actual Results
Build script fails to download realm-sync archive (looking for realm-sync-Debug-v4.9.5-Linux-devel). Realm core seems to download normally.

-- Downloading realm-sync...
-- Uncompressing realm-sync...
CMake Error at CMakeLists.txt:157 (include):
  include could not find load file:

    /root/mongorealm/realm-dotnet-release-4.3.0/wrappers/cmake-build-debug/realm-sync-Debug-v4.9.5-Linux-devel/lib/cmake/realm/realm-sync-config.cmake

-- Configuring incomplete, errors occurred!

## Steps to Reproduce
Follow the steps at https://github.com/realm/realm-dotnet/blob/release/4.3.0/wrappers/README.md using  Debian 10 with all the prerequisites installed.

## Version of Realm and Tooling
Realm dotnet 4.3.0
Realm core 5.23.8
Realm sync 4.9.5
- Realm Object Server Version: ? (you can see this as well in Studio once connected to a Realm instance) 
- Flavor:
  - [ ] Realm Cloud
  - [X] Self-Hosted
- Server OS & Version: Debian 10 x64
- Client SDK Version: ?
- Client OS & Version: Debian 10 x64

**Comment by fealebenpae** [comment]
Hey @Fixer040,

We only provide realm-sync binaries for Linux in Release mode, so the build should work as long as you don't build in Debug. You can also edit the `CMakeLists.txt` file to always use Release builds of realm-core and realm-sync if you need to build the wrappers themselves in Debug.

**Comment by Fixer040** [comment]
Hello, thanks, switching to Release fixed the issue for me.
