### ISSUE TITLE
Error when run system on Linux Ubuntu - Raspberry Pi4 - ARM64

### ISSUE THREAD

**Issue by tricuongle** [realm/realm-dotnet#2000]
When apply on Ubuntu 18.04 - Raspberry PI4 error happen
but I build and apply project on Window, Linux - Centos 7 - 64x is OK.

crit: Microsoft.AspNetCore.Hosting.Diagnostics[6]
      Application startup exception
System.TypeInitializationException: The type initializer for 'Realms.SharedRealmHandle' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'realm-wrappers' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: librealm-wrappers: cannot open shared object file: No such file or directory

## Steps to Reproduce
To Solve Problem I tried:
- I copy file "realm-wrappers.dll" to raspberry but can't solve problem.
- Update realm V4.2.0 to V4.3.0 but still error.

## Code Sample
At my code: 

        public static void CreateDatabase(RealmConfiguration configuration)
        {

            Configuration = configuration;
            Realm realm = Realm.GetInstance(configuration);
            realm.Dispose();
        }

## Version of Realm and Tooling

- Realm Object Server Version: ? (you can see this as well in Studio once connected to a Realm instance) 
- Flavor:
  - [ ] Realm Cloud
  - [X ] Self-Hosted
- Server OS & Version: ? (e.g. CentOS 6)
  Ubuntu 18.04 - Rapberry PI4 - ARM64

**Comment by nirinchev** [comment]
The .NET SDK doesn't support Linux on Arm64 yet.

**Comment by tricuongle** [comment]
Thank you nirinchev, so sad to know this.
Is it support for ARM32? (Ubuntu 32 bit for Raspberry)

**Comment by nirinchev** [comment]
No, we only support x86/x64 architectures for Linux. We do plan to add RPi support in the future, but don't have a timeline for it yet.

**Comment by tricuongle** [comment]
Do you have any solution for minimal modification for use on Raspberry? 
It will takes a lot of effort to rewrite the data management of my project.

**Comment by nirinchev** [comment]
No, we don't build the native binaries for RPi.

**Comment by tricuongle** [comment]
It's just few SBC/Mobile devices use X86-64. 
Realm is a great DB. But I have to change the other database (maybe MongoDB). - So Sad. :(
Thanks your support. @nirinchev

**Comment by nirinchev** [comment]
We support the ARM architecture for iOS, Android, and UWP. We haven't prioritized supporting it for Linux, because most deployments run on x86/x64. As I said though, we're totally planning to add support in the future, just have a few more pressing things to attend to first.

**Comment by tricuongle** [comment]
So is it support for Window IOT?
If it can, it will be the great new.

**Comment by tricuongle** [comment]
Install and check in Windows10 IoT, Universal Window, ARM - Raspberry PI3 B+. 
Result: Can't work same in Linux Arm Chipset.

**Comment by nirinchev** [comment]
I don't understand - did it work or not? Note that for Windows, we support ARM and not ARM64.

**Comment by tricuongle** [comment]
So sorry, I don't say it clearly. 
- I Test on ARM64. So I will test on ARM. => Thanks your note.
