### ISSUE TITLE
Where do (All<T>, Where, OrderBy, Last) Execute?

### ISSUE THREAD

**Issue by MhAllan** [realm/realm-dotnet#2004]
Could someone please help me analyse how is this query executed. Documentation for .Net is very poor, and I want to know what exactly gets executed in memory and what is not. 

```
_db.All<Users>().Where(x => x.BookId == "123").OrderBy(x => x.Id).Last()
```
Having Id and BookId indexed:

- Does All<T>() fetch records to memory?
- Does OrderBy() work in memory? It brings all records to memory then order them?
- Does Last() brings them in memory then get Last?

**Comment by nirinchev** [comment]
Thanks for the input - we're working on revamping the .NET docs, but don't have an ETA for when the new docs will be available. 

That being said, In the [existing .NET docs](https://realm.io/docs/dotnet/latest/#more-query-examples) query section, it is written:

> This is standard LINQ implementation - you get an object representing the query. The query doesn’t do anything until you make a further call that needs to iterate or count the results.

And a little later, there's:

> Objects are not copied - you get a list of references to the matching objects, and you work directly with the original objects that match your query.

To summarize - when working with `IQueryable<T>` you're building a query that will get executed by the database when the results are enumerated (or `First`, `Last`, `Single`, or `ElementAt` are called). When the query is realized by the database, you get references to objects. The database records are never copied in memory. Instead, when you access a property, the .NET SDK fetches the value from the database and returns the result.

In your example, `_db.All<Users>().Where(x => x.BookId == "123").OrderBy(x => x.Id)` gets executed by the database. When you call `.Last()`, you get a `RealmObject` instance that points to the database record, but hasn't copied any data from it. When you access its properties, by doing e.g. `user.Name`, the property getter will read the value from the database and return it. This is explained in the [Auto Updating Objects](https://realm.io/docs/dotnet/latest/#auto-updating-objects) section of the docs.

Hope this clarifies things.

**Comment by MhAllan** [comment]
Very clear, thank you so much
