### ISSUE TITLE
[Bug] Realm accessed from incorrect thread in UWP app

### ISSUE THREAD

**Issue by tipa** [realm/realm-dotnet#2045]
## Goals
Initialize a "main thread" realm instance in my app constructor and use it across my app (in the main thread).
There were no issues with that code until the NuGet version 5.x - it worked fine in 4.3.0.
Having a static realm instance like this makes it much easier for me to work with Realm in various app pages as well as in the app background task

## Expected Results
No crash

## Actual Results
When trying to access the realm instance:
`System.Exception: 'Realm accessed from incorrect thread.'`

## Steps to Reproduce
`Realm.GetInstance()` in app constructor
`realm.Write()` later on in MainPage

## Code Sample
[RealmCrash.zip](https://github.com/realm/realm-dotnet/files/5317134/RealmCrash.zip)

## Version of Realm and Tooling
- Client SDK Version: 5.1.1

**Comment by nirinchev** [comment]
That's an annoying implementation detail in the way UWP/WPF installs the synchronization context on the main thread. We special cased it for WPF, but seems like we'll need it for UWP too.

**Comment by nirinchev** [comment]
This has been fixed and will be released with the next Realm version. If you want to give it a shot, check out the [nightly builds](https://github.com/realm/realm-dotnet#nightly-builds) section of the readme on how to get the latest build from master (I just merged the PR, so it should be up in the packages section in ~20-30 minutes).

**Comment by tipa** [comment]
Thanks for the quick fix!

**Comment by nirinchev** [comment]
No worries, thanks for the repro - that made it super straightforward to repro and test the fix 😄
