### ISSUE TITLE
Upload release notes in NuGet package

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-dotnet#2050]
When building for release, we should update the nuget package with the release notes from the changelog.

**Comment by nirinchev** [comment]
The correct field seems to be `PackageReleaseNotes`, not `ReleaseNotes`. Additionally, we can probably see if something like [SIL.ReleaseTasks](https://github.com/sillsdev/SIL.BuildTasks/blob/master/Documentation/SIL.ReleaseTasks.md#setreleasenotesproperty-task) to generate the field from the changelog.

**Comment by nirinchev** [comment]
What's the issue that prevents us from using `SIL.ReleaseTasks`?

**Comment by LaPeste** [comment]
> [Keep a Changelog](https://keepachangelog.com/) doesn't make any recommendations in what form versions should be put in the changelog. The default for the SetReleaseNotesProperty task follows the example given on the [Keep a Changelog](https://keepachangelog.com/) website, which puts the version number in square brackets, e.g. ## [1.0.0] - 2017-06-20. However, it's possible to set the VersionRegex property to allow parsing different formats.

I don't recall why I could not get VersionRegex to work. I'll dig-in and try to remember, but in any case before going in holiday I started writing a simple MSBuild Task that extrapolates the Changelog in a new file, exactly as it's done in CI. Meaning that the logic for extracting the Changelog will be moved from the release workflow to the mentioned task and the release workflow will just read the Changelog file. That was my idea, at least.

You can take a look at WIP in the test repo:
1- [msbuild task](https://github.com/realm/test/blob/master/NugetPublishTest/MSBuildTasks/ReadTextFromFile.cs)
2- [call of msbuild task](https://github.com/realm/test/blob/47d43d220c42b7d370c5910c8438826d720503cc/NugetPublishTest/NugetPublishTest.csproj#L16) from the csproj
