### ISSUE TITLE
Deleting From RealmDB - XamarinForms ReactiveUI

### ISSUE THREAD

**Issue by draganDBL** [realm/realm-dotnet#2087]
Hello , I’m having problem when deleting from Realm, I’m using Xamarin Forms with ReactiveUI. Adding , Updating works fine , but Deleting not , I’m getting Realms.Exceptions.RealmInvalidObjectException: 'Attempted to access detached row' , I have a service class that have all methods for CRUD operations . There I’m creating instance of Realm object. My service class is singleton.

**Comment by nirinchev** [comment]
Can you share a repro case that I can run locally?

**Comment by draganDBL** [comment]
My problem is that when my app is in  background and I  remove object from server using postman,  and entering app again  OnResume() is called , there I'm doing Sync() and  Sync() is calling  Realm.Delete(Id). And  I'm getting exception I wrote.

**Comment by nirinchev** [comment]
The issue is likely related to the data binding framework trying to access an object after it has been deleted. I wrote a lengthy explanation in [this forum post](https://developer.mongodb.com/community/forums/t/deleting-from-realmdb-xamarinforms/11151/4?u=nirinchev)

**Comment by draganDBL** [comment]
Should I call that Invoke method somewhere?  Or  I need to do something else , don't understand

**Comment by nirinchev** [comment]
No, that invoke method is part of reflection-based solution that avoids this error when realm objects are used as binding context in Xamarin.Forms. We will need to provide something similar for whatever data binding engine you're using. To be able to make progress on this issue, I will need either a repro case that I can run or more information about the frameworks you're using for ReactiveUI/Databinding.

**Comment by draganDBL** [comment]
Hi ,My ItemSource is ReadOnlyObservableCollection. I'm using this.WhenActivated inside my View to bind ItemSource to the xam forms CollectionView. I'm connecting to the SourceCache(dynamic data) to listen the stream (e.g mySourceCache.Connect().Bind(out  myReadOnlyObservableCollection))  , and I'm observing everything on MainThread.

**Comment by nirinchev** [comment]
What version of Xamarin.Forms are you using? Also, how are you wiring the Realm collection change notifications to the ReadOnlyObservableCollection you're using as ItemSource?

**Comment by draganDBL** [comment]
Xamarin Forms v 4.8.0.1560 and for collection change notifications Im using this:

  RealmDbService.GetAll().SubscribeForNotifications((sender, changes, error) =>
            {
                var keys = new HashSet<string>();

                if (changes?.DeletedIndices != null)
                {
                    foreach (var index in changes.DeletedIndices)

                    {
                        var device = _ioTDevices.Keys.ElementAt(index);
                        keys.Add(device);
                    }

                    _ioTDevices.Remove(keys);
                }
                _ioTDevices.Edit(innerCache =>
                {
                    innerCache.Clear();
                    innerCache.AddOrUpdate(sender);
                });

            });

**Comment by nirinchev** [comment]
What is `_ioTDevices`? Is it a dictionary?

**Comment by draganDBL** [comment]
_ioTDevices is a SourceCache<object, string>

**Comment by nirinchev** [comment]
I don't have experience with the DynamicData API, so I'm struggling to understand what exactly is going on in that snippet. Namely, why do you call `_ioTDevices.Remove(keys)` if you're going to `Clear` the cache in the `_ioTDevices.Edit` callback? Does `Clear` not remove all elements in `_ioTDevices` anyway?

**Comment by draganDBL** [comment]
Yes I don't need _ioTDevices.Remove(keys) you are right if I'm using  Clear the cache . I  have remove that part , but still  I'm getting the  same exception .
  RealmDbService.GetAll().SubscribeForNotifications((sender, changes, error) =>
            {
                
                _ioTDevices.Edit(innerCache =>
                {
                    innerCache.Clear();
                    innerCache.AddOrUpdate(sender);
                });
                _ioTDevices.AddOrUpdate(sender);

            });
this is ok but still the same exception

**Comment by nirinchev** [comment]
It looks like to compute the change notifications, the `ObservableCache` will read data from elements in the existing collection, which will not work as those have been deleted. There are two possible solutions here:
1. Don't use `ObservableCache`. Realm collections are observable in and of themselves, so running them through `ObservableCache` doesn't really add much value.
2. Instead of calling `innerCache.AddOrUpdate(sender)`, call `innerCache.AddOrUpdate(sender.Freeze())`. This will freeze the collection at the current version, so even after deletion, the elements will be accessible. Note that this will increase the filesize and/or memory usage as Realm will now need to keep track of multiple versions of the database at the same time.

I would strongly suggest going for option 1 unless you have a use case that hasn't been demonstrated by the code snippets you've posted.

**Comment by draganDBL** [comment]
Hi , when trying to call  Frezee() than Im getting ReactiveUI unhandled exception , so  still  I didn't managed to make this fix

**Comment by nirinchev** [comment]
What is the exception that you're getting?

**Comment by draganDBL** [comment]
ReactiveUI.UnhandledErrorException: 'An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case.'

**Comment by nirinchev** [comment]
That's error message is not particularly helpful as it doesn't provide any information about the underlying error. Can you try inspecting the stack trace to see if there's anything Realm-related further down the stack or follow the error's advice and subscribe to the ThrownExceptions property and see if the error passed there is more relevant.

**Comment by draganDBL** [comment]
Hi problem I think my  my problem is  is  when listening to database changes  when calling ,
  **RealmDbService.GetAll().SubscribeForNotifications((sender, changes, error)**
need to see what is proper way to do this
