### ISSUE TITLE
Run benchmarks for more platforms

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-dotnet#2118]
Currently running them for .NET Framework, but can easily run them on Linux, macOS, maybe even mobile.

**Comment by nirinchev** [comment]
Looks like for Xamarin we'll need to use a nightly build: https://github.com/dotnet/BenchmarkDotNet/issues/1430

**Comment by papafe** [comment]
This issue will deal only with running benchmarks on Linux and macOS, I've created issue #2140 to work on mobile
