### ISSUE TITLE
Opening Realm files of format version 20 is not supported by this version of Realm

### ISSUE THREAD

**Issue by mBoyceRTI** [realm/realm-dotnet#2138]
## Goals
I am trying to build a Xamarin Forms app that will come with a pre-populated Realm DB and does not make use of the cloud or Realm Sync.

## Expected Results
The app should copy the pre-populated.realm file bundled with the app on first run to default.realm if not present.

## Actual Results
The first call to Realm.GetInstance() throws the following error:
- Opening Realm files of format version 20 is not supported by this version of Realm

This happens on my Pixel 3 running the latest version of Android and on Apple's iOS simulator

## Steps to Reproduce

First, I created the model .cs files in VS, added a few items programmatically, and ran the app. This created the initial default.realm.

I copied that to my desktop and opened it with the latest version of MongoDB Realm Studio and got the following popup:

- The Realm file stores data in an outdated format

I allowed Realm Studio to update the format then added the rest of my data (much easier in Realm Studio than in VS as C#).

I then followed the steps in the SO mentioned in the [official docs](https://realm.io/docs/dotnet/latest/#bundling-a-realm-with-an-app).

I have tried:
Saving to a name other than default.realm.
Removing and re-adding the NuGet.
Updating and Restoring NuGets.

## Code Sample

`public class Heading : RealmObject
    {
        [PrimaryKey]
        [MapTo("name")]
        public string Name { get; set; }

        [MapTo("type")]
        public string Type { get; set; }

        [MapTo("contentname")]
        public ContentObj ContentName { get; set; }

        [MapTo("children")]
        public IList<Heading>? Children { get; }

        [MapTo("parent")]
        public string? Parent { get; set; }
    }`
`public class ContentObj : RealmObject
    {
        [PrimaryKey]
        [MapTo("name")]
        public string Name { get; set; }

        [MapTo ("text")]
        public string Text { get; set; }

        [MapTo("tags")]
        public string? Tags { get; set; }

        [MapTo("checklist")]
        public string? Checklist { get; set; }

        [MapTo("myheading")]
        [Backlink(nameof(Heading.ContentName))]
        public IQueryable<Heading>? MyHeading { get; }
    }`

## Version of Realm and Tooling

- Realm Object Server Version: N/A
- Flavor: Offline
- Server OS & Version: ? N/A
- Visual Studio Pro V 8.8.3 (build 16)
- Realm NuGET v5.1.2 (Latest stable)
- Mono 6.12.0.107
- .NET Core Runtime 5.0.0 (and older)
- .NET Core 3.1 SDK 3.1.403
- Xamarin iOS 14.6.0.15
- Xcode 12.2
- Xamarin Android 11.1.0.17

**Comment by nirinchev** [comment]
This is because the latest version of Realm Studio uses a newer version of the Realm database - opening the file automatically upgrades it. You have two options:
1. Download an older version of Studio - here's a link to the 5.x line of releases: https://studio-releases.realm.io/v5.0.1
2. Upgrade to v10 of the .NET SDK, which is still in beta. It's mostly the Sync API that are in beta, so if you're not using any of them, there should be almost no difference compared to the 5.x release.

**Comment by mBoyceRTI** [comment]
I upgraded to the v10 beta and it works as expected, thanks for the quick and helpful response!
