### ISSUE TITLE
Measure added size for real apps

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#218]
Due to linker stripping, we can't estimate added size just from the size of the Realm dlls. The IOS one is currently 97MB with its many different processor bits. 

We need to measure with some sample apps how much their deployed size increased by when put on the store and downloaded, or as close to that process as we can get. This is complicated by Apple's _App Thinning_ which effectively delays the last stages of linker stripping to the download process from iTunes. We may need to put real samples up at least as far as beta testing to have reasonable results.

**Comment by kristiandupont** [comment]
## iOS
Without realm: 8.997.966 bytes
With realm: 9.916.021 bytes
Diff: 981.055 bytes

We should set up a CI job to keep these numbers up to date.
