### ISSUE TITLE
Realm Memory Leak When Get Data.

### ISSUE THREAD

**Issue by tricuongle** [realm/realm-dotnet#2184]
## Goals
We receiver feed back from some user that host server is slow and disconnect many time. 
We see Ram Overload and we check detail, it maybe memory leak. 
We stop all function, test with just very simple get data from Ream for check bigger issue. 

## Expected Results

Memory is ok.

## Actual Results

Memory none stop Increasing. 

## Steps to Reproduce

We check memory leak, and we thing it is leaking. 
Test function by function to finding where it leak => We found it in very simple function.
Test many way but can't solve. 
Finding google and issue in Realm but can't find anything like that. 

## Code Sample

Calling Function: 
 
        [HttpPost ("{id}/Measures", Name = "PostSchedules")]
        public string PostMeasure(string id, int child,  [FromBody] object value, string token)
        {
            Database.GWTokenDB.GetTokenGW(id); 
            return "{\"Result\":\"Successful\"}"; ;
        }

Action function: ( In test case it will return null - So Clone() function don't run in this test)

        public static GatewayTokenModel GetTokenGW(string gatewayId)
        {
            using (var realm = Realm.GetInstance(Configuration))
            {
                try
                {
                    var data = realm.Find<GatewayTokenModel>(gatewayId);
                    if (data != null) return data.Clone();
                    else return null;
                }
                catch (Exception ex)
                {

                }
            }
            return null;
        }

## Version of Realm and Tooling

- Realm Object Server Version: ? 5.1.2
- Flavor:
  - [ ] Realm Cloud
  - [x] Self-Hosted
- Server OS & Version: ? CentOS 6. 
- Client SDK Version: http request.
- Client OS & Version: Window 10, request http to server.

Adding Image Test Memory Leak: 
![image](https://user-images.githubusercontent.com/54373361/104357441-c6b54080-553f-11eb-91db-b3f70f7754d0.png)

Capture Information at end of test => Stop send data more and press GC Collect many times until memory don't decreasing more.
![image](https://user-images.githubusercontent.com/54373361/104357584-fbc19300-553f-11eb-8db8-67a84bda214e.png)

**Comment by nirinchev** [comment]
This looks like a bug indeed - we'll try to repro and get back with more info.

**Comment by tricuongle** [comment]
@nirinchev thank you your feedback
, and should I daily restart program and waiting your solution or the next version?

**Comment by nirinchev** [comment]
We don't have a workaround for this yet, so restarting your app is your best bet there. But we are currently looking into it, so hopefully it won't be long before a fix is released.

**Comment by tricuongle** [comment]
Thank you your answer, I hope it ok in the next release. I will create function to auto restart system.

**Comment by nirinchev** [comment]
@tricuongle this was fixed and will be in the next 10.x release. We don't plan to backport it to the 5.x line of releases, so you'll likely have to upgrade.

**Comment by tricuongle** [comment]
@nirinchev Thanks for your team's efforts to resolve the issue quickly. I'll do. Thank you.
