### ISSUE TITLE
on realm.add() add a parameter notifysubscription

### ISSUE THREAD

**Issue by CursedMun** [realm/realm-dotnet#2279]
## Goals

The main goal of this is to not notify the subscription.
## Expected Results

If the bool value is set to true then the event subscription will trigger otherwise no.

**Comment by papafe** [comment]
Hi @CursedMun, I am not sure I understood what you would like to accomplish. Can you make an example?

**Comment by CursedMun** [comment]
For example: I have the following->
```
        public class Event : RealmObject
        {
            public string EventName { get; set; }
            public DateTimeOffset Date { get; set; }
        }
            Realm.All<Event>().SubscribeForNotifications(callback);
            //This will notify the callback
            Realm.Add(new Event
            {
                EventName = "Party",
                Date = DateTimeOffset.Now
            }, update = true);
            //This doesn't
            Realm.Add(new Event
            {
                EventName = "Party",
                Date = DateTimeOffset.Now
            },update = true, NotifySubscription = false);
```
This can be useful sometimes and there is no need in dispose it every time I don't want to notify the callback

**Comment by papafe** [comment]
Hi @CursedMun, thanks for writing an example, this clarifies what you are trying to accomplish. We have added your proposal to our backlog so that we can take it into consideration when planning new features.

**Comment by DominicFrei** [comment]
@papafe @nirinchev The Core API in https://github.com/realm/realm-core/blob/master/src/realm/object-store/impl/collection_notifier.hpp#L65 would probably offer what we need here.

The Cocoa API for example:
https://github.com/realm/realm-cocoa/blob/master/Realm/RLMRealm.h#L414
and
https://github.com/realm/realm-cocoa/blob/master/RealmSwift/Realm.swift#L318

**Comment by nirinchev** [comment]
Yes, seems like something that can be done, although this may be a bit of a footgun especially in combination with databindings. If you don't notify the UI that something has changed, you may end up in inconsistent state and either visualize the wrong thing or crash the app.
