### ISSUE TITLE
Restore ability to add objects with new in transaction

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#229]
Prior to the big CoreProvider gutting, we had objects automatically register with an active write transaction on the current thread.

So for most cases (when there's only one write active in this thread) we got quick creation of objects that constructed them directly in the database.

I am fairly certain the following syntax worked.

```
using (var transaction = realm.BeginWrite())
{
    p3 = new Person { FullName = "Peter Jameson", Email = "peter@jameson.com", IsInteresting = true };
  transaction.Commit();
}
```

**Comment by nirinchev** [comment]
I feel this is not something we'd want. Objects magically being added to the Realm is not obvious and definitely counter intuitive. Does anyone feel otherwise, or should I close that one?

**Comment by AndyDentFree** [comment]
Killing issue due to majority vote
