### ISSUE TITLE
“Unable to load DLL 'realm-wrappers'” exception with Realm 10 and Windows 8.1

### ISSUE THREAD

**Issue by andlang** [realm/realm-dotnet#2298]
## Goals

I would like to use Realm 10 in a simple .NET Core CLI on Windows 8.1 in order to generate a database that I can use in apps. Everything is locally without any cloud services.

## Expected Results

Program runs without exception like it does with Realm v5.1.3.

## Actual Results

With Realm v10.1.1 I get following exception (with Realm v5.1.3 everything works as expected):

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'Realms.SharedRealmHandle' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'realm-wrappers' or one of its dependencies: Das angegebene Modul wurde nicht gefunden. (0x8007007E)
   at Realms.SynchronizationContextScheduler.install_scheduler_callbacks(get_context get, post_on_context post, release_context release, is_on_context is_on)
   at Realms.SynchronizationContextScheduler.Install()
   at Realms.NativeCommon.Initialize()
   at Realms.SharedRealmHandle..cctor()
   --- End of inner exception stack trace ---
   at Realms.SharedRealmHandle.Open(Configuration configuration, RealmSchema schema, Byte[] encryptionKey)
   at Realms.RealmConfiguration.CreateRealm(RealmSchema schema)
   at Realms.RealmConfiguration.<>c__DisplayClass25_0.<CreateRealmAsync>b__1(Task _)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
```

## Steps to Reproduce

Build and run the program below with Realm 10 on Windows 8.1

## Code Sample

From https://docs.mongodb.com/realm/dotnet/async-console/

```c#
public static void Main(string[] args)
{
    AsyncContext.Run(async () => await MainAsync(args));
}

private static async Task MainAsync(string[] args)
{
    using var realm = await Realm.GetInstanceAsync();
    var foos = realm.All<Foo>().Where(f => f.Bar > 5);
    foreach (var foo in foos)
    {
        await Task.Delay(10); // Simulates some background work
        Console.WriteLine(foo.Bar);
    }
}
```

## Version of Realm and Tooling

- Flavor:
  - [ ] Realm Cloud
  - [ ] Self-Hosted
  - [x] Local DB
- OS & Version: Windows 8.1
- SDK Version: Realm v10.1.1
- Target: .NET Core 3.1

**Comment by LaPeste** [comment]
Hi andlang,

I tried the code sample that you submitted in a new CLI project targeting .Net Core 3.1 on Windows 10.
There is no issue building and running the test project. However, we've seen in the past people having issues while updating realm versions. Please try to delete your build folder ([clean the entire solution](https://docs.microsoft.com/en-us/visualstudio/ide/building-and-cleaning-projects-and-solutions-in-visual-studio?view=vs-2019)) and try to build again.

Andrea

**Comment by andlang** [comment]
Hi Andrea,

I cleaned the build folder and still get the same error. But for compatibility reasons, I run it with Windows 8.1 and not with Windows 10. Could you try, if it works for you with Windows 8.1? Or is that version not supported anymore?

Andreas

**Comment by nirinchev** [comment]
8.1 should be supported, but admittedly we don't run automated tests for it. I think I have a VM with 8.1 that I can try running on.

**Comment by nirinchev** [comment]
I did repro it on Win 8.1 - seems like NuGet doesn't resolve the correct dependency here - I'll keep looking.

**Comment by nirinchev** [comment]
We were able to track it down to our Core database accidentally using a Win10 API. We'll fix it with the next release. Unfortunately, there are no known workarounds at the moment besides upgrading to Win10, I am sorry about that 😔

**Comment by markusroessler** [comment]
The same exception occurs on Windows Server 2012 R2. When will the fix/next release arrive?

**Comment by nirinchev** [comment]
We don't have an update unfortunately - the accidental usage of a Win10 API turned out to be a false lead. We could still repro even after removing it. I'll ping the Core team to see if there have been any developments.

**Comment by nirinchev** [comment]
This has been resolved and will be included in the next release.

**Comment by movsar** [comment]
What the hell? why can't you really fix it instead of saying - you should upgrade to windows 10? I got a project specifically for windows 7 and unfortunately I was using Realm from ground up, now it seems the only option is to change my DBMS, this is really bad.
