### ISSUE TITLE
error realm-wrappers on xamarin form 5.0

### ISSUE THREAD

**Issue by harriscreativity** [realm/realm-dotnet#2311]
[Mono] DllImport error loading library 'librealm-wrappers.so': 'dlopen failed: library "librealm-wrappers.so" not found'.
[Mono] DllImport error loading library 'librealm-wrappers.so': 'dlopen failed: library "librealm-wrappers.so" not found'.
[Mono] DllImport error loading library 'librealm-wrappers': 'dlopen failed: library "librealm-wrappers" not found'.
[Mono] DllImport unable to load library 'realm-wrappers'.
**System.DllNotFoundException:** 'realm-wrappers assembly:<unknown assembly> type:<unknown type> member:(null)'

Realm v10.1.2

**Comment by papafe** [comment]
Hi @harriscreativity, I have some question for you to better understand the problem:
- Can you provide us an example of how you are using Realm?
- What operating system do you use?
- Has it ever worked for you?

**Comment by harriscreativity** [comment]
`public static Realms.Sync.App RealmApp;
protected override void OnStart()
        {
                   
RealmApp = Realms.Sync.App.Create(appId);
        }
`
Windows 10
Visual Studio Pro 2019
Xamarin 16.9.000.271
Version 5, legacy version did work previously

**Comment by harriscreativity** [comment]
code

**Comment by harriscreativity** [comment]
`public static Realms.Sync.App RealmApp;
    protected override void OnStart()
   {
     RealmApp = Realms.Sync.App.Create(appId);
    }`

Windows 10
Visual Studio Pro 2019
Xamarin 16.9.000.271
Version 5, legacy version did work previously

**Comment by nirinchev** [comment]
The logs you posted indicate that the runtime is looking for `realm-wrappers.so` - are you building for Android? Did you try deleting your bin/obj files and rebuilding the project? What Android platform are you running this code on?

**Comment by harriscreativity** [comment]
I have tried that and I am still getting the same error. I am running this on Android 10

**Comment by harriscreativity** [comment]
Here is the link to the sample project
https://github.com/harriscreativity/XFrealm

**Comment by LaPeste** [comment]
You only added the Realm package to the common project (assembly) **XFrealm**. You didn't add the Realm package to your Android project. That's why the dll isn't found. The same issue exists for you iOS project.
More context can be obtained from a [similar issue](https://stackoverflow.com/questions/47827941/realm-system-typeinitializationexception-the-type-initializer-for-realms-rea).

**Comment by harriscreativity** [comment]
Yes it working thank you
