### ISSUE TITLE
Xamarin Android binding library

### ISSUE THREAD

**Issue by Adit2705** [realm/realm-dotnet#2319]
I have to use Realm in Android binding project Xamarin and to create a dll from it and referenced it to Xamarin project. 
Can anyone please let me know how to do it?

**Comment by nirinchev** [comment]
I'm sorry, we don't officially support using Realm in binding projects. I would recommend asking on the Xamarin forums or reaching out to the author of the library that you want to create bindings for (assuming it's a 3rd party library that happens to use Realm).

**Comment by Adit2705** [comment]
Ok Can I get the jars or aar for Realm?

**Comment by nirinchev** [comment]
You can download the aars from maven central: https://search.maven.org/artifact/io.realm/realm-android-library/10.4.0/aar - there's a download button at the top right. Just out of curiosity, what library are you trying to use in your Android project that depends on Realm?

**Comment by Adit2705** [comment]
Ok thanks @nirinchev  I am trying to integrate https://github.com/reference-point/SmartcardSDK into the Xamarin

**Comment by nirinchev** [comment]
I see - unfortunately, I don't know of any existing customers who are using it, so can't really offer any pointers. I hope it turns out to be reasonably straightforward though!

**Comment by nirinchev** [comment]
I'm closing this issue as it's not directly related to the .NET SDK. If you need more help with it, feel free to post a question on the [community forums](https://developer.mongodb.com/community/forums/c/realm-sdks/58) - there might be other users who have had success creating binding projects for the native SDKs.
