### ISSUE TITLE
Simplify query_cs in wrappers

### ISSUE THREAD

**Issue by papafe** [realm/realm-dotnet#2323]
At the moment several methods in `query_cs.cpp` have a switch statement on the type of the input  that calls almost the same method on a `Mixed` parameter. It should be possible to remove the switch and simplify the code quite a bit.
Additionally, methods like `query_primitive_equal` and `query_null_equal` could be merged.

**Comment by nirinchev** [comment]
That will go away once we adopt the new LINQ provider, so not worth doing it.
