### ISSUE TITLE
realm-wrappers.pdb not load in Xamarin Forms / UWP

### ISSUE THREAD

**Issue by ivanrlg** [realm/realm-dotnet#2336]
## Goals
Find out what generates exception.

## Expected Results

Correct the error.

## Actual Results

```
    In MetaDataChatRepository ReadAsync:p => ((p.EmailUser == value(MyClinicalApp.Services.ManagerDataBaseService+<>c__DisplayClass81_0).MetaDataChatModel.EmailUser) AndAlso (p.ToEmail == value(MyClinicalApp.Services.ManagerDataBaseService+<>c__DisplayClass81_0).MetaDataChatModel.ToEmail)) Time: 4/15/2021 3:28:06 PM
Exception thrown at 0x00007FFD52B84B59 in FusionMedicalRealm.UWP.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FFD52B84B59 in FusionMedicalRealm.UWP.exe: Microsoft C++ exception: EEMessageException at memory location 0x0000004ADD27DC30.
      In GetInstanceAsync  Time: 4/15/2021 3:28:06 PM
Exception thrown at 0x00007FFD52B84B59 in FusionMedicalRealm.UWP.exe: Microsoft C++ exception: EEMessageException at memory location 0x0000004ADD27DC70.
Exception thrown at 0x00007FFD52B84B59 in FusionMedicalRealm.UWP.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FFD52B84B59 in FusionMedicalRealm.UWP.exe: Microsoft C++ exception: EEMessageException at memory location 0x0000004ADD27DC70.
Exception thrown at 0x00007FFD52B84B59 in FusionMedicalRealm.UWP.exe: Microsoft C++ exception: EEMessageException at memory location 0x0000004ADD27DC30.
Exception thrown at 0x00007FFD52B84B59 in FusionMedicalRealm.UWP.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FFD52B84B59 in FusionMedicalRealm.UWP.exe: Microsoft C++ exception: EEMessageException at memory location 0x0000004ADD27DC30.
Exception thrown at 0x00007FFD52B84B59 in FusionMedicalRealm.UWP.exe: Microsoft C++ exception: EEMessageException at memory location 0x0000004ADD27DC70.
Exception thrown at 0x00007FFD52B84B59 in FusionMedicalRealm.UWP.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FFD52B84B59 in FusionMedicalRealm.UWP.exe: Microsoft C++ exception: EEMessageException at memory location 0x0000004ADD27DC70.
Exception thrown at 0x00007FFD52B84B59 in FusionMedicalRealm.UWP.exe: Microsoft C++ exception: EEMessageException at memory location 0x0000004ADD27DC30.
Exception thrown at 0x00007FFD52B84B59 in FusionMedicalRealm.UWP.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FFD52B84B59 in FusionMedicalRealm.UWP.exe: Microsoft C++ exception: EEMessageException at memory location 0x0000004ADD27DC30.
Exception thrown at 0x00007FFD52B84B59 in FusionMedicalRealm.UWP.exe: Microsoft C++ exception: EEMessageException at memory location 0x0000004ADD27DC70.
Exception thrown at 0x00007FFD52B84B59 in FusionMedicalRealm.UWP.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FFD52B84B59 in FusionMedicalRealm.UWP.exe: Microsoft C++ exception: EEMessageException at memory location 0x0000004ADD27DC70.
Exception thrown at 0x00007FFCD09911B0 (realm-wrappers.dll) in FusionMedicalRealm.UWP.exe: 0xC0000005: Access violation reading location 0x0000000000000098.
```

## Steps to Reproduce

It is a Xamarin Forms app on UWP that receives and sends messages through signalR. At the moment of inserting them in an alternative way, it generates an expecion. To go further, enable the debuger Type in the Mixed project (Managed and Native) since otherwise no error would be shown.

At some point I get an error: realm accessed from incorrect, but currently it says absolutely nothing. I'm not sure that's the cause of the crash.

## Code Sample

```
  public async Task<IResponse> UpdateAsync(MetaDataChatModel MetaDataChatModel)
        {
            Debug.WriteLine($"    In MetaDataChatRepository UpdateAsync:{MetaDataChatModel.LastMessage} Time: {DateTime.Now}");

            MetaDataChatModel.Partition = _realmManager.projectPartition;

            var MetaDataChatDto = MetaDataChatModel.ToDto();

            var realmInstance = await _realmManager.GetInstanceAsync();
            if (realmInstance == null)
                return new Response(false, "Realm instance can't be null");


            await realmInstance.WriteAsync(realm =>
            {
                realm.Add(MetaDataChatDto, true);
            });

            Debug.WriteLine($"    Out MetaDataChatRepository UpdateAsync:{MetaDataChatModel.LastMessage} Time: {DateTime.Now}");
            return new Response(true);
        }
```

## Version of Realm and Tooling
- Xamarin
- Client SDK Version: Realm 10.1.2.
- Client OS & Version: Windows 10 Pro 20H2

Microsoft Visual Studio Community 2019
Version 16.9.4

**Comment by nirinchev** [comment]
Hey, that exception message is pretty worrying. I have a couple of questions:
1. Is this something that you can consistently reproduce? If we had a project that we could debug locally, that'd make it a lot easier to figure out what's wrong.
2. If 1. is not an option, do you execute `UpdateAsync` on the main thread or a background thread? And do you know which line throws the "Realm accessed from incorrect thread" exception?
3. I can try and produce a debug build of the SDK which should hopefully give us a more detailed error message. If 1. and 2. don't get us anywhere, would you be fine with trying it out?

**Comment by ivanrlg** [comment]
Hello Nirinchev,

1) Yes, it happens constantly, I could try creating a simplified project to pass it on to you.

2) I'm sad to say, but I know the basics about threads and tasks. It is an app that has a message chat with signalR, messages are received and both the message and the metadata are saved, most of the time it happens to the 4th or 5th message received, on other occasions it happens to the 1st. But it always happens.

Currently of several changes that I have made it does not show me that exception: "Realm accessed from incorrect thread", but if I was wrong it was in `var realmInstance = await _realmManager.GetInstanceAsync () ;`.

3) In the same way I would be happy to receive the SDK and try to find the cause of this.

Thank you.

**Comment by nirinchev** [comment]
Hey sorry for the delay - I created the packages but forgot to attach them here 🤦‍♂️ Please find the debug packages here:

https://drive.google.com/file/d/1U-pG-f_u_IyobibFMb-1VzmTgqdWCANo/view?usp=sharing, https://drive.google.com/file/d/1a85ekJyE-CRg_ueQva54PmUSLjAH_HsL/view?usp=sharing

You can try running with those and hopefully we'll get more meaningful error message/stacktrace.

**Comment by ivanrlg** [comment]
Hi @nirinchev , thank you very much for the packages, yesterday I installed them but can't get the error with this version Still, I want a little time to be able to test well.

Best regards.

**Comment by ivanrlg** [comment]
Hi @nirinchev, after doing many tests I have not yet been able to replicate the exception that was generated in UWP with version 10.1.2. I think and believe that version 10.2.0-PR-2337.1 does not generate the exception in UWP. Likewise, before closing the case, I would like to test a little more.

But, I said, I will try to do a test on Android to see what, boom, the application fails to start and throws the following exception.
It should be noted, that I downgraded to version 10.1.2 for the project and again I was able to run without problems on android.

Best regards,

[Mono] DllImport attempting to load: 'realm-wrappers'.
[Mono] DllImport error loading library '/data/data/com.cardiomet.centralcardiomet/files/.__override__/realm-wrappers': '(null)'.
[Mono] DllImport error loading library '/data/data/com.cardiomet.centralcardiomet/files/.__override__/librealm-wrappers.so': '(null)'.
[Mono] DllImport error loading library '/data/data/com.cardiomet.centralcardiomet/files/.__override__/librealm-wrappers.so': '(null)'.
[Mono] DllImport error loading library '/system/lib/realm-wrappers': '(null)'.
[Mono] DllImport error loading library '/system/lib/librealm-wrappers.so': '(null)'.
[Mono] DllImport error loading library '/system/lib/librealm-wrappers.so': '(null)'.
[Mono] DllImport error loading library 'realm-wrappers': 'dlopen failed: library "realm-wrappers" not found'.
[Mono] DllImport error loading library 'librealm-wrappers.so': 'dlopen failed: library "librealm-wrappers.so" not found'.
[Mono] DllImport error loading library 'librealm-wrappers.so': 'dlopen failed: library "librealm-wrappers.so" not found'.
[Mono] DllImport error loading library 'realm-wrappers': 'dlopen failed: library "realm-wrappers" not found'.
[Mono] DllImport error loading library '/data/data/com.cardiomet.centralcardiomet/files/.__override__/librealm-wrappers': '(null)'.
[Mono] DllImport error loading library '/data/data/com.cardiomet.centralcardiomet/files/.__override__/librealm-wrappers.so': '(null)'.
[Mono] DllImport error loading library '/data/data/com.cardiomet.centralcardiomet/files/.__override__/librealm-wrappers.so': '(null)'.
[Mono] DllImport error loading library '/system/lib/librealm-wrappers': '(null)'.
[Mono] DllImport error loading library '/system/lib/librealm-wrappers.so': '(null)'.
[Mono] DllImport error loading library '/system/lib/librealm-wrappers.so': '(null)'.
[Mono] DllImport error loading library 'librealm-wrappers': 'dlopen failed: library "librealm-wrappers" not found'.
[Mono] DllImport error loading library 'librealm-wrappers.so': 'dlopen failed: library "librealm-wrappers.so" not found'.
[Mono] DllImport error loading library 'librealm-wrappers.so': 'dlopen failed: library "librealm-wrappers.so" not found'.
[Mono] DllImport error loading library 'librealm-wrappers': 'dlopen failed: library "librealm-wrappers" not found'.
[Mono] DllImport unable to load library 'realm-wrappers'.
[Mono] DllImport attempting to load: 'realm-wrappers'.
[Mono] DllImport error loading library '/data/data/com.cardiomet.centralcardiomet/files/.__override__/realm-wrappers': '(null)'.
[Mono] DllImport error loading library '/data/data/com.cardiomet.centralcardiomet/files/.__override__/librealm-wrappers.so': '(null)'.
[Mono] DllImport error loading library '/data/data/com.cardiomet.centralcardiomet/files/.__override__/librealm-wrappers.so': '(null)'.
[Mono] DllImport error loading library '/system/lib/realm-wrappers': '(null)'.
[Mono] DllImport error loading library '/system/lib/librealm-wrappers.so': '(null)'.
[Mono] DllImport error loading library '/system/lib/librealm-wrappers.so': '(null)'.
[Mono] DllImport error loading library 'realm-wrappers': 'dlopen failed: library "realm-wrappers" not found'.
[Mono] DllImport error loading library 'librealm-wrappers.so': 'dlopen failed: library "librealm-wrappers.so" not found'.
[Mono] DllImport error loading library 'librealm-wrappers.so': 'dlopen failed: library "librealm-wrappers.so" not found'.
[Mono] DllImport error loading library 'realm-wrappers': 'dlopen failed: library "realm-wrappers" not found'.
[Mono] DllImport error loading library '/data/data/com.cardiomet.centralcardiomet/files/.__override__/librealm-wrappers': '(null)'.
[Mono] DllImport error loading library '/data/data/com.cardiomet.centralcardiomet/files/.__override__/librealm-wrappers.so': '(null)'.
[Mono] DllImport error loading library '/data/data/com.cardiomet.centralcardiomet/files/.__override__/librealm-wrappers.so': '(null)'.
[Mono] DllImport error loading library '/system/lib/librealm-wrappers': '(null)'.
[Mono] DllImport error loading library '/system/lib/librealm-wrappers.so': '(null)'.
[Mono] DllImport error loading library '/system/lib/librealm-wrappers.so': '(null)'.
[Mono] DllImport error loading library 'librealm-wrappers': 'dlopen failed: library "librealm-wrappers" not found'.
[Mono] DllImport error loading library 'librealm-wrappers.so': 'dlopen failed: library "librealm-wrappers.so" not found'.
[Mono] DllImport error loading library 'librealm-wrappers.so': 'dlopen failed: library "librealm-wrappers.so" not found'.
[Mono] DllImport error loading library 'librealm-wrappers': 'dlopen failed: library "librealm-wrappers" not found'.
[Mono] DllImport unable to load library 'realm-wrappers'.
**System.DllNotFoundException:**'realm-wrappers assembly:<unknown assembly> type:<unknown type> member:(null)'

* *System.Reflection.TargetInvocationException:**'Exception has been thrown by the target of an invocation.'

 * *System.TypeInitializationException:**'The type initializer for 'Realms.Sync.AppHandle' threw an exception.'

**Comment by nirinchev** [comment]
Hm, interesting - it's possible something in 10.2.0 fixed the UWP issue. Can you try upgrading to the public beta then: https://www.nuget.org/packages/Realm/10.2.0-beta.1? That one is built in release mode and as long as you don't use any of the new datatypes, it should be as stable as 10.1.2.

**Comment by ivanrlg** [comment]
Hi @nirinchev , unfortunately with the 10.2.0-beta.1 beta version generates the exception in UWP and also generates it when starting in android, the same as the last message.

The 10.2.0-PR-2337.1 version does not generate exception it in UWP but in android when starting.

Version 10.1.2 stable has no problem starting android.

Best Regards,

**Comment by nirinchev** [comment]
So, the Android issue sounds more like a caching problem - did you try wiping the `/bin` and `/obj` folders as well as rebuilding?

I have another set of packages for you - these are identical to the ones I sent previously (10.2.0-PR-2337.1) but are release builds rather than debug. If those fix the UWP issue, then that would be great. If they don't, then it likely means that the problem is a race condition that is masked by the slower debug packages.

https://drive.google.com/file/d/1J76oNyUKB-MgXN4o35Z1K8MfnqeAZUut/view?usp=sharing, https://drive.google.com/file/d/1VgWJ9xDYly5dYaRmrdbVp1SiEM863Xru/view?usp=sharing

**Comment by ivanrlg** [comment]
Hello @nirinchev, unfortunately with the release version the exception occurs in UWP almost immediately.

**Comment by nirinchev** [comment]
Ugh! So it's most likely a race condition. Do you think it'd be possible to share a repro case that we can run locally - either your full project or a slimmed-down version that reproduces the crash?

**Comment by ivanrlg** [comment]
Hello @nirinchev  yes, I can pass the project on to you. how do i do it? by email?

**Comment by nirinchev** [comment]
Hey, you can upload it on our secure upload portal: https://10gen-httpsupload.s3.amazonaws.com/upload_forms/13a8c245-38bb-4dd5-8f13-b60aea55ba82.html

**Comment by ivanrlg** [comment]
Hi @nirinchev, I have uploaded the project to the link you sent me. please read the readme file.

Let me know if you have any questions about how to reproduce the error.

**Comment by nirinchev** [comment]
Thanks, I can confirm we got it and we'll have someone look into it tomorrow.

**Comment by papafe** [comment]
Hi @ivanrlg we managed to reproduce the crash you were experiencing on UWP and we've produced version 10.1.3 that should contain a fix for your problem. Let us know how it goes!

**Comment by ivanrlg** [comment]
Hello @papafe  and @nirinchev , thank you very much, it seems it worked. I think we can close the case. best regards.

**Comment by papafe** [comment]
@ivanrlg Glad to hear :)
