### ISSUE TITLE
realms.Exceptions.RealmInvalidTransactionException:** 'Loading...

### ISSUE THREAD

**Issue by harriscreativity** [realm/realm-dotnet#2341]
First time it works but the second time it throws this error
### **realms Exceptions RealmInvalidTransactionException**

```
 App.realm.Write(() => {
      configButton.updatedAt = DateTimeOffset.Now;
      configButton.UsageCount -= 1;

      var auditlog = new AuditLog
      {
          userId = App.RealmApp.CurrentUser.Id,
          AppliedAt = DateTimeOffset.Now,
          Email = App.RealmApp.CurrentUser.Profile.Email,
          ButtonApplied = configButton,
          SiteLocation = new SiteLocation
          {
              Altitude = location.Altitude,
              Latitude = location.Latitude,
              Longitude = location.Longitude
          }
      };
      id = auditlog.Id;
      App.realm.Add(auditlog); 
  });
```

**Comment by papafe** [comment]
Hi @harriscreativity, can you post the body of the exception? It should give you more details about the reason of this error

**Comment by harriscreativity** [comment]
{Realms.Exceptions.RealmInvalidTransactionException: Cannot modify managed objects outside of a write transaction.  at Realms.NativeException.ThrowIfNecessary (System.Func`2[T,TResult] overrider) [0x0000a] in C:\jenkins\workspace\realm_realm-dotnet_PR-2302\Realm\Realm\Native\NativeException.cs:55   at Realms.ObjectHandle.SetValue (System.IntPtr propertyIndex, Realms.RealmValue& value, Realms.Realm realm) [0x0009f] in C:\jenkins\workspace\realm_realm-dotnet_PR-2302\Realm\Realm\Handles\ObjectHandle.cs:187   at Realms.RealmObjectBase.SetValue (System.String propertyName, Realms.RealmValue val) [0x00012] in C:\jenkins\workspace\realm_realm-dotnet_PR-2302\Realm\Realm\DatabaseTypes\RealmObjectBase.cs:193   at UtiliPro.Models.ConfigButton.set_updatedAt (System.DateTimeOffset value) [0x00000] in C:\Repository\usc-mobile-xamarin\UtiliPro\UtiliPro\UtiliPro\Models\Button.cs:18   at UtiliPro.helpers.RealmHelpers+<>c__DisplayClass7_0.<CreateAuditLog>b__0 () [0x00001] in C:\Repository\usc-mobile-xamarin\UtiliPro\UtiliPro\UtiliPro\helpers\RealmHelpers.cs:127   at Realms.Realm+<>c__DisplayClass60_0.<Write>b__0 () [0x00000] in C:\jenkins\workspace\realm_realm-dotnet_PR-2302\Realm\Realm\Realm.cs:701   at Realms.Realm.Write[T] (System.Func`1[TResult] function) [0x00018] in C:\jenkins\workspace\realm_realm-dotnet_PR-2302\Realm\Realm\Realm.cs:739   at Realms.Realm.Write (System.Action action) [0x0001d] in C:\jenkins\workspace\realm_realm-dotnet_PR-2302\Realm\Realm\Realm.cs:699   at UtiliPro.helpers.RealmHelpers.CreateAuditLog (Xamarin.Essentials.Location location, UtiliPro.Models.ConfigButton configButton) [0x0002c] in C:\Repository\usc-mobile-xamarin\UtiliPro\UtiliPro\UtiliPro\helpers\RealmHelpers.cs:125   at UtiliPro.Pages.WriteOperation.WriteOperation+<>c__DisplayClass4_1.<TapGestureRecognizer_Tapped>b__0 () [0x00001] in C:\Repository\usc-mobile-xamarin\UtiliPro\UtiliPro\UtiliPro\Pages\WriteOperation\WriteOperation.xaml.cs:64   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in /Users/builder/azdo/_work/278/s/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:36   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in /Users/builder/azdo/_work/278/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-30/mcw/Java.Lang.IRunnable.cs:84   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.39(intptr,intptr)}

**Comment by nirinchev** [comment]
Looks like configButton is a RealmObject - is it managed by the same Realm you're trying to write to?

**Comment by harriscreativity** [comment]
What is actually happening is that when I run this it works for the first time, it will create the object in database perfect press the button again to perform the same action for the second time it crashes...

`public class ConfigButton : RealmObject
    {
        [PrimaryKey]
        [MapTo("_id")]
        public ObjectId Id { get; set; } = ObjectId.GenerateNewId();
        public string Description { get; set; }
        public int UsageCount { get; set; }
        public string Permission { get; set; }
        public DateTimeOffset createdAt { get; set; } = DateTimeOffset.Now;
        public DateTimeOffset updatedAt { get; set; } = DateTimeOffset.Now;
        public IList<RealmSettings> settings { get; }
    }`

**Comment by papafe** [comment]
@harriscreativity, are you adding `configButton` to a realm before adding it into the `auditLog` as you've showed it on the top? Can you show us how it's created?
Also, can you show us how `App.realm` is defined?

**Comment by harriscreativity** [comment]
`App.realm.All<ConfigButton>()`
render it to listview on item click get the selected item then pass it to function mentioned above to update then create auditlog

**Comment by harriscreativity** [comment]
var config = new SyncConfiguration(partitionKey, user);
  var realm = await Realm.GetInstanceAsync(config);
  App.realm = realm;

**Comment by nirinchev** [comment]
Is `configButton.Realm == App.realm`?

**Comment by harriscreativity** [comment]
yes it is,

```
public ConfigButton createBtn(List<Instruction> instructions, string _description, int _usageCount, string _permission)
        {
            var configBtn = new ConfigButton()
            {
                Description = _description,
                UsageCount = _usageCount,
                Permission = _permission,
            };
            foreach (var item in instructions)
            {
                if (item.ShowDetail)
                {
                    //ADD FRIENDLY NAME WITHT DEFAULT VALUE OF TRUE DON'T ASK ME WHY
                    var settings = new RealmSettings
                    {
                        FriendlyNane = item.FriendlyName,
                        Prop = item.Prop,
                        DefaultValue = "True"
                    };

                    foreach (var element in item.Details)
                    {
                        if (!string.IsNullOrEmpty(element.DefaultValue) && element.DefaultValue != "null")
                        {
                            settings.settings.Add(new RealmSetting
                            {
                                FriendlyNane = element.FriendlyName,
                                DefaultValue = element.DefaultValue,
                                Prop = element.Prop
                            });
                        }
                    }
                    //ADD TO REALM CONFIG BUTTON
                    configBtn.settings.Add(settings);

                }

            }

            App.realm.Write(() =>
            {
                //ADD TO REALM DB
                App.realm.Add(configBtn);

            });
            var obj = App.realm.Find<ConfigButton>(configBtn.Id);
            return obj;

        }
```

**Comment by harriscreativity** [comment]
```
App.realm.Write(() => {
            
                var btn = App.realm.Find<ConfigButton>(configButton.Id);

                btn.updatedAt = DateTimeOffset.Now;
                btn.UsageCount = btn.UsageCount - 1;

                var auditlog = new AuditLog

                {
                    userId = App.RealmApp.CurrentUser.Id,
                    AppliedAt = DateTimeOffset.Now,
                    Email = App.RealmApp.CurrentUser.Profile.Email,
                    ButtonApplied = configButton,
                    SiteLocation = new SiteLocation
                    {
                        Altitude = location.Altitude,
                        Latitude = location.Latitude,
                        Longitude = location.Longitude
                    }
                };

                id = auditlog.Id;
                App.realm.Add(auditlog); 
            });
```
![unnamed](https://user-images.githubusercontent.com/20087512/115389799-d2b73b00-a1dd-11eb-8656-4730113ca813.jpg)

**Comment by papafe** [comment]
@harriscreativity From the last screenshot it seems that `configButton` is not in `App.realm`, and this makes me think that maybe you are working on two different realms.
What you should do is to check the value of `App.realm.Config `and `configButton.Realm.Config` and see if they are the same. If not, it means that you're actually working on different realms, and that's the cause of your error. You can also paste the result of config values here.
Also, what is the method `WriteSafe` on `App.realm`?

**Comment by papafe** [comment]
@harriscreativity Did you manage to solve the issue?
