### ISSUE TITLE
Investigate infinite sync tests

### ISSUE THREAD

**Issue by papafe** [realm/realm-dotnet#2353]
While working on #2348 I ran out into a case in which some sync tests (the ones in `DataTypeTests.cs`) would run fine (most of the times) if run one by one, but would just continue forever when the whole test fixture is run. 
This was happening while using a wrongly produced docker image that did not support `float` properties. This happened with the image for date 2021-04-26.
It would be good to investigate why the tests were not failing but just running indefinitely.

**Comment by nirinchev** [comment]
This was fixed as a drive-by in https://github.com/realm/realm-dotnet/pull/2380
