### ISSUE TITLE
Very heavy load on first sync.

### ISSUE THREAD

**Issue by ivanrlg** [realm/realm-dotnet#2388]
## Goals

Find the cause of the problem.

## Expected Results
Have a faster start.

## Actual Results
6-8 Minutes start with a 340Mb data transfer load and my database does not reach 15mb.

## Steps to Reproduce

This is a Xamarin Forms application (Android).

I realized after some time testing locally on my emulator and local android device (Everything works perfectly) that when doing a new installation of the app, the first time it took approximately 6-8 minutes for the initial data load.

My first query is to get a simple record from a user table. (In my case Oatients.)

Do some research on the internet and put this code snippet to see what data it brought when doing a GetInstanceAsync.
`Console.WriteLine ($" Progress: {progress.TransferredBytes} / {progress.TransferableBytes} ");`

And I realize something more interesting, that it tries to synchronize 340mb and I suppose that explains the 6-8min.

But if I enter the MongoBD portal, I also realize that all my collections, which are 20 in total, do not weigh more than 15mb.

So the question is, because the initial load tries to bring 340Mb, is it a huge configuration problem? of programming? Please kindly guide me on how I can improve this?

It should be noted that after this "first synchronization" this does not happen again.

Best regards.

## Code Sample

```
        public async Task<IDataResponse<IEnumerable<PatientModel>>> ReadAsync(Expression<Func<PatientModel, bool>> predicate)
        {
            IEnumerable<Patient> resultDto;
            IEnumerable<PatientModel> result;

            var realmInstance = await _realmManager.GetInstanceAsync();
            if (realmInstance == null)
                return new DataResponse<IEnumerable<PatientModel>>(null, false, "Realm instance can't be null");

            var afterParameter = Expression.Parameter(typeof(Patient), predicate.Name);
            var visitor = new ExpressionExtension(predicate, afterParameter);
            var newPredicate = Expression.Lambda<Func<Patient, bool>>(visitor.Visit(predicate.Body), afterParameter);

            resultDto = realmInstance.All<Patient>()
                                     .Where(newPredicate);
            result = resultDto.ToModel();

            return new DataResponse<IEnumerable<PatientModel>>(result, result != null);
        }
```

```
 public async Task<Realms.Realm> GetInstanceAsync()
        {
            Debug.WriteLine($"      In GetInstanceAsync  Time: {DateTime.Now}");
            return await Realms.Realm.GetInstanceAsync(syncConfig);
        }
```

   ```
     public async Task RealmLogInAsync()
        {
            if (RealmApp.CurrentUser == null)
            {
                User user = await RealmApp.
                LogInAsync(Credentials.EmailPassword("my_user", "my_passoword"));

                if (user == null)
                {
                    return;
                }
            }

            projectPartition = $"project={RealmApp.CurrentUser.Id}";
            syncConfig = new SyncConfiguration(projectPartition, RealmApp.CurrentUser)
            {
                OnProgress = progress =>
                {
                    Console.WriteLine($"Progress: {progress.TransferredBytes}/{progress.TransferableBytes}");
                }
            };
        }

```

## Version of Realm and Tooling

- Realm Object Server Version: ? (you can see this as well in Studio once connected to a Realm instance) 
- Flavor:
Xamarin
Client SDK Version: Realm 10.1.4.
Client OS & Version: Android 9/10.
Microsoft Visual Studio Community 2019
Version 16.9.6

**Comment by nirinchev** [comment]
Hey, there might be multiple causes of the slowdown - it can be a client-side issue (e.g. slow integration of changes) or a server-side problem where the server has a lot of history and it takes a while to prepare the changesets. To get to the bottom of it, we'll likely need to discuss private details about your app which are not suited for a public Github issue. Can you please open a ticket on https://support.mongodb.com/ where the support engineers will work with you to find the root cause or figure out a feasible workaround.

**Comment by ivanrlg** [comment]
Hello @nirinchev , thank you for your prompt reply.

The case that I open is not so slow, it is more related to the fact that I do not understand why the initial load downloads 340MB when if I go to my Database I see that it weighs 15mb.

Is it a normal behavior in the first synchronization to download 340Mb? Is it a configuration issue? Is there a way to avoid this?

Best regards.

**Comment by ivanrlg** [comment]
Sure, I can also open a ticket there. The same before the question was to evaluate if it was something simple.

**Comment by nirinchev** [comment]
I wish there was an easy yes/no answer here 😅 The tl;dr of it is that Realm stores a history of changes (if you're familiar with MongoDB's oplog - it's a similar concept) and this is the basis for our synchronization algorithm. That history has roughly the shape of "class._id.prop = value" - e.g. "Person.123.Name = 'Peter'". Keeping that history is important for conflict resolution purposes, which means that if your app generates many updates that overwrite the properties of the same object, the history will grow large, even though the data itself is actually more or less constant in size. There are certain heuristics that we employ to trim the history at opportune times, but in real-world scenarios, it is usually expected that the history is larger than the state, although your case where it's 20+ times larger is unusual.

We do have certain improvements in the pipeline which can speed up this initial download, but it is nonetheless a good idea to have the Cloud team look into your app and determine whether the history compaction algorithms work as expected and/or if there are ways to improve initial download times and sizes.

**Comment by ivanrlg** [comment]
Thanks @nirinchev , I have made the support request.

**Comment by ivanrlg** [comment]
Hi @nirinchev , the supported database size has already been fixed.

I only have one doubt, currently the size of my database is 19mb, as I see that every first synchronization is completely downloaded. There will come a time when, even when compacted, this size would be much larger.

Is there a good practice to avoid downloading everything the first time and only what is needed?

In the same way, if you wish, you can close this case.

**Comment by nirinchev** [comment]
With the current architecture and feature set there's no way to avoid that unfortunately. We have some features in the pipeline that will hopefully improve things, but those are more in the 6-12 month timeframe.
