### ISSUE TITLE
Implement Realm.DynamicApi breaking changes

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-dotnet#2391]
Once we want to bump the major version, there are some breaking changes we'd like to do for Realm.DynamicApi:

- [x] Replace all return types that were `dynamic` with non-dynamic versions.
- [x] Make `Realm.Dynamic` a struct that gets created on demand similar to `RealmObjectBase.Dynamic`.
- [x] Replace `CreateObject(string, object)` with overloads that accept the concrete PK types similar to `Find`.

**Comment by papafe** [comment]
@nirinchev should we do this if we're going to have the major bump?

**Comment by nirinchev** [comment]
Yes - the plan is to cut a final 10.x release with Core 13.2.0, then go through all the breaking changes and do them for 11.x.
