### ISSUE TITLE
Exception occurred when trying to access property of *frozen* realm object from another thread

### ISSUE THREAD

**Issue by VictorKochetkov** [realm/realm-dotnet#2395]
Unexpected exception occurred when trying to access property of **frozen** realm object from another thread

## Steps to reproduce:
1. Find realm object inside `Task.Run`
2. Call `value.Freeze()`
3. Get value from realm object in another thread like `Device.InvokeOnMainThreadAsync`
4. Expects no error, because object was frozen

## Actual Results
Exception throws `System.Exception: Realm accessed from incorrect thread.`

## Code Sample
```
            await Task.Run(async () =>
            {
                using (var realm = RealmHelper.GetInstance())
                {
                    var point = realm
                        .All<Point>()
                        .Where(x => x.IsSelected)
                        .FirstOrDefault();

                    point.Freeze();

                    await Device.InvokeOnMainThreadAsync(() =>
                    {
                        string id = point.Id; // Exception!
                    }
                   }
            }
```

## Version of Realm and Tooling
- NuGet: Realm 10.1.4
- Platform: iOS (possibly Android too), Xamarin.Forms

**Comment by nirinchev** [comment]
`RealmObject.Freeze()` will return a new frozen instance of the same object - it won't freeze the existing one. So you should do something like:

```csharp
var frozenPoint = point.Freeze();
await Device.InvokeOnMainThreadAsync(() =>
{
    string id = frozenPoint; // No exception! 🤞 
}
```

**Comment by VictorKochetkov** [comment]
> `RealmObject.Freeze()` will return a new frozen instance of the same object - it won't freeze the existing one. So you should do something like:
> 
> ```cs
> var frozenPoint = point.Freeze();
> await Device.InvokeOnMainThreadAsync(() =>
> {
>     string id = frozenPoint; // No exception! 🤞 
> }
> ```

This is breaking changes I think? 5.1.* version does not have another behavior(
Thank you!

**Comment by nirinchev** [comment]
In 5.x we had a method `FreezeInPlace` which would freeze the object in place. That was removed in v10. [`Freeze`](https://github.com/realm/realm-dotnet/blob/a8cf123a29a60b8e73f7033316ccc4fc1f640fc4/Realm/Realm/Extensions/FrozenObjectsExtensions.cs#L60-L61) would still create a new object without modifying the exiting object.

**Comment by nirinchev** [comment]
Closing this as I believe the original problem was resolved.
