### ISSUE TITLE
[Unity] Host a licensing server for Unity CI

### ISSUE THREAD

**Issue by geragray** [realm/realm-dotnet#2407]
We need to host a Unity licensing server to support using a build server: https://unity.com/products/unity-build-server

**Comment by nirinchev** [comment]
@realm/ci-team any updates here - did the Unity team come back with any advice?

**Comment by bwachter** [comment]
> @realm/ci-team any updates here - did the Unity team come back with any advice?

The end result of that meeting we had about it was that we'll be setting it up in a private network, so for now we don't need to contact Unity. I got access to AWS, got a quick overview of what you're running there currently, and then got sidetracked into looking at the Java and JS components. I'll get back to this in the next few days.

**Comment by nirinchev** [comment]
Here's a Unity project you can use to test the build server.

[UnityLicensingTester.zip](https://github.com/realm/realm-dotnet/files/6776905/UnityLicensingTester.zip)
