### ISSUE TITLE
Helper function for migrating to EmbeddedObject

### ISSUE THREAD

**Issue by DominicFrei** [realm/realm-dotnet#2408]
## Goals

When migrating to `EmbeddedObject` two cases have to be handled:
- Objects without backlinks (orphaned objects)
- Objects with more than one backlink

This is necessary due to the nature of `EmbeddedObject`s always belonging to one and only one other object.

As explained in https://github.com/realm/realm-dotnet/issues/2394 and https://github.com/realm/realm-dotnet/discussions/2393 this cannot be achieved while migrating because `EmbeddedObject` cannot be iterated over / queried since it's not a standalone object.

This will also unlock https://github.com/realm/realm-dotnet/issues/2394.

## Expected Results

- Orphaned objects get deleted automatically when a flag for deleting them is set as part of the migration block.
- Objects with multiple backlinks will be duplicated so that every object linking to them gets their own version.

**Comment by DominicFrei** [comment]
This will be unlocked by https://github.com/realm/realm-core/issues/4729.

**Comment by softlion** [comment]
The core has been changed last year
https://github.com/realm/realm-core/pull/5737

Also, how to do that manually as questioned here ? Can't find a way.
https://github.com/realm/realm-dotnet/discussions/2594#discussioncomment-5881789

**Comment by nirinchev** [comment]
This is now unblocked and we can pick it up.
