### ISSUE TITLE
Mapping not work

### ISSUE THREAD

**Issue by carbonete** [realm/realm-dotnet#2447]
## Goals

Create user custom data. But field mapping properties PartitionKey to _partitionKey  not occurs.

## Expected Results

Create document with this schema and mapped names.

```
{"_id":"60c90d08e89f1cdae9ed1b99",
"_partitionKey":"scf@kounen.com",
"MaxDevices":{"$numberInt":"2"}}
```

## Actual Results

```
{"_id":"60c90d08e89f1cdae9ed1b99",
"PartitionKey":"scf@kounen.com",
"MaxDevices":{"$numberInt":"2"}}
```

## Code Sample
```
// class mapping 
 public class UserExtension : RealmObject
    {
        [PrimaryKey]
        [MapTo("_id")]
        public string Id { get; set; }

        [Required]
        [MapTo("_partitionKey")]
        public string PartitionKey { get; set; }
        
        public int MaxDevices { get; set; } = 2;
        
        public IDictionary<string,string> Devices { get; } /* unique id , device name */

        #region Constructor
        public UserExtension(string id, string partition)
        {
            this.Id = id;
            this.PartitionKey = partition;
        }

        public UserExtension() { }

        #endregion
    }
// code inserting doc

public async Task<string> CreateUserExtension()
        {
            try
            {
                var mongoClient = RealmUser.GetMongoClient(clusterName);
                var dbTracker = mongoClient.GetDatabase(databaseName); 
                var cudCollection = dbTracker.GetCollection<UserExtension>(userCollectionName);
                UserExtension = new UserExtension(RealmUser.Id, RealmUser.Profile.Email);
                var insertResult = await cudCollection.InsertOneAsync(UserExtension);
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
            return string.Empty;
        }

```

## Version of Realm and Tooling

- Flavor:
  - [x] MongoDB Realm
  - [ ] Local Database only
- Client SDK Version: ? Realm .Net 10.2.0
- Client OS & Version: ? Xamarin Forms 5.0 , UWP 6.2.12 , Windows 10 PRO Build 19041.1052

**Comment by nirinchev** [comment]
When using the remote mongodb client, we're using the MongoDB.Bson component of the C# driver to do the mapping to-and-from documents. We have mapping examples in the [Query MongoDB](https://docs.mongodb.com/realm/sdk/dotnet/examples/mongodb-remote-access/) section of the docs, but the gist of it is - replace `[MapTo]` with `[BsonElement]`. I noticed that there's a minor flaw with the examples in that they showcase the document classes as inheriting from `RealmObject` which is not necessary and I filed a ticket to fix the docs.

To go a little deeper - `RealmObject` inheritors will respect the `[MapTo]` attribute which is used for remapping properties stored in the local Realm database. Using the MongoClient API, you're calling directly into the [MongoDB data access API](https://docs.mongodb.com/realm/mongodb/) which is a rest-like API that communicates over json. The serialization/deserialization of your models from/to json happens using the MongoDB.Bson library and respects the attributes it exposes for controlling the serializer behavior.

**Comment by nirinchev** [comment]
And by the way, if you do want to use Realm Sync to create the UserExtension locally and have it synchronized in the background to your Atlas cluster, you can check out the [Sync docs](https://docs.mongodb.com/realm/sdk/dotnet/examples/sync-changes-between-devices/). If you do use Realm Sync, then your model class looks correct and `Partition` will show up as `_partition` in Atlas.

**Comment by carbonete** [comment]
Thanks
