### ISSUE TITLE
ERROR ITMS-90171: "Invalid Bundle Structure"

### ISSUE THREAD

**Issue by wowapps-global** [realm/realm-dotnet#2448]
## Goals

I am building a Xamarin mobile app which uses `realm` for some internal database features.
The app compiles in VS (Windows) without error, but fails at the Mac Transporter validation steps with this error message..

> ERROR ITMS-90171: “Invalid Bundle Structure” - The binary file "MYAPP.iOS.app/Frameworks/realm-wrappers.framework/realm-wrappers is not permitted.

I have  tried…
- increasing / decreasing version of Realm from v10.0.1 to v10.2.0
- removing bin/obj folders and building again
- clearing cache folders on MAC

I have 
- created a bug report for Visual Studio on microsofthttps://developercommunity.visualstudio.com/t/ERROR-ITMS-90171:-Invalid-Bundle-Struct/1450505 
- Put a question on MS Q&A 
- Researched Realm for bugs…  (here)

## Expected Results

Expect transporter to say "yep, all good.. Upload away!".. 

## Actual Results

Transporter says "YOU SHALL NOT PASS!"

## Steps to Reproduce

Try to upload my IPA's using transporter..

## Version of Realm and Tooling

- Flavor:
- Realm NuGet Package (v10.0.1 to v10.2.0)
- Realm.Fody nuget package (v10.0.1 to v10.2.0)

VS Info
`Microsoft Visual Studio Community 2019
Version 16.10.1
VisualStudio.16.Release/16.10.1+31402.337
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

ASP.NET and Web Tools 2019   16.10.526.50910
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.10.526.50910
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.10.526.50910
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.10.526.50910
Azure Functions and Web Jobs Tools

Bundler & Minifier   2.8.396
Adds support for bundling and minifying JavaScript, CSS and HTML files in any project.

C# Tools   3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Clean Solution   1.4.30
Cleans up the solution for the next time you open it. Closes open documents and collapses folders automatically when a solution is being closed.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.40423.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   16.10.15 (552afdf)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.30310.1 Commit Hash:e550dd1b679956810ccace4368dbc7a64443213b
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   5.10.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   16.1.0.2122504+13c05c96ea6bdbe550bd88b0bf6cdddf8cde1725
Provides languages services for ASP.NET Core Razor.

SettingsCommands Extension   1.0
SettingsCommands Visual Studio Extension Detailed Info

SlowCheetah - XML config transforms   1.0
This package enables you to transform your app.config or any other XML file based on the build configuration. It also adds additional tooling to help you create XML transforms.

SQL Server Data Tools   16.0.62105.04180
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.30429.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.10.0-beta.21262.7+1b23bbeda88ea3cb9be9af777f4c99fa8663df81
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.10.000.230 (d16-10@0e66389)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.10.0.115 (remotes/origin/c750fbf1bde3c720d077f51640fe197c6dac7cbe@c750fbf1b)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.10.5 (355b57a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.3.0.1 (d16-10/22fc2b3)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: b4a3858
    Java.Interop: xamarin/java.interop/d16-10@f39db25
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.35.4@85460d3
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0

Xamarin.iOS and Xamarin.Mac SDK   14.20.0.3 (17fdcf569)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
`

**Comment by wowapps-global** [comment]
Upgrading VS to v16.10.2 does not rectify the issue.

**Comment by nirinchev** [comment]
Can you try building and uploading your project from macOS directly? Recent releases of VS for Windows seem to introduce various bugs related to native libraries (or at least ours) and we still haven't gotten to the bottom of it.

**Comment by wowapps-global** [comment]
Hi @nirinchev ,

I'll try that later in the week..
For your information, I've also logged this issue with Microsoft..

https://developercommunity.visualstudio.com/t/ERROR-ITMS-90171:-Invalid-Bundle-Struct/1450505

**Comment by nirinchev** [comment]
Seems like it's indeed a bug in VS: https://github.com/xamarin/xamarin-macios/issues/11728 and https://developercommunity.visualstudio.com/t/Cant-deliver-to-the-appstore-since-last/1436223#T-N1445242.

It looks like 16.10.2 just dropped and that should hopefully resolve some of the issues. We'll check it out later today, but feel free to give it a shot on your end and let us know how it goes.

**Comment by wowapps-global** [comment]
Hi @nirinchev , 
I have tried 16.10.2, and that does not fix the issue..

**Comment by nirinchev** [comment]
The [Xamarin issue](https://github.com/xamarin/xamarin-macios/issues/11728) got closed and I can't repro this with 16.10.3, so closing this issue as well.
