### ISSUE TITLE
User profile email is null 

### ISSUE THREAD

**Issue by carbonete** [realm/realm-dotnet#2460]
## Goals

Retrieve user email from Realm User Profile when registered using:
 await RealmApp.EmailPasswordAuth.RegisterUserAsync(mail, password);

EMail is displayed at Realm portal.

AlternativalIy i try find a way to recover Provider data, but without success, i can't find doc about.  

## Expected Results

RealmUser.Profile.Email contains mail used to registration.

## Actual Results

All properties in Profile is null.

## Steps to Reproduce

Register a new user with email/password.
Consult RealmApp.AllUsers ,any user and watch Profile.

## Version of Realm and Tooling

- Flavor:
  - [x ] MongoDB Realm
  - [ ] Local Database only
- Client SDK Version: ? .Net 10.2.0
- Client OS & Version: ? Xamarin.Forms.UWP 5.0 Windows 10

**Comment by nirinchev** [comment]
Do you login with the user after registering? I just checked by modifying this integration test that we have:

https://github.com/realm/realm-dotnet/blob/d5aa97ece0f2286a944ca3710edf24fe7b547050/Tests/Realm.Tests/Sync/UserManagementTests.cs#L151-L168

And inspecting the `UserProfile` gives us the email correctly. Do you have a minimal repro that we can run locally and test with?

**Comment by carbonete** [comment]
Hi @nirinchev , sorry i think i not describe correct the problem. This occurs when i access RealmApp.AllUsers, to list users connect to realm. Fig 1 show user loggedin and Fig 2 Profile properties all Null.

![image](https://user-images.githubusercontent.com/3043885/123006151-a8286080-d38d-11eb-9c44-679c7097912a.png)

and profile propertie

![image](https://user-images.githubusercontent.com/3043885/123006332-df970d00-d38d-11eb-89b3-d31789529e83.png)

**Comment by nirinchev** [comment]
Hm... that is suspicious - do you get that immediately after logging a user in or after restarting the app?

**Comment by carbonete** [comment]
After Restarting app.

**Comment by nirinchev** [comment]
Thanks, I confirmed that this is indeed a bug in Core. I filed https://github.com/realm/realm-core/issues/4775 to track this and will close the .NET issue as once the Core bug is resolved, we'll automatically pick it up (i.e. there's no .NET work that needs to be done).

Unfortunately, I don't see a workaround at this point other than copying the user profile data immediately upon login to a local Realm and cross-referencing that whenever you need to iterate `AllUsers`.
