### ISSUE TITLE
Delete User from realm server not remove local 

### ISSUE THREAD

**Issue by carbonete** [realm/realm-dotnet#2466]
## Goals

Remove User through Realm web portal, not remove local user when app starts.

## Expected Results

Local user must be removed If deleted from server.

## Actual Results

RealmApp.AllUsers return user deleted  from APP Users through Realm web portal.

## Steps to Reproduce

Register and make user login at local app.

Delete user at Realm Web Portal

![image](https://user-images.githubusercontent.com/3043885/123140594-d8bfd700-d42d-11eb-8df4-2bc3944ac97a.png)

- Flavor:
  - [x ] MongoDB Realm
  - [ ] Local Database only
- Client SDK Version: ? .Net 10.2.0
- Client OS & Version: ? Xamarin Forms UWP 5.0

**Comment by nirinchev** [comment]
The `realmApp.AllUsers` is a collection persisted locally and users will be removed only when they log out locally or when the app detects that a user's refresh token is invalidated. When a deleted user tries to call some server-side functionality - either open a synchronized Realm, call a function, or otherwise interact with the server, the SDK will try to refresh the access token, get a 401 error from the server and remove the local user.

**Comment by carbonete** [comment]
Hi, thanks for explanation. 
But SDK is not removing User after a error to refresh access token. Every time starting app , user exist in AllUsers and error occurs. Error = InvalidSession: invalid session: failed to find refresh token

I try put before RefreshCustomDataAsync , var t = user.RefreshToken; that not receive any error and not resolve.

Ex:

foreach (var user in RealmApp.AllUsers)
            {
           try
            {
                       await user.RefreshCustomDataAsync();
                      userExtension = user.GetCustomData<UserExtension>();

            }
            catch (Exception ex)
            {
                var s = ex;
                userExtension = null;
            }
 
            }

**Comment by nirinchev** [comment]
You're right - this was fixed in https://github.com/realm/realm-core/pull/4747/ but that fix hasn't been released in the .NET SDK yet. We're hoping to do a patch release that picks it up at some point next week.

**Comment by carbonete** [comment]
Thanks, I will wait and test.

**Comment by nirinchev** [comment]
This should now be fixed with the latest release (10.3.0).
