### ISSUE TITLE
IDictionary not work in User custom data 

### ISSUE THREAD

**Issue by carbonete** [realm/realm-dotnet#2476]
## Goals

Recover user custom data that contains IDictionary

## Expected Results

Recover this document

```
{"_id":"60d890e993476a0f1dd4cea0",
"_partitionKey":"60d890e993476a0f1dd4cea0",
"Devices":{"b500d101-c953-4cbf-a3c8-c36de42747cc":"DESKTOP-T7SJQJ0"},
"Email":"----@----.com",
"MaxDevices":{"$numberLong":"2"},
"RecoveryAnswer":"4",
"RecoveryQuestion":"2+2"}
```
## Actual Results

"Element 'Devices' does not match any field or property of class LexSemanticAppSyncPersistence.Model.UserExtension."

## Code Sample

```
    public class UserExtension : RealmObject
    {
        [PrimaryKey]

        public string _id { get; set; }

        [Required]
        public string _partitionKey { get; set; }

        [Required]
        public string Email { get; set; }

        [Required]
        public string RecoveryQuestion { get; set; }

        [Required]
        public string RecoveryAnswer { get; set; }

        public int MaxDevices { get; set; } = 2;
        
        [Required]
        public IDictionary<string,string> Devices { get; } /* unique id , device name */

        #region Constructor
        public UserExtension(string id, string partition)
        {
            this._id = id;
            this._partitionKey = partition;
        }

        public UserExtension() { }

        #endregion
    }
```

===========================================

```
        public async Task<UserExtension> GetCurrentUserExtension(User user)
        {
            UserExtension userExtension;
            try
            {
                await user.RefreshCustomDataAsync();
                userExtension = user.GetCustomData<UserExtension>();
            }
            catch (Exception ex)
            {
                var m = ex;
                throw;
            }
            return userExtension;
        }
```

======================================================
```
        public string CreateUserExtension(string deviceId, string deviceName, string email, string question, string answer)
        {
            try
            {
                UserExtension = new UserExtension(RealmUser.Id, RealmUser.Id);
                UserExtension.Email = email;
                UserExtension.RecoveryQuestion = question;
                UserExtension.RecoveryAnswer = answer;
                UserExtension.Devices.Add(deviceId, deviceName);
                RealmInstance.Write(() => { RealmInstance.Add(UserExtension); });
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
            return string.Empty;
        }
```

## Version of Realm and Tooling

- Flavor:
  - [x] MongoDB Realm
  - [ ] Local Database only
- Client SDK Version: ? .Net 10.2.0
- Client OS & Version: ? Windows 10  Xamarin Forms 5

**Comment by nirinchev** [comment]
The model in which you deserialize CustomData does not have to inherit from RealmObject - it can be a POCO. My guess here is that the deserializer cannot set `Devices` because it's a getter only property. Can you try to create a copy of `UserExtension` that doesn't inherit from RealmObject and has a setter for the `Devices` property and check if the serializer will be happy?

**Comment by carbonete** [comment]
@nirinchev I make copy and include Set in Devices property. They work to read, user.GetCustomData<UserExtensionCopy>(); , but now I have two class, one to insert data and other operations in CustomData collection and this copy.

**Comment by nirinchev** [comment]
Yeah, that's true. Those are fundamentally different pieces of functionality, which is why we haven't really considered use cases where you'd like to both insert custom data via Sync and read the custom data via the User. What we typically see people use (and the way we modeled these API) is they either use custom data, which is populated server-side and read it on the client or they just use Sync and store anything user related in a per-user Realm (e.g. partitioned on the user id). Can you clarify a little bit your use case and why do you need to access the data both via Realm and the CustomData API?

**Comment by carbonete** [comment]
I think we will discuss is conceptual. One think I choose Realm .NET is that i don't want making use of ORM or serializations. I don't want access anything using custom data api.
At Git one feature is ,
"Simple: Data is directly exposed as objects and queryable by code, removing the need for ORM's riddled with performance & maintenance issues. Plus, we've worked hard to keep our API down to just a few common classes: most of our users pick it up intuitively, getting simple apps up & running in minutes."

In this case i need to understand Bson Document way.   

Anything I want to make with this collection i cant use the simple way this is special i need to use different way. 

For example we have a Devices Dictionary, add or delete device is simple.
RealmInstance.Write(() => { UserExtension.Devices.Add(deviceId, deviceName); });
or
RealmInstance.Write(() => { UserExtension.Devices.Remove(deviceId); });

I think i will need rethink use i made  custom data.

**Comment by nirinchev** [comment]
If you already have the `UserExtension` instance, there's not much point in trying to access it via `CustomData` - the information stored there will be exactly the same.

**Comment by carbonete** [comment]
@nirinchev  Yes, but i have a page that list AllUsers, in this case i need in every user create Realm Instance  and ,i'm not sure, switch to user to turn it current, and access data ?

**Comment by nirinchev** [comment]
I see - yes, in that case it'd be much better to use the custom data API. Unfortunately, I don't see a workaround beside having two almost identical model classes.

**Comment by carbonete** [comment]
I have a case, i control user list device and max number of contract devices. If user login in a new device and exceed max devices, they need remove from my list and if try access through  removed device , update removing local user.

**Comment by carbonete** [comment]
I review my flow, to adapt
