### ISSUE TITLE
realm::InvalidDatabase: Invalid top array size

### ISSUE THREAD

**Issue by Dany2697** [realm/realm-dotnet#2485]
Good morning,
recently, I've found an exception in my application about Realm :

 /usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:72: abort_message: assertion "terminating with uncaught exception of type realm::InvalidDatabase: Invalid top array size (ref: 41497584, size: 0)

If it's possible, I would like to have more informations about the cause of this error and, in case, a possible solution.
If it will be necessary, I will try to provide you more details.

Thank you.

Daniele

## Version of Realm and Tooling

Realm Version : 10.1.0

**Comment by nirinchev** [comment]
@simonask, as far as I can remember, this typically indicates corruption. Is there anything more we can infer from inspecting the Realm file or give the user more information about the circumstances that may lead to this?

**Comment by nirinchev** [comment]
@finnschiermer reassigning to you as Simon is out this week.

**Comment by nirinchev** [comment]
@Dany2697 if you send us the Realm file, the Core team can try and analyze it.
