### ISSUE TITLE
Custom logging has deprecated API with no replacement

### ISSUE THREAD

**Issue by ChaseFlorell** [realm/realm-dotnet#2493]
## Goals

When I try and setup  a custom logger on my App Config, I get a message saying the API is obsolete

```csharp
        [Obsolete("Configure the global RealmConfiguration.Logger instead")]
        public Action<string, LogLevel> CustomLogger { get; set; }
```

However, when I try an use RealmConfiguration.Logger, the API doesn't exist

## Expected Results

I should have access to set a custom logger

## Actual Results

no custom logger

## Steps to Reproduce
![image](https://user-images.githubusercontent.com/471626/124304365-71361580-db18-11eb-985c-17d33e7c497d.png)
![image](https://user-images.githubusercontent.com/471626/124308028-7ea1ce80-db1d-11eb-8779-ef7d6bea6d92.png)

## Version of Realm and Tooling

- Flavor:
  - [x] MongoDB Realm
  - [ ] Local Database only
- Client SDK Version: ? 10.2.1
- Client OS & Version: ?

**Comment by nirinchev** [comment]
This is an error in the API docs - you can use the standalone Logger class:

https://github.com/realm/realm-dotnet/blob/19d4a60fa477670bd437b6bf5e223a1f6a176467/Realm/Realm/Logging/Logger.cs#L71

**Comment by ChaseFlorell** [comment]
Excellent, thank you!
Should we leave this issue open until the docs are updated?

**Comment by nirinchev** [comment]
Yeah, I'll fix that next week and close the issue, thanks!
