### ISSUE TITLE
Security breach ?

### ISSUE THREAD

**Issue by carbonete** [realm/realm-dotnet#2494]
## Goals

No applicationID is public.

## Actual Results

Windows folder with ApplicationID is created :

![image](https://user-images.githubusercontent.com/3043885/124394454-e26ef780-dcd5-11eb-873c-bbaaa826c41c.png)

With this code all APP methods is accessible, like register user, login etc.

## Version of Realm and Tooling

- Flavor:
  - [x] MongoDB Realm
  - [ ] Local Database only
- Client SDK Version: ? .Net 10.2.0
- Client OS & Version: ? Windows

**Comment by nirinchev** [comment]
The app Id is not secret information and can easily be obtained by anyone motivated enough. If you wish to prevent users from registering, you should employ a different mechanism for that, such as using a confirmation function rather than email.

**Comment by carbonete** [comment]
@nirinchev Not only register, but all data from APP class , including AllUsers, actual User, custom user and if not encrypt local db with secret key they access user data. I'm wrong ?

**Comment by nirinchev** [comment]
All that data does not depend on the app id. It's stored locally and we advise users to always encrypt it or to avoid persisting it. An attacker that has access to the device storage can read any unencrypted data regardless of whether they know the app id or not. Again, the app id is super easy to guess or sniff and is not meant in any way as a security mechanism.

The app configuration class allows you to specify the metadata persistence mode. If you choose not to persist the user metadata, then Realm will not store the user access token locally, so an attacker won't be able to impersonate the user. If you choose to encrypt the metadata, then you need to supply an encryption key and an attacker won't be able to read AllUsers/CurrentUser unless they obtain the encryption key. If you do decide to store the metadata unencrypted, an attacker with access to the filesystem will be able to read the user access token, regardless of whether they know the app id or not. We generally don't recommend this mode outside of development unless there are other controls in place to encrypt the hard disk (e.g. iOS and Windows have options to do so), meaning that an attacker would need to first break through the OS user authentication.

Let me know if that information helps put things into context or if you still feel there's a possible attack that we're not seeing, please outline it and we can evaluate.

**Comment by carbonete** [comment]
@nirinchev thanks your information clarify my doubts and sorry about  my ignorance about encryption of user metadata. Only suggestion is made default encryption in all OS like made in IOS. 

Thanks for help.
