### ISSUE TITLE
[Bug]: IDictionary not found Key

### ISSUE THREAD

**Issue by carbonete** [realm/realm-dotnet#2517]
### What happened?

When try to verify if a Key exist they return false, but when iterate through KEYS i found it.

### Repro steps

See code 

### Version

10.3.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### What type of application is this?

Xamarin

### Host OS and version

Windows 10 

### Client OS and version

Windows 10

### Code snippets

== Data Class ==
   public class UserExtension : RealmObject
    {
        [PrimaryKey]

        public string _id { get; set; } /* user Id */

        [Required]
        public string _partitionKey { get; set; } /* user Id */

        [Required]
        public string Email { get; set; }

        [Required]
        public string RecoveryQuestion { get; set; }

        [Required]
        public string RecoveryAnswer { get; set; }

        public int MaxDevices { get; set; } = 2;
        
        [Required]
        public IDictionary<string,string> Devices { get; } /* unique id , device name */

        #region Constructor
        public UserExtension(string id, string partition)
        {
            this._id = id;
            this._partitionKey = partition;
        }

        public UserExtension() { }

        #endregion
    }

== Document ==

{"_id":"60e602a8552102df3b737a4a",
"_partitionKey":"60e602a8552102df3b737a4a",
"Devices":{
"b500d101-c953-4cbf-a3c8-c36de42747cc":"DESKTOP-T7SJQJ0",
"fbc94717-1651-462a-a7a0-2f40282607a3":"Galaxy J7 Prime"
},
"Email":"xxx@xxx.com",
"MaxDevices":{"$numberLong":"2"},
"RecoveryAnswer":"U/oOzhGsRQkniKaEj5iFx6aQfes=",
"RecoveryQuestion":"2+2"}

=== DeviceId Content ===
App.AppEnvironmentService.UniqueDeviceId = "b500d101-c953-4cbf-a3c8-c36de42747cc"

=== Code ===

// read data 
UserExtension = realmInstance.All<UserExtension>().Where(u => u._id == realmUser.Id).FirstOrDefault();

//iteract through and found match key
                    foreach (var item in syncDB.UserExtensionData.Devices.Keys)
                    {
                        var b = item == App.AppEnvironmentService.UniqueDeviceId; // return TRUE when match 
                    }

// this all failed 
bool c = syncDB.UserExtensionData.Devices.TryGetValue(App.AppEnvironmentService.UniqueDeviceId,out t); // return FALSE

var s = syncDB.UserExtensionData.Devices[App.AppEnvironmentService.UniqueDeviceId]; // throw KeyNotFound

syncDB.UserExtensionData.Devices.ContainsKey(App.AppEnvironmentService.UniqueDeviceId) // return FALSE 

### Stacktrace of the exception/crash you're getting

```shell
System.Collections.Generic.KeyNotFoundException
  HResult=0x80131577
  Message=The given key 'b500d101-c953-4cbf-a3c8-c36de42747cc' was not present in the dictionary.
  Source=Realm
  StackTrace:
   at Realms.RealmDictionary`1.get_Item(String key)
   at LexSemanticClient.ViewModel.LoginViewModel.<HasAuthSaved>d__77.MoveNext() in C:\Users\scf\Source\Repos\Utilities\LexSemanticClient\LexSemanticClient\ViewModel\LoginViewModel.cs:line 545
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at LexSemanticClient.Services.AppEnviromentService.<OpenAsyncDB>d__129.MoveNext() in C:\Users\scf\Source\Repos\Utilities\LexSemanticClient\LexSemanticClient\Services\AppEnviromentService.cs:line 369
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at LexSemanticClient.App.<OnStart>d__37.MoveNext() in C:\Users\scf\Source\Repos\Utilities\LexSemanticClient\LexSemanticClient\App.xaml.cs:line 222

  This exception was originally thrown at this call stack:
    [External Code]
    LexSemanticClient.ViewModel.LoginViewModel.HasAuthSaved() in LoginViewModel.cs
    [External Code]
    LexSemanticClient.Services.AppEnviromentService.OpenAsyncDB() in AppEnviromentService.cs
    [External Code]
    LexSemanticClient.App.OnStart() in App.xaml.cs
```

**Comment by nirinchev** [comment]
Thanks for the report, this definitely looks suspicious, we'll try to reproduce it and get back to you.

**Comment by papafe** [comment]
Hi @carbonete, I have tried to reproduce your error but I couldn't. Would it be possible for you to create a sample project with the issue and send it to us privately?

**Comment by carbonete** [comment]
Hi @papafe , sorry but i forgot some information. This collection is SYNC, and Realm is encrypted and this collection is linked to User Custom Data. I detected this problem after update to Realm 10.3.0.
When i run same test today they work well. I'm closing and if happens again open a new ticket.
