### ISSUE TITLE
[Bug]: Invalid references 

### ISSUE THREAD

**Issue by carbonete** [realm/realm-dotnet#2526]
### What happened?

Two invalid references is added to projects. I try delete this but they added again. Both references paths apparently to IOS and Mac binaries. 

### Repro steps

Add Realm  nuget to xamarin forms and android, IOS and UWP projects. This references not added to Forms project.
![image](https://user-images.githubusercontent.com/3043885/125852847-d8a0761d-b672-4f3e-9d58-cce809a31103.png)
![image](https://user-images.githubusercontent.com/3043885/125852733-a10167c2-91c2-4212-8d85-35de09692f40.png)
![image](https://user-images.githubusercontent.com/3043885/125853180-3bf5541d-f6bc-459f-96da-1b91189ee5cb.png)

### Version

10.3.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### What type of application is this?

Xamarin

### Host OS and version

Windows 10 

### Client OS and version

Windows 10

**Comment by papafe** [comment]
Hi @carbonete, I did not manage to reproduce this issue. Would it be possible for you to send us a project where this issue is present?

**Comment by LaPeste** [comment]
Hi @carbonete. This is not the first time we hear about this problem. You can see this [here](https://github.com/realm/realm-dotnet/issues/1360) and [here](https://github.com/realm/realm-dotnet/issues/2297).
As I said already in that github issue 2297:
_you can verify by yourself the fact that those refs aren't included, just by decompressing the built binary and looking into the folder to see what libs are imported. You should not see any of the dylib listed in VS._

**Comment by papafe** [comment]
Hi @carbonete, given what @LaPeste said I am going to close this ticket. Feel free to reach out to us if you have additional questions
