### ISSUE TITLE
Keep examples in repository updated and add them to CI

### ISSUE THREAD

**Issue by papafe** [realm/realm-dotnet#2527]
We need to find a way to keep the examples in the repository updated, maybe at least to jump the realm version every time we have a new major version. It would also be convenient to build examples on CI to be sure they're always working

**Comment by nirinchev** [comment]
We can automatically bump the version when doing a release as part of the release workflow: https://github.com/realm/realm-dotnet/blob/master/.github/workflows/release.yml.
