### ISSUE TITLE
Add survey CTA to all Realm SDK readmes 

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-dotnet#2542]
Use https://github.com/realm/realm-dotnet/pull/2541 as model. Needs to be added to all SDKs, which if I remember correctly are dart, js, kotlin, java, and cocoa but may be missing something.

- [x] dart: https://github.com/realm/realm-dart/pull/108
- [x] js: https://github.com/realm/realm-js/pull/3871
- [x] kotlin: https://github.com/realm/realm-kotlin/pull/362
- [x] java: https://github.com/realm/realm-java/pull/7529
- [x] cocoa: https://github.com/realm/realm-cocoa/pull/7339
- [x] dotnet: https://github.com/realm/realm-dotnet/pull/2541

**Comment by DominicFrei** [comment]
Updated the description with the links to the PRs. @LaPeste has already taken core of that but I guess we only want to close this ticket when everything is merged. 👍

**Comment by DominicFrei** [comment]
Last PR was just merged. 👍
