### ISSUE TITLE
Support win-arm outside of UWP

### ISSUE THREAD

**Issue by boswelja** [realm/realm-dotnet#2545]
### Description

Right now, it looks like Windows on ARM is supported via UWP projects, but it would be nice to get native builds too.
For context, I'm working on bringing osu!lazer to Windows on ARM devices, and Realm throws DLLNotFoundException if the project isn't a UWP project.
I have a Surface Pro X for testing, so I'll have a go at building Realm and running some tests in the meantime.

### How important is this improvement for you?

Would be a major improvement

**Comment by papafe** [comment]
Hi @boswelja, you're correct in saying that at the moment we support ARM only in UWP projects. We are going to look into it though!

**Comment by fealebenpae** [comment]
#2819 added support for win-arm64 for both UWP and regular apps. We have no plans to add support for 32bit win-arm outside of UWP.
