### ISSUE TITLE
Fix API docs for NotificationCallbackDelegate

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-dotnet#2546]
https://docs.mongodb.com/realm-sdks/dotnet/latest/reference/Realms.NotificationCallbackDelegate-1.html - `changes` will be `null` the first time the callback is invoked. There's also a typo where it says `or null if an has error occurred`.

**Comment by DominicFrei** [comment]
https://github.com/realm/realm-dotnet/blob/77364559c8c9f6143f90f753a39ee096a9f1b09d/Realm/Realm/Linq/IRealmCollection.cs/#L157 probably also needs to be updated, the summary described the same `each time`:
```
/// <summary>
/// Register a callback to be invoked each time this <see cref="IRealmCollection{T}"/> changes.
/// </summary>
```

**Comment by nirinchev** [comment]
Interestingly, the remarks in the linked-to code correctly describe the behavior of the notifier. I guess we need to copy some of those into the `NotificationCallbackDelegate` API docs.
