### ISSUE TITLE
Make RealmSet queryable

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-dotnet#2555]
### Description

Similar to https://github.com/realm/realm-dotnet/issues/1499 but for `ISet`.
See https://github.com/realm/realm-dotnet/issues/2647 for dictionary.

### How important is this improvement for you?
Fairly niche, but nice to have anyway

**Comment by carbonete** [comment]
It's useful and create facility. At #1499 example this have [IGNORED] and will calculate at runtime, but it's possible result write and  indexed to global query of all objects in this collection ?

I have a new doubt after read this. It's possible to have like a static class properties in Realm Object  ? 
I have a case that i need  create many to many relation , where the second class is only a string indexed. To determine if exist in a list of first class without need to read all objects and interact through list . They can be exist in more than one object of first class.

Bsr
Carbonete

**Comment by nirinchev** [comment]
I'm sorry, it's really difficult to understand what you mean. Can you try rewording it, possibly with code snippets so that we can see what you're trying to achieve.

**Comment by DominicFrei** [comment]
Related issues / PRs:
- https://github.com/realm/realm-dotnet/pull/2554
- https://github.com/realm/realm-dotnet/issues/2555

**Comment by carbonete** [comment]
> I'm sorry, it's really difficult to understand what you mean. Can you try rewording it, possibly with code snippets so that we can see what you're trying to achieve.

Sorry for my bad communication.
Maybe this code clarifying.

    public class FavoriteList : RealmObject
    {
       public static IDictionay<FavoritedVerbete, List<FavoriteList.Name>> AllFavoritedVerbetes; /* only illustratoin this will valid for all objects _partitionKey to sync maybe a challenger*/

        [PrimaryKey]
        public string _id { get; set; } = Guid.NewGuid().ToString("N");

        [Required]
        public string _partitionKey { get; set; } /* user Id */

        [Required]
        [Indexed]
        public string Name { get; set; }

        [Required]
        public string Description { get; set; }

        public IList<string> FavoritedVerbetes { get; }

        #region Constructor
        public FavoriteList( string partition, string name)
        {
            this._partitionKey = partition;
            this.Name = name;
        }
      
public Favorite(string) 
{
add to FavoritedVerbetes and to AllFavoriteVerbetes
}
        public FavoriteList() { }
        #endregion

    }

In substituition of 

    public class FavoriteList : RealmObject
    {
        [PrimaryKey]
        public string _id { get; set; } = Guid.NewGuid().ToString("N");

        [Required]
        public string _partitionKey { get; set; } /* user Id */

        [Required]
        [Indexed]
        public string Name { get; set; }

        [Required]
        public string Description { get; set; }

        public IList<FavoritedVerbete> FavoritedVerbetes { get; }

        #region Constructor
        public FavoriteList( string partition, string name)
        {
            this._partitionKey = partition;
            this.Name = name;
        }

        public FavoriteList() { }

        #endregion

    }

 public  class FavoritedVerbete : RealmObject
    {
        [PrimaryKey]
        public string _id { get; set; } = Guid.NewGuid().ToString("N");

        [Required]
        public string _partitionKey { get; set; } /* user Id */

        [Required]
        [Indexed]
        public string Name { get; set; }

        [Backlink(nameof(FavoriteList.FavoritedVerbetes))]
        public IQueryable<FavoriteList> FavoriteLists { get; }

        #region Constructor
        public FavoritedVerbete(string partition, string verb)
        {
            this._partitionKey = partition;
            this.Name = verb;
        }

        public FavoritedVerbete() { }

        #endregion

**Comment by DominicFrei** [comment]
Issue is divided into two parts now. This will keep the set part, the dictionary was moved to https://github.com/realm/realm-dotnet/issues/2647.
