### ISSUE TITLE
Remove unnecessary InvalidOperationException

### ISSUE THREAD

**Issue by papafe** [realm/realm-dotnet#2559]
It seems that we throw an unnecessary InvalidOperationException when we build an ObjectSchema and object has no properties. Fody should throw a compiler exception if this is the case.

https://github.com/realm/realm-dotnet/blob/250d5bfe01f330fe863061cabd6501fc66b39977/Realm/Realm/Schema/ObjectSchema.cs#L173-L185

**Comment by nirinchev** [comment]
Technically, it's possible that someone creates the schema manually - I recommended exactly that to a user recently: https://www.mongodb.com/community/forums/t/how-to-add-dynamicrealmobject/119228/8?u=nirinchev. That being said, that link in the exception message is... 😬

We'll eventually want to expose the schema API publicly, so we should probably look into what validations make and don't make sense at that point.

**Comment by papafe** [comment]
I see your points... I'll fix at least the message :)
