### ISSUE TITLE
Ignore base properties when serializing RealmObjects

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-dotnet#2579]
### Description

RealmObject inheritors should only serialize their own properties when using Json.NET/System.Text.Json. Currently, a bunch of base properties will be added to the json string without offering any value. While users can customize serialization, it's a bit of a hassle and we should do our best to have the SDK just work.

### How important is this improvement for you?

Fairly niche, but nice to have anyway

**Comment by DoubleDBE** [comment]
This doesn't work when using System.Text.Json (using .NET 7, .NET 6 also doesn't work).

This is because it's [not supported out of the box](https://devblogs.microsoft.com/dotnet/system-text-json-in-dotnet-7/#example-custom-attribute-support)

The solution would be to also add `[System.Text.Json.Serialization.JsonIgnore]` attributes.

I'd be happy to create a PR for this!

**Comment by nirinchev** [comment]
Good find. This will be somewhat complicated because we'll need to add this attribute only in the .NET 6 version of the assembly, but not the .net standard 2.0 one. Also, it'll need to be done for both the base classes as well as the source generated classes. If you're up for it, feel free to open a PR, otherwise I'll probably pick it up after we ship the v11 release.

**Comment by DoubleDBE** [comment]
Well, System.Text.Json's nuget package supports .NET standard 2.0.

This brings another dependency only for using those attributes and is understandably not desired.

Another option is to create a dummy attribute that will be used for .NET standard 2.0:

`internal class DummyJsonIgnoreAttribute : Attribute { }`

Then this can be easily used with a using directive:

![image](https://user-images.githubusercontent.com/45478482/224991383-16115ac4-b52b-484d-94a5-13eb71b14aef.png)

and results in usage like this:

![image](https://user-images.githubusercontent.com/45478482/224992129-9e34e8da-41b3-4020-b08b-e2413e755099.png)

Another option is going with the ugly one:

![image](https://user-images.githubusercontent.com/45478482/224992285-190cfb4b-4c50-4dc7-a39f-707eccb0d975.png)

As for the source generators, that is outside my experience but I could give it a shot.

**Comment by DoubleDBE** [comment]
Hi @nirinchev,

Do you have a preference on what option I should use?

**Comment by nirinchev** [comment]
Looking at the source code for System.Text.Json, it appears like they're matching the custom attribute by name, not type, so you could try "polyfilling" the attribute for .NET Standard:

```csharp
#if NETSTANDARD2_0
namespace System.Text.Json.Serialization
{
    /// <summary>
    /// Prevents a property or field from being serialized or deserialized.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Field, AllowMultiple = false)]
    internal sealed class JsonIgnoreAttribute : JsonAttribute
    {
        /// <summary>
        /// Specifies the condition that must be met before a property or field will be ignored.
        /// </summary>
        /// <remarks>The default value is <see cref="JsonIgnoreCondition.Always"/>.</remarks>
        public JsonIgnoreCondition Condition { get; set; } = JsonIgnoreCondition.Always;

        /// <summary>
        /// Initializes a new instance of <see cref="JsonIgnoreAttribute"/>.
        /// </summary>
        public JsonIgnoreAttribute() { }
    }

    /// <summary>
    /// When specified on <see cref="JsonSerializerOptions.DefaultIgnoreCondition"/>,
    /// determines when properties and fields across the type graph are ignored.
    /// When specified on <see cref="JsonIgnoreAttribute.Condition"/>, controls whether
    /// a property or field is ignored during serialization and deserialization. This option
    /// overrides the setting on <see cref="JsonSerializerOptions.DefaultIgnoreCondition"/>.
    /// </summary>
    internal enum JsonIgnoreCondition
    {
        /// <summary>
        /// Property is never ignored during serialization or deserialization.
        /// </summary>
        Never = 0,
        /// <summary>
        /// Property is always ignored during serialization and deserialization.
        /// </summary>
        Always = 1,
        /// <summary>
        /// If the value is the default, the property is ignored during serialization.
        /// This is applied to both reference and value-type properties and fields.
        /// </summary>
        WhenWritingDefault = 2,
        /// <summary>
        /// If the value is <see langword="null"/>, the property is ignored during serialization.
        /// This is applied only to reference-type properties and fields.
        /// </summary>
        WhenWritingNull = 3,
    }
}
#endif
```
