### ISSUE TITLE
Crash upon bumping Realm to 10.4.0 on older linux distros due to apparent GLIBCXX version incompatibility

### ISSUE THREAD

**Issue by bdach** [realm/realm-dotnet#2602]
### What happened?

Hi,

I'm a contributor on https://github.com/ppy/osu (a cross-platform .NET Core game). During reviews of recurring dependabot PRs it has come to my attention that upon bumping Realm from 10.3.0 to 10.4.0 the game would no longer launch on my system.

This is likely specific to my system, as I am on a bit of a "stale" system, you could say (details in the fields below), as it seems that there is a GLIBCXX version incompatibility that prevents the dynamic linker from successfully loading `realm-wrappers`, but looking at the changelog I am not really sure whether that is an intentional breakage or something that just happened by accident, which is mostly why I am opening this issue. If this is indeed deliberate, then feel free to close this immediately.

### Repro steps

1. Clone https://github.com/ppy/osu
2. Bump all references to Realm from 10.3.0 to 10.4.0
3. Attempt to run the `osu.Desktop` project
4. The game crashes with instantly upon first realm access

### Version

5.0.302

### What SDK flavour are you using?

Local Database only

### What type of application is this?

Other

### Client OS and version

Ubuntu 18.04.5 LTS x86_64, kernel: 4.15.0-154-generic

### Stacktrace of the exception/crash you're getting

.NET stacktrace is:

```shell
[runtime] 2021-09-01 18:03:50 [error]: System.DllNotFoundException: Unable to load shared library 'realm-wrappers' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: librealm-wrappers: cannot open shared object file: No such file or directory
[runtime] 2021-09-01 18:03:50 [error]: at Realms.SynchronizationContextScheduler.install_scheduler_callbacks(get_context get, post_on_context post, release_context release, is_on_context is_on)
```

LD_DEBUG shows:

```shell
     20597:     /usr/lib/x86_64-linux-gnu/libstdc++.so.6: error: version lookup error: version `GLIBCXX_3.4.26' not found (required by /home/dachb/Dokumenty/opensource/osu/osu.Desktop/bin/Debug/net5.0/runtimes/linux-x64/native/librealm-wrappers.so) (fatal)
```

`strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25 | grep GLIBCXX` shows `GLIBCXX_3.4.25` as the highest version symbol defined.

**Comment by nirinchev** [comment]
Hey, thanks for reporting that and apologies for the regression. You're right - that was definitely unintentional and my best guess is that this is due to switching the release build from Jenkins (running on Ubuntu 18.04) to Github Actions, which is running on 20.04.

I'll ping our build gurus tomorrow to confirm if that's the case - it should be fairly easy to hotfix if it is.

**Comment by nirinchev** [comment]
Hey @bdach I believe we have a fix for the regression - can you try on your end and confirm if this version works on your machine: [Realm.10.4.1.zip](https://drive.google.com/file/d/1PPiHLCqw4Rv-o2GT8kufPD9JOIOUxCTA/view?usp=sharing)?

**Comment by bdach** [comment]
Sorry for the late response, I wasn't in a position to test yesterday. I've checked 10.4.1 today and it looks to be working perfectly fine now.

Thanks for the prompt handling of the issue!

**Comment by nirinchev** [comment]
No worries, thanks again for the report and happy to hear things are working now!
