### ISSUE TITLE
Unity: Multiple precompiled assemblies with the same name Mono.Cecil.dll included or the current platform.

### ISSUE THREAD

**Issue by Faketa** [realm/realm-dotnet#2630]
### What happened?

After import the latest release I've get the below error:
Multiple precompiled assemblies with the same name Mono.Cecil.dll included or the current platform.

My Unity packages uses "com.unity.nuget.mono-cecil@1.10.1-preview.1".

### Repro steps

Import the latest release of the Realm SDK into the Unity

### Version

5

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### What type of application is this?

Unity

### Client OS and version

Windows 10 Pro

**Comment by nirinchev** [comment]
Realm uses Mono.Cecil in the editor plugin to weave the C# models on compilation. Are you including Mono.Cecil with your game or are you also using it for compile-time modifications? One option would be to remove your dependency on Mono.Cecil and use the one bundled with Realm. Alternatively, we could look into embedding it into the editor plugin to avoid conflicts like that.

**Comment by Faketa** [comment]
Hi, thanks for your answer. Unfortunately, MLAPI package depends on Mono.Cecil DLL internally. I can't change that. Is there any solution for such a case?
