### ISSUE TITLE
Creating a realm instance via xUnit crashes

### ISSUE THREAD

**Issue by peppy** [realm/realm-dotnet#2642]
### What happened?

- Attempt to create a new realm context in a test
- Receive incorrect thread error

### Repro steps

```sh
git clone https://github.com/peppy/osu-realm-structural-integrity
cd osu-realm-structural-integrity
git checkout help
dotnet test
```

Relevant repo: https://github.com/peppy/osu-realm-structural-integrity/tree/help

Changing the filename to a constant filename (ie. not using `Guid.New`) will fail the first run but pass the second. Note that this failure is at a native level and halts the test runner, meaning all further tests also fail and no managed `Exception` is thrown. Pretty scary.

### Version

10.5.0

### What SDK flavour are you using?

Local Database only

### What type of application is this?

Console/Server

### Client OS and version

macOS 12.0

### Relevant log output

```shell
❯ dotnet test
  Determining projects to restore...
  Restored /Users/dean/Projects/temp/osu-realm-structural-integrity/RealmStructuralIntegrity/RealmStructuralIntegrity.csproj (in 480 ms).
  RealmStructuralIntegrity -> /Users/dean/Projects/temp/osu-realm-structural-integrity/RealmStructuralIntegrity/bin/Debug/net5.0/RealmStructuralIntegrity.dll
Test run for /Users/dean/Projects/temp/osu-realm-structural-integrity/RealmStructuralIntegrity/bin/Debug/net5.0/RealmStructuralIntegrity.dll (.NETCoreApp,Version=v5.0)
Microsoft (R) Test Execution Command Line Tool Version 16.11.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
The active test run was aborted. Reason: Test host process crashed : libc++abi: terminating with uncaught exception of type realm::IncorrectThreadException: Realm accessed from incorrect thread.


Test Run Aborted.
```

**Comment by nirinchev** [comment]
This looks like some funky behavior due to xUnit's synchronization context. If you install `Nito.AsyncEx` and wrap your test code in `AsyncContext.Run(() => { /* test code */ })`, everything works as normal. We'll need to setup a test project using xUnit and debug what's going on there, but replacing the synchronization context with something better behaved should hopefully unblock you.

**Comment by peppy** [comment]
I wouldn't have suspected a `SynchronizationContext` issue as I'm not really making any synchronous calls, but I'll give that a try. Note that the linked repo/branch is as barebones a setup project as it gets, so should be a good starting point to test against (the only code in the project is this one file: https://github.com/peppy/osu-realm-structural-integrity/blob/help/RealmStructuralIntegrity/UsageTests.cs).

**Comment by peppy** [comment]
Nesting each test inside `AsyncContext.Run` does work, thanks.

**Comment by nirinchev** [comment]
Yeah, it's not intuitive, but even for synchronous operations, Realm needs to check sometimes that it's being accessed from the correct thread. If there's a synchronization context installed, we proxy these checks to it and essentially ask it if we're still on the original thread. If for some reason, it returns `false`, we assume that we're on a different thread now, even if we aren't. This hasn't been an issue with the Nito.AsyncEx context or the various main thread synchronization contexts on Xamarin, WPF, or Unity, but it seems like it is for xUnit. We'll probably have to special case it in some way, but until we dive deeper into it, it's hard to tell what the fix should look like.

**Comment by peppy** [comment]
That make a lot more sense, thanks for the explanation. Although I'm still a bit confused by it seeming to be a native crash if the thread checks are being done via synchronization contexts - is that just the way the realm error handler is run after the check fails?

**Comment by nirinchev** [comment]
Yeah, I'm not sure why this is a native crash - it should have been bubbled up to a normal .NET exception. My theory for what is happening is: 
1. We call "open Realm" in native and pass in the synchronization context.
2. Some stuff goes on in native and it tries to check if we're still on the original Realm thread.
3. That calls into managed, asks the synchronization context, which for some reason returns `false`.
4. The incorrect thread exception is thrown in native.
5. --> Here, we should have caught that and converted it into a managed C# exception and rethrown it from `Realm.GetInstance`.

Something in 5. seems to be going wrong but I don't have a theory for what that may be yet.

**Comment by nirinchev** [comment]
Should be fixed in https://github.com/realm/realm-dotnet/pull/2787.
