### ISSUE TITLE
Extended api for synchronous write to avoid capture in closure

### ISSUE THREAD

**Issue by peppy** [realm/realm-dotnet#2660]
### Description

While this is already the case for `WriteAsync`, it would be nice from a code quality and correctness perspective to have an overload for `realm.Write()` which provides the context inside the delegate, to avoid capturing it from outside. There are two reasons I think this is beneficial:

- Can avoid delegate allocation overhead in many cases (if there are no other captures)
- Can avoid inspections suggesting to avoid capture:

![20210927 191730 (JetBrains Rider)](https://user-images.githubusercontent.com/191335/134890389-cb005bf3-fc4c-43f7-99dc-8af540b2256e.png)

Note that we can work around the inspection by using

```csharp
using (var transaction = realm.BeginTransaction())
{
...
}
```

but it could be considered less clean.

The proposal would be to add these two new overloads to `Realm.cs`:

```csharp
        public void Write(Action<Realm> function)
        {
            ThrowIfDisposed();
            Argument.NotNull(function, nameof(function));

            using var transaction = BeginWrite();
            function(this);
            transaction.Commit();
        }

        public T Write<T>(Func<Realm, T> function)
        {
            ThrowIfDisposed();
            Argument.NotNull(function, nameof(function));

            using var transaction = BeginWrite();
            var result = function(this);
            transaction.Commit();
            return result;
        }
```

If deemed as a valid direction I'm willing to PR the changes, if that helps.

### How important is this improvement for you?

I'd like to see it, but have a workaround

**Comment by LaPeste** [comment]
Hi Peppy,

Thank you very much for the suggestion. While we fully understand where you're coming from, unfortunately we don't believe that it's a good idea for us to implement the suggested change.
The reason being that:
* If we keep both methods, the one you proposed and the current one, new users could get confused. 
* If instead we add the proposed method and deprecate the previous one, many users will get very frustrated when seeing the warning.
* The signature and functionality you proposed can be easily obtained with a small extension method.


But again, I'd like to re-iterate how much we appreciate community engagement. So thank you again for having taken the time to write the post.

Andrea

**Comment by peppy** [comment]
No worries, I've already added these as extension methods. We like to keep our allocation overhead very low but I can understand this isn't as important to the vast majority of users.

I'm not sure if it's best to leave this open for visibility or not, but feel free to close at your will.

**Comment by LaPeste** [comment]
Thank you again for the engagement. We really like to see our community so active :)
