### ISSUE TITLE
Always trying to access my documents in W10

### ISSUE THREAD

**Issue by hallo-w3lt** [realm/realm-dotnet#2676]
### What happened?

Hi there, I don't know if this is an error, but since version 10.X the library tries to access the user's folder (```Environment.SpecialFolder.Personal```), even when provided with the path where the realm database should be created or found.

Really everything works as it should, except that request to access the user's documents, which the anti-ransomware blocks and therefore always creates the "Documents" folder in the current directory of the binary.

This happens the first time it is run ```Realm.GetInstance(Config);```

My Config is: 

```
var config = new RealmConfiguration(path)
            {
                SchemaVersion                 = 25, 
                ShouldDeleteIfMigrationNeeded = false,
                EncryptionKey                 = phrase,
                MigrationCallback = (migration, oldSchemaVersion) =>
                {
                    if (oldSchemaVersion >= 25) return; 
                    // ....
                }
            };
```

Perhaps it has to do with reflection, when calling:

```
private static readonly List<string> _potentialStorageFolders = new List<string>
   {
            Environment.GetFolderPath(Environment.SpecialFolder.Personal),
            Path.Combine(Directory.GetCurrentDirectory(), "Documents")
   };
```

Any information would be of great help, thank you.

### Repro steps

Install Realm 10.x through Nuget.
Enable ransomware protection in Windows 10.
Check if the My Documents folder is protected.
Try to compile and deploy to the device.

### Version

Realm 10.6.0 
MongoDB.Bson 2.13.2
.Net 4.8

### What SDK flavour are you using?

Local Database only

### What type of application is this?

WPF

### Client OS and version

Windows 10 Pro 21H1

**Comment by hallo-w3lt** [comment]
Hi we want to share a demo project that we use for debugging, we add a simple database call and show how we usually instantiate the library. 

Thanks in advance. 
[Hollow.zip](https://github.com/realm/realm-dotnet/files/7358530/Hollow.zip)

**Comment by LaPeste** [comment]
Hi @hallo-w3lt, I can reproduce the issue with your last example project. It happens only with ransomware protection ON and interestingly the `Documents` folder is created in the bin folder of the app, but it's empty. Finally, the realm files are created at the specified absolute path.
I'll start working on it.

**Comment by LaPeste** [comment]
I've identified the issue and I'm working on the solution. The issue is the we eagerly create a static `RealmConfiguration.DefaultConfiguration`. That is clearly created regardless of the user passing or not an absolute path. The fix should be available in the next release.
Thank you again for having taken the time to report the issue. We truly appreciate contributions like yours.
