### ISSUE TITLE
IRealmCollection can't see all documents (because of null value in optional field?)

### ISSUE THREAD

**Issue by polymath74** [realm/realm-dotnet#2688]
### How frequently does the bug occur?

All the time

### Description

`IRealmCollection<ScoringRequest> scoringRequests = ScoresRealm.All<ScoringRequest>().AsRealmCollection();`
`while (scoringRequests.Count > 0) {` …

`scoringRequests.Count` is 0 even when there are documents in the collection, as verified by looking in the Atlas UI.

If I put in a document that has a non-null value in every field, it turns up fine. But all my documents that have null in an optional string field don't get seen. If I use the Atlas UI to add an empty string value for the optional field, then my code can see it here.

My schema is:
`{
  "title": "ScoringRequest",
  "properties": {
    "_id": {
      "bsonType": "objectId"
    },
    "_partition": {
      "bsonType": "string"
    },
    "carnival": {
      "bsonType": "objectId"
    },
    "carnivalEvent": {
      "bsonType": "objectId"
    },
    "gender": {
      "bsonType": "string"
    },
    "group": {
      "bsonType": "string"
    },
    "timestamp": {
      "bsonType": "string"
    }
  },
  "required": [
    "_id",
    "carnival",
    "carnivalEvent",
    "group",
    "_partition"
  ]
}`

The optional field that sometimes has null values is `gender`.

![image](https://user-images.githubusercontent.com/89322485/138366617-2a150b39-67ab-42bf-8348-60c334ea3d27.png)

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

1. Create a schema with an optional string field.
2. Save a new object with no value set for that field.
3. Look at `.All<>()` and see whether it turns up.

### Version

10.5.1, 10.6.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Windows 10 Pro 21H1 19043.1288

### Build environment

Microsoft Visual Studio Community 2019
Version 16.11.2
VisualStudio.16.Release/16.11.2+31624.102
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA650
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.11.75.64347
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.11.75.64347
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.11.75.64347
Azure App Service Tools v3.0.0

C# Tools   3.11.0-4.21403.6+ae1fff344d46976624e68ae17164e0607ab68b10
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Dotfuscator Community Edition   6.3.0+8b29d6f4a2
PreEmptive Protection - Dotfuscator CE

GitHub.VisualStudio   2.11.106.19330
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   5.11.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   16.1.0.2122504+13c05c96ea6bdbe550bd88b0bf6cdddf8cde1725
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   16.0.62107.28140
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.30526.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.11.0-4.21403.6+ae1fff344d46976624e68ae17164e0607ab68b10
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.11.0-beta.21322.6+488cc578cafcd261d90d748d8aaa7b8b091232dc
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

**Comment by papafe** [comment]
A fix for this issue is currently live, so I'm closing this ticket. Feel free to reopen it if you're still experiencing any issue.
