### ISSUE TITLE
[Bug]: [Android 8.1] IDictionary can't find existing key

### ISSUE THREAD

**Issue by carbonete** [realm/realm-dotnet#2689]
### What happened?

This problem occurs in Android 8.1 Samsung J7 Prime device. Not occur in emulator Android 10.0 and UWP windows 10.

Try to access IDictionary providing a key , using dic[key] and receive message Key not present in dictionary, consulting dictionary enumerator and found key.

I use same realm local encrypted db in this 3 environment.

### Repro steps

Message error
![image](https://user-images.githubusercontent.com/3043885/138475591-76dd0596-fa2e-4f5a-84d3-fb66449b079a.png)

IDictionary content

![Screenshot 2021-10-22 112939_REALM_IDICTIONARY](https://user-images.githubusercontent.com/3043885/138475807-850fd90a-d748-40db-8617-1174925e54c6.png)

### Version

Net Standard 2.0

### What SDK flavour are you using?

Local Database only

### What type of application is this?

Xamarin

### Client OS and version

Android 8.1

### Code snippets
```csharp
[Required]
public IDictionary<string, string> CatGram { get; }

about = realmInstance.All<Dictionar>().FirstOrDefault();

private Dictionar about;
public Dictionar About
{
    get { return this.about; }
}
```

**Comment by LaPeste** [comment]
@carbonete I'm closing this issue since it's been inactive for a while. But feel free to reopen it when you have a repro project.
