### ISSUE TITLE
[Bug]: Crash when goto 10.7.0 

### ISSUE THREAD

**Issue by carbonete** [realm/realm-dotnet#2718]
### What happened?

I upgrade from 10.5.0  direct to 10.7.0, app crash   Message=Continuous transaction through DB object without history information

Downgrade to 10.6.0 app works fine.

### Repro steps

Upgrade from 10.5.0 to 10.7.0 

### Version

10.7.0

### What SDK flavour are you using?

Local Database only

### What type of application is this?

Xamarin

### Client OS and version

	Microsoft Windows 10 Pro Version	10.0.19043 Build 19043

### Stacktrace of the exception/crash you're getting

```shell
Realms.Exceptions.RealmException
  HResult=0x80131500
  Message=Continuous transaction through DB object without history information
Exception backtrace:
<backtrace not supported on this platform>
  Source=Realm
  StackTrace:
   at Realms.NativeException.ThrowIfNecessary(Func`2 overrider)
   at Realms.SharedRealmHandle.Open(Configuration configuration, RealmSchema schema, Byte[] encryptionKey)
   at Realms.RealmConfiguration.CreateRealm()
   at LexSemanticDicPersistence.Context.DB.GetNewInstance() in C:\Users\scf\Source\Repos\Utilities\LexSemanticDicPersistence\Context\DB.cs:line 119
   at LexSemanticDicPersistence.Services.LexSemanticDicService.<SearchComposed>d__13.MoveNext() in C:\Users\scf\Source\Repos\Utilities\LexSemanticDicPersistence\Services\LexSemanticDicService.cs:line 247
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LexSemanticDicPersistence.Services.LexSemanticDicService.<SearchVol>d__10.MoveNext() in C:\Users\scf\Source\Repos\Utilities\LexSemanticDicPersistence\Services\LexSemanticDicService.cs:line 175
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LexSemanticClient.ViewModel.VerbeteSearchObservableCollection.<LoadSearchedCollection>d__51.MoveNext() in C:\Users\scf\Source\Repos\Utilities\LexSemanticClient\LexSemanticClient\ViewModel\VerbeteSearchViewModel.cs:line 567
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LexSemanticClient.ViewModel.VerbeteSearchObservableCollection.<LoadSearched>d__50.MoveNext() in C:\Users\scf\Source\Repos\Utilities\LexSemanticClient\LexSemanticClient\ViewModel\VerbeteSearchViewModel.cs:line 529

  This exception was originally thrown at this call stack:
    [External Code]
    LexSemanticDicPersistence.Context.DB.GetNewInstance() in DB.cs
    LexSemanticDicPersistence.Services.LexSemanticDicService.SearchComposed(string, string) in LexSemanticDicService.cs
    [External Code]
    LexSemanticDicPersistence.Services.LexSemanticDicService.SearchVol(System.Collections.Generic.IList<string>, string) in LexSemanticDicService.cs
    [External Code]
    LexSemanticClient.ViewModel.VerbeteSearchObservableCollection.LoadSearchedCollection(string) in VerbeteSearchViewModel.cs
    [External Code]
    LexSemanticClient.ViewModel.VerbeteSearchObservableCollection.LoadSearched() in VerbeteSearchViewModel.cs
```

**Comment by papafe** [comment]
Hi @carbonete,

Thanks for reporting this issue. Can you show here how you're opening the realm?
Also, are you maybe using frozen realms?

**Comment by carbonete** [comment]
@papafe I have two realm in my app one that is synced and other that is local. Synced not crash.
```
ulong schemaVersion = 1;
               realmConfigurationBase = new RealmConfiguration(Path.Combine(dir, db))
                {
                    EncryptionKey = cryptKey,
                    IsReadOnly = true,
                    SchemaVersion = schemaVersion,
                };
            realmConfigurationBase.Schema = new Type[]
            {
                typeof(Dictionar),
                typeof(GNG),
                typeof(Group),
                typeof(LexicalRelation),
                typeof(SemanticRelation),
                typeof(TextAndAuthor),
                typeof(Verbete),
                typeof(VerbeteAtGroup),
            };

            try
            {
                realmInstance = Realm.GetInstance(realmConfigurationBase);
                about = realmInstance.All<Dictionar>().FirstOrDefault();
            }
            catch (Exception err)
            {
                throw;
            }

```

**Comment by papafe** [comment]
Hi @carbonete, so far I did not manage to reproduce your issue using the same configuration you're using, passing from version 10.5 to 10.7 of Realm. 

Do you maybe have the possibility of sharing your project? 
Also I have another question. Do you get the same result if you open your realm with `IsReadOnly=false`?

**Comment by carbonete** [comment]
@papafe i can't share project, but your question about IsReadOnly = false, made me remember this issue https://github.com/realm/realm-dotnet/issues/2619 that apparently must be related, but sollution is in 10.7.0. I try open with IsReadOnly=false, and have same problem.

**Comment by carbonete** [comment]
@papafe ,making more step by step debug, this error not occurs when open realm. I need explain more detailed about logic.
1 - My app access more than 1 local realm simultaneously. In this case 3.
2 - When start a task to made search i execute Realm realm = DBPool.Instance.GetDB(dbname).GetNewInstance(); that returns realminstance to this task.
3 - I have two diferentes search tasks, execute first search task , and after end all execute second search task. 
4 - I made test made explicit realm.Dispose(), and problem not occurs, apparently when made Realm.GetInstance(realmConfigurationBase); more times is the problem. That not happen in previous version. 

Sorry about my english , i'm not sure you will understand.

thanks

**Comment by carbonete** [comment]
This is anoying problem , realm.Dispose() not resolve all, same error in another part of app.

**Comment by carbonete** [comment]
Error continuing's occurs in GetInstance(), Maybe problem is when compare if previous realm instance exists and return same instance.

**Comment by nirinchev** [comment]
Are you sure you're always opening the Realm with the exact same configuration? I.e. is it possible that in one part of the app, you're using one config and in another - a different one? Can you look for all the `Realm.GetInstance` calls in your application and verify if the configs are identical (for paths that are identical - it's perfectly fine to have different configs for different paths).

**Comment by carbonete** [comment]
@nirinchev ,  because if this the problem why not occurs in previous version ?
There is simultaneously open 3 realms.
When i introduce Dispose() problem not occurs in second search task. 
@papafe  this partial code of project.

I have a DBPoll Class that is pool of open Realms.
`    public sealed class DBPool
    {
        #region Instanciamento
        public static readonly DBPool Instance = new DBPool();
        DBPool() { }
        #endregion

        #region Pool
        private static readonly Dictionary<string, DB> pool = new Dictionary<string, DB>();
        #endregion

        #region methods

        public DB GetDB(string db)
        {
            return pool[db];
        }

        public IEnumerable<string> GetOpenDBList()
        {
            return pool.Keys.AsEnumerable();
        }

        public DB DB(string db, string dir, byte[] cryptKey, bool onlyRead)
        {
            try
            {
                if (!pool.ContainsKey(db))
                {
                    pool[db] = new DB(db, dir, cryptKey, onlyRead);
                }
            }
            catch (Exception e)
            {
                var err = e;
                throw;
            }

            return pool[db];
        }

        public void Close(string db, bool compact)
        {
            try
            {
                var status = pool[db].Dispose(compact);
                pool.Remove(db);
            }
            catch (Exception)
            {
                throw;
            }
        }

        public void CloseAll(bool compact)
        {
            foreach (var db in pool.Keys)
            {
                Close(db, compact);
            }
        }


        #endregion
    }
`
There is a DB class that administrators individual Realm's
`    public class DB
    {
        #region Properties

        private Realm realmInstance;

        private RealmConfigurationBase realmConfigurationBase;

        private Dictionar about;
        public Dictionar About
        {
            get { return this.about; }
        }

        #endregion


        #region Constructor
        public DB(string db, string dir, byte[] cryptKey, bool onlyRead)
        {
//#if DEBUG
//            log();
//#endif
            ulong schemaVersion = 1;

            if (onlyRead)
            {
                realmConfigurationBase = new RealmConfiguration(Path.Combine(dir, db))
                {
                    EncryptionKey = cryptKey,
                    IsReadOnly = onlyRead,
                    SchemaVersion = schemaVersion,
                };
            }
            else
            {
                realmConfigurationBase = new RealmConfiguration(Path.Combine(dir, db))
                {
                    EncryptionKey = cryptKey,
                    IsReadOnly = onlyRead,
                    SchemaVersion = schemaVersion,
                    MigrationCallback = (migration, oldSchemaVersion) =>
                    {
                        System.Diagnostics.Debug.WriteLine("******************************************");
                        System.Diagnostics.Debug.WriteLine("OldSchemaVersion => {0}", oldSchemaVersion);
                        System.Diagnostics.Debug.WriteLine("******************************************");
                    },
                };
            }
            realmConfigurationBase.Schema = new Type[]
            {
                typeof(Dictionar),
                typeof(GNG),
                typeof(Group),
                typeof(LexicalRelation),
                typeof(SemanticRelation),
                typeof(TextAndAuthor),
                typeof(Verbete),
                typeof(VerbeteAtGroup),
            };

            try
            {
                realmInstance = Realm.GetInstance(realmConfigurationBase);
                about = realmInstance.All<Dictionar>().FirstOrDefault();
            }
            catch (Exception err)
            {
                var t = err;
                throw;
            }

        }
        //private void log()
        //{
        //    Logger.LogLevel = LogLevel.All;
        //    Logger.Default = Logger.Function(message =>
        //    {
        //        System.Diagnostics.Debug.WriteLine(message);
        //    });
        //}

        public DB() { }
        #endregion

        #region Dispose
        public bool Dispose(bool compact)
        {
            bool ret = true;
            realmInstance.Dispose();
            if (compact)
            {
                ret = Realm.Compact(realmConfigurationBase);
            }
            return ret;
        }
        #endregion
        #region methods
        public Realm GetInstance()
        {
            return realmInstance;
        }

        public Realm GetNewInstance()
        {
            return Realm.GetInstance(realmConfigurationBase);
        }
        #endregion
    }
`

And the two search tasks, if i remove dispose() from first error occurs.

`        public async Task<IList<string[]>> Search(string dbname, string lke)
        {
            Realm realm = DBPool.Instance.GetDB(dbname).GetNewInstance();
            string idiom = realm.All<Dictionar>().FirstOrDefault().VerbeteIdiom.ToString();
            var verbeteInstance = realm.All<Verbete>();
            IList<string[]> ret = new List<string[]>();
            foreach (var v in verbeteInstance.Where(v => v.SearchText.StartsWith(lke)))
            {
                ret.Add(new string[] { idiom, v.Text.ToString() });
            }
            realm.Dispose();
            return ret;
        }
        public async Task<IList<string[]>> SearchComposed(string dbname, string lke)
        {
            Realm realm = DBPool.Instance.GetDB(dbname).GetNewInstance();
            string idiom = realm.All<Dictionar>().FirstOrDefault().VerbeteIdiom.ToString();
            var verbeteInstance = realm.All<Verbete>();
            IList<string[]> ret = new List<string[]>();
            string where1 = "* " + lke + "*";
            string where2 = "*-" + lke + "*";
            foreach (var v in verbeteInstance.Where(v => v.Composed && (v.SearchText.Like(where1, false) || v.SearchText.Like(where2, false))))
            {
                ret.Add(new string[] { idiom, v.Text.ToString() });
            }
            realm.Dispose();
            return ret;
        }
`

**Comment by nirinchev** [comment]
@papafe I have a repro for this:

```csharp
var c = new RealmConfiguration("foo")
{
    IsReadOnly = true
};

var r = Realm.GetInstance(c);
r.Refresh();
```

**Comment by papafe** [comment]
@nirinchev thank you, I'll take a look

**Comment by carbonete** [comment]
@nirinchev , you are fast than me, but i think valid to disclosure my code to you , @papafe and others that have this need.
There is simultaneously open 3 realms.
When i introduce Dispose() problem not occurs in second search task. 
@papafe  this partial code of project.

I have a DBPoll Class that is pool of open Realms.
```
   public sealed class DBPool
    {
        #region Instanciamento
        public static readonly DBPool Instance = new DBPool();
        DBPool() { }
        #endregion

        #region Pool
        private static readonly Dictionary<string, DB> pool = new Dictionary<string, DB>();
        #endregion

        #region methods

        public DB GetDB(string db)
        {
            return pool[db];
        }

        public IEnumerable<string> GetOpenDBList()
        {
            return pool.Keys.AsEnumerable();
        }

        public DB DB(string db, string dir, byte[] cryptKey, bool onlyRead)
        {
            try
            {
                if (!pool.ContainsKey(db))
                {
                    pool[db] = new DB(db, dir, cryptKey, onlyRead);
                }
            }
            catch (Exception e)
            {
                var err = e;
                throw;
            }

            return pool[db];
        }

        public void Close(string db, bool compact)
        {
            try
            {
                var status = pool[db].Dispose(compact);
                pool.Remove(db);
            }
            catch (Exception)
            {
                throw;
            }
        }

        public void CloseAll(bool compact)
        {
            foreach (var db in pool.Keys)
            {
                Close(db, compact);
            }
        }


        #endregion
    }

```
There is a DB class that administrators individual Realm's
```
   public class DB
    {
        #region Properties

        private Realm realmInstance;

        private RealmConfigurationBase realmConfigurationBase;

        private Dictionar about;
        public Dictionar About
        {
            get { return this.about; }
        }

        #endregion


        #region Constructor
        public DB(string db, string dir, byte[] cryptKey, bool onlyRead)
        {
//#if DEBUG
//            log();
//#endif
            ulong schemaVersion = 1;

            if (onlyRead)
            {
                realmConfigurationBase = new RealmConfiguration(Path.Combine(dir, db))
                {
                    EncryptionKey = cryptKey,
                    IsReadOnly = onlyRead,
                    SchemaVersion = schemaVersion,
                };
            }
            else
            {
                realmConfigurationBase = new RealmConfiguration(Path.Combine(dir, db))
                {
                    EncryptionKey = cryptKey,
                    IsReadOnly = onlyRead,
                    SchemaVersion = schemaVersion,
                    MigrationCallback = (migration, oldSchemaVersion) =>
                    {
                        System.Diagnostics.Debug.WriteLine("******************************************");
                        System.Diagnostics.Debug.WriteLine("OldSchemaVersion => {0}", oldSchemaVersion);
                        System.Diagnostics.Debug.WriteLine("******************************************");
                    },
                };
            }
            realmConfigurationBase.Schema = new Type[]
            {
                typeof(Dictionar),
                typeof(GNG),
                typeof(Group),
                typeof(LexicalRelation),
                typeof(SemanticRelation),
                typeof(TextAndAuthor),
                typeof(Verbete),
                typeof(VerbeteAtGroup),
            };

            try
            {
                realmInstance = Realm.GetInstance(realmConfigurationBase);
                about = realmInstance.All<Dictionar>().FirstOrDefault();
            }
            catch (Exception err)
            {
                var t = err;
                throw;
            }

        }
        //private void log()
        //{
        //    Logger.LogLevel = LogLevel.All;
        //    Logger.Default = Logger.Function(message =>
        //    {
        //        System.Diagnostics.Debug.WriteLine(message);
        //    });
        //}

        public DB() { }
        #endregion

        #region Dispose
        public bool Dispose(bool compact)
        {
            bool ret = true;
            realmInstance.Dispose();
            if (compact)
            {
                ret = Realm.Compact(realmConfigurationBase);
            }
            return ret;
        }
        #endregion
        #region methods
        public Realm GetInstance()
        {
            return realmInstance;
        }

        public Realm GetNewInstance()
        {
            return Realm.GetInstance(realmConfigurationBase);
        }
        #endregion
    }

```
And the two search tasks, if i remove dispose() from first error occurs.

```
     public async Task<IList<string[]>> Search(string dbname, string lke)
        {
            Realm realm = DBPool.Instance.GetDB(dbname).GetNewInstance();
            string idiom = realm.All<Dictionar>().FirstOrDefault().VerbeteIdiom.ToString();
            var verbeteInstance = realm.All<Verbete>();
            IList<string[]> ret = new List<string[]>();
            foreach (var v in verbeteInstance.Where(v => v.SearchText.StartsWith(lke)))
            {
                ret.Add(new string[] { idiom, v.Text.ToString() });
            }
            realm.Dispose();
            return ret;
        }
        public async Task<IList<string[]>> SearchComposed(string dbname, string lke)
        {
            Realm realm = DBPool.Instance.GetDB(dbname).GetNewInstance();
            string idiom = realm.All<Dictionar>().FirstOrDefault().VerbeteIdiom.ToString();
            var verbeteInstance = realm.All<Verbete>();
            IList<string[]> ret = new List<string[]>();
            string where1 = "* " + lke + "*";
            string where2 = "*-" + lke + "*";
            foreach (var v in verbeteInstance.Where(v => v.Composed && (v.SearchText.Like(where1, false) || v.SearchText.Like(where2, false))))
            {
                ret.Add(new string[] { idiom, v.Text.ToString() });
            }
            realm.Dispose();
            return ret;
        }
```

**Comment by LaPeste** [comment]
Just for the sake of information, investigating this issue made us notice a slightly suspicious [behaviour](https://github.com/realm/realm-core/issues/5061) in core that is worth digging deeper in.
