### ISSUE TITLE
Compile shared libs for osx-arm64 (Apple Silicon)

### ISSUE THREAD

**Issue by collinkreutzer** [realm/realm-dotnet#2732]
### Description

There are no shared libraries for osx-arm64 yet, making native osx-arm64 builds of projects using these libraries impossible.

### How important is this improvement for you?

Dealbreaker

**Comment by carbonete** [comment]
@collinkreutzer  Sorry, but you can explain how much improvement you say. I think first how .Net 6 address it?

**Comment by nirinchev** [comment]
Hey @collinkreutzer this is something we have on our todo list for sure, but haven't prioritized it yet. Can you describe your use case in a little more detail? Are you building a macOS application/game or do you need it for development purposes?

**Comment by collinkreutzer** [comment]
@nirinchev Nice to hear this is on your todo list! I'm not developing any app with realm myself though it prevented me from building a native version of an app using realm-dotnet because of the missing shared libs. Namely: https://github.com/ppy/osu

**Comment by nirinchev** [comment]
I see. Yes, we'll try to get M1 builds up and running soon-ish - the main obstacle is that Github Actions, which we use for CI doesn't have M1 runners, meaning we need to provision and self-host some ourselves.

**Comment by nekodex** [comment]
Hello there, I'm a member of the development team for the aforementioned osu! project and we have recently been looking at getting M1/osx-arm64 builds going for our game.

Just wondering if there has been any updates to this?

The wrapper library (`librealm-wrappers.dylib`) seems to already be built as a universal binary:
```
$ lipo -info librealm-wrappers.dylib 
Architectures in the fat file: librealm-wrappers.dylib are: x86_64 arm64 

$ otool -L librealm-wrappers.dylib
librealm-wrappers.dylib (architecture x86_64):
	@rpath/librealm-wrappers.dylib (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1853.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 60157.30.13)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1200.3.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1853.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
librealm-wrappers.dylib (architecture arm64):
	@rpath/librealm-wrappers.dylib (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1853.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 60157.30.13)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1200.3.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1853.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

However, the dylib is being output to the architecture-specific (`runtimes\osx-x64\native`) path, which prevents dotnet from finding the library when run on arm64.

Looking at [Realm.csproj](https://github.com/realm/realm-dotnet/blob/60c629ea728f281b76272d8b21a3f915fcefbfb5/Realm/Realm/Realm.csproj#L51) suggests this can be resolved by changing the output path to the non-architecture-specific (`runtimes\osx\native`) path (for dotnet6.0 at least, I'm unsure if the [RID graph lookup](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog#rid-graph) is the same for previous versions?).

Alternatively, outputting an extra copy of the wrapper to `runtimes\osx-arm64\native` in addition to `runtimes\osx-x64\native` could also work, if the previous method doesn't.

I'd be happy to make a PR if the above suggestion(s) seem acceptable?

FWIW I've tested copying the wrapper dylib to the non-architecture-specific path (`runtimes\osx\native`) manually in our project and the library loads and works as expected on M1/osx-arm64.
