### ISSUE TITLE
Close issue with release contain solution

### ISSUE THREAD

**Issue by carbonete** [realm/realm-dotnet#2744]
### Description

When a issue receive a MERGE it's closed, but user may wait to release version containing solution to test and confirm this solution is working.  

Sugestion ,  wait 1 week after release contain solution to close issue.

I'm waiting next release to test solution, and if someone that have this problem see this issue closed can be take a misleading

thanks.

### How important is this improvement for you?

Would be a major improvement

**Comment by LaPeste** [comment]
Hi @carbonete, thank you for the feedback. What you’re suggesting would be a "breaking change" for the way We use github issues and would leave all previous users really confused.
We do our best to test a fix before release. Of course, this does not mean that every solution is 100% bug-free. If that happens to be the case, you’re most welcome to reopen the issue adding further information on how what we thought it’s a fix doesn’t fix your issue.
About your second point, if someone is having your same issue, that person can verify if the current release has the fix or not by looking at the changelog of the release. We religiously keep it up to date so there should be no doubt there.

**Comment by carbonete** [comment]
@LaPeste  i don't have any doubts about the test a fix before release. But i will only put fix in my project when new nugget arrive. I think today workflow work only when developer use direct GitHub and can access changes before release new nugget.

Thanks for attention.
