### ISSUE TITLE
[Bug]: handshake: x509: certificate has expired or is not yet valid:

### ISSUE THREAD

**Issue by carbonete** [realm/realm-dotnet#2754]
### What happened?

App not receive any change and i start receive from MongoDB Mails with handshake: x509: certificate has expired or is not yet valid: .

### Repro steps

Receiving mail from MongoDB

### Version

10.6.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### What type of application is this?

Xamarin

### Client OS and version

UWP and Android

### Relevant log output

```shell
translator failed to complete processing batch: failed to update resume token document: connection() error occured during connection handshake: x509: certificate has expired or is not yet valid: current time 2021-12-16T18:16:04Z is after 2021-12-16T17:53:09Z
Source:

Error syncing MongoDB write


recoverable event subscription error encountered: error making mongo client to register translator handler: error connecting to MongoDB service cluster: failed to ping: server selection error: server selection timeout, current topology: { Type: ReplicaSetNoPrimary, Servers: [{ Addr: cluster0-shard-00-00.owqih.mongodb.net:27017, Type: Unknown, Last error: connection() error occured during connection handshake: x509: certificate has expired or is not yet valid: current time 2021-12-16T18:19:51Z is after 2021-12-16T17:53:09Z }, { Addr: cluster0-shard-00-01.owqih.mongodb.net:27017, Type: Unknown, Last error: connection() error occured during connection handshake: x509: certificate has expired or is not yet valid: current time 2021-12-16T18:19:51Z is after 2021-12-16T17:53:09Z }, { Addr: cluster0-shard-00-02.owqih.mongodb.net:27017, Type: Unknown, Last error: connection() error occured during connection handshake: x509: certificate has expired or is not yet valid: current time 2021-12-16T18:19:51Z is after 2021-12-16T17:53:09Z }, ] }
Source:

Error syncing MongoDB write
```

**Comment by carbonete** [comment]
Column Name and User Id are empty

![image](https://user-images.githubusercontent.com/3043885/146434062-e51b0ade-7912-48c4-819b-9e6b110fbb00.png)

**Comment by carbonete** [comment]
Sorry I know this is not a sdk problem, i'm using free tier to develop and test app. But is hard see a problem that is not in app, and no way to talk with support. I open forum https://www.mongodb.com/community/forums/t/handshake-x509-certificate-has-expired-or-is-not-yet-valid/137458 with no answers.
Exist any way to send to support Atlas - Realm support a msg with this problem ?

I try restart SYNC but this is not working.

![image](https://user-images.githubusercontent.com/3043885/146560194-ab5acc28-8389-4e19-958f-0f373ecc92d4.png)

**Comment by carbonete** [comment]
![image](https://user-images.githubusercontent.com/3043885/146560588-677dfefa-778d-4543-9f04-7afec7158ad0.png)

Another message error

**Comment by ianpward** [comment]
hey @carbonete there is something up with your Atlas instance. You can still contact support even without a support plan by toggling the little chat widget in the lower right hand corner of the Cloud Web UI. These repos are kept for local realm sdk bugs so I am closing
