### ISSUE TITLE
[Bug]:  Error: Failed to codesign 

### ISSUE THREAD

**Issue by ivanrlg** [realm/realm-dotnet#2757]
### What happened?

When I compile the Xamarin.IOs project in release mode with the apple certificate. (It is my first time doing this procedure)

### Repro steps

Compile in Release with the Iphone / Generic Device configuration

Note: with IphoneSimulator the compilation error does not happen

### Version

.NET Standard 2.1

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### What type of application is this?

Xamarin

### Client OS and version

IOS

### Stacktrace of the exception/crash you're getting

```shell
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.Shared.targets(3,3): Error: Failed to codesign 'bin/iPhone/Release/FMPatients.iOS.app//Frameworks/realm-wrappers.framework/realm-wrappers': Warning: unable to build chain to self-signed root for signer "Apple Distribution: Ivan Labrador (XXXXXXXX)"
/Users/rilanderrincon/Documents/GitHub/FMPatient/FMPatients.iOS/bin/iPhone/Release/FMPatients.iOS.app/Frameworks/realm-wrappers.framework: errSecInternalComponent
```

**Comment by papafe** [comment]
Hi @ivanrlg this seems to be a signing problem that is unrelated to realm itself. Unfortunately sometimes the signing process on iOS is a little mysterious and errors can be deceiving (talking from personal experience).
Looking a little bit online this post on stackoverflow [here](https://stackoverflow.com/questions/58326124/command-usr-bin-codesign-failed-with-exit-code-1-on-xcode-11) seems to be solving a similar issue. Let me know if it helped

**Comment by nirinchev** [comment]
Closing this due to a lack of response.
