### ISSUE TITLE
Rework tests that use `Session.Error` given that it's going to be deprecated

### ISSUE THREAD

**Issue by LaPeste** [realm/realm-dotnet#2788]
We're going to deprecate `Session.Error` in favour of using `SyncConfigurationBase` to handle all the session errors. Our unit tests and integration tests rely on `Session.Error`, so we should rework them. I'm specifically talking about `SynceTestHelpers.WaitForSessionError` and `SynceTestHelpers.RunBaasTestAsync`. There's likely more, so more usages need to be searched. Just make sure not to touch the integration tests in `SessionTets` that end with *`_Coexistence`, as those are meant to use `Session.Error` until deprecation.

**Comment by papafe** [comment]
I'm closing this since this has been already removed with version 11
