### ISSUE TITLE
[Bug]: SessionException 112 : "Bad changeset (DOWNLOAD)"

### ISSUE THREAD

**Issue by carbonete** [realm/realm-dotnet#2794]
### What happened?

Existing User Logged in new device after install fresh app. This occurs in Windows and Android.
Realm.Login occurs ok
but 
Realm.GetInstanceAsync(RealmSyncConfig) raised exception
Realms.Sync.Exceptions.SessionException Code 112 
Message = "Bad changeset (DOWNLOAD)"

### Repro steps

1 - Login user in Realm Sync
2 - GetInstanceAsync

### Version

10.8.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### What type of application is this?

Xamarin

### Client OS and version

Windows and Android

**Comment by carbonete** [comment]
Log Trace 

Failed to integrate downloaded changesets: Failed to parse, or apply received changeset: ArrayErase: No such object: FavoriteList in class '"c554ff27417a46d38cb87f6082930890"' (instruction table: FavoriteList, version: 544, last_integrated_remote_version: 1, origin_file_ident: 85, timestamp: 223489990364)
Exception backtrace:
<backtrace not supported on this platform>
[0:] 2022-01-31 23:16:18.027 Info: Connection[1]: Connection closed due to error
[0:] 2022-01-31 23:16:18.074 Detail: Connection[1]: Allowing reconnection in 3045813 milliseconds
[0:] 2022-01-31 23:16:18.078 Debug: Connection[1]: Session[1]: Progress handler called, downloaded = 0, downloadable(total) = 0, uploaded = 0, uploadable = 0, reliable_download_progress = true, snapshot version = 2
[0:] 2022-01-31 23:16:18.160 Debug: Connection[1]: Session[1]: Initiating deactivation

**Comment by nirinchev** [comment]
Hey, can you [file a support ticket](https://support.mongodb.com/welcome) about this as it's likely a server-side issue that the support team will be equipped to investigate and resolve. Unfortunately, there's not much we can do from our end.

**Comment by carbonete** [comment]
@nirinchev  thanks for attention sdk team is champion.
Unfortunately  I'm in development phase and using free tier. Two different attendees reply my request, one try sale to me a Paid tier and other try sale a paid Support. No one say how i recover from this error.

**Comment by nirinchev** [comment]
I understand. Can you please try to use the feedback widget in the cloud portal again and tell the team you're reporting a bug and have already spoken with me and Ian Ward about it. This is a bug that may be affecting other users, so we're going to make an exception and address it without the need for a support plan.

**Comment by carbonete** [comment]
Thanks @nirinchev and @ianpward for intervention help-desk is analyzing the problem.
