### ISSUE TITLE
[Bug]: Issue initializing Realm in .NET 6 MAUI app

### ISSUE THREAD

**Issue by ShaneBridges** [realm/realm-dotnet#2802]
### What happened?

DllNotFoundException being thrown as soon as I try to initialize Realm through Realms.Sync.App.Create.  This is with a .NET 6 MAUI app on **Android**.  Note that everything works if I change the output target to "Windows Machine" and run it as a WinUI desktop app.  I have not tested this with iOS yet.

Additional Info: I reached out to the MAUI team and they believe it may be a Realm package issue.  I posted more details on the issue as well as the stack trace, debug output and a very simple sample project at the link below.  Hopefully they will review it again to see if it's something on their end.

[https://github.com/dotnet/maui/issues/4427](url)

Files:
[logcat.txt](https://github.com/realm/realm-dotnet/files/7982861/logcat.txt)
[MauiApp1.zip](https://github.com/realm/realm-dotnet/files/7982830/MauiApp1.zip)
[stacktrace.txt](https://github.com/realm/realm-dotnet/files/7982859/stacktrace.txt)

### Repro steps

1) Create a new .NET Maui App
2) Add the Realm nuget package
3) Add the following two lines at the end of the MainPage constuctor:

AppConfiguration config = new("carom_app-vyzkd"); // you can use this value for testing...it's a sample Mongo app id.
Realms.Sync.App.Create(config); // DllNotFoundException "realm.wrappers"

### Version

.NET 6.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### What type of application is this?

Other

### Client OS and version

Windows 11 21H2, Build 22000.434

**Comment by nirinchev** [comment]
Thanks for reporting this. MAUI is pretty high on our priority list, so we'll start tackling this and other usability issues in the near future.

**Comment by dev-thinks** [comment]
@nirinchev not working in iOS 15.2 (iphone 13) with MAUI preview 13. Getting the same exception as mentioned here in this issue. can we get a fix at the earliest so that we can pass through this bump. Thank you.

**Comment by huoyaoyuan** [comment]
Also hitting this when converting Xamarin to `net6.0-android`. Symptoms I've met:
If Realm is a transitive dependency from other project, a DllNotFoundException will occur. If Realm is directly added to the project, a SEGV_ACCERR will occur when trying to initialize Realm.

**Comment by huoyaoyuan** [comment]
It looks like an interop issue now.
Maybe `[UnmanagedCallersOnly]` can help, or you can switch to function pointers on .NET 5+.

**Comment by huoyaoyuan** [comment]
The `.props` is working correctly with .NET 6. In fact, the SEGV_ACCERR only occurs in Debug configuration. After switching to Release configuration, I've had the whole application running successfully.

**Comment by huoyaoyuan** [comment]
Adding the `.props` into `buildTransitive` together with `build` in nuget package should bring the native assets correctly. I've opened an issue for mono crashing: https://github.com/dotnet/runtime/issues/67140

**Comment by Axemasta** [comment]
Since MAUI has an RC and is fast approaching GA, is there any timeline on this getting picked up?

**Comment by nirinchev** [comment]
Yes, we have a PR open for it: https://github.com/realm/realm-dotnet/pull/2906

The core work in the PR is done and we're just testing various platforms to make sure we didn't accidentally break something.

**Comment by fealebenpae** [comment]
We released [10.12.0](https://github.com/realm/realm-dotnet/releases/tag/10.12.0) with preview support for the .NET 6 Mobile and MAUI workloads.
