### ISSUE TITLE
Unity WebGL Support

### ISSUE THREAD

**Issue by Scott-Hickmann** [realm/realm-dotnet#2805]
### Description

The Realm Unity SDK works great. However, it looks like WebGL builds are currently not supported. Is there any plan to implement this soon?

### How important is this improvement for you?

Dealbreaker

**Comment by nirinchev** [comment]
Yes, we do plan to add support for web assembly and later - WebGL. We already [have an issue for WASM support](https://github.com/realm/realm-dotnet/issues/2199), which I've renamed to also capture WebGL, so I'll close this one.

But to give you the current status - Realm SDKs are implemented as a wrapper around a C++ database - realm-core. This means that we need to first add WASM support to Core, before SDKs can start supporting browser use cases. We do have some done some PoCs/research on this topic, but nothing that we can comfortably share with users yet.
