### ISSUE TITLE
[Bug]: CollectionChanged not called for downloaded modifications (is only called for local changes)

### ISSUE THREAD

**Issue by polymath74** [realm/realm-dotnet#2833]
### What happened?

My `RealmCollection<>.CollectionChanged()` event handler is being called normally for changes I make locally, and also seems to be called when a document is added or removed remotely. However, remote changes that modify an existing document **do not** trigger the callback.

The data _is_ being changed in the local Realm. If I manually reload the collection (by selecting another view in my application, then returning) the new data is correctly retrieved. I have turned on sync debugging, and I can see the data arriving. It just does not call my callback.

### Repro steps

1. var collection = realm.All<Something>().AsRealmCollection()
2. collection.CollectionChanged += CollectionChanged;
3. var something = collection.First();
4. something.field++; // will correctly call CollectionChanged
5. modify the field remotely (e.g. other machine, or use Compass) // data arrives locally, Realm is updated, but CollectionChanged is NOT called
6. add or delete a document from the collection remotely // CollectionChanged IS called

### Version

10.10.0 (also happens on 10.7.1)

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### What type of application is this?

WPF

### Client OS and version

Microsoft Windows 10 Pro Version 10.0.19043 Build 19043

### Code snippets

Can provide code if you need it :)

### Relevant log output

```shell
REALM: 2022-03-04 07:03:34.212 Trace: Connection[8]: Download message compression: is_body_compressed = false, compressed_body_size=85, uncompressed_body_size=85
REALM: 2022-03-04 07:03:34.225 Trace: Connection[8]: Received: DOWNLOAD CHANGESET(server_version=84, client_version=137, origin_timestamp=226307016656, origin_file_ident=194, original_changeset_size=55, changeset_size=55)
REALM: 2022-03-04 07:03:34.235 Trace: Connection[8]: Changeset: 3F 00 0B 45 76 65 6E 74 52 65 73 75 6C 74 3F 01 0B 70 65 72 66 6F 72 6D 61 6E 63 65 04 00 0A 62 21 B6 79 19 14 A0 91 0C 02 4E 14 01 00 07 00 00 00 00 00 80 50 40 00
REALM: 2022-03-04 07:03:34.242 Debug: Connection[8]: Session[8]: Received: DOWNLOAD(download_server_version=84, download_client_version=137, latest_server_version=84, latest_server_version_salt=2198879587461132926, upload_client_version=138, upload_server_version=83, downloadable_bytes=0, last_in_batch=true, query_version=0, num_changesets=1, ...)
REALM: 2022-03-04 07:03:34.255 Debug: Connection[8]: Session[8]: 1 remote changeset integrated, producing client version 139
REALM: 2022-03-04 07:03:34.263 Debug: Connection[8]: Session[8]: Sending: UPLOAD(progress_client_version=139, progress_server_version=84, locked_server_version=84, num_changesets=0)
REALM: 2022-03-04 07:03:34.271 Debug: Connection[8]: Session[8]: Progress handler called, downloaded = 7609, downloadable(total) = 7609, uploaded = 33179, uploadable = 33179, reliable_download_progress = true, snapshot version = 139
REALM: 2022-03-04 07:03:34.280 Debug: Connection[8]: Session[8]: Progress handler called, downloaded = 7609, downloadable(total) = 7609, uploaded = 33179, uploadable = 33179, reliable_download_progress = true, snapshot version = 139
```

**Comment by nirinchev** [comment]
This is how `INotifyCollectionChanged` is designed to work. It only emits events for modifications of the collection itself, not whenever an object inside the collection changes. It is typically used in combination with `INotifyPropertyChanged` for its objects where the data binding framework subscribes to `CollectionChanged` on the collection and then to `PropertyChanged` on each object inside.

**Comment by polymath74** [comment]
Thanks @nirinchev … then what is the `NewModifiedIndices`  part of the notification for?

**Comment by peppy** [comment]
I'm also a bit confused by this answer. As mentioned in the opening post, we also see events fired when adjusting only one property on a model (that is not relevant to the query/subscription). Of course we can just ignore the case, but it doesn't seem to match the described behaviour – `CollectionChanged` *is* getting fired.

![JetBrains Rider-EAP 2022-03-04 at 09 57 05](https://user-images.githubusercontent.com/191335/156742044-e472ca9d-adb3-4362-87b2-0cec2aa138c9.png)

**Comment by nirinchev** [comment]
Hm... I think there is some confusion here - the original post mentions `collection.CollectionChanged += CollectionChanged` which is using the `CollectionChanged` event. The [args object](https://docs.microsoft.com/en-us/dotnet/api/system.collections.specialized.notifycollectionchangedeventargs?view=net-6.0) passed to the event handler doesn't contain properties for modified indices - only for new/old items and the action, which is add/remove/move/replace/reset.

**Comment by peppy** [comment]
Aha, I didn't realise the event path has different behaviour to `SubscribeForNotifications`. That's good to know, I'll have to take a look into it.

**Comment by nirinchev** [comment]
@polymath74 to be notified for modifications, you need to use the `SubscribeForNotifications` API rather than the `CollectionChanged` event - that callback should be invoked regardless of where the changes originate from.

**Comment by polymath74** [comment]
Ah, ok thanks. The documentation page doesn't make that clear.

**Comment by peppy** [comment]
@nirinchev while in the topic could i ask whether there is a difference in the overhead between these two subscription methods? is using `CollectionChanged` a good idea when only wanting to act on changes to the overall collection?

**Comment by nirinchev** [comment]
@peppy there's no meaningful perf difference between the two methods. The `CollectionChanged` event uses `SubscribeForNotifications` under the hood and just ignores modifications to objects. Its primary use case is for Xaml-based databinding and probably not worth using it for something as custom as what you're doing as it loses some information to adhere to the `INotifyCollectionChanged` contract. For example, if you have both additions and removals from the collection, that cannot be expressed with the `NotifyCollectionChangedEventArgs` API, which means we're forced to raise a `Reset` event, essentially telling the consumer to re-read the entire collection.

**Comment by nirinchev** [comment]
@polymath74 were you able to get this working using the `SubscribeForNotifications` API? Can I close this issue or are you still seeing unexpected behavior?

**Comment by polymath74** [comment]
@nirinchev Yes, all good now, `SubscribeForNotifications` does exactly what I want. Thanks! (And sorry for the delay.)

**Comment by nirinchev** [comment]
Great, thanks for confirming!
