### ISSUE TITLE
Problem of EmbeddedObject nested collection binding (.net Xamarin Forms)

### ISSUE THREAD

**Issue by aliegeni** [realm/realm-dotnet#2840]
### Discussed in https://github.com/realm/realm-dotnet/discussions/2839

<div type='discussions-op-text'>

<sup>Originally posted by **aliegeni** March  6, 2022</sup>
Despite official docs says: "You can use the same embedded object type in multiple parent object types and you can embed objects inside of other embedded objects."
You get the RealmInvalidObjectException: "Can't enumerate the collection because it was deleted or the Realm it is contained in has been closed." when trying to update parent RealmObject with EmbededObject member witch has inside List of other embedded objects.
That makes "live" data binding impossible in Xamarin Forms! Is there any workaround?

Have simple project to reproduce the issue.
https://github.com/aliegeni/RealmXamarinTest
 </div>

**Comment by nirinchev** [comment]
Can you share your project?

**Comment by aliegeni** [comment]
> Can you share your project?

https://github.com/aliegeni/RealmXamarinTest

**Comment by nirinchev** [comment]
You can't have multiple objects referencing the same embedded object. In your repository you're adding the same track to multiple albums and the same album to multiple artists.

**Comment by aliegeni** [comment]
That not the case! It is not possible even to add same instance of embedded object to multiple realms! That why there is deep cloning at the and of repository GetData() function .  
Issue is related about nested list iteration.

**Comment by nirinchev** [comment]
My bad - I misunderstood where the original problem was manifesting. I can see the actual issue now and it seems to be databinding related. Should be simple to workaround.

**Comment by PawKanarek** [comment]
@nirinchev Do you know when will be available new Realm Nuget package with this fix? I have the same issue, app is crashing & i don't know how to make workaround :(

**Comment by nirinchev** [comment]
We're wrapping up a few in-flight PRs and will do a release shortly after. Either this week or early next one.
