### ISSUE TITLE
[Bug]: Huge performance drop on update writes Iphone X / Iphone 12

### ISSUE THREAD

**Issue by rhaly** [realm/realm-dotnet#2866]
### What happened?

Background: We are currently using Realm _3.3.0_ and from time to time we are measuring times of db operations (_inserts_, _reads_, _updates_, _deletes_) in several devices both on iOS and Android platforms. The overall conclusion is that Realm has performance degradation on _reads_ and _updates_ operations but in general _inserts_ and _delete_ op are faster. I've compared Realm _3.3.0_ against several versions _5.1.2_, _10.1.2_ and _10.10.0_ Performance degradation is main reason why we don't update Realm version, because it's significant especially on older devices.

On version _10.8.0_ there is huge performance drop on updates in newer apple devices like _iphone X_ / _iphone 12_ on updates with many transactions. On version _10.7.1_ my test case on _iphone X_ took **200ms** and _10.8.0_ over **11000ms**, thats over 50-times slower. The same problem is with delete operations with many transactions. 
On _Iphone 6+_ update in version _3.3.0_ took 3800ms and in version _10.10.0_  8000ms which is 2 times slower, but still faster than on new iphones :)

### Repro steps

My test case is:
1. create db
2. insert 1000 objects to db
3. measure 500 updates, (each update is in separate transaction, this way I simulate actual usage of an app by user) 
4. delete db

I perform the test 15 times and only step 3 is measured.

### Version

Mono 6.12.0.93 / Xamarin.iOS 15.0.0.6

### What SDK flavour are you using?

Local Database only

### What type of application is this?

Xamarin

### Client OS and version

iphone X (15.2) / iphone 12 (15.4)

### Code snippets

My data structure is simple:

```csharp
public class Publication : RealmObject, IPublication
{
    [PrimaryKey]
    public string Id { get; set; }

    public string Title { get; set; }

    public string CoverUrl { get; set; }

    public int Version { get; set; }

    [Indexed]
    public int RemoteId { get; set; }

    public bool HasCover => string.IsNullOrEmpty(CoverUrl) == false;

    public int DownloadPercentage { get; set; }

    public string SomeDescription { get; set; }

    [Backlink(nameof(PublicationCollection.Publications))]
    public IQueryable<PublicationCollection> Collections { get; }
}

public class PublicationCollection : RealmObject, IPublicationCollection
{
    [PrimaryKey]
    public string Id { get; set; }

    public string Name { get; set; }

    [Indexed]
    public int RemoteId { get; set; }

    public IList<Publication> Publications { get; }

    public int PublicationsCount => Publications.Count;

    public string CoverUrl => Publications.FirstOrDefault(x => x.CoverUrl != null)?.CoverUrl;

    public bool HasCover => CoverUrl != null;
}
```
Code which is measured in this case:

```csharp
public override int UpdatePublicationsInManyTransactions()
{
    var total = 0;
    var publications = _realm.All<Publication>().Where(x => x.Version == 1).ToList();
    foreach (var publication in publications)
    {
        _realm.Write(() =>
        {
            publication.Version = 2;
        });
        total++;
    }

    return total;
}
```

**Comment by rhaly** [comment]
> I'd be interested in knowing whether you can measure the same performance degradation if you have 10.000 objects instead of 1000 ?

@finnschiermer I've checked this on Iphone 12 with 10.000 items inserted. Update of 5.000 items took on average 1605ms in version 10.7.1 and on 10.8.0 version it was 101.110ms, so it's more or less the same x50+ slow down factor.

**Comment by finnschiermer** [comment]
@rhaly, thanx a lot... so the 50x slow down factor must have been introduced between 10.7.1 and 10.8.0 ... interesting

**Comment by rhaly** [comment]
It looks like it. I've also check this on android Samsung A50 and it's not so significant 8.482ms in 10.7.1 vs 25.224ms in 10.8.0 for 10.000 items scenario.
