### ISSUE TITLE
IList declarations need more work to enable Standalone objects with relationships

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#287]
This is a concern as I thought they were working and heavily tested.

If you replace RealmList with IList in the declarations in `RelationshipTests.cs` then all the tests apart from the _TopDog_ tests will fail. I'm not sure if this is a problem with Fody or the RealmList classes.

**Comment by CrimsonKyle** [comment]
Being able to define an IList of realm objects with a setter in a model is essential to being able to deserialize a root level Json doc into more than 2 levels deep i.e. (Parent < Child).  Do you know where ILists are currently on the priority list?

**Comment by AndyDentFree** [comment]
@CrimsonKyle is the concern over having a setter or using `IList` in the declaration? The setter may come earlier as improving initialisation syntax is a passionate goal of mine too. The JSON decoding is a great scenario to help bump the priority of this task.

**Comment by Shazbot89** [comment]
Not certain, but we think the Newtonsoft deserializer is unable to map the child RealmLists without a set method. @CrimsonKyle was able to verify non-Realm objects using IList properties with { set; } were able to deserialize the entire tree of objects while Realm inherited objects with RealmList stop deserializing at the first level.

**Comment by CrimsonKyle** [comment]
#492

**Comment by AndyDentFree** [comment]
Whilst this is working with the current commit, based on a discussion with @fealebenpae I am going to rewrite it to avoid generating a return `RealmList` all the time and allow init with simple braced expressions even if you just declare the `get` without `set`.
