### ISSUE TITLE
[Bug]: Realm v10 database in Xamarin Forms iOS project won't build - "No matching framework found inside...realm-wrappers.xcframework"

### ISSUE THREAD

**Issue by drewrobey** [realm/realm-dotnet#2914]
### What happened?

Further to my post on StackOverflow, I've followed advice from @Tayschrenn and opened this issue.
https://stackoverflow.com/questions/71952545/realm-v10-database-in-xamarin-ios-project-wont-build-no-matching-framework-f

I'm attempting to upgrade the Realm database version I'm using in my Xamarin Forms project, from v5 up to the latest v10.

The original Realm database has been working fine for years, however when I try to use Realm v10 I can build the Android project successfully, but when I attempt to build the iOS project I get the error:

"No matching framework found inside 'C:\Users\MYNAME.nuget\packages\realm\10.11.1\build..\native\ios\universal\realm-wrappers.xcframework'"

![InkedScreenshot 2022-04-22 123420_LI](https://user-images.githubusercontent.com/15341697/164708562-2f6a2436-8dd5-4686-9a53-bf92420d2bd5.jpg)

I have tried:
- Deleting all obj/bin folders.
- Deleting all cached build files on the macOS build server.
- Creating a fresh project, rather than upgrading from v5 in the current project.
- Using a different macOS build server.

I'm using Windows 10, Visual Studio 2022, linked to a macOS Monterey build server with Xcode 13.3.1

### Repro steps

1. Create a Xamarin Forms project.
2. Install any v10 of Realm database, along with all accompanying automatic dependencies.
3. Build the Android project - this should work fine.
4. Connect to mac build server.
5. Build the iOS project - this will fail with the above error.

### Version

.NET Standard 2.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### What type of application is this?

Xamarin

### Client OS and version

iOS

### Relevant log output

```shell
No matching framework found inside 'C:\Users\MYNAME\.nuget\packages\realm\10.11.2\build\..\native\ios\universal\realm-wrappers.xcframework'.
         SupportedPlatform: 'ios', SupportedPlatformVariant: '', SupportedArchitectures: 'ARMv7, ARMv7s, ARM64'.	Leather.iOS
```

**Comment by fealebenpae** [comment]
Hey @drewrobey,

Thanks for the more detailed build log snippet. I think the issue is that we don't support the `ARMv7s` architecture. We never have, actually, but I think the build tooling could only reliably detect this at compile-time with `.xcframework` inputs. Try removing the `ARMv7s` architecture from your project and build again.

**Comment by drewrobey** [comment]
@fealebenpae You absolute genius - that's precisely it, a full Release build completes no problems now.

That also explains why creating a new project from scratch also wasn't working: the new build setup was defaulting to the full ARM architecture set.
