### ISSUE TITLE
[Bug]: System.DllNotFoundException on iOS with latest release

### ISSUE THREAD

**Issue by peppy** [realm/realm-dotnet#2929]
### What happened?

In our latest release, we updated to realm 10.12.0. This broke iOS releases for us, causing a startup crash with `System.DllNotFoundException` (see https://sentry.ppy.sh/share/issue/dc452be56fdc4bb0908d3025efe9fd7e/ for full stack).

### Repro steps

We publish using the (classic) xamarin build chain. Of note, we also include a reference to realm in our iOS specific project along with the base project, to avoid issues with transitive dependencies not copying native DLLs correctly. I do not know if that has any effect here, but removing this does not help resolve the issue.

I haven't investigated too deeply yet, but this is 100% repro when building our iOS project (https://github.com/ppy/osu). I can investigate further if required (we will be reverting to the previous release for now).

### Version

10.12.0

### What SDK flavour are you using?

Local Database only

### What type of application is this?

Xamarin

### Client OS and version

All iOS

**Comment by papafe** [comment]
This seems to be the same as https://github.com/realm/realm-dotnet/issues/2926 and should be solved with https://github.com/realm/realm-dotnet/pull/2927. 
In the meanwhile you can safely revert to the the previous version (10.11.2), since the current one is only relevant if you're targeting net6-ios or net6-android.

**Comment by peppy** [comment]
Thanks. I saw that issue but somehow didn't connect the dots that it was the same one. We've already reverted so this is not an imminent issue.
