### ISSUE TITLE
[Bug]: Returns Null Realm Object, but visible in Realm Studio

### ISSUE THREAD

**Issue by senorezi** [realm/realm-dotnet#2937]
### What happened?

I'm trying to create a Realm instance of a local realm file on disk. The realm file is not null because when I open it in Realm Studio there is indeed data in there.

I have the latest Realm (10.13.0) and Realm.Fody (10.13.0) NuGet packages. I have the FodyWeavers.xml in my project root directory.

I have very basic piece of code that creates an instance but I am getting nothing back. Anyone experience this?

Code:

```
using Realms;

string realmPath = @"C:\foobar\test.realm";
var config = new RealmConfiguration(realmPath);
config.SchemaVersion = 4; // tried it without this
var realm = Realm.GetInstance(config);
```

### Repro steps

1.) Create C# Console Application 
2.) Use .NET 6.0 Framework
3.) Download Realm 10.13.0
4.) Download Realm.Fody 10.13.0
5.) Build solution
6.) Make sure FodyWeavers.xml exists
7.) Use code
```
using Realms;

string realmPath = @"C:\foobar\test.realm";
var config = new RealmConfiguration(realmPath);
config.SchemaVersion = 4; // tried it without this
var realm = Realm.GetInstance(config);
```
8.) Return null realm object

### Version

6.0

### What SDK flavour are you using?

Local Database only

### What type of application is this?

Console/Server

### Client OS and version

Windows 10 Pro

### Code snippets

Code provided above

### Stacktrace of the exception/crash you're getting

```shell
No crash
```

### Relevant log output

```shell
No error log
```

**Comment by senorezi** [comment]
I noticed when I rebuild the solution I get this warning... not sure if it's related to the issue.

>MSBUILD : warning : Fody/Realm: Default schema for FOOBAR, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null appears to be empty. This is not an error if you don't have any RealmObject inheritors declared. Otherwise it may be a bug with the weaver.

This is what my FodyWeavers.xml looks like:
```
<Weavers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FodyWeavers.xsd">
  <Realm />
</Weavers>
```

**Comment by LaPeste** [comment]
> Return null realm object
What do you mean by this? Do you get a null [Realm](https://www.mongodb.com/docs/realm-sdks/dotnet/latest/reference/Realms.Realm.html), which to my knowledge should never happen since an exception would have come first. Or are you later on using that realm to extract a [RealmObject](https://www.mongodb.com/docs/realm-sdks/dotnet/latest/reference/Realms.RealmObject.html) that isn't there?

**Comment by LaPeste** [comment]
> 

Also this hints to the fact that you have no `RealmObject`s in your project. Do you have any?

**Comment by LaPeste** [comment]
I'm closing this issue as the reporter hasn't come back in a while.
The user can reopen this github issue if they still experience the problem.
