### ISSUE TITLE
[Bug]:  conflicting documentation 

### ISSUE THREAD

**Issue by carbonete** [realm/realm-dotnet#2975]
### What happened?

At https://www.mongodb.com/docs/realm/sdk/dotnet/advanced-guides/client-reset/ say "If you do not specify a ClientResetHandler, the default is ManualRecoveryHandler"

and 

at https://www.mongodb.com/docs/realm-sdks/dotnet/latest/reference/Realms.Sync.SyncConfigurationBase.html#Realms_Sync_SyncConfigurationBase_ClientResetHandler 
say "The default [DiscardLocalResetHandler](https://www.mongodb.com/docs/realm-sdks/dotnet/latest/reference/Realms.Sync.ErrorHandling.DiscardLocalResetHandler.html) will have no custom actions set for the before and after callbacks."

I think correct is class doc 

 public abstract class SyncConfigurationBase : RealmConfigurationBase
    {
        private ClientResetHandlerBase _clientResetHandler = new DiscardLocalResetHandler();

### Repro steps

access docs

### Version

Last

### What SDK flavour are you using?

MongoDB Atlas (i.e. Sync, auth, functions)

### What type of application is this?

Xamarin

### Client OS and version

Windows 10

**Comment by LaPeste** [comment]
Thank you for the report. You're correct, the default is `DiscardLocalResetHandler`. I'll communicate this issue to the docs team.

**Comment by nirinchev** [comment]
@LaPeste did you file a ticket with the docs team? If so, let's close this issue.

**Comment by LaPeste** [comment]
@nirinchev yes, of course. But it is on out internal platform, so I could not link it here.

**Comment by nirinchev** [comment]
Yeah, that's fine. Let's close this one then. @carbonete thanks again for your report. The docs team has the ticket on their backlog and will address it.
