### ISSUE TITLE
[Bug]: Error Login after update to 10.15.0

### ISSUE THREAD

**Issue by luigidegiacomo** [realm/realm-dotnet#2987]
### What happened?

My WebApp works great with 10.14.0 Realm .Net
I have update to 10.15.0 and running with Realm File on client from prec launching.

this line: 

            User = await app.LogInAsync(Credentials.EmailPassword(Settings.RealmUser,Settings.RealmPassword));

got error: InvalidSession: authentication via 'custom-token' is unsupported

### Repro steps

1) Access to Realm App with 10.14.0 and store/synch realm file
2)Change to 10.15.0
3)Run application

### Version

10.15.0

### What SDK flavour are you using?

MongoDB Atlas (i.e. Sync, auth, functions)

### What type of application is this?

Other

### Client OS and version

MAC OS 12.5

### Code snippets

            User = await app.LogInAsync(Credentials.EmailPassword(Settings.RealmUser,Settings.RealmPassword));

### Stacktrace of the exception/crash you're getting

```shell
Exception thrown: 'Realms.Sync.Exceptions.AppException' in System.Private.CoreLib.dll
Exception thrown: 'Realms.Sync.Exceptions.AppException' in System.Private.CoreLib.dll
Exception thrown: 'System.NullReferenceException' in TalkAppBackEnd.dll
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor: Information: Executing ViewResult, running view Login.
      Executing ViewResult, running view Login.
InvalidSession: authentication via 'custom-token' is unsupported[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor[1]
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor: Information: Executed ViewResult - view Login executed in 3.8955ms.
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor[4]
      Executed ViewResult - view Login executed in 3.8955ms.
```

**Comment by nirinchev** [comment]
I can reproduce this. Will try and fix it shortly.
