### ISSUE TITLE
[Bug]:  API Doc not reflect last version's 

### ISSUE THREAD

**Issue by carbonete** [realm/realm-dotnet#2996]
### What happened?

Doc API at https://www.mongodb.com/docs/realm-sdks/dotnet/10.0.0/reference/Realms.Realm.html#methods

Not contain 10.14.0 (2022-06-02) writeasync update.

### Repro steps

navigate to https://www.mongodb.com/docs/realm-sdks/dotnet/10.0.0/reference/Realms.Realm.html#methods

### Version

10.15.1

### What SDK flavour are you using?

MongoDB Atlas (i.e. Sync, auth, functions)

### What type of application is this?

Xamarin

### Client OS and version

Windows

**Comment by nirinchev** [comment]
Where did you get that API reference link from? The API reference link from the [.NET docs](https://www.mongodb.com/docs/realm/sdk/dotnet/) links to https://www.mongodb.com/docs/realm-sdks/dotnet/latest/ which does contain the new methods.

**Comment by carbonete** [comment]
Sorry, my mistake, I have  browser tab group with docs, and this not pointing to latest. 

Suggestion  in latest Docs deprecated/obsolete functions are  marked only in declaration, may be more visible mark at method doc head help.

thanks for attention @nirinchev
