### ISSUE TITLE
[Bug]: Doc API right menu not work well

### ISSUE THREAD

**Issue by carbonete** [realm/realm-dotnet#2997]
### What happened?

When browse methods right menu not show all methods and not sync. I can't down in this menu.

### Repro steps

![image](https://user-images.githubusercontent.com/3043885/185438434-5ac1dd31-b428-41a6-a9ea-cc003e6c6ac7.png)

### Version

10.15.1

### What SDK flavour are you using?

MongoDB Atlas (i.e. Sync, auth, functions)

### What type of application is this?

Xamarin

### Client OS and version

UWP and Android

**Comment by carbonete** [comment]
Sorry i forgot include browser info.

![image](https://user-images.githubusercontent.com/3043885/185439034-c5a54ca2-a31f-484f-9ce8-1cb0fe71dcfa.png)

**Comment by nirinchev** [comment]
This is a bug in docfx, which we use for docs generation. There seems to be a workaround proposed in [this issue](https://github.com/dotnet/docfx/issues/5671) which we could test.
