### ISSUE TITLE
[Bug]: A Critical Bug ON IOS 

### ISSUE THREAD

**Issue by Bruce-Chan** [realm/realm-dotnet#3003]
### What happened?

I try to build unity project to iOS App. But I found a bug and I can reproduce it. If I use ".Count()" method on IQueryable object, I will met a NotSupportedException exception.

### Repro steps

1.  using the code I show
2.  build it to ios project
3.  run it on my iphone with Xcode
4.  see the exception on Xcode console

### Version

"io.realm.unity": "10.14.0"

### What SDK flavour are you using?

Local Database only

### What type of application is this?

Unity

### Client OS and version

iPhone 15.3.1

### Code snippets
```csharp
        IQueryable<ConversationData> matchedConvs = findConvs(conversType, convID);
        Debug.Log("matchedConvs is " + matchedConvs.ToString());
        Debug.Log("matchedConvs count " + matchedConvs.ToList().Count);
        Debug.Log("After find Convs");
        **if (matchedConvs!= null && matchedConvs.Count() > 0) // it will exception here**
        {
            Debug.Log("try to insert exist conv, conv count="+ matchedConvs.Count());
            insertMsgToExistConv(matchedConvs.First(), message);
        }
```
### Stacktrace of the exception/crash you're getting

```shell
NotSupportedException: The rhs of the binary operator 'Extension' should be a constant or closure variable expression.
Unable to process 'PartialEvalException (NullReferenceException ("Object reference not set to an instance of an object."), value(RealmManager+<>c__DisplayClass22_0).conversType)'.
  at Realms.RealmResultsVisitor.VisitBinary (System.Linq.Expressions.BinaryExpression node) [0x00000] in <00000000000000000000000000000000>:0 
  at Realms.RealmResultsVisitor.VisitCombination (System.Linq.Expressions.BinaryExpression b, System.Action`1[T] combineWith) [0x00000] in <00000000000000000000000000000000>:0 
  at Realms.RealmResultsVisitor.VisitBinary (System.Linq.Expressions.BinaryExpression node) [0x00000] in <00000000000000000000000000000000>:0 
  at Realms.RealmResultsVisitor.VisitMethodCall (System.Linq.Expressions.MethodCallExpression node) [0x00000] in <00000000000000000000000000000000>:0 
  at Realms.RealmResultsVisitor.RecurseToWhereOrRunLambda (System.Linq.Expressions.MethodCallExpression m) [0x00000] in <00000000000000000000000000000000>:0 
  at Realms.RealmResultsVisitor.VisitMethodCall (System.Linq.Expressions.MethodCallExpression node) [0x00000] in <00000000000000000000000000000000>:0 
  at Realms.RealmResultsProvider.Execute (System.Linq.Expressions.Expression expression) [0x00000] in <00000000000000000000000000000000>:0 
  at Realms.RealmResultsProvider.Execute[T] (System.Linq.Expressions.Expression expression) [0x00000] in <00000000000000000000000000000000>:0 
  at RealmManager.insertNotificationMsg (System.Int32 conversType, System.String convID, System.String convName, System.String ConvImageURL, MessageData message) [0x00000] in
```

### Relevant log output

```shell
Log1(Success): matchedConvs is Realms.RealmResults`1[ConversationData]
Log2(Success): matchedConvs count 0
Log3(Success): After find Convs
```

**Comment by fealebenpae** [comment]
Hey @Bruce-Chan, can you share the code that builds your query (the `findConvs` method)? Alternatively, the value of `matchedConvs.Expression.ToString()` can also help. It sounds like there’s a LINQ expression there that’s not supported by our query translator.

**Comment by Bruce-Chan** [comment]
> Hey @Bruce-Chan, can you share the code that builds your query (the `findConvs` method)? Alternatively, the value of `matchedConvs.Expression.ToString()` can also help. It sounds like there’s a LINQ expression there that’s not supported by our query translator.

private List<ConversationData> findConvs(int conversType, string convID)
    {
        Debug.LogFormat("findConvs:conversType={0}, convID={1}", conversType, convID );

        return realm.All<ConversationData>().Where(c => c.ConversType == conversType && c.Id == convID).ToList();
    }



    private List<ConversationData> findConvs(int conversType)
    {
        Debug.LogFormat("findConvs:conversType={0}", conversType);

        return realm.All<ConversationData>().Where(c => c.ConversType == conversType).ToList();
    }

**Comment by Bruce-Chan** [comment]
> ```cs
> private List<ConversationData> findConvs(int conversType, string convID)
>     {
>         Debug.LogFormat("findConvs:conversType={0}, convID={1}", conversType, convID );
> 
>         return realm.All<ConversationData>().Where(c => c.ConversType == conversType && c.Id == convID).ToList();
>     }
> 
> 
> 
>     private List<ConversationData> findConvs(int conversType)
>     {
>         Debug.LogFormat("findConvs:conversType={0}", conversType);
> 
>         return realm.All<ConversationData>().Where(c => c.ConversType == conversType).ToList();
>     }
> ```

private IQueryable<ConversationData> findConvs(int conversType, string convID)
    {
        Debug.LogFormat("findConvs:conversType={0}, convID={1}", conversType, convID );

        return realm.All<ConversationData>().Where(c => c.ConversType == conversType && c.Id == convID);
    }



    private IQueryable <ConversationData> findConvs(int conversType)
    {
        Debug.LogFormat("findConvs:conversType={0}", conversType);

        return realm.All<ConversationData>().Where(c => c.ConversType == conversType);
    }

**Comment by Bruce-Chan** [comment]
It seems that  I modified the code last time, and it should look like that.

**Comment by nirinchev** [comment]
Are you sure this is the code that actually throws? Looking at the stacktrace, it seems like `conversType` is not a variable but rather a field on another type (probably `RealmManager`?). Ideally, if you can share a small project that reproduces the issue, that would be super helpful.

**Comment by Bruce-Chan** [comment]
> 

Yes, I am sure. I need to convert all the result got from realm to the list, by using `ToList()`. If I don't do that, I will get a lot of exception.

**Comment by nirinchev** [comment]
I have made a very simple app attempting to reproduce the issue and things seem to work for me. I've run it both on the simulator and my iPhone 12 Pro and it works on both. I'm attaching the project here for your to run and verify if it works for you. If it does, can you please modify it in a way so that it starts failing and send it back?

It contains a very barebones script, that will open a Realm on start, insert a `ConversationData` then create a query and count the matches. The expectation is that the number of matches increases every time the project is run.

[Issue3003.zip](https://github.com/realm/realm-dotnet/files/9489649/Issue3003.zip)

**Comment by nirinchev** [comment]
I'm going to close this one due to inactivity. Feel free to reopen if you do get back to it and are able to provide more information.
