### ISSUE TITLE
A signature of `Assert.Throw` is something misused when checking for the exception err msg. This should be fixed

### ISSUE THREAD

**Issue by LaPeste** [realm/realm-dotnet#3021]
`Assert.Throws<T>(TestDelegate code, string message, params object[] params);` is something misused thinking that `message` is actually the message NUnit is going to check for equality in the returned exception. This is not the case. That message is only used when the test fails, to show devs a possible reason for failure.
The proper way of checking for the exception's message is
```cs
var ex = Assert.Throws<ExceptionType>(() => /*code that throws*/);
Assert.That(ex.Message.Contains("Expected content of the exception's error"), Is.True);
// or
Assert.That(ex.Message, Is.EqualTo("Exact expected content of the exception's error"));
```

Just 3 examples of the wrong usage in the codebase:
1. https://github.com/realm/realm-dotnet/blob/4a8888a7f98127e2898b82ccb49213d85b4738fb/Tests/Realm.Tests/Database/CollectionTests.cs#L1550
2. https://github.com/realm/realm-dotnet/blob/4a8888a7f98127e2898b82ccb49213d85b4738fb/Tests/Realm.Tests/Database/CollectionTests.cs#L1557
3. https://github.com/realm/realm-dotnet/blob/4a8888a7f98127e2898b82ccb49213d85b4738fb/Tests/Realm.Tests/Database/DynamicEmbeddedTests.cs#L749
4. There are more of these error. It needs to be searched.

**Comment by papafe** [comment]
I'm closing this as it seems we don't have any remaining wrongly used `message` in our codebase
