### ISSUE TITLE
[Bug]: App Store Connect error: The executable contains bitcode

### ISSUE THREAD

**Issue by tipa** [realm/realm-dotnet#3059]
### What happened?

I upgraded my app from a "legacy" Xamarin to a .NET 6 project and built it with Visual Studio and Xcode 14 and uploaded the .ipa to AppStore Connect. Shortly after I received a mail with the error:
```
Dear Developer,
We identified one or more issues with a recent delivery for your app, "MyApp". Please correct the following issues, then upload again. 
ITMS-90482: Invalid Executable - The executable 'MyApp.app/Frameworks/realm-wrappers.framework/realm-wrappers' contains bitcode. 
Best regards,
The App Store Team
```
This prevents me to publish my app update.

I don't know if this is a problem that you can resolve or Microsoft/the Xamarin team needs to fix. I think the problem has to do with bitcode being deprecated since Xcode 14 (see [here](https://developer.apple.com/documentation/Xcode-Release-Notes/xcode-14-release-notes))

### Repro steps

- Create .NET6 for iOS project
- Add latest Realm NuGet package
- Build .ipa in Release mode with Xcode 14
- Upload .ipa file to App Store Connect

### Version

10.17.0

### What SDK flavour are you using?

Local Database only

### What type of application is this?

Other / .NET for iOS

### Client OS and version

N/A

**Comment by nirinchev** [comment]
I think we have a fix for this. If you're willing to test it out and confirm it works, you can install it from our [nightly build feed](https://github.com/realm/realm-dotnet#nightly-builds). The version you need is `10.17.0-pr-3060.629`.

**Comment by tipa** [comment]
Thanks! Seems to work now with the version from the nightly feed.
