### ISSUE TITLE
Default constructor is removed by linker on iOS

### ISSUE THREAD

**Issue by kristiandupont** [realm/realm-dotnet#307]
..which means that our woven constructor cannot be invoked through `CreateObject<>()` if the constructor is never explicitly used.

**Comment by AndyDentFree** [comment]
Can add an XML file to fix this according to new user on [Xamarin Forum](https://forums.xamarin.com/discussion/comment/210171#Comment_210171)

**Comment by nirinchev** [comment]
I'd guess they are referring to https://developer.xamarin.com/guides/cross-platform/advanced/custom_linking/. However, it requires manipulating the mtouch arguments which is rather unpleasant :) Weaving `[Preserve]` seems to be easier and more robust.

**Comment by nirinchev** [comment]
This should be fixed in #843
