### ISSUE TITLE
Typo in source generator error message

### ISSUE THREAD

**Issue by peppy** [realm/realm-dotnet#3081]
### What happened?

https://github.com/realm/realm-dotnet/blob/a7b8f3a749d1a863ac617acee656bcf179ed7cd9/Realm/Realm.SourceGenerator/Diagnostics.cs#L144

"annotiation" should be "annotation"

### Version

6

### What SDK flavour are you using?

Local Database only

### What type of application is this?

Other

### Client OS and version

10.18.0

**Comment by papafe** [comment]
@peppy Thanks for the issue, good eye! 😄
