### ISSUE TITLE
[Bug]: SourceGenerated classes cant be in 'Realm' namespace

### ISSUE THREAD

**Issue by J-Swift** [realm/realm-dotnet#3099]
### What happened?

If you have a namespace ending in `Realm` the SG class ends up getting confused.

```
using Realms;

namespace MyApp.Realm;

public partial class Foo : IRealmObject { }
```
Results in:
> CS0738: 'Foo' does not implement interface member 'IRealmObjectBase.Realm'. 'Foo.Realm' cannot implement 'IRealmObjectBase.Realm' because it does not have the matching return type of 'Realm'.

This is because the naming collision between `MyApp.Realm` and `Realms.Realm`, and the generated class not using the fully-qualified `Realms.Realm`. I'm not sure theres a way to fix it by overriding, I think since this collides with codegen it should be simple enough to just fully qualify names on that side?

### Repro steps

See above

### Version

6

### What SDK flavour are you using?

Local Database only

### What type of application is this?

Other

### Client OS and version

Maui

**Comment by papafe** [comment]
Thanks for reporting! Yes, it seems we need to fully qualify Realm in this case, the fix will probably be included in the next version
