### ISSUE TITLE
Cascading Deletes

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#310]

**Comment by Harvinator** [comment]
Hi would like to request this feature as I'm having to write and manage boiler plate code to handle this.

Got excited when I saw you recently bumped to version 1 as I was expecting it to be available based on [this from the documentation](https://realm.io/docs/xamarin/latest/#current-limitations)

> Features missing from this beta version which are expected to be added prior to 1.0 release:
> 
> Async queries
> **Cascading deletes** (but see a workaround in [this StackOverflow answer](http://stackoverflow.com/a/37840478/53870))
> More LINQ operations - see details on the [LINQ Support page](https://realm.io/docs/xamarin/latest/api/linqsupport.html)
> Searching by related data

**Comment by SKLn-Rad** [comment]
Any news on this? As far as some searching goes it appears to be done in iOS Native so it would be nice to have alignment here as well! :D

**Comment by nirinchev** [comment]
I am not aware of a native implementation. Can you link to the document that claims otherwise? There is no progress on the .NET front on this yet.

**Comment by nirinchev** [comment]
This is addressed to a certain extend by using embedded objects which will ship with v10. We don't have plans to support cascading deletes for non-embedding relationships at this point.
