### ISSUE TITLE
multiple FlexibleSyncConfiguration problem

### ISSUE THREAD

**Issue by sansamit** [realm/realm-dotnet#3105]
### What happened?

I have 2 FlexibleSyncConfiguration settings in one app. Hereinafter, they will be referred to as A and B.

However, the first open A seems to run PopulateInitialSubscriptions ,
The B that opens next doesn't seem to perform PopulateInitialSubscriptions .

### Repro steps

I have 2 FlexibleSyncConfiguration settings in one app. Hereinafter, they will be referred to as A and B.

However, the first open A seems to run PopulateInitialSubscriptions ,
The B that opens next doesn't seem to perform PopulateInitialSubscriptions .

### Version

10.18.0

### What SDK flavour are you using?

MongoDB Atlas (i.e. Sync, auth, functions)

### What type of application is this?

WPF

### Client OS and version

win10

**Comment by nirinchev** [comment]
Can you share some code - particularly how you're creating the configs? `PopulateInitialSubscriptions` is only run when the Realm file is first created. Are you specifying different users or file paths for the configurations? If you're creating both with the same user and don't customize the file path, they end up pointing to the same file on disk, so essentially opening the same Realm.

**Comment by sansamit** [comment]
```
public static async Task<RealmConfigurationBase> GetMinuteCandleStickGeneratorConfigurationAsync(string dataDir)
{
   string key = "minute_candle_stick_generator";

   if (!_configurations.TryGetValue(key, out RealmConfigurationBase configuration))
   {
       AppConfiguration appConfiguration = new("@@@@@@@@@@@@@@@@@@");
       App app = App.Create(appConfiguration);
       string apiKey = "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@m";
       User user = await app.LogInAsync(Credentials.ApiKey(apiKey));

       configuration = new FlexibleSyncConfiguration(user, Path.Combine(dataDir, $"{user.Id}.realm"))
       {
           ClientResetHandler = new RecoverOrDiscardUnsyncedChangesHandler(),
           PopulateInitialSubscriptions = (_) =>
           {
               _.Subscriptions.Add(_.All<FC>());
               _.Subscriptions.Add(_.All<MCS>());
           }
       };

       _configurations.TryAdd(key, configuration);
   }

   return configuration;
}

public static async Task<RealmConfigurationBase> GetMovingAverageCalculatorConfigurationAsync(string dataDir, string commodity)
{
   string key = commodity;

   if (!_configurations.TryGetValue(key, out RealmConfigurationBase configuration))
   {
       AppConfiguration appConfiguration = new("("@@@@@@@@@@@@@@@@@@");");
       App app = App.Create(appConfiguration);
       User user = await app.LogInAsync(Credentials.Anonymous());

       configuration = new FlexibleSyncConfiguration(user, Path.Combine(dataDir, $"{commodity}.realm"))
       {
           ClientResetHandler = new RecoverOrDiscardUnsyncedChangesHandler(),
           PopulateInitialSubscriptions = (_) =>
           {
               _.Subscriptions.Add(_.All<MCS>().Where((_) => _.Commodity == commodity));
               _.Subscriptions.Add(_.All<MA>().Where((_) => _.Commodity == commodity));
           }
       };

       _configurations.TryAdd(key, configuration);
   }

   return configuration;
}
```



Each local db file path is different.
When I tested it a bit more, it seems that when I have 2 environments in one app, the writing of the realm for each environment is unified.

After all, when writing data to A, B is interlocked, and when writing data to B, it seems that A is interlocked.

This test was attempted in one process.
It has not been tested in different processes.

**Comment by nirinchev** [comment]
What do you mean that writing is interlocked? That when you write to A, you cannot write to B or that the data you write to A appears in B as well? Neither of these should happen and if they do, it would be great if you can provide a minimal project that reproduces the issue. Also, I assume you closed this by mistake? Or is this no longer an issue for you?
