### ISSUE TITLE
[Bug]: RealmConfiguration not shared

### ISSUE THREAD

**Issue by ghost** [realm/realm-dotnet#3109]
### What happened?

realms are cool.

There is something strange about this test.

I've noticed a peculiar phenomenon where RealmConfiguration cannot be shared.
Remember to share RealmConfiguration after creating it in UI thread.
If you take out the RealmConfiguration from the thread and use it
A thread conflict error occurs.

I'd like to share my code, but unfortunately I can't because I'm testing it without using the reuse method.

### Repro steps

realms are cool.

There is something strange about this test.

I've noticed a peculiar phenomenon where RealmConfiguration cannot be shared.
Remember to share RealmConfiguration after creating it in UI thread.
If you take out the RealmConfiguration from the thread and use it
A thread conflict error occurs.

I'd like to share my code, but unfortunately I can't because I'm testing it without using the reuse method.

### Version

latest

### What SDK flavour are you using?

Local Database only

### What type of application is this?

WPF

### Client OS and version

Windows 10 Pro 19044.2251

**Comment by papafe** [comment]
Hi @sansamit, I just wanted to confirm I have understood the situation.

You created a RealmConfiguration on the main thread and opened a realm with it. Then you used the same object to open a realm on another thread but you got an exception. Is this correct?
Also, what kind of exception/error did you get?

**Comment by sansamit** [comment]
```
...
RealmConfiguration _config;

public void Main() {
    _config = new RealmConfiguration("...");
   using Realm realm = Realm.GetInstance(_config);

   Task.Run(() => {
       using Realm realm2 = Realm.GetInstance(_config);
       Test test = realm2.All<Test>().Where((_) => _.id == "abc");

       Console.WriteLine(test.Value);         <========== realm incorrect thread.!!!
   });
}
```

**Comment by papafe** [comment]
Thanks for the code, we'll investigate

**Comment by papafe** [comment]
I did not manage to reproduce this with the latest version of the SDK, so I am closing it for now. Feel free to reopen it if this is still an issue for you
