### ISSUE TITLE
[Bug]:  string count returns wrong value in Turkish

### ISSUE THREAD

**Issue by mfa95** [realm/realm-dotnet#3119]
### What happened?

I'm trying to filter words by Length in realm database where there are Turkish words. However, words with Turkish characters are filtered incorrectly.

Turkish characters: (ş Ş ı ü Ü ö Ö ç Ç ğ Ğ İ)

For example, when the command to filter words with a word length of 3 is run, the words with Turkish characters do not appear even though they are 3 letters. each letter counts as 2 characters.
Example: 
"gol" => Length = (3) --> true
"çok" => Length = (4) --> false, because it must be 3 characters
"çağ" => Lenth = (5) --> false, because it must be 3 characters.

I can't do length filtering with Linq. it gives an error.
Code:
```
var db = _realm.All<Model>().Where(s=> s.wordString.Length == 3);

"NotSupportedException: The left-hand side of the GreaterThan operator must be a direct access to a persisted property in Realm. Unable to process 'w.word.Length'."
```

(except realm, linq counts letters correctly. but with realm this command cannot be used (without copying))

so i am using realm query.
Code:
`var db = _realm.All<Model>().Filter($"wordString.@count ==3");`

here words containing turkish characters do not return correct length. 
this query does not include:
"yaş, çip, çağ, tüp, küp, şok, dağ etc.."

(sorry i used google translate.)

### Repro steps

*Can be tested either with code or with realm studio.
1) Add words containing Turkish characters to realm database.
2) open realm studio
3) Type the character length of a word you know the length of in the search bar. Example word "çağ" is 3 characters. but it comes up in 5 length searches! false!

1) "word.@count = 3 AND word LIKE "çağ""
that's what it had to be: found
 in reality:found
only this (in the wrong query) can be found => "word.@count = 5 AND word LIKE "çağ""

### Version

.Net Standart 2.1

### What SDK flavour are you using?

Local Database only

### What type of application is this?

Unity

### Client OS and version

Windows 10

### Code snippets

public class Model : RealmObject
{
    [PrimaryKey] public int wordId { get; set; }
    [Required] public string wordString { get; set; }
    public Model(int wordId, string wordString )
    {
        this.wordId = wordId;
        this.wordString = wordString ;
    }
}

**Comment by LaPeste** [comment]
> I can't do length filtering with Linq. it gives an error.

That's expected. Unfortunately the LINQ implementation of the .NET Realm SDK does not yet support querying on linked objects.
Regarding the issue with the count of Turkish characters I can confirm that I can reproduce the issue.
We'll look into it and report back.

**Comment by LaPeste** [comment]
Given that this isn't an issue with our SDK but with Core, I'm going to close this issue as we can't do much for it.
