### ISSUE TITLE
Add some .NET Reactive Extensions love

### ISSUE THREAD

**Issue by WarBorg** [realm/realm-dotnet#3171]
### Problem

Hello, we are interested in using Realm as a cacheing solution in our Xamarin mobile app project because we work a lot with live data coming from the cloud and on the mobile app we use .net reactive extensions a lot

I was a bit surprised that there are implementations for RxJava but not for .NET Rx, or maybe I didn't find it ? 

Any help would be appreciated!

### Solution

one possible solution would be to add a nuget package with extension methods dedicated to using .NET Reactive Extensions like returning IObservable from the database objects etc

### How important is this improvement for you?

Would be a major improvement

### Feature would mainly be used with

Local Database only

**Comment by nirinchev** [comment]
Hey, we haven't received many requests for Rx improvements - there's been a few between the years, but nothing to indicate it's a major pain point for a significant portion of our users. While we don't plan to add first party support for Rx, we'd be happy to work with and help the community should they decide to pick it up.

**Comment by WarBorg** [comment]
hey @nirinchev thank you for the replay, yea unfortunately the. NET community has not embraced Rx like the other communities have (the irony is that Rx came out from the Microsoft research labs :D) 
 I guess we can always use Rx to transform the events provided by Realm to observable streams, or do you see any potencial downsides to this approach?

**Comment by nirinchev** [comment]
I don't see major concerns with this approach. As with everything reactive, the main thing to watch out for is threading, but as long as there's a well-behaved synchronization context installed, things should just work.
