### ISSUE TITLE
App crashes while using MapTo() and PopulateInitialSubscriptions

### ISSUE THREAD

**Issue by movsar** [realm/realm-dotnet#3178]
### What happened?

While using PopulateInitialSubscriptions (on clean, fresh start without a database file), on attempt to write a new object, Realm throws `RealmException: Cannot write to class <ClassName>when no flexible sync subscription has been created.`. 

It happens when using models with MapTo attribute, without the attribute everything works fine.

### Repro steps

1. Try to connect with PopulateInitialSubscriptions and a model with MapTo attribute
2. Exception 

Solution: Removing MapTo and renamed the object model from LanguageEntity to Language solved the problem.

Although I made it work, it's inconvenient to work without **MapTo**, please take a look.

### Version

.NET 6

### What Atlas Services are you using?

Atlas Device Sync

### What type of application is this?

Other

### Client OS and version

Windows 10

### Code snippets

Use this code to connect:
```
            _app = App.Create(new AppConfiguration(myRealmAppId) {
                BaseFilePath = FileService.AppDataDirectory,
            });
            _user = await _app.LogInAsync(Credentials.Anonymous());
            _config = new FlexibleSyncConfiguration(_user)
            {
                PopulateInitialSubscriptions = (realm) =>
                {
                    realm.Subscriptions.Add(realm.All<LanguageEntity>());
                }
            };
            var _realm = Realm.GetInstance(_config);
            await _realm.Subscriptions.WaitForSynchronizationAsync();
       
            _realm.Write(() =>
            {
                var languages = _localRealm.All<LanguageEntity>();
                foreach (var language in languages)
                {
                    _realm.Add(new LanguageEntity() { Code = language.Code, _id = language._id });
                }
            });

            await _realm.Subscriptions.WaitForSynchronizationAsync();
```
With this model:
```
namespace Data.Entities
{
    [MapTo("Language")]
    public class LanguageEntity : RealmObject
    {
        [PrimaryKey]
        public ObjectId _id { get; set; } = ObjectId.GenerateNewId();
        public string Code { get; set; } = string.Empty;
        public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.Now;
    }
}
```

And if Realm.GetInstance() is changed to await Realm.GetInstanceAsync() - it just hangs there indefinitely with these logs (after which it’s just ping-pong logs:

### Stacktrace of the exception/crash you're getting

```shell
RealmException: Cannot write to class Language when no flexible sync subscription has been created.
```

### Relevant log output

```shell
APP: Realm : 2023-01-13 04:19:35.526 Debug: WebSocket::initiate_client_handshake()
APP: Realm : 2023-01-13 04:19:35.758 Debug: WebSocket::handle_http_response_received()
APP: Realm : 2023-01-13 04:19:35.760 Detail: Connection[1]: Negotiated protocol version: 7
APP: Realm : 2023-01-13 04:19:35.761 Debug: Connection[1]: Will emit a ping in 12788 milliseconds
APP: Realm : 2023-01-13 04:19:35.763 Debug: Connection[1]: Session[1]: Sending: IDENT(client_file_ident=18, client_file_ident_salt=576499042362797227, scan_server_version=12, scan_client_version=5, latest_server_version=12, latest_server_version_salt=4481538362546054629, query_version: 0 query_size: 2, query: “{}”)
APP: Realm : 2023-01-13 04:19:35.765 Debug: Connection[1]: Session[1]: Sending: MARK(request_ident=2)
APP: Realm : 2023-01-13 04:19:36.140 Debug: Connection[1]: Session[1]: Received: MARK(request_ident=2)
APP: Realm : 2023-01-13 04:19:36.142 Debug: Connection[1]: Session[1]: Sending: UPLOAD(progress_client_version=13, progress_server_version=12, locked_server_version=12, num_changesets=0)
APP: Realm : 2023-01-13 04:19:49.259 Debug: Connection[1]: Sending: PING(timestamp=133122415, rtt=0)
APP: Realm : 2023-01-13 04:19:49.321 Debug: Connection[1]: Received: PONG(timestamp=133122415)
APP: Realm : 2023-01-13 04:19:49.326 Debug: Connection[1]: Round trip time was 67 milliseconds
APP: Realm : 2023-01-13 04:19:49.327 Debug: Connection[1]: Will emit a ping in 55078 milliseconds
The thread 0x759c has exited with code 0 (0x0).
The thread 0x7560 has exited with code 0 (0x0).
The thread 0x7004 has exited with code 0 (0x0).
The thread 0x29cc has exited with code 0 (0x0).
The thread 0x675c has exited with code 0 (0x0).
APP: Realm : 2023-01-13 04:20:44.900 Debug: Connection[1]: Sending: PING(timestamp=133178056, rtt=67)
APP: Realm : 2023-01-13 04:20:44.962 Debug: Connection[1]: Received: PONG(timestamp=133178056)
APP: Realm : 2023-01-13 04:20:44.964 Debug: Connection[1]: Round trip time was 64 milliseconds
APP: Realm : 2023-01-13 04:20:44.965 Debug: Connection[1]: Will emit a ping in 55907 milliseconds
```

**Comment by papafe** [comment]
Hi @movsar
I've just copied your example to a Console app and everything is working as expected. 

What I think could have happened:
- You already opened a synced realm at some point in FileService.AppDataDirectory
- You added a subscription for `LanguageEntity`, but you didn't use the `MapTo` attribute.
- You are trying to reopen the same synced realm
- `PopulateInitialSubscriptions` is called only once in the lifetime of the realm, so it has no effect now that you're calling again
- There is no subscription for `Language` now, so you get the exception.

If you remove the sync folder and run the following console app you will get the same behaviour you're seeing:

```csharp
var myRealmAppId = ".....";
var _app = App.Create(new AppConfiguration(myRealmAppId)
{
    BaseFilePath = MySyncFolder,
});

var _user = await _app.LogInAsync(Credentials.Anonymous());
var _config = new FlexibleSyncConfiguration(_user);
var _realm = Realm.GetInstance(_config);

await _realm.Subscriptions.WaitForSynchronizationAsync();

_realm.Write(() =>
{
    _realm.Add(new LanguageEntity() { Code = "test" });
});

await _realm.Subscriptions.WaitForSynchronizationAsync();

```
In this case I've removed `PopulateInitialSubscriptions` so there are no subscriptions available. If you remove the sync folder and add back `PopulateInitialSubscriptions`, it will start to work.

**Comment by movsar** [comment]
Hi @papafe I don't think I have a sync folder, where should I look for it? I didn't understand what you meant by 
`You added a subscription for LanguageEntity, but you didn't use the MapTo attribute. This means that in the database you have a subscription for LanguageEntity.`
should I have used MapTo somewhere in Subscriptions? Otherwise it was present in LanguageEntity before I removed it and renamed the class to Language, when it started to work.

Other points I didn't fall to, I cleaned up the project multiple times and it was tried with fresh starts many times as well. But it's no longer an issue for me, and if you can't reproduce it, maybe you can close this until somebody else comes up with more information as to why it had happened.

The problem with such issues is that there is no comprehensive error message given, the app just hangs, in debug the ping-pong messages or very general information like, if you added more information to exception, it would be much easier for us (developers) to understand what's happening and for you (maintainers) to fix it.

Thank you

**Comment by papafe** [comment]
@movsar Sorry if I wasn't clear, let me try to explain what I meant in some points. 

When you are creating your app, you are using:
```
_app = App.Create(new AppConfiguration(myRealmAppId) {
                BaseFilePath = FileService.AppDataDirectory,
            });
```
`BaseFilePath` is the root folder relative to which all local data for this application will be stored. This data includes metadata for users and synchronized Realms. This is also related to your other point. Even if you clean the project, if you don't remove this folder, you'll still keep the realm and all the associated metadata, that is probably why you could not get rid of the issue. And that is also why I think maybe the first time you opened the realm for the first time you didn't have `MapTo` in the model definition, although you could have done something slightly different. 

Regarding `MapTo`, I think that when you started the application the first time, you probably didn't have it set it yet, that's what I meant. Setting it up in the model definition is the only thing that is necessary, you don't need to set it anywhere else. 

Regarding the errors... I agree that the app should not hang indefinitely when `GetInstanceAsync` is used, but it should give them the same error when the non-async version is used (`GetInstance`). Regarding the exception, I think that in this case `RealmException: Cannot write to class Language when no flexible sync subscription has been created` is quite explicative. 
The thing is that your project ended up in a strange state because, possibly, the first time you opened it you were not using `MapTo` and you setup the subscriptions differently. I think there are different things that were happening here at the same time, and it's definitely difficult to understand exactly what was the cause of the issue you were experiencing. 

Overall, if you delete the sync folder, it'll be like starting from scratch, and you should be able to solve your issues.

**Comment by movsar** [comment]
@papafe thank you for the explanation, yes, I did clean the BaseFilePath and yes, the first time I created the database and synced, the MapTo existed in the models, because Entry and Word are already used in .NET so right from the beginning I decided to use *Entity names with MapTo.

Regarding error messages - yes, this particular message is expressive indeed, that's why I was able to quickly find a workaround, but I've been struggling with Realm Sync for many days and the other issues unfortunately didn't produce such explicative error messages: for example, [this one](https://www.mongodb.com/community/forums/t/client-tried-to-connect-using-flexible-sync-before-initial-sync-is-complete/208025/13)

Thank you.
