### ISSUE TITLE
The Realm file stores data in an outdated format

### ISSUE THREAD

**Issue by MihailsKuzmins** [realm/realm-dotnet#3181]
### What happened?

When opening a `something.realm` file with a latest [Realm Studio](https://www.mongodb.com/docs/realm-legacy/products/realm-studio.html) (13.0.2) there is a notification that files are created with an outdated format. Cannot seem to find a workaround.

![image](https://user-images.githubusercontent.com/47413092/213160080-c6fb9b8f-f2e6-4c25-8040-ee82383a7d0d.png)

### Repro steps

- Install Realm (10.19.19), Realm.Fody (10.19.19), Realm.SourceGenerator (10.19.19)
- create a realm file. Add some data
- try opening it with the Realm Studio

### Version

.net6

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Other

### Client OS and version

Windows10

**Comment by LaPeste** [comment]
I can confirm the issue. I'm going to investigate and report back.

**Comment by nirinchev** [comment]
Studio 13 uses Core 13 which we'll upgrade to with 10.20. Since 10.19 uses Core 12, you need Studio 12 to read/write files in the same format.
