### ISSUE TITLE
Unity3D - Failed to weave assembly. 

### ISSUE THREAD

**Issue by georgiitonchev** [realm/realm-dotnet#3198]
### What happened?

I get the "Failed to weave assembly." error for one of my assemblies in my Unity project. Happens on any assembly reload.
Tools > Realm > Weave Assemblies also produces the same result.

### Repro steps

Assembly Reload due to code changes in solution -> "Failed to weave assembly."
Tools > Realm > Weave Assemblies  -> "Failed to weave assembly."

### Version

10.19.0

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Unity

### Client OS and version

Microsoft Windows 11 Pro - 10.0.22621 Build 22621

**Comment by nirinchev** [comment]
Hey @georgiitonchev did you mean to close this issue or did you do it accidentally? If it's still a problem, do you think you can share a minimal repro that we can try out locally?
