### ISSUE TITLE
Adding Subscriptions during development

### ISSUE THREAD

**Issue by liftee** [realm/realm-dotnet#3235]
### What happened?

I had to uninstall the application to get the subscriptions to refresh when adding another subscription during development.

### Repro steps

1. Update the RealmService Class GotRealm() from the .NET MAUI Sample project with another subscription query
2. Try and add new record from the user interface
3. receive error no subscription found
4. uninstall the application
5. rerun the application within visual studio
6. able to add CRUD

### Version

10.20.0

### What Atlas Services are you using?

Atlas Device Sync

### What type of application is this?

Other

### Client OS and version

Windows 11

### Code snippets

 PopulateInitialSubscriptions = (realm) =>
            {
                // Item
                var (query, queryName) = GetQueryForSubscriptionType(realm, SubscriptionType.Mine);
                realm.Subscriptions.Add(query, new SubscriptionOptions { Name = queryName });

               [new Subscription here]
...

### Stacktrace of the exception/crash you're getting

```shell
no subscription found execption
```

**Comment by nirinchev** [comment]
`PopulateInitialSubscriptions` only gets invoked the first time the Realm is opened. So if you change the subscriptions that get created there, you'll need to delete the Realm file (or uninstall the app) to get it to trigger again. Alternatively, you could modify the subscriptions at any time using `realm.Subscriptions.Update`.

**Comment by nirinchev** [comment]
Closing this due to lack of response. Feel free to reopen if that's still an issue for you.
