### ISSUE TITLE
Possibility to reset an EmbeddedObject

### ISSUE THREAD

**Issue by meierhoeferjannis** [realm/realm-dotnet#3262]
### Problem

Im currently working with Automapper in my Project to Map from an DTO to a RealmObject that also contains an EmbeddedObject.
The problem is that Automapper gets the instance of the nested Object, maps it's Properties and then tries to set the exact same instance back to the field via the setter. 
This causes Realm to throw an 
 **Realms.Exceptions.RealmException Can't link to an embedded object that is already managed**
event though the RealmObject and the nested Object are the same instances. Would it be possible for realm to check if the EmbeddedObject is getting reassigned to the same Parent Instance and so no new link has to be established ?

### How important is this improvement for you?

I would like to have it but have a workaround

### Feature would mainly be used with

Atlas Device Sync

**Comment by nirinchev** [comment]
Hey, thanks for the report. This makes sense to me and we should probably special case it. I don't have an estimate when we'll be able to pick it up, but I hope it can go in before the next release.
