### ISSUE TITLE
Issues with Unity Il2cpp on UWP ARM64

### ISSUE THREAD

**Issue by Suddelnuppe** [realm/realm-dotnet#3264]
Hey, we are currently evaluating Realm as a Database for our project. However we encountered some issues on UWP ARM64 with Unity.

### What happened?

When we are trying to build for HoloLens 2 on UWP ARM64 via Unity, il2cpp throws an linker error

### Repro Steps

Create an empty Unity project with Unity 2021.3.5f1 LTS, add Realm via UPM and build for UWP ARM64. After compiling the resulting Visual Studio Solution, we get the error message. iOS and Android seemed to work fine so far.

We already tried to change the obvious parameters like build config (Debug, Release, Master), IL2CPP code generation (smaller faster build, faster runtime) and tried adding the dlls to the link.xml to avoid assembly stripping. Nothing did change.

### Version

10.20.0

### What type of platform is this?

Cross platform solution, UWP ARM64, Android, iOS

### Client OS and Version

Windows 10 and Windows 11 tested with both Visual Studio 2019 and 2022

### Code Snippets

We didn't write a single line of code, we just added the dependency

### Stacktrace

`1>EXEC : error : Unity.IL2CPP.Building.BuilderFailedException: Realm.cpp`

`1>Build\Il2CppOutputProject\Source\il2cppOutput\Realm.cpp(38408): error C2664: 'Expression_tC1A9026F0E722992682A07158173040E34601E0A *PartialEvaluatingExpressionVisitor_EvaluateIndependentSubtrees_m9917185E9452E8E6BDE3AA9D2D8F3F0FDE09DABC(Expression_tC1A9026F0E722992682A07158173040E34601E0A *,RuntimeObject *,const RuntimeMethod *)': cannot convert argument 1 from 'Expression_t70AA908ECBD33E94249BF235E4EBB0F831AD8785 *' to 'Expression_tC1A9026F0E722992682A07158173040E34601E0A *'`

`1>Build\Il2CppOutputProject\Source\il2cppOutput\Realm.cpp(38408): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast`

`1>Build\Il2CppOutputProject\Source\il2cppOutput\Realm.cpp(9110): note: see declaration of 'PartialEvaluatingExpressionVisitor_EvaluateIndependentSubtrees_m9917185E9452E8E6BDE3AA9D2D8F3F0FDE09DABC'`

`1>Build\Il2CppOutputProject\Source\il2cppOutput\Realm.cpp(38408): note: while trying to match the argument list '(Expression_t70AA908ECBD33E94249BF235E4EBB0F831AD8785 *, EvaluatableExpressionFilter_t27C7CB7F55B1EC4E002FFE3B10FEB5EEEBB041FE *, int)'`

`1>Build\Il2CppOutputProject\Source\il2cppOutput\Realm.cpp(38409): error C2440: '=': cannot convert from 'Expression_tC1A9026F0E722992682A07158173040E34601E0A *' to 'Expression_t70AA908ECBD33E94249BF235E4EBB0F831AD8785 *'`

`1>Build\Il2CppOutputProject\Source\il2cppOutput\Realm.cpp(38409): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast`

**Comment by nirinchev** [comment]
This seems to point to relinq: https://github.com/re-motion/Relinq/blob/769b56688ef4bbdb2e68abf5708bb9692451d298/Core/Parsing/ExpressionVisitors/PartialEvaluatingExpressionVisitor.cs#L43.

Not sure why it's complaining, but if that's just an empty project and you're not actually exercising this codepath, it's possible that this code is strippable - have you tried [instructing the managed linker](https://docs.unity3d.com/Manual/ManagedCodeStripping.html) to increase the code stripping aggressiveness? While I think it points to a Unity bug, it's possible that we can workaround it temporarily by stripping the offending code.

**Comment by Suddelnuppe** [comment]
Ok, setting the stripping level to medium seems to have fixed it, however I yet have to evaluate if this will impact the live project in any way.

Suppose I wanna use the library as intended, will this cause problems again?

**Comment by nirinchev** [comment]
I can't say without having further investigated this. If you do run into it in your normal app, we should be able to workaround it - this is an issue with one of our LINQ components and if we run into it, we can always replace LINQ usage with a string-based query. That being said, I think we should be able to resolve this with Unity as it is valid c# and likely an IL2CPP bug.

**Comment by Suddelnuppe** [comment]
We are still having issues when building with Visual Studio 2022, even when setting assembly stripping in Unity to the highest level.

Could you in that case please fix it on your end?

**Comment by nirinchev** [comment]
I don't believe it's a bug on our end - this appears to be an issue with the Unity IL2CPP compiler. I would suggest filing a ticket with Unity.

**Comment by nirinchev** [comment]
Oh yeah, so are you able to identify which LINQ query is causing the issue? I know this may be a bit of a tall order, especially for larger projects, but if you could find it, then you could rewrite it using the string query syntax. You can read more about the RQL in our [docs page](https://www.mongodb.com/docs/realm/realm-query-language/), but the tl;dr is you'll need to do something like:

```diff
-realm.All<Person>().Where(p => p.FirstName.StartsWith("P") && p.Age > 10);
+realm.All<Person>().Filter("FirstName STARTSWITH $0 AND Age > $1", "P", 10);
```

**Comment by Suddelnuppe** [comment]
Ok maybe I misunderstood your initial answer: This is not related to some specific linq query, but rather a general incompatibility between realm and our Unity version.

In general is there any short-term way to work around this issue other than contacting Unity?

**Comment by nirinchev** [comment]
To clarify, the initial bug report you posted was related to `PartialEvaluatingExpressionVisitor_EvaluateIndependentSubtrees`. This is a type used by Realm when evaluating LINQ queries against the database. If you don't exercise this code path, Unity should be able to strip it and avoid triggering the IL2CPP bug, which can be done by replacing your LINQ queries with RQL queries. Note that this only applies to Realm queries and you can continue using LINQ for in-memory collection queries.

Alternatively, you could try upgrading your Unity version and hope that they've fixed it at some point.

Finally, considering this is valid C# code and compilation for Android and iOS works fine, all signs point to the IL2CPP compiler for UWP. It's likely that the Unity team will be able to quickly reproduce the issue, but I'm not sure if they'll be willing to backport it to the 2021 line of releases.

**Comment by Suddelnuppe** [comment]
As a small update: After updating to Unity 2022LTS, this issue is gone and the app runs again.

Thanks for the quick help!
