### ISSUE TITLE
Issue an error when using the source generators with older versions of C#

### ISSUE THREAD

**Issue by papafe** [realm/realm-dotnet#3265]
Nullability annotations have been introduced in C# 8.0, so they won't be supported in earlier versions. 
We need to issue an error when developers use older versions of C#, otherwise they will have compilation errors when using the source generator

**Comment by carbonete** [comment]
Hi @papafe i have this problem in my Xamarin Forms app. This use .NetStandard 2.0 with C#7 , change to C# is not dificult but only need change .csproj  to insert <LangVersion>8.0</LangVersion>. But after this i receive errors
Error	CS8400	Feature 'not pattern' is not available in C# 8.0. Please use language version 9.0 or greater.

I think deprecation of old and adopt only Interfaces can only be occurs more to end 2024. 
The official support for Xamarin.Forms will end on May 1, 2024

**Comment by nirinchev** [comment]
Looks like we only use `is not` once in the generated class - we should easily be able to avoid this.
