### ISSUE TITLE
The method 'SequenceEqual' is not supported

### ISSUE THREAD

**Issue by A9G-Data-Droid** [realm/realm-dotnet#3279]
### Problem

When working with an `IQueryable` dataset I get a `Realms.RealmResults<MyType>` object. I have two different objects that request data in different ways and I want to see if they contain the same dataset.

My first attempt would be:
```
MyRealmObject.OneToMany.SequenceEqual(MyOtherRealmObject.OneToMany);
```

The Realm throws an error
> System.NotSupportedException
  HResult=0x80131515
  Message=The method 'SequenceEqual' is not supported
  Source=Realm

### Solution

If I manually enumerate the `IQueryable` to a list then it works:

```
MyRealmObject.OneToMany.ToList().SequenceEqual(MyOtherRealmObject.OneToMany.ToList());
```

So it seems that for Realm to support `SequenceEqual` we need to expose the underlying set of objects so they can be compared to each other. 

Queryable objects do normally have this interface:
https://learn.microsoft.com/en-us/dotnet/api/system.linq.queryable.sequenceequal?view=net-6.0

### Alternatives

I am currently using the aforementioned `.ToList()` workaround. 

### How important is this improvement for you?

I would like to have it but have a workaround

### Feature would mainly be used with

Local Database only

**Comment by nirinchev** [comment]
The reason why we're throwing an exception is to indicate that this API will not be evaluated at the database layer. Unfortunately, the queryable API supported by Realm do not cover the complete set of API defined on `Queryable`. As you have found out, when you encounter an unsupported API, the only thing you can do is to convert the query into a list/array and then use LINQ-to-objects. The drawback is that this is significantly less efficient than the API that execute directly in the database, but for small datasets it's typically acceptable.

For more details on the supported/unsupported feature by our LINQ engine, you can refer to the [docs](https://www.mongodb.com/docs/realm-sdks/dotnet/latest/linqsupport.html).
