### ISSUE TITLE
Realm namespace

### ISSUE THREAD

**Issue by sandr01d** [realm/realm-dotnet#3351]
### What happened?

Since upgrading to version 11.1.0 I get the following compiler error:

```
error CS0118: 'Realm' is a namespace but is used like a type
```
When trying to use the Realm type like this:

```cs
using Realms;

public class Example
{
    private Realm realm;
}
```

Fully qualifying the type does resolve the error:

```cs
public class Example
{
    private Realms.Realm realm;
}
```

 I think this might have something to do with the addition of the Realm namespace in  #3323 

### Repro steps

1. Create a new Unity project and add the realm package
2. Create the following class:

```cs
using Realms;

public class Example
{
    private Realm realm;
}
```

### Version

11.1.0

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Unity

### Client OS and version

Windows 11

### Code snippets

```cs
using Realms;

public class Example
{
    private Realm realm;
}
```

### Relevant log output

```shell
Assets\Example.cs(5,13): error CS0118: 'Realm' is a namespace but is used like a type
```

**Comment by nirinchev** [comment]
You're right - we must have overlooked that - https://github.com/realm/realm-dotnet/blob/eca251b5ea25669951c96603972ea1d8986a98bf/Realm/Realm.UnityUtils/DeviceInfo.cs#L22 this should have been `Realms.UnityUtils`.

**Comment by nirinchev** [comment]
I can't reproduce this in Maui. Is this happening for you in a new project or an existing one? If you can upload a repro case here, that would be super helpful.

**Comment by nirinchev** [comment]
I was able to track that down - looks like the xamarin tooling is generating a namespace that is the same as the assembly name (in our case Realm.PlatformHelpers). I'll try and see how we can disable or at least configure this.
