### ISSUE TITLE
InvalidOperationException: No properties in class, has linker stripped it?

### ISSUE THREAD

**Issue by 89trillion-zhixin** [realm/realm-dotnet#3363]
### What happened?

I'm having problems using Realm, Realm cannot create LocalResData, LocalResData is in the assembly, and Realm Init is in other assembly.

Unity: 2020.3.38f1
Relam: 11.1.2
Build：IL2CPP, Android

I don't know how to solve this problem, can anyone help me?

### Repro steps

After I build Android apk, this issue will definitely happen

### Version

4.x

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Unity

### Client OS and version

Unity 2020.3.38f1

### Code snippets

This is LocalResData
```
using Realms;

namespace Functions.Core.Realms.RealmModel
{
    [Preserve(AllMembers = true)]
    public class LocalResData : RealmObject
    {
        [PrimaryKey, Preserve(AllMembers = true)] public int JoinId { get; set; }
        [Preserve(AllMembers = true)] public long Num { get; set; }

        public static void Init()
        {
        }
    }
}
```

This is init
```
public static void New(string userId)
{
    RealmConfiguration config = new RealmConfiguration($"{Application.persistentDataPath}/{userId}_JPG");
    config.Schema = new Type[]
    {
        typeof(LocalResData),
        typeof(TopicData)
    };
    config.EncryptionKey = Convert.FromBase64String(Url);
    config.SchemaVersion = 0;
    Realm = Realm.GetInstance(config);
}
```

I already have link.xml
```
<linker>
    <assembly fullname="Functions.Core" preserve="all"/>
</linker>
```

### Stacktrace of the exception/crash you're getting

```shell
This is the error log

2023-06-27 00:20:41.927 22720-22873/? E/Unity: System.InvalidOperationException: No properties in LocalResData, has linker stripped it? See https://docs.mongodb.com/realm/sdk/dotnet/troubleshooting/#resolve-a--no-properties-in-class--exception
      at Realms.Schema.ObjectSchema+Builder..ctor (System.Type type) [0x00000] in <00000000000000000000000000000000>:0 
      at Realms.Schema.ObjectSchema+<>c.<FromType>b__23_0 (System.Type t) [0x00000] in <00000000000000000000000000000000>:0 
      at System.Func`2[T,TResult].Invoke (T arg) [0x00000] in <00000000000000000000000000000000>:0 
      at System.Collections.Concurrent.ConcurrentDictionary`2[TKey,TValue].GetOrAdd (TKey key, System.Func`2[T,TResult] valueFactory) [0x00000] in <00000000000000000000000000000000>:0 
      at Realms.Schema.RealmSchema+Builder.Add (System.Type type) [0x00000] in <00000000000000000000000000000000>:0 
      at Realms.Schema.RealmSchema+Builder..ctor (System.Collections.Generic.IEnumerable`1[T] types) [0x00000] in <00000000000000000000000000000000>:0 
      at Realms.Schema.RealmSchema.op_Implicit (System.
```
```


### Relevant log output

_No response_

**Comment by nirinchev** [comment]
Hey, do you have a minimal repro project you could share with us? That'll help quite a lot to pinpoint where the issue stems from.

**Comment by nirinchev** [comment]
This looks similar to https://github.com/realm/realm-dotnet/issues/3364. Can you try if the [package linked in the last comment](https://drive.google.com/file/d/1n48kf9gz7aVF4hHNjfMuRWEQlvc-X2Tl/view?usp=share_link) alleviates the issues for you?

**Comment by avolkangursel** [comment]
> This looks similar to #3364. Can you try if the [package linked in the last comment](https://drive.google.com/file/d/1n48kf9gz7aVF4hHNjfMuRWEQlvc-X2Tl/view?usp=share_link) alleviates the issues for you?

Hello, I tried the package. The "Could not analyze the user's assembly." error seems to be resolved, but unfortunately, we still receive the "InvalidOperationException: No properties in class, has linker stripped it?" error when building with "batch mode" on the CI/CD machine.

**Comment by nirinchev** [comment]
Can you share the logs when building on CI?

**Comment by avolkangursel** [comment]
Unfortunately, for privacy reasons, I cannot share the entire log of the project. Instead, I will try to reproduce the issue with a test project. If I can reproduce it, I can directly share the project.

Additionally, I can examine the log file on the CI machine and share the information I found. For example, when the API Updater runs, I see the following messages related to Realm:

> [API Updater] Assemblies not requiring updates:
…
[API Updater] Packages/{package name}/Runtime/ThirdParty/Realm/Editor/Realm.UnityWeaver.dll (stdout below):
[AssemblyUpdater] Removing 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' from 'Realm.UnityWeaver' list of referenced assemblies (no type referencing this assembly was found).
[API Updater] Packages/{package name}/Runtime/ThirdParty/Realm/Runtime/Realm.UnityUtils.dll (stdout below):
…

By the way, we are using the Realm SDK by including it in a custom package that we have created internally. Therefore, the file paths for the Realm DLLs are located within the Packages folder.

After the Tundra build, the error message below appeared precisely 94 times. It starts with the message 
`*** Tundra build success (18.56 seconds), 961 items updated, 1062 evaluated.`

Then, in succession, the following error message occurs 94 times.

> NullReferenceException: Object reference not set to an instance of an object
  at RealmWeaver.UnityWeaver.GetAnalyticsConfig (System.Nullable`1[T] target) [0x0009b] in <a5e405b1e32b4d13b28711640d3a5919>:0 
  at RealmWeaver.UnityWeaver+<>c.<Initialize>b__18_1 (System.String assemblyPath, UnityEditor.Compilation.CompilerMessage[] _) [0x0003e] in <a5e405b1e32b4d13b28711640d3a5919>:0 
  at UnityEditor.Compilation.CompilationPipeline+<>c.<SubscribeToEvents>b__23_2 (UnityEditor.Scripting.ScriptCompilation.ScriptAssembly scriptAssembly, UnityEditor.Compilation.CompilerMessage[] messages) [0x0002a] in /Users/bokken/build/output/unity/unity/Editor/Mono/Scripting/ScriptCompilation/CompilationPipeline.cs:282 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
UnityEditor.Compilation.<>c:<SubscribeToEvents>b__23_2(ScriptAssembly, CompilerMessage[]) (at /Users/bokken/build/output/unity/unity/Editor/Mono/Scripting/ScriptCompilation/CompilationPipeline.cs:286)
UnityEditor.Scripting.ScriptCompilation.EditorCompilation:InvokeAssemblyCompilationFinished(ScriptAssembly[], BeeDriverResult, CompilerMessage[][]) (at /Users/bokken/build/output/unity/unity/Editor/Mono/Scripting/ScriptCompilation/EditorCompilation.cs:1123)
UnityEditor.Scripting.ScriptCompilation.EditorCompilation:ProcessCompilationResult(ScriptAssembly[], BeeDriverResult, Object) (at /Users/bokken/build/output/unity/unity/Editor/Mono/Scripting/ScriptCompilation/EditorCompilation.cs:1088)
UnityEditor.Scripting.ScriptCompilation.EditorCompilation:TickCompilationPipeline(EditorScriptCompilationOptions, BuildTargetGroup, BuildTarget, Int32, String[]) (at /Users/bokken/build/output/unity/unity/Editor/Mono/Scripting/ScriptCompilation/EditorCompilation.cs:1052)
UnityEditor.Scripting.ScriptCompilation.EditorCompilationInterface:TickCompilationPipeline(EditorScriptCompilationOptions, BuildTargetGroup, BuildTarget, Int32, String[]) (at /Users/bokken/build/output/unity/unity/Editor/Mono/Scripting/ScriptCompilation/EditorCompilationInterface.cs:211)
UnityEditor.BuildPipeline:BuildPlayerInternalNoCheck(String[], String, String, BuildTargetGroup, BuildTarget, Int32, BuildOptions, String[], Boolean)
UnityEditor.BuildPipeline:BuildPlayerInternal(String[], String, String, BuildTargetGroup, BuildTarget, Int32, BuildOptions, String[]) (at /Users/bokken/build/output/unity/unity/Editor/Mono/BuildPipeline.bindings.cs:455)
UnityEditor.BuildPipeline:BuildPlayer(String[], String, String, BuildTargetGroup, BuildTarget, Int32, BuildOptions, String[]) (at /Users/bokken/build/output/unity/unity/Editor/Mono/BuildPipeline.bindings.cs:348)
UnityEditor.BuildPipeline:BuildPlayer(BuildPlayerOptions) (at /Users/bokken/build/output/unity/unity/Editor/Mono/BuildPipeline.bindings.cs:322)
Magiclab.MarketingSDK.Core.Editor.Build.BuilderCli:iOSBuild(String[], String, BuildTarget, BuildOptions) (at Library/PackageCache/com.magiclab.marketingsdk.core@d8d96022dc/Editor/Core/Build/BuilderCli.cs:118)
Magiclab.MarketingSDK.Core.Editor.Build.BuilderCli:BuildIOS() (at Library/PackageCache/com.magiclab.marketingsdk.core@d8d96022dc/Editor/Core/Build/BuilderCli.cs:34)

Apart from those, no other sentences are starting with "Weaving completed" or any other messages related to Realm.

**Comment by nirinchev** [comment]
Thanks, that's quite helpful. I think I know what's going on - I've created a PR with a proposed fix and will give you a package to try as soon as CI builds it.

**Comment by avolkangursel** [comment]
Thank you very much. I can try it when the package arrives.

**Comment by nirinchev** [comment]
Can you try [this package](https://drive.google.com/file/d/19HWA-AcFFQnJF8feZdsqsX2WrOdW25_l/view?usp=share_link) and see if that still causes the error on CI?

**Comment by avolkangursel** [comment]
I apologize for the delayed response. I tried the package, and it seems that the issues have been resolved. Thank you very much.

**Comment by nirinchev** [comment]
Thanks for confirming! We'll schedule an official release with the bugfix shortly.
