### ISSUE TITLE
Multiple Apps in same Process wrongfully Activate each others' Users

### ISSUE THREAD

**Issue by moritz-mg** [realm/realm-dotnet#3382]
### What happened?

For our editor and server development workflow, we try to have two realm apps in the same process.

However, isolation between multiple distinct instances of `Realms.Sync.App` seems to break down if their Realm-ID is the same.

Expected: The app instances are not identical (comparing with the == operator), this is the case. ✅

Unexpected: When one App instance's `LoginAsync` call succeed, the other(s) instantly considers itself logged in with that user as the active user.💥 

Same seems true for `LogOutAsync`. Added complexities emerge with different `MetaDataPersistenceMode` constellations and from #3383, but the core issue is lack of isolation.

For debugging, profiling and tracing, it would be extremely useful to have two Apps connecting to the same Atlas App Service coexist in the same process. (and also automated gameplay tests with 2 logged in players coexisting in one process)

### Repro steps

1. `App.Create(AppConfig)` two realm apps with the same Realm-ID, but different base paths.
2. Log one of them in.
3. Observe: the other app instance consider that User the active user (App.currentUser), as well; and now acts with the other App's user's credentials.

The order of App creation does not matter, if the Client one is created and waits for the user to input their credentials, then as soon as the Server one logs in, the Client one is "logged in" as the Server's API user. (in the other case the Client will already find itself "logged in" and not show the login dialog at all, only to fail when it tries to trigger something which requires a specific user profile document which naturally doesn't exist for the API user of the server)

### Version

11.2.0

### What Atlas Services are you using?

Both Atlas Device Sync and Atlas App Services

### What type of application is this?

Unity

### Client OS and version

Unity 2022.3.5f1 on Windows 11 x64

### Code snippets

I create two apps, "client" and "server" like this:
```cs
public static App CreateApp(string role)
        {
             // ...
            try
            {
                var path = Path.Combine(Application.persistentDataPath, role);
                Debug.Log($"Creating App for role '{role}' at '{path}'.");
                Directory.CreateDirectory(path);
                var config = new AppConfiguration(RealmID)
                {
                    BaseFilePath = path,
                    LocalAppName = role, //tried this to no avail
                };
                return App.Create(config);
            }
            //...
``` 

and using it kind of like:
```cs
a = Environment.CreateApp("alpha");
b = Environment.CreateApp("beta");
```

Any number of apps share the same user login, even though the directory structure is as expected, split into base paths for each of these apps (named "client", "server", "alpha", "beta"). Newly added ones even "inherit" whoever it was that was last logged in in any of the older ones.

However, as soon as one of the apps (e.g. the role="server" one) logs in (in this case, via Api key), the role="client" one thinks it's logged in (has a currentUser != null, which is logged in, and which is actually the ApiKey user from *the other App*).

**Comment by moritz-mg** [comment]
Small addendum: It works as expected with separate app-ids (apart from the path problem in issue 3383), but of course there are no compatible users between two distinct apps.

**Comment by moritz-mg** [comment]
If `MetadataPersistenceMode.Disabled` is used for one of the apps, it will still "Log in" its own active user for the other apps, but this is not persisted - if the App is not Created during a subsequent run, the other Apps don't find themselves with the API credentials of the first app.

(still they are confused/compromised throughout the first run)

**Comment by nirinchev** [comment]
This is working as intended, though I can understand if that design is not ideal for your use case. Essentially, we keep a cache of all apps keyed by their id and when you call `App.Create` we get or add an element from the cache. I'll try and see if we can provide an option to disable the caching and see what breaks.

**Comment by moritz-mg** [comment]
Perhaps you can augment these keys by appending the local app name (if provided)?

If I'm getting something cached, it's strange because I seem to get a brand new instance of `Reamlms.Sync.App`. This led me to believe something is amiss.

```
a = CreateApp(same_id, "a");
b = CreateApp(same_id, "b");

Assert.Equal(a, b); //💥, but actually behaviour here is exactly as expected
```

**Comment by nirinchev** [comment]
The managed app instances are different, but the native ones are the same, which is why it's not exactly obvious that caching is involved.

**Comment by moritz-mg** [comment]
One more thought:
If their native sides are cached, what happens if (pseudocode):

```
AppConfig encrypted = new AppConfig{MetadataPersistenceMode = Encrypted};
AppConfig unencrypted = new AppConfig{MetadataPersistenceMode = Unecrypted};
AppConfig none = new AppConfig{MetadataPersistenceMode = Disabled};

a = CreateApp(unencrypted); //pseudocode assuming we get the "native" handle here
b = CreateApp(encrypted);
c = CreateApp(nonpersistent);

Assert.NotEqual(a, b); //I'd very much expect that, currently only passes becuas of the managed instance
Assert.NotEqual(b, c);
Assert.NotEqual(a, c);

Assert.IsActuallyEncrypted(b);
Assert.IsActallyNotPersisting(c);
```

**Comment by moritz-mg** [comment]
Slightly scary if someone upgrades their App to use encryption in the future.
Clients with existing realms might quietly stay unencrypted.

**Comment by nirinchev** [comment]
Some clarification about this:
1. `MetadataPersistenceMode` controls the behavior of the metadata persistence Realm, not the user-created Realms. This Realm stores information about users and their access/refresh tokens (e.g. this is why `App.CurrentUser` persists across app restarts). It doesn't affect the encryption of Realms created using `Realm.GetInstance(Async)` as the encryption there is controlled by the Realm config.
2. The app cache is in-memory, which means that changing the parameters of the app config with an app upgrade will not use cached versions of the app - e.g. if in v1 of your app you set `AppConfiguration { BaseFilePath = "/foo/bar" }` and in v2 you set it as `AppConfiguration { BaseFilePath = Application.persistentDataPath }`, users who upgrade to v2 will use the new path, regardless of what the value was for v1 of the app. The cache is only relevant if in your codebase you have multiple places where `App.Create` is invoked.
3. If you change the encryption of the metadata Realm across app versions (or for any other reason really), opening the existing metadata Realm will fail as it'll use different encryption than before.

**Comment by nirinchev** [comment]
I've put up a PR that alleviates some of the issues reported here - notably, it adds a `UseAppCache` property on `AppConfiguration` - you can use that to create multiple apps with the same id but different configurations. Note that there is still room for error there - e.g. if you create two apps that use the same base file path but different encryption keys, the second one will fail to open the metadata Realm. 

Additionally, I've changed the implementation of `App.GetHashCode` and `App.Equals` to correctly account for the native cache, so that

```csharp
var app1 = App.Create(config);
var app2 = App.Create(config);
app1.Equals(app2); // true
```

Finally, I filed https://github.com/realm/realm-core/issues/6810 to track adding validations when using the app cache to avoid silently ignoring different properties - once that is complete, you'll get an exception if you try to create a cached app with a different config.

**Comment by moritz-mg** [comment]
Impressive turnaround, thank you so much! Can't wait to test this soon. :)
