### ISSUE TITLE
Migration support

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#34]
Support full migration with a callback. Note this requires callback from C++ ObjectStore to C# to provide full application programmer control. May want some pruning by object class and by property so callback only occurs as little as possible.

See further discussion in the [Schema and Migration](https://github.com/realm/realm-wiki/wiki/Schema-and-Migration) wiki page.

**Comment by kristiandupont** [comment]
Moved to realm/realm-dotnet#545
