### ISSUE TITLE
AOT analysis warning when using backlinks on iOS

### ISSUE THREAD

**Issue by charlesroddie** [realm/realm-dotnet#3418]
### What happened?

When trying to [build an iOS project with NativeAOT](https://devblogs.microsoft.com/dotnet/announcing-dotnet-8-preview-6/#support-for-targeting-ios-platforms-with-nativeaot) with Realm using backlinks we get AOT analysis warnings.

Previously there were many more warnings but updating to use the source generator cleared up most of them.

### Repro steps

Use a [backlink](https://www.mongodb.com/docs/realm/sdk/dotnet/model-data/relationships/) in a realm object

Compile for iOS with NativeAOT

### Version

11.2.0

### What Atlas Services are you using?

-- select --

### What type of application is this?

Xamarin

### Client OS and version

iOS

### Code snippets

```csharp
[Backlink(nameof(R_GPanel.Tags))]
public IQueryable<R_GPanel> GPanels { get; } = null!;
```

### Relevant log output

```shell
ILC : AOT analysis warning IL3050: ContentRealmTypes.R_Word.GPanels.get: Using member 'System.Linq.Queryable.AsQueryable<R_GPanel>(IEnumerable`1<R_GPanel>)' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. Enumerating in-memory collections as IQueryable can require creating new generic types or methods, which requires creating code at runtime. This may not work when AOT compiling. [/Users/runner/work/1/s/Platforms/iOS/50iOS.csproj]
```

**Comment by nirinchev** [comment]
Are you certain that the class that contains `GPanels` is a source-generated class? Asking because those should not be using `AsQueryable` for backlinks getters.

**Comment by charlesroddie** [comment]
Ah sorry some confusion here about what is in what branch - we'll check again.

**Comment by charlesroddie** [comment]
Yes you are right. Sorry for our confusion here. Closing as invalid.
