### ISSUE TITLE
Crash from realm core

### ISSUE THREAD

**Issue by avolkangursel** [realm/realm-dotnet#3430]
### What happened?

Hello, we are using the realm-dotnet v11.3.0 SDK in our game. Occasionally, we receive a crash report from our live game like the one below:

> Crashed: Thread
0  libsystem_kernel.dylib         0x7578 __pthread_kill + 8
1  libsystem_pthread.dylib        0x7118 pthread_kill + 268
2  libsystem_c.dylib              0x1d178 abort + 180
3  realm-wrappers                 0x3dd1ac please_report_this_issue_in_github_realm_realm_core_v_13_17_0 + 10
4  realm-wrappers                 0x3dd4e0 realm::util::terminate_internal(std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char>>&) + 244
5  realm-wrappers                 0x3dd350 realm::util::terminate_with_info(char const*, char const*, long, char const*, std::initializer_list<realm::util::Printable>&&) + 400
6  realm-wrappers                 0x3dd1c0 realm::util::terminate(char const*, char const*, long, std::initializer_list<realm::util::Printable>&&) + 18
7  realm-wrappers                 0x2340e0 realm::sync::ClientImpl::Session::begin_resumption_delay(realm::sync::ProtocolErrorInfo const&) + 384
8  realm-wrappers                 0x233ea4 realm::sync::ClientImpl::Session::suspend(realm::sync::SessionErrorInfo const&) + 276
9  realm-wrappers                 0x22ef2c realm::sync::ClientImpl::Session::receive_error_message(realm::sync::ProtocolErrorInfo const&) + 440
10 realm-wrappers                 0x22ebf0 realm::sync::ClientImpl::Connection::receive_error_message(realm::sync::ProtocolErrorInfo const&, unsigned long long) + 80
11 realm-wrappers                 0x22d204 void realm::_impl::ClientProtocol::parse_message_received<realm::sync::ClientImpl::Connection>(realm::sync::ClientImpl::Connection&, std::__1::basic_string_view<char, std::__1::char_traits<char>>) + 3612
12 realm-wrappers                 0x236350 realm::sync::ClientImpl::Connection::WebSocketObserverShim::websocket_binary_message_received(realm::util::Span<char const, 18446744073709551615ul>) + 148
13 realm-wrappers                 0x21ab64 (anonymous namespace)::WebSocket::frame_reader_loop() + 136
14 realm-wrappers                 0x20dba0 realm::sync::network::Service::BasicStreamOps<realm::sync::network::ssl::Stream>::BufferedReadOper<realm::util::UniqueFunction<void (std::__1::error_code, unsigned long)>>::recycle_and_execute() + 220
15 realm-wrappers                 0x2144d4 realm::sync::network::Service::Impl::run_impl(bool) + 388
16 realm-wrappers                 0x2059f8 realm::sync::websocket::DefaultSocketProvider::event_loop() + 220
17 realm-wrappers                 0x2076c4 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (realm::sync::websocket::DefaultSocketProvider::*)(), realm::sync::websocket::DefaultSocketProvider*>>(void*) + 64
18 libsystem_pthread.dylib        0x16b8 _pthread_start + 148
19 libsystem_pthread.dylib        0xb88 thread_start + 8

We are obtaining this crash report through Firebase Crashlytics.

Unity version: 2021.3.26f1

### Repro steps

Unfortunately, we are unable to capture it in our tests. This error report doesn't occur very often, but it's affecting the smooth operation of our game.

### Version

11.3.0

### What Atlas Services are you using?

Both Atlas Device Sync and Atlas App Services

### What type of application is this?

Unity

### Client OS and version

iOS16.6.0

**Comment by nirinchev** [comment]
@danieltabacaru or @michael-wb can you guys take a look? Looks like a sync client assertion in `begin_resumption_delay`.

**Comment by danieltabacaru** [comment]
There is only one assertion `REALM_ASSERT(!m_try_again_activation_timer);` and that could be triggered if the server sends at least two errors in a row. Is there a log file?

**Comment by nirinchev** [comment]
@avolkangursel I don't believe you have client file logs you can share, do you? If you don't, then we'll need your app id and a rough timeframe for when the crash happened so we can try and correlate the crash with the server logs.

**Comment by avolkangursel** [comment]
When the game starts, we send the user ID of each user to our analytics tools. Unfortunately, we do not see any logs associated with this user concerning the reported error (maybe the error occurred earlier). I've also been unsuccessful in deducing the event timestamp, even though the reported time of the event is available. Here are the details regarding the error report:

App ID: lm-application-pqiww
Report time: Aug 30, 2023, 8:12:30 PM
Device Model: iPhone SE (2nd generation)
OS: iOS 16.6.0

The event timestamp doesn't always match the report's arrival time exactly, and I'm not sure of the time zone of the report's time. I am located in Türkiye, and Türkiye operates in the UTC+03:00 time zone.

**Comment by avolkangursel** [comment]
I apologize for the delayed response; it was a very busy day.
Unfortunately, we don't know who encountered the error. It came from one of our live games. It could be the user you mentioned.

We are closely monitoring the situation to provide more information, but the same error hasn't reoccurred yet. If the same error happens again, I can provide a specific user ID. 

We had released an update to our game one day before this error occurred, but we didn't make any changes to the Realm SDK. I am not sure this information could help you but I wanted to mention it.

**Comment by avolkangursel** [comment]
We were able to access the details of the report. The time when the report was generated appears to be exactly 2023-08-30 17:12:30.000000 UTC. For further details, I am sharing the report.

[realm_crash_report.csv](https://github.com/realm/realm-dotnet/files/12503663/realm_crash_report.csv)

**Comment by jbreams** [comment]
I think this should be fixed by https://github.com/realm/realm-core/pull/7207.
