### ISSUE TITLE
Investigate failing CI test

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-dotnet#3510]
We have a failing test on iOS that we should fix: `Realms.Tests.Database.LifetimeTests.TransactionShouldHoldStrongReferenceToRealm` fails occasionally on iOS.

**Comment by papafe** [comment]
Didn't manage to reproduce locally on .NET 8.0, so given the push by the MAUI team to fix performance issues (including memory leaks), it could be that it's a bug in MAUI itself. So the plan of action is to update the .NET versions on our tests
