### ISSUE TITLE
Fix failing XUnit tests on CI

### ISSUE THREAD

**Issue by papafe** [realm/realm-dotnet#3538]
Example run: https://github.com/realm/realm-dotnet/actions/runs/8190417386/job/22397978196

**Comment by papafe** [comment]
It seems to be happening every now and then on CI, but I can't manage to reproduce it locally

**Comment by nirinchev** [comment]
Can you add a link to a failing build for reference purposes?

**Comment by papafe** [comment]
@nirinchev, sure. Just added it in the bug description
