### ISSUE TITLE
Privacy Manifest support would be needed in realm-wrappers

### ISSUE THREAD

**Issue by takeshik** [realm/realm-dotnet#3541]
### Problem

[Like realm-swift did](https://github.com/realm/realm-swift/issues/8428), it seems that realm-dotnet also need to address Apple's new [Privacy Manifest](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files) reguration.

Apple has [announced](https://developer.apple.com/news/?id=3d8a9yyh) that new publication and updates must support Privacy Manifests starting May 1.

### Solution

To compliant the new regulation, it would be needed to include a privacy manifest file into `realm-wrappers.framework`.

As an experiment, I wrote [some patch](https://github.com/takeshik/realm-dotnet/commit/cf0d9c4ab6b8731160dedae538982403853ab376) to include a manifest into `realm-wrappers.framework`.
In this patch, `PrivacyInfo.xcprivacy` is brought from realm/realm-swift#8455. I think that the declaration in the manifest can be appropriated as is, but I'm not certain.

### How important is this improvement for you?

Would be a major improvement

### Feature would mainly be used with

Local Database only

**Comment by nirinchev** [comment]
Thanks for bringing it to our attention. We'll schedule some work to make sure it's done before May 1st.

**Comment by takeshik** [comment]
Thanks a lot for your comment. I'm relieved to hear that.

By the way, I previously wrote that the declaration in the manifest can be appropriated as is. But after that, I found that realm-wrappers seems to use not only fstat and stat, but also [statvfs](https://github.com/realm/realm-core/blob/3ba2a75a72e55369702a483fff82e43572bfa123/src/realm/util/file.cpp#L1985).
[realm-swift's PrivacyInfo.xcprivacy](https://github.com/realm/realm-swift/blob/bc54beb294e634f69c4f7a3a44a6f5ad10e342f1/Realm/PrivacyInfo.xcprivacy) only declares `NSPrivacyAccessedAPICategoryFileTimestamp` (for fstat and stat).
In realm-wrappers, it might be also needed to declare `NSPrivacyAccessedAPICategoryDiskSpace` in the manifest.

<details>
<summary>FYI: PrivacyInfo.xcprivacy</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>NSPrivacyAccessedAPITypes</key>
	<array>
		<dict>
			<key>NSPrivacyAccessedAPIType</key>
			<string>NSPrivacyAccessedAPICategoryFileTimestamp</string>
			<key>NSPrivacyAccessedAPITypeReasons</key>
			<array>
				<string>C617.1</string>
			</array>
		</dict>
		<dict>
			<key>NSPrivacyAccessedAPIType</key>
			<string>NSPrivacyAccessedAPICategoryDiskSpace</string>
			<key>NSPrivacyAccessedAPITypeReasons</key>
			<array>
				<string>E174.1</string>
			</array>
		</dict>
	</array>
	<key>NSPrivacyTracking</key>
	<false/>
  <key>NSPrivacyTrackingDomains</key>
  <array>
  </array>
  <key>NSPrivacyCollectedDataTypes</key>
  <array>
  </array>
</dict>
</plist>
```

</details>

**Comment by papafe** [comment]
Little bit of confusing info but here are two links from Microsoft about this:
- https://learn.microsoft.com/en-us/dotnet/maui/ios/privacy-manifest?view=net-maui-8.0#create-a-privacy-manifest
- https://devblogs.microsoft.com/dotnet/apple-privacy-manifest-support/

**Comment by nirinchev** [comment]
Note that it appears we don't have to add this by May 1st as the Realm .NET SDK is not included in that list: https://developer.apple.com/support/third-party-SDK-requirements/.

**Comment by papafe** [comment]
Yes, fortunately we're not there. It's mostly a nice thing so developers don't have to do it themselves

**Comment by papafe** [comment]
Looking at the [documentation](https://learn.microsoft.com/en-us/dotnet/maui/ios/privacy-manifest?view=net-maui-8.0), it seems that the minimum privacy manifest necessary for iOS application already contains the keys that we wanted to include in out privacy manifest. For this reason we believe we should not do anything on our side, so I'm closing this ticket but feel free to reopen it if you experience any issue. 

On a side note, @takeshik thanks a lot for reporting this and also spending the time to investigate how to fix it. I verified that your patch puts the privacy framework in the right place for iOS before noticing we probably don't need it. So thanks a lot on our side 😄

**Comment by roycho111** [comment]
Hello @papafe 

i'm wondering if Realm dotnet uses these [C# .Net framework APIs](https://docs.unity3d.com/6000.0/Documentation/Manual/apple-privacy-manifest-policy.html#CSharpDotNetAPIs)

if so, it would be needed to include a privacy manifest file into realm-wrappers.framework as @takeshik mentioned

i might be wrong, it's quite confusing :(

**Comment by papafe** [comment]
It seems that our usage is already covered by the default privacy manifest that MAUI needs, so we should be fine. I've also tried to send a test app to Apple for review and did not get any warning/errors about the privacy manifest, so hopefully we are already covered. 

That said, feel free to reopen this if you get any errors about Realm when submitting to Apple.
