### ISSUE TITLE
Crash: Realm.SyncSession is only valid for synchronized Realms

### ISSUE THREAD

**Issue by softlion** [realm/realm-dotnet#3562]
### What happened?

realm 11.7.0

Real crashed while reading a table.

```c#
Db = Realm.GetInstance();
var x = Db.All<DbWallet>().ToList()
```

Exception:
```c#
System.NotSupportedException: Realm.SyncSession is only valid for synchronized Realms (i.e. ones that are opened with FlexibleSyncConfiguration or PartitionSyncConfiguration). The unsupported member type is located on type 'Realms.Sync.Session'. Path: $.Realm.SyncSession.
 ---> System.NotSupportedException: Realm.SyncSession is only valid for synchronized Realms (i.e. ones that are opened with FlexibleSyncConfiguration or PartitionSyncConfiguration).
   at Realms.Realm.get_SyncSession() in D:\a\realm-dotnet\realm-dotnet\Realm\Realm\Realm.cs:line 247
```

### Repro steps

```c#
var wallet = Db.Find<DbWallet>(walletId);

await Db.WriteAsync(() =>  {   wallet.Alias = "some new value";   });

var allWallets = Db.All<DbWallet>().ToList();
```

### Version

8.0

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Other

### Client OS and version

Maui. Android emulator API 33 (pixel 5) on windows 11.

### Code snippets

```c#
public partial class DbWallet : IRealmObject
{
    [PrimaryKey]
    public string WalletId { get; set; }
    public string? Alias { get; set; }
}
```

### Stacktrace of the exception/crash you're getting

```c#
System.NotSupportedException: Realm.SyncSession is only valid for synchronized Realms (i.e. ones that are opened with FlexibleSyncConfiguration or PartitionSyncConfiguration). The unsupported member type is located on type 'Realms.Sync.Session'. Path: $.Realm.SyncSession.
 ---> System.NotSupportedException: Realm.SyncSession is only valid for synchronized Realms (i.e. ones that are opened with FlexibleSyncConfiguration or PartitionSyncConfiguration).
   at Realms.Realm.get_SyncSession() in D:\a\realm-dotnet\realm-dotnet\Realm\Realm\Realm.cs:line 247
```

**Comment by papafe** [comment]
Hi @softlion, thanks for your report. 
The exception that you're seeing should be raised when trying to get a `SyncSession` on a local realm. From the code snippets that you posted it seems you're indeed creating a local realm, but I don't see you accessing `SyncSession` anywhere, so I'm not sure how it could happen. I also took a look at our source code and we access `SyncSession` only with a synchronized realm (when opening the realm with `FlexibleSyncConfiguration` or `PartitionSyncConfiguration`), so it shouldn't be possible. 

Is that the whole stack trace you're getting? From that I can't see where the `SyncSession` is accessed. 
Would it be possible to for you to create a repro case and send it to us? This would be really helpful

**Comment by softlion** [comment]
That triggers the issue.

The key that triggers it is the json serializer.

```
    [Fact]
    public async Task TriggerRealmBug()
    {
        using var db = Realm.GetInstance(new InMemoryConfiguration("unittests"));
        db.Error += (sender, args) => output.WriteLine(args.Exception.ToLongString());

        var walletId = "someId";
        var wallet = new DbWallet { WalletId = walletId };
        await db.WriteAsync(() => { db.Add(wallet); });
        
        wallet = db.Find<DbWallet>(walletId);
        await db.WriteAsync(() =>  { wallet.Alias = "some new value"; });
        
        var dbWallets = db.All<DbWallet>().ToList();
        Assert.Single(dbWallets);

        //Crash here
        var jsonWallets = JsonSerializer.Serialize(db.All<DbWallet>().ToList());
    }
```

**Comment by papafe** [comment]
Ok, this makes sense. It seems that `System.Text.Json` is ignoring the `IgnoreDataMember` attribute we put on the source generated class properties so that they're ignored by the serialization. During the serialization `System.Text.Json` is trying to access `DbWallet.Realm.SyncSession` and so the exception is raised. 

It seems we need to add the `JsonIgnore` attribute to be compatible with `System.Text.Json`. In the meanwhile, you can add special support for `IgnoreDataMember` as explained [here](https://devblogs.microsoft.com/dotnet/system-text-json-in-dotnet-7/):

```csharp
//NOTE: This is copied from the link above
var options = new JsonSerializerOptions
{
    TypeInfoResolver = new DefaultJsonTypeInfoResolver
    {
        Modifiers = { DetectIgnoreDataMemberAttribute }
    }
};

JsonSerializer.Serialize(new MyPoco(), options); // {"Value":3}

static void DetectIgnoreDataMemberAttribute(JsonTypeInfo typeInfo)
{
    if (typeInfo.Kind != JsonTypeInfoKind.Object)
        return;

    foreach (JsonPropertyInfo propertyInfo in typeInfo.Properties)
    {
        if (propertyInfo.AttributeProvider is ICustomAttributeProvider provider &&
            provider.IsDefined(typeof(IgnoreDataMemberAttribute), inherit: true))
        {
            // Disable both serialization and deserialization 
            // by unsetting getter and setter delegates
            propertyInfo.Get = null;
            propertyInfo.Set = null;
        }
    }
}
```

To be honest I am surprised this was working before. You said you updated your nuget packages and this stopped working. What nuget packages did you exactly update?

**Comment by nirinchev** [comment]
Looks like the json serializer is trying to serialize the `Realm` property on `DBWallet`, even though it's annotated with `IgnoreDataMember`. I don't think we can polyfill `JsonIgnoreAttribute`, so we'll probably need to apply it if possible based on the compilation target.

**Comment by softlion** [comment]
> Ok, this makes sense. It seems that `System.Text.Json` is ignoring the `IgnoreDataMember` attribute we put on the source generated class properties so that they're ignored by the serialization. During the serialization `System.Text.Json` is trying to access `DbWallet.Realm.SyncSession` and so the exception is raised.
> 
> It seems we need to add the `JsonIgnore` attribute to be compatible with `System.Text.Json`. In the meanwhile, you can add special support for `IgnoreDataMember` as explained [here](https://devblogs.microsoft.com/dotnet/system-text-json-in-dotnet-7/):
> 
> ```cs
> //NOTE: This is copied from the link above
> var options = new JsonSerializerOptions
> {
>     TypeInfoResolver = new DefaultJsonTypeInfoResolver
>     {
>         Modifiers = { DetectIgnoreDataMemberAttribute }
>     }
> };
> 
> JsonSerializer.Serialize(new MyPoco(), options); // {"Value":3}
> 
> static void DetectIgnoreDataMemberAttribute(JsonTypeInfo typeInfo)
> {
>     if (typeInfo.Kind != JsonTypeInfoKind.Object)
>         return;
> 
>     foreach (JsonPropertyInfo propertyInfo in typeInfo.Properties)
>     {
>         if (propertyInfo.AttributeProvider is ICustomAttributeProvider provider &&
>             provider.IsDefined(typeof(IgnoreDataMemberAttribute), inherit: true))
>         {
>             // Disable both serialization and deserialization 
>             // by unsetting getter and setter delegates
>             propertyInfo.Get = null;
>             propertyInfo.Set = null;
>         }
>     }
> }
> ```
> 
> To be honest I am surprised this was working before. You said you updated your nuget packages and this stopped working. What nuget packages did you exactly update?

maui, realm, json, and some others. 
It may not have worked previously though, it may only not report the crash.

Anyway now we found the issue.

**Comment by papafe** [comment]
This has been solved with https://github.com/realm/realm-dotnet/pull/3451, so I am closing it
