### ISSUE TITLE
Realm.DeleteRealm() creates lock file if Realm doesn't exist

### ISSUE THREAD

**Issue by peachypixels** [realm/realm-dotnet#3563]
### What happened?

Hello!

Not a big issue, but just noticed that calling Realm.DeleteRealm() on a (non-existent) Realm creates its corresponding lock file.

I understand DeleteRealm() doesn't delete lock files (although unsure why) but it seems strange to create a lock file for a Realm that doesn't exist.

Of course it's easy to work around in the app, but thought I'd raise it anyway.

Hope this helps.

### Repro steps

1. "Test.realm" file does not exist
2. "Test.realm.lock" file does not exist
3. Realm.DeleteRealm(config);
4. "Test.realm.lock" file exists

NOTE: Config points to "Test.realm"

### Version

11.7.0

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Unity

### Client OS and version

WIndows 10 (22H2)

**Comment by nirinchev** [comment]
This is expected - in order to delete the Realm file, we need to acquire multiprocess lock. Unfortunately, acquiring the lock implicitly creates the file. If you want to avoid this, you could check if the file exists before deleting it:

```csharp
if (File.Exists(config.DatabasePath))
{
    Realm.DeleteRealm(config);
}
```
