### ISSUE TITLE
Change passing of tests on CI

### ISSUE THREAD

**Issue by papafe** [realm/realm-dotnet#3565]
As it is know, the steps of the workflow related to testing are failing only if there's an actual crash/error in the steps, but will succeed even if there are failing tests. The failing tests are then reported inside the checks that are created by the `Code coverage` workflow.
This causes some issues:
- Due to an [an issue with GitHub](https://github.com/orgs/community/discussions/24616), the test results get attached to a random action, and it is cumbersome to find  the original action responsible for it, especially for newcomers.
- It is difficult to see the previous checks results.
- In case of flaky test, it's not possible to just press "re-run failed jobs" to run only the failing test suites

For these reasons it would be probably beneficial to change how our CI works, so that the test steps are failing also due to failing tests. This would make our repo be aligned with the other SDKs

**Comment by papafe** [comment]
@rorbech Did I forget anything?

**Comment by rorbech** [comment]
> @rorbech Did I forget anything?

I think it catches the annoyances that I have stumbled upon 🎉
