### ISSUE TITLE
Compacting a Realm results in an upgrade prompt in Realm Studio

### ISSUE THREAD

**Issue by peachypixels** [realm/realm-dotnet#3583]
### What happened?

Hello!

I was running some test code yesterday and noticed something unusual. It may well be an issue with Realm Studio rather than Realm, but thought I'd post here as a start.

Basically, compacting a Realm results in Realm Studio presenting an upgrade dialog when the Realm is opened.

### Repro steps

The steps to reproduce (in code) are...

1. Create Realm
2. Add\Write IRealmObject (two properties, 1 x string primary key, 1 x byte[])
3. Close Realm

4. Open Realm
5. Delete IRealmObject
6. Close Realm

7. Compact Realm (using Realm.Compact)

8. Open Realm in Realm Studio (a "Realm file needs an upgrade" dialog appears, showing In-place & Backup and Upgrade options)

If you repeat the process without step 7, the Realm will open in Realm Studio without the prompt.

### Version

Realm 12.0.0, Realm Studio 15.0.0/15.0.1

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Unity

### Client OS and version

Windows 10

**Comment by markusroessler** [comment]
I think this is also caused by https://github.com/realm/realm-core/issues/7747
See #3612
