### ISSUE TITLE
ToDictionary(Tkey, Filter) not filter

### ISSUE THREAD

**Issue by carbonete** [realm/realm-dotnet#3607]
### What happened?

When use .ToDictionary( Tkey, Filter) allways return all documents.

### Repro steps

Always return all documents, change logical operator not affect. Allways return all docs.

```
var favDic =RealmInstance
                    .All<FavoriteList>()
                    .ToDictionary( k => k.Name , l=> l.Name != DefaultListName )
```

### Version

11.6.1

### What Atlas Services are you using?

Atlas App Services: Functions or GraphQL or DataAPI etc

### What type of application is this?

Xamarin

### Client OS and version

Android 10

### Code snippets

var favDic = RealmInstance
                    .All<FavoriteList>()
                    .ToDictionary( k => k.Name , l=> l.Name == DefaultListName )

**Comment by nirinchev** [comment]
Where does this method come from? To me this looks like the built-in [`Enumerable.ToDictionary`](https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.todictionary?view=net-8.0) where the second argument isn't a filter but instead a predicate that generates the value of the dictionary based on the enumerated object.

**Comment by carbonete** [comment]
@nirinchev sorry my mistake in use this method.
