### ISSUE TITLE
Realm gets deleted on Compact

### ISSUE THREAD

**Issue by markusroessler** [realm/realm-dotnet#3612]
### What happened?

All RealmObjects in a Realm are deleted on Compact when ShouldDeleteIfMigrationNeeded is set to true.
(Regression since 12.0.0)

### Repro steps

Execute the NUnit-Test: https://github.com/markusroessler/RealmCompactBug/blob/main/RealmCompactBugTest/UnitTest1.cs
The test fails on [line 41](https://github.com/markusroessler/RealmCompactBug/blob/main/RealmCompactBugTest/UnitTest1.cs#L41)

Note: The test passes with Realm 11.7.0

### Version

12.2.0

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Console/Server

### Client OS and version

Mac OS 14.5

**Comment by nirinchev** [comment]
This is caused by https://github.com/realm/realm-core/issues/7747.
