### ISSUE TITLE
Getting exception The class TripModel is not in the limited set of classes for this realm

### ISSUE THREAD

**Issue by sledderGIT** [realm/realm-dotnet#3638]
### What happened?

Just started to get an exception
System.ArgumentException: The class TripModel is not in the limited set of classes for this realm (Parameter 'T')

```
using Realms;

namespace CTeleport.Mobile.Core.RealmStore.Trips;

public class TripModel: RealmObject
{
    public TripModel()
    {
    }
    
    [Indexed]
    public DateTimeOffset EndingDate { get; set; }

    [Indexed]
    public DateTimeOffset CreatedAt { get; set; }
    
    [Indexed]
    public DateTimeOffset UpdatedAt { get; set; }
    
    [PrimaryKey]
    public string Id { get; set; }
    public string TravelerName { get; set; }
    public IList<BookingModel> Bookings { get; }
}
```

### Repro steps

1. `RealmInstance.All<TripModel>().Count();`
2. System.ArgumentException: The class TripModel is not in the limited set of classes for this realm (Parameter 'T')

### Version

.NET 8 

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Xamarin

### Client OS and version

iOS simulator 17.2 Realm 12.2

**Comment by nirinchev** [comment]
How do you open the Realm instance? Particularly, how does the config look like?

**Comment by sledderGIT** [comment]
```
    public async Task<Realm> GetRealmInstance(string id)
    {
        return await Realm.GetInstanceAsync(GetRealmConfig(id));
    }

    public RealmConfiguration GetRealmConfig(string id)
    {
        return new RealmConfiguration(id)
        {
            SchemaVersion = RealmVersion,
            ShouldDeleteIfMigrationNeeded = true
        };
    }
```

Nothing extrodinary I would say :)

**Comment by nirinchev** [comment]
Are the models that you use and the code that opens the Realm in the same assembly?
