### ISSUE TITLE
Unity: Compensating Write Errors not Logged as Errors

### ISSUE THREAD

**Issue by moritz-mg** [realm/realm-dotnet#3642]
### What happened?

When certain errors occur, such as compensating writes, the errrors are logged with `Debug.Log` instead of `Debug.LogError` or `Debug.LogException` (or the respective UnityLogger function) in Unity.

This makes compensating writes difficult to spot.

![image](https://github.com/realm/realm-dotnet/assets/98975044/b09fdc73-7637-4376-a613-c06295e68de5)

### Repro steps

1. Make Unity Project :)
2. Write to an object that realm rules disallow this client to write to
3. Observe - plain "Log" entries, even though the condition should be treated as an error log.

### Version

12.1.0

### What Atlas Services are you using?

Atlas Device Sync

### What type of application is this?

Unity

### Client OS and version

UnityEditor (Windows)

### Stacktrace of the exception/crash you're getting

```shell
2024-07-09 08:17:08.264 Info: Connection[1]: Session[7]: Received: ERROR "Client attempted a write that is not allowed; it has been reverted" (error_code=231, is_fatal=false, error_action=Warning)
UnityEngine.Debug:Log (object)
UnityUtils.UnityLogger:LogImpl (Realms.Logging.LogLevel,string)
Realms.Logging.Logger:Log (Realms.Logging.LogLevel,string)
Realms.Logging.Logger:LogDefault (Realms.Logging.LogLevel,string)
Realms.SharedRealmHandle:LogMessage (Realms.Native.StringValue,Realms.Logging.LogLevel)
```

```
2024-07-09 08:17:08.376 Info: Connection[1]: Session[1]: Reporting compensating write for client version 221 in server version 44653: Client attempted a write that is not allowed; it has been reverted
UnityEngine.Debug:Log (object)
UnityUtils.UnityLogger:LogImpl (Realms.Logging.LogLevel,string)
Realms.Logging.Logger:Log (Realms.Logging.LogLevel,string)
Realms.Logging.Logger:LogDefault (Realms.Logging.LogLevel,string)
Realms.SharedRealmHandle:LogMessage (Realms.Native.StringValue,Realms.Logging.LogLevel)
```
```


### Relevant log output

_No response_

**Comment by nirinchev** [comment]
@danieltabacaru this is logged from the sync client - do we think it'd make sense to move the log level for these to `Error` or is `Info` the right place, considering these errors are not fatal?

**Comment by danieltabacaru** [comment]
@nirinchev I think `Info` is fine.
@moritz-mg If you need to keep track of (any) errors, you should do it in the error handler.

**Comment by nirinchev** [comment]
@moritz-mg for more context, you can setup an error handler like:

```csharp
var config = new FlexibleSyncConfiguration(...)
{
    OnSessionError = (session, error) =>
    {
        if (error is CompensatingWriteException cwe)
        {
            foreach (var info in cwe.CompensatingWrites)
            {
                // log write info at whatever level makes sense for your project
            }
        }
    }
}
```
