### ISSUE TITLE
App.AllUsers return include logged out ?

### ISSUE THREAD

**Issue by carbonete** [realm/realm-dotnet#3650]
### What happened?

Hi in my doubt is what App.AllUsers return because in .NET SDK release 12.1.0 notes say

App.AllUsers included logged out users only if they were logged out while the App instance existed. It now always includes all **logged out** users. (Core 14.6.0) ( [Release 12.1.0 · realm/realm-dotnet · GitHub](https://github.com/realm/realm-dotnet/releases/tag/12.1.0) )

But in Realm .NET SDK Docs say :

AllUsers Gets all currently **logged in** users. ( [Class App | Realm](https://www.mongodb.com/docs/realm-sdks/dotnet/latest/reference/Realms.Sync.App.html#Realms_Sync_App_AllUsers) )

What is correct , i use it in my app and until now i consider only user logged in will returned.

Thanks

### Repro steps

visit urls

### Version

12.1.0

### What Atlas Services are you using?

Atlas App Services: Functions or GraphQL or DataAPI etc

### What type of application is this?

Xamarin

### Client OS and version

Android 10

**Comment by papafe** [comment]
Hi @carbonete, thanks for reporting this. What you read in the release should be correct, so `App.AllUsers` should contain both logged in and logged out users. We need to fix the docs of the API

**Comment by carbonete** [comment]
@papafe Thanks 

Please see this page https://www.mongodb.com/docs/atlas/device-sdks/sdk/dotnet/logging/

I think after 12.3.0 release this need revision too.
