### ISSUE TITLE
Realm in Unity Issues after update to 12.3.0

### ISSUE THREAD

**Issue by unapartidamasSL** [realm/realm-dotnet#3656]
### What happened?

I've updated from 12.2.0 to 12.3.0 and now I get this error. If I play my game, when I close I have a crash in Unity without log. I've came back to 12.2.0 and now I can play again without errors.

EntryPointNotFoundException: shared_realm_get_log_level assembly:<unknown assembly> type:<unknown type> member:(null)
Realms.SharedRealmHandle.GetLogLevel (Realms.Logging.LogCategory category) (at <5c992fe941464f80ba4d8c018995b0c9>:0)
Realms.Logging.RealmLogger.GetLogLevel (Realms.Logging.LogCategory category) (at <5c992fe941464f80ba4d8c018995b0c9>:0)
Realms.Logging.RealmLogger.Log (Realms.Logging.LogLevel level, Realms.Logging.LogCategory category, System.String message) (at <5c992fe941464f80ba4d8c018995b0c9>:0)
Realms.Logging.RealmLogger.Log (Realms.Logging.LogLevel level, System.String message) (at <5c992fe941464f80ba4d8c018995b0c9>:0)
Realms.NativeCommon.CleanupNativeResources (System.String reason) (at <5c992fe941464f80ba4d8c018995b0c9>:0)
UnityUtils.Initializer+<>c.<Initialize>b__1_0 () (at <afca79feead543578646db21d682fc81>:0)

### Repro steps

Just start realm config with 12.3.0 and Unity 2023.2.x

### Version

12.3.0

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Unity

### Client OS and version

Windows 11

### Relevant log output

```shell
EntryPointNotFoundException: shared_realm_get_log_level assembly:<unknown assembly> type:<unknown type> member:(null)
Realms.SharedRealmHandle.GetLogLevel (Realms.Logging.LogCategory category) (at <5c992fe941464f80ba4d8c018995b0c9>:0)
Realms.Logging.RealmLogger.GetLogLevel (Realms.Logging.LogCategory category) (at <5c992fe941464f80ba4d8c018995b0c9>:0)
Realms.Logging.RealmLogger.Log (Realms.Logging.LogLevel level, Realms.Logging.LogCategory category, System.String message) (at <5c992fe941464f80ba4d8c018995b0c9>:0)
Realms.Logging.RealmLogger.Log (Realms.Logging.LogLevel level, System.String message) (at <5c992fe941464f80ba4d8c018995b0c9>:0)
Realms.NativeCommon.CleanupNativeResources (System.String reason) (at <5c992fe941464f80ba4d8c018995b0c9>:0)
UnityUtils.Initializer+<>c.<Initialize>b__1_0 () (at <afca79feead543578646db21d682fc81>:0)
```

**Comment by nirinchev** [comment]
This looks like the update didn't correctly update the native library. Can you try and do a clean rebuild of the project (and make sure to restart Unity).

**Comment by unapartidamasSL** [comment]
I did it. And all of we did it. Nothing worked.

**Comment by nirinchev** [comment]
I've tried to reproduce it and everything works as expected. Here's the project I used: 
[Realm12.3.0.zip](https://github.com/user-attachments/files/16454594/Realm12.3.0.zip)

If you can modify it to trigger the erroneous behavior, let me know and I'll take another look.

**Comment by peachypixels** [comment]
FWIW... I'm using Unity 2022.3.LTS with local databases (Windows 10) and everything is working ok, after upgrading from 12.2.0 to 12.3.0

**Comment by unapartidamasSL** [comment]
> I've tried to reproduce it and everything works as expected. Here's the project I used: [Realm12.3.0.zip](https://github.com/user-attachments/files/16454594/Realm12.3.0.zip)
> 
> If you can modify it to trigger the erroneous behavior, let me know and I'll take another look.

Ok, I will do it next saturday.
