### ISSUE TITLE
List of EmbeddedObject no longer being returned with parent object. 

### ISSUE THREAD

**Issue by lamotuab** [realm/realm-dotnet#3657]
### What happened?

I have Journal and JournalEntry classes per the definitions below. During startup, some sample data is created including 3 Journal objects each with either two or three JournalEntry objects attached. Subsequently, I use the following query to retrieve the list of Journals.

`
var journalList = new ObservableCollection<Journal>(_realm.All<Journal>().OrderBy(x => x.Date).ToList());
`

All three of the Journal objects retrieved have an empty Entries list (i.e. list count is zero).

I'm not sure which package upgrade caused this to stop working. 

### Repro steps

Interestingly though, if I migrate all objects to partial classes and use interfaces (i.e IRealmObject) it starts working again. However, this appears to bring heaps of pain with compiler nullability warnings left, right, and centre that I cannot seem to resolve.

### Version

Realm 12.3.

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Other

### Client OS and version

macOS 14.5; NET MAUI 8; C# 12

### Code snippets

```csharp
public class Journal : RealmObject
{
    [PrimaryKey]
    [MapTo("_id")]
    public string Id { get; set; } = Guid.NewGuid().ToString();

    [MapTo("date")]
    public DateTimeOffset Date { get; set; }

    [MapTo("counterparty")]
    public Counterparty Counterparty { get; set; } = new ();

    [MapTo("memo")]
    public Memo? Memo { get; set; }

    [MapTo("reporting_group")]
    public ReportingGroup? ReportingGroup { get; set; }

    [MapTo("amount")]
    public decimal Amount { get; set; }

    [MapTo("entries")]
    public IList<JournalEntry> Entries { get; } = [];
}


public class JournalEntry : EmbeddedObject
{
    [MapTo("_id")]
    public string Id { get; set; } = Guid.NewGuid().ToString();

    [MapTo("account")]
    public Account Account { get; set; } = new();

    [MapTo("currency")]
    public Currency Currency { get; set; } = new();

    [MapTo("amount")]
    public decimal Amount { get; set; }

    [MapTo("is_credit")]
    public bool IsCredit { get; set; }
}
```

**Comment by lamotuab** [comment]
Hi,

I removed the list assignment for Entries in the Journal model definition. It made no difference.

Regards,
Ian

**Comment by nirinchev** [comment]
I've tried to reproduce that and have not been successful. Here's my minimal attempt based on the models that you posted and that behaves as expected (re-running the application preserves the objects I've added). Can you try running it and if that works fine for you - try and modify it so that it triggers the behavior you're observing.

[Issue3657.zip](https://github.com/user-attachments/files/16444155/Issue3657.zip)

**Comment by lamotuab** [comment]
Hi,

My apologies.

I did not fully remove the setting of Entries. Doing so does fix the issue.

Many thanks for your prompt help.

You can close the ticket.

Regards,
Ian
