### ISSUE TITLE
Added db objects are not shown at the Winui3 ItemsControl loading completed.

### ISSUE THREAD

**Issue by daniDevKr** [realm/realm-dotnet#3659]
### What happened?

Added db objects are not shown at the Winui3 ItemsControl loading completed.

### Repro steps

1. At the ItemsControl control loading sample data are loaded into db.
2. The app window not showing added Realm objects.

### Version

net8.0-windows10.0.19041.0

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Other

### Client OS and version

Windows 11 Pro 23H2, build 22631.3958

### Code snippets

Sample code repo link: [Link](https://github.com/daniDevKr/Winui3ItemsControlBug.git)

**Comment by uixiu** [comment]
I didn't test your linked project.
 From reading the MainWindow.xaml and MainWindow.xaml.cs, i think you were binding ItemsControl's ItemsSource to an empty Users[ObservableCollection] , instead of a public/internal _users[IQueryable<Users>] getter.

You can bind the ItemsControl's ItemsSource directly to...

public IQueryable<User> Users => _users; 

...and you will leverage collection change notification just like ObservableCollection.

[Sent from mobile app]

**Comment by daniDevKr** [comment]
Yes, i fix it. But the problem already exist.

**Comment by uixiu** [comment]
I tested your updated project
Indeed, `ItemsControl ` does not support collection change notifications from Realm's `RealmResults` collection.
I changed `ItemsControl ` to `ItemsRepeater ` and it correctly reacts to collection change notifications, including Add and Delete.

Here is the updated XAML

```
<?xml version="1.0" encoding="utf-8"?>
<Window
    x:Class="Winui3ItemsControlBug.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:Winui3ItemsControlBug"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <StackPanel Padding="50">
        <TextBlock> Items:</TextBlock>
        <ItemsRepeater x:Name="ItemsControl1" ItemsSource="{x:Bind _users}" Loaded="ItemsControl1_Loaded">
            <ItemsRepeater.ItemTemplate>
                <DataTemplate x:DataType="local:User">
                    <StackPanel Orientation="Horizontal">
                        <TextBlock Text="{x:Bind Firstname}" Padding="0 0 10 0"/>
                        <TextBlock Text="{x:Bind LastName}"/>
                    </StackPanel>
                </DataTemplate>
            </ItemsRepeater.ItemTemplate>
        </ItemsRepeater>
    </StackPanel>
</Window>
```

**Comment by uixiu** [comment]
Hi @daniDevKr ,
I believe this issue has been resolved, as it's not realm-dotnet related. Could you please close this issue if everything looks good?
Thank you!

**Comment by daniDevKr** [comment]
I replaced `IQueryable<User>` with `IRealmCollection<User>` (on repo) because that supports changes notification, by `INotifyCollectionChanged` event implementation, but not data was showed.
The event `IRealmCollection<User>.CollectionChanged` was never sended.

**Comment by uixiu** [comment]
> I replaced IQueryable<User> with IRealmCollection<User> (on repo) because that supports changes notification, by INotifyCollectionChanged event implementation, but not data was showed.

In fact, you do not need this cast
The following code will return `true`, which indicates IQueryable is IRealmColleciton
```
private IQueryable<User> _users;
...
public MainWindow()
{
  ...
  bool  doesImplement = _users is IRealmCollection<User>;
  ...
}
```
> The event IRealmCollection<User>.CollectionChanged was never sended.

Try with the following code (taken from https://www.mongodb.com/docs/atlas/device-sdks/sdk/dotnet/react-to-changes/#std-label-dotnet-collection-notifications) to make sure the collection change notifications actually fires ( It correctly fires on a few machines/configs of mine, except for a [v12.0.0-v12.3.0]  when compiled under x86 on amd64 Windows  machine. So make sure you compile your project against x64).

```
private IQueryable<User> _users;
...
var subscriptionToken = _users.SubscribeForNotifications((sender, changes) =>
{
    if (changes == null)
    {
      // This is the case when the notification is called
      // for the first time.
      // Populate tableview/listview with all the items
      // from `collection`
      return;
    }
 
    // Handle individual changes
    foreach (var i in changes.DeletedIndices)
    {
      // ... handle deletions ...
    }

    foreach (var i in changes.InsertedIndices)
    {
      // ... handle insertions ...
    }
 
    foreach (var i in changes.NewModifiedIndices)
    {
      // ... handle modifications ...
    }
 
    if (changes.IsCleared)
    {
      // A special case if the collection has been cleared:
      // i.e., all items have been deleted by calling
      // the Clear() method.
    }
    });
```

Actually the notifications are triggered, which indicate it's not realm-dotnet issue but `ItmesControl `issue. As I suggested earlier, you can use `ItemsRepeater ` wich will react to collection change (except perhaps range db transactions)

Not all list based controls behaves the same in WinUI. None play correctly with RealmCollection change notification in WPF. You can actually work around this by using the mentionned `SubscribeForNotifications ` to update an auxiliary/proxy ObservableCollection, if that's suiting your needs.
