### ISSUE TITLE
Possible re-architecture of Windows exception throwing

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#385]
Windows reports when we attempt to throw an exception with our delegate  _“An exception of the type…occurred in Realm.dll and wasn’t handled before a managed/native boundary"_

From the [Slack discussion,](https://realmio.slack.com/archives/dotnet/p1454421887000380) we need to review how Windows handles the exceptions from our delegate. The operating theory is that we have a different reaction in Windows vs Mono.

So, instead of throwing an exception in our delegate, we need to stash an error over on the managed side and then check for that error when we return from our P/Invoke call. Then we throw the exception in the managed caller rather the the callback from native.

Ideally, this can be added without an impact on performance because this is an overhead on every single call.

An attractive idea is that we could add this conditionally for Windows and, **if** the existing approach is robust for the Xamarin environment, then we can keep that.

For Windows, we would stash the error in the realm as thread-local storage.

If we were just allowing people to check for the error themselves we would maybe want a stack here but as it's checked by our code on return from native we can be safe with a single value.

**Comment by kristiandupont** [comment]
Fixed with #681
