### ISSUE TITLE
Add sample for local storage of encryption key

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#405]
How to store a key securely is a platform-specific issue and [Java}(https://realm.io/docs/java/latest/#encryption) and [Cocoa](https://realm.io/docs/swift/latest/#encryption) have samples showing how to do this.  A technique needing review is [this SO Answer](http://stackoverflow.com/questions/28429004/correct-way-to-store-encryption-key-for-sqlcipher-database)

**Comment by cbush** [comment]
We are revamping the Realm docs. We're not ignoring this issue -- we've read through every one of them, and we'll be sure to address this as part of our updates. We're closing the GitHub issues and creating new JIRA tickets to track the work at a high level.
