### ISSUE TITLE
Consider allowing struct instead of/as well as class for realm objects

### ISSUE THREAD

**Issue by kristiandupont** [realm/realm-dotnet#485]

**Comment by dirkoswanepoel** [comment]
In C# structs don't support inheritance. They can only implement interfaces. As such, structs won't be able to use the base object of type RealmObject.

**Comment by fealebenpae** [comment]
@dirkoswanepoel: this ties into our plan to move away from `RealmObject` as a base class and use an attribute to annotate the model types instead (see #529).
