### ISSUE TITLE
Test Android N linking

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#491]
The [Xamarin keynote release post](https://releases.xamarin.com/evolve-keynote-releases/) warns:

_Since Google’s newest Android N previews now [only allow linking to NDK-provided native libraries,](http://developer.android.com/preview/behavior-changes.html#ndk) existing apps using e.g. Mono.Data.Sqlite.dll will crash when running on Android N._

This is a separate issue for dotnet testing apart from any success of our Java product using core on Android N.

**Comment by nirinchev** [comment]
@AndyDentFree is this still needed? One of my devices is on Android N and haven't noticed anything funny. Also, no one seems to have complained about it. Should we close it or is there something else you'd like to test?

**Comment by AndyDentFree** [comment]
> One of my devices is on Android N and haven't noticed anything funny. 

I'm considering it closed then.
