### ISSUE TITLE
Add UWP support

### ISSUE THREAD

**Issue by bmunkholm** [realm/realm-dotnet#509]
Which platforms are most required to support?
- Upvote [this comment for Mobile](https://github.com/realm/realm-dotnet/issues/509#issuecomment-218226192)
- Upvote [this comment for for Surface/tablets and PC](https://github.com/realm/realm-dotnet/issues/509#issuecomment-218226305)
- Upvote [this comment for the remaining targets (HoloLens, IoT, Devices, XBox)
  ](https://github.com/realm/realm-dotnet/issues/509#issuecomment-218226526)

-----------

Core ref: https://github.com/realm/realm-core/issues/2059

**Comment by JonathanADaley** [comment]
I'm definitely interested in Realm for UWP, specifically so it could be used within a native Windows 10 app, across the Desktop/PC, Mobile & Xbox device families; and maybe even HoloLens.

**Comment by adamhill** [comment]
+1

**Comment by balazsgerlei** [comment]
It would be awesome to use Realm in UWP Windows 10 Apps! I hope ypu'll add support soon!

**Comment by corcav** [comment]
Please add UWP support.

**Comment by donniefitz2** [comment]
UWP would  be great and would be in line with the Xamarin cross platform goal (particularly with Xamarin.Forms).

**Comment by AlexBream** [comment]
Please add UWP support!

**Comment by eduard1989** [comment]
Confirm. UWP support would be awesome.

**Comment by kristiandupont** [comment]
Please upvote this comment if you are primarily interested in UWP for Mobile

**Comment by kristiandupont** [comment]
Please upvote this comment if you are primarily interested in UWP for Surface/tablets

**Comment by kristiandupont** [comment]
Please upvote this comment if you are primarily interested in the remaining targets (HoloLens, IoT, Devices, XBox)

**Comment by JonathanADaley** [comment]
While HoloLens and Xbox would be really cool, I think in the near term it'll be more commercially viable for more developers if Tablet/Surface/PC is the primary target. Mid to long term, HoloLens could be very important.

**Comment by rockfordlhotka** [comment]
Seems like a nice data storage option, but not useful for me until it works on UWP and WP8.1 - we're using Xamarin to build an iOS/Android/UWP/WP8.1 app - want to reach all the people.

**Comment by tommy7600** [comment]
+1

**Comment by escamoteur** [comment]
Same for me without UWP it does not make sense

**Comment by pablopioli** [comment]
If UWP is supported I', in!

**Comment by mtycholaz** [comment]
+1

**Comment by delfinof** [comment]
+1

**Comment by cmcginty84** [comment]
+1 for UWP!

**Comment by jantielens** [comment]
👍 or better +37 :)

**Comment by Stoffe** [comment]
+1 for UWP here too!!!!

**Comment by MihaMarkic** [comment]
UWP

**Comment by bernabei** [comment]
UWP++

**Comment by bitdisaster** [comment]
UWP Please!!!

**Comment by joaoBeno** [comment]
+1

**Comment by ShotiQ** [comment]
UWP please please <3 <3

**Comment by soycabanillas** [comment]
+1

**Comment by AndyDentFree** [comment]
@joaoBeno 
>What are the challenges for this to happen? 
Realm has a common C++ core which is compiled for each platform. The C# product is an extremely thin layer on top of this core, mapping data access directly through to the core objects (which is why we use Fody to weave in these accessors). It also implements LINQ querying to use the core engine's query capabilities.

So, the challenge for the device platforms we don't yet support is building core for them, plus a little bit of work to setup test and deployment. That's why we have the individual comments above we'd like you to upvote to determine which device platforms we should prioritise.

**Comment by joaoBeno** [comment]
@AndyDentFree Thanks for the quick reply! I asked mostly to understand and see if I could help with something... Seems that an upvote is all I can do for now...  :D

**Comment by dilipgandham** [comment]
Please support UWP and Windows Phone platforms too.....

**Comment by MihaMarkic** [comment]
If one writes a .net cross platform solution for mobile it is most likely that it has to support Android, iOS and UWP these days. So, it one isn't covered by realm, then it can't be used with other two as well.

**Comment by BlueVirusX** [comment]
+1

**Comment by ShotiQ** [comment]
+10000000000000 :3

**Comment by ncarandini** [comment]
Please add UWP support!

**Comment by Xamtastic** [comment]
I'd love to use Realm but I'm committed to only using technologies that support all three of iOS, Android, and UWP, I'll be watching this space with the hope of being able to use it when UWP support arrives!

**Comment by adrianchifor** [comment]
+1

**Comment by boring32** [comment]
+1

**Comment by csnazell** [comment]
Echoing some of the earlier comments lack of UWP automatically rules out my use of Realm. When UWP becomes a supported platform I'll be interested to take it for a spin.

**Comment by crapitan** [comment]
+1

**Comment by MiddleTommy** [comment]
+1 for UWP Support

**Comment by JOELJOSEPHCHALAKUDY** [comment]
+1 for UWP Support

**Comment by Gionet** [comment]
+1 Please add UWP support please please

**Comment by GiancarloLelli** [comment]
+1

**Comment by lasthulk** [comment]
+2

**Comment by AnasMostefaoui** [comment]
UWP support would be great

**Comment by simor52** [comment]
+1 for UWP

**Comment by ciani** [comment]
+1 for UWP

**Comment by fileman** [comment]
+1 UWP

**Comment by SamuelLioult** [comment]
+1 for UWP. It seems to be logical with the support of Xamarin...

**Comment by JagadeswariGandham** [comment]
+1

**Comment by VamsikrishnaBoggavarapu** [comment]
+1 for UWP

**Comment by ravi1015** [comment]
+1 for UWP

**Comment by ravirajpaidisetti** [comment]
+1 for UWP

**Comment by BharatiGorantla** [comment]
+1

**Comment by SulochanaYelamanchili** [comment]
+1 for UWP

**Comment by dachibox** [comment]
Lets start supporting UWP! First step with xamarin is done! :)

**Comment by MongkonEiadon** [comment]
Can't wait for UWP

**Comment by vaspop** [comment]
Would love some uwp support!

**Comment by vb2ae** [comment]
I would love UWP support

**Comment by support3ds** [comment]
Please add UWP support!

**Comment by ryandary** [comment]
+1

**Comment by escamoteur** [comment]
Anything new on this topic? I'm pondering of replacing akavache with Realm, but without UWP it does not really make sense

**Comment by jurby** [comment]
+1

**Comment by lyzerk** [comment]
+1

**Comment by raznet** [comment]
+1

**Comment by j-hayes** [comment]
+1

**Comment by AuroraDysis** [comment]
+1

**Comment by cbartonnh** [comment]
+1

**Comment by SemyonTenforce** [comment]
+1

**Comment by worstenbrood** [comment]
+1

**Comment by fr0gs** [comment]
+1

**Comment by baguadev** [comment]
+1

**Comment by isaevdan** [comment]
+1

**Comment by wdlb** [comment]
+1 for UWP

**Comment by vobreshkov** [comment]
+1 for UWP

**Comment by nuseaki** [comment]
+1 for UWP

**Comment by shaynevanasperen** [comment]
+1 for UWP

**Comment by drakemonir** [comment]
+1 for UWP

**Comment by Anil86** [comment]
When is UWP for PC going to be supported? Please share the roadmap.

+1 for UWP PC

**Comment by feliciafaye** [comment]
+1 for UWP

**Comment by wfrank2509** [comment]
+1 for UWP

**Comment by orschaef** [comment]
+1 for UWP

**Comment by thaberkern** [comment]
+1 4 UWP

**Comment by validvoid** [comment]
+1 for UWP

**Comment by hvining** [comment]
+1 UWP!!!!!

**Comment by md1986** [comment]
Come on guys don't leave us hanging! +1 4 UWP

**Comment by orospakr** [comment]
I'll note that today's OSS release of Core should now allow for a community-contributed UWP port now. Cheers :)

**Comment by AndyDentFree** [comment]
@orospakr Yes!
See the [open Windows issues](https://github.com/realm/realm-core/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20windows) and particularly realm/realm-core#2059

**Comment by cmcginty84** [comment]
Any updates on this? Need any alpha testers?!

**Comment by EmmanVazz** [comment]
+1 for UWP

**Comment by justinimel** [comment]
UWP support would be awesome!!

**Comment by atultiwari** [comment]
+1 for UWP.
any ETA for UWP support?

**Comment by kristiandupont** [comment]
Sorry, we can't give any specifics yet. We will post any updates in this issue.

**Comment by ajmmurray** [comment]
I note that there are now 200+ MILLION devices running Windows 10. So UWP and WP support is strongly necessary.

**Comment by mdeme** [comment]
+1 for UWP. 

We'd love to use realm in our project but can't as it is Xamarin Android, iOS and UWP.

**Comment by mcortecchia** [comment]
+1 for uwp

**Comment by imrepapp** [comment]
+1 for uwp

**Comment by uneasiersubset** [comment]
+1 UWP  seriously!  win8.1 would be fine too.  anything that can get realm+xamarin forms running on windows. uwp makes the most sense i think.

**Comment by bmunkholm** [comment]
We heard you all loud and clear and are actively working on adding support for UWP. Thanks for all the feedback!
While we would love to make promises about timelines for feature releases, we generally try to avoid that so we don't disappoint you too much in case we need to shuffle priorities. All we can say is that the main blocker - adding support in realm-core - will be completed just before xmas. I'm hopeful we can get a release out before Feb, but as priorities can change there is no promises :-)
Hope this at least gives you some hints to not be in the dark to much longer.

Should there be anyone interested in doing some beta testing, we would love to hear from you!

**Comment by ncarandini** [comment]
I'd like to be a beta tester! :-)

**Comment by iWeaverMan** [comment]
+1 for UWP

**Comment by PolywickStudio** [comment]
Can you contact me for the beta test?

**Comment by ncarandini** [comment]
Hi,
Thanks for inviting me.

Nicolò Carandini 

Inviato da iPhone

**Comment by greglaurent** [comment]
+1 for UWP -- I want to use this for a Xamarin.Forms project, but require UWP. Are there dates for this feature?

**Comment by nirinchev** [comment]
We don't have exact dates that we can commit to, but it is high priority in our backlog and we have already started work on it. You can check the [uwp milestone](https://github.com/realm/realm-dotnet/milestone/4) for a high level overview of what needs to be done and our progress towards it.

**Comment by Steviey** [comment]
Other Windows versions like Win 7 / 8 etc. have still a bigger market share then Win 10 (UWP).
Official support for Win 7 will last until 2020. 

So currently, if I want to be really cross platform (incl. all Windows-Desktops and other OS-Desktops), and have a decent local client db, the is no alternative to SQLite.

**Comment by nirinchev** [comment]
You'd be happy to learn that support for desktop windows is very close to being released. So if you'd like to use Realm for (e.g.) WPF applications, you'll be able to do that. In terms of other OS-Desktops, do you refer to native development (e.g. Obj C for macOS) or using Mono?

**Comment by Steviey** [comment]
@nirinchev 
Sorry, I was in the wrong thread, I left Xamarin-tech months ago :-). 
Just found the realm.js-repo.

**Comment by Zhuinden** [comment]
@nirinchev according to [HERE](https://realm.io/news/realm-microsoft-xamarin-1-0-azure-windows-desktop/) you seem to have released it, is there any sample application and documentation that shows how to use Realm for UWP?

**Comment by nirinchev** [comment]
We released Windows Desktop (i.e. WPF/Console app) support. We're actively working on UWP and hope to have an alpha release in several weeks.

**Comment by ncarandini** [comment]
Waiting for the UWP one ;-)
Nicolò.

Da: Nikola Irinchev [mailto:notifications@github.com]
Inviato: venerdì 17 febbraio 2017 14:21
A: realm/realm-dotnet <realm-dotnet@noreply.github.com>
Cc: Nicolò Carandini <n.carandini@outlook.com>; Comment <comment@noreply.github.com>
Oggetto: Re: [realm/realm-dotnet] Add UWP support (#509)


We released Windows Desktop (i.e. WPF/Console app) support. We're actively working on UWP and hope to have an alpha release in several weeks.

**Comment by sergi10** [comment]
+1

**Comment by tommy7600** [comment]
+1

**Comment by kipters** [comment]
+1

**Comment by atultiwari** [comment]
+1 for UWP.
Sir, any rough estimate, when will UWP support be added or any way to track its progress?
Thanks.

**Comment by nirinchev** [comment]
We're making solid progress toward UWP. We'll be shipping .NET standard soon and next target would be packaging everything for UWP. While we can't give concrete dates, we're very optimistic about landing UWP by mid 2017.

**Comment by hadoan** [comment]
+1

**Comment by JohnCido** [comment]
+1

**Comment by sorochan** [comment]
+1 UWP and Windows Phone 8

**Comment by HobDev** [comment]
Any updates on realm uwp support

**Comment by nirinchev** [comment]
We're happy to announce that this has shipped with version 1.3.0.

**Comment by Zhuinden** [comment]
https://news.realm.io/news/realm-mobile-database-for-universal-windows-platform/

**Comment by Amor-Fairouz** [comment]
no sample project here in this case ? i'm trying to get just the instance in the UWP and it's not working (realm 1.4 )

**Comment by fealebenpae** [comment]
hey @Amor-Fairouz, please open a new issue and attach as much information as possible - code snippets, targeted devices, exception messages (don't forget to check the inner exception, if any).

**Comment by Amor-Fairouz** [comment]
@fealebenpae  done #1410
