### ISSUE TITLE
Binary data properties

### ISSUE THREAD

**Issue by kristiandupont** [realm/realm-dotnet#510]
The obvious choice is to go with `byte[]`. However, those are mutable and there is no way to get around that, so we will probably go with [System.Data.Linq.Binary](https://msdn.microsoft.com/en-us/library/system.data.linq.binary(v=vs.110).aspx) instead. It's unfortunate because it requires referencing a non-default assembly but at least it's a framework assembly.

**Comment by flagbug** [comment]
I don't think `System.Data.Linq.Binary` is available on any other platform than the Full .NET Framework and Windows Phone Silverlight, so using it is problematic

**Comment by kristiandupont** [comment]
@flagbug you are right (http://stackoverflow.com/a/15753777/1417293). Back to the drawing board then. Any suggestions?

**Comment by flagbug** [comment]
You could take something out of [System.Collections.Immutable](https://www.nuget.org/packages/System.Collections.Immutable/1.2.0-rc2-24027) maybe? 

Help me understand what exactly the problem with the mutability of `byte[]` is?

**Comment by kristiandupont** [comment]
I think we might end up going with pure `byte[]` after all. The problem is that we cannot detect mutations (`myObject.BinData[0] = 0;`, etc.). So contrary to what you would expect, such changes will not be persisted.

**Comment by flagbug** [comment]
>  So contrary to what you would expect, such changes will not be persisted.

Generally in .NET you wouldn't expect change notifications for collections, unless they implement [INotifyCollectionChanged](https://msdn.microsoft.com/en-us/library/system.collections.specialized.inotifycollectionchanged(v=vs.110).aspx), so I don't think that would be the case, but maybe that's just me :smile:

**Comment by fealebenpae** [comment]
@flagbug The issue I'm worried about is that changing the byte array you get from a Realm object will not change the same value in the database. `myObject.BinData[0] = 0` might seem like it's a change that will be persisted by Realm, but it actually won't be. That's why we wanted to go with something immutable.

**Comment by flagbug** [comment]
@kristiandupont @fealebenpae So how about `IReadOnlyList<byte>`?

**Comment by fealebenpae** [comment]
Implemented in #567
