### ISSUE TITLE
Fix Core 0.99 onwards freeze on Android

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#516]
Due to a combination of oversights and not realising that our CI was freezing in tests rather than just freezing, we have a current master which stalls running Android tests.

This is an extremely serious potential rollback as it includes the updates to be compatible with the new Timestamp file format with Core 0.100.0. ( **edit** it is core 0.99 causing problems)

All unit tests are freezing in core in the `SharedGroup` destructor, whilst closing the Realm.

**Comment by fealebenpae** [comment]
Fixed in #556
