### ISSUE TITLE
Add macOS support

### ISSUE THREAD

**Issue by umurgdk** [realm/realm-dotnet#528]
As well as UWP also macOS support is needed. Xamarin's power is you can target mobile and desktop applications all together.

**Comment by fealebenpae** [comment]
Hey @umurgdk, Xamarin.Mac support is something we're already considering, so stay tuned.

**Comment by AndyDentFree** [comment]
This is rising in importance now with multiple people in the last few weeks pointing out this is needed for them to be writing things like provisioning tools and other corporate utilities. 

The workaround I recommend is to run a simulator and write little tool apps for that but it is an ugly process and not something they can deliver to non-programmers.

**Comment by sushihangover** [comment]
With `1.0.3` released, is `Xamarin.Mac` next?  Creating matching macOS apps is becoming a sore spot for myself and a number of clients need to sync their iOS app data to/from their Mac apps. We been doing prototypes w/ alpha sync in custom Realm .Net builds and a hacked Xamarin.Mac binding on `realm-cocoa` but need to plan for production releases and trying to determine if RMD Pro/Ent subscriptions will be accessible from Xamairn.Mac. 

Please? Pretty please? Pretty please w/ sugar and sprinklers on top? 🎉

**Comment by nirinchev** [comment]
Hi @sushihangover, we haven't received that many requests for Xamarin.Mac which is why it hasn't been super high priority so far. The good news is that we have core + sync building on macOS, so there's nothing blocking us from doing it.

Obviously, if the request comes from a Pro/Ent customer, we could reprioritize it :) If you could drop us a line at sales@realm.io, our field team will contact you to discuss your needs (which I expect will then be delivered to us in the form of deadlines 😅).

**Comment by sushihangover** [comment]
@nirinchev Thanks for the quick reply, I'm not writing the checks 💰on this one so I passed along the info, hopefully the 2 clients will follow up w/ Sales in the next day or so.

**Comment by nirinchev** [comment]
That's great. Feel free to talk to sales, even if it's a developer edition initially, as the field team's feedback is taken very seriously when planning what to focus on. So even if a company doesn't plan to jump to the Pro edition initially, knowing what's important for our customers will help us better allocate our resources :)

**Comment by NickSpagXamarin** [comment]
+1

**Comment by devkhan** [comment]
Is there any estimates as to when will this be implemented? I tried to use Realm in a Xamarin.Mac app, but got `Fody: Unsupported target: Xamarin.Mac`.

Sorry for my ignorance here, but I don't know how much challenging it is to implement this, and I need to quickly decide on an embedded database to use for my app (and Realm's notifications is a huge plus).

**Comment by NickSpagXamarin** [comment]
I'm in the same boat as @devkhan. And echo @AndyDentFree's point- without Mac support it prevents realm being considered for certain all-platform enterprise stuff. I'm not sure if @sushihangover would open source the Xamarin.Mac binding of Realm-cocoa, which could serve as a stop gap, but a timeline would also be helpful.

Is this something that could be kicked started by community members? Or could a limited functionality version be released per @nirinchev's comment about what's currently working? Thanks all.

**Comment by nirinchev** [comment]
We're still working on enabling macOS support and it's in the really early stages - smoke tests pass, but there's still quite a bit of work to be done before calling it stable. If you're interested though, I can share prerelease packages so you can run your tests with it.

Just to confirm, do you want to use Realm just as offline storage, or are you interested in the Realm Mobile Platform as well?

**Comment by devkhan** [comment]
@nirinchev Sounds great, please share the packages. I'd like to test them as the app is still in early stages.

I want to use Realm for a hobby project of mine to store preferences and some data, so the mobile platform is not planned to be used right now, but I'll see later on.

**Comment by nirinchev** [comment]
Here's the [NuGet package](https://drive.google.com/file/d/0B45yfBWnWXwASUxqUzNNaWRCNGc/view?usp=sharing) you can use to try it out in a Xamarin.Mac app. Keep in mind it's prerelease and there may be quite a few issues there.

**Comment by NickSpag** [comment]
Thank you so much @nirinchev ! It has been great to use so far. Got it working in a Mac app using PCL, and another with .net standard 1.4. And I hope to use the Mobile Platform down the line, yes.

One thing, and this is a hurdle in general with Xamarin Mac, RealmObject doesn't/can't inherit from NSObject when its in a PCL/.NET Standard library, so its a bit troublesome to observe directly to your models. Unless I'm blatantly off point the only route I've seen is to wrap the models with a container object in the Mac project, duplicating some work and, really unfortunately, dulling some of your guys' awesome functionality. I was curious if you all had thought about ways around this? I'm not experienced with IL Weaving or Fody- and thought to try and maybe inject an NSObjet inheritance through that means, but that may interfere with Realm's plumbing and I'm quickly out of my league so don't know what's realistic to attempt.

If there's any areas where feedback could be particularly helpful to you please let me know!

**Comment by fealebenpae** [comment]
> RealmObject doesn't/can't inherit from NSObject when its in a PCL/.NET Standard library, so its a bit troublesome to observe directly to your models

If you mean KVO, you can use the `PropertyChanged` event, part of the `INotifyPropertyChanged` interface that `RealmObject` implements, to observe a realm object for changes. Or do you mean something else?

**Comment by NickSpag** [comment]
@fealebenpae I originally assumed that's what I'd do as well but I believe, and would love to be corrected here, that when using CocoaBindings on macOS (binding values of UI elements, etc, directly to datamodels from within InterfaceBuilder & without all the code) the data object needs to inherit from NSObject and the property needs to be exposed to objective C. So to bind directly to models in a PCL/Standard library, nice and clean/easy, you'd need the Foundation APIs in said library, which isn't too easy from what I can tell. At one point there was a Xamarin nuget that did just that but it hasn't been updated last I checked. Anyway, its not an issue specific to realm really, just gotta wrap the objects/expose properties that'll be exposed to the UI, from the platform specific project.

**Comment by fealebenpae** [comment]
@NickSpag I see, thanks! Indeed you need your object to be exposed to Objective-C and conform to KVC and KVO if you wish to use Cocoa bindings.

**Comment by nirinchev** [comment]
We're pleased to announce that Xamarin.Mac and .NET Core on Mac are fully supported as of Realm 1.6.0. Looking forward to seeing what you folks build with it!
