### ISSUE TITLE
Realm PCL: Portable Class Library

### ISSUE THREAD

**Issue by reader-man** [realm/realm-dotnet#534]
Thanks guys on this initiative, and it would be great to support PCL:
https://msdn.microsoft.com/en-us/library/gg597391(v=vs.110).aspx

So it will be one ring that rules them all, and then it will be easy to use it with Xamarin.Forms in one shot.

**Comment by fealebenpae** [comment]
We do support PCL - our NuGet package has assemblies for iOS, Android, and PCL so if you have a Xamarin.Forms app with code shared between iOS and Android, you can use that. Check out the samples included in the [Xamarin Component](https://components.xamarin.com/view/realm) we ship or [here in the repo](https://github.com/realm/realm-dotnet/tree/master/component/samples/Simple).

**Comment by reader-man** [comment]
Thanks, and sorry because when i went to your site, it was clearly stating iOS and android, but no PCL mentioning.

**Comment by AndyDentFree** [comment]
Thanks for that feedback. Realm has a C++ core so ultimately you are building for a platform and include Realm in both your PCL and the destination platform. Rest assured you can write all your domain logic in a pure PCL and it's just final compilation which is device specific.
