### ISSUE TITLE
Use System.ComponentModel.DataAnnotations attributes instead of our own

### ISSUE THREAD

**Issue by kristiandupont** [realm/realm-dotnet#538]
..and possibly add an `Index` equivalent to the one in EF: https://msdn.microsoft.com/en-us/library/system.componentmodel.dataannotations.schema.indexattribute(v=vs.113).aspx

**Comment by papafe** [comment]
I suppose that changing our attributes is not exactly something we want to do. @nirinchev should we just close this?

**Comment by nirinchev** [comment]
Yeah, that shipped has sailed I guess 😅 Additionally, the system attributes expose more functionality than we support, which would have made it confusing as to what works and what doesn't.
