### ISSUE TITLE
Please support Windows/Mono-Linux

### ISSUE THREAD

**Issue by escamoteur** [realm/realm-dotnet#539]
Hi,

we are discussing right now on slack that it would be necessary to have Realm running on the server side, so that you could generate Realm databases there and download them to the device.

Any chance to see this in the near future?

Best
Thomas

**Comment by bmunkholm** [comment]
Yeah we already support Mac for Swift and ObjC. The Browser runs there as well. For the exact use case you mention (not on Mac) you can also just generate the data in an app and a simulator for now. But we will consider supporting this usecase as well.
 
Others please upvote this if needed above.

**Comment by AndyDentFree** [comment]
@escamoteur for your scenario of Realm running server side, would you prefer it to be accessible from C# or some other server-side programming languages?

**Comment by escamoteur** [comment]
defenetly C# as I could use the same classes as on the Client. But I'm sure other would be happy about other bindinds ;-)

**Comment by ApolonTorq** [comment]
Our ideal would be for Realm to evolve into a modern cross platform database that can be applied to both the server side and client side of a system. A cross platform Realm-Core would be the foundation for this. The priority would be Realm-Core on Win-32 with support for Windows 7 on-wards. However Linux/Unix open-source support would be also very useful. It doesn't have to be free as in beer from my perspective as long as pricing is reasonable. However making the source available would be useful in helping the progression on Linux/Unix systems.

**Comment by ApolonTorq** [comment]
@AndyDentFree For Realm running server side, having both C++ and C# APIs would be useful for different projects/products.

**Comment by nirinchev** [comment]
This has been supported for a while now. Closing.
