### ISSUE TITLE
Byte Array Support

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-dotnet#548]
Based on http://stackoverflow.com/questions/37303478/does-realm-io-support-blobs-byte-type-storage

Is Byte Array support possible in Realm-Xamarin?

I know it is in Realm-Java and it cannot be larger than 16 MB, but I see no such note on Realm-Xamarin.

**Comment by kristiandupont** [comment]
Not yet but it (binary data) is high priority and we expect to have it soon. See #510.

**Comment by Zhuinden** [comment]
I see, thank you for the answer
