### ISSUE TITLE
Android crash using sdcard

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#554]
Spun off from #541 with a copy of the user report from @jerryno6 here below, as it seems to be a distinctly different issue.

I've just create new project, install Realm 0.74.1, and i see the `Import...Fody.targets`
 in my `.csproj.`
Now the database creation is OK, but i have another crash.

``````
   ``` public static string DBFilePath
    {
        get
        {
            string path = Path.Combine(AppFolder, "database.realm");
            return path;
        }
    }
``````

``````
 ```public static string AppFolder
        {
            get
            {
                var packageCode = "DemoRealm1";
                var firstPath = Android.OS.Environment.ExternalStorageDirectory.AbsolutePath;
                string path = Path.Combine(firstPath, packageCode);
                return CreateDirectoryIfNotExists(path);
            }
        }
``````

It crash when i use this code: 

``````
          ```var appDirectory = AppConstants.AppFolder;
            string dbpath = AppConstants.DBFilePath;
            RealmConfiguration cfg = new RealmConfiguration(appDirectory);
``````

//it still crash when I use dbpath 
                var realm = Realm.GetInstance(cfg);```

It is ok if i use this code, but i cannot get the database file path from the sdcard, it always return the default path. I always connect the tablet to PC, and copy files from tablet to PC.

``````
            ```string dbpath = AppConstants.DBFilePath;
            RealmConfiguration cfg = new RealmConfiguration();
            cfg.ConfigWithPath(dbpath);
            var realm = Realm.GetInstance(cfg); ```
``````

**Comment by AndyDentFree** [comment]
I am currently testing a pure Android solution to see if our Android product has the same issues.

**Comment by AndyDentFree** [comment]
So the (confusing) state of this is:
- our Android product can create a Realm on external storage (working in Java)
- the Xamarin test program can create a standard file and write text to it, proving the permissions are correctly set and the program has write access
- that same Xamarin program still gets a RealmFileAccessException when it tries to create the Realm on the external storage. 

Note that _external storage_ is a misnomer - the path is actually `/storage/emulated/0/database.realm`

**Comment by AndyDentFree** [comment]
It is apparently an ObjectStore problem due to `mkfifo` not being supported on external storage's FAT32 system. See for example [this SO question](http://stackoverflow.com/questions/2740321/how-to-create-named-pipe-mkfifo-in-android).

Worked out that the primary difference between Xamarin and Java on Android was the former's use of ObjectStore which led me to ask the question on our Slack and a fast answer from SF.

**Comment by AndyDentFree** [comment]
Progress report - am working on debugging with Visual Studio as adding `EPERM` error result handling for the `mkfifo` call and using a different directory for the pipe appears to work but then crashes later at an undetermined location.

**Comment by AndyDentFree** [comment]
Having to try NDK r11c to be able to build Wrappers on Visual Studio due C++14  problems with the NDK r10e gcc3.x and known bug in the Clang in that version.

**Comment by AndyDentFree** [comment]
Moved this back to backlog as am too busy on other items to call it _Active_ and the PC on which I need to test is tied up doing the IList job.

**Comment by fealebenpae** [comment]
Object Store now handles creating realm files on the SD card and non-standard filesystems. The issue was opening named pipes, which is now implemented.
