### ISSUE TITLE
RealmWeaver.Fody.dll was not found

### ISSUE THREAD

**Issue by SamuelLioult** [realm/realm-dotnet#558]
Hi,
I have an issue after Realm nuget package installation. When I build my solution I have this error:

> Could not copy the file "my_path\packages/Realm.0.74.1/tools/RealmWeaver.Fody.dll" because it was not found.

I try to run an UWP app with Visual Studio 2015 Update 2.
Thanks

**Comment by AndyDentFree** [comment]
Sorry, we do not yet support UWP - see issue #509 for voting.

**Comment by SamuelLioult** [comment]
Okay, thanks for reply.
I will close this issue and vote for UWP!
