### ISSUE TITLE
Base Realm notification on top of SynchronizationContext

### ISSUE THREAD

**Issue by fealebenpae** [realm/realm-dotnet#564]
Every Realm has a background watcher that notifies it of changes in the database file - the `ExternalCommitHelper` and `WeakRealmNotifier` tandem.

Because `ExternalCommitHelper` receives change notifications from other Realm instances on a worker thread, `WeakRealmNotifier` has to call back to the original thread, the one that owns the Realm instance that needs to be notified of changes, using platform-specific primitives such as the Android Looper and the iOS RunLoop.

Unfortunately, this doesn't work when a Realm is opened on a thread without an active Looper or RunLoop, or when those aren't given a chance to process their message queue.

To remedy this, I propose that the `WeakRealmNotifier` class be taught to use .NET's `SynchronizationContext` primitive. 
Xamarin already implement `SynchronizationContext` on top of the [Android Looper](https://github.com/xamarin/xamarin-android/blob/master/src/Mono.Android/Android.App/SyncContext.cs) and the [iOS RunLoop](https://github.com/xamarin/xamarin-macios/blob/master/src/UIKit/UIKitSynchronizationContext.cs) so we wouldn't be losing existing functionality or behaviour. On the contrary, we'd gain support for asynchronously observing realms inside [NUnit async tests](https://github.com/nunit/nunitlite/blob/master/src/framework/Internal/AsyncSynchronizationContext.cs) and other environments that do not interact with the Looper and RunLoop we currently rely on.

**Comment by AndyDentFree** [comment]
Agree strongly this is the way to go after reading [Be Aware of the Synchronization Context](http://www.gamlor.info/wordpress/2010/10/c-5-0-async-feature-be-aware-of-the-synchronization-context/) which includes examples of how this can work in other than simple GUI apps.
