### ISSUE TITLE
Unable to build Xamarin.iOS app with Realm via Macincloud

### ISSUE THREAD

**Issue by MtMovo** [realm/realm-dotnet#584]
Have an issue building iOS app. The reason why i create issue here is that the problem occurs when adding Realm Nuget package. I am able to build the app without it. 

Additional info: 
I'm using Macincloud service to build the app with XCode version 7.3.1

Am i missing something here? Are there any additional work required to make it build?
Thanks

#### Goal

> What do you want to achieve?
Build and debug an app using Xamarin Forms with Realm db
#### Expected Results

Running the app ;)

#### Actual Results

Unable to build app. example error message from build log in Visual Studio:

Error		Native linking error: realm::_impl::AsyncQuery::deliver(realm::SharedGroup&, std::exception_ptr) in libwrappers.a(async_query.o)	Test.iOS

#### Steps & Code to Reproduce

1) Create a Blank Xamarin Forms Shared Project
2) install Realm Nuget Package
3) Connect to a Mac
4) See the errors

#### Code Sample

No custom code. Just a blank app will do to reproduce.

#### Version of Realm and tooling
Realm version(s): ? 0.74.1

Xamarin/Visual Studio version: ?

Xamarin.Forms version 2.0.0.6482
Visual Studio 2015 Update 2 (14.0.25123.00)

Which operating system version and device: ?
Windows 10
Haven't notice any difference between devices - all fail

**Comment by MtMovo** [comment]
Just wanted to give an update on this one.

Was able to make it work. Changed Deployment Target in Info.plist file from 6.0 to 7.1.

So i guess 6.0 is not supported?

**Comment by kristiandupont** [comment]
Great. Yes, we support 7 and up. It's annoying that a new Xamarin app created with Visual Studio defaults to 6.0.

**Comment by MtMovo** [comment]
Thanks for clarification. 
I can see now that You guys mention it in the docs. My bad ;)
