### ISSUE TITLE
Error Updating to Realm 0.75.0 in Xamarin Forms Project

### ISSUE THREAD

**Issue by renzska** [realm/realm-dotnet#586]
#### Goal

Update Xamarin.Forms Realm to 0.75.0.

> What do you want to achieve?

#### Expected Results

> To updated properly

#### Actual Results

PCL project:

Error: "Could not install package 'Realm 1.0.2.4'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile78', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

Android project: 

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

Tried updating NuGet package using Xamarin Studio

> Your code here. Bigger samples should ideally be as separate Xamarin/Visual Studio project, 
> in gists/repositories or privately at help@realm.io)

#### Version of Realm and tooling
Realm version(s): ? 0.75.0 (0.74.1 installs fine).

Xamarin/Visual Studio version: ? 6.1

Which operating system version and device: ? Mac OSX El Captan, Macbook Pro

**Comment by fealebenpae** [comment]
Hey @renzska,

Realm 1.0.2.4 isn't a version that is listed on the [NuGet Gallery](https://www.nuget.org/packages/Realm/) so this appears to be attempting to install a different package. Could you please try deleting your NuGet cache under `~/.local/share/NuGet/Cache` and updating Realm again?

**Comment by renzska** [comment]
@fealebenpae 

Thanks for the info. I deleted the *.json folder and all of its files in the ~/.local/share/NuGet/v3-cache folder and that did the trick!
