### ISSUE TITLE
RealmObject.Equals throws NullReferenceException

### ISSUE THREAD

**Issue by XavierQuincieux** [realm/realm-dotnet#587]
#### Goal

For some reason, I need in generic method to check objects equality thanks to EqualityComparer<T>.Default.Equals(obj1, obj2).

#### Expected Results

I expected EqualityComparer<T>.Default.Equals to return true or false.

#### Actual Results

It throws a NullReferenceException. obj1 and obj2 are not null.

System.NullReferenceException: Object reference not set to an instance of an object
  at Realms.RealmObject.Equals (System.Object obj) [0x00045]
  at System.Collections.Generic.ObjectEqualityComparer`1[T].Equals (System.Collections.Generic.T x, System.Collections.Generic.T y) [0x00016]
  at MyProject.Core.BaseNotifyPropertyChanged.SetField[T] (MyTennisPlayer.Core.T& field, MyProject.Core.T value, System.String propertyName) [0x0000d] 

#### Steps & Code to Reproduce

Create a classe that inherit from RealmObject.
Create two objects of that class, without adding them to a Realm or loading them from a Realm.
Compare equality.

```csharp

public class MyObject : RealmObject
{
	[ObjectId]
	public int Id { get; set; }
	public string Name { get; set; }
}

...

var obj1 = new MyObject () {
	Id = 1,
	Name = "My object 1"
};
var obj2 = new MyObject () {
	Id = 2,
	Name = "My object 2"
};

bool areEquals = EqualityComparer<MyObject>.Default.Equals(obj1, obj2);

```
#### Code Sample

```csharp

protected bool SetField<T>(ref T field, T value, [CallerMemberName]string propertyName = null)
{
    if (EqualityComparer<T>.Default.Equals(field, value)) return false;
    field = value;
    OnPropertyChanged(propertyName);
    return true;
}

```

#### Version of Realm and tooling
Realm version(s): 0.74.1

Xamarin/Visual Studio version: Xamarin Studio 5.10

Which operating system version and device: iPhone Simulator / iOS 9.2

**Comment by kristiandupont** [comment]
What you have there are two standalone objects (i.e. not created with `Realm.CreateObject<>()`). Note that these are not persisted until you call `Realm.Manage()` on them. You have still found a bug though, that is noted. We will fix that :-)

**Comment by XavierQuincieux** [comment]
Thanks for your reply :).

I had a look at the source code and I think it's about the RowHandle in the RealmObject class. I wanted to be sure I didn't do anything wrong (expect not having them persisted in a Realm).
