### ISSUE TITLE
make: /ndk-build: No such file or directory

### ISSUE THREAD

**Issue by shinriyo** [realm/realm-dotnet#589]
I read README.md
and I did
```
cd realm-dotnet-master/wrappers
make clean
make all 
```
but error occurred
```
make: /ndk-build: No such file or directory
```

**Comment by kristiandupont** [comment]
Hi @shinriyo, you need to have the [Android NDK](https://developer.android.com/ndk/index.html) installed. Furthermore, you need [XCode](https://developer.apple.com/xcode/) for the iOS wrappers. At the moment, it's only possible to build on OS X.

And yes, we need to document all of this in the readme.

**Comment by kristiandupont** [comment]
@shinriyo, did you get this working or is it still causing you trouble?
