### ISSUE TITLE
Realm dotnet v0.75.0 - error : Failed to resolve “System.String System.String::Format(System.IFormatProvider,System.String,System.Object)”

### ISSUE THREAD

**Issue by m-mccool** [realm/realm-dotnet#591]
#### Goal

To be able to compile my Xamarin application with Realm V0.75.0

#### Expected Results

A successful build

#### Actual Results

The following error is raised while compiling the solution. The compilation fails

`C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(673,3): error : Failed to resolve "System.String System.String::Format(System.IFormatProvider,System.String,System.Object)" reference from "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"`

#### Steps & Code to Reproduce

I have an existing application to which I add Realm v0.75.0 using the Nuget package manager in Visual Studio. The realm nuget package is added to a Xamarin.iOS project and a portable library project.
I then build the application. It fails with the error above

#### Code Sample

No code is executed

#### Version of Realm and tooling
Realm version(s): 0.75.0

Xamarin/Visual Studio version: Visual Studio 2015 Update 2 (14.0.25123.00)
Xamarin 4.0.4.4
Xamarin.iOS 9.6.2.2

Which operating system version and device: Windows 7

**Comment by AndyDentFree** [comment]
What version of IOS are you targeting? We only support v7 upwards.

Are you able to send a copy of the project or a cut-down version directly to email, if not willing to post here?  `ad@realm.io`

Have you also upgraded your Xamarin version at the same time?

**Comment by m-mccool** [comment]
I are targeting v9. I updated Xamarin to the latest versions after I found this issue, just in case that was the problem. I did notice that the version listed on your site are later versions

On your site

Visual Studio 2015 or higher, or Xamarin Studio version 5.00.0 or higher.
Xamarin iOS version 9.8.0.244 for iOS 7 or higher, using native UI or Xamarin Forms.
Xamarin Android version 6.1.0.37 for API level 10 or later, using native UI or Xamarin 

On my computer

Visual Studio 2015 Update 2
Xamarin.iOS 9.6.2.2
Xamarin.Android 6.0.4.0

I'm not sure why your site lists later versions. As far as I am aware the versions I have installed are the latest stable releases. Is this correct?
I will try to build a smaller app tomorrow which illustrates this issue. I cannot send you our app.

**Comment by eyadon** [comment]
I also got this error with 0.75.0 and iOS, I rolled back to 0.74.1 and was able to build.

**Comment by AndyDentFree** [comment]
@m-mccool > As far as I am aware the versions I have installed are the latest stable releases. Is this correct?

Yes. We also support the beta versions because so many people use them. That used to be explained on the web page but looks like someone simplified the message. I'll change the docs to be sure they only mention the highest stable version.
