### ISSUE TITLE
Update to Core 1.1.2

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#592]
Note to revisit anything involved in the REALM_ANDROID definition inconsistency and yay! for C++14

**Comment by AndyDentFree** [comment]
1.1.0 was pulled due to a bug

**Comment by AndyDentFree** [comment]
Tested heavily with latest core 1.1.2 and running all unit tests fine, noting bug #582 still in force.

**Comment by fealebenpae** [comment]
We don't ship debug versions of core out, so #582 only impacts us internally. We should follow up and see what the fuss is about, but otherwise I'd ignore it.
