### ISSUE TITLE
Encryption key should not be dumped in exception

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#598]
Reported (privately) by a user _I noticed that if I try to open an encrypted realm using GetInstance, the exception that is thrown dumps out the encryption key in the exception message. This seems insecure_

Our good intentions for debugging should not be building for release. it will be fixed in the next release.

**Comment by m-mccool** [comment]
HI Andy,
Will this remove the ability to retrieve the encryption key from the realm completely, otherwise it means anyone could build a custom version of realm to extract the key.

**Comment by AndyDentFree** [comment]
You can't open an encrypted realm without knowing its key, so even someone who rebuilds from the Realm source won't be able to retrieve the key.

**Comment by m-mccool** [comment]
Ok, that's what I was asking, sorry for the confusion

**Comment by AndyDentFree** [comment]
In case anyone's looking at this issue from the outside, due to the potentially sensitive nature of this alleged problem, discussion is taking place via direct email (something we normally discourage).

**Comment by AndyDentFree** [comment]
The debugging code was already removed in Realm 0.75.0

The apparent access to a key was only possible because the Realm was already still open from a previous thread and the correct key was in memory, in a cached schema. Nobody trying to build Realm from source will be able to bypass our encryption.
