### ISSUE TITLE
Unable to use == on member of type long in Where clause of linq query

### ISSUE THREAD

**Issue by Rohitwagh** [realm/realm-dotnet#607]
I am trying to use the following query:

```csharp

long id = 21;
return realm.All<Observations>().Where(x => x.Id == id).First()

```

while using the == in the above Where clause, i get the below exception:

>06-08 17:41:17.902 I/MonoDroid(31149): UNHANDLED EXCEPTION:
06-08 17:41:17.912 I/MonoDroid(31149): System.NotImplementedException: The method or operation is not implemented.
06-08 17:41:17.912 I/MonoDroid(31149):   at Realms.RealmResultsVisitor.AddQueryEqual (Realms.QueryHandle queryHandle, System.String columnName, System.Object value) [0x00197] in <filename unknown>:0 
06-08 17:41:17.912 I/MonoDroid(31149):   at Realms.RealmResultsVisitor.VisitBinary (System.Linq.Expressions.BinaryExpression b) [0x00112] in <filename unknown>:0 
06-08 17:41:17.912 I/MonoDroid(31149):   at Realms.ExpressionVisitor.Visit (System.Linq.Expressions.Expression exp) [0x000d2] in <filename unknown>:0 
06-08 17:41:17.912 I/MonoDroid(31149):   at Realms.RealmResultsVisitor.VisitMethodCall (System.Linq.Expressions.MethodCallExpression m) [0x0006a] in <filename unknown>:0 
06-08 17:41:17.912 I/MonoDroid(31149):   at Realms.ExpressionVisitor.Visit (System.Linq.Expressions.Expression exp) [0x000ec] in <filename unknown>:0 
06-08 17:41:17.912 I/MonoDroid(31149):   at Realms.RealmResultsVisitor.RecurseToWhereOrRunLambda (System.Linq.Expressions.MethodCallExpression m) [0x0000d] in <filename unknown>:0 
06-08 17:41:17.912 I/MonoDroid(31149):   at Realms.RealmResultsVisitor.VisitMethodCall (System.Linq.Expressions.MethodCallExpression m) [0x0025a] in <filename unknown>:0 
06-08 17:41:17.912 I/MonoDroid(31149):   at Realms.ExpressionVisitor.Visit (System.Linq.Expressions.Expression exp) [0x000ec] in <filename unknown>:0 
06-08 17:41:17.912 I/MonoDroid(31149):   at Realms.RealmResultsProvider.Execute[T] (System.Linq.Expressions.Expression expression) [0x00013] in <filename unknown>:0 
06-08 17:41:17.912 I/MonoDroid(31149):   at System.Linq.Queryable.First[TSource] (IQueryable`1 source) [0x00011] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/System.Core/System/Linq/IQueryable.cs:744 

It seems to be the reason of this line: https://github.com/realm/realm-dotnet/blob/7187390529201ba843cd105fc6e3e11acb0c6217/Realm.Shared/linq/RealmResultsVisitor.cs#L385

i see all the supported data types except long.

#### Version of Realm and tooling
Realm: 0.75.0
Xamarin 4.0.3.214 (0dd817c)
Xamarin.Android 6.0.3.5 (a94a03b)
VS 2013
Android version 6.0 - API 23
Samsung EDGE 6 - SM G9251

**Comment by kristiandupont** [comment]
It does indeed look like we are missing support for `long` there. We'll fix that, thanks!
