### ISSUE TITLE
Add support for ObservableCollections

### ISSUE THREAD

**Issue by alexrainman** [realm/realm-dotnet#610]
> **Feature Request**:

Add support for observable collections. ObservableCollection implements IList<T> but also implements INotifyCollectionChanged interface, really useful for ListView bindings.

**Comment by promontis** [comment]
Isn't this already supported?

**Comment by nirinchev** [comment]
All collections used by Realm now implement `INotifyCollectionChanged` and `INotifyPropertyChanged`. Feel free to reopen if you need something particular about `ObservableCollection`.
