### ISSUE TITLE
once I've upgraded to 0.75.0.0 - i can't link assemblies anymore

### ISSUE THREAD

**Issue by YordanYanakiev** [realm/realm-dotnet#611]
> Severity	Code	Description	Project	File	Line	Suppression State
> Error		The "LinkAssemblies" task failed unexpectedly.
> Xamarin.Android.XamarinAndroidException: error XA2006: Reference to metadata item 'System.String System.String::Format(System.IFormatProvider,System.String,System.Object)' (defined in 'Realm, Version=0.75.0.0, Culture=neutral, PublicKeyToken=null') from 'Realm, Version=0.75.0.0, Culture=neutral, PublicKeyToken=null' could not be resolved. ---> Mono.Cecil.ResolutionException: Failed to resolve System.String System.String::Format(System.IFormatProvider,System.String,System.Object)
>    at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
>    at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
>    at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
>    at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
>    at Mono.Linker.Steps.MarkStep.ProcessQueue()
>    at Mono.Linker.Steps.MarkStep.Process()
>    at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
>    at Mono.Linker.Pipeline.Process(LinkContext context)
>    at MonoDroid.Tuner.Linker.Process(LinkerOptions options, LinkContext& context)
>    at Xamarin.Android.Tasks.LinkAssemblies.Execute()
>    --- End of inner exception stack trace ---
>    at Xamarin.Android.Diagnostic.Error(Int32 code, Exception innerException, String message, Object[] args)
>    at Xamarin.Android.Tasks.LinkAssemblies.Execute()
>    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
>    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	Sledi.Droid	C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets	1473	

I've cleaned the solution, upgraded - it didn't worked.
then I've removed every linked assemblies trough NuGet, and installed  them as new - same.

**Comment by fealebenpae** [comment]
Hey @YordanYanakiev, this was fixed in #602. We'll release a new version with the fix in the next few days.
