### ISSUE TITLE
Fody Unhandled Exception: Sequence contains no matching elements

### ISSUE THREAD

**Issue by heiser** [realm/realm-dotnet#635]
I installed Realm for Xamarin (0.76) into my PCL, iOS and Android projects. Everything compiles fine.

Then I created an object derived from RealmObject like so:

`    public class HistoryProperty : RealmObject
    {
        public string Name { get; set; }
        public int Order { get; set; }
    }
`

This results in the following exception (if I remove RealmObject, no error; if I derive from it, then I get the exception):

1>    Fody: Fody (version 1.29.4.0) Executing
1>MSBUILD : error : Fody: An unhandled exception occurred:
1>MSBUILD : error : Exception:
1>MSBUILD : error : Sequence contains no matching element
1>MSBUILD : error : StackTrace:
1>MSBUILD : error :    at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
1>MSBUILD : error :    at ModuleWeaver.WeaveRealmObjectHelper(TypeDefinition realmObjectType)
1>MSBUILD : error :    at ModuleWeaver.Execute()
1>MSBUILD : error :    at lambda_method(Closure , Object )
1>MSBUILD : error :    at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 161
1>MSBUILD : error :    at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 82
1>MSBUILD : error : Source:
1>MSBUILD : error : System.Core
1>MSBUILD : error : TargetSite:
1>MSBUILD : error : TSource Single[TSource](System.Collections.Generic.IEnumerable`1[TSource], System.Func`2[TSource,System.Boolean])
1>MSBUILD : error : 

The Realm assembly and FodyWeaver.xml files are present in all three projects.

**Comment by AndyDentFree** [comment]
Do you have _Linker Behaviour_ set to _Link All_ in the Build settings (Build - IOS Build)? That would explain this issue - #615 schedules adding full linking support.

Also, are you compiling for IOS or Android or experiencing this on both platforms?

**Comment by heiser** [comment]
Currently, my iOS build setting for Linker Behaviour is set to Link SDKs.

But I'm experiencing this problem when attempting to compile for the Android platform.

**Comment by AndyDentFree** [comment]
What is your Android linking setting - is that also Link SDKs or full linking?

**Comment by heiser** [comment]
Android Options -> Linking: None

**Comment by heiser** [comment]
This exception occurs right away, almost immediately after I start the build. I changed the Android link settings to the other options but it didn't make a difference.

**Comment by AndyDentFree** [comment]
Are you building on Visual Studio or Xamarin Studio?

If in Visual Studio, can you please go into Tools - Options - Projects and Solutions - Build and Run and change the _maximum number of parallel project builds_ to 1.

If in Xamarin Studio, please go into Preferences - Projects - Build and uncheck _Enable parallel build of projects._

Then rebuild and see if that works.

I think the weaving code which is falling over is trying to get a reference to the default constructor which is _generated_ by compilation and so there _may_ be a race condition.

**Comment by heiser** [comment]
Using Visual Studio.

I set the maximum number of parallel projects to 1, but unfortunately the results are the same.

**Comment by AndyDentFree** [comment]
Sorry, you've exhausted my theories for remote debugging. As a last-ditch attempt, if you haven't already, try rebuilding your project.

If you can send a copy of your project please mail it to `help@realm.io` or attach it here. That should help us diagnose the problem a lot quicker, thanks.

**Comment by heiser** [comment]
#636 seems to be it! I had one class derived from RealmObject that did not have a default constructor which was causing the exception. Didn't see that as a requirement in the docs.
Thanks for all the help--great support, very responsive.

**Comment by kristiandupont** [comment]
Excellent! No, it wasn't in the docs, we'll fix that. Thanks for the input! :-)
