### ISSUE TITLE
Error with FodyWeavers.xml while updating Realm

### ISSUE THREAD

**Issue by abdullahibnnadjo** [realm/realm-dotnet#649]
Hi,

Updating Realm package (any version) in Xamarin Studio gives me an error with FodyWeavers.xml :

`An error occurred while applying transformation to 'FodyWeavers.xml' in project 'xxxx': No attribute 'name' exists for the Match Locator`

But it does not impact the update, just throwing some warnings.

Also, it adds an extra `<RealmWeaver/>` tag next to the existing one :

```xml
<?xml version="1.0" encoding="utf-8"?>
<Weavers>
	<RealmWeaver/>
	<RealmWeaver/>
  
</Weavers>
```
#### Steps to Reproduce

- Start a new iOS App solution
- Add Realm package < 0.76.1
- Update to 0.76.1

Note : It was already the case with earlier versions

On Xamarin Studio 6.0 Build 5174 on OS X 10.11.5

**Comment by AndyDentFree** [comment]
Related to #524 but adds the error message
