### ISSUE TITLE
Unable to use Linq syntax with ToNotifyCollectionChanged in Xamarin.Forms

### ISSUE THREAD

**Issue by renzska** [realm/realm-dotnet#650]
#### Goal/Expected Results

Updating items in the UI via binding when ordered or with a filtered query using Xamarin.Forms and Realm.

#### Actual Results

IOrderedQueryable does not contain a definition for "ToNotifyCollectionChanged"

#### Code Sample

```
entries = _realm.All<JournalEntry>()
								.OrderBy(x => x.DateCreatedUTC)
								.ToNotifyCollectionChanged(e =>
								{
									// recover from the error - recreate the query or show message to the user
									System.Diagnostics.Debug.WriteLine(e);
								}) as IEnumerable<JournalEntry>;
```

It may be a syntax thing, but I haven't found a way to accomplish this and no samples show it being done.

#### Version of Realm and tooling
Realm version(s): 0.76.1

Xamarin/Visual Studio version: Xamarin Studio 6.0

Which operating system version and device: Mac OS X El Capitan, MacBook Pro

**Comment by fealebenpae** [comment]
The `IOrderedQueryable` is actually a `RealmResults` object so in order to access its API you just need to cast it:
```
var results = _realm.All<JournalEntry>().OrderBy(x => x.DateCreatedUTC) as RealmResults<JournalEntry>;
entries = results.ToNotifyCollectionChanged(...) as IEnumerable<JournalEntry>;
```

**Comment by renzska** [comment]
That does this trick. Thanks!

**Comment by bmunkholm** [comment]
Would this need updated docs or examples?

Den mandag den 20. juni 2016 skrev John Rennemeyer <notifications@github.com

**Comment by renzska** [comment]
I'd recommend adding the usage to https://github.com/realm/realm-dotnet/blob/master/examples/QuickJournal/QuickJournal/ViewModels/JournalEntriesViewModel.cs

By doing a sort order on the date in reverse order showing the newest items at top

```
public JournalEntriesViewModel()
        {
            _realm = Realm.GetInstance();

var results = _realm.All<JournalEntry>().OrderByDescending(x => x.Date) as RealmResults<JournalEntry>;

            Entries = results
                            .ToNotifyCollectionChanged(e =>
                            {
                                // recover from the error - recreate the query or show message to the user
                                System.Diagnostics.Debug.WriteLine(e);
                            }) as IEnumerable<JournalEntry>;

            AddEntryCommand = new Command(AddEntry);
            DeleteEntryCommand = new Command<JournalEntry>(DeleteEntry);
        }
```

**Comment by fealebenpae** [comment]
@bm @renzska: Personally I don't like having to use manual casts, but unfortunately the LINQ extension methods perform type erasure so `RealmResults` is reduced to `IQueryable`. I really wish C# had something like Objective-C's `instancetype` 😞 

But yes, this should be included in our documentation until we can come up with a way around it.

**Comment by nirinchev** [comment]
What about defining `ToNotifyCollectionChanged` extension method over `IQueryable<T>` that simply casts and throws if the collection isn't `RealmResults<T>`? It could be a little misleading, but as long as it's inline documented, I think it would be okay, considering it's unlikely I'll have non-Realm `IQueryable`-s on mobile.

**Comment by AndyDentFree** [comment]
@nirinchev Great minds think alike! I was just mulling over that idea when I saw your comment.

**Comment by fealebenpae** [comment]
@nirinchev precisely, that's what Entity Framework does when exposing advanced functionality on top of LINQ queries such as async and stuff.
