### ISSUE TITLE
Values that are set in Constructor of Model based on RealmObject are not saved to disk

### ISSUE THREAD

**Issue by j3rm** [realm/realm-dotnet#654]
Take this code for example

```
public class Contact : RealmObject
    {
        public Contact()
        {
            // init default
            this.dateAdded = DateTime.UtcNow;
            this.dateModified = DateTime.UtcNow;
            this.isDeleted = false;
        }

```

Then in the dataService i perform these actions.

```

                var c1 = realm.CreateObject<Contact>();
                c1.fullName = "Jeremy Wesley";
                c1.firstName = "Jeremy";
                c1.lastName = "Wesley";
                c1.companyName = "The XYZ Group";
```

I would expect that this newly created object to have a dateAdded and a dateModified but they only have what appears to be a default value of 1/1/1970 when I run this code on ios 9.3 in the simulator.

isDeleted is null, which should be false.

It is as if the constructor code is completely disregarded.

**Comment by fealebenpae** [comment]
Hi @j3rm,

When using `Realm.CreateObject<T>()` the constructor of `T` is invoked before the object is wired up to the Realm instance so any property setters in the constructor would be ignored.

What you can do instead is create the object manually and then add it to the realm:
```csharp
var c1 = new Contact
{
    fullName = "Jeremy Wesley",
    firstName = "Jeremy",
    lastName = "Wesley",
    companyName = "The XYZ Group"
};
realm.Manage(c1);
```

These are what we call standalone, or unmanaged, objects. Realm objects instantiated like so retain their default backing storage (a private field for every automatic property) and adding them to a Realm will copy that backing storage, which means that properties set in the constructor will be honored. Be aware, though, that for the time being `RealmList<>` relationship properties will not work on objects created this way before they have been added to a Realm.

**Comment by j3rm** [comment]
FWIW the Manage call still has to be inside a write transaction.. just incase some one else finds this thread.

```
				realm.Write(() =>
				{
					realm.Manage(c1); // save it to realm
				});
```
