### ISSUE TITLE
Assigning a second object the Same [ObjectId] value does not throw error

### ISSUE THREAD

**Issue by j3rm** [realm/realm-dotnet#655]
Lets use this object
```
public class Contact : RealmObject
{
		public Contact()
		{}
		public string fullName { get; set; }
		[ObjectId]
		public string cID { get; set; }
}
```

now run this code
```
realm.Write(() =>
			{
				var c1 = realm.CreateObject<Contact>();
				c1.fullName = "Jeremy Wesley";
				c1.cID = Guid.NewGuid().ToString("N").ToUpper(); 

				var c2 = realm.CreateObject<Contact>();
				c2.fullName = "Christine Smith";
				c2.cID = c1.cID; // Trying to cause error here instead of using Guid.NewGuid().ToString("N").ToUpper();
});

```
I would expect an error as The cID is suppose to unique. But what happens is that both records are added, with the same ID. I confirmed this by opening the Realm File with the OSX app. When all Contacts are queried it will only return the second contact even though the first contact exist in the database.

**Comment by nirinchev** [comment]
Actually, it is not supposed to be unique, although, I agree, many people will expect it to be. It seems that the Realm team is trying to move away from the notion of primary keys - https://github.com/realm/realm-cocoa/issues/2849. What you're looking for is a `Unique` attribute, which, it appears, is not there yet, so you should handle uniqueness for now.

**Comment by j3rm** [comment]
According to this page it is supposed to. 


https://realm.io/docs/xamarin/latest/

"A single [ObjectId] attribute can be specified on one property to set the model’s object id. Declaring an object id allows objects to be looked up and updated efficiently and enforces uniqueness for each value."

**Comment by AndyDentFree** [comment]
I can't replicate this behaviour of both records being added.

 I can confirm that they are both **accepted** where you might reasonable expect an error trying to add a second object with the same ObjectId, and will look further into that.

Which Realm version are you using and are you running on Simulator or device?

**Comment by j3rm** [comment]
Realm.Xamarin 0.76.1 Version , iOS simulator 9.3,

I went back and ran the test again and I now only see the C2 contact is created with the code posted.

I would expect that C1 should have been created and then C2 would not have been allowed to be created.  C1 existed first, why does it not win in the uniqueness war?

**Comment by AndyDentFree** [comment]
Agreed - the behaviour should be that an exception is generated when you try to save two objects with the same ID, on writing the second.

**Comment by AndyDentFree** [comment]
I am marking this as blocked until we have better ObjectId support for quick direct queries. See #402

**Comment by kristiandupont** [comment]
See also realm/realm-cocoa#4003
