### ISSUE TITLE
Creating new RealmList causes "JIT compile method" crash on iOS

### ISSUE THREAD

**Issue by caranf** [realm/realm-dotnet#660]
When I use:

`new RealmList<RealmFieldData>();`

App crash with message:

```
Attempting to JIT compile method 'SmartDataCollection.TrackingData:.ctor ()' while running with --aot-only. See http://docs.xamarin.com/ios/about/limitations for more information.
```

Here's my model class: 

```
public class TrackingData : RealmObject
{
	public RealmList<RealmFieldData> FieldData {get; }

	public TrackingData()
	{
		FieldData = new RealmList<RealmFieldData>();
	}
}
```

**Comment by AndyDentFree** [comment]
Simply, don't create a `RealmList` - it is created for you automatically when you use the property `FieldData`. Your model class should be just:

```csharp
public class TrackingData : RealmObject
{
    public RealmList<RealmFieldData> FieldData {get; }
}
```

The debugger may show the `FieldData` as null because it inspects a backing field rather than calling the getter woven in by Fody.
