### ISSUE TITLE
DateTimeOffset does not implement IConvertible.

### ISSUE THREAD

**Issue by j3rm** [realm/realm-dotnet#664]
When trying to use reflection to set the value of a DateTimeOffset property on a RealmObject,
 the error "Object must implement IConvertible. " is thrown.

This is the code I'm using.
```
PropertyInfo propertyInfo = _existingRealmObject.GetType().GetProperty(propertyName);
realm.Write(() =>
{
	propertyInfo.SetValue(_existingRealmObject, Convert.ChangeType(newValue, propertyInfo.PropertyType), null);
});
```
newValue is also a nullable DateTimeOffset

**Comment by kristiandupont** [comment]
Yes, `Convert.ChangeType` won't work with `DateTimeOffset`. You could add a check for it and simply skip the redundant conversion, or perhaps you might want to look at [Automapper](http://automapper.org/) for a more industrial-strength solution.

**Comment by kristiandupont** [comment]
I'll close this as it's not strictly related to Realm.
