### ISSUE TITLE
Confirm adding properties handled by automatic migration

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#669]
With 0.76.1 user report of exception being thrown:

`_Realms.RealmMigrationNeededException` : Migration is required due to the following errors: - Property 'ActiveEngines' has been added to latest object model.

As per our documentation, we expect simple additions of properties to migrate automatically.

**Comment by eyadon** [comment]
Looks like it fails to migrate when there's no data to migrate -- I was able to reproduce in the QuickJournal example by adding a RealmObject class, running the app, then adding a property to the class and running again. 
[Foo.txt](https://github.com/realm/realm-dotnet/files/341479/Foo.txt)

**Comment by renzska** [comment]
I was also experiencing the same thing, but assumed, based on the documentation here stating that "migrations" were a part of the current limitations that support for migrations was something that still needed to be added:

https://realm.io/docs/xamarin/latest/#current-limitations

**Comment by ericmutta** [comment]
Just ran into this same issue. Had a person object with Name and Age properties. Tried adding a new property Contact which is another RealmObject with properties Email and PhoneNumber. Subsequent call to Realm.GetInstance() throws:

```
Realms.RealmMigrationNeededException: Migration is required due to the following errors: 

- Property 'Contact' has been added to latest object model.
```

Please tell me that this is me doing something wrong and not a bug/limitation in realm-dotnet because if it's a limitation, it would make Realm impossible for me to use right now :-(

**Comment by AndyDentFree** [comment]
@ericmutta  it is a documentation bug

The easy fix is to set a new schema version each time you change your schema, then it auto-migrates.

See **con.SchemaVersion** below 

```csharp
using Xamarin.Forms;
using Realms;
using System.Diagnostics;
            
namespace test077_pcl
{

    internal class Testr : RealmObject
    { 
        internal string Name { get; set; }  // first prop
        internal int LaterProp { get; set; } // added after launch a few times
    }

    public partial class App : Application
    {
        public App()
        {
            InitializeComponent();

            MainPage = new test077_pclPage();
        }

        protected override void OnStart()
        {
            // Handle when your app starts
            var con = RealmConfiguration.DefaultConfiguration;
            con.SchemaVersion = 1;  // set explicit, ascending number to auo-migrate
            using (var realm = Realm.GetInstance(con)) {
                realm.Write(() => {
                    var obj = realm.CreateObject<Testr>();
                    obj.Name = "Andy";
                });
                Debug.WriteLine($"{realm.All<Testr>().Count()} objects in Realm");
            }
        }

        protected override void OnSleep()
        {
            // Handle when your app sleeps
        }

        protected override void OnResume()
        {
            // Handle when your app resumes
        }
    }
}


```

**Keeping open as doc task**

**Comment by AndyDentFree** [comment]
Note due to a stupid, long-running problem with our content publishing system, the API Help page for RealmConfiguration is broken.

The code is [here](https://github.com/realm/realm-dotnet/blob/master/Realm.Shared/RealmConfiguration.cs)

**Comment by AndyDentFree** [comment]
Incrementing the `SchemaVersion` will automatically handle:

- add properties
- remove properties
- rename properties
- properties changing from required to optional (nullable)
- changing which property is `ObjectId`

Changing the set of `RealmObject` classes does **not** require bumping the schema version.

Note that removing a class declaration **leaves its data** in the Realm. 

Renaming a class behaves like removing it and adding a new one - the automatic migration leaves the old data behind and you see zero objects in the new class.

Using the [browser](https://realm.io/docs/xamarin/latest/#realm-browser) is a great way to see these effects.

Source for `ObjectStore::create_tables` which does auto-migration,  is [here](https://github.com/realm/realm-dotnet/blob/master/wrappers/src/object-store/src/object_store.cpp#L257), in C++

**Comment by ericmutta** [comment]
@AndyDentFree awesome! 

Thanks a lot for the clarification (especially about the actions that can be auto-migrated). The link to the C++ source is also helpful (I thought the whole C++ part was still closed source!).

The level of tech support for this thing is unlike anything I have seen for a free product. Really appreciate it :+1:

**Comment by AndyDentFree** [comment]
@ericmutta The core portion is _yet-to-be-released_ source but a lot of logic lives out in the common `ObjectStore` C++ code. Whilst included individually in the C#, React-JS and Cocoa repos it is common code we evolve in collaboration.

**Comment by AndyDentFree** [comment]
Note that the documentation and tests should also demonstrate catching `RealmMigrationNeededException` as if an app asks the user for permission to migrate, then applying the schema increment and confirming migration works.

**Comment by Rohitwagh** [comment]
This did not solved the problem for me. I tired to update the schema version (SchemaVersion is some long number), but it still fails. with the same error. 

>  FATAL EXCEPTION: main
                                                   Process: com.vitalhealthsoftware.mediq, PID: 28678
                                                   java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
                                                       at dalvik.system.NativeStart.main(Native Method)
                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                    Caused by: android.runtime.JavaProxyThrowable: Realms.RealmException: Migration is required due to the following errors:
                                                   - Property 'ServerIdDuplicate' has been added to latest object model.
                                                     at Realms.NativeException.ThrowIfNecessary () <0x6a3a3468 + 0x00028> in <filename unknown>:0 
                                                     at Realms.SharedRealmHandle.Open (Realms.SchemaHandle schemaHandle, System.String path, Boolean readOnly, Boolean durability, System.Byte[] encryptionKey, UInt64 schemaVersion) <0x6a3a65e8 + 0x000bf> in <filename unknown>:0 
                                                     at Realms.Realm.GetInstance (Realms.RealmConfiguration config, Realms.RealmSchema schema) <0x6a46db78 + 0x001af> in <filename unknown>:0 
                                                     at Realms.Realm.GetInstance (Realms.RealmConfiguration config) <0x6a46d8d0 + 0x00017> in <filename unknown>:0 


Realm version: 0.77.1
Android: 4.4 api 19
Xamarin.Forms version: 2.3.0.114
