### ISSUE TITLE
Simple foreach over RealmResults fails

### ISSUE THREAD

**Issue by SyedWasiHaider** [realm/realm-dotnet#671]
#### Goal

>  I want to iterate over a realmlist and add one of the fields to another list. I would use select() LINQ syntax but that throws a runtime error. So for example I am trying to do this:

    var anotherList = new List<string>
    var temp = realm.All<Records>().ToList(); 
    /*If I put a breakpoint here and inspect temp, I can see ALL the 
    fields are clearly there so it is not because they aren't there to being with. */
    foreach (var element in temp)
     {
            anotherList.add(element.name); //all fields here are null so the entire list will be empty strings.
     }

#### Expected Results

  Should give me a list with the requested properties

#### Actual Results

  List is empty since the members are null;

#### Steps & Code to Reproduce

 See above

#### Code Sample

See above.

#### Version of Realm and tooling
Realm version(s): 0.76.1

Xamarin/Visual Studio version:
Xamarin Studio Enterprise
Version 6.0.1 (build 9)

Which operating system version and device: 
iOS 9.3.2 iPhone 6s

**Comment by SyedWasiHaider** [comment]
Nevermind. It seems the list was populating with the strings but in the breakpoint the field would show up as null.

**Comment by AndyDentFree** [comment]
Just a quick note - you don't need to use `ToList` to iterate like that. Yes we know you can't at present just use `Select` but if you iterate as you have shown and pull the field out, you will just be pulling objects into memory one at a time. The `ToList` will create a list of all the objects in one iteration then you are iterating the `ToList` again.

This is not a problem for small lists but with thousands of objects might become a noticeable impact on memory or CPU.

**Comment by SyedWasiHaider** [comment]
Oh @AndyDentFree I didn't realize that. The only reason I'm even making a list is because I am trying to have a pure MVVM architecture. In other words, I am trying bind the ItemSource property of a ListView in my XAML to some collection object in my View Model. See here for an better example: https://developer.xamarin.com/guides/xamarin-forms/user-interface/listview/data-and-databinding/#Data_Binding

I tried binding to a RealmList<MyModel> but that just caused a straight up native crash (I should probably file a bug report for that). :sweat_smile:

**Comment by AndyDentFree** [comment]
Binding to a `RealmList` is likely to run into problems depending on how you create it.

For a full example of how you can bind to a list see our [QuickJournal example](https://github.com/realm/realm-dotnet/tree/master/examples/QuickJournal) in the `examples` directory.

From `JournalEntriewsViewModel.cs` see:

```csharp
    public class JournalEntriesViewModel
   ...
        public IEnumerable<JournalEntry> Entries { get; private set; }

        public JournalEntriesViewModel()
        {
            _realm = Realm.GetInstance();

            Entries = _realm.All<JournalEntry>()
                            .ToNotifyCollectionChanged(e =>
                            {
                                // recover from the error - recreate the query or show message to the user
                                System.Diagnostics.Debug.WriteLine(e);
                            }) as IEnumerable<JournalEntry>;
```

**Comment by fealebenpae** [comment]
Binding to a `RealmList` shouldn't crash - can you please post an example that triggers a crash?
