### ISSUE TITLE
Crash when querying Realm database (Realms.NativeResults.get_row)

### ISSUE THREAD

**Issue by heiser** [realm/realm-dotnet#684]
I've been able to successfully integrate Realm into a previous Xamarin app, but have hit a problem with my current project using much of the same code. When attempting to query information from the database, the application crashes and I receive:

```
07-10 11:13:10.976 D/Mono    (14165): Searching for 'results_create_for_query_sorted'.
07-10 11:13:10.976 D/Mono    (14165): Probing 'results_create_for_query_sorted'.
07-10 11:13:10.976 D/Mono    (14165): Found as 'results_create_for_query_sorted'.
07-10 11:13:10.986 E/mono-rt (14165): Stacktrace:
07-10 11:13:10.986 E/mono-rt (14165): 
07-10 11:13:10.986 E/mono-rt (14165):   at <unknown> <0xffffffff>
07-10 11:13:10.986 E/mono-rt (14165):   at (wrapper managed-to-native) Realms.NativeResults.get_row (Realms.ResultsHandle,intptr) <0x0003b>
07-10 11:13:10.986 E/mono-rt (14165):   at Realms.RealmResultsEnumerator`1<T_REF>.MoveNext () <IL 0x0002d, 0x00143>
07-10 11:13:10.986 E/mono-rt (14165):   at System.Linq.Buffer`1<TElement_REF>..ctor (System.Collections.Generic.IEnumerable`1<TElement_REF>) [0x00083] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/System.Core/System/Linq/Enumerable.cs:2568
07-10 11:13:10.986 E/mono-rt (14165):   at System.Linq.Enumerable.ToArray<TSource_REF> (System.Collections.Generic.IEnumerable`1<TSource_REF>) [0x00011] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/System.Core/System/Linq/Enumerable.cs:830
```

This crash is caused from the execution of the ToArray line:

```
var realm = Realm.GetInstance();
var list = realm.All<SampleListItem>().Where(d => d.Id > 0).OrderByDescending(d => d.Id);
return list.ToArray();
```

I've also tried ToList, and querying the RealmResult.

This occurs when data has not yet been saved to the database, and also after saving a record with the following code (which executes successfully):

```
_realm.Write(() =>
{
    var item = _realm.CreateObject<SampleListItem>();
    item.Description = description;
});

```

SampleListItem is derived from RealmObject, has a default constructor, etc. 

Xamarin Realm version is 0.76.1
Microsoft Visual Studio Professional 2015
Microsoft .NET Framework Version 4.6.01038
Xamarin   4.1.0.530 
Xamarin.Android   6.1.0.71
Xamarin.iOS   9.8.0.323

**Comment by AndyDentFree** [comment]
How are you assigning the `id` property?

**Comment by heiser** [comment]
`Id` is defined as a long in the `SampleListItem` class. It is currently being set to DateTimeOffset.Now.Ticks.

I have tried Id marked with [ObjectId] and without.

**Comment by AndyDentFree** [comment]
Can you please send a sample which reproduces the crash either attaching a zip to this issue or, to keep things private, email it to help@realm.io.

Also, which platform is this crashing on - iOS or Android, simulator or actual device? If it is just one device please supply more details about the device.

**Comment by heiser** [comment]
It's happening on an actual Android device (Galaxy S7).

I'll have to create the sample, I won't be able to send the actual project I'm working on. My concern is that I won't be able to replicate the issue; as I mentioned above, I am using the same code in another app that is working fine. Does the debug output give any hints where I should look?

**Comment by AndyDentFree** [comment]
A few suggestions on things to gather and send. We may be able to replicate ourselves.
- are any writes or accesses occurring on **other threads** including using `async`?
- at least send us the full schema (change names of properties and classes if privacy requires)
- look at other data values going into the objects and their sizes
- document the amount of data being produced

We have a known bug that we are **not** currently checking to see if access is confined to a single thread, unlike the Cocoa and Java products. So, where they will throw an exception, we would allow inadvertent use on another thread which will have a range of side-effects.

**Comment by AndyDentFree** [comment]
Whilst waiting for the user, we can try doing some quick tests putting long values in from ticks?

**Comment by heiser** [comment]
Writes/accesses are only occurring in one place in the application at the moment, which is the `OnAppearing` override of a `ContentPage` class.

Here is the object:

```
public class SampleListItem : RealmObject
{
    //[ObjectId]
    public long Id;

    public DateTimeOffset   Time;
    public long             Order;
    public string           Description;
    public DateTimeOffset?  SyncTime;
    public int?             SyncResult;

    public SampleListItem()
    {
        DateTimeOffset dto = DateTimeOffset.Now;

        Id = dto.Ticks;
        Time = dto;
        Order = dto.Ticks;
        Description = String.Empty;
        SyncTime = null;
        SyncResult = null;
    }
}
```

There is not much data being produced. I first tried the query without saving anything to the database to test the behavior when blank, and got the crash. I then saved an object to the database (w/o errors) basically using the default data filled out by the constructor above, and also experienced the crash. I also experimented with removing the `[ObjectId]` attribute, removing the constructor, etc., but with the same results.

**Comment by kristiandupont** [comment]
Ah, the reason you are experiencing problems is that you are using public fields, not properties. Only public properties are persisted and recognized by Realm. It's still a bug on our part that you are not properly informed about this when trying to query those, but to get up and running, try adding `{ get; set; }` after each of your fields.

You should also be aware that your constructor will not work with `Realm.CreateObject()`. This is another issue we are aware of (see #654).

**Comment by heiser** [comment]
Converting the fields to properties did the trick, thank you!

**Comment by AndyDentFree** [comment]
Enhancements in #687 and #689 will provide compile errors to prevent this issue recurring for other users.
