### ISSUE TITLE
Where returning null

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#688]
A user has reported `var x = realm.All<Address>().Where(p => p.id == i);` returns null.

Code supplied privately for the schema.

**Comment by AndyDentFree** [comment]
From discussion on the XamarinChat slack, seems likely to be a side-effect of using the Fody.PropertyChanged  weaver.

**Comment by j-hayes** [comment]
I am also trying to use Fody.PropertyChanged with my realm objects. Are you finding these to not be compatible?

**Comment by AndyDentFree** [comment]
Copying comments from there to explain and also added #693 

Using `Fody.PropertyChanged`  ​_should_​ not cause a problem, but it might still be a bit fragile. If you add the `INotifyPropertyChanged` interface to your class and a `public event PropertyChangedEventHandler PropertyChanged;` handler, our weaver should add the mechanics for it to your class.  (This was actually our first third-party PR accepted into realm-dotnet).
