### ISSUE TITLE
JSON extensions

### ISSUE THREAD

**Issue by alexrainman** [realm/realm-dotnet#702]
> **Feature Request**: Just fill in the first two sections below.

One common scenario is receiving a JSON string from back-end or reading it from file system. It will be really useful to have extensions to handle this cases:

RealmResults<T> query = realm.CreateOrUpdateAllFromJson(JSONobj);

RealmObject obj = realm.CreateOrUpdateFromJson(JSONobj);

**Comment by escamoteur** [comment]
Isn't there any way now to read and write JSON?

**Comment by sushihangover** [comment]
I wrote a bunch of Extension methods to do this. Not as efficient as being able to directly initialize a RealmObject with JSON, but it works well for me (I bulk load ~500k RealmObjects and perform updates/inserts around the 25K mark for a Graph database implementation in Xamarin with the JSON coming from a Neo4j instance...)

`Xamarin.Android` JSON-based Android Asset to Realm Usage:

```
using (var theRealm = Realm.GetInstance("StackOverflow.realm"))
using (var assetStream = Assets.Open("States.json"))
{
	theRealm.JsonArrayToRealm<State>(assetStream);
}
```

Extension Sample:
```
public static class RealmDoesJson
{
	public static void JsonArrayToRealm<T>(this Realm realm, Stream stream) where T : RealmObject
	{
		Mapper.Initialize(cfg =>
		{
			cfg.CreateMap<T, T>();
		});
		using (var streamReader = new StreamReader(stream))
		using (var jsonTextReader = new JsonTextReader(streamReader))
		{
			var serializer = new JsonSerializer();
			if (!jsonTextReader.Read() || jsonTextReader.TokenType != JsonToken.StartArray)
				throw new Exception("MALFORMED JSON, Start of Array missing");
			realm.Write(() => // move inside while loop / single object transaction for memory management reasons if needed, or partition writes to 10k per transaction
			{
				while (jsonTextReader.Read())
				{
					if (jsonTextReader.TokenType == JsonToken.EndArray)
						break;
					var jsonObject = serializer.Deserialize<T>(jsonTextReader);
					var realmObject = realm.CreateObject(typeof(T).Name);
					Mapper.Map<T, T>(jsonObject, realmObject);
				}
			});
		}
	}
}

```

Ref: http://stackoverflow.com/questions/40270544/is-there-any-straightforward-way-to-populate-and-update-a-realm-xamarin-from-jso

**Comment by nirinchev** [comment]
Hi, that's quite neat, thanks 👏 I'm not sold on the need for streams though - I did a fairly quick (and dirty) test **on iOS** with 500k objects weighing around 55MB on disk and just reading the file and deserializing it was ~10% faster:
```csharp
var json = File.Read("test.json");
var items = JsonConvert.DeserializeObject<MyObject[]>(json);
foreach (var item in items)
/* ... */
```

Obviously that will differ based on the complexity and the amount of items, but I imagine in most cases the good ol' `DeserializeObject` will work just fine (and makes the code way easier to read 😸).

**Comment by sushihangover** [comment]
@nirinchev I have extensions that do it that way also and use those for *smaller* Json files (width or/and length). Also you are *cheating* by testing on a iDevice as they have the fastest memory and flash IO... ;-) I wish I only had one device manufacture to deal with...

The reason for using a Json streamer in this case is runtime memory consumption. Some of my Json files cause OOM exceptions otherwise, I have to `Deserialize` them on the fly.

**Comment by nirinchev** [comment]
Yes, I figured that might be the case, but didn't have an Android (or an older iPhone for that matter) to confirm it. Either way, good job and thanks for sharing with the community 🙌

**Comment by nirinchev** [comment]
With our latest release, we made some serious improvements of the speed of `Realm.Manage` and now it's the recommended way of adding standalone objects to the Realm. It should be much faster than using AutoMapper and comparable to doing it manually with `Realm.CreateObject` and populating the properties by hand.

Additionally, we've added support for updating objects by primary key, so, piggybacking on @sushihangover's extension methods, here's a sample that you could use for deserializing and adding objects to realm:
```csharp
public static void AddOrUpdateFromJson(this Realm realm, Stream jsonStream)
{
    using (var streamReader = new StreamReader(stream))
    using (var jsonTextReader = new JsonTextReader(streamReader))
    {
        var serializer = new JsonSerializer();
        realm.Write(() =>
        {
            while (jsonTextReader.Read() && jsonTextReader.TokenType != JsonToken.EndArray)
            {
                var jsonObject = serializer.Deserialize<T>(jsonTextReader);
                realm.Manage(jsonObject, update: true);
            }
        });
    }
}
```

Please note that if your objects don't have `[PrimaryKey]` defined, the `update: true` option will be ignored and the objects will be added, not updated.

**Comment by sushihangover** [comment]
Just an FYI, if anyone is looking for a drop-in set of json extensions, I packaged mine up, they mainly mimic the Realm Java ones...

* [Realm.Json.Extensions](https://github.com/sushihangover/Realm.Json.Extensions) `v1.1.0` using Realm `v0.80.0`

	* Due to the changes in `Manage`, it is now faster to create/update `RealmObject`s when dealing with under 1k records then using `AutoMapper`, see [Perf.md](https://github.com/sushihangover/Realm.Json.Extensions/blob/master/Perf.md) for details.
	* Replaced `AutoMapper` w/ `Manage` except for:
	* Added `CreateAllFromJsonViaAutoMapper`

If interested, some very basic and rough perf results of `AutoMapper` vs. `Realm.Manage` that I cooked up as I am mainly using Https-based Json steaming to bulk load ~250k-~500k records. With `0.80.0` I am still using AutoMapper for those large transactions as the memory requirement is lower than using `Realm.Manage`.... 

I have not done much in-depth research beyond those Perf results as I converted the app to `0.80.0` and it passed all the unit tests and benchmarks and then I updated the json extensions to use `Manage` vs `AutoMapper` and the app crashed on large bulk recordset loading. I added `AutoMapper` back for just one method, `CreateAllFromJsonViaAutoMapper` to not use Manage. It appears to be memory fragmentation issues, but again, I have not deep-dived into this and I doubt(?) many people are adding that many records in one transaction using `Realm.Manage`.

Ref: https://github.com/sushihangover/Realm.Json.Extensions/blob/master/Perf.md

**Comment by nirinchev** [comment]
Thank you so much for that, I love the detailed performance analysis! I've opened two new issues to follow up:
- #904 - ideally we'd like to have a gallery of 3rd party packages like yours to ease discoverability.
- #903 - we'll investigate what is causing increasing memory consumption in `Manage` for large number of records.
