### ISSUE TITLE
Integrated XML docs for Xamarin with Visual Studio 2015

### ISSUE THREAD

**Issue by ericmutta** [realm/realm-dotnet#704]
I am new to Realm and really like what I am seeing so far. I plan to use it with Xamarin for Android development.

As a long time Visual Studio user, I enjoy Intellisense with built-in documentation when exploring new APIs. I know you have API docs here:

https://realm.io/docs/xamarin/latest/api/class_realms_1_1_realm.html

...but I would really like them to be integrated into the IDE so I can see them easily via the object browser and intellisense windows. This would make it much easier to use the API without switching to my browser window to see the docs.

Awesome work you guys are doing, thanks in advance!

**Comment by AndyDentFree** [comment]
Please explain how you are unable to see these docs because they **are** written in XML documentation format. If they are not visible then something is going wrong.

**Comment by AndyDentFree** [comment]
I just realised we assume you're using from via nuget. If you're using source you would see the XML docs so any suggestions on how we can fix this would be appreciated!

**Comment by AndyDentFree** [comment]
How we build docs is documented [here](https://github.com/realm/realm-dotnet/blob/master/internals/RealmAPIdocBuilding.md)

**Comment by ericmutta** [comment]
![realm-no-docs](https://cloud.githubusercontent.com/assets/20465797/16867508/de9b9dae-4a7a-11e6-8cfd-f586c4085283.png)

That's a screenshot showing my object browser viewing the Realm assembly. I am using Visual Studio 2015 Community and I pulled in Realm via Nuget. The lower right pane of the object browser should contain a description of the selected Realm class but it is empty.

I think the way Visual Studio does this is by looking for the associated XML docs in a file with the same name as the assembly. So for the Realm.dll assembly the XML docs should be in the same folder with a name like Realm.xml. Here is an example with the popular DevExpress libraries:

![devex-docs](https://cloud.githubusercontent.com/assets/20465797/16867675/c0fbe3ac-4a7b-11e6-943e-c4bd5979ca0f.png)

There if I reference DevExpress.Data.v11.2.dll Visual Studio will pull the docs from DevExpress.Data.v11.2.xml which sits in the same folder.

**Comment by kristiandupont** [comment]
@ericmutta you are right, that was an oversight on our part. Thank you for the notice!

**Comment by ericmutta** [comment]
@kristiandupont great! So I figure you know what's happening now and there will be a fix? :+1:

**Comment by AndyDentFree** [comment]
The good news is that the content is already there we just need to generate the XML file with our next release

**Comment by ericmutta** [comment]
@AndyDentFree @kristiandupont thanks a lot for the super fast responses!
