### ISSUE TITLE
Expose Core C++ engine API to allow faster innovation.

### ISSUE THREAD

**Issue by ericmutta** [realm/realm-dotnet#705]
I am new to Realm and have noticed that not all language bindings are created equal. For example the Xamarin binding has nothing that I can see for accessing schema objects or doing migrations, while the Java binding does.

I was really interested in accessing the schema dynamically so I can make a generic class that would generate unique IDs specific to a RealmObject of type T, but I can't access the schema in Xamarin. It also appears to be impossible to access a field dynamically by string at runtime (e.g. MyRow.Columns["Foo"]) whereas the Java binding seems to have this functionality.

Rather than slave away creating bindings for each language and have them mismatched in features, why not expose and document the API in your wrappers shared libary (I can see the native calls via Reflector)? This would allow a lot of rapid innovation from the community (for example I would happily create a convenient API for migrations and schema access in Xamarin) and more importantly, would free you up to focus on the hardcore stuff in the engine itself.

Any plans in this direction?

**Comment by AndyDentFree** [comment]
Most of what you are looking for is nearly complete. The Xamarin team is a totally separate team from the core engine C++ team, so our time would not be better spent on the core. There is a schedule for releasing the core as open source I can't give dates at this point.

**Comment by kristiandupont** [comment]
Regarding your specific requests, PR's #658 and #675 have been merged into master and will be released shortly. 

The wrappers library is already open source, you are welcome to browse it (or contribute to it): https://github.com/realm/realm-dotnet/tree/master/wrappers

As for open sourcing the core, that is going to happen. Unfortunately we cannot give a timeline at this point, but stay tuned :-)

**Comment by ericmutta** [comment]
Wow, that was fast! Much appreciated @kristiandupont and @AndyDentFree. Looking forward to peeking into the core :-)
