### ISSUE TITLE
Cant use Realm on Xamarin Forms

### ISSUE THREAD

**Issue by joaoalbertofn** [realm/realm-dotnet#729]
Hi I'm having trouble trying to use Realm with Xamarin Forms.

I created a blank new Xamarin Forms and installed Realm (0.77.0) from NuGet .
This is it. Nothing more.
When I try to compile it I get this error: 

> Error: Fody: An unhandled exception occurred:
> Exception:
> Value cannot be null.
> Parameter name: type
> StackTrace:
>   at Mono.Cecil.ModuleDefinition.ImportReference (Mono.Cecil.TypeReference type, IGenericParameterProvider context) <0x3197160 + 0x0009b> in <filename unknown>:0 
>   at Mono.Cecil.ModuleDefinition.ImportReference (Mono.Cecil.TypeReference type) <0x3197130 + 0x0001f> in <filename unknown>:0 
>   at ModuleWeaver.Execute () <0x3157f60 + 0x009ff> in <filename unknown>:0 
>   at (wrapper dynamic-method) System.Object:lambda_method (System.Runtime.CompilerServices.Closure,object)
>   at InnerWeaver.ExecuteWeavers () <0x31579c0 + 0x001b0> in <filename unknown>:0 
>   at InnerWeaver.Execute () <0x30eb2d0 + 0x000df> in <filename unknown>:0 
> Source:
> Mono.Cecil
> TargetSite:
> Mono.Cecil.TypeReference ImportReference(Mono.Cecil.TypeReference, Mono.Cecil.IGenericParameterProvider)
>  (Realm)

But when I delete the : 	<RealmWeaver/> from FodyWeavers.xml it builds fine.
What could it be?
Another thing that I believe it is wrong is because this Sample project it is sized in almost 300mb.
No idea why.

Xamarin Studion Version :
Xamarin Studio Community
Version 6.0.1 (build 9)
Installation UUID: 2ab4b5e8-8790-4585-ac51-8d4506bc625b
Runtime:
	Mono 4.4.1 (mono-4.4.0-branch-c7sr0/4747417) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 404010000

Xamarin.Profiler
Not Installed

Apple Developer Tools
Xcode 7.3.1 (10188.1)
Build 7D1014

Xamarin.iOS
Version: 9.8.1.4 (Xamarin Studio Community)
Hash: 3cf8aae
Branch: c7sr0
Build date: 2016-06-20 16:09:58-0400

Xamarin.Android
Version: 6.1.1.1 (Xamarin Studio Community)
Android SDK: /Users/joaoalbertofn/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.0.3  (API level 15)
		4.1    (API level 16)
		4.2    (API level 17)
		4.3    (API level 18)
		4.4    (API level 19)
		4.4.87 (API level 20)
		5.0    (API level 21)
		5.1    (API level 22)
		6.0    (API level 23)

SDK Tools Version: 25.1.7
SDK Platform Tools Version: 24.0.1
SDK Build Tools Version: 23.0.1

Java SDK: /usr
java version "1.7.0_71"
Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.71-b01, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Xamarin Android Player
Version: 0.6.5
Location: /Applications/Xamarin Android Player.app

Xamarin.Mac
Not Installed

Build Information
Release ID: 600010009
Git revision: e879ce52093257c5c386ad7e390dfaa937fa7f90
Build date: 2016-06-24 11:53:43-04
Xamarin addins: a9252e6df4851fbbed1f9c6228e7b6dd1b475ac5
Build lane: monodevelop-lion-cycle7-sr0

Operating System
Mac OS X 10.11.5
Darwin Joaos-MacBook-Pro.local 15.5.0 Darwin Kernel Version 15.5.0
    Tue Apr 19 18:36:36 PDT 2016
    root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64

Enabled user installed addins
Prism Template Pack 1.3
Gorilla Player 0.9.1.2

**Comment by nirinchev** [comment]
I think this is similar to: https://github.com/realm/realm-dotnet/issues/715. Probably the easiest fix is to rollback to an older Realm version.

**Comment by kristiandupont** [comment]
@nirinchev is right. We are in the process of fixing this. I will close this issue as it's covered by #715.
