### ISSUE TITLE
Simplify Realm.Write and make safer

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#734]
It seems both annoying and a potential cause for subtle bugs that our `Write` taking a lambda requires specifying the Realm again within.

If people have multiple Realms open with copy and paste of expressions, the _inner Realm_ might not match that being used to invoke `Write`.

Good examples:

``` csharp
 _realm.Write(() => _realm.CreateObject<ObjectInPCL>());
```

 or typical longer form assigning properties

``` csharp
    _realm.Write (() => {
         for (var pid = 1; pid <= 4; ++pid) {
              var p = _realm.CreateObject<Product>();
              p.Id = pid; 
              p.Name = $"Product {pid}";
          }
    });
```

**Easily written bug**

``` csharp
 _realm.Write(() => realm.CreateObject<ObjectInPCL>());
```

Would it be worth replacing this, or having an overload, which takes the Realm as a parameter?

``` csharp

 _realm.Write(r => r.CreateObject<ObjectInPCL>());

```

**Comment by promontis** [comment]
This enhancement really makes sense!
