### ISSUE TITLE
Xamarin Studio Only Error - Cannot build an empty ObjectSchema with encryption

### ISSUE THREAD

**Issue by m-mccool** [realm/realm-dotnet#739]
#### Goal

To be able to run an iOS application from Xamarin Studio using Realm 0.77.1

#### Expected Results

The app runs

#### Actual Results

An exception is raised when attempting to retrieve an encrypted realm

System.InvalidOperationException Cannot build an empty ObjectSchema at Realms.Schema.ObjectSchema
This works on an application built using Visual Studio, it only seems to happen with an application built using Xamarin studio

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

The code I am running is similar to that below

```
var config = new RealmConfiguration("MyEncrypted.realm");
                var encryptionKey = new byte[64] // key MUST be exactly this size
                    {
                  0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01,
                  0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01,
                  0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01,
                  0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01,
                 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01,
                  0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01,
                  0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01,
                  0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01,
                    };

                config.EncryptionKey = encryptionKey;
                var realm = Realm.GetInstance(config);
                return realm;
```

It throws the exception on the Realm.GetInstance(config) line

#### Version of Realm and tooling
Realm 0.77.1

Visual Studio 2015 Update 3 v14.0.25424.00 with
Xamrin 4.1.1.3
Xamarin Android 6.1.1.1
Xamarin iOS 9.8.1.4

Xamarin Studio
=== Xamarin Studio Community ===

Version 6.0.1 (build 8)
Installation UUID: c0a4c8dc-0061-4b22-a3ad-b4e6bc68b1db
Runtime:
	Mono 4.4.1 (mono-4.4.0-branch-c7sr0/4747417) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 404010000

=== Xamarin.Profiler ===

Version: 0.31.0
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 6.1.1.1 (Xamarin Studio Community)
Android SDK: /Users/Username/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		2.3   (API level 10)
		4.0.3 (API level 15)
		4.4   (API level 19)
		5.0   (API level 21)
		6.0   (API level 23)

SDK Tools Version: 24.4.1
SDK Platform Tools Version: 23.0.1
SDK Build Tools Version: 23.0.1

Java SDK: /usr
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Android Player ===

Not Installed

=== Apple Developer Tools ===

Xcode 7.3.1 (10188.1)
Build 7D1014

=== Xamarin.Mac ===

Version: 2.8.1.4 (Xamarin Studio Community)

=== Xamarin.iOS ===

Version: 9.8.1.4 (Xamarin Studio Community)
Hash: 3cf8aae
Branch: c7sr0
Build date: 2016-06-20 16:09:58-0400

=== Build Information ===

Release ID: 600010008
Git revision: 0ecc3639cde21616d675e4fdef1b858d166dd065
Build date: 2016-06-20 13:16:51-04
Xamarin addins: a9252e6df4851fbbed1f9c6228e7b6dd1b475ac5
Build lane: monodevelop-lion-cycle7-sr0

=== Operating System ===

Mac OS X 10.11.5
Darwin W013208-MAC 15.5.0 Darwin Kernel Version 15.5.0
    Tue Apr 19 18:36:36 PDT 2016
    root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64

Which operating system version and device: 
iOS targetting 9.0.0
Device running 9.2.1
Mac OS X El Capitan
Windows 7

**Comment by AndyDentFree** [comment]
Do you have any classes declared yet which are `RealmObject` subclasses?

> Cannot build an empty ObjectSchema

Sounds like it has no classes.

That would still be a bug but a much less serious one.

**Comment by m-mccool** [comment]
This is failing the first time I attempt to get the encrypted realm, so there are no objects in the Realm yet. So the app stops immediately. The strange thing is that it only happens using Xamarin studio. 

I am not seeing any build tasks performing any fody processing? Could this be the issue?

**Comment by AndyDentFree** [comment]
Sorry if I wasn't clear, I am **not** asking if you have stored any objects.

Have you got any classes **declared** yet?

I just replicated the bug:

1. Built an IOS solution
2. Added the Realm NuGet
3. Copied and pasted in your code to encrypt **before** adding an RealmObject subclasses
4. Run and aborts with that exception.
5. Add a `RealmObject` subclass declaration and it is fine.

**Comment by m-mccool** [comment]
Hi @AndyDentFree,

I'm still not sure what you mean by this. The application has classes which derive from RealmObject e.g.

```
public class MyRealmDao : RealmObject
{
    public string ValueOne
    {
        get;
        set;
    }
}
```
Is this what you mean? Our app consists of an Xamarin iOS project which references other PCL projects. All the Realm logic is in the PCL projects. Is this why I am getting the error even with RealmObjects defined.

At the moment I can only perform Adhoc builds in Xamarin Studio, so this is a problem.

**Comment by AndyDentFree** [comment]
> The application has classes which derive from RealmObject  

Yes that is one question I needed answering.

> All the Realm logic is in the PCL projects

OK, I am wondering if your `RealmObject` classes are getting woven. If you rebuild your PCL do you see something like this in the log:

```
	Target FodyTarget:
		  Fody: Fody (version 1.29.4.0) Executing
		  Fody: ProjectDirectory: '/Users/andydent/Projects/MultiplatUsingPCL/MultiplatUsingPCL/'.
		  Fody: AssemblyPath: '/Users/andydent/Projects/MultiplatUsingPCL/MultiplatUsingPCL/obj/Debug/MultiplatUsingPCL.dll'
		  Fody: Found path to weavers file '/Users/andydent/Projects/MultiplatUsingPCL/MultiplatUsingPCL/FodyWeavers.xml'.
		  Fody: SolutionDirectory path is '/Users/andydent/Projects/MultiplatUsingPCL/'
		  Fody: Finding weavers
		  Fody: Adding weaver dlls from '/Users/andydent/Projects/MultiplatUsingPCL/Packages'.
		  Fody: Could not find packages dir from nuget config.
		  Fody: SolutionDirectoryPath: /Users/andydent/Projects/MultiplatUsingPCL/
		  Fody: Adding weaver dlls from '/Users/andydent/Projects/MultiplatUsingPCL/packages'.
		  Fody: SolutionDirectoryPath: /Users/andydent/Projects/MultiplatUsingPCL/
		  Fody: Adding weaver dlls from '/Users/andydent/Projects/MultiplatUsingPCL/Tools'.
		  Fody: Fody weaver file added '/Users/andydent/Projects/MultiplatUsingPCL/Tools/RealmWeaver.Fody.dll'
		  Fody: No Weaver project file found.
		  Fody: Finished finding weavers 2ms
		  Fody: Reference count=52
		  Fody: Found debug symbols at '/Users/andydent/Projects/MultiplatUsingPCL/MultiplatUsingPCL/obj/Debug/MultiplatUsingPCL.dll.mdb'.
		  Fody: Weaver '/Users/andydent/Projects/MultiplatUsingPCL/Tools/RealmWeaver.Fody.dll'.
		  Fody:   Initializing weaver
		  Fody:   Loading '/Users/andydent/Projects/MultiplatUsingPCL/Tools/RealmWeaver.Fody.dll' from cache.
		    Fody/RealmWeaver:   Executing Weaver 
		    Fody/RealmWeaver:   Finished 'RealmWeaver' in 4011ms 
```

**Comment by m-mccool** [comment]
Hi @AndyDentFree 
It will be Monday before I can get back to you on this to confirm for certain, but I looked before and I am sure it was not happening.

I have been reading about the Microsoft.Bcl.Build nuget package stopping the Fody weaving

http://stackoverflow.com/questions/25794350/xamarin-studio-build-targets-trying-to-get-fody-working

**Comment by AndyDentFree** [comment]
Thanks, yes that matches my further testing.

1. Created a project using Realm in a PCL
2. Declared a `RealmObject` in the PCL
3. Added your encryption code.
4. Built and ran the project OK
5. Disabled Fody by commenting out the line in the PCL csproj `<Import Project="..\packages\Fody.1.29.4\build\portable-net+sl+win+wpa+wp\Fody.targets" Condition="Exists('..\packages\Fody.1.29.4\build\portable-net+sl+win+wpa+wp\Fody.targets')" />`
6. Ran again and I get the same exception as you.

**Comment by AndyDentFree** [comment]
I have now managed to replicate this in a simple IOS unit test project without involving PCL or encryption at all.

**Comment by m-mccool** [comment]
Hi @AndyDentFree , Is the cause known for this issue? Is there a possible workaround for this?

**Comment by AndyDentFree** [comment]
@m-mccool There are **two** ways to trigger that exception message, which is why we have changed it to be more informative in the next release.

1. You either have no woven RealmObjects, probably because something went wrong with Fody, or
2. Your RealmObjects had their properties stripped because you have Full Linking turned on and they lack the `    [Preserve(AllMembers = true)]` attribute on the class declaration.

If neither of these are the case then we have more headaches and would appreciate some quick feedback.

The next release also increases the amount of information from Fody as you build, so you see the names of properties that are being woven, unless you have your build log set to **Minimal**.
