### ISSUE TITLE
Deletion from a filtered query result - Potentially does not perform delete

### ISSUE THREAD

**Issue by m-mccool** [realm/realm-dotnet#743]
#### Goal

When attempting to delete a list of RealmObjects from a query result,  to know if it has not successfully deleted all the objects returned in the query

#### Expected Results

All the RealmObjects in the query are deleted 

#### Actual Results

Not all the RealmObjects are deleted

#### Steps & Code to Reproduce

See the code below. 

```
var filteredObjects = realm.All<MyRealmObject>().Where(x => x.FieldOne == false
                        && x.FieldTwo == "someText");
                        foreach (var realmObject in filteredObjects)
                        {
                            realm.Remove(realmObject);
                        }
```
What I find is that not all the reamlObjects are being removed/deleted. If I debug it I see the foreach loop exiting before all the objects in the filteredObjects list is processed. To fix it I had to put .ToList() at the end of the query as shown below.

```
var filteredObjects = realm.All<MyRealmObject>().Where(x => x.FieldOne == false
                        && x.FieldTwo == "someText").ToList();
                        foreach (var realmObject in filteredObjects)
                        {
                            realm.Remove(realmObject);
                        }
```

I think this may be a silent fail of trying to delete from an IEnumerable as you loop through it. If this is the case it should throw an exception.

Version of Realm and tooling

Realm 0.77.1

Visual Studio 2015 Update 3 v14.0.25424.00 with
Xamrin 4.1.1.3
Xamarin Android 6.1.1.1
Xamarin iOS 9.8.1.4

Xamarin Studio
=== Xamarin Studio Community ===

Version 6.0.1 (build 8)
Installation UUID: c0a4c8dc-0061-4b22-a3ad-b4e6bc68b1db
Runtime:
Mono 4.4.1 (mono-4.4.0-branch-c7sr0/4747417) (64-bit)
GTK+ 2.24.23 (Raleigh theme)

Package version: 404010000
=== Xamarin.Profiler ===

Version: 0.31.0
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 6.1.1.1 (Xamarin Studio Community)
Android SDK: /Users/Username/Library/Developer/Xamarin/android-sdk-macosx
Supported Android versions:
2.3 (API level 10)
4.0.3 (API level 15)
4.4 (API level 19)
5.0 (API level 21)
6.0 (API level 23)

SDK Tools Version: 24.4.1
SDK Platform Tools Version: 23.0.1
SDK Build Tools Version: 23.0.1

Java SDK: /usr
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Android Player ===

Not Installed

=== Apple Developer Tools ===

Xcode 7.3.1 (10188.1)
Build 7D1014

=== Xamarin.Mac ===

Version: 2.8.1.4 (Xamarin Studio Community)

=== Xamarin.iOS ===

Version: 9.8.1.4 (Xamarin Studio Community)
Hash: 3cf8aae
Branch: c7sr0
Build date: 2016-06-20 16:09:58-0400

=== Build Information ===

Release ID: 600010008
Git revision: 0ecc3639cde21616d675e4fdef1b858d166dd065
Build date: 2016-06-20 13:16:51-04
Xamarin addins: a9252e6df4851fbbed1f9c6228e7b6dd1b475ac5
Build lane: monodevelop-lion-cycle7-sr0

=== Operating System ===

Mac OS X 10.11.5
Darwin W013208-MAC 15.5.0 Darwin Kernel Version 15.5.0
Tue Apr 19 18:36:36 PDT 2016
root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64

Which operating system version and device: 
iOS targetting 9.0.0
Device running 9.2.1
Mac OS X El Capitan
Windows 7

**Comment by AndyDentFree** [comment]
People have logged this issue before, making the same mistake. Yes you are correct that it is an issue solved by using `ToList`. The fact that we have had 2 or 3 issues so far reported is a concern for how easy it is for this kind of code to be written.

>I think this may be a silent fail of trying to delete from an IEnumerable as you loop through it. If this is the case it should throw an exception.

I think you are right in what might be expected behaviour - I did some testing with List and it throws an `InvalidOperationException` if you try removing whilst iterating.

The question is, **how would we detect this is happening?**

Unlike a `List`, where you call `myList.Remove`, we are calling `myRealm.Remove`  with an arbitrary object.

We could maybe do something where an iterator being active at the same time as Remove being called was flagged.  It could detect that the `RealmResults` has been iterated but not reached the end, so is _presumed to be active_.

But say someone has code which iterates through a collection until they find the object they want, then they remove that object. How would we detect that as different from them removing _within_ a loop?

**Comment by AndyDentFree** [comment]
Maybe it is worth writing a very specific test to catch this particular scenario - when an object is removed, check if it is the `Current` in any enumerators on that Realm. That requires the Realm instance track all its `RealmResultsEnumerator` instances which are active.

(Sorry I keep using the term _iterators_ - blame a lot of C++).

**Comment by AndyDentFree** [comment]
Further to the above thought, if we **did** detect deleting the `Current` object in a `RealmResults` being enumerated then there **is** the opportunity for it to adjust the internal state of the `RealmResultsEnumerator` so `MoveNext` won't skip an object. That would give the more intuitive result, although strictly speaking a bit _less correct_ compared to normal `List` behaviour.

**Comment by m-mccool** [comment]
Just working through your comments so I've got it straight

My understanding is that because an IQueryable is returned from the Where clause, then it is acting against the realm e.g. each time I would do a foreach it would query the realm. 

So it seems like the MoveNext is skipping objects because the RealmObject has been removed  from the IQueryable when the call to Remove happens.

I guess the problem is that you cannot tell the difference between someone iterating and updating an object, and someone iterating and deleting an object.

Is an easier option to provide a method that takes the list of object someone want to delete. At least it would take away some of possibility of it happening. You can bet people will write their own method to do this any way. My first thought was to look for a Remove method on the API that does this

**Comment by AndyDentFree** [comment]
Well, there is [RemoveRange](https://realm.io/docs/xamarin/0.77.1/api/class_realms_1_1_realm.html#a783301f776505602af58d8931d9c8061).

So your sample would become:

```
var filteredObjects = realm.All<MyRealmObject>().Where(x => x.FieldOne == false
                        && x.FieldTwo == "someText");
realm.RemoveRange<MyRealmObject>(filteredObjects);
```

Incidentally, there is a search box on the top right corner of the API docs which makes it easy to find these kind of things. Maybe I should try to highlight it or link directly from the main doc?

**Comment by m-mccool** [comment]
Yes but doesn't RemoveRange take a RealmResults rather than an IQueryable, do you have to just cast it to RealmResults. Always a bit wary of casting to fit an API

**Comment by AndyDentFree** [comment]
Yes you have to cast, sorry.

Yes that is a valid concern and I think we should fix it with a runtime test so my (untested) sample code above just works. I have just added #745 for that change.

**Comment by keshavkaul** [comment]
@AndyDentFree Casting from `IQueryable<T>` to `RealmResults<T>` and then passing to RemoveRange doesn't work. It gives me an `EntryPointNotFoundException: results_clear` exception.

I would want RemoveRange to also work with IList<T> for scenarios when  removing all objects in a relation.

**Comment by AndyDentFree** [comment]
@keshavkaul can you please start a new issue with some sample code - that exception shouldn't be occurring.
