### ISSUE TITLE
Refine RemoveRange or overload to take IQueryable

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#745]
A recommended solution to delete a selection of objects is

```
var filteredObjects = realm.All<MyRealmObject>().Where(x => x.FieldOne == false
                        && x.FieldTwo == "someText");
realm.RemoveRange<MyRealmObject>(filteredObjects);
```

However, that doesn't currently compile because `RemoveRange` takes a `RealmResults` and the LINQ expression returns an `IQueryable`.

An overload of `RemoveRange` could take an `IQueryable` parameter and check its actual type matches. It may also be able to avoid using the generic by using IRealmResults interface to get the `ResultsHandle`.

**Comment by fealebenpae** [comment]
We could have a generic constraint like `void RemoveRange<T>(IQueryable<T> items) where T : RealmObject` pretty much like we do for the `ToNotifyCollectionChanged` extension method.
