### ISSUE TITLE
Fatal signal 11 (SIGSEGV) - Crashing on any realm.io operations

### ISSUE THREAD

**Issue by DrifterApps** [realm/realm-dotnet#748]
#### Goal

Ever since I upgraded to 0.77.1, my Android application keeps crashing.

The call that crashes matching the stack trace is:

`RealmDb.All<Tag> ().Any (t => t.Id != id && t.Name == name)`

But the same type of crashes occurs if I try to  use Write and so on.

Because I was busy, my code did not change in the past few weeks. And all the calls to Realm in 0.68.1 were working, but are now failing once I upgraded to 0.77.1.

#### Expected Results

Since my Tag table is empty, the call should return false.

#### Actual Results

[Mono] DllImport searching in: 'wrappers' ('./libwrappers.so').
[Mono] Searching for 'query_group_begin'.
[Mono] Probing 'query_group_begin'.
[Mono] Found as 'query_group_begin'.
[Mono] DllImport searching in: 'wrappers' ('./libwrappers.so').
[Mono] Searching for 'query_get_column_index'.
[Mono] Probing 'query_get_column_index'.
[Mono] Found as 'query_get_column_index'.
[mono-rt] Stacktrace:
[mono-rt] 
[mono-rt]   at <unknown> <0xffffffff>
[mono-rt]   at (wrapper managed-to-native) Realms.QueryHandle/NativeMethods.get_column_index (Realms.QueryHandle,string,intptr,Realms.NativeException&) <IL 0x00037, 0x0013e>
[mono-rt]   at Realms.QueryHandle.GetColumnIndex (string) <IL 0x0000f, 0x000f3>
[mono-rt]   at Realms.RealmResultsVisitor.AddQueryNotEqual (Realms.QueryHandle,string,object) <IL 0x00002, 0x000ab>
[mono-rt]   at Realms.RealmResultsVisitor.VisitBinary (System.Linq.Expressions.BinaryExpression) <IL 0x00138, 0x00863>
[mono-rt]   at Realms.ExpressionVisitor.Visit (System.Linq.Expressions.Expression) <IL 0x000d9, 0x001e6>
[mono-rt]   at Realms.RealmResultsVisitor.VisitCombination (System.Linq.Expressions.BinaryExpression,System.Action`1<Realms.QueryHandle>) <IL 0x00012, 0x0010b>
[mono-rt]   at Realms.RealmResultsVisitor.VisitBinary (System.Linq.Expressions.BinaryExpression) <IL 0x0002b, 0x001a7>
[mono-rt]   at Realms.ExpressionVisitor.Visit (System.Linq.Expressions.Expression) <IL 0x000d9, 0x001e6>
[mono-rt]   at Realms.RealmResultsVisitor.RecurseToWhereOrRunLambda (System.Linq.Expressions.MethodCallExpression) <IL 0x00042, 0x002c7>
[mono-rt]   at Realms.RealmResultsVisitor.VisitMethodCall (System.Linq.Expressions.MethodCallExpression) <IL 0x001fb, 0x01343>
[mono-rt]   at Realms.ExpressionVisitor.Visit (System.Linq.Expressions.Expression) <IL 0x000f3, 0x00352>
[mono-rt]   at Realms.RealmResultsProvider.Execute<bool> (System.Linq.Expressions.Expression) <IL 0x00014, 0x00105>
[mono-rt]   at System.Linq.Queryable.Any<TSource_REF> (System.Linq.IQueryable`1<TSource_REF>,System.Linq.Expressions.Expression`1<System.Func`2<TSource_REF, bool>>) [0x00022] in /Users/builder/data/lanes/3540/1cf254db/source/mono/external/referencesource/System.Core/System/Linq/IQueryable.cs:1038
[mono-rt]   at DrifterApps.FeedTheHole.Core.Data.Repository.BaseRepository`2<TObject_REF, TInterface_REF>.Exists (System.Linq.Expressions.Expression`1<System.Func`2<TInterface_REF, bool>>) [0x0001a] in /Users/patrick/Projects/FeedTheHole/Core.Data/Repository/BaseRepository.cs:79
[mono-rt]   at DrifterApps.FeedTheHole.Core.Managers.TagManager/<Validate>c__AnonStorey4.<>m__0 () [0x000e8] in /Users/patrick/Projects/FeedTheHole/Core/Managers/TagManager.cs:89
[mono-rt]   at System.Reactive.Linq.QueryLanguage/<>c__DisplayClassd5`1/<>c__DisplayClassd7<DrifterApps.FeedTheHole.Core.Managers.TagValidation>.<ToAsync>b__d4 () <IL 0x00013, 0x000bd>
[mono-rt]   at System.Reactive.Concurrency.Scheduler.Invoke (System.Reactive.Concurrency.IScheduler,System.Action) <IL 0x00001, 0x00079>
[mono-rt]   at System.Reactive.Concurrency.ScheduledItem`2<System.TimeSpan, System.Action>.InvokeCore () <IL 0x00012, 0x000a4>
[mono-rt]   at System.Reactive.Concurrency.ScheduledItem`1<System.TimeSpan>.Invoke () <IL 0x00014, 0x000e7>
[mono-rt]   at System.Reactive.Concurrency.CurrentThreadScheduler/Trampoline.Run (System.Reactive.Concurrency.SchedulerQueue`1<System.TimeSpan>) <IL 0x00041, 0x0032f>
[mono-rt]   at System.Reactive.Concurrency.CurrentThreadScheduler.Schedule<TState_REF> (TState_REF,System.TimeSpan,System.Func`3<System.Reactive.Concurrency.IScheduler, TState_REF, System.IDisposable>) <IL 0x00047, 0x0041f>
[mono-rt]   at System.Reactive.Concurrency.LocalScheduler.Schedule<TState_REF> (TState_REF,System.Func`3<System.Reactive.Concurrency.IScheduler, TState_REF, System.IDisposable>) <IL 0x00016, 0x0015e>
[mono-rt]   at System.Reactive.Concurrency.Scheduler.Schedule (System.Reactive.Concurrency.IScheduler,System.Action) <IL 0x0002a, 0x001ce>
[mono-rt]   at System.Reactive.Linq.QueryLanguage/<>c__DisplayClassd5`1<DrifterApps.FeedTheHole.Core.Managers.TagValidation>.<ToAsync>b__d3 () <IL 0x0002a, 0x0027b>
[mono-rt]   at System.Reactive.Linq.QueryLanguage.Start<DrifterApps.FeedTheHole.Core.Managers.TagValidation> (System.Func`1<DrifterApps.FeedTheHole.Core.Managers.TagValidation>,System.Reactive.Concurrency.IScheduler) <IL 0x00008, 0x000c4>
[mono-rt]   at System.Reactive.Linq.Observable.Start<DrifterApps.FeedTheHole.Core.Managers.TagValidation> (System.Func`1<DrifterApps.FeedTheHole.Core.Managers.TagValidation>,System.Reactive.Concurrency.IScheduler) <IL 0x00023, 0x0016a>
[mono-rt]   at DrifterApps.FeedTheHole.Core.Managers.TagManager.Validate (DrifterApps.FeedTheHole.Core.Data.Model.ITag) [0x0002c] in /Users/patrick/Projects/FeedTheHole/Core/Managers/TagManager.cs:85
[mono-rt]   at DrifterApps.FeedTheHole.Core.ViewModels.TagViewModel/<TagViewModel>c__AnonStorey0.<>m__0 (string) [0x00029] in /Users/patrick/Projects/FeedTheHole/Core/ViewModels/TagViewModel.cs:76
[mono-rt]   at System.Reactive.Linq.ObservableImpl.Select`2/_<TSource_REF, TResult_REF>.OnNext (TSource_REF) <IL 0x00014, 0x000c5>
[mono-rt]   at System.Reactive.Linq.ObservableImpl.DistinctUntilChanged`2/_<TSource_REF, TKey_REF>.OnNext (TSource_REF) <IL 0x00090, 0x005be>
[mono-rt]   at System.Reactive.Linq.ObservableImpl.Throttle`1/_<TSource_REF>.Propagate (System.Reactive.Concurrency.IScheduler,ulong) <IL 0x00030, 0x001bc>
[mono-rt]   at ReactiveUI.HandlerScheduler/<Schedule>c__AnonStorey1`1<ulong>.<>m__0 () [0x0000c] in /Users/paul/code/reactiveui/reactiveui/ReactiveUI/Android/AndroidUIScheduler.cs:57
[mono-rt]   at Java.Lang.Thread/RunnableImplementor.Run () [0x0000b] in /Users/builder/data/lanes/3540/1cf254db/source/monodroid/src/Mono.Android/src/Java.Lang/Thread.cs:36
[mono-rt]   at Java.Lang.IRunnableInvoker.n_Run (intptr,intptr) [0x00009] in /Users/builder/data/lanes/3540/1cf254db/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Java.Lang.IRunnable.cs:81
[mono-rt]   at (wrapper dynamic-method) object.5f1214c2-c7c1-4dfe-bfe6-ffe85bb21911 (intptr,intptr) <IL 0x00011, 0x00031>
[mono-rt]   at (wrapper native-to-managed) object.5f1214c2-c7c1-4dfe-bfe6-ffe85bb21911 (intptr,intptr) <IL 0x0001e, 0x000a5>
[mono-rt] 
[mono-rt] Attempting native Android stacktrace:
[mono-rt] 
[mono-rt] 	Could not unwind with `libunwind.so`: dlopen failed: library "/data/app/com.drifterapps.feedthehole-1/lib/x86_64/libunwind.so" not found
[mono-rt] 	Could not unwind with `libcorkscrew.so`: libcorkscrew is only supported on 32-bit ARM/x86
[mono-rt] 
[mono-rt] 	No options left to get a native stacktrace :-(
[mono-rt] 
[mono-rt] =================================================================
[mono-rt] Got a SIGSEGV while executing native code. This usually indicates
[mono-rt] a fatal error in the mono runtime or one of the native libraries 
[mono-rt] used by your application.
[mono-rt] =================================================================
[mono-rt] 
[libc] Fatal signal 11 (SIGSEGV), code 1, fault addr 0x7ffeebdb8718 in tid 2826 (pps.feedthehole)

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```csharp

> Your code here. Bigger samples should ideally be as separate Xamarin/Visual Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): 0.77.1

Xamarin/Visual Studio version: 6.0.2 build 73

Which operating system version and device: Android API 24

**Comment by kristiandupont** [comment]
@DrifterApps I am unable to reproduce the error in a clean setup. Is it possible for you to share some code that demonstrates the problem?

Also, you state that
>But the same type of crashes occurs if I try to use Write and so on.
How exactly does the error reveal itself here?

**Comment by DrifterApps** [comment]
Hi,

It looks like any call which accesses an object causes the crash... Just doing a Realm.All<>().Count() will be fine because it returns 0... But as soon as I do a call like Realm.All<>().Where(x => x.name == "test")... then I get the crash with the above log...

Doing a Realm.Write(() => {
 ...
});

I get the same type of crash.

I will try to build a test project for tomorrow and send it to you. Hopefully I can reproduce it also.

**Comment by DrifterApps** [comment]
Hi,

I cannot reproduce it either with a new project. Probably means that something is interfering with this release of Realm. I will go thru the release note again and try to figure out what could be causing this. 

Thanks!

**Comment by DrifterApps** [comment]
HI,

I'm closing this issue because downgrading to Realm v0.76 causes the same crash. So it's probably another packages upgrade which caused the issue... I will investigate more and if I ever find the root cause, I will post it here.
