### ISSUE TITLE
Don't close in Dispose

### ISSUE THREAD

**Issue by kristiandupont** [realm/realm-dotnet#759]
Currently, Dispose closes the database. This causes other instances to close as well which is wrong. However, just relying on the reference count seems not to work on Windows so that needs to be resolved.

**Comment by petersondrew** [comment]
So is there currently a workaround to this behavior? Also, when *should* we call close? I had been considering using `ThreadLocal<>` to manage my Realm instances across threads but decided it was easier to call `GetInstance` wrapped in a using statement whenever I need a Realm instance. This bug would mean disposing would actually create cross-thread issues correct?

**Comment by petersondrew** [comment]
@kristiandupont Any advice for the above questions? Thanks.

**Comment by kristiandupont** [comment]
@petersondrew my apologies, this flew off my radar. Calling `GetInstance` in a using statement will work fine because only other instances on the same thread will be closed along with the one being disposed. We are going to remove the `Close` method altogether because it's quite confusing.

**Comment by nirinchev** [comment]
This has been superseded by the `RealmState` approach.
