### ISSUE TITLE
Problems when using Where with DateTimeOffset or Any

### ISSUE THREAD

**Issue by almujtaba** [realm/realm-dotnet#777]
Hello,
I had two problems while trying to do some queries using on Xamarin.Android and realm ...

### Realm classes
First of all, here are my realm classes

```
class dArticle : RealmObject
{
    [ObjectId]
    public int article_id { get; set; }

    public RealmList<dCategory> article_categories { get; }
    public DateTimeOffset created { get; set; }
}

class dCategory : RealmObject
{
    [ObjectId]
    public string identifier { get; set; }

    public string item_name { get; set; }
}
```

### First problem
When using `Where` with `DateTimeOffset` , as in this example :

```
DateTime myTime = new DateTime(1990, 1, 1, 0, 0, 0);
Realm realm = Realm.GetInstance(RealmConfiguration.DefaultConfiguration);
var results = realm.All<dArticle>().Where(d => d.created.DateTime != myTime );
Console.WriteLine("aaaaaa");
Console.WriteLine("bbbbb " + results.Count() );
Console.WriteLine("cccccc");
```

The table `dArticle` is empty and doesn't contain any rows, so the console should print
```
- aaaaaa
- bbbbb 0
- cccccc
```

but actually I'm getting only
`- aaaaaa`

and everything from the line of results.Count() and after it doesn't run
(no errors or crash ... the app keeps working)
I thought maybe results.Count() causing round loop and prevent the app from running the rest of the code

### Second problem
Very similar to the previous problem but when using `Where `with `Any` , as in this example :

```
Realm realm = Realm.GetInstance(RealmConfiguration.DefaultConfiguration);
var results = realm.All<dArticle>().Where(d =>
                            d.article_categories.Any(cat => cat.item_name == "news")
                                         );
Console.WriteLine("aaaaaa" );
Console.WriteLine("bbbbb " + results.Count() );
Console.WriteLine("cccccc" );
```

This table `dCategory` doesn't contain row with the name "news", so the console should print
```
- aaaaaa
- bbbbb 0
- cccccc
```

but actually I'm getting only
`- aaaaaa`
and also everything after the line of results.Count() and after it doesn't run

I don't know if the problem is in my code or it is an issue in this version of Realm
Thanks in advance ...

### Version of Realm and tooling
Realm version: 0.77.2

Using Microsoft Visual Studio Community 2015
Version 14.0.25422.01 Update 3

Running of LG Nexus 5 with Android 6.0

**Comment by AndyDentFree** [comment]
In your first example you are using a local `DateTime myTime ` instead of a `DateTimeOffset` so I am not surprised there are problems.

LINQ is not evaluated until you write an expression which uses the LINQ results - in this case your `Count` statements. 

The second one appears to be failing because you are searching via the related list, which seems similar to a problem brought up a while ago #651. I will dig further into this using your schema (thanks for including them).

**Comment by AndyDentFree** [comment]
See also #723

**Comment by almujtaba** [comment]
### For the first problem : 
I was able to solve it using your advice, as in the following example:
```
DateTimeOffset myTime = new DateTimeOffset(1990, 1, 1, 0, 0, 0, new TimeSpan(0, 0, 0));
Realm realm = Realm.GetInstance(RealmConfiguration.DefaultConfiguration);
var results = realm.All<dArticle>().Where(d => d.created != myTime );
Console.WriteLine("aaaaaa");
Console.WriteLine("bbbbb " + results.Count() );
Console.WriteLine("cccccc");
```
and it works perfectly ..

### For the second problem : 
I think the support of `Contains` and `Any` operations is very important for the usage of realm
Hope you can support them soon ..
At the moment, the documentation in [realm.io](https://realm.io/docs/xamarin/latest/) should be a little more detailed and mention the unsupported LINQ operations ...
it only says 

> Current Limitations: More LINQ operations

which is not clear at all

#### And finally thanks for your efforts ...

**Comment by almujtaba** [comment]
I was able to solve the second problem by this simple workaround : 

```
Realm realm = Realm.GetInstance(RealmConfiguration.DefaultConfiguration);
var results = realm.All<dArticle>();
List<dArticle> articlesList = new List<dArticle>();

foreach (dArticle one_article in results)
{
    if (one_article.article_categories.Any( cat => cat.item_name == "news" ))
    {
        articlesList.Add(one_article);
    }
}

Console.WriteLine("aaaaaa");
Console.WriteLine("bbbbb " + articlesList.Count() );
Console.WriteLine("cccccc");
```

**Comment by AndyDentFree** [comment]
Closing for now - we have #651 to cover making the second case work and user has a workaround for now.
