### ISSUE TITLE
Make dynamic Realm opening public

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#778]
On top of the current Schema and other dynamic classes, this would allow a user app to open a completely unknown Realm and browse its contents (unless encrypted).

**Comment by AndyDentFree** [comment]
See user example in #824

**Comment by AndyDentFree** [comment]
Further reason to do this - might allow writing IronPython tools to work on existing Realms.

**Comment by Zhuinden** [comment]
Any news on this?

**Comment by listepo** [comment]
Hi, guys, I'm working on a Realm browser for Windows and I'm waiting for this feature

**Comment by listepo** [comment]
Any news on this?

**Comment by nirinchev** [comment]
Hi @listepo, we haven't made any progress on it. It's fairly high on our priority list though, so we're optimistic about delivering it this fall.

**Comment by listepo** [comment]
@nirinchev thanks, I'll wait
