### ISSUE TITLE
Transaction.Dispose() may throw exception

### ISSUE THREAD

**Issue by csoren** [realm/realm-dotnet#779]
In certain scenarios, Transaction.Dispose() may throw an exception, particularly when the Realm object has been dropped on the floor and presumably garbage collected.

This worked in 0.76.1 but fails in 0.77.2. I have not tried 0.77.1

#### Goal

Perform a rollback by calling Dispose(), but not keep track of the Realm object myself. It is my understanding that GetInstance() has a thread local copy of the Realm handle anyway.

#### Expected Results

Rollback the transaction. Don't throw exceptions in Dispose() as per the usual Dispose() contract.

#### Actual Results

A System.ObjectDisposedException is thrown when calling Transaction.Dispose()

Cannot access a disposed object.
Object name: 'handle'.

  at System.Runtime.InteropServices.SafeHandle.DangerousAddRef (System.Boolean& success) [0x00020] in /Users/builder/data/lanes/3539/f37444ae/source/maccore/_build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/corlib/System.Runtime.InteropServices/SafeHandle.cs:120 
  at (wrapper managed-to-native) Realms.SharedRealmHandle+NativeMethods:cancel_transaction (Realms.SharedRealmHandle,Realms.NativeException&)
  at Realms.SharedRealmHandle.CancelTransaction () [0x00000] in <filename unknown>:0 
  at Realms.Transaction.Rollback () [0x00016] in <filename unknown>:0 
  at Realms.Transaction.Dispose () [0x00014] in <filename unknown>:0 
  at realmtest.Application.Main (System.String[] args) [0x00012] in /Users/ces/Projects/realmtest/realmtest/Main.cs:27 

#### Steps & Code to Reproduce

Run the sample code. You may need to adjust the sleep interval.
https://github.com/csoren/realm-transaction-dispose

#### Code Sample

https://github.com/csoren/realm-transaction-dispose

Essentially this snippet will reproduce the problem:

```csharp
        static Transaction GetTransaction()
        {
            var realm = Realm.GetInstance();
            return realm.BeginWrite();
        }

        // This is the main entry point of the application.
        static void Main(string[] args)
        {
            var transaction = GetTransaction();

            // Sleep two seconds, may need to adjust this value
            System.Threading.Thread.Sleep(2000);

            transaction.Dispose();
        }
```

#### Version of Realm and tooling
Realm version(s): 0.77.2. Example worked in 0.76.1

Xamarin/Visual Studio version: 
Xamarin Studio Business
Version 6.0.2 (build 73)
Installation UUID: 4d1d704d-e2ee-4ab5-8fad-c11eac1363f9
Runtime:
	Mono 4.4.2 (mono-4.4.0-branch-c7sr1/f72fe45) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Package version 404020011

Xamarin.Profiler
Version: 0.24.0.0
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Apple Developer Tools
Xcode 7.3.1 (10188.1)
Build 7D1014

Xamarin.iOS
Version: 9.8.2.22 (Xamarin Business)
Hash: f37444a
Branch: cycle7-sr1
Build date: 2016-07-28 12:17:02-0400

Which operating system version and device: iPhone Simulator 9.3

**Comment by fealebenpae** [comment]
Hey @csoren, this is indeed a bug. Fortunately, it was easy to fix. Thank you for reporting it!
