### ISSUE TITLE
String query ignore case

### ISSUE THREAD

**Issue by sunniejai** [realm/realm-dotnet#794]
Is there anyway to do a case insensitive string query?

Things I tried but didn't work:

`realm.All<Item>().Where(x => String.Equals(x.Name, "abc", StringComparison.OrdinalIgnoreCase))`
`realm.All<Item>().Where(x => x.Name.Equals("abc", StringComparison.OrdinalIgnoreCase))`

**Comment by kristiandupont** [comment]
This is not yet supported, no. Thank you for reporting this, we will prioritize it.
