### ISSUE TITLE
Remaining Element Operators

### ISSUE THREAD

**Issue by kristiandupont** [realm/realm-dotnet#802]
Missing:
 - [x] FirstOrDefault
 - [x] ElementAt
 - [x] ElementAtOrDefault
 - [x] SingleOrDefault
 - [x] Last
 - [x] LastOrDefault
 - [ ] DefaultIfEmpty

**Comment by promontis** [comment]
+1 for this. This should be low hanging fruit right?

**Comment by kristiandupont** [comment]
Hopefully :-)

**Comment by AndyDentFree** [comment]
The `ElementAt` appears to be implemented in #802 but needs unit tests.

**Comment by AndyDentFree** [comment]
Dropping `DefaultIfEmpty` from this and moving to lower priority #816 as it seems very complex to implement with our current architecture and of little appeal.
