### ISSUE TITLE
Delete if migrations required on Windows

### ISSUE THREAD

**Issue by kristiandupont** [realm/realm-dotnet#809]
Currently this doesn't work. Probably related to #759, setting `m_sharedgroup` to `nullptr` isn't enough to close the file on Windows. This (and #759) is most probably an issue in object store.

**Comment by fealebenpae** [comment]
This turned out to be due to the implementation of the generic `ExternalCommitHelper` which held a `SharedGroup` instance of the file.

**Comment by nirinchev** [comment]
@fealebenpae is this resolved now?

**Comment by fealebenpae** [comment]
I think so? Does the test pass on Windows?
