### ISSUE TITLE
Executing Realm on iOS Simulator

### ISSUE THREAD

**Issue by LuigiMaestrelli** [realm/realm-dotnet#817]
I'm trying to execute a simple project on iOS Simulator and the build throws this error:

>  Undefined symbols for architecture x86_64

When I set the platform to IPhoneSimulator, is not possible to define the supported architetures to ARMv7 or ARM64

There are something that I can do to execute on the simulator?

Thanks

**Comment by AndyDentFree** [comment]
In Xamarin Studio, you need to set the Project Options - Build section - iOS Build panel.

The top of that panel has Configuration settings to choose Debug/Release and iPhone/iPhoneSimulator. Choose those to match.

After choosing the type of configuration, check that Supported architectures matches i386+x86_64. It sounds like it is just at i386.

**Comment by LuigiMaestrelli** [comment]
Thanks for responding.

Same error. I tried with only i386 and only and x86_64.

A attached the full log of the build compilation.
I hope that helps.
 
[iOSBuild.txt](https://github.com/realm/realm-dotnet/files/456549/iOSBuild.txt)

**Comment by fealebenpae** [comment]
Hey @LuigiMaestrelli, it looks like your app's minimum iOS version is 6, but realm only supports 7 and up and the linker errors are for symbols in the C++ standard library that are missing in iOS 6.

**Comment by LuigiMaestrelli** [comment]
Ridiculous mistake, sorry.

Thanks for the fast replies
