### ISSUE TITLE
Ensure Weaver adding preserve attribute

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#822]
See the latest [SO Question](http://stackoverflow.com/questions/39365317/realm-exception-when-schema-is-created-on-ios-only/39366902?noredirect=1#comment66062117_39366902) indicating fairly clearly that our weaver is **not** adding the expected preserve attribute, so the user is having to work around by adding it themselves.

This is not the first time this problem has surfaced and it needs explanation each time.

It _may_ be that this is a variant where we need to be adding the preserve attribute to their own default constructor, or we are possibly not adding the `AllMembers` clause.

It may also be that our preserve attribute is (no longer) compatible with the IOS one.

**Comment by nirinchev** [comment]
It is looking for the attribute by name and I haven't heard about changes on Xamarin's side, so it is unlikely to be an incompatibility. Also, it is strange that the user reports their linker setting is `Don't link`, yet adding `[Preserve]` fixes the issue. Finally, I'd expect similar linker settings for iOS and Android, yet the user reports the problem surfacing only on iOS. 

Long story short, unless we're able to repro/validate that the weaver is not adding `[Preserve]` attributes (which should be fairly straightforward), there may be some other issue in disguise :)

**Comment by marceln** [comment]
I'm the original reporter of the issue on SO. If you need more details, then let me know.

**Comment by AndyDentFree** [comment]
I simply took the [Preserve] attributes off the `RealmObject` subclasses used in our unit tests and set the `IntegrationTest.XamarinIOS` project to full linking - that was enough to reproduce the error.

A possible complication is that the matching by name, regardless of framework, has been broken in the past and looks like it may be something they regress to occasionally, see Xamarin bugs [26571](https://bugzilla.xamarin.com/show_bug.cgi?id=29571) and [28389](https://bugzilla.xamarin.com/show_bug.cgi?id=28389).

Note that the [Android Linking guide](https://developer.xamarin.com/guides/android/advanced_topics/linking/)  says

_If you do not want to take a dependency on the Xamarin libraries – for example, you are building a cross platform portable class library (PCL) – you can still use the Android.Runtime.Preserve attribute. To do this, declare a PreserveAttribute class within the Android.Runtime namespace_

That is **contrary** to the [IOS Linking Docs](https://developer.xamarin.com/guides/ios/advanced_topics/linker/) _It does not really matter in which namespace this is defined, the linker looks this attribute by type name._
