### ISSUE TITLE
Create ObjectSchema programmatically

### ISSUE THREAD

**Issue by remaerd** [realm/realm-dotnet#824]
#### Goal
I'm creating an app which the user defines database schema. With Core Data, I can create NSManagedModel programmatically. But Xamarin Realm do not have a similar solution. All ObjectSchema are created from RealmObject subclasses. And the initalize method of ObjectSchema is private method.

I found out Realm in Java can create Schema programmatically. Is there any plan these methods will port to Realm for Xamarin in future?

#### Expected Results
> Create ObjectSchema programmatically.

#### Actual Results
>  E.g. full stack trace with exception

#### Steps & Code to Reproduce
> Describe your current debugging efforts.

#### Code Sample
```csharp
> Your code here. Bigger samples should ideally be as separate Xamarin/Visual Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ?

Xamarin/Visual Studio version: ?

Which operating system version and device: ?

**Comment by AndyDentFree** [comment]
This will be provided **soon** by opening up our new dynamic schema classes to be public. Most of the work is done but only tested in the context of using them for migrations, which is about to be released in version 0.78.0.

The remaining work will probably be in a minor release shortly after 0.78.0.

Closing this issue - please see #778 for further comments.

**Comment by AndyDentFree** [comment]
This is not the same as #778 because that just allows you to open an **existing** Realm

**Comment by remaerd** [comment]
@AndyDentFree The `DynamicRealmObject` Class still remains internal in 0.78.1. Is there a plan to make them public in future release? [Dynamic Realms](https://realm.io/docs/java/latest/#dynamic-realms) from Java looks fine.

**Comment by miz-online** [comment]
Are there plans to do this? This is a real showstopper replacing SQLite even without sync. A feature like java Dynamic Realm would be very helpful

**Comment by nirinchev** [comment]
There are definitely plans to do it, although we can't commit to a specific timeframe. It's fairly high on our priority list, so using Blizzard's time terminology, I'd say you can expect it [Very Soon™](http://wowwiki.wikia.com/wiki/Soon#Very_Soon).

**Comment by cmcnicholas** [comment]
Has there been any progress on this issue? Even any plans made about when it might even begin to be looked at? From rigourously testing subquery performance and querying properties directly on the objects being requested the performance difference is an order of magnitude faster at least. I would very much like to, during our initial sync (20k parent objects, 300k child objects spread across those parents) dynamically create the schema to roll the children into the parent object (they are simply key value but I don't know the key values ahead of compilation time)
