### ISSUE TITLE
No properties exception (has linker stripped it?)

### ISSUE THREAD

**Issue by allbdeveloper** [realm/realm-dotnet#829]
#### Steps & Code to Reproduce

> Describe your current debugging efforts.

I know this is known exception but I can't find solution.

1. I have been using realm for long time. It works great.

2. I have a plugin that I have been using from nuget Package. It's "Ble plugin "
https://github.com/xabre/xamarin-bluetooth-le/

3. I removed ble nuget package because I want to download from github and use it.

4. removed package and added project from downloaded source code.

5. problem here. 
"No properties in Baby, has linker stripped it? See https://realm.io/docs/xamarin/latest/#linker-stripped-schema"
when I meet Realm.GetInstance().

I tried using config like

			var config = new RealmConfiguration("myconf");
			config.ObjectClasses = new Type[] { typeof(Baby), typeof(User), typeof(Noti) };
			Realm.GetInstance(config).Write(() =>

but it's not working.
same result.

How to solve this problem? 
Of course I read your guide for this, but I can't understand and can not solve my problem.

#### Version of Realm and tooling
Realm version(s): ? 0.77.2

Xamarin/Visual Studio version: ?
6.0

Which operating system version and device: ?
iOS / Android both

**Comment by allbdeveloper** [comment]
Project link option is set to "Don't link" already.

**Comment by allbdeveloper** [comment]
Strange! I made plain sample app and added only those two library.
Nothing happened.

**Comment by allbdeveloper** [comment]
I created plain sample pcl app and added those two package(realm and ble plugin).
and Nothing happened. 
Other thing might cause the problem....

**Comment by AndyDentFree** [comment]
Can you please send a copy of the project to support@realm.io for me to look at more closely.

Glad to see at least the exception message helped you get to what should have been the right documentation - when we had this problem occur before it resulted in a build that just crashed.
(I know that may not make you feel better right now ;-)

It does seem that your linker settings are OK and more that other things are interfering. If you have other stuff installed that uses the Fody weaver, it may interfere with our weaver being run. This is something we have run into a couple of times but is very hard to diagnose without full projects - if it is a side effect of how the entire project is built.

Thanks for being professional and taking the time to cross-check with your sample project!

**Comment by allbdeveloper** [comment]
Thanks for your kind answer. 

I'm so sorry because I don't think I can send my project. 
It's about to launch.. 

another try. 

1. I made sample project and added realm nuGet and BLE plugin(source library)

2. Added all other package same with my original project. 

3. Build OK.

4. I copy all the source code from my original project with hope. 

5. Unfortunately, after I copied all the source code and success build but same Exception fired. 

Can you give me workaround solution or hint that you found so far?

**Comment by allbdeveloper** [comment]
![screen shot 2016-09-10 at 1 49 50 pm](https://cloud.githubusercontent.com/assets/14910356/18413419/7bf4ca28-77e2-11e6-9bae-34d903e8e5a7.png)
![screen shot 2016-09-10 at 1 49 45 pm](https://cloud.githubusercontent.com/assets/14910356/18413420/83117de2-77e2-11e6-8ae6-424ab29f4e86.png)
![screen shot 2016-09-10 at 1 49 41 pm](https://cloud.githubusercontent.com/assets/14910356/18413421/896e3cca-77e2-11e6-9e57-4891ea3bcc19.png)

**Comment by allbdeveloper** [comment]
Can you see if there is any package that might cause problem?

**Comment by AndyDentFree** [comment]
Please post the content of your `FodyWeavers.xml` file - that tells us which weavers are being used and is more likely to indicate what causes clashes.

If there are other weavers being run after or before `<RealmWeaver/>` try re-arranging their order.

There is a known issue with our nuget install which adds a new `<RealmWeaver/>` entry each time you update, which we don't think causes any problems but it if you have multiples you can safely trim that back to just one.

**Comment by allbdeveloper** [comment]
Hi Andy. Thanks for reply.
I appreciate.

<?xml version="1.0" encoding="utf-8"?>
<Weavers>
	<RealmWeaver/>
  
</Weavers>

This is my FodyWeavers.xml

forms, android, ios all same.

**Comment by AndyDentFree** [comment]
OK, the fact that there is **no** `<RealmWeaver/>` entry in there means the NuGet installation went wrong.

Easiest would be to try removing the Realm nuget, and try adding it again. Please try that and see if there are any errors reported in the _Package Console_.

You can also add entries by hand, which is easiest to work out by taking a simple project, saving a copy and then using NuGet to add Realm, so you can compare the changes.

Your project should end up with several things added, eg: for IOS:

```xml
    <Reference Include="Realm">
      <HintPath>..\packages\Realm.0.77.2\lib\Xamarin.iOS10\Realm.dll</HintPath>
    </Reference>
....
  <Import Project="..\packages\Realm.0.78.0\build\Realm.targets" Condition="Exists('..\packages\Realm.0.78.0\build\Realm.targets')" />

```

**Comment by allbdeveloper** [comment]
I did but nothing special. 

============remove realm and adding again (forms)==========
Adding Realm...
Attempting to resolve dependency 'Fody (≥ 1.29.4)'.
Attempting to resolve dependency 'DotNetCross.Memory.Unsafe (≥ 0.2.2)'.
Adding 'Realm 0.77.2' to allbX1.
For adding package 'Realm 0.77.2' to project 'allbX1' that targets 'portable-net45+win+wp80+MonoTouch10+MonoAndroid10+xamarinmac20+xamarintvos10+xamarinwatchos10+xamarinios10',
>> Assembly references are being added from 'lib/portable-net45+sl5+wp8+wpa81+win8+monoandroid+Xamarin.iOS10+monotouch+Xamarin.Mac'
>> Content files are being added from 'content' (not framework-specific)
>> Build files are being added from 'build' (not framework-specific)
Added file 'FodyWeavers.xml'.
Added reference 'Realm' to project 'allbX1'.
Added file 'packages.config'.
Added file 'packages.config' to project 'allbX1'.
Successfully added 'Realm 0.77.2' to allbX1.


Realm successfully added.


====================ios=========================
Adding Realm...
Attempting to resolve dependency 'Fody (≥ 1.29.4)'.
Attempting to resolve dependency 'DotNetCross.Memory.Unsafe (≥ 0.2.2)'.
Adding 'Realm 0.77.2' to allbX1.iOS.
For adding package 'Realm 0.77.2' to project 'allbX1.iOS' that targets 'xamarinios10',
>> Assembly references are being added from 'lib/Xamarin.iOS10'
>> Content files are being added from 'content' (not framework-specific)
>> Build files are being added from 'build' (not framework-specific)
Added file 'FodyWeavers.xml'.
Added reference 'Realm' to project 'allbX1.iOS'.
Added file 'packages.config'.
Added file 'packages.config' to project 'allbX1.iOS'.
Successfully added 'Realm 0.77.2' to allbX1.iOS.


Realm successfully added.

**Comment by allbdeveloper** [comment]
my FodyWeavers.xml file was and is like that from very first time.
I thought that's natural.

**Comment by AndyDentFree** [comment]
The blank FodyWeavers.xml is created and added to your project if you just install the Fody nuget by itself.

During installation of the Realm nuget, because it depends on Fody, it first runs the Fody nuget so adds Fody to the project and produces that _blank_ FodyWeavers.xml.

It then runs a transformation step which is supposed to add the `<RealmWeaver/>` line.

Our [Installation Docs](https://realm.io/docs/xamarin/latest/#installation) show an example what FodyWeavers.xml should look like.

Because multiple steps are involved, it sounds as though something went wrong after the Fody portion of the NuGet installation.

**Comment by allbdeveloper** [comment]
hm.. 
The FodyWeavers.xml file I attached above, is same as example in docs.
As you can see there **is** \<RealmWeaver/>line.
And you answered after saw my file, "there is no realmweaver entry".
If you don't mind I want to make sure you did see my FodyWeavers.xml file correctly.

**Comment by AndyDentFree** [comment]
Sorry for the confusion, for some weird reason I saw your FodyWeavers.xml as blank without any `<RealmWeaver/>` entry, in the issue. I have no idea what happened in github.

OK, now that is sorted, it seems we are the only thing using Fody.

I have found some advice that *might* help - there's [apparently](https://github.com/Fody/Fody/issues/137) a clash with a task inserted by `Microsoft.BCL`.

[This SO question](http://stackoverflow.com/questions/25794350/xamarin-studio-build-targets-trying-to-get-fody-working/26110785#26110785) has a solution: _remove the build\Microsoft.Bcl.Build.targets from the csproj file_

`<Import Project="..\..\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.targets" Condition="Exists('..\..\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.targets')" />`

This is reportedly safe to do and causes the clash with Fody, so please try it.

**Comment by allbdeveloper** [comment]
I modified it after around 10 seconds because it went blank. 
Wow.. maybe you saw that in that time. I'm sorry too.
Appreciate about all. I will try it.

**Comment by AndyDentFree** [comment]
Just to be clear, I am now waiting for your report on what happens if you remove `Microsoft.Bcl.Build.targets` as [I mentioned yesterday](https://github.com/realm/realm-dotnet/issues/829#issuecomment-246179024)

**Comment by allbdeveloper** [comment]
Hi, Andy sorry for late response. 

I couldn't remove it with using "remove package" because the other packages depend on it. 
But I could remove that line as you mentioned. (on forms side)

And now it works. ;;
It's still on my package list on forms though, 
But the problem is gone currently.

I really appreciate your help and respect how carefully you're developing it.. (even though the other could cause problem)

**Comment by AndyDentFree** [comment]
We have accepted that there is a regular clash with that `BCL.build.targets` entry so it is now [part of the FAQ](https://realm.io/docs/xamarin/latest/#failed-to-weave)

**Comment by allbdeveloper** [comment]
I really appreciate your help Andy.

**Comment by chuongxl** [comment]
I got the same issue and resolved by adding " <RealmWeaver/>" into FodyWeaver.xml

**Comment by danieltabarest** [comment]
I resolved adding<RealmWeaver/> into FodyWeaver.xml
