### ISSUE TITLE
Fix nupkg creation

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#831]
At some point before 2016-09-09 it seems nuget.org started checking the dates of files in the package and rejecting because they had future dates. 

 Kristian said he has been manually  fixing dates, so it is not a recent issue.

Possible cause: 
[nuget pack zip file issue between Mono versus Windows](https://github.com/NuGet/Home/issues/2833)

A fix may be to update our nuget version on Jenkins as [this thread](https://github.com/NuGet/Home/issues/624) seems to suggest it is a known issue that is fixed (or it is something that comes up regularly).

Otherwise, add a sequence like the following at the end of our ci:

```
unzip Realm.0.78.0.nupkg -d Realm.0.78.0
cd Realm.0.78.0
find . -exec touch {} \;
zip -r Realm.0.78.0.nupkg .
```

**Comment by AndyDentFree** [comment]
When this is done, correct the [Release wiki](https://github.com/realm/realm-wiki/wiki/Releasing-Realm-Xamarin)

**Comment by kristiandupont** [comment]
I've uploaded a new NuGet.exe into /usr/bin/local. I tried referencing from the script, but it caused some problem with a config.xml. I reverted it to not break it.

**Comment by nirinchev** [comment]
Didn't face any issues when releasing 0.80.0, so I guess we can close that now.
