### ISSUE TITLE
Realm 0.78.0 crash on writing Nullable DateTimeOffset

### ISSUE THREAD

**Issue by MarcMenghin** [realm/realm-dotnet#833]
#### Goal

> Update to Realm 0.78.0

#### Expected Results

> Same code works (except change from ObjectId to PrimaryKey)

#### Actual Results

```
09-12 12:01:46.413 D/Mono    (31082): DllImport searching in: 'wrappers' ('libwrappers.so').
09-12 12:01:46.413 D/Mono    (31082): Searching for 'shared_realm_begin_transaction'.
09-12 12:01:46.413 D/Mono    (31082): Probing 'shared_realm_begin_transaction'.
09-12 12:01:46.413 D/Mono    (31082): Found as 'shared_realm_begin_transaction'.
09-12 12:01:46.413 D/Mono    (31082): DllImport searching in: 'wrappers' ('libwrappers.so').
09-12 12:01:46.413 D/Mono    (31082): Searching for 'row_for_string_primarykey'.
09-12 12:01:46.413 D/Mono    (31082): Probing 'row_for_string_primarykey'.
09-12 12:01:46.413 D/Mono    (31082): Found as 'row_for_string_primarykey'.
09-12 12:01:46.453 D/Mono    (31082): DllImport searching in: 'wrappers' ('libwrappers.so').
09-12 12:01:46.453 D/Mono    (31082): Searching for 'shared_realm_is_in_transaction'.
09-12 12:01:46.453 D/Mono    (31082): Probing 'shared_realm_is_in_transaction'.
09-12 12:01:46.453 D/Mono    (31082): Found as 'shared_realm_is_in_transaction'.
09-12 12:01:46.453 D/Mono    (31082): DllImport searching in: 'wrappers' ('libwrappers.so').
09-12 12:01:46.453 D/Mono    (31082): Searching for 'row_get_row_index'.
09-12 12:01:46.453 D/Mono    (31082): Probing 'row_get_row_index'.
09-12 12:01:46.453 D/Mono    (31082): Found as 'row_get_row_index'.
09-12 12:01:46.463 E/mono-rt (31082): Stacktrace:
09-12 12:01:46.463 E/mono-rt (31082): 
09-12 12:01:46.463 E/mono-rt (31082):   at <unknown> <0xffffffff>
09-12 12:01:46.463 E/mono-rt (31082):   at (wrapper managed-to-native) Realms.RowHandle/NativeMethods.get_row_index (Realms.RowHandle,Realms.NativeException&) <0x0003b>
09-12 12:01:46.463 E/mono-rt (31082):   at Realms.RowHandle.get_RowIndex () <IL 0x00003, 0x00083>
09-12 12:01:46.463 E/mono-rt (31082):   at Realms.RealmObject.SetNullableDateTimeOffsetValue (string,System.Nullable`1<System.DateTimeOffset>) <IL 0x0003d, 0x001ab>
09-12 12:01:46.463 E/mono-rt (31082):   at ....Models.CompanyCache.set_LastSynchronized (System.Nullable`1<System.DateTimeOffset>) <IL 0x0000f, 0x0010b>

.. (long stack) ..

09-12 12:01:46.473 E/mono-rt (31082): 
09-12 12:01:46.473 E/mono-rt (31082): Attempting native Android stacktrace:
09-12 12:01:46.473 E/mono-rt (31082): 
09-12 12:01:46.483 E/mono-rt (31082):  at ???+0 [0x9bb89918]
09-12 12:01:46.513 E/mono-rt (31082):  at ???+0 [0x9671ad14]
09-12 12:01:46.523 E/mono-rt (31082): 
09-12 12:01:46.523 E/mono-rt (31082): =================================================================
09-12 12:01:46.523 E/mono-rt (31082): Got a SIGSEGV while executing native code. This usually indicates
09-12 12:01:46.523 E/mono-rt (31082): a fatal error in the mono runtime or one of the native libraries 
09-12 12:01:46.523 E/mono-rt (31082): used by your application.
09-12 12:01:46.523 E/mono-rt (31082): =================================================================
09-12 12:01:46.523 E/mono-rt (31082): 
09-12 12:01:46.523 F/libc    (31082): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 31157 (Thread-13296)
09-12 12:01:46.523 W/libc    (31082): Security Level: (1), Debug inforamtion is controlled by the DUMPABLE flag.

```

#### Steps & Code to Reproduce

> Update to Realm 0.78.0 and set a Nullable property

#### Version of Realm and tooling
Realm version(s): 0.78.0

Xamarin/Visual Studio version: current Stable Xamarin (newest CYCLE 7 release) / VS 2015 Update 3

Which operating system version and device: Android (Testdevice running 5.0.2)

#### Notes
New install of App, no preexisting realm on device. Happens on first element written to Realm.

**Comment by AndyDentFree** [comment]
Sorry, I will need more details to replicate this. Can you please either attach a relevant code snippet, including your class declaration, or send a copy to support@realm.io for me to build.

I have just been through a cycle of building an app using the NuGet Realm 0.77.2 with a `DateTimeOffset?` property and an `ObjectId` then updating it to 0.78.0 without problems, including updating an object created in one.

Versions prior to 0.78.0 did not properly enforce the `ObjectId` unique property but if you had written duplicate records, that would result in an exception rather than a crash (I tested that scenario).

**Comment by MarcMenghin** [comment]
Did further investigate the problem and got it to work with Realm 0.78.0. I made the following observations:

- Updating to Realm 0.78.0 does work fine with the stated changes (changing ObjectId to PrimaryKey)
- I map properties from application objects to data objects using Automapper and forgot to ignore the Id Field (has the PrimaryKey attribute). This did work fine with Realm 0.77.2 and it's the same Id so i didn't actually change the Id just re-set it to the same value. (fixed this now)
- I did change my repository.get(string id) method to use the new `ObjectForPrimaryKey` which seems the culprid that causes the exception above.

Following code snipped illustrates the application logic:

```
 public class Repository<TDataType, TDataTypeCache>
        where TDataType : IGuidModel
        where TDataTypeCache : RealmObject, IIdModel, new()
    {

        public void WriteData(Realm realm, params TDataType[] elements)
        {
            using (var transaction = realm.BeginWrite())
            {
                foreach (var element in elements)
                {
                    CreateOrUpdate(realm, element);
                }

                transaction.Commit();
            }

        }

        public TDataTypeCache CreateOrUpdate(Realm realm, TDataType element)
        {
            if (element == null)
            {
                return null;
            }

            var idStr = element.Id.ToString();

            //crashes:
            var dbElement = realm.ObjectForPrimaryKey<TDataTypeCache>(idStr);

            //works fine:
            //var dbElement = realm.All<TDataTypeCache>().Where(model => model.Id == idStr).ToList().SingleOrDefault();

            if (dbElement == null)
            {
                dbElement = Activator.CreateInstance<TDataTypeCache>();
                dbElement.Id = idStr;
                realm.Manage(dbElement);
            }
            Mapper.Map(element, dbElement);

            return dbElement;
        }
    }

  public interface IGuidModel
    {
        Guid Id { get; set; }
    }

 public interface IIdModel
    {
        string Id { get; set; }
    }
```

A few additional notes:

- Automapper is setup to ignore all reference objects
- more complex objects with references call the generic method first and then add the object specific references by using the same workflow for the referenced object (but there is just one transaction over everything)

For complex objects it looks like this:

```
public FooComplexCache CreateOrUpdate(Realm realm, FooComplex fooComplex)
{
  if (fooComplex == null)
  {
    return null;
  }

  var dbElement = Repository<FooComplex, FooComplexCache>.CreateOrUpdate(realm, fooComplex);

  foreach (var reference in fooComplex.References)
  {
    var dbReference = Repository<Foo, FooCache>.CreateOrUpdate(realm, reference);
    if (!dbElement.References.Contains(dbReference))
    {
      dbElement.References.Add(dbReference);
    }
  }

  return dbElement;
}

```

**Comment by AndyDentFree** [comment]
I think the problem is your `CreateOrUpdate` invoking `ObjectForPrimaryKey<TDataTypeCache>`

You can [see the code](https://github.com/realm/realm-dotnet/blob/828bffd8c5e83416a2d374ca8887595da4e62655/Realm.Shared/Realm.cs#L711) 

```
public T ObjectForPrimaryKey<T>(string id) where T : RealmObject
{
    var metadata = Metadata[typeof(T).Name];
    var rowPtr = NativeTable.RowForPrimaryKey(metadata.Table, metadata.PrimaryKeyColumnIndex, id);
    return (T)MakeObjectForRow(metadata, rowPtr);
}
```

This needs better protection to ensure that the type `T` it uses is a concrete class but I am rather puzzled as to how the `Metadata` access worked without just throwing an exception, as it is [defined](https://github.com/realm/realm-dotnet/blob/828bffd8c5e83416a2d374ca8887595da4e62655/Realm.Shared/Realm.cs#L156) as just a `Dictionary<string, RealmObject.Metadata>`.

That suggests something interesting happened to generate an entry in there.

A quick solution might be if you can pass in or derive the string name of the actual class being used, rather than just the abstraction. Then you can use the overload `ObjectForPrimaryKey(string className, string id)` which is part of our more dynamic API.

I am also building a more complex test case to see what else is happening here, based on your snippet.

**Comment by AndyDentFree** [comment]
As my colleague @kristiandupont just pointed out, the fact that the `All<TDataTypeCache>` works fine somewhat contradicts my theory.

Note that as o 0.78.0 you can condense:

`realm.All<TDataTypeCache>().Where(model => model.Id == idStr).ToList().SingleOrDefault();`

to just

`realm.All<TDataTypeCache>().SingleOrDefault(model => model.Id == idStr);`

**Comment by MarcMenghin** [comment]
I do use the concrete Types as the generic parameters. No abstract types are used. So TDataTypeCache should always be the correct concrete type.

**Comment by AndyDentFree** [comment]
Can you please include a class declaration for one of those concrete types that are causing problems.

**Comment by MarcMenghin** [comment]
This are the objects first written to the realm. Where it is one CompanyCache instance and about 5 FooCache. It never gets to commiting the transaction.

```
internal sealed class CompanyCache : RealmObject, ICacheModel
    {
        [PrimaryKey]
        public string Id { get; set; }

        public string Name { get; set; }

        public IList<FooCache> Foo { get; }

        public DateTimeOffset LastModified { get; set; }

        public DateTimeOffset? LastSynchronized { get; set; }

        public override string ToString()
        {
            return $"{this.GetType().Name} ({Id})";
        }

        private bool Equals(CompanyCache other)
        {
            return base.Equals(other) && string.Equals(Id, other.Id);
        }

        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj is CompanyCache && Equals((CompanyCache) obj);
        }

        public override int GetHashCode()
        {
            return (Id != null ? Id.GetHashCode() : 0);
        }
    }

 internal sealed class FooCache : RealmObject, ICacheModel
    {
        [PrimaryKey]
        public string Id { get; set; }

        public string Name { get; set; }

        public DateTimeOffset? ArchivedOn { get; set; }

        public DateTimeOffset LastModified { get; set; }

        public DateTimeOffset? LastSynchronized { get; set; }

        public override string ToString()
        {
            return $"{this.GetType().Name} ({Id})";
        }

        private bool Equals(FooCache other)
        {
            return base.Equals(other) && string.Equals(Id, other.Id);
        }

        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj is FooCache && Equals((FooCache) obj);
        }

        public override int GetHashCode()
        {
            return (Id != null ? Id.GetHashCode() : 0);
        }
    }
```

**Comment by AndyDentFree** [comment]
Mostly a note for self (it is late here in Oz) - I have a dark suspicion this crash has the same root cause as #723 - using an expression that ends up getting a column index for the wrong table. In this case it is due to the way the generics are working out, rather than relationships. However, that still doesn't explain what makes `All` work instead of `ObjectForPrimaryKey`. 

Attempting to build a cut-down but similar solution in a unit test  works fine so it maybe needs two levels of interfaces.

@ MarcMenghin can you please supply the declaration of `ICacheModel` and clarify how `  var dbElement = Repository<FooComplex, FooComplexCache>.CreateOrUpdate(realm, fooComplex);` compiles because it seems to need a static method to me.

**Comment by eyadon** [comment]
Here's some more data for you, Andy -- I am seeing the same issue when trying to update our app to use `ObjectForPrimaryKey`. Clean install, no existing data. The app exits without exception when it hits the first `ObjectForPrimaryKey` call, stacktrace below and code attached. 
Realm 0.78.0
Xamarin Forms 2.3.1.114

[CachedProperty.txt](https://github.com/realm/realm-dotnet/files/470538/CachedProperty.txt)

> 
> 09-13 13:13:08.806 D/Mono    (13786): Searching for 'row_for_string_primarykey'.
> 09-13 13:13:08.806 D/Mono    (13786): Probing 'row_for_string_primarykey'.
> 09-13 13:13:08.806 D/Mono    (13786): Found as 'row_for_string_primarykey'.
> 09-13 13:13:08.816 E/mono-rt (13786): Stacktrace:
> 09-13 13:13:08.816 E/mono-rt (13786): 
> 09-13 13:13:08.816 E/mono-rt (13786):   at <unknown> <0xffffffff>
> 09-13 13:13:08.816 E/mono-rt (13786):   at (wrapper managed-to-native) Realms.RowHandle/NativeMethods.get_row_index (Realms.RowHandle,Realms.NativeException&) <0x00007>
> 09-13 13:13:08.816 E/mono-rt (13786):   at Realms.RowHandle.get_RowIndex () <IL 0x00003, 0x00077>
> 09-13 13:13:08.816 E/mono-rt (13786):   at Realms.RealmObject.SetStringValue (string,string) <IL 0x0003d, 0x0017f>
> 09-13 13:13:08.816 E/mono-rt (13786):   at Testing.Core.CachedProperty.set_Value (string) <IL 0x0000f, 0x0006f>
> 09-13 13:13:08.816 E/mono-rt (13786):   at Testing.Core.CachedProperty/<>c__DisplayClass11_0.<SetMultipleProperties>b__0 () [0x00001] in C:\Users\Me\Source\Repos\AppName\Testing.Core\CachedProperty.cs:70
> 09-13 13:13:08.816 E/mono-rt (13786):   at Realms.Realm.Write (System.Action) <IL 0x00008, 0x000a7>
> 09-13 13:13:08.816 E/mono-rt (13786):   at Testing.Core.CachedProperty.SetMultipleProperties (System.Collections.Generic.IEnumerable`1<Testing.Core.CachedProperty>) [0x00087] in C:\Users\Me\Source\Repos\AppName\Testing.Core\CachedProperty.cs:68
> 09-13 13:13:08.816 E/mono-rt (13786):   at Testing.Core.Location.LocationService/<SaveCurrentLocationToDevice>d__34.MoveNext () [0x0004a] in C:\Users\Me\Source\Repos\AppName\Testing.Core\Location\LocationService.cs:138
> 09-13 13:13:08.816 E/mono-rt (13786):   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<TStateMachine_REF> (TStateMachine_REF&) [0x00031] in /Users/builder/data/lanes/3540/1cf254db/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:316
> 09-13 13:13:08.816 E/mono-rt (13786):   at Testing.Core.Location.LocationService.SaveCurrentLocationToDevice () <IL 0x0002a, 0x001cb>
> 09-13 13:13:08.816 E/mono-rt (13786):   at Testing.Core.Location.LocationService/<OnLocationUpdate>d__39.MoveNext () [0x00298] in C:\Users\Me\Source\Repos\AppName\Testing.Core\Location\LocationService.cs:227
> 09-13 13:13:08.816 E/mono-rt (13786):   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<TStateMachine_REF> (TStateMachine_REF&) [0x00031] in /Users/builder/data/lanes/3540/1cf254db/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:316
> 09-13 13:13:08.816 E/mono-rt (13786):   at Testing.Core.Location.LocationService.OnLocationUpdate (Testing.Shared.Location.Models.LocationPosition) <IL 0x00031, 0x001f7>
> 09-13 13:13:08.816 E/mono-rt (13786):   at Testing.Core.Location.LocationService/<<SubsrcibeToMessages>b__38_0>d.MoveNext () [0x0000e] in C:\Users\Me\Source\Repos\AppName\Testing.Core\Location\LocationService.cs:176
> 09-13 13:13:08.816 E/mono-rt (13786):   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start<TStateMachine_REF> (TStateMachine_REF&) [0x00031] in /Users/builder/data/lanes/3540/1cf254db/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:84
> 09-13 13:13:08.816 E/mono-rt (13786):   at Testing.Core.Location.LocationService.<SubsrcibeToMessages>b__38_0 (Testing.Shared.Location.ILocation,Testing.Shared.Location.Models.LocationPosition) <IL 0x00038, 0x00257>
> 09-13 13:13:08.816 E/mono-rt (13786):   at Xamarin.Forms.MessagingCenter/<>c__DisplayClass3_0`2<TSender_REF, TArgs_REF>.<Subscribe>b__0 (object,object) [0x00027] in C:\BuildAgent\work\aad494dc9bc9783\Xamarin.Forms.Core\MessagingCenter.cs:37
> 09-13 13:13:08.816 E/mono-rt (13786):   at Xamarin.Forms.MessagingCenter.InnerSend (string,System.Type,System.Type,object,object) [0x00069] in C:\BuildAgent\work\aad494dc9bc9783\Xamarin.Forms.Core\MessagingCenter.cs:95
> 09-13 13:13:08.816 E/mono-rt (13786):   at Xamarin.Forms.MessagingCenter.Send<TSender_REF, TArgs_REF> (TSender_REF,string,TArgs_REF) [0x00013] in C:\BuildAgent\work\aad494dc9bc9783\Xamarin.Forms.Core\MessagingCenter.cs:16
> 09-13 13:13:08.816 E/mono-rt (13786):   at Testing.Shared.Location.Location._Locator_PositionChanged (object,Plugin.Geolocator.Abstractions.PositionEventArgs) [0x0000e] in C:\Users\Me\Source\Repos\AppName\Testing.Shared\Location\Location.cs:84
> 09-13 13:13:08.816 E/mono-rt (13786):   at Plugin.Geolocator.GeolocatorImplementation.OnListenerPositionChanged (object,Plugin.Geolocator.Abstractions.PositionEventArgs) [0x00030] in C:\projects\xamarin-plugins\Geolocator\Geolocator\Geolocator.Plugin.Android\GeolocatorImplementation.cs:282
> 09-13 13:13:08.816 E/mono-rt (13786):   at Plugin.Geolocator.GeolocationContinuousListener.OnLocationChanged (Android.Locations.Location) [0x0014e] in C:\projects\xamarin-plugins\Geolocator\Geolocator\Geolocator.Plugin.Android\GeolocationContinuousListener.cs:86
> 09-13 13:13:08.816 E/mono-rt (13786):   at Android.Locations.ILocationListenerInvoker.n_OnLocationChanged_Landroid_location_Location_ (intptr,intptr,intptr) [0x00011] in /Users/builder/data/lanes/3540/1cf254db/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.Locations.ILocationListener.cs:94
> 09-13 13:13:08.816 E/mono-rt (13786):   at (wrapper dynamic-method) object.632cebcd-9510-4457-b6da-96a016407e07 (intptr,intptr,intptr) <IL 0x00017, 0x00027>
> 09-13 13:13:08.816 E/mono-rt (13786):   at (wrapper native-to-managed) object.632cebcd-9510-4457-b6da-96a016407e07 (intptr,intptr,intptr) <IL 0x0001f, 0x0008f>
> 09-13 13:13:08.816 E/mono-rt (13786): 
> 09-13 13:13:08.816 E/mono-rt (13786): Attempting native Android stacktrace:
> 09-13 13:13:08.816 E/mono-rt (13786):

**Comment by AndyDentFree** [comment]
Looking at this thread later, it is not hugely obvious that the fix was a fix to a simple, stupid bug in my first implementation of `ObjectForPrimaryKey` - it was not correctly retuning `null` when the object was not found. 

I thought I'd add this comment in case someone wondered how the fix worked.
