### ISSUE TITLE
RealmConfiguration documentation page missing

### ISSUE THREAD

**Issue by grahampett** [realm/realm-dotnet#837]
Clicking on "RealmConfiguration" link in Realm Xamarin documentation gives a page not found error. Appears to be missing page rather than single broken link as various links to it I tried all didn't work. Documentation v0.78.0

**Comment by AndyDentFree** [comment]
Thanks, forwarded to our docs team - we have an intermittent problem with our content system doing something weird with that page.

In the meantime, the [0.77.1 version](https://realm.io/docs/xamarin/0.77.1/api/class_realms_1_1_realm_configuration.html) is fine and there were no changes in 0.78.0 to that class.

**Comment by AndyDentFree** [comment]
Fixed (with manual intervention) - docs are available but we **do** have a weird ongoing problem.
