### ISSUE TITLE
Upgrade Core Version

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#846]
Internal file format change but should be no C# changes required.

**Comment by sisterray** [comment]
Hi,

How would someone upgrade an existing application if the older databases cannot be opened after this bug has been applied. This is a problem if an application has lots of users with local data stored in their realm database on their mobile device.

Is there a migration strategy to cater for this case?

**Comment by fealebenpae** [comment]
Hey @sisterray,

Realm should automatically update older realm files to the new version of the file format when they're first opened.

**Comment by sisterray** [comment]
That's good to know @fealebenpae I think we are on 0.77.1. Hopefully an upgrade to 0.80 will work. I'll give it a try ASAP

Thanks
