### ISSUE TITLE
Image and documentation text different

### ISSUE THREAD

**Issue by ersin-ertan** [realm/realm-dotnet#848]
#### Goal

Image to be updated
#### Expected Results

ream is changed to to realm

#### Actual Results

ream

#### Steps & Code to Reproduce

https://realm.io/assets/img/docs/ros-rmp/RealmBrowser-Conect-To-Object-Server.png

#### Version
Website

**Comment by AndyDentFree** [comment]
Thanks for logging this, it has already been logged as an internal documentation issue and fixed.
