### ISSUE TITLE
Xamarin Realm ObjectForPrimaryKey Failing

### ISSUE THREAD

**Issue by barrysohl** [realm/realm-dotnet#849]
I have a Xamarin Forms project using Realm (Shared Project, latest Nuget). I have a RealmObject "Organization" that has a [PrimaryKey] on a string property called "UniqueId", which is a string GUID. No matter what I do, calling ObjectForPrimaryKey<Organization>( someUniqueId ) fails with a SystemEntryPointNotFoundException 'row_for_string_primarykey'.

I thought maybe it was config related, or thread related. But if I use the exact same realm instance, in the exact same location of code and run a LINQ query on the exact same object with exact same uniqueId, it finds the object no problem. What am I doing wrong?

Exception:
System.EntryPointNotFoundException: row_for_string_primarykey
  at at (wrapper managed-to-native) UIKit.UIApplication:UIApplicationMain (int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Users/builder/data/lanes/3818/3983064a/source/xamarin-macios/src/UIKit/UIApplication.cs:79
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x00038] in /Users/builder/data/lanes/3818/3983064a/source/xamarin-macios/src/UIKit/UIApplication.cs:63
  at DXLibTest.iOS.Application.Main (System.String[] args) [0x00008] in /Users/bsohl/Projects/DXLibTest/iOS/Main.cs:17

This fails:
var org = realm.ObjectForPrimaryKey<Organization>( cac6aab8-1a43-465f-8bc9-3c7af64a9581 );

This works:
var orgs = realm.All<Organization>().Where( org => org.UniqueId == "cac6aab8-1a43-465f-8bc9-3c7af64a9581" );

Primary key is defined as such:
[PrimaryKey]
public string UniqueId { get; set; }

Realm browser shows the row with the correct UniqueId.

Please help! I am loving Realm so far, but am completely stumped on this.

Thanks,
-Barry Sohl
barrysohl@demivision.com

**Comment by barrysohl** [comment]
OK, more info. It looks like it works if the ObjectForPrimaryKey call is inside a Write transaction. So at least I have a workaround for now. But surely this can't be intended behavior? And why would it matter (especially when the identical LINQ query works fine)?

**Comment by AndyDentFree** [comment]
Hi Barry. ObjectForPrimaryKey uses a completely parallel mechanism to LINQ both at the outside C# level (bypassing all the LINQ assembly and parsing of an AST) and a more optimal search inside the Realm core. 

The general search used by LINQ is designed to return a **list** of values. Searching directly for a single primary key is an optimal pathway.

The call `row_for_string_primarykey` is the C++ call being used from C# and is only used in the `ObjectForPrimaryKey` calls with a string key. There's a similar call for int keys.

I would have thought that this pointed to something strange about linking. It seems that the DLL doesn't contain that entry point.

You have now thoroughly confused and alarmed me with your added info:

>it works if the ObjectForPrimaryKey call is inside a Write transaction

I am struggling to see how that can be a related factor unless it is still somehow affecting linking.

Things to try/confirm:

1. Does this occur on Android, iOS Device, iOS Simulator or all?
1. Do you have your linker settings on Link All?

**Comment by barrysohl** [comment]
I have changed so many settings and so forth in the meantime, it is unfortunately hard for me to know for sure exactly what my full state was at the time. I know that I had to change the “Link All” setting because I was having other Realm issues related to that. I believe I was using “Platform SDK only” at the time. I have also delete the entire realm and started fresh since then. And also since changed from Shared to PCLs (because so many other libs require PCL). All I know is that with my current setup, ObjectForPrimaryKey seems to be working correctly now! So I will just chalk that one up to the gremlins.

Overall, I’m loving Realm so far. My only major grip is no inheritance :(  We don’t need full polymorphism, but simple code reuse would be a huge help. All of our data objects have a guid, created/modified/delete timestamps, and some other common fields and related functionality. Every ORM-ish platform we have used in the past, we have always abstracted those out into a parent class, which really cleans up the child classes. Any idea when that will be coming to Realm Xamarin?

Thanks!
-Barry

**Comment by kristiandupont** [comment]
Hm, that is still suspicious. We'll keep an eye out for it, thanks for reporting.

Regarding inheritance, you can keep an eye on #529 which will probably include (or just precede) the ability to use inheritance but unfortunately we can't give a timeline for it at this moment.

**Comment by barrysohl** [comment]
Thanks, I will eagerly follow that thread. A [RealmObject] annotation would definitely be my vote!

-Barry
