### ISSUE TITLE
Revisit the public API and align it with .NET standards

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-dotnet#853]
Currently there are some places where our public API is confusing and not aligned with .NET naming conventions.

Todo:
- [x] Rename `Realm.All` to `GetAll`
- [x] Rename `Realm.ObjectForPrimaryKey` to `Find`
- [x] Rename `Realm.Manage` to `Add`
- [ ] Rename `Realm.RealmChanged` to something
- [x] Rename `RealmConfiguration.ReadOnly` to `IsReadOnly`
- [x] Rename `RealmConfiguration.PathToRealm` to `GetPathToRealm`
- [x] Remove `RealmList.ITEM_NOT_FOUND`
- [x] Rename `RealmResults.NotificationCallback` to `NotificationCallbackDelegate`
- [x] Remove `Realm.Close` - related to #759 
- [ ] Make `RealmList` internal

**Comment by AndyDentFree** [comment]
I favour usable APIs over slavish adherence to ours or .NET standards so would like to see a clear explanation of changes and how they deliver benefit, **especially** if they make names longer.

As far as I know, nobody else has complained about these being confusing.

**Comment by nirinchev** [comment]
The reason we have standards is so that people know what to expect, so adhering to the .NET ones will make the adoption barrier lower, since users will be able to naturally figure out what's going on, based on their previous experience. There are a few areas that could be improved before launching 1.0.

`Realm.All` - method names should be verbs. There are many discussions out there, so not going to reproduce them here, but .NET developers will expect it and there are two very obvious problems here. First, since it's a noun and parameterless method, people will assume it's a property, thus not adding `()` after the invocation and losing time figuring out why is the IDE complaining. Additionally, if they don't know the exact name, they will try to use intellisense to try and find `getXXX` method (since that is the expected verb for getting things) and fail. So renaming it to `GetAll` wouldn't increase the length that much, while fixing the mentioned problems.

`Realm.ObjectForPrimaryKey` - again, method should be verb and it's way more descriptive than the rest of the methods out there - we have `Remove`, `Manage`, and suddenly, it feels like I'm reading Obj-C 😱 Since most of Realm's users will undoubtedly associate it with ORMs, we should capitalize on that and not try to fight it. Since EF is the de-facto standard for .NET ORMs, we could borrow their naming and call it `Find`.

`Realm.Manage` - this is basically an `Add` - why call it otherwise and then spend countless hours figuring out how to name the `AddOrUpdate` method.

`Realm.RealmChanged` - the event name is a little confusing because it implies that something about the Realm itself has changed (e.g. database location, or encryption, etc.), not that the objects it stores have changed. So perhaps we could go with something like `TransactionCommitted` or `SavedChanges` (the latter is more EF-like).

`RealmConfiguration.ReadOnly` should be `IsReadOnly` to be similar to [`FileInfo.IsReadOnly`](https://msdn.microsoft.com/en-us/library/system.io.fileinfo.isreadonly(v=vs.110).aspx).

`RealmConfiguration.PathToRealm` should be a verb - e.g. `GetPathToRealm` or `ConstructPathToRealm`.

`RealmList.ITEM_NOT_FOUND` should not be public (and probably should be removed whatsoever) because it is consistent with the way .NET lists work, so it provides no value, just a possible source of confusion.

`RealmResults.NotificationCallback` should probably be `NotificationCallbackDelegate` for consistency with `RealmConfiguration.MigrationCallbackDelegate`.

`Realm.Close` should be removed in favor of `Realm.Dispose` since Dispose will call `Close` internally. In general, we should avoid providing multiple ways to free resources because it is annoying and confusing to developers and they tend to just write all close methods they can find one after the other.

Finally, those are just concerns I'm voicing from an end-user point of view. Probably there are even better names than what I've proposed, so I'm open for discussion.
