### ISSUE TITLE
Api reference docs incorrectly recognizes expression bodied properties as attributes

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-dotnet#854]
#### Expected Results

Expression bodied properties are documented as properties in the api reference page.
#### Actual Results

They are marked as attributes.
#### Steps & Code to Reproduce

https://realm.io/docs/xamarin/latest/api/class_realms_1_1_realm_object.html

**Comment by AndyDentFree** [comment]
Already logged as [Doxygen bug 771283](https://bugzilla.gnome.org/show_bug.cgi?id=771283)
