### ISSUE TITLE
Crash on X86 android

### ISSUE THREAD

**Issue by kristiandupont** [realm/realm-dotnet#859]
`NotificationTests.CollectionChangedAdapter_DeletingItemFromRealm_ShouldRaiseReset` crashes when run on Android x86.

**Comment by kristiandupont** [comment]
At this moment, it seems that calling `ALooper_PollAll` doesn't trigger updates on x86.

**Comment by fealebenpae** [comment]
Go go #564!

**Comment by fealebenpae** [comment]
This happens when the NDK that we build wrappers with is a different version than the one we built core with.
