### ISSUE TITLE
Unable to open a realm at path '/data/data/[package]/files/database.realm' Unsupported Realm file format version

### ISSUE THREAD

**Issue by atultiwari** [realm/realm-dotnet#879]
I created `.realm` file by importing CSV through Realm Browser (2.0.1). It's opening fine in browser itself. But when I tried to add it into assets (Both Android and iOS) of Xamarin Studio (v 6.1.1, Realm 0.78.1), while accessing the database I got error -
`Unsupported Realm file format version`

How can I work around this error. I can't create new realm from app itself, as my pre-populated database contain more than 30,000 rows and I couldn't find any tutorial which can teach me to import/update so many rows at runtime from my website's MySQL database (like in case of SQLite I used to do this with the help of JSON). If anyone can point me to any such tutorial that would be an additional help.

p.s. - I am completely new to all 3 - Xamarin, Mac and Realm (4 days to be specific), have worked in android studio just to learn basics.

Thanks
Regards,
Dr. Atul

**Comment by nirinchev** [comment]
Hi Dr. Atul,

Sorry for the hiccup you’ve experienced. Unfortunately, the Realm browser format is slightly ahead of the one used in Realm for .NET. In our next NuGet release, we’ll support the newer format, but we don’t have a good estimate when that will be ready. Until then, here are two possible workarounds:

- Use an older version of the Realm Browser. You can download the compatible [Realm Browser 1.0.2](https://github.com/realm/realm-browser-osx/releases/tag/1.0.2) from the releases feed.
- Alternatively, you can use the [nightly build](https://www.myget.org/gallery/realm-nightly) of Realm for .NET from myget. Keep in mind that, even though this build passes our automatic tests, it has not gone through the rigorous testing that our NuGet releases go through, so there might be some things that don’t work as expected.

Hope this helps. If you have any more questions, don’t hesitate to ask us 🙌

**Comment by atultiwari** [comment]
@nirinchev thank you for reply. Since Realm Browser has its limitations (like I couldn't find way to alter table structures, or rename/add new table in imported database), I am planning to create blank realm database on first run and then import all the 30000 rows. But, while doing so, I am facing hurdles, which I have asked in separate question [here](https://github.com/realm/realm-dotnet/issues/881), as it's a completely different approach. Please have a look at that.

Thanks.
