### ISSUE TITLE
Unrecognized transform root element: Weavers.

### ISSUE THREAD

**Issue by sharvari09** [realm/realm-dotnet#892]
> We LOVE to help with any issues or bug you have!
> 
> **Questions**: If you have questions about how to use Realm, please ask on [SO](http://stackoverflow.com/questions/ask?tags=realm) - we monitor the Realm tag.
> 
> **Feature Request**: Just fill in the first two sections below.
> 
> **Bugs**: To help you as fast as possible with an issue or bug please describe your issue and the steps you have taken to reproduce it in as many details as possible.
> 
> Thanks for helping us help you :-)
> 
> Remove this and above before submitting.
#### Goal

> What do you want to achieve?
#### Expected Results

> ?
#### Actual Results

>  E.g. full stack trace with exception
#### Steps & Code to Reproduce

> Describe your current debugging efforts.
#### Code Sample

``` csharp

> Your code here. Bigger samples should ideally be as separate Xamarin/Visual Studio project, 
> in gists/repositories or privately at help@realm.io)

```
#### Version of Realm and tooling

Realm version(s): ?

Xamarin/Visual Studio version: ?

Which operating system version and device: ?

**Comment by kristiandupont** [comment]
Hi @sharvari09, could you describe your problem to us? Do you get this error when trying to install Realm from NuGet?

**Comment by kristiandupont** [comment]
I'm closing this due to lack of details.
