### ISSUE TITLE
binding to Entry

### ISSUE THREAD

**Issue by amccorma** [realm/realm-dotnet#894]
<Entry Text="{Binding ItemDesc}" />

**Error: can not set value outside of a transaction.**

```
public class Page3 : ContentPage
	{
		public Page3()
		{
			using (var realm = Realms.Realm.GetInstance())
			{
				realm.Write(() =>
				{
					var obj = realm.CreateObject<Sample1>();
					obj.PeopleID = 10;
					obj.Text = "Sample Text";
				});
			}

			var data = Realms.Realm.GetInstance().All<Sample1>().First();
			this.BindingContext = data;

			var entry = new Entry();
			entry.SetBinding(Entry.TextProperty, "Text");

			this.Content = new StackLayout
			{
				Children =
				{
					entry
				}
			};
		}
	}
}

```

**Comment by nirinchev** [comment]
The problem stems from the fact that writes must happen in a write transaction, while data-binding relies on being able to simply set properties. While we plan on making it work out of the box (see #887), that is not ready yet. As a workaround, you can create a transaction [`Realm.BeginWrite`](https://realm.io/docs/xamarin/latest/api/class_realms_1_1_realm.html#ab80df0f96fea5684dcb720a5b9c640a9), e.g. in [`Page.OnAppearing`](https://developer.xamarin.com/api/member/Xamarin.Forms.Page.OnAppearing/) and commit it in [`Page.OnDisappearing`](https://developer.xamarin.com/api/member/Xamarin.Forms.Page.OnDisappearing()/). 

Alternatively, for MVVM-based solution, check out our [QuickJournal sample](https://github.com/realm/realm-dotnet/blob/master/examples/QuickJournal/QuickJournal/ViewModels/JournalEntryDetailsViewModel.cs).

I'll be closing this as a duplicate (#647), but if you have any issues or need further help, feel free to reopen it.
