### ISSUE TITLE
Showcase 3rd party libraries based on Realm

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-dotnet#904]
It would be convenient for our users to be able to browse 3rd party supplementary packages. Let's investigate where is the right place to create such a gallery.

**Comment by cbush** [comment]
We are revamping the Realm docs. We're not ignoring this issue -- we've read through every one of them, and we'll be sure to address this as part of our updates. We're closing the GitHub issues and creating new JIRA tickets to track the work at a high level.
