### ISSUE TITLE
Validation on [Required] properties

### ISSUE THREAD

**Issue by fealebenpae** [realm/realm-dotnet#912]
Based on #349 

- [x] Validate that only scalar reference type properties are decorated with `[Required]`
- [x] Setters on those properties should throw if the value is null

**Comment by nirinchev** [comment]
Is the first condition worded correctly? I would assume only **nullable** types can be decorated with `[Required]`

**Comment by fealebenpae** [comment]
@nirinchev: good catch, I tried to enhance the wording.

**Comment by nirinchev** [comment]
The second requirement is handled in native.
