### ISSUE TITLE
Change samples to build 32+64bit iOS

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#915]
You get the 32-bit warning _The Developer of this app needs to update it to improve its compatibility._ on launching our unit test runner and possibly other test apps, at least on the iOS simulator.

That was mentioned in the [Xcode 8.1 bulletin](https://releases.xamarin.com/technical-bulletin-xcode-8-1-gm/) from Xamarin.

We just need to change them to build i38x+x86_64 configs for Simulator.

It is not urgent, but our tests should be running realistic configs and our sample apps should avoid triggering warnings.

**Comment by nirinchev** [comment]
Haven't seen this in a while, so I believe we have fixed it along the way.
