### ISSUE TITLE
Feature Request: Realm.Xamarin support for LinkingObjects

### ISSUE THREAD

**Issue by SKMoss** [realm/realm-dotnet#922]
#### Goal

I use LinkingObjects in Realm.Swift.  I would like to move my project to Visual Studio for Mac or Visual Studio 2017 w/Xamarin.  

The quote below is no less true in Xamarin than Swift ;)

> Because manually synchronizing pairs of relationships is error prone, complex and duplicates information, Realm provides linking objects properties to represent these inverse relationships.

Realm.Xamarin Docs doesn't mention LinkingObjects so I'm assuming it isn't supported on Xamarin yet?  If not, is it planned?  When?  If it is and just not mentioned, can I get a code example, please?

#### Expected Results

umm.  Ability to use LinkingObjects in Realm.Xamarin

**Comment by fealebenpae** [comment]
Hey @SKMoss,

Realm for Xamarin doesn't support the `LinkingObjects` type yet, but it's tracked in our backlog: https://github.com/realm/realm-dotnet/issues/219. There isn't a timeline for when it'll be implemented, though.
