### ISSUE TITLE
Native linking errors with Xamarin Forms + iOS

### ISSUE THREAD

**Issue by mkuennek** [realm/realm-dotnet#935]
#### Goal

Build a Xamarin forms iOS project with Realm.

#### Expected Results

It builds sucessfully.

#### Actual Results

The build fails with some linking errors. The build output is attached:
[BuildOutput.txt](https://github.com/realm/realm-dotnet/files/605674/BuildOutput.txt)
Note that in this Build we had two PCL projects. Nevertheless, the problem can be reproduced with a single PCL, like described below. I already checked that the iOS project is referencing the correct assembly and not the dummy PCL one.

#### Steps & Code to Reproduce

The problem can be reproduced with a new Xamarin Forms app:

1. Create a new blank Xamarin Forms app with PCL
2. Update the Forms Nuget to the latest stable release
3. Add the Realm nuget to the PCL-, Android as well as iOS project
4. Build the iOS app targetting the iPhone Simulator

#### Version of Realm and tooling
Initially with 0.77.2 but was also tested with 0.80 resulting in the same error.

Xamarin/Visual Studio version: ?
Visual Studio 2015 Enterprise with Update 3
Latest stable version of Xamarin(should be Xamarin for Visual Studio 4.2.1.62)
The Mac is running the latest stable version of Xamarin iOS as well(should be 10.2.0.4)

Which operating system version and device: ?
iPhone Simulator(iPhone SE) with iOS 10.1

**Comment by fealebenpae** [comment]
Realm for Xamarin only supports iOS 7.1 and up, while the deployment target of your project is 6.0 - you can see this in the linker error messages.

**Comment by mkuennek** [comment]
You are right, should have seen that. Sorry for the inconvenience and thanks for the help!
