### ISSUE TITLE
Fix Realm.RealmChanged doc

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#936]
The API doc need fleshing out to explain the event fires for every object changed in a transaction.

Currently it says _Triggered when a realm has changed (i.e. a transaction was committed)_ which is misleading. 

Ideally it should also link to a sample.

**Comment by nirinchev** [comment]
I believe it shouldn't fire for every object in the transaction, just once/twice when advancing to a new version.
