### ISSUE TITLE
synchronization of live objects with Realm Object Server

### ISSUE THREAD

**Issue by raphaels17** [realm/realm-dotnet#965]
> **Feature Request**

#### Goal
I understand that having Embedded object database for mobile app with Realm Mobile Platform extensions  to allow synchronization of live objects with Realm Object Server is on his way.
Where can i track the progress and contribute ? I there any beta available ? can I bind safely with swift't solution meanwhile?

#### Expected Results

> same then swift.

#### Version of Realm and tooling
Realm version(s): 

Xamarin: Xamarin.Forms 2.3

Which operating system version and device:  Microsoft / iphone/ android

**Comment by fealebenpae** [comment]
Hey @raphaels17,

We're busy integrating the Realm Mobile Platform in the Realm for Xamarin SDK - you can use the issues here in the repository to track our progress.

**Comment by nirinchev** [comment]
And to answer your beta question - we don't have plans to distribute a beta version for sync, but the master branch *should* be stable enough to develop against. So if you are interested in testing our sync features, feel free to build the latest master and use that.
