### ISSUE TITLE
Deprecate CreateObject

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#998]
This may be an argument for killing off CreateObject, but also affects future attempts to implement inheritance, so I think is worth documenting.

From our [internal Slack](https://realmio.slack.com/archives/sync/p1481205489000055), _the effect of setting a primary key later than other fields is that those previous updates will not be redirected to the winning object in a conflict._

**Comment by bdash** [comment]
Why is this constraint something to expose to users? It's something that the binding should do internally.

**Comment by AndyDentFree** [comment]
We can't stop them doing ordered property setting, unless we completely remove `CreateObject`, because that's a two-stage init of creating a blank managed object and then user code setting properties.

**Comment by AndyDentFree** [comment]
We manage the order of property setting when they create an object in memory with `new MyRO {Name="fred", Age=99...` and pass that to our `Realm.Add()` (formerly `Realm.Manage`. Because, in that case, we have a single method which does property copying and is able to pick up the PK first.

**Comment by bdash** [comment]
There are ways to solve the problem without forcing users to be aware of implementation details like this. For instance, on objects with primary keys  we could buffer writes in memory (that is, without setting values on the underlying row) until the primary key property is set and only then populate the row.

**Comment by AndyDentFree** [comment]
I agree that _just coping_ maybe with buffered writes is more desirable in the longer term. 

However, we *will* be shipping a version of the Xamarin SDK which supports Synchronised Realms before there's time to add such a feature. I am also wary of adding more complexity into the base setters and getters as that could have performance implications when people are doing large data import loops.

It is more likely we would decide to just drop `CreateObject` altogether but it needs to go through a deprecation period first.

**Comment by bdash** [comment]
IMO we either need to make `CreateObject` do the right thing with sync or remove it. Leaving its current semantics in place guarantees that some users will use it to shoot themselves in the foot in a non-obvious and hard-to debug fashion. Documentation isn't sufficient to prevent that.

**Comment by nirinchev** [comment]
I've updated the title - deprecating it is significantly less work and definitely less error-prone, while keeping it around provides little benefit anymore. Combined with #1000, I think the right choice is to deprecate and then remove it.
